### ISSUE TITLE
[GL] TextureView format ignored on blits / glReadPixels

### ISSUE THREAD

**Issue by Valkirie** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#10]
#### Emulator _[Required]_
Yuzu

---
#### CPU/GPU _[Required]_
Intel(R) Core(TM) i5-1035G7
Intel(R) Iris(R) Plus Graphics

---
#### GPU Driver Version _[Required]_
27.20.100.9126

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_: OpenGL
**API Version** _(example DirectX 12)_: 5.1

---
#### Description _[Required]_
Calling BlitFramebuffer (and DSA friends) ignores the attached texture views format and seems to use the underlying texture format.

---
#### Screenshots _[Optional]_
The expected output is something like:
![image](https://user-images.githubusercontent.com/934757/103937466-13a4ab80-5129-11eb-9a43-b553a14ce042.png)
And what the driver is currently emitting:
![image](https://user-images.githubusercontent.com/934757/103937527-24edb800-5129-11eb-9292-c2f8515c8614.png)

**Comment by Valkirie** [comment]
Intel replicated the bug and reported it.

**Comment by estebanr863** [comment]
Hi Valkirie,

Please open a support ticket with Intel at [https://www.intel.com/content/www/us/en/support/contact-intel.html](https://www.intel.com/content/www/us/en/support/contact-intel.html), so your issue can be routed to the correct team supporting developers.
