### ISSUE TITLE
FINAL FANTASY X/X-2 HD Remaster - Texture & Crash

### ISSUE THREAD

**Issue by TakuCED** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#101]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

FINAL FANTASY X/X-2 HD Remaster

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-1035G7

### GPU Driver Version [Required]

- [x] 30.0.101.1121 (*latest*)
- [X] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Description and steps to reproduce [Required]

![FINAL FANTASY X 17_11_2021 19_24_17](https://user-images.githubusercontent.com/42077840/142262476-f909a24c-fe7e-4ca3-81fc-ea9084f444fc.png)

Initially everything works fine, after a while time (random) the textures turn black and then crash after X time without error.
Already had this problem with the old drivers.

### Device / Platform

GPD Win Max

### Save game

[FINAL FANTASY X&X-2 HD Remaster.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/7557200/FINAL.FANTASY.X.X-2.HD.Remaster.zip)
Documents\Square Enix

### Game custom logs

[CoreDump.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/7557215/CoreDump.zip)
\steamapps\common\FINAL FANTASY FFX&FFX-2 HD Remaster

I'm not sure if this.

**Comment by TakuCED** [comment]
Crash random with latest version 1191

**Comment by estebanr863** [comment]
Hi @mva94,

Do you own this game? If you do, can you please try to replicate it?

**Comment by estebanr863** [comment]
Hi @TakuCED,

Can you please run the [Intel SSU Tool](https://www.intel.com/content/www/us/en/support/articles/000057926/memory-and-storage.html) on your system and send us the result?

**Comment by estebanr863** [comment]
Hi @TakuCED,

Also, it there an estimated amount of time for the issue to happen? I'm trying to reproduce the issue on a TigerLake, but didn't see any issues after 30 minutes of play.

**Comment by TakuCED** [comment]
> Hi @TakuCED,
> 
> Also, it there an estimated amount of time for the issue to happen? I'm trying to reproduce the issue on a TigerLake, but didn't see any issues after 30 minutes of play.
[result-ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/7903421/result-ssu.txt)

Maybe the issue is only for 10th gen, I have still issue and I finished it on my desktop with GTX.

**Comment by estebanr863** [comment]
Hi @TakuCED,

After analyzing the coredump file you attached, I see that the error is caused by a Memory Access Violation (code 0xc0000005) from the app FFX.exe. This points to an issue on the app side and is sometimes caused by corrupted files.

Have you tried completely uninstalling the game and installing it again?

**Comment by TakuCED** [comment]
> 

Sorry for late, I have try uninstalling the gane and reinstalling, work fine I don't get issue two sessions 40 minutes.

I'm on driver 1340.

**Comment by IGCIT** [comment]
> > 
> 
> Sorry for late, I have try uninstalling the gane and reinstalling, work fine I don't get issue two sessions 40 minutes.
> 
> I'm on driver 1340.

can this be closed?
