### ISSUE TITLE
Assassin's creed origin bad performances 

### ISSUE THREAD

**Issue by mva94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#102]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Assassin's creed origin

### Game Platform [Required]

- [ ] Steam
- [X] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

I7 1195g7

### GPU Driver Version [Required]

- [ ] 30.0.101.1121 (*latest*)
- [X] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Description and steps to reproduce [Required]

Games run super well at 40-50 fps, however for some reasons it drop to 10-15 for with a lot of stutters without any obvious reason 
https://youtube.com/shorts/XnG7hM21RWM?feature=share

### Device / Platform

One x player

### Game Settings

1280×800 
Low preset

**Comment by estebanr863** [comment]
Hi @mva94,

Got the chance to test with the latest drivers?

**Comment by estebanr863** [comment]
Hi @mva94 can this be closed?

**Comment by estebanr863** [comment]
Hi @mva94, @IGCIT and @Valkirie,

Can this be closed?

**Comment by pacoa-kdbg** [comment]
@estebanr863 
This can not be closed yet, 
Already tested up to date drivers,
i7 1195G7 @ 35W TDP

1920 x 1200 with 70% resolution scaling, "Very low" settings (or lowest not sure the name) 
It averages ~22 FPS

**Comment by estebanr863** [comment]
Hi @pacoa-kdbg,

Are you using a handheld device? I ask because we are not seen this behaviour on the lastest drivers in our lab systems. And the main diference are the thermal contrains of the handheld devices.

**Comment by pacoa-kdbg** [comment]
@estebanr863 
Thanks for pointing that out,

Looks like the games uses all CPU resources so I just limited CPU freq to ~3.2GHz to allow the cooling solution to be effective
and now I get ~35 FPS
![image](https://user-images.githubusercontent.com/29181120/165399293-17758710-773d-4240-afb3-a6c8f9336aae.png)

**Comment by estebanr863** [comment]
@pacoa-kdbg 

I'm glad it helped! Please let @mva94 or @IGCIT know if this issues can be closed now.
