### ISSUE TITLE
Zoom Crash when Screen Sharing starts

### ISSUE THREAD

**Issue by Hyatice** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#103]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [ ] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Zoom

### Processor / Processor Number [Required]

1180G7

### GPU Driver Version [Required]

- [ ] 30.0.101.1121 (*latest*)
- [ ] 30.0.101.1069
- [X] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [X] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Description and steps to reproduce [Required]

Join or host a Zoom meeting. Begin a screen share or have someone else begin a screen share.

Happens ~50% of the time. I have not tested with the latest drivers due to other issues which prevent my external monitor(s) from working.

I have not tested without external monitors plugged in, in case that matters.

### Device / Platform

Dell Latitude Detachable 7320

**Comment by estebanr863** [comment]
Hi @Hyatice,

I tried to replicate this issue on a i7-1165G7 without success. Can you please install the latest drivers and try again?

**Comment by estebanr863** [comment]
Hi @IGCIT, can you please help try reproduce this issue?

**Comment by IGCIT** [comment]
> Hi @IGCIT, can you please help try reproduce this issue?

tested on gpd win 3 and gpd win max with and without an external display for both.
windows 11 and windows 10 21H2

i started a meeting on both
started and stopped multiple screen share with different options on both devices, with and without recording
no crashes, but i ll wait for @Hyatice test

**Comment by estebanr863** [comment]
Hi @Hyatice, did you had the chance to test this?

**Comment by Hyatice** [comment]
I believe that this issue is resolved, I have not had any unexplained crashes during zoom since upgrading to 1191; which is also what fixed the dual monitor issue I had before as well. Whatever secret sauce went into the "more desktop stability" part of that upgrade apparently did its job!
