### ISSUE TITLE
Trails of Cold Steel III - crash/freeze when fishing with MSAA

### ISSUE THREAD

**Issue by kalenjohnson** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#105]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

The Legend of Heroes: Trails of Cold Steel III

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7-1165G7

### GPU Driver Version [Required]

- [ ] 30.0.101.1121 (*latest*)
- [X] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [X] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [X] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/7583425/ssu.txt)

### Description and steps to reproduce [Required]

Game freezes/crashes when fishing in game and with MSAA turned on. 2x/4x/8x all result in a crash. Switching MSAA off or to FXAA allow the fishing game to finish. When fishing, as soon as you hook a fish, the game window freezes. Audio and inputs continue to work for 30-60 seconds before the game fully crashes with this error:
![image](https://user-images.githubusercontent.com/2036520/142914379-573b3a58-7766-44b2-8f04-9534bb31121c.png)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![Trails of Cold Steel 3 Configuration 11_22_2021 10_12_39 AM](https://user-images.githubusercontent.com/2036520/142914402-b094cf38-f62b-429a-8b46-c1901e2427c3.png)

### Crash dumps [Required]

[https://drive.google.com/file/d/1khcCBHodtSh-VlsFBGD9RlwnUFnZuuJD/view?usp=sharing](https://drive.google.com/file/d/1khcCBHodtSh-VlsFBGD9RlwnUFnZuuJD/view?usp=sharing)

**Comment by estebanr863** [comment]
Hi @kalenjohnson 

Can you provide a save game that get us to the fishing part?

**Comment by kalenjohnson** [comment]
Save games go in %USERPROFILE% \Saved Games\FALCOM\ed8_psv3

There are 3 saves, the 3rd should be right in front of a fishing spot

[ed8_psv3.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/8241773/ed8_psv3.zip)

**Comment by EstebanIntel** [comment]
Hi @kalenjohnson, unfortunately, due to the development team limited resources and needing to work on other higher priority game issues, this issue won't be fixed.
