### ISSUE TITLE
Forza Horizon 4: Severe slow down/performance regression with latest stable drivers.

### ISSUE THREAD

**Issue by Saracchini** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#108]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Forza Horizon 4

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel 1165g7

### GPU Driver Version [Required]

- [X] 30.0.101.1191 (*latest*)
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [X] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

SSU report anonimized: 
[fh4_intelSSU_1191.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/7763534/fh4_intelSSU_1191.txt)

### Description and steps to reproduce [Required]

- Start game as normally
- Game performance is as expected.
- Play for around 4,5 minutes, issue can happen earlier or later. Can be triggered earlier by jumping back and forward to in-game to car listings menus with large amount of items (photography challenges, AutoShow, My Garage).
- Frame rate starts to go down severely. Issue is quite pronounced in shopping menu (usually auto shop and car listing menus). In-world frame rate is also affected by a lesser amount.
- Issues observed: variable frame rate (from locked 30/60 to 25-50 oscillating quite inconsistently) . Frame rate in menus with car listings can go down to 10-15 fps. 

Seems to be a regression issue. Rolled back to driver version 1121 and the game can run for more than 3 hours without issues or frame rate issues. No changes on device TDP or GPU behavior where done. Device is running with factory settings.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Default settings given by the game, after first run.
Frame lock can be set either to 30 or 60. Issues are much more visible with 60 fps lock (in-game options).

Same settings runs without performance issues on 1121 driver version. 

### Device / Platform name

GPD Win3 1165g7 version

### Crash dumps [Required]

No crashs observed.

**Comment by Saracchini** [comment]
Issue persists in 1340 driver. It does not happen in 1121.

**Comment by Saracchini** [comment]
Gave a more careful testing. Slow-down seems to be caused by a significantly increased CPU usage with the newer drivers. With driver 1121 I was able to play the game with 15W TDP easily and reach constant 60fps with the Win3 set with power-saving settings (Windows Balanced mode, slider set to power saver). With newer drivers I have to use 25W in Edinburgh zone to reach 45-60fps, and CPU usage raises drastically. Note that during sttutering GPU usage falls down to 30-40% when the normal is be at 75-90%.

**Comment by Saracchini** [comment]
Update. How to trigger this issue consistently:
go to a "heavy region"(Edinburgh for instance). Open the pause menu and go to "Cars" tab and select "Horizon Promo & Car Collection". Fast scroll the car selection screen holding LB or RB (or the side buttons with the brand names) until you see the the fps counter lower. Close all menus and open it again. Repeat. Sometimes one cycle will not show the issue, but repeating the procedure does, which means as you play the game, it slows down when you go back and forward in menus.  
Scrolling across cars already shows a slow down which did not occur previously. 
 
At certain point the whole game starts to slow down heavily, and you can observe from the in-game GPU stats that usage falls to 30-40%, when the normal is 75-90%.

If you restart the game, it goes back to normal. 

I can repeat the process in 1121 driver and the issue never shows.

**Comment by Saracchini** [comment]
Issue persists with 1404 driver.

**Comment by estebanr863** [comment]
HI @Saracchini 

We were able to reproduce this issue and it has now been escalated to our driver development team. I just want to set the right expectation with you, as with the current workload, it may take from 3 to 6 months for a possible fix to be integrated into a release driver.

**Comment by Saracchini** [comment]
Issue persists with 1934 driver.

**Comment by Saracchini** [comment]
Issue persists with 1960 driver.

**Comment by Saracchini** [comment]
Issue persists with 1994 driver.

**Comment by Saracchini** [comment]
Issue seems to be solved in driver 3222. I need further testing, but I cannot reliably reproduce it anymore. A similar issue with Forza Horizons 5 Hot Wheels DLC rewards menu seems also to be solved.
