### ISSUE TITLE
Cod: Vanguard latency , texture burst and extrapolation logos 

### ISSUE THREAD

**Issue by mva94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#109]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Call of duty vanguard 

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [X] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

I7 1195g7

### GPU Driver Version [Required]

- [X] 30.0.101.1191 (*latest*)
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

![20220111_174132](https://user-images.githubusercontent.com/78859716/148986186-9b9d42df-2866-407a-bc84-6c6db56ec4d1.jpg)

### Description and steps to reproduce [Required]

Start the game
Go in online multiplayer 

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280×800

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Lowest with no fsr

### Device / Platform name

Oxp mini

### Crash dumps [Required]

No crash

**Comment by estebanr863** [comment]
Hi @mva94,

Was this issue seen on interlaced or progresive resolution? (800i vs 800p)

**Comment by estebanr863** [comment]
Hi @mva94,

Can you please explain what you mean by "extrapolation logos"?

**Comment by mva94** [comment]
@estebanr863 I meant this
![c3uc1ligtu281](https://user-images.githubusercontent.com/78859716/150192514-368237c4-8caf-4381-b0dc-7e436d5f27f0.png)


Keeps on popping up in game ( multi)
