### ISSUE TITLE
Assassins Creed Valhalla  Starts stuttering after 20 -25mins of gameplay. No heating issue runs smooth then stutter

### ISSUE THREAD

**Issue by nielo360** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#112]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Assassins Creed Valhalla

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

intel i7 1195g7

### GPU Driver Version [Required]

- [X] 30.0.101.1340 (*latest*)
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/8123528/ssu.txt)

### Description and steps to reproduce [Required]

Game runs excellent at 35-40fps at starting, Low settings & mixed settings
After 20-25 mins its starts to stutter during movement. and becomes unplayable. System is running fine.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280x800

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Low setting.

### Device / Platform name

Onexplayer mini 

### Crash dumps [Required]

There is no crash

**Comment by felipin58** [comment]
Hi Nielo360,

A possible fix for this issue has been included in the [latest driver version 30.0.101.3222](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html). Can you please test it and let us know?

**Comment by estebanr863** [comment]
Hi @nielo360,

Were you able to test the fix?

**Comment by estebanr863** [comment]
HI @IGCIT,

We are not seen this issue at our lab on the latest driver and @nielo360 is not responding. Can this be closed?
