### ISSUE TITLE
Chrono Cross [Radical Dreamers Edition][Steam] Memory Leak Crash

### ISSUE THREAD

**Issue by shinra358** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#118]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

CHRONOCROSS.exe; RADICALDREAMERS.exe

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7-1195g7

### GPU Driver Version [Required]

- [X] 30.0.101.1660 (*latest*)
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404
- [ ] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11
- [X] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

Report Date: Thursday, 07 April 2022
Report Time [hh:mm:ss]: 07:45:32 PM
Operating System: Microsoft Windows 10 Home 10.0.19044
IGCC Version: 1.100.3407.0
Language: en-US
Physical Memory: 15.78 GB 
Current Resolution: 1280x720

Processor: 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz
Processor Speed: 2918 MHz
GFX Driver Name: Intel® Iris® Xᵉ Graphics
Shader Version: 5.1
OpenCL* Version: 3.0
* Microsoft DirectX* *
Runtime Version: 12
Hardware-Supported Version: 12
Vendor ID: 8086
Device ID: 9A49
Device Revision: 03
GFX Driver Version: 30.0.101.1631
Dedicated RAM: 4 GB
Shared RAM: 8 GB
Max Supported Displays: 4
GFX Vulcan: 1.2.205
GFX GOP: 17.0.1070

* Devices connected to the Graphics Accelerator *

Active Displays: 2

* Digital Display 1 *

Display Name: Optoma 1080P
Display Type: Digital
Serial Number: Q7G9AAAAAC  
DDC2 Protocol: Supported
Gamma: 2.2
Connector Type: DisplayPort

Maximum Image Size
Horizontal - 0 inches
Vertical - 0 inches

Supported Modes
640 x 480 (60p Hz)
640 x 480 (67p Hz)
640 x 480 (72p Hz)
640 x 480 (75p Hz)
720 x 400 (70p Hz)
720 x 480 (60p Hz)
720 x 480 (60i Hz)
720 x 576 (50p Hz)
720 x 576 (50i Hz)
800 x 600 (56p Hz)
800 x 600 (60p Hz)
800 x 600 (72p Hz)
800 x 600 (75p Hz)
832 x 624 (75p Hz)
1024 x 768 (60p Hz)
1024 x 768 (70p Hz)
1024 x 768 (75p Hz)
1024 x 768 (120p Hz)
1152 x 870 (75p Hz)
1280 x 720 (50p Hz)
1280 x 720 (60p Hz)
1280 x 720 (120p Hz)
1280 x 800 (60p Hz)
1280 x 1024 (60p Hz)
1280 x 1024 (75p Hz)
1366 x 768 (60p Hz)
1400 x 1050 (60p Hz)
1440 x 900 (60p Hz)
1600 x 1200 (60p Hz)
1920 x 1080 (24p Hz)
1920 x 1080 (30p Hz)
1920 x 1080 (50i Hz)
1920 x 1080 (50p Hz)
1920 x 1080 (60p Hz)
1920 x 1080 (60i Hz)

Power Management Support
-

Raw EDID:
00 FF FF FF FF FF FF 00 3E 8D 0A 7A 03 03 00 00 
1D 1E 01 03 80 00 00 78 0A 94 FF A0 5C 55 8A 24 
16 50 5E BF EF 80 81 C0 81 00 81 80 90 40 A9 40 
95 00 81 FC 61 7C 02 3A 80 18 71 38 2D 40 58 2C 
45 00 00 00 00 00 00 1E 00 00 00 FF 00 51 37 47 
39 41 41 41 41 41 43 0A 20 20 00 00 00 FC 00 4F 
70 74 6F 6D 61 20 31 30 38 30 50 0A 00 00 00 FD 
00 18 79 0F 66 11 00 0A 20 20 20 20 20 20 01 49 

02 03 25 F2 4D 01 03 04 05 07 90 12 13 14 16 9F 
20 22 23 09 07 01 83 09 00 00 6A 03 0C 00 10 00 
38 28 20 80 00 02 3A 80 18 71 38 2D 40 58 2C 45 
00 00 00 00 00 00 1E 66 21 56 AA 51 00 1E 30 46 
8F 33 00 00 00 00 00 00 1E 01 1D 00 72 51 D0 1E 
20 6E 28 55 00 00 00 00 00 00 1E 01 1D 80 D0 72 
1C 16 20 10 2C 25 80 00 00 00 00 00 9E 8C 0A D0 
8A 20 E0 2D 10 10 3E 96 00 00 00 00 00 00 18 8B 

* Digital Display 2 *

Display Name: Built-In Display
Display Type: Digital
Serial Number: -
DDC2 Protocol: Supported
Gamma: 2.2
Connector Type: Built-In Display

Maximum Image Size
Horizontal - 2.76 inches
Vertical - 4.72 inches

Supported Modes
720 x 1280 (60p Hz)

Power Management Support
Active Off Mode Supported

Raw EDID:
00 FF FF FF FF FF FF 00 36 7F 01 00 01 00 00 00 
00 0C 01 03 A5 07 0C 78 2F 00 00 A0 57 49 9B 26 
10 48 4F 00 00 00 01 01 01 01 01 01 01 01 01 01 
01 01 01 01 01 01 D4 19 D0 78 20 00 20 50 28 10 
82 00 00 00 00 00 00 18 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 91 

* Other names and brands are the property of their respective owners.

### Description and steps to reproduce [Required]

Just play the game and walk 1 or 2 screens over.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

any

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Doesn't have much but viewing mode and resolution.

### Device / Platform name

GPD Win 3

### Crash dumps [Required]

None

### Save game

None, just start game and play as soon as you get control of your characters.

### Game custom logs

None

**Comment by Saracchini** [comment]
Can confirm it crashes in older drivers as well, but later. Usually mid battle, sometimes with "failed to load font" error.

**Comment by IntelSupport-Arun** [comment]
Hi @Saracchini, The issue has been verified on our side, and we are able to reproduce it. We will be working on a fix. I want to give you a heads up that the fix may take 3 to 6 months to be included.

**Comment by estebanr863** [comment]
Hi @Saracchini,

After debugging this issue, we found the root-cause to be on the app side. We then proceeded to escalate the issue to SquareEnix. They took some time to reply, but their official answer is that Intel GPUs are not supported for this game and they are not willing to invest time to fix any issue on this game when running on an Intel GPU.
