### ISSUE TITLE
Doom Eternal crash after 10-20 minutes

### ISSUE THREAD

**Issue by Valkirie** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#12]
#### Game _[Required]_
Doom Eternal

---
#### CPU _[Required]_
Intel(R) Core(TM) i5-1035G7

---
#### GPU Driver Version _[Required]_
Intel(R) Iris(R) Plus Graphics

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_: Vulkan
**API Version** _(example DirectX 12)_: 1.2.162

---
#### Windows Build Number _[Required]_
Windows 10 20H2

---
#### Description _[Required]_
Doom Eternal will crash after a random period of time going from 10 to 30 minutes.

**Comment by Valkirie** [comment]
Some users reported a drivers rollback to 8935 seems to have fixed the crash issue, with the ability to play for at least an hour.

**Comment by leoben2** [comment]
We're looking into this now

**Comment by leoben2** [comment]
we're getting this specific part in house this week, will report back soon.

**Comment by mva94** [comment]
@Valkirie seems not to crash anymore on the latest drivers on tigerlake.
Needs confirmation on Icelake though

**Comment by IGCIT** [comment]
@mva94 i can test this on icelake

**Comment by mva94** [comment]
@IGCIT nice let me know

**Comment by Valkirie** [comment]
> @IGCIT nice let me know

Please keep us posted :)

**Comment by IGCIT** [comment]
tested for 3 hours and yeah, crashes are gone

**Comment by leoben2** [comment]
noice!

**Comment by halljames** [comment]
Still crashes for me.

**Comment by Valkirie** [comment]
> Still crashes for me.

Please share details on your hardware.

**Comment by LesBoobies** [comment]
Does not launch at all after the latest DE update. 
Just black screen for a few seconds and quits to desktop

**Comment by IGCIT** [comment]
@LesBoobies 
i ve just update mine, it is working (bethesda launcher)

what is your hardware? driver version?
have you tried to reinstall the game?

**Comment by LesBoobies** [comment]
@IGCIT reinstalled twice. Tried on latest driver - 9316 and also tried 8935.
Gpd win max (i5-1035G7 / Iris Plus 940)
Problems occured right after update

**Comment by IGCIT** [comment]
@LesBoobies 
ok, we have the same hardware, so there is something else going on there
are you a member of gpd discord server? you could find more help there
