### ISSUE TITLE
Functionality Request - Undervolt Tiger Lake

### ISSUE THREAD

**Issue by Valkirie** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#13]
#### Description _[Required]_
**Unclewebb**, creator of Throttlestop, a commonly used solution to change TDP, Turbo Boost Ratio and Voltage [lately reported](https://www.techpowerup.com/forums/threads/throttlestop-on-tigerlake-u-i7-1165g7.275464/post-4405760) Intel has either blocked access to the FIVR controls or the FIVR used since the 4th Gen Haswell no longer exists in this design.

On portable device, undervolting can be extremely beneficial to reduce both temp and power consumption.

---
#### Functionality Request _[Required]_
Bring back FIVR controls over Tiger Lake CPU or communicate on how to get Throttlestop and similar tools compatible.

**Comment by estebanr863** [comment]
Hi @Valkirie,

Starting with TigerLake, the FIVR has changed, with several power gates now moved to the SoC. This means that the developer of Throttlestop or any other similar application will need to change their code to adapt to the new arquitecture.
