### ISSUE TITLE
Non-Game: External Monitors "Inactive" despite being detected in Device Manager on 30.0.101.1934

### ISSUE THREAD

**Issue by gmartins-henrique** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#144]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 11

### Processor / Processor Number [Required]

1195G7

### GPU Driver Version [Required]

- [X] 30.0.101.1934 (*latest*)
- [X] 30.0.101.1660
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404
- [X] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Other Windows build number

22000 (21H2)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/8604218/ssulog.txt)

### Description and steps to reproduce [Required]

Connected a monitor (Dell U2719DC) via USB-C to USB-C (DisplayPort over USB-C) and the monitor does not connect. This worked on 30.0.101.1660 and 30.0.101.1340, but is completely dead in 30.0.101.1934.

Monitors show up in Display Settings, but say they are inactive.
Monitors show up in Intel Graphics Control Panel, but say they are inactive.
Monitors show up in Device Manager
USB devices plugged into the monitor continue to work.

Rolling back to 30.0.101.1660/1340 resolved this issue.

Rolling back from 30.0.101.1934 to 30.0.101.1660 resolved the issue.
Upgrading from 30.0.101.1660 to 30.0.101.1934 broke it again.
Rolling back from 30.0.101.1934 to 30.0.101.1340 resolved the issue once more.
Upgrading from 30.0.101.1340 to 30.0.101.1934 broke it again.

Setting to second screen only did not work, It only showed on the built-in display

No combination of settings allowed any two monitors - or three, for that matter - (internal, or two external daisy-chained via DP 1.2) to work sim. For clarity: Removing the second monitor from the DP Chain did not resolve the original issue.

### Device / Platform

GPD Win 3 (1195G7)

### Crash dumps [Required]

No Crash

**Comment by gmartins-henrique** [comment]
To be clear, I have 2 USB-C hubs:
-A small one, with three ports: usb, hdmi, and usb-c PD; 
-A bigger one, with six ports: 2xusb, 2xhdmi, usb-c PD, and usb-c; 

On the smaller one, it works, normally, even using the built in screen, and the external monitor, and on the big one, it works ONLY on the buit-in screen, not on any of the two external monitors.

**Comment by estebanr863** [comment]
Hi @gmartins-henrique,

Can you please confirm if the issue happens when conecting the external monitor directly to your system (without using an external hub/adapter)?

**Comment by gmartins-henrique** [comment]
If you mean with a usb-c to hdmi cable, I don't have one. And the win3 has no hdmi in or out without and adapter.

**Comment by estebanr863** [comment]
@gmartins-henrique can you try using the USB-C to USB-C cable to conect the GPD Win3 directly to the Monitor with no Hubs?

**Comment by gmartins-henrique** [comment]
My monitors don't have usb-c ports sadly, so I can't test that out.

**Comment by estebanr863** [comment]
Hi @gmartins-henrique,

From our experience, your issue is probably caused by your USB-C Hub. Since these Hubs are manufactured by a lot of different companies, it’s basically impossible for us to certify which one work and which ones don’t. And the fact that one of your Hubs works as expected and the other doesn’t, is even stronger evidence.

I do understand your line of thought, that since the issue is only happening on newer drivers, it may be caused by the driver. However, the manufacturer of your Hub may have developed their product assuming that some feature of sub-system was working a certain way on the Intel driver. And if that feature or sub-system was changed, the manufacturer (who is not working with Intel) will need to adapt.

My only advise is for you to contact the manufacturer of the Hub for support.

**Comment by gmartins-henrique** [comment]
No problem, you can close the issue then.
