### ISSUE TITLE
Call of duty black ops 3 black background multiplayer/zombie mode and rendering issues

### ISSUE THREAD

**Issue by IGCIT** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#145]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Call of duty black ops 3

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7-1165g7

### GPU Driver Version [Required]

- [X] 30.0.101.1934 (*latest*)
- [ ] 30.0.101.1660
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404
- [ ] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/8606316/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Play a multiplayer match or a zombie match

once finished and you go back to menu, background will be black in both multiplayer and zombie mode

if you don't set `RestrictGraphicsOptions = "0"` in `...\Steam\steamapps\common\Call of Duty Black Ops III\players\config.ini`
the game will not render correctly with a lot of missing graphics

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

extra/high settings
no AA
No Subsurface scattering
No Order independent transparency

### Device / Platform name

gpd win 3

### Crash dumps [Required]

none

**Comment by estebanr863** [comment]
Hi @IGCIT,

We tested this report on 2 different Tiger Lake systems on our lab and couldn't reproduce it.

Can anyone else try to reproduce this issue?

**Comment by estebanr863** [comment]
Hi @IGCIT,

We tried to replacing the file you pointed us to with the one you uploaded. But we still haven’t been able to replicate the issue.  

Can anyone else reproduce this issue?

**Comment by IGCIT** [comment]
hi @estebanr863 , found it, it's game fault

it seems it is saving some "settings" in a config file (don't know which) instead of getting them at runtime and a driver change broke it because it was using its old, now wrong, settings.

on top of that, reinstalling didn't help because i realized steam was **not** deleting these config files on uninstall for unknown reasons...so i had to manually delete the whole game folder
