### ISSUE TITLE
PCSX2 (PS2 Emulator) Crashing when using the Vulkan backend on the latest drivers (Last working on driver 1191)

### ISSUE THREAD

**Issue by KingYozora** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#146]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

PCSX2

### Processor / Processor Number [Required]

1135G7

### GPU Driver Version [Required]

- [X] 30.0.101.1960 (*latest*)
- [ ] 30.0.101.1934
- [ ] 30.0.101.1660
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404
- [ ] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11
- [X] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

.

### Description and steps to reproduce [Required]

Like the title says.  Any games crash on the PS2 emulator when using Vulkan on all the newer drivers.  The last working drivers was 1191.  

### Device / Platform

GPD Win 3

### Crash dumps [Required]

.

**Comment by IGCIT** [comment]
hi, please understand that we cannot help with crashes in emulators, you should raise this issue to PCSX2 developers, then they can contact Intel or open an issue here if this is a driver bug, with more details.

**Comment by Saracchini** [comment]
I ran two nightly build versions (1.7.2252 and latest nightly 1.7.2746) which supported Vulkan on my Win3 (1165g7,  W11) using latest stable driver (1960). Both of them ran without crashing, with the later showing minor graphic glitches and the first running without any visible issues with default settings.
