### ISSUE TITLE
Dark souls 3 graphical glitches 

### ISSUE THREAD

**Issue by mva94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#147]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Dark souls 3

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

I7 1260p

### GPU Driver Version [Required]

- [X] 30.0.101.1994 (*latest*)
- [ ] 30.0.101.1960
- [ ] 30.0.101.1934
- [ ] 30.0.101.1660
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404
- [ ] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[dark_souls_3.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/8793037/dark_souls_3.txt)

### Description and steps to reproduce [Required]

Start the game 
Create a character 
Go to first mini boss 
Glitches happen everywhere 

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920*1200

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

1920*1200p
Medium preset
Fullscreen

### Device / Platform name

Oxp mini

### Crash dumps [Required]

No crash

**Comment by mva94** [comment]
Here is the video using 30.0.101.1994 :
https://youtube.com/shorts/SstSt6_FKCs?feature=share
On intel support utility I was using 30.0.101.1934 , though tried the latest three with same result: 
30.0.101.1994 
 30.0.101.1960 
30.0.101.1934

**Comment by IntelSupport-Arun** [comment]
https://user-images.githubusercontent.com/91881865/171920104-3217cac6-2eb7-4744-9652-6af4c47f4655.mp4

**Comment by IntelSupport-Arun** [comment]
Hi @mva94 , After reviewing your video link, we tried to reproduce your issue in our lab with the latest graphics driver 30.0.101.1994 but we were unable to duplicate the issue. Issue has been verified on multiple devices, and we have not been able to reproduce it, we suspect that the issue is specific to the device you are using. As you are experiencing issues with multiple graphics drivers, we suggest that you may contact your device manufacturer's support for a fix. Our issue verification has been captured. Please take a look.

https://user-images.githubusercontent.com/91881865/171920771-5b9f8342-2366-406d-8d44-0d690df29194.mp4

**Comment by IntelSupport-Rozilah** [comment]
Hi @mva94 , hope you take a look at the video and as my advice for you to contact your device manufacturer's support for a fix. will request to close the case if there are no other further questions.
