### ISSUE TITLE
Final Fantasy XV - Crash 

### ISSUE THREAD

**Issue by reiterizpie** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#15]
#### Game _[Required]_
Final Fantasy XV - Steam

---
#### CPU _[Required]_
Intel i5-1035g7

---
#### GPU Driver Version _[Required]_
27.20.100.9126
&
27.20.100.9168

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_:
**API Version** _(example DirectX 12)_:
Direct X11

---
#### Windows Build Number _[Required]_
OS Build #:19042.746
****
---
#### Description _[Required]_
When exploring, usually in a battle the game will freeze. I usually start in the desert area, I swing the camera around, I get in to an area where I can fight and I look for an enemy. It will likely crash shortly after that, occasionally crashes without entering battle. 

---
#### Steps To Reproduce _[Required]_
Go in to battle in the desert area and you will eventually get a freeze, I'm unsure if it's due to swinging the weapon or the game just crashes. This did not happen previously on older drivers. 

Triggering a crash may take a second battle. 

---
#### Screenshots _[Optional]_

---
#### Notes _[Optional]_
[Event_Viewer_-_FFVX_Crash.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/5831459/Event_Viewer_-_FFVX_Crash.txt)

**Comment by leoben2** [comment]
Looking into this now.

**Comment by reiterizpie** [comment]
A

> 
> 
> Looking into this now.

Awesome. This is also happening on the latest drivers. I added that to the post.

**Comment by leoben2** [comment]
we're getting this specific i5 part in house this week, hopefully will have more results by then.

**Comment by reiterizpie** [comment]
> we're getting this specific i5 part in house this week, hopefully will have more results by then.

Hey Leoben2, no rush but just checking to see if you guys had a chance to look into this issue yet.

**Comment by IGCIT** [comment]
issue caused by system settings, @reiterizpie confirmed it is now solved.
