### ISSUE TITLE
Kill La Kill If - Black/broken screen in fights and some character textures not appearing.

### ISSUE THREAD

**Issue by Red-Haze1** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#150]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Kill La Kill If

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7-1165g7

### GPU Driver Version [Required]

- [ ] 30.0.101.3109 (*latest*)
- [X] 30.0.101.1994
- [ ] 30.0.101.1960
- [X] 30.0.101.1934
- [ ] 30.0.101.1660
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404
- [ ] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [X] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[](url
[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/8942334/ssulog.txt)
)

### Description and steps to reproduce [Required]

Start the story mode. Character models aren’t always displayed during the cutscenes. When you get to the first fight, the screen either displays nothing or a static half rendered stage even though the game continues to run (moving and pressing buttons give sound effects and vibrations). 

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

All settings give the same results.

### Device / Platform name

gpd win 3

### Crash dumps [Required]

None

**Comment by IntelSupport-Rozilah** [comment]
hi @Red-Haze1,
The case has been verified on our side and we are able to reproduce it. We will be working on a fix. I want to give you a heads up that the fix may take 3 to 6 months to be included.

**Comment by Red-Haze1** [comment]
Hi. Just an update that the graphical and crash issues still persist up to today's 3790 driver.

**Comment by EstebanIntel** [comment]
Hi @Red-Haze1 , a possible fox for this issues is included in driver version [31.0.101.4146](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?). Can you please test it and let me know?

**Comment by EstebanIntel** [comment]
Hi @Red-Haze1, a possible fox for this issues is included in driver version [31.0.101.4146](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?). Can you please test it and let me know?

**Comment by Red-Haze1** [comment]
Thanks EstebanIntel. I've checked on my i7-1165g7 with the 31.0.101.4146 version driver and the game runs fine now.
