### ISSUE TITLE
Marvel's spiderman remastered bad framerate

### ISSUE THREAD

**Issue by pacoa-kdbg** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#153]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Marvel's Spiderman Remastered

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7 1195G7

### GPU Driver Version [Required]

- [X] 31.0.101.3222 / 31.0.101.2111 (*latest*)
- [ ] 30.0.101.3113
- [ ] 30.0.101.3109
- [ ] 30.0.101.1994
- [ ] 30.0.101.1960
- [ ] 30.0.101.1934
- [ ] 30.0.101.1660
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404
- [ ] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9353306/ssu.txt)

### Description and steps to reproduce [Required]

go in game

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

any

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Lowest

### Device / Platform name

onexplayer mini

### Crash dumps [Required]

https://drive.google.com/file/d/1ULQWtcvzZ1WA86T6jSI6sJPWOf6q5aC1/view?usp=sharing

**Comment by IntelSupport-Arun** [comment]
Hi @pacoa-kdbg ,

We are currently working on this, meantime please share the password for the crash dump to review the dump.

**Comment by pacoa-kdbg** [comment]
Hi @IntelSupport-Arun 
I should not share the dump key per IGCIT wiki 

Please either edit and show some documentation that it can be shared or just try to reproduce it, you just need to go in game to get it .

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/How-to-obtain-crash-dumps

**Comment by IGCIT** [comment]
@IntelSupport-Arun you should receive it internally

**Comment by IntelSupport-Arun** [comment]
Hi @pacoa-kdbg,
To narrow down the issue and better understand the frame drop rate, is it possible to share the video of the issue?

**Comment by IGCIT** [comment]
https://user-images.githubusercontent.com/76787191/185224756-d5249921-b68e-4df6-ae5f-dd387321be4d.mp4

settings change has no effect

**Comment by IntelSupport-Arun** [comment]
Hi @pacoa-kdbg,
We are verifying the issue on our side and soon will update you the observations

**Comment by IntelSupport-Arun** [comment]
Hi @pacoa-kdbg,
I have tested the game on our multiple platforms and The issue can be reproduced with the latest graphics driver version:  31.0.101.3222, but not with the latest internal driver.
As of the latest internal driver, no performance issues were observed, and I'll let you know when this fix will be included in the public driver release. 
Once it is available, please verify the issue and let us know your observations.
Also, I would like to inform you that, As per the [game requirements](https://store.steampowered.com/app/1817070/Marvels_SpiderMan_Remastered/), the minimum requirement for the game is NVIDIA GTX 950 or AMD Radeon RX 470 and
3D mark score of [AMD Radeon RX 470 is 3668](https://benchmarks.ul.com/hardware/gpu/AMD+Radeon+RX+470+review) and [NVIDIA GTX 950 score is 1900](https://benchmarks.ul.com/hardware/gpu/NVIDIA+GeForce+GTX+950+review). 
While the Intel Intel Iris Xe Graphics eligible((1195G7)) 3D mark score is 1370 , below the min. requirement. This may also cause the poor performance of the game.
Please stay tuned for our next update on the new driver release.

**Comment by pacoa-kdbg** [comment]
@IntelSupport-Arun 
Thanks, although, it is not on the recommended settings.
By using an AMD 5825U (vega 8) CPU I am able to achieve 30 FPS at 720p medium settings.
Similar performance should be achiavable on i7 1195G7

**Comment by IntelSupport-Arun** [comment]
Hi @pacoa-kdbg,
As mentioned earlier, 3D mark score of 1370 for Intel Iris Xe Graphics eligible ((1195G7)) does not reach the minimum requirements of the game, but not that far behind. To get the best performance of the game, we always recommend meeting the recommended requirements.
Once the new driver is officially released, please have a quick look at it and let us know what you find.
Please stay tuned for our next update.

**Comment by davidibi** [comment]
I have the same problem . Someone has edited a D3d12.dll file and the game runs well with same processor . Only it has another failure. You can’t take photos in different missions because the icon of the camera inside the game doesn’t turn green so you can’t follow further those missions

**Comment by IntelSupport-Arun** [comment]
Hi @pacoa-kdbg,
There is a new graphcis driver has been released [31.0.101.3413](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) and we have tested from our side and the issue not observing with the latest driver. Please give a try from your side and let me know the result.
If your issue got resolved with the latest driver please close this case.

**Comment by pacoa-kdbg** [comment]
Yes, seems like performance have been fixed.
Although there are some gfx issues here and there,will close this and open one dedicated to that during the week.
Thx
