### ISSUE TITLE
XeSS cant be used on Iris Xe (TGL) on Shadows of the Tomb Raider

### ISSUE THREAD

**Issue by pacoa-kdbg** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#157]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Shadows of the Tomb Raider

### Processor / Processor Number [Required]

i7 1195G7

### GPU Driver Version [Required]

- [ ] 31.0.101.3616 / 31.0.101.2111 (*latest*)
- [X] 31.0.101.3413 / 31.0.101.2111
- [ ] 31.0.101.3222 / 31.0.101.2111
- [ ] 30.0.101.3113
- [ ] 30.0.101.3109
- [ ] 30.0.101.1994
- [ ] 30.0.101.1960
- [ ] 30.0.101.1934
- [ ] 30.0.101.1660
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404
- [ ] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

![image](https://user-images.githubusercontent.com/29181120/192621290-0b03f4fa-db85-4169-8212-e9d7ec681aea.png)

### Description and steps to reproduce [Required]

Lauch the config utility of the game

### Device / Platform

onexplayer mini

### Crash dumps [Required]

no crash dumps

**Comment by estebanr863** [comment]
Hi @pacoa-kdbg,

For XeSS to be available, please use driver version [31.0.101.3430](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) or newer. Also, you need to update the game to the latest [patch released today](https://store.steampowered.com/news/app/750920/view/3272451439792050249).
