### ISSUE TITLE
Forza Horizon 5 (windows and steam version) crash on start (Arc A380)

### ISSUE THREAD

**Issue by Midiamp** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#158]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Forza Horizon 5

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

12700K

### GPU Driver Version [Required]

- [X] 31.0.101.3430 / 31.0.101.2111 (*latest*)
- [ ] 31.0.101.3616 / 31.0.101.2111
- [ ] 31.0.101.3413 / 31.0.101.2111
- [ ] 31.0.101.3222 / 31.0.101.2111
- [ ] 30.0.101.3113
- [ ] 30.0.101.3109
- [ ] 30.0.101.1994
- [ ] 30.0.101.1960
- [ ] 30.0.101.1934
- [ ] 30.0.101.1660
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404
- [ ] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Other Windows build number

Windows 11 25217

### Intel System Support Utility report

Operating System:	Microsoft Windows 11 Pro Insider Preview(10.0.25217 Build 25217)
Physical Memory (Installed):	32 GB
Processor:	12th Gen Intel(R) Core(TM) i7-12700KF
System Type:	x64-based PC
Total Installed Updates:	15 Updates - See Detailed View for more information
Display Adapter(s):	Intel(R) Arc(TM) A380 Graphics	31.0.101.3430
System Manufacturer:	Micro-Star International Co., Ltd.
System Model:	MAG B660 TOMAHAWK WIFI DDR4 (MS-7D41)
Network Adapter(s):	Bluetooth Device (Personal Area Network) #2	10.0.25217.1000
	Intel(R) Wi-Fi 6 AX201 160MHz	22.140.0.3
	Realtek Gaming 2.5GbE Family Controller #2	1125.8.515.2022
	TAP-ProtonVPN Windows Adapter V9	9.24.6.601
	Xbox Wireless Adapter for Windows	1.0.46.1
Disk(s):	ADATA SX8200PNP	291,66 GB (available)	10.0.25217.1000
	ADATA SX8200PNP	276,43 GB (available)	10.0.25217.1000
	Force MP500	160,94 GB (available)	10.0.25217.1000
	Samsung SSD 750 EVO 500GB	323,00 GB (available)	10.0.25217.1000
	TEAM T253X2001T	290,68 GB (available)	10.0.25217.1000
	WDC WD40EZAZ-00SF3B0	1,13 TB (available)	10.0.25217.1000
	WDC WD40EZRZ-00GXCB0	1,23 TB (available)	10.0.25217.1000
System Messages:	Included
Direct-X Diagnostics:	Included

### Description and steps to reproduce [Required]

Immediately crash to desktop upon launch.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

How can I attach screenshot when the game literally crash upon launch?

### Crash dumps

CrashReport
MEM_AVAILABLE Value="34212798464"
USERCONFIG_ID Value=""
AUDIO_ENGINE_INIT_RESULT Value="0"
AUDIO_ERROR_LOG Value=""
AUDIO_ERROR_COUNT Value="0"
AUDIO_API_ERROR_LOG Value=""
AUDIO_API_ERROR_COUNT Value="0"
UPTIME Value="0.000000"
UPTIME_RESUMED Value="0.000000"
TOTAL_UPTIME Value="0.000000"
UPTIME_DRIVING Value="0.000000"
RESUME_COUNT Value="0"
TOTAL_LAUNCHES Value="0"
MEM_UNKNOWN_CURRENT Value="0"
MEM_UNKNOWN_PEAK Value="0"
MEM_UNKNOWN_SUBCATEGORIES_CURRENT Value="0,0,0,0,0"
MEM_UNKNOWN_SUBCATEGORIES_PEAK Value="0,0,0,0,0"
MEM_GRAPHICS_CURRENT Value="0"
MEM_GRAPHICS_PEAK Value="0"
MEM_GRAPHICS_SUBCATEGORIES_CURRENT Value="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
MEM_GRAPHICS_SUBCATEGORIES_PEAK Value="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
MEM_GRAPHICSCACHE_CURRENT Value="0"
MEM_GRAPHICSCACHE_PEAK Value="0"
MEM_GRAPHICSCACHE_SUBCATEGORIES_CURRENT Value="0,0"
MEM_GRAPHICSCACHE_SUBCATEGORIES_PEAK Value="0,0"
MEM_FILECHUNK_CURRENT Value="0"
MEM_FILECHUNK_PEAK Value="0"
MEM_FILECHUNK_SUBCATEGORIES_CURRENT Value="0,0"
MEM_FILECHUNK_SUBCATEGORIES_PEAK Value="0,0"
MEM_TRACK_CURRENT Value="0"
MEM_TRACK_PEAK Value="0"
MEM_TRACK_SUBCATEGORIES_CURRENT Value="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
MEM_TRACK_SUBCATEGORIES_PEAK Value="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
MEM_CAR_CURRENT Value="0"
MEM_CAR_PEAK Value="0"
MEM_CAR_SUBCATEGORIES_CURRENT Value="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
MEM_CAR_SUBCATEGORIES_PEAK Value="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
MEM_CROWDS_CURRENT Value="0"
MEM_CROWDS_PEAK Value="0"
MEM_CROWDS_SUBCATEGORIES_CURRENT Value="0,0"
MEM_CROWDS_SUBCATEGORIES_PEAK Value="0,0"
MEM_AUDIO_CURRENT Value="0"
MEM_AUDIO_PEAK Value="0"
MEM_AUDIO_SUBCATEGORIES_CURRENT Value="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
MEM_AUDIO_SUBCATEGORIES_PEAK Value="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
MEM_LIVERY_CURRENT Value="0"
MEM_LIVERY_PEAK Value="0"
MEM_LIVERY_SUBCATEGORIES_CURRENT Value="0,0,0,0,0,0,0,0"
MEM_LIVERY_SUBCATEGORIES_PEAK Value="0,0,0,0,0,0,0,0"
MEM_POPCORNFX_CURRENT Value="0"
MEM_POPCORNFX_PEAK Value="0"
MEM_POPCORNFX_SUBCATEGORIES_CURRENT Value="0,0,0,0,0,0,0,0,0,0"
MEM_POPCORNFX_SUBCATEGORIES_PEAK Value="0,0,0,0,0,0,0,0,0,0"
MEM_UI_CURRENT Value="0"
MEM_UI_PEAK Value="0"
MEM_UI_SUBCATEGORIES_CURRENT Value="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
MEM_UI_SUBCATEGORIES_PEAK Value="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
MEM_DATABASE_CURRENT Value="0"
MEM_DATABASE_PEAK Value="0"
MEM_DATABASE_SUBCATEGORIES_CURRENT Value="0,0"
MEM_DATABASE_SUBCATEGORIES_PEAK Value="0,0"
MEM_GAME_CURRENT Value="0"
MEM_GAME_PEAK Value="0"
MEM_GAME_SUBCATEGORIES_CURRENT Value="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
MEM_GAME_SUBCATEGORIES_PEAK Value="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
MEM_HAVOK_CURRENT Value="0"
MEM_HAVOK_PEAK Value="0"
MEM_HAVOK_SUBCATEGORIES_CURRENT Value="0,0,0,0,0,0,0,0,0"
MEM_HAVOK_SUBCATEGORIES_PEAK Value="0,0,0,0,0,0,0,0,0"
MEM_NETWORK_CURRENT Value="0"
MEM_NETWORK_PEAK Value="0"
MEM_NETWORK_SUBCATEGORIES_CURRENT Value="0,0"
MEM_NETWORK_SUBCATEGORIES_PEAK Value="0,0"
MEM_ANIMATION_CURRENT Value="0"
MEM_ANIMATION_PEAK Value="0"
MEM_ANIMATION_SUBCATEGORIES_CURRENT Value="0,0,0,0,0,0,0,0,0,0"
MEM_ANIMATION_SUBCATEGORIES_PEAK Value="0,0,0,0,0,0,0,0,0,0"
MEM_GENERALSCENE_CURRENT Value="0"
MEM_GENERALSCENE_PEAK Value="0"
MEM_GENERALSCENE_SUBCATEGORIES_CURRENT Value="0,0,0,0,0,0,0,0,0,0,0,0"
MEM_GENERALSCENE_SUBCATEGORIES_PEAK Value="0,0,0,0,0,0,0,0,0,0,0,0"
MEM_SMALLPOOLPAGE_CURRENT Value="0"
MEM_SMALLPOOLPAGE_PEAK Value="0"
MEM_SMALLPOOLPAGE_SUBCATEGORIES_CURRENT Value="0,0"
MEM_SMALLPOOLPAGE_SUBCATEGORIES_PEAK Value="0,0"
MEM_ONESHOTBUFFERS_CURRENT Value="0"
MEM_ONESHOTBUFFERS_PEAK Value="0"
MEM_ONESHOTBUFFERS_SUBCATEGORIES_CURRENT Value="0,0"
MEM_ONESHOTBUFFERS_SUBCATEGORIES_PEAK Value="0,0"
REASON Value="Video card"
REASON_INFO Value="0xffffffff887a0020"
STACK_TRACE Value="0x0,0x0,"
VRAM_BUDGET Value="0"
VRAM_USED Value="0"
VIDEO_SHARED_BUDGET Value="0"
VIDEO_SHARED_USED Value="0"
DATE_TIME Value="20221009-08:36.34"
MEM_USED Value="1164701696"
MEM_LIMIT Value="34212798464"
OSVERSION Value="10.0.25217.1000"
GPU_DIAG Value="0x00000000"
D3D_HR_ERROR Value="0x887a0005"
LIVERY_TEXTURE_COUNTS Value="0,0,0,0,0,0,0,0,0"
CAR_TEXTURE_COUNTS Value="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
TRACK_TEXTURE_COUNTS Value="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
LSP_CORRELATION_ID Value="0x0000000000000000"
ROUTESPEC_ROUTE Value="0"
ROUTESPEC_UNIVERSE Value="0"
UI_SCENE Value=""
SKY_1 Value=""
SKY_2 Value=""
LAST_STATE_MACHINE_INSTANCE Value=""
LAST_STATE_MACHINE_STACK Value=""
TOD Value=""
WIND_INTENSITY Value="0.000000"
ATMOSPHERE_INTENSITY Value="0.000000"
ENVIRONMENTAL_INTENSITY Value="0.000000"
PRECIPITATION_INTENSITY Value="0.000000"
LIGHTNING_INTENSITY Value="0.000000"
STORM_INTENSITY Value="0.000000"
RICH_PRESENCE Value=""
LOCATION Value=""
ONLINE Value=""
PARTY_SIZE Value="0"
SEASON_INSTANCE Value="0"
PLAYER_CAR Value="0"
PLAYER_CAR_STATE Value=""
RACE_COUNT Value="0"
TRACK_ID Value=""
LAST_SERIALIZED_CHALLENGE_ID Value="0"
UserConfig_FramerateLimitId Value=""
UserConfig_VSyncEnabled Value=""
UserConfig_FullyApplied Value="0"
UserConfig_AnisotropyQualityId Value=""
UserConfig_ShadowQualityId Value=""
UserConfig_NightShadowsQualityId Value=""
UserConfig_MotionBlurAmountId Value=""
UserConfig_MotionBlurQualityId Value=""
UserConfig_EnvironmentTextureQualityId Value=""
UserConfig_EnvironmentGeometryQualityId Value=""
UserConfig_MSAAId Value=""
UserConfig_FXAAId Value=""
UserConfig_TAAId Value=""
UserConfig_SSAOId Value=""
UserConfig_ReflectionQualityId Value=""
UserConfig_CarLODQualityId Value=""
UserConfig_DeformableSnowQualityId Value=""
UserConfig_SSRQualityId Value=""
UserConfig_LensEffectsId Value=""
UserConfig_ShaderQualityId Value=""
UserConfig_ParticlesQualityId Value=""
UserConfig_DXRQuality Value=""
UserConfig_ShowFPSId Value=""
UserConfig_HDR Value=""
UserConfig_ResolutionWidth Value="0"
UserConfig_ResolutionHeight Value="0"
UserConfig_ResolutionScaling Value=""
UserConfig_VisualPreset Value=""
UserConfig_UsingTHPPreset Value="0"
THP_WinVer Value=""
THP_CPU0Name Value=""
THP_GPU0Name Value=""
THP_GPU0Description Value=""
THP_GPU0Driver Value=""
THP_THPBucket Value=""
BUILD Value="507426"
PLATFORM Value="PC_Steam"
FLAVOR Value="ReleaseFinal"
SANDBOX Value=""
CAM_POS Value="0.000000,0.000000,0.000000"
SESSION_ID Value=""
TAGS Value=""
SYSTEM_OS_VERSION Value=""
SYSTEM_HOSTING_OS_VERSION Value=""
SYSTEM_FAMILY Value=""
SYSTEM_FORM Value=""
SYSTEM_OS_NAME Value=""
SEASON Value=""
LAST_RAN_ACTION Value=""
LAST_RAN_CONDITION Value=""
CMS_SNAPSHOT Value=""
LAST_SERIALIZED_SAVE_STATE Value=""

### Game custom logs

[CrashReport.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9742856/CrashReport.zip)

**Comment by IntelSupport-Arun** [comment]
Hi @Midiamp ,
Can I ask you a quick question, which edition of the game are you playing? Standard, Premium, or Deluxe? Standard, Premium, or Deluxe?
The latest driver for Intel Arc A380 can be downloaded from the site [Intel Arc Graphics Windows DCH Driver](https://www.intel.com/content/www/us/en/download/726609/intel-arc-graphics-windows-dch-driver.html). Please confirms that you downloaded the driver from the same site?

**Comment by Midiamp** [comment]
Confirmed driver downloaded directly from Intel website and Forza horizon 5
premium edition on steam and standard edition on windows store as it comes
with PC Game Pass.

**Comment by IntelSupport-Arun** [comment]
Hi Midiamp,
Thank you for the confirmation. I will verify the issue on our side and let you know the update, please stay tuned.

**Comment by Midiamp** [comment]
I just updated to driver 3490. Still same issue, crash on startup. I triple
checked that I downloaded the driver from Intel Arc Graphics site and not
Intel Graphics site. What irritates me is that reviewers are showing Forza
Horizon 5 running fine on A750/770. I can only attribute the crash to using
Windows Insider dev channel, except that the game only crash on A380 and
not on A750/770.

**Comment by IntelSupport-Arun** [comment]
Hi @Midiamp , Thank you for the details. We are testing the issue and will update you on the status soon.

**Comment by IntelSupport-Arun** [comment]
Hi @Midiamp, Thank you for your patience. I have verified the issue on our side with both the latest driver 31.0.101.3490 and the old driver 31.0.101.3430, and both work fine. From our observation, we do not believe that the driver is causing the problem. For your reference, I have captured a video. 

https://user-images.githubusercontent.com/91881865/196412780-1777015d-b08e-44cd-87b8-b245d44c534c.mp4

Could you try below recommendation and let us know your updates:
 1. Could you re-install the game and see if the game can launch or not? Also, please make sure your system meets the minimum system requirement mentioned below:
![system Requirement](https://user-images.githubusercontent.com/91881865/196410594-a0017a48-512b-4f23-8344-ec8501c4743b.JPG)
2. Forza support site [Forza launch issues](https://support.forzamotorsport.net/hc/en-us/articles/360007593074-My-Game-is-Not-Launching-or-is-Crashing-on-PC) has some troubleshooting methods which may help you resolve the issue, you can try them and let us know how it goes.
