### ISSUE TITLE
Detroit Become Human (Silent crash)

### ISSUE THREAD

**Issue by thealgorithmc64** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#16]
#### Game

Detroit Become Human
---
#### CPU 

i7 1165g7
---
#### GPU Driver Version

9168 and earlier
---
#### Rendering API 

Vulkan

---
#### Windows Build Number
Windows 20H2

---
#### Description
Game gives a dialog box warning that it may not run due to unsupported driver, then exits back to desktop.
---
#### Steps To Reproduce _[Required]_

Run the game as normal.
---

**Comment by Valkirie** [comment]
Also reported on #30. Impacted SKUs:
- 1035G7
- 1160G7

**Comment by leoben2** [comment]
We have repro, and is under debug now.

**Comment by Valkirie** [comment]
Hey @leoben2, just a quick ping as this one was acknowledged late Feb.

**Comment by Valkirie** [comment]
Duplicate from #82, closing.
