### ISSUE TITLE
Throttle max VRAM speed while at idle on Windows desktop for high refresh ratio 4K monitors

### ISSUE THREAD

**Issue by BigNish7** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#161]
### Application [Required]

Windows desktop / idle GPU state

### Processor / Processor Number [Required]

AMD Ryzen 9 5950X

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Describe the feature [Required]

I noticed that my A770 VRAM is operating at max speed (2,000MHz) while at idle on the Windows Desktop. I have an ASUS VGVG28UQL1A 4K 144 Hz monitor and it is set to 144Hz on the desktop. I have installed the A770 card coming over from an AMD 6900XT. There was a toggle in the AMD Software Settings under the Display Tab (called Radeon FreeSync - Not Supported/Supported) which allowed the user to select a variable refresh rate panel. Once this toggle was switched on (i.e. FreeSync Supported), the VRAM speed of my 6900XT dropped from 2000MHz to just 16MHz and this had the additional benefit of keeping the card's overall idle temp down. 

It would be great if the Alchemist series of cards could throttle their VRAM speed while idle on the Windows desktop at a 144Hz, but I am not certain if this can be achieved in this first generation of cards.

**Comment by IntelSupport-Rozilah** [comment]
hi @BigNish7, 
thanks for contacting us, we will start to validate the issue and will update you soon, Stay tuned!

**Comment by IntelSupport-Rozilah** [comment]
hi @BigNish7, could you try this latest Beta driver version [31.0.101.3793](https://www.intel.com/content/www/us/en/download/729157/751349/intel-arc-graphics-windows-dch-driver-beta.html)  as well because there is a new fix for VRAM issue, let me know if it is fixed for you.

**Comment by BigNish7** [comment]
Happy to assist, and thank you for your reply. I can confirm that I have upgraded to the latest 31.0.101.3793 driver. I can also confirm that this Beta driver has fixed one VRAM issue, namely my VRAM was running slower than expected. It is now running at 2187.1 MHz as expected. Yay! 

However, I can also confirm that the VRAM is still running at full speed while at idle on the windows desktop. Below I have two images from HWiNFO, one from my A770 and one from my former Radeon RX 6900 XT. The data in both images show each GPU at idle on the desktop using the same VGVG28UQL1A 4K monitor operating at 144Hz. My A770 is showing the GPU Memory Clock as 2,187.1 MHz and the other from my 6900 XT shows its GPU Memory Clock at only 16MHz (down from the 2,000MHz it ran at full speed). 

As I understand it, there is is a 'dance' between the GPU VRAM and each monitor's VBLANK timing, pixel clock rate and the link speed between GPU and monitor combined with the VESA Coordinated Video Timings standard. If you do an online search for terms such as 'AMD high idle VRAM speed' you will see the issues AMD users had with this over many years. With some of the most recent AMD driver updates AMD finally fixed the issue for the 6000 series cards. Users had to select "FreeSync Supported' via a toggle switch on their AMD Software Setting app. Once this was selected, the VRAM speed dropped from 2,00MHz to 16MHz. 

Just to try something, I changed my monitor's refresh rate in Windows Settings from 144Hz down to 60Hz, but the VRAM speed did not change i.e. it was still at 2,187.1MHz. 

I am sorry for the very long reply and for mentioning a competitor's product, but it would be great (at least I think it would be great) if Intel's GPUs also had the ability to reduce VRAM speed when at idle on the windows desktop. However, I am realistic enough to appreciate that this feature may need to wait for a future generation of Intel GPUs.   

A770 HWiNFO image - GPU memory clock = 2,187.1MHz:
![image](https://user-images.githubusercontent.com/116610885/198550399-d310af5b-da5f-4e33-ad4b-d659094319f4.png)

AMD RX6900XT HWiNFO image - GPU memory clock (same monitor and 144Hz refresh rate) = 16MHz:
![image](https://user-images.githubusercontent.com/116610885/198550727-c215e360-806e-4f87-8e20-fdfeb3b5e1e0.png)

**Comment by IntelSupport-Rozilah** [comment]
hi @BigNish7,
Thanks so much for the information you provided, it is very clear enough. I believed your VG28UQL1A 4K monitor is meet the requirement and I will check internally if there is any implementation to drop down VRAM speed when idle. If no, then I will point this concern internally to improve the features. Stay tuned!

**Comment by BigNish7** [comment]
Thank you @IntelSupport-Rozilah. If you need any further information that I can provide, please feel free to ask. I think it would be technically very clever if Intel discrete GPUs were able to lower the memory clock at idle and it might also assist in lowering heat and being able to have a fan-off mode.

**Comment by IntelSupport-Rozilah** [comment]
hi @BigNish7,
can you please provide us with SSU for the system?, want to confirm which windows 11 version did you used.

**Comment by BigNish7** [comment]
Hi @IntelSupport-Rozilah. SSU .txt file attached. I trust that this is what you need. Please note my scan log was created on 28 Oct as I created it for an earlier issue. If you need a version that is more current, I would be happy to generate another log.

[System Support Log_BigNish7.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9927940/System.Support.Log_BigNish7.txt)

**Comment by IntelSupport-Rozilah** [comment]
hi @BigNish7, 
Thanks for the reply and this is enough for us to verify this issue. :)

**Comment by IntelSupport-Rozilah** [comment]
hi @BigNish7,
The case has been verified on our side and we are able to reproduce it with our configurations as below:
Processor:  AMD Ryzen 7 5800X 
Graphic Driver version: 31.0.101.3490 and 31.0.101.3793
We will be working on a fix. I want to give you a heads-up that the fix may take 3 to 6 months to be included.

**Comment by EugenHud** [comment]
hello,

also with me the memory clock remains at 2.187,7 Mhz in desktop mode

![Info](https://user-images.githubusercontent.com/118109598/202727820-2bf7abfd-e019-4592-94b4-54d925b79faa.jpg)

**Comment by CrafterLaughter** [comment]
I'm also never seeing my VRAM clock adjust it's clock frequency when idle on my A380 with driver 31.0.101.3802

![image](https://user-images.githubusercontent.com/23381273/204927032-507cb3a2-bbfc-4877-ac0b-c3cb4a3194d6.png)

**Comment by dcominottim** [comment]
I opened/closed the duplicate #199 because I have >30W of power usage in idle with an Arc 750 + AW2521HF (1080P 240Hz). Waiting for a fix, too.

**Comment by EugenHud** [comment]
with the latest driver, the problem remains that the memory clock does not go down in desktop mode.  
![speicher](https://user-images.githubusercontent.com/118109598/211192491-b5096fe0-f2bd-4a21-b752-0726685afbd5.jpg)

**Comment by RhanCandia** [comment]
I have the same problem with my system. Because of this high idle power usage my card is always at 55 deg celcius when idle.

![image](https://user-images.githubusercontent.com/7951366/220890534-f31954ba-3855-41a2-bb10-31fb1b1be365.png)

AMD R5 5600
MSI MAG B550M MORTAR WIFI
16Gb 3600
ASRock A750
Win 11 Pro

**Comment by EstebanIntel** [comment]
Hi @BigNish7, after consulting with our developer team, they confirmed this is an expected behavior for the Arc A-Series GPUs

**Comment by BigNish7** [comment]
Hi @EstebanIntel, thank you very much for your reply and sorry for my late response. Can you please clarify your response a little for me please? 

Does this mean that it will not be possible for the Arc A-Series generation of GPUs to slow/lower their memory clocks when the GPU is at idle on the Windows desktop in the future via either a driver or GPU firmware update? I appreciate that there are likely to be limitations to what is possible to achieve with 1st gen hardware, it's just I had hoped it was something that could have been achieved. However I recognise that my request is very 'niche'.

Even if it is not possible, I am still very pleased to have purchased a 1st gen Intel discrete GPU and am really enjoying it and receiving all the driver update goodness, albeit Arc Control still needs further development, but I am glad Intel is working on it.

**Comment by EstebanIntel** [comment]
@BigNish7, we have made some changes in the driver to keep the idle power as low as possible, with some limitations. You can read about on this thread #164. Specifically for the VRAM clock, the A-Series architecture don't support decreasing it, even when using adaptative sync. However, this may change for future Arc GPU products.

And we really appreciate all your tests and feedback!
