### ISSUE TITLE
Age of Empires 2 Definitive Edition - Main Menu Glitch

### ISSUE THREAD

**Issue by me-jterhorst** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#165]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Age of Empires 2 Definitive Edition

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 5950x

### Graphic Card [Required]

Intel Arc A770 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.3491 (*latest*)
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel Support.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9873918/Intel.Support.txt)

### Description and steps to reproduce [Required]

![image](https://user-images.githubusercontent.com/69008590/198143217-50782b21-0b49-470d-a1df-6401bb13c3b8.png)
The button text is halfway overlapped and can't be seen. Smaller Buttons in sub menues don't have any issues. 

The Game itself runs smoothly.  

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080, 2560x2880

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Happens regardless of the settings

### Crash dumps [Required]

-

**Comment by me-jterhorst** [comment]
Hi @IntelSupport-Arun 
I've tried 3490 first and then 3491 BETA to see if the issue was resolved with the updated driver.
Same Issue persisted.

**Comment by IntelSupport-Arun** [comment]
A fix for this issue is included with latest Beta driver version [31.0.101.3793](https://www.intel.com/content/www/us/en/download/729157/751349/intel-arc-graphics-windows-dch-driver-beta.html). Please Update your driver to this version and test it.

**Comment by me-jterhorst** [comment]
Hi @IntelSupport-Arun 
I tested your suggested driver and the issue is resolved. 
Thank you very much.
