### ISSUE TITLE
Suggest having options list in Menu Customization sub-screen in same order as they appear on Left Hand side of Arc Control

### ISSUE THREAD

**Issue by BigNish7** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#168]
### Application [Required]

Arc Control

### Processor / Processor Number [Required]

AMD Ryzen 9 5950X

### Graphic Card [Required]

Intel Arc A770

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Other (Please specify)

### Describe the feature [Required]

This request is only a minor alteration. I think it would align/look better if the options list in the Menu Customization sub-screen (from top to bottom) were in the same order as they appear on the Left Hand side of Arc Control. This means swapping the positions of 'Games' and 'Drivers' as they appear in the Menu Customization sub-screen.  

In the LH Side of Arc Control (from top to bottom) the options are listed as Drivers/Games/Performance/Studio. If the Menu Customization sub-screen icon is clicked, the item list (from top to bottom) are Games/Drivers/Performance/Studio i.e. the relative positions of the Games and Drivers options are reversed. 

I appreciate it is only a very minor issue, but I could not help myself :-). 

![image](https://user-images.githubusercontent.com/116610885/198820532-fd7812bd-862b-4d79-adc8-f3c2b2d7ab59.png)

**Comment by IntelSupport-Arun** [comment]
Hi @BigNish7,

We are working on your Enhancement Request and will update you soon.

**Comment by IntelSupport-Arun** [comment]
HI @BigNish7 ,
We always consider and appreciate suggestions for Intel Arc, and I would like to thank you for your interest and effort. Based on your request, I have also created an internal improvement request and passed it along to the concerted team. As a heads-up, it may take some time to get implemented depending on the severity and priority of the request. 

If you do not have any further questions, we can close this case.

**Comment by BigNish7** [comment]
Hi @IntelSupport-Arun. Thanks for the reply and kind words. Just happy to be part of the extended supporter team, and really appreciate that the suggestions are being read and considered. Happy for this case to be closed.
