### ISSUE TITLE
Horizon Zero Dawn (Early Crash, Slowdown)

### ISSUE THREAD

**Issue by thealgorithmc64** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#17]
#### Game

Horizon Zero Dawn (Latest patch)
---
#### CPU

i7 1165g7

---
#### GPU Driver Version 

9168 (And also earlier) But there was a very early version which seemed more reliable but with severe slowdown.

---
#### Rendering API

Vulkan

---
#### Windows Build Number _[Required]_

Windows 20H2
---
#### Description _[Required]_

Extremely slow loading at all times.   Usually crashes when attempting to get to game,  But at most it does sometimes get to the  beginning part of a game which has severe lag and pauses, then crashes.   The initial cutscene works just fine though.  Tried at various resolutions, and settings.
---
#### Steps To Reproduce

Run the game as normal.  Wait till shaders have finished compiling

**Comment by Valkirie** [comment]
Thanks for sharing !

**Comment by leoben2** [comment]
We know of this one, not sure we'll be able to prioritize soon since the game's min GPU requirement is around 4TFLOPS.

**Comment by leoben2** [comment]
Under debug.

**Comment by hididi31** [comment]
Just for motive engineers Intel. The games run well on AMD 4500u, 30 fps and this apu got only 1,1 t flops, the iris xe got 1,7 t flops 😆

**Comment by Valkirie** [comment]
> Just for motive engineers Intel. The games run well on AMD 4500u, 30 fps and this apu got only 1,1 t flops, the iris xe got 1,7 t flops 😆

Indeed, [game works great on AMD 4500U](https://www.youtube.com/watch?v=bvfblj5E634) that is no better than TGL 1165G7.
Hang on @leoben2 !

**Comment by IGCIT** [comment]
confirmed no more crashes

**Comment by estebanr863** [comment]
Hi @thealgorithmc64, can you please try this with the [latest drivers](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html)?

**Comment by KaeAlSa** [comment]
I'm not there original poster but I've played through all of horizon zero dawn and the expansion on my 1195 with no problems.
