### ISSUE TITLE
vikings wolves of midgard silent crash at launch

### ISSUE THREAD

**Issue by IGCIT** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#170]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

vikings - wolves of midgard

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i9-11900kb

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.3793 (*latest*)
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9895968/igcit_ssu.txt)

### Description and steps to reproduce [Required]

start the game from steam, it will run the game launcher
the game crashes when you select launch game, no window or error appears

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

none

**Comment by IntelSupport-Rozilah** [comment]
hi @IGCIT,
could you try this solution from [here](https://steamcommunity.com/app/404590/discussions/0/1479856439036730131/)?
let me know if its works for you

**Comment by IntelSupport-Rozilah** [comment]
hi @IGCIT,
Thanks for the reply and we will verify the issue ,stay tuned!

**Comment by IntelSupport-Rozilah** [comment]
hi @IGCIT,
The case has been verified on our side and we are able to reproduce it with our configurations as below:
Processor:  RLK i7-11700K and AMD Ryzen 7 5800X
Graphic Driver version:  31.0.101.3490, 31.0.101.3793, 31.0.101.1743, ci-master 12705mDCH-I and NVIDIA GeForce RTX 3060(31.0.15.2686).
We will be working on a fix. I want to give you a heads-up that the fix may take 3 to 6 months to be included.

**Comment by EstebanIntel** [comment]
Hi @IGCIT, a possible fox for this issues is included in driver version [31.0.101.4146](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?). Can you please test it and let me know?

**Comment by IGCIT** [comment]
did a clean install of 4146 but the game still crashes

**Comment by EstebanIntel** [comment]
@IGCIT, sorry for the confusion, as I mixed up the status of this issue with another issue. The real status for this on e that unfortunately, due to the development team limited resources and needing to work on other higher priority game issues, this issue won't be fixed.

**Comment by IGCIT** [comment]
fixed in 45xx drivers
