### ISSUE TITLE
XeSS settings not working/applying in Modern Warfare 2 2022 A770 16GB LE

### ISSUE THREAD

**Issue by Dayman556** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#171]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Call Of Duty: Modern Warfare 2 2022

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [X] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i9 9900K

### GPU Driver Version [Required]

- [X] 31.0.101.3790 / 31.0.101.2114 (*latest*)
- [ ] 31.0.101.3729 / 31.0.101.2114
- [ ] 31.0.101.3430 / 31.0.101.2111
- [ ] 31.0.101.3616 / 31.0.101.2111
- [ ] 31.0.101.3413 / 31.0.101.2111
- [ ] 31.0.101.3222 / 31.0.101.2111
- [ ] 30.0.101.3113
- [ ] 30.0.101.3109
- [ ] 30.0.101.1994
- [ ] 30.0.101.1960
- [ ] 30.0.101.1934
- [ ] 30.0.101.1660
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSUReportDayman.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9896294/SSUReportDayman.txt)

### Description and steps to reproduce [Required]

In the game Modern Warfare 2 the XeSS upscaling feature simply does not work - the game fails to apply the settings within the ingame menu.

I have included a youtube video for an example

https://www.youtube.com/watch?v=U-HfwIOYVmw

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1440x2560

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://user-images.githubusercontent.com/117031082/198890061-66e9da94-d935-419a-9fb1-bde5db8226a0.png)
![image](https://user-images.githubusercontent.com/117031082/198890066-2b427915-71c6-470b-b811-fc3be3c06c34.png)
![image](https://user-images.githubusercontent.com/117031082/198890074-7d306a87-e926-44e9-b0fa-ef4bcf6d9809.png)
![image](https://user-images.githubusercontent.com/117031082/198890080-9fac34c6-3872-4b4c-bd09-12a09aea3356.png)
![image](https://user-images.githubusercontent.com/117031082/198890087-4cb332a0-de6b-40c1-9c8f-129d124c5a0f.png)
![image](https://user-images.githubusercontent.com/117031082/198890095-53dd9675-bd5a-465d-a202-1e86194d9fda.png)

### Device / Platform name

weedu

**Comment by IGCIT** [comment]
Hi @Dayman556
please, next time, use the correct template to avoid confusion, this is an Arc issue

thanks :)

**Comment by IntelSupport-Rozilah** [comment]
hi @Dayman556 ,
Thanks for contacting Intel, just need confirmation here before we start to verify the issue, is the issue happening on both internal and Arc Intel graphic drivers because I saw the SSU detail on Arc A770?.

**Comment by Dayman556** [comment]
> hi @Dayman556 , Thanks for contacting Intel, just need confirmation here before we start to verify the issue, is the issue happening on both internal and Arc Intel graphic drivers because I saw the SSU detail on Arc A770?.

Hi @IntelSupport-Rozilah,

I have only tried with Arc drivers and on A770 16GB LE - tested on 101.3490, 101.3491 and 101.3493(latest beta). The game simply fails to apply the graphical settings for XeSS. I realise this may not be specifically be an intel driver issue rather than a game developer issue.

**Comment by IntelSupport-Rozilah** [comment]
hi @Dayman556, 
Just to inform you that this issue has already been reported internally and we are
working on it. I want to give you a heads-up that the fix may take 3 to 6 months to be included.

**Comment by IntelSupport-Rozilah** [comment]
hi @Dayman556,
can you confirm which edition of the game having the issue?
![image](https://user-images.githubusercontent.com/44628772/201011105-bda4b5ef-66e5-4500-9df7-6e4fcccdc0d8.png)

**Comment by IntelSupport-Arun** [comment]
Hi @Dayman556 , This issue was fixed by the game developer on the game patch from 11/09/22. Please update their game to the latest version to get the fix.

**Comment by IntelSupport-Rozilah** [comment]
hi @Dayman556, 
As follow up, did you have any change to try on the latest game patch?

**Comment by IntelSupport-Rozilah** [comment]
Hi @Dayman556, 
Please to inform that we are proceeding to close this case since there is no response from your side. If you require any further assistance please follow our suggestions and update your finding, then we will resume our support again. You may submit a new GitHub case if you have new questions and we are happy to assist you.

Hi @IGCIT,
please close the case since there is no further response.
