### ISSUE TITLE
Total War: Warhammer III color issue has returned in 3793.

### ISSUE THREAD

**Issue by Maniir** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#172]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Total War: Warhammer III

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

Xbox for PC Launcher

### Processor / Processor Number [Required]

Intel Core i9-11900K

### Graphic Card [Required]

Intel ARC A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.3793 (*latest*)
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9896749/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Run in-game 'battle benchmark'. Bright blue and teal color issues are hard to miss.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

High Preset

**Comment by IntelSupport-Arun** [comment]
Hi @Maniir ,

Could you provide the below details for further investigation:

1.  Could you provide a video or Screenshot of the issue for better understanding the issue
2.  Please provide the steps to reproduce the issue? What are the settings enabled in the game before launching the benchmark
3. Did you get any chance to test with another brand of Graphics card? or issue is specific to ARC 770 ?

**Comment by Maniir** [comment]
I should have attached photos, my mistake.

This is driver version 3490 which is working correctly: 
![3490 Working Screenshot](https://user-images.githubusercontent.com/46582102/199115339-265c7f0c-e365-4995-9f1c-266df772d67b.jpg)

Here is the glitched driver version 3793:
![3793 Glitch Screenshot](https://user-images.githubusercontent.com/46582102/199115412-4fdf334b-62ac-4aa0-a991-838568c3b27a.jpg)

And here are the settings I used:
![settings 1](https://user-images.githubusercontent.com/46582102/199115441-e5d4d2b2-cd38-400a-8fb5-fdad62ba5fd3.jpg)
![settings 2](https://user-images.githubusercontent.com/46582102/199115446-04ba72d8-2ce4-44de-97de-1e192b7fb8c0.jpg)

I also ran the game on my GTX 1080Ti and the glitches were _not_ present and it functioned correctly.

**Comment by Maniir** [comment]
And I should specify, this was tested with the built-in Battle Benchmark.

**Comment by IntelSupport-Arun** [comment]
Hi @Maniir ,

Thank you for the quick check and update.

Could you try a clean installation of the driver [31.0.101.3793](https://www.intel.com/content/www/us/en/download/729157/751349/intel-arc-graphics-windows-dch-driver-beta.html) y following the below screenshot and see the issue is still observing:
![1](https://user-images.githubusercontent.com/91881865/199188540-069617a1-67a4-4809-9bfe-ae07a8a78fe5.JPG)

**Comment by Maniir** [comment]
After a clean install the issue still persists. This same issue was present in pre-3490 drivers, but was fixed. It has now reappeared with 3793. 
![image](https://user-images.githubusercontent.com/46582102/199391130-4da83f21-8005-4ab9-8007-78328fdf8e78.png)

**Comment by IntelSupport-Arun** [comment]
Hi @Maniir ,

Thanks for the confirmation and update.
I will verify the issue on our side and let you know the further updates. Please stay tuned.

**Comment by IntelSupport-Arun** [comment]
Hi @Maniir ,
This issue has been already internally and our team is working on it. . I want to give you a heads-up that the fix may take 3 to 6 months to be included. Thank you.

**Comment by EstebanIntel** [comment]
Hi @Maniir, a possible fox for this issues is included in driver version [31.0.101.4146](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?). Can you please test it and let me know?

**Comment by Maniir** [comment]
It looks like it is indeed fixed with the current driver.
