### ISSUE TITLE
Same two Live Performance Monitoring Tiles appearing after monitor wakes up from sleep even though they had been turned off in Settings.

### ISSUE THREAD

**Issue by BigNish7** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#175]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 11 Pro  22H2  22621.755

### Processor / Processor Number [Required]

AMD Ryzen 9 5950X

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

- [X] 31.0.101.3793 (*latest*)
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Other Windows build number

22621.755

### Intel System Support Utility report

[System Support Log_BigNish7.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9947465/System.Support.Log_BigNish7.txt)

### Description and steps to reproduce [Required]

In Windows - System - Power - Screen and Sleep, I have set up my PC to enter sleep after 2 hour and my monitor to enter sleep after 25mins. I have noticed that after returning to my PC between when the monitor has gone to sleep but before the PC has gone to sleep i.e. between 25mins and 2 hours, Live Performance Monitoring in ARC Control displays two tiles (GPU Memory Utilization and GPU Memory Used) that I had previously turned off - refer image. If I click on the Settings button, Settings shows these two Tiles as being unchecked (i.e. do not display) in their respective check boxes.  

From doing a bit of experimenting, It seems this issue is based on how long the monitor is in its sleep state, rather than the time set to enter its sleep state. I tried various 'enter sleep state' times between 2 mins and 25 mins and then waking the monitor up almost immediately, but this did not result in the two rogue GPU Memory tiles appearing. However, if I left the monitor in its sleep state for around 15mins for different 'enter sleep state times', the two rogue GPU Memory tiles appeared after I woke the monitor up.

To stop them from being displayed I have to check and then uncheck their respective checkboxes. 

Image of ARC Control showing the two GPU based performance tiles, even though they have been turned off:
 
![image](https://user-images.githubusercontent.com/116610885/200209607-cce145d1-53a8-483c-99ea-943fbe6086fd.png)

### Device / Platform

N/A

### Crash dumps [Required, if applicable]

N/A. This issue doesi not result in a crash. It just re-displays two performance tiles I had turned off. 

### Application / Windows logs

N/A

**Comment by BigNish7** [comment]
I can also confirm that the two GPU Memory based Tiles reappear each time the monitor goes to sleep for around 15mins even though they had been switched off again in Settings and the PC has not gone to sleep or been rebooted.

**Comment by IntelSupport-Arun** [comment]
Hi @BigNish7 

For further verification of the issue we would like to know below information from your side:
1. Is the issue specific to GPU Memory Utilization and GPU Memory Used settings? what about the other settings?
2. Are you observing the issue when the system is in Hibernation or S4 mode?
3. Please try a clean installation of the graphics driver by selecting the below option and see if the issue is still observing
![1](https://user-images.githubusercontent.com/91881865/200302444-eb665db1-0ba6-4fe7-9c3e-16000592d3fa.JPG)

4. Did you get any chance to verify the issue with the previous driver [31.0.101.3490](https://www.intel.com/content/www/us/en/download/726609/intel-arc-graphics-windows-dch-driver.html)? If yes, please let me know the observations?
5. I would appreciate if you could provide clear steps of how the issue was reproduced so that we can follow the same steps and make sure we are on the same page.

**Comment by BigNish7** [comment]
Hi @IntelSupport-Arun. I will try to answer your questions as well as I can, and after some further investigating, I think that the issue is with Intel Arc Control version 1.0.4765.0, and is solved with version 1.57.4034.4. Now to your questions.

Q1. Is the issue specific to GPU Memory Utilization and GPU Memory Used settings? what about the other settings? 
A1. I can confirm that the issue is specific to GPU Memory Utilization and GPU Memory Used. It is only the Tiles for these two settings that reappear. The Tiles for the other settings stay off.

Q2. Are you observing the issue when the system is in Hibernation or S4 mode? 
A2. I am sorry but I can’t answer this question. I do not use Hibernation. However the issue occurs when the monitor/screen has been turned off via the Windows Power Setting, but my PC itself has not entered sleep.
 
![image](https://user-images.githubusercontent.com/116610885/200470805-0e99aa9e-7104-40d8-aae5-a375563b627c.png)

Q3. Please try a clean installation of the graphics driver by selecting the below option and see if the issue is still observing.
A3. Given this suggestion, I reinstalled the 3793.exe driver package, chose Customize and checked the Execute a clean installation button. The installation proceeded as normal, but on further investigation I found that while it had installed the 3793 driver, it had not installed the latest version of Intel Arc Control. I therefore had Driver Version 31.0.101.3793 installed but only Intel Arc Control Version 1.0.4765.0 installed. I also now believe these were the Versions I had installed when I first noticed this issue. 
![image](https://user-images.githubusercontent.com/116610885/200472524-4fcaa7e3-66cf-45d1-b980-ec43e7704eef.png)
   
I tried reinstalling the 3793.exe driver package and this time selected Repair and again Repair (refer images below). This however did not fix the driver version miss-match issue. I still had Driver Version 31.0.101.3793 with Intel Arc Version 1.0.4765.0. I don't know how or why 3793 installed correctly but Intel Arc Control version 1.57.4034.4 did not also install and replace 1.0.4765.0.

![image](https://user-images.githubusercontent.com/116610885/200472747-b1bb2df7-c356-464c-b4dc-bf60d30e2f87.png)

![image](https://user-images.githubusercontent.com/116610885/200472769-09330528-8fae-4343-a9b2-2e97bc6a756a.png)

At this point I used Display Driver Uninstaller (DDU) version 18.0.5.6 to remove the Intel Graphics Driver and Intel Arc Control so that I could start again from scratch. I then installed 3490 and confirmed I had Driver Version 31.0.101.3490 and Arc Control Version 1.0.4765.0 installed. I then checked if this combination had the rogue Tiles issue, and can confirm that they did have the issue (refer Q4). 

I then clicked on the 3793.exe and checked the Execute a clean installation, and was able this time to successfully install both Driver Version 31.0.101.3793 and Intel Arc Control Version 1.57.4034.4.

![image](https://user-images.githubusercontent.com/116610885/200473940-a23d45ce-38b0-4fd6-b099-ef4aaa10fa29.png)

I then tested for the issue, but this time when I woke the monitor up I noticed two information boxes appeared that I had never seen before. They were both labelled 'Device Changed' (refer image). They were only on the screen a short time and then both disappeared. 

![image](https://user-images.githubusercontent.com/116610885/200475090-693af11c-c9b0-4075-b922-c3d7d5a8f22b.png)

I then opened Arc Control to check on the Live Performance Monitoring Tiles, and am very pleased to report that they were as I had set them and no longer included either the GPU Memory Utilization and GPU Memory Used. The issue seems to have been solved with Intel Arc Control version 1.57.4034.4.

Q4. Did you get any chance to verify the issue with the previous driver [31.0.101.3490] If yes, please let me know the observations? 
A4. After Using DDU and doing a clean install of 3490 (along with Arc Control version 1.0.4765.0) I can confirm that 3490 does have this issue.

Q5. I would appreciate if you could provide clear steps of how the issue was reproduced so that we can follow the same steps and make sure we are on the same page.  
A5. Step 1. Under Windows 11 - Settings - Screen and Sleep, I have set Windows to turn my monitor off after 25mins and my PC to go to sleep after 2 hours. For the sake of testing, I shortened the time my monitor went to sleep to 3mins as this did not affect the issue and vastly sped up my testing.

![image](https://user-images.githubusercontent.com/116610885/200476180-95bdde55-2d0c-40f8-b41c-559495abea06.png)

Step 2. In Intel Arc Control under the Performance Tab, I found that 8 Live Performance Monitoring Tiles fit nicely in the window provided. If there are any more than 8 Tiles I have to scroll up and down to see all their values. I therefore chose the 8 Tiles I most wanted to see, and unchecked CPU Activity/Memory Utilization/GPU Memory Utilization/GPU Memory Used/VRAM Temperature/Render Activity and Media Activity Tiles using the Live Performance Monitoring - Settings sub-menu. This left the following 8 Tiles: GPU Voltage/GPU Clock/GPU Temperature/GPU Power/GPU Activity/VRAM Clock/VRAM Effective Frequency/Fan Speed being displayed in the Live Performance Monitoring window. 

Step 3. I closed Intel Arc Control and did not touch my PC but let it idle for the 3 minutes until Windows 11 turned off my monitor (ASUS TUF Gaming VG28UQL1A). 

Step 4. I still did not touch my PC and waited a further 15mins. My monitor remained off for the duration of the 15mins (but my PC was on the whole time). I then woke up my monitor by wiggling the mouse. 

Step 5, I opened Intel Arc Control and noticed that both the GPU Memory Utilization and GPU Memory Used Tiles were again being displayed in the Live Performance Monitoring window, even though there were both unchecked in Settings s per my original set-up. This only occurred if I waited approx. 15mins to wake up my monitor after Windows had turned it off. If I turned on the monitor on within a few seconds of it being turned off, the Live Performance Monitoring window showed only the 8 Tiles I had selected i.e. the two rogue Tiles did not reappear.

NOTE: During the above testing my PC had not entered a sleep state as 2 hrs (120mins) had not passed while my PC was not being used. I only waited the 3 mins for Windows to turn my monitor off and then a further 15mins before waking my monitor up.

As noted above, the two GPU Memory Utilization and GPU Memory Used Tiles only reappeared when I was using Arc Control Version 1.0.4765.0 (either with the 3490 and 3793 driver) but not Version 1.57.4034.4. Under 1.57.4034.4, I got the two short-lived messages 'Device Changed' messages, but the Live Performance Monitoring Tile were unchanged from the 8 I had selected.    

I sincerely trust the above reply assists you in replicating the issue. If you have any further requests for information from me, or if I have not been clear, please don't hesitate to ask for further info, and I will try to answer it as best as I can.

**Comment by IntelSupport-Arun** [comment]
Hi @BigNish7 ,

Thank you for the details investigation and quick reply to our questions.
Sorry for the confusion, In your comment, you mentioned that the issue has been resolved after installing the latest graphics driver version 31.0.101.3793, and Intel Arc Control version 1.57.4034.4? or are you still facing the issue?
Please confirm.

**Comment by IntelSupport-Arun** [comment]
Hi @BigNish7 ,
It happy to hear that the issue has been resolved by latest graphics driver version 31.0.101.3793, and Intel Arc Control version 1.57.4034.4.  
For your Overlay (Alt+O) issue we will further assist you in another GitHub thread.
If you are happy to close this issue please close it. Thank you.

**Comment by BigNish7** [comment]
Thank you @IntelSupport-Arun. Happy to close this issue. Thank you for the correspondence and your support.
