### ISSUE TITLE
Lighting bug making everything dark/black on Sonic Frontiers - Intel Arc A770 16GB

### ISSUE THREAD

**Issue by anto-lcd** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#178]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Sonic Frontiers

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-11400

### Graphic Card [Required]

Intel ARC A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.3793 (*latest*)
- [ ] 31.0.101.3491
- [X] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9965504/igcit_ssu.txt)

### Description and notes
When the weather is getting cloudy and/or rainy, all the ground and textures becomes dark/black (even when cinematics), making the game unplayable.
- This issue isn't happening in cyberspace levels, it only happens in the main open-zone world
- This issue is present on the latest official driver (3490) and the latest BETA driver (3793).

### Steps to reproduce
- Launch the game from Steam as usual
- Start a new game or continue one
- Wait for the weather to be cloudy and/or rainy

- NOTE : I know the game just released and this may be corrected in a future game update, but because I only saw people owning Intel Graphics Cards complaining about this lighting problem, I thought it was a good idea to report the issue here.

### Screenshots
![20221108205552_1](https://user-images.githubusercontent.com/61962757/200683359-808e8ec1-0d9b-47a2-931c-b3c326f978d4.jpg)
![20221108202438_1](https://user-images.githubusercontent.com/61962757/200683435-7cac832e-a013-49e4-bdbc-9568c867d8cb.jpg)
![20221108204739_1](https://user-images.githubusercontent.com/61962757/200683448-298e7b6a-c18d-42f0-a1ee-31daa79fbec7.jpg)
![20221108205411_1](https://user-images.githubusercontent.com/61962757/200683481-5d48e11d-4d71-4b1f-bf5b-2f85b203abf0.jpg)

As you can see on the last screenshot, the game looks fine when the weather is clear, but shadows are still very saturated.
There's also a graphical glitch with a vertical black bar on the second screenshot.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Everything set on High, 60 FPS, V-Sync enabled

### Device / Platform name

iiyama G-Master GE2788HS

**Comment by IntelSupport-Arun** [comment]
Hi @adancingmilk ,
Thank you for contacting us.
This issue has been already reported internally and our team is working on it.  I want to give you a heads-up that the fix may take 3 to 6 months to be included. Thank you.

**Comment by EstebanIntel** [comment]
Hi @anto-lcd, a possible fox for this issues is included in driver version [31.0.101.4146](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?). Can you please test it and let me know?

**Comment by EstebanIntel** [comment]
Hi @anto-lcd did you had the chance to test the fix?

**Comment by anto-lcd** [comment]
Hi @EstebanIntel, I confirm that the problem is fixed since Driver 4146 !
