### ISSUE TITLE
Beyond : Two souls (Slowdown)

### ISSUE THREAD

**Issue by thealgorithmc64** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#18]
#### Game 

Beyond : Two souls

---
#### CPU

i7 1165g7 (Intel XE and 16gb ram)

---
#### GPU Driver Version

9168 (Occurs also before)

---
#### Rendering API _[Required]_

DirectX (Not sure which version)

---
#### Windows Build Number

Windows 20h2

---
#### Description

Runs extremely slow regardless of settings, resolution or windowed/bordered/fullscreen mode.
Should not be the case as the game can run well at >30fps on even a gpd win 2..  Frame rates are sub20fps mainly dipping into single digit numbers sometimes.

---
#### Steps To Reproduce

Just run the game

**Comment by leoben2** [comment]
Going to look at this now.

**Comment by leoben2** [comment]
Reproduced, bug filed, will keep you posted!

**Comment by thealgorithmc64** [comment]
This game has been fixed in recent driver. I tested it on latest as of now

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mva94** [comment]
@thealgorithmc64 happy to close it then, let me know if you see regression or whatsoever with newer drivers as we can always reopen it

**Comment by thealgorithmc64** [comment]
Apologies.  I had tested it on two laptops with tigerlake chipsets (i7 1165g7 and i5 1135g7) and these worked fine in the latest driver.. However upon testing it on the win3, there is still the slowdown issue (though no more purple flickering). 

Could be resolution/portrait oriented issue? though on icelake and win max it works fine
