### ISSUE TITLE
Frequent crashes and low FPS menu in Apex Legends

### ISSUE THREAD

**Issue by bvhari** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#181]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Apex Legends

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 5800X3D

### Graphic Card [Required]

Intel Arc A770 16 GB

### GPU Driver Version [Required]

- [X] 31.0.101.3793 (*latest*)
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [X] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9978782/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Game crashes most of the time when entering a match[anytime after leaving the lobby] and after leaving a match[after clicking Return to lobby]. This happens in BR, Arenas, and Firing range. However, during a match, the game is mostly stable.

There is an additional issue where the menu runs at very low FPS. However, 2 specific submenus run normally: Legend skin selection and Legend emote selection. There is also a noticeable stutter when opening some of the menus involved while in a match[eg: Loba's Black Market boutique, death box].

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![apex_video_settings_1](https://user-images.githubusercontent.com/82035780/201042110-207e5825-ad02-493e-a807-e79f9e82044f.png)
![apex_video_settings_2](https://user-images.githubusercontent.com/82035780/201042146-a70721fd-8b83-4bb2-9851-95f777cb8f21.png)

### Crash dumps [Required, if applicable]

[apex_legends_dmp.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9978933/apex_legends_dmp.zip)

**Comment by IntelSupport-Arun** [comment]
Hi @bvhari ,

I would like to know below details from your side for further verification:
1.  You have disabled all the settings under Advanced Game Settings, such as V-sync, Adaptive Resolution, Anti-aliasing, etc. Could you tell me if the crash and low FPS issue only occurs when these settings are disabled or if you notice it even when these settings are enabled. Could you clarify?
2. Also, may I know the status of the Resizable BAR in BIOS?
3. Would you able to verify the issue on Win 11 11 22H2 or 22H1?

**Comment by IntelSupport-Arun** [comment]
Hi @bvhari ,

Could you provide the details we requested for further investigation?

**Comment by bvhari** [comment]
1. Tried changing the settings. No difference. However the latest game update might have fixed the crash upon match entry. The crash upon match exit remains but is now slightly less frequent.
2. Resizable BAR is enabled in BIOS
3. This is not feasible, unfortunately
4. https://user-images.githubusercontent.com/82035780/201950409-87a4ee5b-60a5-4dfc-8e30-899796eda426.mp4

**Comment by IntelSupport-Arun** [comment]
Hi @bvhari ,

We tested the issue in our lab and were able to reproduce it. 

Although we are not experiencing game crash issues, we are experiencing performance issues.

As a result of the observation, we filed an internal bug and escalated it to the next level for further investigation.e.

I want to give you a heads-up that the fix may take 3 to 6 months to be included. So please stay tuned.

**Comment by bvhari** [comment]
Hi,
The issues are mostly solved as of game version 3.0.26.26 and driver version 31.0.101.4125.
Hence closing this issue.

Thank you for the support.
