### ISSUE TITLE
Dual Univers missing textures Intel Arc a770 16GB

### ISSUE THREAD

**Issue by EugenHud** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#183]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Dual Univers

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

novaquark Launcher

### Processor / Processor Number [Required]

AMD Ryzen 5 5600X 6-Core Processor             

### Graphic Card [Required]

Intel Arc a770 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.3793 (*latest*)
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [X] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Other Windows build number

19044 (21H2)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9997130/igcit_ssu.txt)

### Description and steps to reproduce [Required]

When I start the game it tells me that the graphics card has less than 1024 MB of memory and in the game itself I am missing voxel textures. 

After a while textures are loaded, but then they are the wrong / or arbitrary ones. 

![dualuniverse_2022-11-12_15h28m52s](https://user-images.githubusercontent.com/118109598/201520932-c458d654-afdf-4af7-a172-0e9c1b16a2cf.png)
![dualuniverse_2022-11-12_16h17m58s](https://user-images.githubusercontent.com/118109598/201520936-a44be815-780e-4dff-80ae-c85dd48ae273.png)
![dualuniverse_2022-11-13_12h38m30s](https://user-images.githubusercontent.com/118109598/201520942-34f24415-a08b-48e8-9d66-ce7ab0b301b2.png)
![dualuniverse_2022-11-13_12h38m58s](https://user-images.githubusercontent.com/118109598/201520947-21c4395d-c6ed-4009-afe3-6727ab329df3.png)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![dualuniverse_2022-11-13_12h59m55s](https://user-images.githubusercontent.com/118109598/201520640-86ef3075-3ec3-4a3e-b646-e3648e9fcf72.png)

### Device / Platform name

Windowes 10

**Comment by IntelSupport-Arun** [comment]
Hi @EugenHud ,

For further investigation we would like to know below information from your side:
1. Did you able to check the issue on other graphics card brand? os issue is specific to ARC ?
2. Is issue is specific to Win 10 21H2(19044 ) or any chance to repo the issue on Win 11?
3. May I know the status of the Resizable Bar in BIOS, option is enabled or not?
4. What is the current VRAM size in OS, can you go and check "Settings > System > Display > Advanced display>Display adapter properties for Display"
5. Please confirm the VRAM size in BIOS side aswell

**Comment by EugenHud** [comment]
Hi @IntelSupport-Arun 

1.  it only affects the Arc a770 graphics card , previously had an AMD Vega64 in it , it did not have this problem
2. I can't say anything about win 11 since I don't have that installed.
3.  Resizable Bar is enabeld
4. 
![GPU](https://user-images.githubusercontent.com/118109598/201660220-827d7c25-92fb-4e0c-ae01-d9d47a91899c.gif)
![GPU1](https://user-images.githubusercontent.com/118109598/201660228-1163d295-911e-4d6f-a0a1-4649599ad253.gif)
[DESKTOP.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10002920/DESKTOP.txt)

**Comment by IntelSupport-Arun** [comment]
Hi @EugenHud ,

Thank you for the details. I will verify the issue on our side and will you the observations. Stay tuned.

**Comment by IntelSupport-Arun** [comment]
Hi @EugenHud  ,
There is a new driver has been released [ 31.0.101.3802](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html?wapkw=arc). Could you update the driver and let me know the observations.

**Comment by EugenHud** [comment]
Hello,
yes I have seen it with the new driver.

Unfortunately the problem remains :( . 

But thanks for the tip.

Also the problem that the memory clock does not go down as in the other post remains.

**Comment by IntelSupport-Arun** [comment]
Hi @EugenHud , Thank you for the update. I will verify the issue on our side and confirm. Please stay tuned.

**Comment by IntelSupport-Arun** [comment]
Hi @EugenHud , I've already purchased the game with one month's game time from steam and linked the steam account to Novaquark.

Upon launching the game after entering credentials, the game throws an error stating that game time is not available. 

Did you encounter such an issue before? Do you have any recommendations if yes

**Comment by EugenHud** [comment]
Yes the error is known .
Mostly the linking is not succeeded why ever, so link again .

Best to look there on the HP whether the game time is "active" (you can see at MyProducts).

Maybe it also works if you use the launcher from the HP .

I can also send them game time (still have some through funding), but I would have to know the ingame name.


Normally, the error should also be present in the demo. 
The demo is not limited in time, only there will be reset every 2 weeks.

**Comment by IntelSupport-Rozilah** [comment]
hi @EugenHud,
Just to inform you that currently, we having a login issue that couldn't redeem game time for this game. I have submitted a ticket to the technical support of Dual Universe for assisting us with the login issue.  Please expect a delay in response and will update you once this login issue is resolved. Stay tuned!

**Comment by EugenHud** [comment]
small update, today the game has apparently the voxels with the correct textures apparently worked.
Whether this is now the new driver in conjunction with DXVK no idea

**Comment by IntelSupport-Arun** [comment]
Hi @EugenHud ,
 Thank you for sharing the update.
Our issue regarding the game purchase is still not resolved yet and we are working with the Novaquark team.
May I know did you verify the issue latest Beta Driver [31.0.101.3959](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html)?

**Comment by EugenHud** [comment]
hi@IntelSupport-Arun,

The interesting thing is that in some places the right textures are really loaded. Unfortunately, I can hardly really understand when the wrong and when the right ones are loaded.

At one login I was in a building and the wrong ones were loaded, at the next time the right ones were loaded.

I have Beta Driver [31.0.101.3959] Installed.

**Comment by IntelSupport-Arun** [comment]
Hi @EugenHud , 
Thank you for the update.
Both Steam and DU support failed to help me resolve the login issue. Though I purchased the game from Steam, my DU account shows no product and no game time. Despite raising the same concerns with the respective teams, I have not heard anything back. 
![DU_Account Details](https://user-images.githubusercontent.com/91881865/207788203-ad66176f-c07d-492a-94a2-d9e8ab351095.JPG) 
![DU_Steam_Account_Linked](https://user-images.githubusercontent.com/91881865/207789056-d91a9979-0824-4388-bd40-8266725bb5fd.JPG)

I keep chasing the support and will update you if any good news from them.
Same time, there is another latest Beta driver has been released [31.0.101.3975](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html), If you see any improvements with this driver, please let me know.

**Comment by EugenHud** [comment]
Hello,

I just send them to the account playtime in the form of DACs

can convert them to playtime under DACs.

Don't worry, the playtime was still from my "donation".

I haven't tested the new driver yet, will probably do it on Saturday or Sunday then.

**Comment by EugenHud** [comment]
Hello,

have test the driver.

After installing the driver, the correct textures were loaded for the voxels.
Thought it was now solved the problem.

However, the next day this problem was there again.

But now I have noticed the following. After installing the driver I have deleted the game cache, when starting the next day I have not done that.
When looking for the cause of this, I cleared the game cache again and the correct textures were loaded again.

Greetings

**Comment by IntelSupport-Arun** [comment]
Hi @EugenHud ,
Thank you so much for sharing the game time and now I can play the game. 
I started verifying the issue AMD Ryzen 7 5800x with the latest graphics driver [31.0.101.3975](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html) and so far I have not experienced any kind of texture missing. I would appreciate it if you could send me the latest issue screenshot and other details, such as the game stage where the issue occurs, so we can verify the issue and further debug it.

**Comment by EugenHud** [comment]
They have also become really less.

Had to start the game several times to get this error again until it was back.

Recorded the error.

First video without this texture error

https://vimeo.com/782656530

Second video where this texture error occurs.

https://vimeo.com/782657122

Even with the new driver the error is not there all the time, it was quite different with the previous drivers. 
I had it there all the time.

**Comment by IntelSupport-Arun** [comment]
Hi @EugenHud ,
I appreciate the video because it helps me understand the issue better.

I have been playing the game for the last two days and never encountered the issue shown in your videos. 

I have verified the issue with the latest graphics driver [31.0.101.3975](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html) and also tested with multiple internal drivers(Not release public) ,both have no issues.

As you said, it may be intermittent and it has been improved with the latest graphics driver [31.0.101.3975](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html).

As we are unable to reproduce the issue,  we would like to close this case.

Although you can always reopen this issue if reproducibility rates are higher in upcoming drivers. We are not expecting this since we have already tested upcoming drivers and cannot reproduce the issue. However, these drivers have not yet been publicly released. 

Once again thank you for sharing the  Game time to play the game.

If you agree, please close this case. We will wait for your input.

**Comment by EugenHud** [comment]
can not be changed that they can not reproduce this error which now appears only sporadically with the latest driver.
At least I know how to get the handle (clear cache from the game).
If it should get worse I will of course get back to you.

Thanks for the support anyway
