### ISSUE TITLE
Rocket League refuses to launch

### ISSUE THREAD

**Issue by rx570gtx1060** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#185]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Rocket League

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-10400

### Graphic Card [Required]

Intel Arc A770 16GB Limited Edition GPU

### GPU Driver Version [Required]

- [X] 31.0.101.3793 (*latest*)
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [X] Other (Please specify)

### Other Windows build number

Windows 10 22H2

### Intel System Support Utility report

[bugreportforintelarcissues5.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10016208/bugreportforintelarcissues5.txt)

### Description and steps to reproduce [Required]

Install Rocket League using the Epic Games Launcher.
Try to open it up using a shortcut and it seems like its loading.
Then it closes after a few seconds

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

No game settings.
My first time launching rocket league.

**Comment by IntelSupport-Arun** [comment]
Hi @rx570gtx1060 ,

We have following questions to you:
1. Did you able to launch the game with Internal Graphics?
2. Did you able to capture the crash log if any?
3. Could you confirm the game is [Rocket League® - Painted Prestige Bundle](https://store.epicgames.com/en-US/p/rocket-league--painted-prestige-bundle)?

**Comment by rx570gtx1060** [comment]
Here is my reply @IntelSupport-Arun 

1. Integrated Graphics is disabled. My system is only using the A770
2. No I haven't been able to.
3. It is the normal Rocket League not [Rocket League® - Painted Prestige Bundle](https://store.epicgames.com/en-US/p/rocket-league--painted-prestige-bundle)?

**Comment by IntelSupport-Arun** [comment]
Hi @rx570gtx1060 ,
There is a new driver has been released [ 31.0.101.3802](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html?wapkw=arc). Could you update the driver and let me know the observations.

**Comment by rx570gtx1060** [comment]
> Hi @rx570gtx1060 , There is a new driver has been released [ 31.0.101.3802](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html?wapkw=arc). Could you update the driver and let me know the observations.

@IntelSupport-Arun 
The New Driver allowed it to launch.
Thanks for your help.
