### ISSUE TITLE
Fortnite comes up with error messsage

### ISSUE THREAD

**Issue by rx570gtx1060** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#186]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Fortnite

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-10400

### Graphic Card [Required]

Intel Arc A770 16GB Limited Edition GPU

### GPU Driver Version [Required]

- [X] 31.0.101.3793 (*latest*)
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Other Windows build number

Windows 10 22H2

### Intel System Support Utility report

[bugreportforintelarcissues6.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10025541/bugreportforintelarcissues6.txt)

### Description and steps to reproduce [Required]

Just opened Fortnite via the Epic Games Launcher.
The Error Message that came up was

A D3D11-compatible GPU (Feature Level 11.0, Shader Model 5.0) is required to run the engine

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

N/A

**Comment by IntelSupport-Arun** [comment]
Hi @rx570gtx1060 ,

We are verifying the issue on our side and will update you once done. Please stay tuned. Thanks.

**Comment by IntelSupport-Arun** [comment]
Hi @rx570gtx1060 ,
There is a new driver has been released [ 31.0.101.3802](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html?wapkw=arc). Could you update the driver and let me know the observations.

**Comment by rx570gtx1060** [comment]
> Hi @rx570gtx1060 , There is a new driver has been released [ 31.0.101.3802](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html?wapkw=arc). Could you update the driver and let me know the observations.

@IntelSupport-Arun
I have opened a new ticket with some details.
I'll be closing this one and refer you to the new ticket here

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/187
