### ISSUE TITLE
Issue with and in Fortnite ( Both DX 11 and DX 12 Modes)

### ISSUE THREAD

**Issue by rx570gtx1060** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#187]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Fortnite

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [x] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz

### Graphic Card [Required]

Intel Arc A770 16GB Limited Edition GPU

### GPU Driver Version [Required]

- [X] 31.0.101.3802 (*latest*)
- [X] 31.0.101.3793
- [X] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Windows 10 21H1
- [ ] Other (Please specify)

### Other Windows build number

19045 (22H2)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10048027/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Steps to Reproduce:

1. Open Fortnite as Usual
2. Wait for it to load
3. Go into the settings and use the detailed game settings below.
4. Play any game. There starts to be huge FPS drops even to below the 30s while GPU Usage then goes between 90 -100%. However, the temperatures keep rising to above 75c in some instances when taking a look at task manager.

Issues faced Fortnite
1. FPS struggles to reach the cap (specified in the game settings below) and as the GPU is trying to reach the cap. FPS also starts to drop while GPU temps start to climb into 75c and above.
2. After playing Fortnite a couple of times. Occasionaly I can't seem to open it to play.
Although I have closed the issue as it seems to work on the current BETA driver, I raised for this previously about me being unable to open Fortnite and I have experienced this on every driver version so far that is supported for the Intel Arc A770
4. Use of DX 11 game mode doesn't feel as smooth as DX 12 and the low FPS problem is even much worse in DX 11.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![FortniteClient-Win64-Shipping_2022_11_19_21_28_47_604](https://user-images.githubusercontent.com/70267266/202872977-17d2d5d0-b89d-4993-b9f7-aad9fca99341.jpg)
![FortniteClient-Win64-Shipping_2022_11_19_21_31_21_097](https://user-images.githubusercontent.com/70267266/202872996-418ced7a-93ab-4379-a53b-90ea2492b7b0.jpg)
![FortniteClient-Win64-Shipping_2022_11_19_21_33_24_458](https://user-images.githubusercontent.com/70267266/202873006-b2aa2eea-5b3d-4002-9849-88d50acfdb11.jpg)
![Screenshot (6)](https://user-images.githubusercontent.com/70267266/202873078-e1e10b8f-5d6b-4183-9b1e-285a0eefae52.png)

### Save game

N/A

### Game custom logs

[Uploading Logs.zip…]()

**Comment by IntelSupport-Arun** [comment]
Hi @rx570gtx1060 ,
Thank you for the details .
Does the issue only arise with the above settings mentioned in your issue description or does it also arise with other settings as well?
Could you try the below setting and let me know what is the observation
![Recommendation](https://user-images.githubusercontent.com/91881865/203005806-4f93b032-fca6-49c8-9c46-afb09ed98ed5.JPG)
s

**Comment by IntelSupport-Arun** [comment]
Hi @rx570gtx1060 , Did you get chance to verify the above settings suggested?

**Comment by rx570gtx1060** [comment]
@IntelSupport-Arun 

I'll give it a try today and let you know what happens.

**Comment by rx570gtx1060** [comment]
@IntelSupport-Arun
I can't play in the resolution given above.
As I have an Ultrawide 21:9 Monitor called the LG 29WK600-W.
However I have included Screenshots of a Similar Resolution below with monitor here.
I had to change my Monitor Aspect Ratio to Original from Full Wide at 2560 x 1080.
![screenshotofavailableresolutions](https://user-images.githubusercontent.com/70267266/203622382-9d640707-a3a1-466d-a76f-ff1377a261da.png)
![fortnitegraphicalsettingsforticket](https://user-images.githubusercontent.com/70267266/203622399-43375640-d166-4098-bff0-c184248a7660.png)
![screenshot2](https://user-images.githubusercontent.com/70267266/203622414-ab9732f7-dbfa-4f36-be96-0930632ac34e.png)
![screenshot3](https://user-images.githubusercontent.com/70267266/203622423-2bb7eb51-cfc9-4336-a164-24a959e16787.png)

**Comment by rx570gtx1060** [comment]
@IntelSupport-Arun 
Yesterday Experience with the above settings in my pcitures was much better.
Didn't experience any stuttering/breaks.

**Comment by IntelSupport-Arun** [comment]
Hi @rx570gtx1060 , I'm sorry, is your issue resolved or are you still experiencing this issue? Please confirm

**Comment by rx570gtx1060** [comment]
> Hi @rx570gtx1060 , I'm sorry, is your issue resolved or are you still experiencing this issue? Please confirm

@IntelSupport-Arun 

It is still an issue.

**Comment by IntelSupport-Rozilah** [comment]
Hi @rx570gtx1060 
Just to inform you that the issue has been reported internally and we will be working on a fix. I want to give you a heads-up that the fix may take 3 to 6 months to be included.

**Comment by Arturo-Intel** [comment]
@rx570gtx1060 hi, do you still experience this behavior with the latest driver ([101.4577](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?))? 
Dont forget to use [DDU in safe mode](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) when installing the newest one.

-- r2

**Comment by EstebanIntel** [comment]
Hi @rx570gtx1060,

Revisiting this, I tested Fortinite on DX12 @ 1080p Epic preset. The test was done on an Arc A750 using driver 101.4952. As you can see in the image below, the framerate didn't drop below 100 fps during an 800s recording of a game. There were a few spikes on frametime, which match low GPU usage. But these spikes were few and far apart, so stuttering was not actually noticeable. The analysis also confirms this, showing only 0.46s of stuttering out of the 800s of recording.

So please update your game to the latest version, as well as your driver and let us know if you still experience the issue.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/87549650/0277e7d1-c848-4fe7-a1c3-5282c3c9ce4a)

**Comment by EstebanIntel** [comment]
@IGCIT can this be closed?
