### ISSUE TITLE
Inconsistent Performance in Halo Infinite

### ISSUE THREAD

**Issue by JohnnyTex** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#189]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Halo Infinite

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5 12600k

### Graphic Card [Required]

ARC A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.3802 (*latest*)
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Windows 10 21H1
- [ ] Other (Please specify)

### Intel System Support Utility report

[SecondSSU.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10136521/SecondSSU.txt)

### Description and steps to reproduce [Required]

Halo Infinite is weirdly unoptimized overall. The map Launch Site regularly sees the fps dip all the way down to 60(!!!) when on most other maps the game manages to keep a consistent 120fps. Another map that has similarly poor performance would be Live Fire, through the fps drops are far more acceptable (typically only going down to the 80s at the most severe). All of this while the game already runs at a reduced resolution of 1339p. These smaller maps shouldn't be having such poor performance; Big Team Battle maps rarely if ever drop below 100fps. 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2381 x 1339

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Everything is set to high except textures, which is set to ultra. These are the exact same settings I ran on my RTX 3060, and that ran all the smaller maps consistently above 130 fps.

**Comment by IntelSupport-Rozilah** [comment]
hi @JohnnyTex,
Thanks for contacting Intel, can you attach the screenshot or video recorded for this issue while our system setup is ready to verify?

**Comment by JohnnyTex** [comment]
I'll see to getting that screenshot, but I can confirm I've only got the free to play multiplayer installed.

**Comment by IntelSupport-Rozilah** [comment]
hi @JohnnyTex , thanks for the reply, we will start to verify the issue soon. Stay tuned!

**Comment by IntelSupport-Rozilah** [comment]
hi @JohnnyTex ,
can you please share any iso file link for this build "Windows 11 Home 64-bit (10.0, Build 22623) (22621.ni_release.220506-1250)" because we could not find this os, else we will continue to verify this issue on the nearest build 22621.

**Comment by JohnnyTex** [comment]
I don't think I have any ISO file or anything, the PC I'm gaming on was originally a pre-built, so the Windows I'm using is the one they sent me. I think I *may* have had Windows Insider turned on at some point, but ik for a fact that I have it off now. It's finals week so I'm kinda all over the place, but I'll see about getting more info soon-ish.

**Comment by IntelSupport-Rozilah** [comment]
hi @JohnnyTex,
 thanks for the reply, hope that you are able to get the official iso file or link that will be better for us to verify this issue and [188](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/188) issue as well.

**Comment by JohnnyTex** [comment]
1) I don't think I've had another build version, so I'll see what I can do for the Windows version info. 
2) I'm installing the driver as we speak. I'll update if applicable here as well as on 188.

**Comment by JohnnyTex** [comment]
It seems to me that the build is indeed a Windows Insider Build. I'll note though that I was in Windows Insider before I got my ARC, and none of the aforementioned issues were present.

**Comment by EstebanIntel** [comment]
Hi @JohnnyTex, a possible fox for this issues is included in driver version [31.0.101.4146](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?). Can you please test it and let me know?

**Comment by JohnnyTex** [comment]
On another ticket I submitted it was marked as "implemented", as I did indeed hear from another Intel employee that 4146 supposedly fixed this. However, I can safely say the issue persists and I have asked that the implemented status be removed.

**Comment by JohnnyTex** [comment]
Huh... I always DDU my system before updating drivers. I"ll try that again today after class.

**Comment by JohnnyTex** [comment]
The issue seems to have been resolved on most maps. I saw this issue arise however in the map "Cliffhanger", and I haven't run through all the examples I gave here and elsewhere. I"ll get to more testing soon enough.

**Comment by JohnnyTex** [comment]
Furthermore, on the Big Team Battle map "Oasis", the fps is at like 45.

**Comment by JohnnyTex** [comment]
Another example of an area that suffers from these plunges in fps would be on Catalyst, near the spawns where you can see the sunset. Run up towards the edge of the surface.

**Comment by EstebanIntel** [comment]
Hi @JohnnyTex,

A fix for this issue has been included in the latest beta driver [31.0.101.4311](https://www.intel.com/content/www/us/en/download/729157/776400/intel-arc-iris-xe-graphics-beta-windows.html?cache=1681490509). Can you please test it?

**Comment by JohnnyTex** [comment]
I confirmed the fix on another medium, totally forgot to update my post here on Github. My b, let me make it clear; Halo Infinite is now almost TOTALLY fixed on ARC, and the progress made both on this map and in the game as a whole has been awe-inspiring. Well done to everyone!
