### ISSUE TITLE
Redout (Exit to desktop)

### ISSUE THREAD

**Issue by thealgorithmc64** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#19]
#### Game

Redout

---
#### CPU

i7 1165g7 (Intel XE + 16gb ram)

---
#### GPU Driver Version

9168 (Happens in earlier drivers too)

---
#### Rendering API

Direct X (Not sure which version)

---
#### Windows Build Number

Windows 20h2

---
#### Description

Shows the titlepage, then exits to desktop.

---
#### Steps To Reproduce

Just run the game

**Comment by leoben2** [comment]
Going to look at this now.

**Comment by leoben2** [comment]
We reproduced this today, so will be filing a bug against it. Thanks for the flag.

**Comment by estebanr863** [comment]
Hi @thealgorithmc64, can you try this using driver version 30.0.100.9955? https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html

**Comment by estebanr863** [comment]
Hi @thealgorithmc64, did you had a chance to test it?

**Comment by estebanr863** [comment]
Hi @mva94 and @IGCIT, if any of you own this game, can help and try this with the latest driver?

**Comment by pacoa-kdbg** [comment]
I tested with latest stable and still happening

**Comment by estebanr863** [comment]
Hi @pacoa-kdbg,

Can you please:

1. run the commands below
2. restart your system
3. repro the issue
4. attach the resulting file located at C:\AppCrashDumps

reg add "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting" /v "Disabled" /t REG_DWORD /d "0x1" /f
reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\Windows Error Reporting" /v "Disabled" /t REG_DWORD /d "0x1" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v "DumpFolder" /t REG_EXPAND_SZ /d "C:\AppCrashDumps" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v "DumpType" /t REG_DWORD /d "0x2" /f
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CrashControl\LiveKernelReports" /v "DeleteLiveMiniDumps" /t REG_DWORD /d "0x0" /f
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CrashControl" /v "FilterPages" /t REG_DWORD /d "0x1" /f
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CrashControl" /v "CrashDumpEnabled" /t REG_DWORD /d "0x1" /f
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" /v "PagingFiles" /t REG_MULTI_SZ /d "C:\pagefile.sys 17400 17400" /f

**Comment by estebanr863** [comment]
Hi @pacoa-kdbg,

In order to send us bigger files, please download the FTP client of your choice and configure it as follow:

Username: tmp02761
Password: IGC1Tp@ssw0rd
Host Name: secureftp.intel.com
Server/Protocol Type: FTP/SSL (AUTH_SSL, AUTH_TLS, or Explicit SSL/TLS)
Mode: Passive
Port: 21

**Comment by estebanr863** [comment]
Hi @pacoa-kdbg,

Did you had the chance to capture the app crash dump? We are not seen the crash on our lab.

**Comment by estebanr863** [comment]
Hi @thealgorithmc64 and @pacoa-kdbg,

We are not seen any issues with the [latest drivers](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html). Can you please perform a [clean instal](https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html)l with this driver version and try again?

**Comment by estebanr863** [comment]
Hi @IGCIT and @mva94,

We are not seen this issue in our lab with the lastest drivers. Can any of you help test it?

**Comment by IGCIT** [comment]
Hi, unfortunately i don't own the game

**Comment by estebanr863** [comment]
Since @thealgorithmc64  is not responding and we are not seen the issue on the latest drivers, can this be closed?
