### ISSUE TITLE
Sekiro shadows die twice 

### ISSUE THREAD

**Issue by mva94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#20]
#### Game _[Required]_ sekiro 

---
#### CPU _[Required]_  i7 1160g7

---
#### GPU Driver Version _[Required]_  27.20.100.9168

---
#### Rendering API _[Required]_ directx11

**API** _[DirectX, OpenGL, Vulkan]_:
**API Version** _(example DirectX 12)_:

---
#### Windows Build Number _[Required]_ latest

---
#### Description _[Required]_ after 5 minutes of moving around the game just crashes and goes back to desktop. 
No error message nothing just as if you were shutting down the game --
#### Steps To Reproduce _[Required]_
Just move around for 5 minutes or so and you should meet this crash.
Has been reported by 3 other users on discord 

---
#### Screenshots _[Optional]_
![20210210_175203](https://user-images.githubusercontent.com/78859716/107545302-6dd2d980-6bcb-11eb-8bd3-4dd35afe11b8.jpg)

---

**Comment by mva94** [comment]
There is also a weird behavior with the 16/10 display ratio. 
When set to a full-screen resolution ( 16/10) the game will not go above 30 frames as if vsync was on .
Issue goes away when switched to windowed mode and goes up to a steady 60 frames at the same resolution. 

Of course I checked that nothing was interfering 
@Valkirie

**Comment by Valkirie** [comment]
@mva94 where are we with Sekiro as of 100.9616 ?

**Comment by 123besho321** [comment]
i have crashes every 5 min if playing. 
any updates?!
