### ISSUE TITLE
Incorrect OS Edition info in Intel Arc Control

### ISSUE THREAD

**Issue by ChesterRa** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#204]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

Ryzen 9 5900x

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.3975 (*latest*)
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Windows 10 21H1
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10295521/igcit_ssu.txt)

### Description and steps to reproduce [Required]

I'm using win11 pro 22h2 but it shows win10 pro in Intel Arc Control. That's not correct.

![image](https://user-images.githubusercontent.com/89056353/209349463-f1aea6c1-32e5-4438-aed5-0f5bf35c5456.png)

**Comment by IntelSupport-Arun** [comment]
Hi @ChesterRa ,
Just to inform you that the issue has been reported internally and we will be working on a fix.
I want to give you a heads-up that the fix may take 3 to 6 months to be included.

**Comment by EstebanIntel** [comment]
Hi @ChesterRa, given that the OS can not be reliably read from the OS, Arc Control won't be showing this info in all new version going forward

**Comment by Arturo-Intel** [comment]
@IGCIT can we close this issue? :)
