### ISSUE TITLE
Vulcan vr games are lauching and working on desktop but aren't showing in the vr headset

### ISSUE THREAD

**Issue by Mathieucoco37** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#207]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Half-Life alyx

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-9600k

### Graphic Card [Required]

A770

### GPU Driver Version [Required]

- [X] 31.0.101.3975 (*latest*)
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Windows 10 21H1
- [ ] Other (Please specify)

### Intel System Support Utility report

22621 (22H2)
Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
31.0.101.3975
31.9 GB
MS-7B12
Micro-Star International Co., Ltd.

### Description and steps to reproduce [Required]

start the any vulcan games in vr mode 
It's gonna work on the display as well as the vr control but it's not gonna be displaying in the vr headset
(infinitly loading)
![Screenshot_20221227_013754](https://user-images.githubusercontent.com/74155844/209622816-05a7dbee-d29c-4284-ba7d-0593b03c5694.png)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

3872x2008

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Vulcan, every thing else dosn't change a thing

*Some direct x games aren't lauching in vr so I've try the dxvk mod and they are lauching but gotten the same issue*

**Comment by Mathieucoco37** [comment]
If you need anything just tell me, I will try anything, I just want it fix as fast as possible

**Comment by IntelSupport-Arun** [comment]
Hi @Mathieucoco37 ,
Do you have any further questions? Since we have answered your questions we would like to close this case. Thanks.

**Comment by IntelSupport-Arun** [comment]
Hi @IGCIT , We have answered customer questions and there has been no update from the customer, so please close this case.

**Comment by characharm** [comment]
And here, after a year, nothing has changed:
https://feedback.halflife2vr.com/boards/bug-reports/posts/game-won-t-render-to-headset-with-intel-arc

The default response without any specifics and ETA, blah blah blah virtual reality headset support for Intel Arc Graphics continues to evolve as we ramp up our products. Straight from 2022, incoming in 3... 2... 1.
