### ISSUE TITLE
Battlefield RTAO Shadow Artifacts

### ISSUE THREAD

**Issue by RhanCandia** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#208]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Battlefield 2042

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Other (please specify)

### Other game platform

Xbox Game Pass PC

### Processor / Processor Number [Required]

Ryzen 5 5600

### Graphic Card [Required]

ASRock Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.3975 (*latest*)
- [X] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Windows 10 21H1
- [ ] Other (Please specify)

### Intel System Support Utility report

![L9PXFoi](https://user-images.githubusercontent.com/7951366/210034988-f5ab5f5d-e248-4bdc-b25c-b687ab62a1ee.png)

These grass and rock shadows are flickering when RTAO is enabled.

### Description and steps to reproduce [Required]

Launch game. Use any graphic preset. I use High preset. Enable Ray Traced Ambient Occlusion. Play the game. Observe the shadows. More obvious on grass and rock shadows.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Just High preset.

**Comment by IntelSupport-Rozilah** [comment]
hi @RhanCandia ,
Thanks for contacting Intel.
1. can you confirm that it is this game https://www.ea.com/games/battlefield/battlefield-2042/buy/pc you using before we start to purchase the game?
2. can you attach SSU detail as well?

**Comment by RhanCandia** [comment]
> 

1. Yes, that is the game.
2. Here's the [SSU.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10323304/SSU.txt).

**Comment by IntelSupport-Rozilah** [comment]
@RhanCandia thanks for the confirmation, we will start to verify the issue once the system is ready

**Comment by RhanCandia** [comment]
Any news on replication for this one? A youtuber claims he also managed to replicate it.

https://youtu.be/tOQjG4qKTDM

Not on the linked video. I just asked him to try RTAO after I watched the video and they said they encountered the same issue on the shadows.

**Comment by IntelSupport-Rozilah** [comment]
hi @RhanCandia, 
thanks for the info, at this moment we still waiting for the game-purchasing process and will update you once the system is ready.

**Comment by IntelSupport-Rozilah** [comment]
hi @RhanCandia,
The case has been verified on our side and we are able to reproduce it with our configurations as below:
Processor: AMD Ryzen 7 5800X
Graphic device: Intel(R) Arc(TM) A770 Graphics
Graphic Driver version: 31.0.101.4032
We will be working on a fix. I want to give you a heads-up that the fix may take 3 to 6 months to be included.

**Comment by IntelSupport-Rozilah** [comment]
hi @RhanCandia 
I would like to inform you that our driver development team is already investigating the issue. The process will take from 3-6 months, and as soon as we have any update on this issue we will reach out to you again.

**Comment by EstebanIntel** [comment]
Hi @RhanCandia, a possible fix for this issue was added with the latest game version (4.1.0) and [driver version 31.0.101.4311](https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html). Can you please update your game and driver and test it?

**Comment by EstebanIntel** [comment]
Hey @RhanCandia, did you had the chance to test it?

**Comment by RhanCandia** [comment]
> Hey @RhanCandia, did you had the chance to test it?

I have been busy so I haven't tested it. I will test it tonight.

**Comment by EstebanIntel** [comment]
Hi @RhanCandia, did you had the chance to test it?

**Comment by EstebanIntel** [comment]
Hi @RhanCandia, did you had the chance to test it?

**Comment by RhanCandia** [comment]
> Hi @RhanCandia, did you had the chance to test it?

Hi @EstebanIntel, honestly, I haven't had the chance because I uninstalled the game a long time ago and that game is a huge download.

**Comment by EstebanIntel** [comment]
Can we close this issue then? As it is no longer reproducible in our lab.

**Comment by RhanCandia** [comment]
> Can we close this issue then? As it is no longer reproducible in our lab.

Yes, thanks you.
