### ISSUE TITLE
Genshin Impact crash on boot

### ISSUE THREAD

**Issue by Morph1984** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#21]
#### Game _[Required]_

Genshin Impact

---
#### CPU _[Required]_

i3-7100 / i7-8559U (HD 630, Iris Plus 655)

---
#### GPU Driver Version _[Required]_

27.20.100.9168 (Drivers as old as 25.20.100.6618 is affected as well. Tested multiple drivers from WDDM 25, 26 and 27 and they all crash on boot.)

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_: DirectX
**API Version** _(example DirectX 12)_: 11 and 12

---
#### Windows Build Number _[Required]_

19041 (20H2)

---
#### Description _[Required]_

- Launching the game causes the Intel driver to crash, this is confirmed by the logs in event viewer.

---
#### Steps To Reproduce _[Required]_

- Launch the game from the Genshin Impact launcher, upon attempting to load the game the game crashes.

---
#### Screenshots _[Optional]_

---
#### Notes _[Optional]_

This has been reported by several players using Intel iGPUs. Attempting to load the game with a lower resolution and quality does not help alleviate the issue on the latest version of Genshin Impact (1.3.2 as of this report)

**Comment by Morph1984** [comment]
An update to this issue: The WDDM 24 driver 24.20.100.6286 does not cause the game to crash, this driver I find is one of the most stable Intel driver releases thus far.

**Comment by Morph1984** [comment]
Linking this community spreadsheet listing several issues and fixes for Intel GPUs https://docs.google.com/document/d/1xrOX5_WE2Q60hTF14AMFkVsyZlCsfMLGh8eaccaRDXM/edit

**Comment by leoben2** [comment]
This is under debug now.

**Comment by Morph1984** [comment]
This seems to be fixed after a combination of game updates and gpu driver updates, closing.
