### ISSUE TITLE
Witcher 3 Next Gen DX12 Ray Tracing Options Greyed Out

### ISSUE THREAD

**Issue by RhanCandia** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#210]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Witcher 3

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 5600

### Graphic Card [Required]

ASRock Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.3975 (*latest*)
- [X] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Windows 10 21H1
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10323331/SSU.txt)

### Description and steps to reproduce [Required]

Launch game.
Go to Settings > Graphics.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

RT Ultra Preset

**Comment by RhanCandia** [comment]
![Screenshot 2022-12-30 143613](https://user-images.githubusercontent.com/7951366/210042000-6ce985bb-db9c-41a5-a034-c09c8f2b57c6.png)
![Screenshot 2022-12-30 143636](https://user-images.githubusercontent.com/7951366/210042011-32403e9b-e61b-42fb-a2d6-390bd28ae500.png)

**Comment by IntelSupport-Arun** [comment]
Hi @RhanCandia ,
Thank you for contacting us.
I just wanted to let you know that the issue has already been raised internally and we will be working on a solution.
I want to give you a heads-up that the fix may take 3 to 6 months to be included.

**Comment by RhanCandia** [comment]
Oh, okay. Sorry I didn't search this one on the issues first before I filed it. Thanks for letting me know.

**Comment by RhanCandia** [comment]
> Hi @RhanCandia , Thank you for contacting us. I just wanted to let you know that the issue has already been raised internally and we will be working on a solution. I want to give you a heads-up that the fix may take 3 to 6 months to be included.

If 3 to 6 months, is it possible to implement XeSS  too?

**Comment by IntelSupport-Arun** [comment]
Hi @RhanCandia ,

yes, The implementation will be applicable for both arc, UHD and xe Graphics

**Comment by RhanCandia** [comment]
> Hi @RhanCandia ,
> 
> yes, The implementation will be applicable for both arc, UHD and xe Graphics

Oh, I was actually asking if you will also include the XeSS upscaling on that fix/update. I wasn't asking about UHD and Xe graphics.

**Comment by IntelSupport-Arun** [comment]
Hi @RhanCandia ,
XeSS issue was also reported internally and we are working for the fix. Hope both issues will get fixed together. Unfortunately, I cannot give a fixed time for fixing the issue, it may take 3 to 6 months to finish.
As soon as it is fixed, I will post an update here, so please stay tuned.
Thanks for your understanding.

**Comment by EstebanIntel** [comment]
Hi @RhanCandia,

The issue were the RT option was not selectable was fixed by the game developer in game version 4.02. Can you please test it out?

**Comment by RhanCandia** [comment]
> Hi @RhanCandia,
> 
> The issue were the RT option was not selectable was fixed by the game developer in game version 4.02. Can you please test it out?

Can confirm that RT is now available for my Arc A750. Any news on XeSS for Witcher 3?

They added XeSS to Cyberpunk 2077 and it's amazing. My A750 gained so much from that and is now really playable at 1440p60 HIGH.

**Comment by EstebanIntel** [comment]
The XeSS integration is up to the game's developer to implement, so we depend on them to actually add it.

With that said, XeSS for the Witcher 3 should be enabled soon :smile:.

**Comment by RhanCandia** [comment]
> The XeSS integration is up to the game's developer to implement, so we depend on them to actually add it.
> 
> With that said, XeSS for the Witcher 3 should be enabled soon 😄.

Thanks for the response. I do understand that it's on the developer to implement it. But I believe Intel needs to push a bit more. A promotional partnership with the developers or something like that.

XeSS is amazing. Really. In Cyberpunk I was so surprised to see that even XeSS Performance mode beats FSR Quality. Even comes close to DLSS.

Your last sentence give me hope. U am looking forward to that.

I really hope Intel promotes XeSS more and build partnerships with developers. Seriously, XeSS is amazing. I also hope they introduce frame interpolation/generation soon as well. 😸

**Comment by EstebanIntel** [comment]
Hey @RhanCandia, FYI, the latest Witcher 3 patch has now enabled XeSS 😄

**Comment by RhanCandia** [comment]
> Hey @RhanCandia, FYI, the latest Witcher 3 patch has now enabled XeSS 😄

It did. I got to try it. But it's weird. Something feels wrong. The performance in the new patch is terrible.

On 4.0.1 I was playing it HIGH preset, no RT. And I was getting a stable 60fps.

Now on the latest patch, I was getting closer to 50fps on HIGH preset, no RT. Then I enabled XeSS Performance and I was still getting around 50fps. And the GPU Utilization was hovering around 60%. I'm not sure if it's just my system. I am the latest beta drivers.

**Comment by EstebanIntel** [comment]
That is weird, I just tested it and I'm getting 86fps on 1440p, Ultra settings, RT off. And 50fps on 1080p, RT settings, RT on.

![Witcher3](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/87549650/4f6c1899-3b58-4262-a16e-1650247f2572)

**Comment by RhanCandia** [comment]
> That is weird, I just tested it and I'm getting 86fps on 1440p, Ultra settings, RT off. And 50fps on 1080p, RT settings, RT on.
> 
> XeSS enabled in both cases, on driver 31.0.101.4369
> 
> ![Witcher3](https://user-images.githubusercontent.com/87549650/239073851-4f6c1899-3b58-4262-a16e-1650247f2572.jpg)

I'm still on 4355 drivers. I only found out now that there's a new driver. I will update to 4369 later today and test again. I'll take some footages too.

**Comment by RhanCandia** [comment]
Here's a recording. I updated to 4369 before doing this.

https://youtu.be/MIddChimjEc

First run through the small town: Ultra Preset, XeSS Quality, RT Off
Second run: Ultra Preset, FXAA, RT Off
Third run: Ultra Preset, XeSS Performance
