### ISSUE TITLE
When capturing the screen with AV1 codec on Intel Arc Control, the output is corrupted.

### ISSUE THREAD

**Issue by RhanCandia** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#213]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

Ryzen 5 5600

### Graphic Card [Required]

ASRock Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4032 (*latest*)
- [X] 31.0.101.3975
- [X] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10328320/SSU.txt)

### Description and steps to reproduce [Required]

1. Launch Intel Arc Control
2. Go to Studio > Capture > Advanced
3. Set Codec to AV1
4. Start capturing the screen
5. End the capture

The resulting output is corrupted and can't be played.

https://user-images.githubusercontent.com/7951366/210161735-bbf4eb86-71b0-4cbe-9a02-0cdfc320248e.mp4

**Comment by RhanCandia** [comment]
Oh, when it was uploaded here it actually was recognized. But it still is corrupted. It won't play beyond the first frame. That recording was about 12 seconds.

**Comment by RhanCandia** [comment]
Most times it outputs only a 262 bytes file.


https://user-images.githubusercontent.com/7951366/210161823-dc63af65-6703-41a3-85af-339fa3921cd7.mp4

**Comment by IntelSupport-Arun** [comment]
Hi @RhanCandia ,

Thank you for contacting us.
We will verify the issue on our side and will update you on the result. Thanks.

**Comment by IntelSupport-Arun** [comment]
Hi @RhanCandia ,
The issue was reproduced on AMD Ryzon 7 5800x with the latest graphics driver 31.0.101.4032.
I have escalated the issue to the next level for further debugging and fixing and I want to give you a heads-up that the fix may take 3 to 6 months to be included.
We will update you when the fix is ready.

**Comment by RhanCandia** [comment]
@IntelSupport-Arun FYI, I updated to 4091 and tested recording with AV1 format. It works now. Feel free to close this issue once you've verified on your end. Thanks!

https://user-images.githubusercontent.com/7951366/216023960-f4656e30-65f8-47ca-a445-eb3aec010761.mp4

**Comment by Arturo-Intel** [comment]
Hello @IGCIT can you please close this case? :)

**Comment by RhanCandia** [comment]
> Hello @IGCIT can you please close this case? :)

I'll close it. The issue is now resolved on my end. Thanks.
