### ISSUE TITLE
Wallpaper Engine crashes (seemingly) irregularly 

### ISSUE THREAD

**Issue by derlade** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#215]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Wallpaper Engine (Steam version)

### Processor / Processor Number [Required]

Intel Core i3-12100

### Graphic Card [Required]

Intel Arc A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4032 (*latest*)
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [X] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10355765/igcit_ssu.txt)

### Description and steps to reproduce [Required]

After running Wallpaper Engine for a certain amount of time (best estimate I can give is between 1-2h), it crashes with the error message:

> ---------------------------
>wallpaper32.exe - Anwendungsbeendung
>---------------------------
>DirectX 10 wird nicht von deiner Grafikkarte unterstützt oder deine Grafikkartentreiber sind defekt. Windows meldet: Für >diesen Vorgang sind nicht genügend Speicherressourcen verfügbar.  (hr: 8007000e, code: 0, iswnd: 1, hdr: 0).  
>---------------------------
>OK   
>---------------------------

Translated:

>---------------------------
>wallpaper32.exe - Application Crash
>---------------------------
>DirectX 10 is not supported by your graphics card or your graphics card drivers are corrupted. Windows reports: Not enough >memory resources available for this event.  (hr: 8007000e, code: 0, iswnd: 1, hdr: 0).  
>---------------------------
>OK   
>---------------------------

The corresponding error is logged in [SteamDir]\wallpaper_engine\log.txt and reads:

>2023-01-05T11:14:52Z, 8296: DXGI device lost in render loop.
>2023-01-05T11:14:52Z, 8296: DXGI begin recovery.
>2023-01-05T11:14:54Z, 8296: DXGI finish recovery: 1.
>2023-01-05T14:59:42Z, 22020: DXGI Init failed, retrying: 19
>2023-01-05T14:59:43Z, 22020: DXGI Init failed, retrying: 18
...
>2023-01-05T15:00:01Z, 22020: DXGI Init failed, retrying: 1
>2023-01-05T15:00:02Z, 22020: DXGI Init failed, retrying: 0
>2023-01-05T15:00:03Z, 22020: DirectX 10 wird nicht von deiner Grafikkarte unterstützt oder deine Grafikkartentreiber sind defekt. Windows meldet: Für diesen Vorgang sind nicht genügend Speicherressourcen verfügbar.  (hr: 8007000e, code: 0, iswnd: 1, hdr: 0).

### Device / Platform

Self-built

### Crash dumps [Required, if applicable]

Will upload MEMORY.DMP if needed. Other dumps regarding this error are not created.

**Comment by IntelSupport-Arun** [comment]
Hi @derlade ,

Thank you for contacting us.

I would like to know if the app crashes while doing any specific task or if it crashes after 1 or 2 hours of usage. It would be helpful if you could explain how to reproduce the problem.
Also, could you try a clean installation of the graphics driver and see any changes? 

<img width="590" alt="Fresh_Installation_ARC_driver" src="https://user-images.githubusercontent.com/91881865/210975817-9869ce1e-ba48-4f84-899d-84ee7187aa03.png">

**Comment by derlade** [comment]
Hi @IntelSupport-Arun,

Will do.
Until now, I couldn't identify what causes the crash, or when it happens exactly. For me, it seems to be random, after some time of using my PC normally.
I forgot to mention that after the crash, I cannot launch games like Microsoft Flight Simulator.

**Comment by IntelSupport-Arun** [comment]
Hi @derlade , 
Thank you for the quick update.
After the clean installation of the driver please launch the app and make sure that there is no app or program running in the background.

**Comment by IntelSupport-Arun** [comment]
Hi @derlade ,

Did you try the clean installation of the driver? What's the latest update from your side?

**Comment by derlade** [comment]
Hi @IntelSupport-Arun,

I have performed the clean install and a reboot; unfortunately, the problem occured again. Currently, I am trying to find regularities in the crashes to generate reproducible instructions. I have noticed that my time estimate of 1-2h seems to be way off, once it crashed 7h, the next day 11h after booting. Apart from that, I haven't noticed anything new.

**Comment by IntelSupport-Arun** [comment]
Hi @derlade ,

Thank you for the quick check and update.
I would like  you to try the below Troubleshooting method and let us know the outcomes:
**Solution 1**:  Try disabling MSAA and run the Wallpaper Engine
**Solution 2**:  Make sure your antivirus app ignores the wallpaper_engine directory and especially all .exe files:
wallpaper_engine/wallpaper32.exe
wallpaper_engine/wallpaper64.exe
wallpaper_engine/launcher.exe
wallpaper_engine/bin/webwallpaper32.exe
wallpaper_engine/bin/ui32.exe

**Solution 3**: Try to verify the Wallpaper Engine files through steam to ensure they are not broken("Verify the integrity of the files")

**Comment by IntelSupport-Arun** [comment]
Hi@deralde,

Do you have any latest news for us? Any of the solutions help?

**Comment by derlade** [comment]
Hi @IntelSupport-Arun,

I have applied your proposed solutions. For now, the crash has not occurred, although I have only tested it for a day and I seemed to have been lucky the past few days anyways, since the crash also did not occur then. I will report back if I encounter a crash.

**Comment by IntelSupport-Arun** [comment]
Hi @derlade ,  Thank you for checking and updating.
 Please update us and close the case if the issue not observing after two days.
I will stay tuned for your next update.

**Comment by derlade** [comment]
Hi @IntelSupport-Arun,

is it possible to reopen the case should the issue arise again? If not, I would prefer to leave it open for at least two weeks to make sure the fix is permanent.

**Comment by IntelSupport-Arun** [comment]
Hi @derlade , 

Yes, You can reopen the issue if it arises again and we will assist you further.

We prefer you to raise a new support ticket if you're experiencing a different issue.t.

If you are okay with closing now, please close the thread and re-open it if the issue returns. Thank you.

**Comment by derlade** [comment]
Unfortunately, the problem occurred again just now.

**Comment by derlade** [comment]
I have sifted through all events in event viewer that were correlated to the error by time. Apart from the event with source "Application Popup" (that displays the error message) I could only find an event in the protocols of Microsoft/Windows/Shell-Core, in AppDefaults with the source "Shell-Core": The event information reads "AppDefault-Info: Querying default browser info" and it occurred 8 seconds after the Application Popup. It seems unlikely it is connected to the crash.

What I did find peculiar though, is the fact that there are multiple warnings every day in Microsoft/Windows/Diagnostics-Performance, reading: 

> Der Desktopfenster-Manager hat eine starke Ressourcenauslastung ermittelt. 
>     Szenario	:	Es steht wenig Videospeicher zur Verfügung. Dies hat zu einer Überlastung geführt. Dieses Problem kann möglicherweise durch Reduzieren der Anzahl ausgeführter Programme und geöffneter Fenster behoben werden.

Translated: 

> The Desktop Window Manager is experiencing heavy resource contention.
> Scenario : Video memory resources are over-utilized and there is thrashing happening as a result. Reducing number of running programs and open windows may help resolve this condition.

This is odd since at no point (as far as I could tell) did I see the VRAM being heavily utilized (VRAM usage was below 1GB during crash). No warnings in Diagnostics-Performance can be found in the timeframe around the crash, though. Since the desktop windows manager might be connected, I will try disabling SylphyHornPlus to see if the crashes stop occurring.

**Comment by IntelSupport-Arun** [comment]
Hi @derlade ,

Thank you for the update and result.
I would like to know below details from your side:

1. May I know how many monitors you are using? Single or multiple?
2. Can you check your integrated GPU is enabled in BIOS?
3. Your display is connected to ARC graphics card?

**Comment by derlade** [comment]
I am running two monitors, both connected to the dedicated GPU. iGPU multi-monitor support is disabled in BIOS.

**Comment by derlade** [comment]
Disabling SylphyHornPlus neither helped with the crash nor did it reduce the Diagnostics-Performance events in event viewer. Can confirm that after the crash, MSFS won't launch without a PC restart. Trying to start it logs an error in event viewer. Would it be helpful to relay more information about this error?

**Comment by IntelSupport-Arun** [comment]
Hi @derlade .

Thank you for the confirmation. 

1.  To isolate the issue perform the clean boot by following the below link and launch the Wallapaper engine: 
[https://support.microsoft.com/en-us/topic/how-to-perform-a-clean-boot-in-windows-da2f9573-6eec-00ad-2f8a-a97a1807f3dd#ID0EBBD=Windows_11](https://support.microsoft.com/en-us/topic/how-to-perform-a-clean-boot-in-windows-da2f9573-6eec-00ad-2f8a-a97a1807f3dd#ID0EBBD=Windows_11)

This procedure disables all third-party services and programs. You can later, if the problem is solved in this way, selectively enable the programs and services that will start with Windows, instead of keeping all disabled. If the problem returns after activating the startup of a specific service or program, the problem is exactly in the startup of this software and it is recommended to remove it.

2. If you still couldn't find the root cause of the issue, please run the "DxDiag" on you system and share the file for further investigation. Try the below steps

> Tap key combination <Windows Key + R>
> Type 'DxDiag' and tap 'Enter'
> In the 'DxDiag window', click 'Save All Information'
> Save this file to your 'Windows desktop' and name it 'dxdiag' and share it with me.

**Comment by IntelSupport-Arun** [comment]
Hi @derlade , 

Did you try the recommendation? What's the latest news from your side?

**Comment by derlade** [comment]
Unfortunately, I am unable to run my PC in safe mode for up to 12 hours at a time, since I need to work on it. The dxdiag file is attached.
[DxDiag.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10469737/DxDiag.txt)

**Comment by IntelSupport-Arun** [comment]
Hi @derlade ,

Im verifying the issue on our side and let see we can reproduce the issue or not.
Mean time could you try do the clean boot to isolate the issue
https://support.microsoft.com/en-us/topic/how-to-perform-a-clean-boot-in-windows-da2f9573-6eec-00ad-2f8a-a97a1807f3dd#ID0EBBD=Windows_11

**Comment by IntelSupport-Arun** [comment]
Hi @derlade ,
Which option do you select for launching the app
https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html?

**Comment by IntelSupport-Arun** [comment]
Hi @derlade ,
I have been checking the issue on our side for the last 24 hours (Intel Core i7 12700K + Windows 11 , 22h2) and have not encountered any issues.
I have verified the event viewer and not seeing any Errors that you have experienced.
Could you try disabling the below setting in Arc Control and see if the issue is still observing:
1. Disable the "In-Game Overlay" setting in Arc Control
2. Do you have CMAA enabled in Arc Control's Global Settings? If enabled please change it to "Application Choice"

If the issue is still seeing after trying the above recommendation I have one more question, 
1. what is the refresh rate of your displays? Do both have the same refresh rate or different?
2. Are you using the same Display models?
3. Did you check the issue with the single display? Or the issue is observed only with dual monitors?

**Comment by derlade** [comment]
Hi @IntelSupport-Arun,
thank you for taking the time to try to reproduce the issue. 
- Regarding the launch setting in Steam, I am not sure if I am using 32 or 64 bit start, since I set Wallpaper Engine to autostart after startup. 
- I cannot find the setting to disable the in-game overlay. Can you point me to it?
- CMAA was set to "deactivate forcing" (Erzwingen deaktivieren in German), I have set it to Application Choice now.
- Opt to Driver Boost was already enabled
- I am running a dual monitor setup, one is running at 75 Hz and the other at 60 Hz. They are different display models.

As luck has it, the problem has only reoccurred once after my last post, so I will keep observing if the crash happens again. When I have some more time, I will try your suggestions regarding single-monitor/clean boot.

Would it be advisable to also write a support ticket to the Wallpaper Engine developer? I could link him this issue for further details.

**Comment by IntelSupport-Arun** [comment]
Hi @derlade ,

Thank you for the quick reply.

I have one more question, may I know both the displays are connected on Arc?

**Comment by derlade** [comment]
Yes, both are connected to the card directly; one via HDMI, the other via an active HDMI to DP adapter.Am 27.01.2023 um 10:58 schrieb IntelSupport-Arun ***@***.***>:﻿
Hi @derlade ,
Thank you for the quick reply.
I have one more question, may I know both the displays are connected on Arc?

**Comment by IntelSupport-Arun** [comment]
Hi @derlade ,

I would recommend 2 things here to narrow down the issue:

**step1**: Please verify the issue with the single display
                  (a) with HDMI only -- what is the observation?
                  (b) with active HDMI to DP adapter only - what is the observation?

**Step 2**: Connect both displays on Arc and try the below steps:

- Open your Steam Library
- Right-click the "Wallpaper Engine" and select Properties.
- On the General tab you'll find the Launch Options section.
- Enter "-refresh 60" and close the properties
- Launch the "Wallpaper Engine"

Please try the above 2 recommendations and let me know the observations as soon as possible.

**Comment by IntelSupport-Arun** [comment]
Hi @derlade ,

Any update for us?

**Comment by derlade** [comment]
Hi @IntelSupport-Arun,

I have tried setting the fps in the Wallpaper Engine settings to 60 a few days ago. So far, the crash hasn't occured, although the event viewer warnings in Diagnostics-Performance are still present (about 4 hours apart from each other). I will additionally set  -refresh 60 in Steam launch options. 

Should the crash reoccur, I will open this issue again.
