### ISSUE TITLE
Arc Control Perpetually States "Updating Your Experience" on the Driver Page

### ISSUE THREAD

**Issue by TealDolphin** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#218]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

AMD Ryzen 5 7600X

### Graphic Card [Required]

Intel Arc A770 LE

### GPU Driver Version [Required]

- [ ] 31.0.101.4034 (*latest*)
- [X] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10421352/igcit_ssu.txt)

### Description and steps to reproduce [Required]

I have DDU wiped and installed the 31.0.101.4032 Intel Arc drivers including the Support Assist and the Arc Control software a couple of times and every time I open the Arc Control to the Drivers page, it states "Updating Your Experience. Thank you for your patience." every time, regardless of how long I wait.
![ARC Software](https://user-images.githubusercontent.com/44395321/212569816-0a876fd6-8464-4999-bbdd-89a3811ed174.PNG)

**Comment by IntelSupport-Rozilah** [comment]
hi @TealDolphin,
The case has been verified on our side and we are able to reproduce it with our configurations as below:
Processor: AMD Ryzen 7 5800X
Graphic Driver version: 31.0.101.4032
We will be working on a fix. I want to give you a heads-up that the fix may take 3 to 6 months to be included.

**Comment by IntelSupport-Rozilah** [comment]
hi @TealDolphin,
There is new driver(31.0.101.4091) updated for fix this issue, can you have a try and let us know if it is working for you?.

**Comment by TealDolphin** [comment]
Thank you for reaching out. I am currently on the 31.0.101.4091 driver and both the overlay and the desktop application are now loading correctly.
