### ISSUE TITLE
Titanfall 2 Unable to Launch past Respawn Entertainment Logo

### ISSUE THREAD

**Issue by TealDolphin** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#219]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Titanfall 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 5 7600X

### Graphic Card [Required]

Intel Arc A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4034 (*latest*)
- [X] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10421899/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Upon trying to launch Titanfall 2, either through Steam or the EA launcher, the game tries to start loading but crashes on the Respawn Entertainment splash screen. If I launch with the -novid flag, it just goes to the loading screen but doesn't get to the main menu. It crashes to desktop every time.
I have tried on both the newest driver, and the newest beta driver. It gives the same error in event manager (as attached), with the only difference being that the igc64.dll is a different version number (matching the arc driver version number).
![Titanfall2Error](https://user-images.githubusercontent.com/44395321/212582642-260389d6-c7f9-41b3-a474-d724cb9d1565.PNG)
I have tried both validating game files and reinstalling the game. I have also tried reinstalling the 31.0.101.4032 fresh after a DDU wipe, and have tried the 31.0.101.4034 drivers with the Intel installation .exe and the clean install box checked.
I tried with the AMD graphics driver for the onboard graphics disabled and there was no difference.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

Monitor is 2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

I can't get into the main menu. I don't think that game settings have anything to do with it.

### Crash dumps [Required, if applicable]

I have chosen to include 5 crash dumps, if you would like more I can always generate more as they generate with each crash.
[Crash Dumps.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10421956/Crash.Dumps.zip)

### Save game

Can't get to main menu. Don't think that save info matters.

**Comment by IntelSupport-Rozilah** [comment]
hi @TealDolphin ,
1. Thanks for contacting Intel, can you confirm which game version that issue occur before we start purchasing the game?
![image](https://user-images.githubusercontent.com/44628772/212591502-cd0fe0e2-0f6a-4c44-bbe5-958698a7ca4e.png)
2. can you attach a video or screenshot of the issue so that easy for us to verify the issue?

**Comment by TealDolphin** [comment]
Happy to provide any extra info I can. Let me know if there is any extra information you need from me.
![titanfallBuildNumber](https://user-images.githubusercontent.com/44395321/212594452-c2535ea3-7e54-4442-91f5-d199eb5bad34.PNG)
Unfortunately the video of it crashing is too large to share directly. However, I was able to upload it to youtube. Hopefully that is acceptable.
https://youtu.be/Z5ozEOfat-U

**Comment by IntelSupport-Rozilah** [comment]
@TealDolphin, thanks for the quick reply, it's enough info for us and we will start to verify the issue once the system is ready. Stay tuned!

**Comment by IntelSupport-Rozilah** [comment]
Hi @TealDolphin,
This issue has been already internally and internal team working on it. I want to give you a heads-up that the fix may take 3 to 6 months to be included.

**Comment by opteronm** [comment]
@TealDolphin for the mean time if you're looking to play the game. You can use DXVK. I've used it with great success.

**Comment by EstebanIntel** [comment]
Hi @TealDolphin did you had the chance to test with the latest driver?

**Comment by TealDolphin** [comment]
I have finally had the time to go and test Titanfall 2. It does appear to launch and run just fine now. I have not done any long term tests for stability, but it does at least run. Thank you.
