### ISSUE TITLE
Call of duty cold war crashing during start up

### ISSUE THREAD

**Issue by mva94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#22]
#### Game _[Required]_ 
call of duty: Cold war 

---
#### CPU _[Required]_
 i7 1160g7/ i71165g7

---
#### GPU Driver Version _[Required]_ 27.20.100.9313 or earlier versions 

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_: directx
**API Version** _(example DirectX 12)_: dx12

---
#### Windows Build Number _[Required]_
latest

---
#### Description _[Required]_

---
#### Steps To Reproduce _[Required]_
Just boot the game 

---
#### Screenshots _[Optional]_

---

**Comment by leoben2** [comment]
This one we're aware of and working with Beenox to see what can be done.

**Comment by Valkirie** [comment]
Closing as similar to #23.

**Comment by Valkirie** [comment]
Hey @leoben2 any chance you could prioritize this one ? Obviously a huge license with strong community expectations and the game just doesn't boot. Any update from **Beenox** you could share ?

**Comment by mva94** [comment]
@leoben2 any news here ..?

**Comment by leoben2** [comment]
We're working closely with Beenox on this...hopefully good news soon!

**Comment by mva94** [comment]
@leoben2 appreciate it !!!

**Comment by mva94** [comment]
@leoben2 
Apparently the latest update from beenox changed something but didnt solve the issue .
Here is the new error

**Comment by Dev45689** [comment]
They said it's mostly a bug ???

**Comment by Dev45689** [comment]
Anything new yet any updates

**Comment by estebanr863** [comment]
Still of the game developer side @Dev45689

**Comment by Dev45689** [comment]
Have u heard anything from the developers or are they still being lazy

**Comment by Bryce-7995** [comment]
Last update I received was this may take time, the developer was focused on the title that was just released but should have more resources free after launch to put more attention on this. Hopefully we see progress from them soon.

**Comment by IGCIT** [comment]
possible fix in latest driver, please test
https://www.intel.com/content/www/us/en/download/19387/intel-graphics-beta-windows-dch-drivers.html

**Comment by mva94** [comment]
Nice will definitely try it out

**Comment by estebanr863** [comment]
Hi @mva94 

A possible fix for this issue has been included in the [latest driver version](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) 30.0.101.1960. Can you please perform a [clean install](https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html) of this driver version and test it?

**Comment by mva94** [comment]
@estebanr863 Hi 

I tested it yesterday , it works wonder ! 
Great job !
https://youtu.be/Ce3OgLQEWvQ
