### ISSUE TITLE
Batman Arkham Knight extremely poor performance

### ISSUE THREAD

**Issue by AverageGithubBugReporter** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#222]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Batman Arkham Knight

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-12400F

### Graphic Card [Required]

Arc A770 Special Edition

### GPU Driver Version [Required]

- [X] 31.0.101.4034 (*latest*)
- [X] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10451775/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Batman Arkham Knight does not function properly in driver 4032 or 4034

In 4032 the game fails to launch completely, it closes itself after the splash screen shows up and nothing happens

In 4034 the game launches, but the main menu runs at 2fps rendering it unplayable

Using DXVK in either driver allows the game to function properly

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440p

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Game does not launch/performs very poorly so I cannot get to the graphics settings menu

**Comment by IntelSupport-Arun** [comment]
Hi @AverageGithubBugReporter ,

Thank you for reaching out to us.

Batman Arkham Knight config files and graphics XML files can become corrupt over time, if a new patch comes out or a tool/tweak was used before. Deleting the config/XML file will cause the game to make fresh new files which can improve performance and eliminate crashes and other issues.
Delete the **"GFXSettings.BatmanArkhamKnight.xml"** file, located in **C:\Users\YOURNAME\Documents\WB Games\Batman Arkham Knight** (game saved location)
Then delete the game's Binaries and Config folder, if you right-click the game in your Library and select 'Properties', from here go to the 'Local Files' tab and select 'Browse Local Files'. From here delete the 'Binaries' folder, open up the 'BMGame' folder, and delete the 'Config' folder.
Now while you still have the Batman Arkham Knight Properties windows open select 'Verify integrity of game files' , this will helps to fix the missing files.

If the above solution doesn't work  for you , please try disabling the Hardware-Accelerated GPU Scheduling (Windows Settings > System > Display > Graphics Settings)

Please give it a try with the above recommendation and let us know your observations.

**Comment by AverageGithubBugReporter** [comment]
Hello

> Hi @AverageGithubBugReporter ,
> 
> Thank you for reaching out to us.
> 
> Batman Arkham Knight config files and graphics XML files can become corrupt over time, if a new patch comes out or a tool/tweak was used before. Deleting the config/XML file will cause the game to make fresh new files which can improve performance and eliminate crashes and other issues. Delete the **"GFXSettings.BatmanArkhamKnight.xml"** file, located in **C:\Users\YOURNAME\Documents\WB Games\Batman Arkham Knight** (game saved location) Then delete the game's Binaries and Config folder, if you right-click the game in your Library and select 'Properties', from here go to the 'Local Files' tab and select 'Browse Local Files'. From here delete the 'Binaries' folder, open up the 'BMGame' folder, and delete the 'Config' folder. Now while you still have the Batman Arkham Knight Properties windows open select 'Verify integrity of game files' , this will helps to fix the missing files.
> 
> If the above solution doesn't work for you , please try disabling the Hardware-Accelerated GPU Scheduling (Windows Settings > System > Display > Graphics Settings)
> 
> Please give it a try with the above recommendation and let us know your observations.

Hello, I have attempted this and the game no longer boots at all again without DXVK

The splash screen comes up and then goes away after about 20 seconds or so

I have asked someone else with an A770 to test and they are reporting the same behavior, though they have not attempted these recommended steps yet

Also something that may be of note, I could boot up the game as mentioned in the report here at 2fps when I updated to 4034 prior to the recommended steps, but the other person I know could not even after installing the beta driver. No idea if that's at all helpful

**Comment by IntelSupport-Arun** [comment]
Hi @AverageGithubBugReporter ,

We will check the issue on our lab and let you know the update soon.

**Comment by IntelSupport-Arun** [comment]
Hi @AverageGithubBugReporter ,

Could you try the below steps and see it can improve the FPS rate:

1. Re-install the game.

2. Go to Steam's Library -> right click on Batman: Arkham Knight -> Properties -> Set launch options -> write in "-windowed "-> OK -> Close.

**Comment by IntelSupport-Arun** [comment]
Hi @AverageGithubBugReporter ,

Any latest news for us?

**Comment by AverageGithubBugReporter** [comment]
Hello, sorry I haven't had time as of late

I'll check this tomorrow and report back

**Comment by IntelSupport-Arun** [comment]
Hi @AverageGithubBugReporter ,

Have you got any chance to test the settings?

**Comment by IntelSupport-Arun** [comment]
Hi @AverageGithubBugReporter ,

Do you have any latest news for us?

**Comment by IntelSupport-Arun** [comment]
Hi @IGCIT , Since we are not getting any reply please proceed to close this case.

**Comment by toriko2** [comment]
@IGCIT any chance this issue can be reopened as I face the same problem, or should I just make a new issue given this ones been closed for a year?

**Comment by IGCIT** [comment]
> @IGCIT any chance this issue can be reopened as I face the same problem, or should I just make a new issue given this ones been closed for a year?

yes, please, open a new one for current driver
