### ISSUE TITLE
Jedi Fallen Order screen smearing effect

### ISSUE THREAD

**Issue by AverageGithubBugReporter** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#223]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Jedi Fallen Order

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-12400F

### Graphic Card [Required]

Arc A770 Special Edition

### GPU Driver Version [Required]

- [ ] 31.0.101.4034 (*latest*)
- [X] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10451788/igcit_ssu.txt)

### Description and steps to reproduce [Required]

On Dathomir, the game will exhibit very strange screen artifacting, images attached for reference

![image](https://user-images.githubusercontent.com/123030628/213312859-b7409407-a708-4f2c-bcef-4dc7192bcd1a.png)
![image2](https://user-images.githubusercontent.com/123030628/213312862-d323163e-b884-4e15-b2ac-eced34d4dc0e.png)

This occurred several times in about 10 minutes of gameplay

I've played this game for about 60 hours on NVIDIA and AMD hardware and have never seen this behavior

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440p

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

<img width="1280" alt="Screenshot 2023-01-18 175610" src="https://user-images.githubusercontent.com/123030628/213313459-247ae8c4-7790-4a6d-b840-1f36fe3a54d9.png">
<img width="1280" alt="Screenshot 2023-01-18 175645" src="https://user-images.githubusercontent.com/123030628/213313462-edf53c82-ec5f-409d-983c-b290f475c817.png">

**Comment by IntelSupport-Arun** [comment]
Hi @AverageGithubBugReporter ,

We are checking this issue and will update you soon once verified.

**Comment by IntelSupport-Arun** [comment]
Hi @AverageGithubBugReporter ,
After checking internally this issue has already been reported and we are working on the fix.
 I want to give you a heads-up that the fix may take 3 to 6 months to be included. Once the fix is ready we will update you.

**Comment by AverageGithubBugReporter** [comment]
> Hi @AverageGithubBugReporter , After checking internally this issue has already been reported and we are working on the fix. I want to give you a heads-up that the fix may take 3 to 6 months to be included. Once the fix is ready we will update you.

**Comment by IGCIT** [comment]
keep this open until a fix has landed to avoid others opening the same issue again (and also to confirm it has been fixed)

thanks

**Comment by AverageGithubBugReporter** [comment]
Sorry about that, will do

**Comment by EstebanIntel** [comment]
Hi @AverageGithubBugReporter, a possible fix for this issue is included with driver [31.0.101.4369](https://www.intel.com/content/www/us/en/download/726609/779145/intel-arc-iris-xe-graphics-whql-windows.html). Can you please test it?

**Comment by EstebanIntel** [comment]
Hi @IGCIT, we are not seen this issue in our lab on the latest driver and @AverageGithubBugReporter is not responding. Can this issue be closed?
