### ISSUE TITLE
Black Mesa corrupted/missing textures, flashlight does not work

### ISSUE THREAD

**Issue by AverageGithubBugReporter** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#226]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Black Mesa

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-12400F

### Graphic Card [Required]

Arc A770 Special Edition

### GPU Driver Version [Required]

- [X] 31.0.101.4034 (*latest*)
- [X] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10452034/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Load up Xen and at the very beginning of the level, you'll see several missing textures, images attached for reference

Happens in both 4032 and 4034

![blackmesa](https://user-images.githubusercontent.com/123030628/213319301-3aa6f0dd-41f4-49e0-8b55-e7d7b9b6c66a.png)
![blackmesa2](https://user-images.githubusercontent.com/123030628/213319302-6a8574a5-e613-4179-bc60-92a490b4b751.png)

Flashlight also does not work in game at all, there is no light coming from it when you turn it on

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440p

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://user-images.githubusercontent.com/123030628/213319553-2d07fbaa-617d-4bd1-93ad-8f62e22c50fa.png)
![image](https://user-images.githubusercontent.com/123030628/213319636-d790df08-1c1d-4ee5-a945-070587f7d8dd.png)
![image](https://user-images.githubusercontent.com/123030628/213319653-16cac692-fe71-4f44-8d06-b9468eb7e4a9.png)
![image](https://user-images.githubusercontent.com/123030628/213319667-a3f2802a-45b4-4802-b28c-004e39397071.png)

### Save game

[bms-000.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10452042/bms-000.zip)

**Comment by IntelSupport-Arun** [comment]
Hi @AverageGithubBugReporter ,

These issues are known issues and have already been reported in the Steam Community.
For your reference, I'm sharing the link and you may give a try from your side:
Problem with the flashlight and textures : [flashlight and textures issue solution](https://steamcommunity.com/app/362890/discussions/0/2155476542897217516/) 
For other issues please check [MULTIPLE TROUBLESHOOTING TIPS](https://steamcommunity.com/app/362890/discussions/5/2270320616971963929/)

**Comment by AverageGithubBugReporter** [comment]
> Hi @AverageGithubBugReporter ,
> 
> These issues are known issues and have already been reported in the Steam Community. For your reference, I'm sharing the link and you may give a try from your side: Problem with the flashlight and textures : [flashlight and textures issue solution](https://steamcommunity.com/app/362890/discussions/0/2155476542897217516/) For other issues please check [MULTIPLE TROUBLESHOOTING TIPS](https://steamcommunity.com/app/362890/discussions/5/2270320616971963929/)

Alright, thank you for the info, appreciated
