### ISSUE TITLE
Intel wont show the correct Card and Speed in Intel Control Center and GPU-Z / Asrock A770 Phantom Gaming D 8GB OC

### ISSUE THREAD

**Issue by Darklegion1978** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#228]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows general

### Processor / Processor Number [Required]

I5 - 11400F

### Graphic Card [Required]

Intel Arc A770 Phantom Gaming D 8GB OC

### GPU Driver Version [Required]

- [X] 31.0.101.4034 (*latest*)
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

![Screenshot 2023-01-05 114808_Intel_Control_Center_A770](https://user-images.githubusercontent.com/123353653/213979486-a4806fc2-dcee-471f-ae61-e0757957bf25.png)
![Screenshot 2023-01-05 114839_GPU_Z_A770](https://user-images.githubusercontent.com/123353653/213979493-ff3441aa-cdf2-4ed1-bc41-a90fa1cbcf29.png)
[SSU_Log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10477310/SSU_Log.txt)

### Description and steps to reproduce [Required]

Hello,

i bought the Intel Arc A770 Asrock Phantom Gaming D 8GB OC Variant.

It will have 2200 MHz standard/base GPU Clock.

The Card has just 2100 MHz as the normal Intel Arc A770, thats also to see on the Screens from Intel Control Center as also at GPU-Z.

GPU-Z and the Intel Control Center, both are showing the Speed 2100 MHz and not the 2200 MHz.

So wheres the issue or Problem, are these the Drivers from Intel?
Card not identified correct?

Greetings Roman

### Device / Platform

Intel Arc A770 Asrock Phantom Gaming D 8GB OC

**Comment by Darklegion1978** [comment]
Got an Answer from Asrock Support, if it helps you.

"Intel also has notified us about the values showing on the Intel ARC control.
They will judge whether to change the values when detecting the Intel Arc A770 Phantom Gaming D 8GB OC."

Maybe you have the chance to get more into this and if its just a display failure, or the card wont recognized as an asrock card.

**Comment by IntelSupport-Arun** [comment]
Hi @Darklegion1978 ,
We are checking this and will come back soon.

**Comment by Darklegion1978** [comment]
> Hi @Darklegion1978 , We are checking this and will come back soon.

Thats really nice, Asrock is really no help.
Theyr telling me, all is fine and its part of Intel and the Intel Driver.

If they sell products from Intel and OC them, that the standard GPU Speed is higher, it should be so. 
Otherwise i can buy an original Intel Card, and Intel should not sell theyr Products anymore to Brands like Asrock.

Thanks in advance

Roman

**Comment by RhanCandia** [comment]
I can confirm that the Arc Control and GPU-Z is only reporting a base clock of 2050 (Intel base clock). My ASRock A750 is supposed to have a base clock of 2200 according to the product page.

![image](https://user-images.githubusercontent.com/7951366/214773370-9cdff3a8-e740-4cdf-98c7-a58da733bb31.png)

![image](https://user-images.githubusercontent.com/7951366/214773425-e33cbcc7-c10c-4be4-aa9e-ec16a380fb10.png)

**Comment by IntelSupport-Arun** [comment]
Hi @RhanCandia ,

We have been escalated to the next level and waiting for the response.
Will update you once we received a reply from them. Please stay tuned.

**Comment by IntelSupport-Arun** [comment]
Hi @RhanCandia ,
Below is the update from the Engineering Team -
_"We have tested with the  Asrock A770 8GB OC variant and can confirm that the gpuz is not notifying the correct gpu clock frequency. However, ARC control is showing the correct GPU clock running at 2300mhz. We also tested it with the HWinfo utility application to confirm that the GPU clock  was seeing was correct and was able to confirm. 
<img width="1182" alt="Tested with 4091 wGPUz2_52_0_HWinfo_NoActivity_Base_Clock" src="https://user-images.githubusercontent.com/91881865/217174848-e082b269-f2dc-45f3-b4d0-61b7bc83641c.png">

 If we don't run any application, the idling gpu clock frequency is 600MHz. If we put it under load, it shoots upto 2250-2300Mhz. The website does say 2200Mhz but mine goes above as far as base clock is concerned So, the customer would have to reach out to ASRock about this. Also ArcControl matches HWinfo GPU clock frequency so in this case, the suggested resolution would be to contact Asrock."_

**Comment by Darklegion1978** [comment]
Hi and thx for your Test and Answer.

Thats correct, under Load the Card Speeed goes up like the original Intel Card, tested both, the original and the asrock Card.

In Arc Control it doesnt show the corrct speed as like in GPU-Z, in both are just the 2100 MHz as Default Clock and not the OC default Clock.

![image](https://user-images.githubusercontent.com/123353653/217209475-550bedbb-3760-4ddd-abd4-bef4e3d51c96.png)

I wrote also Asrock, they told me, its not theyr fault its Intels Driver fault.

So Brand vs. Brand, but its not fair to the Costumers.

All other Brands like Nvidia or also AMD can show the correct Speed also the OC default one.

The Question is, is the Asrock an OC Variant or not, i guess its not. And its just a Marketing Gag.

Greetz

**Comment by IntelSupport-Arun** [comment]
Hi @Darklegion1978 ,

I just got the update from the Engineering team that they are able to reproduce the issue. 
For further debugging the issue they have submitted internal ticket and started working on this.
As a heads-up, it may take 3 to 6months to get implemented depending on the severity and priority of the request. 
You may please stay tuned for our updates. 
Thank you for the understanding.

**Comment by Darklegion1978** [comment]
> Hi @Darklegion1978 ,
> 
> I just got the update from the Engineering team that they are able to reproduce the issue. For further debugging the issue they have submitted internal ticket and started working on this. As a heads-up, it may take 3 to 6months to get implemented depending on the severity and priority of the request. You may please stay tuned for our updates. Thank you for the understanding.

Big big thx for your Answer, and that Intel will work on it.

Greetings

**Comment by EstebanIntel** [comment]
Hi @Darklegion1978,

After looking further into this issue, our conclusion is that Arc Control is intended to be used with the Intel Limited Edition Arc GPUs. So the reporting of GPU Frequency within the Intel Arc Control System Information page is populated with the base specifications for our graphics products and does not reflect overclocking or other frequency changes that may be made by our graphics manufacturing partners. We recommend you confirm your product specifications for frequency with the manufacturer of your graphics product.

**Comment by EstebanIntel** [comment]
Thanks for the info on the new Asrock FW update helping reduce idle power consumption @Darklegion1978, that is indeed a great data point for us!

Regarding this specific issue, can it be closed?

**Comment by Darklegion1978** [comment]
Hi @EstebanIntel 

Glad i could help a little. Yes it can be closed, hopefully the Speed will be corrected also in an upcoming FW Update. ;)

Greetings
