### ISSUE TITLE
Call of duty: warzone 

### ISSUE THREAD

**Issue by mva94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#23]
#### Game _[Required]_
Call of duty: Warzone

---
#### CPU _[Required]_
I7 1165g7 i71160g7 

---
#### GPU Driver Version _[Required]_

27.20.100.9313
---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_: DirectX 
**API Version** _(example DirectX 12)_: 12

---
#### Windows Build Number _[Required]_
Latest 

---
#### Description _[Required]_
Game runs very badly on tigerlake, shaders optimization lasts at least 30 minutes, once in game you get a lot of stutters and directx crashes.
The igpu is definitely powerful enough to run the games as from time to time it runs fine for 5 minutes and you get 60 fps at 800p.
---
#### Steps To Reproduce _[Required]_

---
#### Screenshots _[Optional]_

---

**Comment by leoben2** [comment]
Repro in progress, stay tuned.

**Comment by leoben2** [comment]
There are a few issues with this game on Intel gfx. We're working with the dev to see what can be done.

**Comment by mva94** [comment]
@leoben2 game starts one time out of ten and all the time you stay stuck during this load screen as you can see in the link
https://youtu.be/1XuNVWhadd8

**Comment by drbenko773** [comment]
Can confirm same issue on 1165g7, 16gb ram 4266. Have tried various drivers, was told 9616 was the one, same issues. Any progress on this issue??

**Comment by estebanr863** [comment]
Hi all,

The new driver version 30.0.101.1069 can now be downloaded at https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html.

This driver includes the possible fix for the performance issue reported. Please help us test it and let us know.

**Comment by mva94** [comment]
@estebanr863 as far as I can tell the game is definitely fixed,  I am going going to try a bit more in depth as I a few stutters, didn't have a very stable WiFi that's why I wanna double check
