### ISSUE TITLE
Deactivate CMAA setting when running the new 4091 driver installer

### ISSUE THREAD

**Issue by paulober** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#231]
### Application [Required]

Microsoft Windows Operating System

### Processor / Processor Number [Required]

Does apply to all processors

### Graphic Card [Required]

Intel Arc A*

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Other Windows build number

maybe also all other supported OS versions

### Describe the feature [Required]

Currently there is a bug if you've set CMAA in global driver settings in Arc Control to "Enhance Application" or "Force On", the new driver will make Windows ClearType not render correctly which causes WinUI 3 app as well as websites like YouTube, Twicht and many other apps and websites to have blurry text.
This issue can be fixed if you set this global setting to "Force Off" but unfortuneally Intel removed this setting from Arc Control and do not set it automatically to "Force Off" when installing the new driver which causes this feature to destroy you hole Windows Desktop and Web experience.

So the only way to fix this currently is by:
- either running DDU in safemode, then install the driver
- (Recommended) use a third party Intel Arc Driver configuration utility like the [Arctic Control project](https://arcticcontrol.paulober.dev) which still offers the option to set this feature to "Force Off" when goging to "Games" -> "Global Setttings" -> CMAA, then restart your PC and your good to go without having to reinstall and the driver with a tool like DDU

### Additional notes

Hope this helps other people searching for a solution to their system fonts getting blurry after the newest Arc driver update.

**Comment by paulober** [comment]
Solution for Intel devs would be following:
- set the CMAA driver setting to "Force Off" via the IGCL SDK as part of the new driver installer before it prompts the user to restart their system but after it installed the new driver.

**Comment by IntelSupport-Rozilah** [comment]
hi @paulober,
thanks for contacting Intel, can you please attach SSU log for us as a reference and provide a video recording of the issue if possible?, so that easy for us to start very the issue.

**Comment by paulober** [comment]
[Screen recording](https://user-images.githubusercontent.com/44974737/216580044-f80949d4-fe38-4c2c-99bb-428457049cde.mp4)
[More examples on the Intel Insider Discord arc support channel](https://discord.com/channels/554824368740630529/1070357324935471154)
[ArcFontBugScreenshot (left side)](https://user-images.githubusercontent.com/44974737/216580343-d1339568-bc45-4d3b-818f-d9ab358c7a79.png)
There you can see the issue and in the linked discord channel are more screenshots by other users expereiencing the same bug with the newest driver.
And here is an SSU log though SSU isn't supported on Windows 11 says its Intel website:
[ssu-log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10578121/ssu-log.txt)

**Comment by IntelSupport-Rozilah** [comment]
hi @paulober,
We were not faced blurry text issues on 31.0.101.4032, 31.0.101.4091 and 31.0.101.4123 but you are right, The CMAA was removed from Intel Arc Control on the latest driver 31.0.101.4091 and 31.0.101.4123. I already reported to the Internal team and will revert back once I get an update from them. Stay tuned!

**Comment by IntelSupport-Rozilah** [comment]
hi @paulober,
I just got a new update from internal and they informed that CMAA has indeed been removed from Arc Control, since the expectation now is for each game or app to implement the Anti-Aliasing (AA) directly. Removing this setting from Arc Control’s latest version is equivalent to setting it to “Application Choice” on older version. This means that it is up to the game, app or OS to decide if it wants to use any kind of AA and if the users want to disable it, they would need to do so in that specific game, app or OS.

**Comment by IntelSupport-Rozilah** [comment]
hi @paulober,
Please to inform that we are proceeding to close this case. If you require any further assistance please follow our suggestions and update your finding, then we will resume our support again. You may submit a new GitHub case if you have new questions and we are happy to assist you.

**Comment by IntelSupport-Rozilah** [comment]
hi @IGCIT please help close the case.
