### ISSUE TITLE
Games doesn't start

### ISSUE THREAD

**Issue by Mathieucoco37** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#232]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Fallout 4

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-9600k

### Graphic Card [Required]

A770

### GPU Driver Version [Required]

- [x] 31.0.101.4091
- [x] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[sytem.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10583327/sytem.txt)

### Description and steps to reproduce [Required]

this appear 
![Screenshot_20230203_054240](https://user-images.githubusercontent.com/74155844/216725599-39bd5de7-38c5-46f7-93ea-cdf99a514589.png)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

3872x2008

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Default settings

**Comment by Mathieucoco37** [comment]
Fallout 4 VR*

**Comment by Mathieucoco37** [comment]
![Screenshot_20230203_073152](https://user-images.githubusercontent.com/74155844/216735000-ae5f5532-e39d-43c0-bd7d-3d8000265eea.png)
VR games work perfectly fine

**Comment by XBravRevolutionz** [comment]
Have you reviewed your virtual memory settings? I encountered this error and it seems to have stopped after resetting my page file settings to allow Windows to auto-allocate, even though I had plenty reserved (32gb system ram with 16gb pagefile):

![image](https://user-images.githubusercontent.com/102002385/216853434-02f2e4e0-059b-4f30-8a0e-683d127d3fbd.png)

**Comment by IntelSupport-Arun** [comment]
Hi @Mathieucoco37 ,
We are checking this issue and will update you.
In between Did you try the same method recommended by @XBravRevolutionz ?

**Comment by Mathieucoco37** [comment]
![Virtual memory allocation](https://user-images.githubusercontent.com/74155844/217394787-945890f7-72a9-4443-9f2f-31547f4b8f6a.png)
it's doesn't appear to have change anything
I can mod the game to get logs, would that be useful?

**Comment by Mathieucoco37** [comment]
It's totally random, the text dxgi error only appear twist normally it's just crash

**Comment by Mathieucoco37** [comment]
And I got other games that are working when it want to start but it's 1/5 times the rest of the time it's just crash

**Comment by IntelSupport-Arun** [comment]
Hi @Mathieucoco37 ,

Are you seeing issues on Fallout 4 VR or Fallout 4?
![image](https://user-images.githubusercontent.com/91881865/217432919-21b04276-8072-4bbd-b1a8-cc977c81e18c.png)

**Comment by Mathieucoco37** [comment]
Fallout 4 VR
RM236.99

**Comment by IntelSupport-Arun** [comment]
Hi @Mathieucoco37 ,

Thank you for the quick confirmation.

I would like to know below details from your side:
1. Are you using a Single display or a Dual Display?
2. What is the refresh rate of your displays?
3. Display is connected to Arc display ports or System ports?

**Comment by Mathieucoco37** [comment]
Single display, 
-2560x1440
-144hz
-Connected to arc displayport 
-Cable isn't an issue *work perfectly with my nvidia Gpu*
Vr headset (oculus quest 2)
-1832x1920 x2 (3664x1920)
-120hz
-Connected through wifi using Virtual desktop

**Comment by Mathieucoco37** [comment]
I've try an other screen cable, it doesn't make a difference 
Just for you know, I got the same issue with Skyrim VR, So it may be a bug with bethesda engine
I said it was a "crash" but it more like a infinite loading/Freezing
There the log and a autoscan from a mod name Buffout 4 in Fallout 4, I don't know if it useful, but let's see
[crash-2023-02-08-23-54-05.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10691102/crash-2023-02-08-23-54-05.log)
[crash-2023-02-08-23-54-05-AUTOSCAN.md](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10691103/crash-2023-02-08-23-54-05-AUTOSCAN.md)

**Comment by Mathieucoco37** [comment]
I really hope it will work 
Thanks a lot, you are doing an excellent job

**Comment by Mathieucoco37** [comment]
There no cable to my vr headset, it's a streaming app named Virtual desktop that I use to connect my VR headset trought wifi

**Comment by Mathieucoco37** [comment]
But every other games that I try are working, so I don't think Virtual desktop is an issue

**Comment by IntelSupport-Arun** [comment]
Hi @Mathieucoco37 , 

Thank you for the quick confirmation.
Do you see the same issue with ALVR as well? Is there any other game that is working fine for you?

**Comment by Mathieucoco37** [comment]
I never try ALVR, I will when I'm back home
Until you fall, beat saber, Half life alyx (With Direct X 11, Vulcan doesn't), I expect you  to die, raw data, Hell Split... they are all working perfectly fine with Virtual Desktop

**Comment by Mathieucoco37** [comment]
I've try ALVR, there an issue with the streaming, rendering look fine on the desktop, but  I have artefact and somethings like 2 fps in the vr headset
I've try multiple bitrate, rendering resolution, encoder and to activate force CPU encoding but still not working
can I tweak something in those setting? I don't know what they are
![Screenshot_20230209_053855](https://user-images.githubusercontent.com/74155844/217956051-376a25f8-46fb-488d-9d7b-11f7c37f5679.png)

Intel encoder doesn't look to by supported 
![Screenshot 2023-02-09 174249](https://user-images.githubusercontent.com/74155844/217956413-b6c458ae-7e6e-473b-b339-2e56eb438ce3.png)

**Comment by IntelSupport-Arun** [comment]
Hi @Mathieucoco37 ,
I checking internally regarding the Vr headset (oculus quest 2) support. 
Please wait for my next response.

**Comment by Mathieucoco37** [comment]
I got no issue at all with the vr headset when i use virtual desktop on steam vr and all the other games that i've that are use direct X *Vulcan api isn't working  in VR with arc gpu*

Fallout 4 vr and skyrim vr are working perfectly fine when i swap my intel arc a770 with my rtx 2060 on the exact same configuration (exept gpu)

Step to issue :
1 : Connecting the pc on my oculus quest 2 using virtual desktop (no issue)
2 : In virtual desktop Lauching Steam vr (no issue)
3 : In steam VR, lauching Fallout 4 VR or skyrim VR (Game dosn't lauch the image freezing, steam vr is crashing, but virtual desktop still connected and working in VR

**Comment by IntelSupport-Arun** [comment]
Hi @Mathieucoco37 ,

I have checked this issue with the next level and here is an update from them "_Support for Steam VR is still being developed, so VR games are not currently supported on Arc. It will be announced once this support is added, but a target date is not available at this time._"

Since the VR is under development you have to wait for the next announcement. 
If you don't have any further questions we would like to close this case. Thank you for your understanding.

**Comment by IntelSupport-Arun** [comment]
Hi @Mathieucoco37 ,

Since the support for steam VR is still under development and  VR games are not currently supported on Arc.  I would like to close this case If you don't have any further questions.

**Comment by Mathieucoco37** [comment]
Fine I will wait, thanks
