### ISSUE TITLE
Severe Frame Drops in Halo Infinite When Looking At Water

### ISSUE THREAD

**Issue by JohnnyTex** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#234]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Halo Infinite

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5 12600k

### Graphic Card [Required]

ARC A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[24ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10610966/24ssu.txt)

### Description and steps to reproduce [Required]

Even when turning reflections off (which is something you must do to avoid graphical glitches on ARC), Halo Infinite's fps will frequently plummet when bodies of water come into view. An obvious example would be on the quickplay map Recharge. When simply playing on the regular portions of the map, I was getting a pretty solid 120fps experience, give or take some. but when you go to the back of the map where the water is, and you get close and look down into it, the fps plunges all the way down to around 60fps for me. Halo Infinite seems to be a pretty problematic title for ARC in general, but this issue is one of the worse ones. 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560 x 1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

I have most everything set to high.

**Comment by IntelSupport-Rozilah** [comment]
hi @JohnnyTex,
can you please attach a video game recording if possible so that easy for us to identify the issue?

**Comment by JohnnyTex** [comment]
So, I presume I won't have to go around providing that footage now? I still can ofc, just checking.

**Comment by IntelSupport-Rozilah** [comment]
hi @JohnnyTex,
we were able to replicate the issue, so no need for that footage for now.  Just wait for the fix and stay tuned!

**Comment by JohnnyTex** [comment]
I just want to update this by saying the issue isn't *strictly* limited to just water, many maps have issues when viewing the edges of the map. For example, On the Big Team Battle map Breaker looking out to the map's foreground from the base at the bottom of the map results in the fps plunging into the 40s, and on the core map Catalyst when trying to view the the sunset in the background a similar dive in fps occurs.

**Comment by Arturo-Intel** [comment]
As Rozilah says before the fix may take 3 to 6 months to be included.

But I did a quick check with the latest 4146 and I notice a considerable FPS improvement on the game. 
Still I see the FPS drop, specially on the water in Recharge map, but is less noticeable.

Anyway the team is still working on this,
Thanks for your patience and feedback.

**Comment by JohnnyTex** [comment]
These update messages are very much appreciated! Just knowing y'all haven't forgotten about the issue is good enough for me lol.

**Comment by Arturo-Intel** [comment]
Glad to help!

**Comment by Arturo-Intel** [comment]
@JohnnyTex  Can you check if this behavior is still happening in beta 4311 from your side? 
There are a huge improvement on the FPS drops!!

**Comment by JohnnyTex** [comment]
Yes there has been! I've been making updates on this issue elsewhere, but totally forgot to do it here on Github. Almost every issue in Halo Infinite has been completely and totally eliminated, and performance is now freakishly good. Very well done!
