### ISSUE TITLE
Monitor sometimes will not turn on

### ISSUE THREAD

**Issue by gargamel314** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#236]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Boot

### Processor / Processor Number [Required]

13700K

### Graphic Card [Required]

A770

### GPU Driver Version [Required]

- [X] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[System Support Utility Report 2-7-23.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10681716/System.Support.Utility.Report.2-7-23.txt)

### Description and steps to reproduce [Required]

I have 2 monitors plugged into 2 DP ports. When I boot my computer, occasionally monitor plugged into the middle DP port will not turn on, regardless of Windows Projection mode. The monitor acts like there is no cable plugged in, and goes to standby mode, windows makes the other monitor my default screen.  This fixes itself upon a system restart. It has happened 3 times since I installed the card 5 days ago.  Before Windows even loads, that monitor is blank and text showed up on the other monitor. It usually shows up on the monitor in question.

### Device / Platform

ASUS Strix Z690-A D4

### Crash dumps [Required, if applicable]

n/a

### Application / Windows logs

[Error Log.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10681695/Error.Log.zip)

**Comment by gargamel314** [comment]
Also, I do have Parsec Virtual Display Driver installed.

**Comment by IntelSupport-Rozilah** [comment]
hi @gargamel314,
Thanks for contacting Intel, can you please attach a video game recording if possible so that easy for us to identify the issue?

**Comment by IntelSupport-Rozilah** [comment]
hi @gargamel314,
 do you have any updates?
can you please provide details/settings of the monitor display that you used?

**Comment by gargamel314** [comment]
Hi there, it's happened a couple times since I wrote this post. I didn't attach a video game recording because it wasn't relevant to any video game - just at computer start up. I've reconnected the monitor to the unoccupied Displayport jack and it hasn't happened since so far.

This monitor does start up every time at boot with a blank screen for about 12 seconds before Windows 11 begins loading. 

Monitor settings:
Viewsonic VX-2KP-MHD 2560x1440 resolution @ 144 Hz (native), Adaptive Sync enabled, connected via Displayport.

**Comment by IntelSupport-Rozilah** [comment]
hi @gargamel314,
Did you use the same type of monitor for both displays?
did you observe the issue on the Beta version https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html?

**Comment by gargamel314** [comment]
They are different displays. The other is a Dell U2715H 2560x1440 @ 60Hz. This has not happened since installing the 4123 beta drivers.

**Comment by IntelSupport-Rozilah** [comment]
hi @IGCIT , please help to close the case since the issue was fixed on the 4132 driver.
