### ISSUE TITLE
Implement DXVK layering to DX11 as well

### ISSUE THREAD

**Issue by JohnnyTex** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#237]
### Application [Required]

DX 11 Games (For reference, Sonic Frontiers)

### Processor / Processor Number [Required]

i5 12600k

### Graphic Card [Required]

ARC A770 LE

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

W/ the implementation of a DXVK-esque layering to DX9 games leading to a huge boost in performance in games like CS:GO and whatnot, it's only sensible in my opinion to extend this to DX11 games as well. Having used DXVK Async recently in Sonic Frontiers, the game went from stuttering all the way down to 25fps at points to running at a silky smooth 60fps w/ almost no drops. Considering that many modern titles continue to use DX11, I think it's a no-brainer to say that improving ARC performance in those titles should be of high priority, and this seems to be one of the most straight forward ways to go around doing that.

**Comment by IntelSupport-Arun** [comment]
Hi @JohnnyTex ,

We always consider and appreciate suggestions for Intel Arc, and I would like to thank you for your interest and effort. Based on your request, I have also created an internal improvement request and passed it along to the concerted team. 
We have added your suggestions to our tracking system and will consider them.
As a heads-up, it may take some time to get implemented depending on the severity and priority of the request.

If you do not have any further questions, we can close this case.

**Comment by IntelSupport-Arun** [comment]
Hi @IGCIT , Based on the customer improvement request we have already raised the ticket for the Feature implementation.
 It may take time to implement depending on its severity and priority.
So please close this case as there is no further request from the customer.
