### ISSUE TITLE
Make an Intel version of RSR

### ISSUE THREAD

**Issue by JohnnyTex** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#238]
### Application [Required]

For all games

### Processor / Processor Number [Required]

i5 12600k

### Graphic Card [Required]

ARC A770 LE

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

While XeSS is impressive in its own ways (along w/ having its own cons), it's still far from reaching the level of adoption to properly rival the usage of DLSS or FSR. One way to give players a more universal performance uplift would be to implement an Intel version of AMD's RSR, which isn't dependent on individual developers and their games adopting the technology.

**Comment by IntelSupport-Arun** [comment]
Hi @JohnnyTex ,
It is always appreciated when you suggest improvements to Intel Arc, and I would like to thank you for your interest and efforts. In response to your request, I have also created an internal improvement request and forwarded it to the concerted team.
Also, we have added your suggestions to our tracking system and will consider them.
Please note that it may take some time for it to be implemented depending on its severity and priority.

If there is nothing to discuss further we would like to close this case. Thanks.

**Comment by IntelSupport-Arun** [comment]
Hi @IGCIT , Based on the customer improvement request we have already raised the ticket for the Feature implementation.
 It may take time to implement depending on its severity and priority.
So please proceed to close this case as there is no further request from the customer side.
