### ISSUE TITLE
Forza Horizons 4 and 5 : Graphic Corruption in GPS Mini-map on driver 4091 and later

### ISSUE THREAD

**Issue by Saracchini** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#239]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Forza Horizons 5

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel i7 1165g7

### Graphic Card [Required]

Intel Iris Xe (integrated GPU)

### GPU Driver Version [Required]

- [X] 31.0.101.4123
- [X] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [X] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[fh5_intelSSU_4123.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10695890/fh5_intelSSU_4123.txt)

### Description and steps to reproduce [Required]

How to reproduce:
- Start the Game
- Exit House/Garage/Horizon Festival secreen (i.e start free roaming)
- Press Start/Esc to enter in the main game menu 
- Go to another section such as "My Horizon", "Online" or "Creative Hub". Entering in subsections like  "My messages" make the issue to occur more often
- GPS Map starts to have graphic corruption issues like weird colours with serrated edges 
- Issue looks like typical DX12 texture corruption in Iris XE as reported in those two issues [here](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/74#issue-967214384) and [here](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/75) 
- Issue does not happen in 4032 driver or earlier.

![fh5_issue](https://user-images.githubusercontent.com/18572281/217782243-efa8e01d-1e60-4731-96e4-e837a6b2ee06.png)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![fh5_settings_0](https://user-images.githubusercontent.com/18572281/217783348-8db47e1c-cf4b-4a30-9add-0597d85bddfa.png)
![fh5_settings_1](https://user-images.githubusercontent.com/18572281/217783358-7a0de8e4-9d60-4a62-a69e-a87d2104ffd6.png)
![fh5_settings_2](https://user-images.githubusercontent.com/18572281/217783364-db43e554-dbd0-4328-85b3-5f54ecf54ea4.png)
![fh5_settings_3](https://user-images.githubusercontent.com/18572281/217783374-8d37f4a2-0de5-41d0-a5a2-7b9f163c4148.png)

### Device / Platform name

GPD Win3 (i7 1165g7)

**Comment by IntelSupport-Arun** [comment]
Hi @Saracchini ,

We will verify the issue from our side and let you know the update.

**Comment by IntelSupport-Arun** [comment]
Hi @Saracchini ,
Im seeing a different issue with the game Forza Horizon 5, when I launch the game its crashes.
Have you seen this issue before?

**Comment by IntelSupport-Arun** [comment]
Hi @Saracchini ,

Thank you for the confirmation.
There is a new Beta driver version [31.0.101.4125](https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html) has been released. Could you check and confirm issue is still seeing with the latest driver.

**Comment by IntelSupport-Arun** [comment]
Hi @Saracchini ,

Thank you for the confirmation.
There is a new Beta driver version [31.0.101.4125](https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html) has been released. Could you check and confirm the issue is still seeing with the latest driver?

**Comment by Saracchini** [comment]
Issue still persists in 4125.
On top of that, i just found out this issue also happens in Forza Horizons 4 as well, but less frequently, and often caused by entering in the map screen and selecting a navigation point, then return to free-roaming.

**Comment by IntelSupport-Arun** [comment]
Hi @Saracchini ,

Thank you for the update.
Could you check this issue in higher resolutions or 4k monitors? Or is this issue specific to the resolution 1280 x 720?

**Comment by Saracchini** [comment]
I have a 4K monitor I can check. 
Do you think it could be also due the portrait screen of the GPD Win3  ?

**Comment by Saracchini** [comment]
I see the issue with 2560x1440 resolution almost immediately, but no matter what I could cause it with 4096x2304...
In fact I could not cause it later with 2460x1440 after switching back from 4096x2304.

**Comment by IntelSupport-Arun** [comment]
Hi @Saracchini ,
Sorry for the confusion. Are you still seeing the issue after switching back from  4096x2304? or issue is specific at and below 2560x1440?

**Comment by Saracchini** [comment]
The issue happens with 2560x1440 or lower resolutions.
I did not see it happening with 4096x2304, or going to 4096x2304 and changing back to 2560x1440 and trying to cause the glitch (i.e. entering in the menus/map/My Horizon)

**Comment by Saracchini** [comment]
Issue still persists on 31.0.101.4146.

**Comment by Karen-Intel** [comment]
Hi @Saracchini thank you for the update. I will check on my end and get back to you as soon as possible

Thanks

Karen

**Comment by Karen-Intel** [comment]
Hi @Saracchini 

After several attempts of trying to replicate the strange behavior in this post, I've not been able to. 
I have an11th Gen, Desktop + with the same configuration in the pictures and low resolutions; so far: no luck. 
If you could share a video on how you reproduce it + any extra configuration you have (I see Anna enabled on your mini map), that would help us a lot.
With driver 4146 I do not see any graphic corruption in the GPS map. Keep me posted

Karen

**Comment by Saracchini** [comment]
Here is one video. I can reproduce it very consistently. 
<iframe src="https://player.vimeo.com/video/806549229?h=4c5d7adb09" width="640" height="564" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
Note that a GPD Win3 has a portrait screen. Not sure if it's related as I managed to reproduce it on an external monitor as well

**Comment by Karen-Intel** [comment]
Got it! Okay.
Just found a machine that is just like yours. I will bring more updates soon. If I have questions I will be back
Thanks for sharing the evidence
Karen

**Comment by Karen-Intel** [comment]
Hi @Saracchini 
After another series of attempts in another machine, I have not been able to reproduce the map corruption 
I proceeded to free roaming, jumping between message center, clicking messages, etc, back to driving. No corruption shows
I'm curious: Can you confirm if you have already upgraded your driver version to v.4146 performing a clean install with [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html)?
I'm asking because I've been trying to reproduce the same odd choppy blocks in GPS map in 2 machines and I'm still unable to reproduce.
I'm testing in a i5-1135G7+ Intel Iris Xe + Graphics driver v.4146, low resolution (144Hz) and same game settings

Please let me know if you have tried a clean driver install, thanks

Karen

**Comment by Saracchini** [comment]
I just tried a clean driver install with DDU. 
I also forced the game to rebuild it's shader cache from scratch after a clean install (i.e trigger "Optimizing for your pc... please wait"  screen).

The issue keeps happening by doing as I demonstrated in the video.  Before and after forcing shader cache creation.  This do not happen in 4032 or older drivers.

I noticed also that the Car Collection menu also has a strange gray border in unselected cars. 
I see the same issues as well in Forza Horizons 4, and sometimes the glitched graphics appears in text and menus.

**Comment by Saracchini** [comment]
Issue persists with 4148 driver in both games.

**Comment by Saracchini** [comment]
Tested with driver 4255. I cannot reproduce anymore the issue, and played the game for near 2 hours and no one of the issues (GPS map corrupted, corrupted graphics on Car Collection) appeared, even after a restart. 
I do not see the issue with Forza Horizons 4 either, but has much less playtime with it and the new driver.


If I do not manage to trigger the issue in the following days, I think the issue can be closed.

**Comment by Karen-Intel** [comment]
Hey @Saracchini that is great! Our debug team is actively working on this issue
Please let me know if you spot it again so I can add that info internally
Have a good day!

Karen

**Comment by Karen-Intel** [comment]
@Saracchini can you confirm if issue is not visible anymore with latest driver?

Thanks!

Karen

**Comment by Saracchini** [comment]
Yes. I cannot reproduce it anymore with latest drivers. 
I'm closing the issue.
