### ISSUE TITLE
Street Racing Syndicate

### ISSUE THREAD

**Issue by Gx1-Al** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#24]
#### Game _[Required]_

Street Racing Syndicate

---
#### CPU _[Required]_

I7 1165g7 i71160g7

---
#### GPU Driver Version _[Required]_

27.20.100.9168

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_: directx
**API Version** _(example DirectX 12)_:  DirectX 9.0b

---
#### Windows Build Number _[Required]_

19042.804

---
#### Description _[Required]_

game freezes and crashes. event viewer says igdumdim32.dll is the error
---
#### Steps To Reprodusce _[Required]_

---
#### Screenshots _[Optional]_

---
#### Notes _[Optional]_

its an older game so should be playable

**Comment by estebanr863** [comment]
Hi @Gx1-Al, we were not able to reproduce this issue with the lastest drivers. Can you please perform a [clean install](https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html) of the [latest drivers](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) and try again?

**Comment by estebanr863** [comment]
Hi @IGCIT & @Valkirie,

We cannot reproduce this issue on our lab and there is no answer from @Gx1-Al.

From our experience, errors related to igdumdim32.dll can arise for a few different different reasons. For instance, a faulty application, igdumdim32.dll has been deleted or misplaced, corrupted by malicious software present on your PC or a damaged Windows registry. This is usually not related with the graphics drivers.

The posible solutions are to try and reinstall the game, and if that doesn't help, perform a clean install of windows and then reinstall the game.

Do you think this issue can be closed?

**Comment by IGCIT** [comment]
yeah, we can re-open if someone else have issues and more info.
