### ISSUE TITLE
[display]output show black screen or no signal on windows

### ISSUE THREAD

**Issue by wenqingx** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#241]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

display

### Processor / Processor Number [Required]

12th Gen Intel(R) Core(TM) i5-12400   2.50 GHz

### Graphic Card [Required]

Intel(R) Arc(TM) A380 Graphics

### GPU Driver Version [Required]

- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [X] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [X] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

The machine is usually used for media testing

### Description and steps to reproduce [Required]

This A380 machine usually does not use HDMI connection, but uses VNC for control. If it does not operate for a long time, it will appear black screen.

**Comment by IntelSupport-Rozilah** [comment]
hi @wenqingx,
Thanks for contacting Intel, can you please attach SSU detail as our reference?.
1. This A380 machine usually does not use HDMI connection, but uses VNC for control. If it does not operate for a long time, it will appear black screen. --> may i know how long time that issue will happen? and do you set the sleep set to never before the issue happen?
2. When the black screen appears, did you try to ping the system and make sure the system is not down at that time?

**Comment by wenqingx** [comment]
> hi @wenqingx, Thanks for contacting Intel, can you please attach SSU detail as our reference?.
> 
> 1. This A380 machine usually does not use HDMI connection, but uses VNC for control. If it does not operate for a long time, it will appear black screen. --> may i know how long time that issue will happen? and do you set the sleep set to never before the issue happen?
> 2. When the black screen appears, did you try to ping the system and make sure the system is not down at that time?

1.config:Modify the powerplan to disable auto sleep/shutdown for the device; Open Development Mode for the device.
If do not restart or connect to HDMI, this problem will continue consistently.Of course, we will repair it in time after finding it, so we can't determine the maximum duration, but we can determine that it can't recover automatically.
2.When the black screen appears, I can still connect it through VNC. The connection is successful, but it is not displayed

sync the status with @Bin-CI

**Comment by IntelSupport-Rozilah** [comment]
hi @wenqingx, I saw you used for older graphic driver version,(31.0.101.3959), can you try on latest graphic driver version 31.0.101.4091 https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html? ?

**Comment by wenqingx** [comment]
> hi @wenqingx, I saw you used for older graphic driver version,(31.0.101.3959), can you try on latest graphic driver version 31.0.101.4091 https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html? ?

OK, I will update the latest version and try it.

**Comment by wenqingx** [comment]
> hi @wenqingx, I saw you used for older graphic driver version,(31.0.101.3959), can you try on latest graphic driver version 31.0.101.4091 https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html? ?

Last week I updated to the latest. But today I use vnc to connect and still have a black screen.

**Comment by IntelSupport-Rozilah** [comment]
can you provide the link of the VNC that you used so that we are on same page?

**Comment by wenqingx** [comment]
@IntelSupport-Rozilah  Thank you very much for your timely response to this question. I will ask about our discussion as soon as possible and provide more help for you to reproduce this question.

**Comment by wenqingx** [comment]
Hi @Karen Gutiérrez ,sync with @IntelSupport-Rozilah ,you will continue to help solve this problem.
With the help of @ IntelSupport Rozilah, we changed the "intel display powerplan" from "balance" to "maximum performance", but the problem has not been completely solved. The DGPU driver will still be lost and needs to be reinstalled.
This time, the VNC connection did not appear black, but it was loaded with igpu.thanks.

**Comment by Karen-Intel** [comment]
Hi @wenqingx 

Alright, let me have a look and I will get back to you. Talk to you soon

Karen

**Comment by wenqingx** [comment]
> Hi @wenqingx
> 
> Alright, let me have a look and I will get back to you. Talk to you soon
> 
> Karen

Hi , Has this issue been updated recently?
My support for this project is up to WW13 (2023.3.31). If there are subsequent updates, you can connect @Bin-CI

**Comment by Karen-Intel** [comment]
HI @wenqingx apologies for the delay. We had a big hw update in our systems 
We have not been able to reproduce on our end with the latest driver, [v.4255](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?) . We also recommend to try with [DDU ](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html)when we start seeing issues so if you can perform the upgrade with it, we'd appreciate it.
@Bin-CI could you check on your end if the issue persists? Keep me posted, thanks

Karen

**Comment by Karen-Intel** [comment]
Hey @Bin-CI thank you for confirming the issue has been fixed using driver v.4255 + DDU
We will proceed to close this post, thank you for your help

@IGCIT could you help us close this post? Fixed with latest official driver

Karen
