### ISSUE TITLE
Update: No Progress Made, Mistaken Update (Assassin's Creed Unity is broken on ARC)

### ISSUE THREAD

**Issue by JohnnyTex** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#244]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Assassin's Creed Unity

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5 12600k

### Graphic Card [Required]

ARC A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[4123ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10737677/4123ssu.txt)

### Description and steps to reproduce [Required]

The game runs at an unplayable 20fps no matter the settings. 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560 x 1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

While I used to play the game on the high preset more or less, the game runs at 20fps max no matter what preset I'm applying, seemingly no matter what setting I put it to.

**Comment by IntelSupport-Rozilah** [comment]
hi @JohnnyTex,
Thanks for contacting Intel, we will start verifying the issue once the system is ready and stay tuned!.

**Comment by 3EyedBlinky** [comment]
Hey, I want to confirm this issue is real. AC Unity on Windows 11 22H2 and the latest driver as of 3/2. You can simply reproduce the issue by launching the game and playing it. You will notice the GPU usage is pegged to 100% for an unknown reason and the fps is poor regardless of graphics preset being low or ultra high. Usage stays 100% like something is just overloading the entire gpu and the game only runs at 17-20fps.

**Comment by JohnnyTex** [comment]
Has anyone managed to check if this has been fixed on 4311? I don't have the game installed at the moment and am not looking forward to the download.

**Comment by Karen-Intel** [comment]
Hey @JohnnyTex can you check this thread? We have seen performance improvements in other AC games using the latest driver, the latest DDU and dxvk

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/289

Maybe this will answer your inquiry as other users have already tried

Karen

**Comment by JohnnyTex** [comment]
Well like I mentioned I don't have the game installed atm, and I'm pretty sure I'll have to uninstall quite a few games to make the necessary space for it. I'll see if I can do that, but no guarantees that will be anytime soon.

**Comment by JohnnyTex** [comment]
I actually got to try it out for a little bit today. Things have been improved so that the game isn't stuck at 20fps, the game still isn't quite playable due to frequent "pauses". The game will be running more or less fine for a little bit, and then the game will almost freeze before going back to being playable, so on so forth.

**Comment by Karen-Intel** [comment]
@JohnnyTex Ooookay, gotcha, these details are good
I have to do pretty much the same (uninstall some games) so I will get on with it and provide an update this week for you

Karen

**Comment by JohnnyTex** [comment]
I was wrong, I totally forgot I had dropped in DXVK at some point in the past to try and make the game playable. The reason AC Unity seemed to work now is because I still had those DXVK files inside. When I removed the DXVK files, the game showed 0 progress, and was locked at 20fps. Now, this is technically still an improvement; after all, prior to the newest driver DXVK would just crash the game. But w/o DXVK, this game is still unplayable.

**Comment by JohnnyTex** [comment]
Any update? This issue remains as of the newest driver.

**Comment by Karen-Intel** [comment]
Hey @JohnnyTex 

Our dev team is still working on this issue and we're waiting for the target release for the fix to be included, which may happen in the following weeks. Wil update this thread once it is ready for you guys to verify.

Karen

**Comment by JohnnyTex** [comment]
The fix has been rolled out and it works very well. Better yet, it's not a fix using DXVK - thus, while the *raw* performance is still lower than what DXVK offers (60-80 fps as opposed to 100-120 fps), I consider this issue resolved. I hope this heralds a major step forward for DX11 compatibility.
