### ISSUE TITLE
Option to Selectively Turn Off Specific ARC Updates

### ISSUE THREAD

**Issue by JohnnyTex** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#245]
### Application [Required]

Intel ARC

### Processor / Processor Number [Required]

i5 12600k

### Graphic Card [Required]

ARC A770 LE

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

On earlier versions of ARC, there wasn't an annoying set of notifications that popped up every time say a controller was plugged in and unplugged. This is honestly very, very annoying, and I wish there was a way to turn it off. You can turn other notifications off, why not this one?

**Comment by IntelSupport-Rozilah** [comment]
hi @JohnnyTex,
can you attach the screenshot of the issue and specified which ARC version to help us for identify the issue?

**Comment by JohnnyTex** [comment]
![20230216_011502](https://user-images.githubusercontent.com/77827332/219294557-1a47a96e-d952-4632-aa7d-5d208967aa55.jpg)

**Comment by JohnnyTex** [comment]
That always pops up when I unplug my controller, switch it to wireless, turn it off, and replug it.

**Comment by IntelSupport-Rozilah** [comment]
@JohnnyTex,
thanks for the quick reply and will start verifying the issue soon.

**Comment by IntelSupport-Rozilah** [comment]
hi @JohnnyTex,
can you please try to give the setting below to help you turn off the non-essential pop-up?
1. Launch Intel Arc Control
2. Go to Setting icon -> App Preferences -> Notification  -> Show notification : Off
3. Close the Intel Arc Control and the notification will not appear after that.
Please let me know if it is working for you.

**Comment by JohnnyTex** [comment]
Unfortunately no, I did as you told and the notification still pops up.

**Comment by IntelSupport-Rozilah** [comment]
did you reboot after giving the setting?, it is working from our end after set this setting.

**Comment by JohnnyTex** [comment]
Oh, I didn't reboot my PC. That did the trick! I'll revise my title post so that it's more constructive.

**Comment by IntelSupport-Rozilah** [comment]
Thanks @JohnnyTex for the confirmation and please feel free to close the issue. You may submit a new GitHub case if you have new questions and we are happy to assist you.

**Comment by JohnnyTex** [comment]
Sure thing.
