### ISSUE TITLE
Disastrous State: Season 2 of Modern Warfare II Has Devastated ARC Performance

### ISSUE THREAD

**Issue by JohnnyTex** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#246]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Call of Duty: Modern Warfare II

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [X] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5 12600k

### Graphic Card [Required]

ARC A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[4123ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10750771/4123ssu.txt)

### Description and steps to reproduce [Required]

Now that Season 2 of MW2 has dropped, performance for ARC has been severely nerfed. On Taraq, I'm now getting 75-ish fps when previously I was getting around 100. On the Hotel map, I'm now locked to the lower 100s when previous it would run consistently at the 120-130fps mark. 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560 x 1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

I'm using XeSS on top of a slightly modified Ultra preset.

**Comment by IntelSupport-Arun** [comment]
Hi @JohnnyTex ,

You have already filed a similar issue #242. Could you list changes in the settings you have made to cause this issue?
If both are similar issues can we track them in one issue #242?

**Comment by JohnnyTex** [comment]
No, they're separate for a reason. #242 is about XeSS' performance in relation to other upscalers, this thread is about how MW2 now runs worse on ARC after the update, not about how well XeSS itself performs. For further context, on Farm 18 before the Season 2 update I was getting 100fps consistently, but now it constantly goes between 100fps and somewhere in the 90s (w/ dips in the 80s).

**Comment by JohnnyTex** [comment]
Have to update the title, bc it's truly disastrous now, where the game's performance is on ARC. El Asilo, a map that once consistently ran at the 100fps mark w/ occasional dips into the 90s, now runs around the 75-85 fps mark, w/ plunges into the 60s. This isn't a large map, it's not a Warzone/DMZ map, this is a core game mode map and w/ performance like this, the A770 is on par w/ something like the Xbox Series S, not the RTX 3060 I believe. This must be addressed ASAP!

**Comment by IntelSupport-Arun** [comment]
Hi @JohnnyTex ,

Thank you for the confirmation.
There is a new Beta driver version [31.0.101.4125](https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html) has been released. Could you check and confirm the issue is still seeing with the latest driver?

**Comment by JohnnyTex** [comment]
Just played some rounds, and tragically I can say that there was no noticeable improvement. Maps still run at much, much slower speeds than before. I was on Al Bagrah Fortress, a map that once comfortably ran at the 90fps range (if not 100), and it's now barely an 80fps map. On Las Almas, a map that once ran at a smooth 100-120fps range (and often punching up to the 130s) it now ran at only 90 fps, w/ frequent dips into the 80s.

**Comment by JohnnyTex** [comment]
Hang on, I'm testing something that may change the outlook of this issue. Give me the day or so to get this right please.

**Comment by JohnnyTex** [comment]
Yeah, it remains the case sadly. Interestingly enough this only seems to be happening at 1440p; a user on Discord informed me that at 1080p the game runs _smoother_ than before. Another use has confirmed to me that they noticed a similar performance drop at 1440p. Yes, this persists to the latest driver.

**Comment by IntelSupport-Arun** [comment]
Hi @JohnnyTex ,

We have purchased the game and checking the issue on our side. Will update you on the observation. Please stay tuned.

**Comment by JohnnyTex** [comment]
If it helps, I'd like to reiterate that I was running the game on the Ultra preset w/ virtually no edits. I'm sure if you were willing to individually adjust each setting you can get a better result.

**Comment by JohnnyTex** [comment]
I hope the investigation over there is going well. On my end, the performance is just so bad, and I have other games to play/things to do, that I'm likely to uninstall the game somewhat soon now, so I will be unable to further assist in any fact-finding and whatnot. Apologies.

**Comment by Arturo-Intel** [comment]
If I understand correctly, the "new" season 2 comes the FPS drops? You where using the same drivers before and after updating to season 2? Did you try with the latest driver?

Sorry for not updated this in a long time, It just got lost from the bunch I have right now

**Comment by JohnnyTex** [comment]
Trust me, I've been really busy myself so I've been slipping too lol, dw about it. 

Yeah, back when S2 dropped, there was no new ARC driver, it was just the season that changed. The connected Discord post showed this verified by others too.

**Comment by JohnnyTex** [comment]
Though we're towards the end of Season 3 now, so the issue has seemingly stubbornly persisted. I can run more tests when I'm on break.

**Comment by JohnnyTex** [comment]
https://youtu.be/b4RPVNhUwSg?t=833

This YouTuber noted similarly poor performance in Warzone 2, something I can vouch for having just tested it. This is WZ, not regular multiplayer, so it's not exactly the same, but still. ARC is pretty far behind in this game overall.

**Comment by JohnnyTex** [comment]
An addendum; the worsening performance numbers apply to WZ2 as well, so the above comment is relevant. Earlier on it wasn't uncommon for me to get around 85fps as my average, now unless I'm looking into a corner there's no way I get above 70, and it's often in the 60s.

**Comment by Arturo-Intel** [comment]
Yeah, that behavior (FPS below the 70) its already being reported to the devs team. 
Something to say is that on the version 4502 there was an improvement vs the previous versions
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/a7119239-cf99-4497-98ad-afd067d2897b)

Still not as good as what we have before with the 4369
I will keep you posted here
-- r2

**Comment by Arturo-Intel** [comment]
@JohnnyTex 
Did you try with the latest beta driver [101.4575](https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html?)?

**Comment by JohnnyTex** [comment]
No, not yet. I actually don't have the game installed atm, so I tragically won't be of much help right now. Did 4575 show signs of improvement on y'all's end?

**Comment by Arturo-Intel** [comment]
Well, I am sure we have a good level of quality on this driver, still, it does not reach the FPS that you say it was previous season 2.
For example:
On Taraq I am getting this data:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/959de509-980b-49b3-9dec-323d7ac50974)
But is using bots and I am not sure if that affects performance

So I played some matches and got a respectable 90ish FPS in average
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/6fefe7dd-f9ae-46b8-bff2-9f925629204f)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/a130ff2c-e959-4564-8ecf-80e90ab1ebdc)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/d4b66edb-b2bf-4e85-89af-c9cf28c09d5e)

Still I want to play Taraq without bots, is there a way to select a map in a match?

--r2

**Comment by JohnnyTex** [comment]
No sadly, it's up to which map is offered/voted on by the players. Also, are you using the same settings as before?

**Comment by Arturo-Intel** [comment]
Yes, Ultra quality, XeSS with Performance profile at 1440p

**Comment by Arturo-Intel** [comment]
I was reviewing the whole story of this case and notice we don't have a pre season 2 benchmark evidence, meaning we don't have data to compare (only the affirmation @JohnnyTex described in this case). 
>Now that Season 2 of MW2 has dropped, performance for ARC has been severely nerfed. On Taraq, I'm now getting 75-ish fps when previously I was getting around 100. On the Hotel map, I'm now locked to the lower 100s when previous it would run consistently at the 120-130fps mark.

I run some benchmarks using 101.4123 in the season 4 and this is what I got:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/fef1cb0f-382b-40e2-942c-b7e55fd6e385)

The FPS on both drivers is almost the same.

The fact that the RTX 3060 is running way better using XeSS on this game Is another issue that it is being attended in other case. #242 
Without the XeSS or another upscaler, Arc770 has the lead on the FPS.

Another thing is the fact that this behavior was reported when season 2 started, this leads us to the assumption that maybe there was some game code changes that were affecting the FPS performance.

Unfortunately without any data to compare it is hard to make a solid case.
AFAIK there is no way to get the pre season 2 data to compare directly (if there is a way, please share it I will love to get that data in my hands). 

Therefore I will request to close this case (@IGCIT) 

--r2

**Comment by JohnnyTex** [comment]
I concur, this specific phenomenon is likely beyond anyone's control. I think resolving #242  is gonna be the best way to improve performance in this game. I think this issue was corroborated in a Discord version of this report though, so you could try looking there for some more reports. Anyhow, I'll go ahead and close this one.
