### ISSUE TITLE
VALORANT missing Multithreaded Rendering Option

### ISSUE THREAD

**Issue by OhSaft** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#248]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

VALORANT

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

Riot Launcher

### Processor / Processor Number [Required]

12600K

### Graphic Card [Required]

A770 LE

### GPU Driver Version [Required]

- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [X] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10766466/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Start up the game.
Go to settings (top right corner).
Go to video settings.
Go to graphics quality.
The setting should appear at the very top of the list, but it's missing.

It requires some minimum system specs to show up (https://support-valorant.riotgames.com/hc/en-us/articles/4408444846355-Multithreaded-Rendering), but the only thing that changed is the video card so it can only be due to the VRAM, which I assume VALORANT fails to figure out the amount of? It worked with a 3070ti before. Nothing else changed.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Those do not matter, as it is a single setting that just does not show and it has no relation to other settings.

**Comment by IntelSupport-Rozilah** [comment]
hi @OhSaft,
Thanks for contacting Intel, we will start to verify the issue once our system is ready. Stay tuned!

**Comment by IntelSupport-Rozilah** [comment]
hi @OhSaft,
The case has been verified on our side and we are able to reproduce it with our configurations as below:
Processor Name: Intel(R) Core(TM) i7-11700K
Driver version: 31.0.101.4091
We will be working on a fix. I want to give you a heads-up that the fix may take 3 to 6 months to be included.
Please do not close the case until the fix is done.

**Comment by Arturo-Intel** [comment]
@IGCIT Please close this case
