### ISSUE TITLE
Arc 770 is sporadically not recognized as a 3D accelerator.

### ISSUE THREAD

**Issue by thelomere** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#249]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

WOW, Cyberpunk etc

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [X] GOG Galaxy
- [ ] Ubisoft Connect
- [X] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 5 2600x

### Graphic Card [Required]

ARC 770, Acer Predator Bifrost

### GPU Driver Version [Required]

- [X] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [x] DirectX11
- [ ] DirectX10
- [x] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu-log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10773623/ssu-log.txt)

### Description and steps to reproduce [Required]

The games do not recognize the card as a 3D accelerator. The settings do not matter at all.

I have already described the problem on the Discord, there they said I should open an issue here because of it. The graphics card is not recognized as a 3D accelerator, then only a restart helps to fix the problem. Even if I have played in the same Windows session before, but quit the game, I can't restart the game because of the error.
The card is new, since Tuesday in the computer. The error has been occurring since then. It's not a clean windows install, I removed the previous drivers with DDU and installed the ARC drivers.

![image](https://user-images.githubusercontent.com/66433572/219848315-9d05a6fc-f5e5-4e1f-afcc-820db277e936.png)
![image](https://user-images.githubusercontent.com/66433572/219848319-a066a67c-3d69-4ba5-914b-d0f648ef2136.png)
![image](https://user-images.githubusercontent.com/66433572/219848322-ab9bc8f2-bc72-49f6-a6c1-bd33c3d4d879.png)
![image](https://user-images.githubusercontent.com/66433572/219848328-8dfa7477-e444-4e29-9cfd-80b5bb311fee.png)
![image](https://user-images.githubusercontent.com/66433572/219848336-974c55ab-adeb-4335-8983-7b8d6af2cc71.png)
![image](https://user-images.githubusercontent.com/66433572/219848345-2f1fb516-6f75-4cd0-af99-54a7c63b0d9c.png)
![image](https://user-images.githubusercontent.com/66433572/219848351-745c432b-3e32-4280-84f6-3d0332f70b1e.png)

### Game graphic quality [Required]

- [ ] Low
- [x] Medium
- [x] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [x] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

The games do not recognize the card as a 3D accelerator. The settings do not matter at all

### Device / Platform name

Self built PC

**Comment by IGCIT** [comment]
this is another instance of #221, #227 and #232

can you please mention what games are triggering this behaviour?

**Comment by thelomere** [comment]
A list?
WOW, Satisfactory, Cyberpunk2077, Skyrim, Fallout4, Gothic with 3d11 renderer, Ixion, The Planetcrafter, Dishonored 1&2, Diablo III, The Outher Worlds, Riftbreaker, World of Tanks, Subnautica + Below Zero and many other games and demos, like the System Shock demo from steam.

DX12, DX11 and DX 9 games.

**Comment by thelomere** [comment]
Addendum: I have such image dropouts. Is it possible that the problem is a defective graphics card?

![image](https://user-images.githubusercontent.com/66433572/219960413-27c0585f-df68-4310-9820-a1e32de307af.png)

**Comment by IntelSupport-Arun** [comment]
Hi @thelomere ,

Thank you for contacting us.

I would like to know below details from your side:
1. Is this issue observed after updating to the latest Beta driver version 31.0.101.4125?
2. How many displays are connected on Arc? Are you using multiple display combinations? All the displays are connected on Arc.
3.  Please change the power plan option to "High Performace " mode and see if the issue is still happening.
4. Have you tried changing the DP cable?

**Comment by thelomere** [comment]
1. yes, the error occurred with the latest release driver as well as the beta.
![image](https://user-images.githubusercontent.com/66433572/220122061-64ee2d93-3f9a-473c-bc1e-3dab8297dddc.png)
2. 3 Displays, Phillips 328E. All connected with DP to the ARC.
3. I use the high performance plan. The only change is Intel's workaround to keep the graphics card's current down in idle mode.
![image](https://user-images.githubusercontent.com/66433572/220123096-a04bf179-7ab4-4c6d-b7e9-bd95a7298b73.png)
4. I have removed all the displays except for the maindisplay from the graphics card. Then tried different cables, both supplied and purchased. No change in the error pattern.

**Comment by thelomere** [comment]
Test used HDMI in single monitor mode, render errors in Curseforge persist. Nothing changes with the power options, the card is not recognized in various games.

**Comment by IntelSupport-Arun** [comment]
Hi @thelomere ,

I will verify the issue from our side and let you know the update.

**Comment by thelomere** [comment]
The problem is done and radically. The card went back to the seller and I installed a 4070Ti. No more problems. I won't look at Intel's graphics cards again until the successor to Battlemage, if they even get that far with the design.
