### ISSUE TITLE
Craftopia Game flickers while looking at the sun

### ISSUE THREAD

**Issue by Xamrica** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#250]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Craftopia (https://store.steampowered.com/app/1307550/Craftopia/)

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7700

### Graphic Card [Required]

Intel Arc A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [X] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10777677/igcit_ssu.txt)

### Description and steps to reproduce [Required]

- start a new game
- look at the sun 
- screen starts flickering white

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Tested on "Highest" and "Lowest" preset

### Device / Platform name

self build

**Comment by IntelSupport-Arun** [comment]
Hi @Xamrica ,

We will try verify the issue on our side and let you know the update.

**Comment by Karen-Intel** [comment]
@Xamrica hi
I'm following up pending issues. Can you confirm if the behavior you have reported is still visible with driver version 4146?
Also, please make sure to upgrade your driver version to v.4146 performing a clean install with [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html)?

I'll be on the lookout, thanks

Karen

**Comment by Xamrica** [comment]
Hi @Karen-Intel ,

Yes, the issue still presists with version 4146.

**Comment by Karen-Intel** [comment]
Hi again @Xamrica 

I have been able to confirm the sun flicking using a 12900K Desktop + ARC 770 LE + Graphics Driver v. 4146
I will report it internally. 
Just FYI , the fix may take a while so please keep your drivers up to date and do not close this case until it has been released. I will post any updates in this thread
And thank you for your collaboration!

Karen

**Comment by Arturo-Intel** [comment]
@Xamrica can you try with version 101.4514? It comes with a huge improvement for DX11 games :)

**Comment by Xamrica** [comment]
Hi @Arturo-Intel,
it looks like the driver changed nothing but a new game update fixed the problem.
Thanks for the help anyway and I'll close this issue now.
