### ISSUE TITLE
GPU Clock Speed is Capped at 300MHz After Launching Microsoft Edge in Application Guard with "Advanced graphics" enabled in Windows Security on First Boot

### ISSUE THREAD

**Issue by willamettefour** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#251]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Microsoft Edge (running in Application Guard)

### Processor / Processor Number [Required]

i5-12490F

### Graphic Card [Required]

ASRock ARC A770

### GPU Driver Version [Required]

- [X] 31.0.101.4125
- [X] 31.0.101.4123
- [X] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[intel_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10796635/intel_ssu.txt)

### Description and steps to reproduce [Required]

Launching Microsoft Edge in Application Guard with "Advanced graphics" enabled in Windows Security on first boot causes the GPU clock speed to be capped at 300MHz. Increasing the voltage, power limit, or performance boost sliders don't fix the issue. GPU clocks return to normal after hibernating, sleeping, or shutting down and starting back up with Fast Startup enabled. The issue doesn't occur when "Advanced graphics" is disabled. The power plan doesn't seem to matter, and the attached video was tested using the High Performance power plan.

https://user-images.githubusercontent.com/94886283/220433421-e9362bde-c752-4cf9-b462-d25335fab9e6.mp4

**Comment by IntelSupport-Rozilah** [comment]
hi @willamettefour ,
Thanks for contacting Intel, we will start to verify the issue once our system is ready. Stay tuned!

**Comment by IntelSupport-Rozilah** [comment]
hi @willamettefour, 
The case has been verified on our side and we are able to reproduce it with our configurations as below:
Processor Name: Intel(R) Core(TM) i7-12700K
Driver version: 31.0.101.4125
We will be working on a fix. I want to give you a heads-up that the fix may take 3 to 6 months to be included.
Please do not close the case until the fix is done.

**Comment by willamettefour** [comment]
I don't know if newer drivers or Windows updates fixed the issue, but I no longer experience the problem with driver version 4575.

**Comment by IGCIT** [comment]
thanks @willamettefour for the update, closing as fixed :)
