### ISSUE TITLE
Getting poor performance on Ryzen 5 3600

### ISSUE THREAD

**Issue by SilasDhayanand** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#254]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Apex Legends

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Intel ARC A750

### GPU Driver Version [Required]

- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [X] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[IntelScan.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10833316/IntelScan.txt)

### Description and steps to reproduce [Required]

playing Apex wiht ARC A750 has been a terrible experience for me. The game can barely reach 100 fps even on the lowest settings with only the textures on high.
Other people have been getting better FPS with A750 in Apex so I don't know if this is a bottleneck because of the R5 3600. It probably is because I've been getting much lower than the expected FPS in games that run well on ARC like Spider - Man Remastered. In that game there are frequent drops to 25 FPS and the game barely reaches 60 FPS on high preset. Is it because of the Ryzen 5 3600? or is it just a faulty A750? Please help.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1680 * 1050

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Every setting on their lowest with textures on high
Resolution: 1680 * 1050
FOV: 110

### Device / Platform name

Ryzen

**Comment by SilasDhayanand** [comment]
Hi, I did install the 4091 driver after using ddu to wipe out the nvidia driver when i got the a750 , even today I tried the beta driver and decided to rollback and used ddu and installed the 4091 driver, didn't make a difference. Thank you for your support

**Comment by freak2fast4u** [comment]
Hi, I'm using the same R5 3600 CPU, but on Windows 10 22H2 with an A770 16GB. Using driver 31.0.101.4146 here (latest available as of time of writing). Is it of any use that I try and replicate on my side ? Mother board is an MSI X570-A PRO with latest BIOS installed (ReBAR enabled, 4GB+ decoding enabled, and PBO enabled, 2x8GB 3200Mhz CL16 RAM). Apex being free to play I'm ok with installing it just for testing.

**Comment by freak2fast4u** [comment]
Other questions : do you have several PCI-E x16 slots ? If so, have you tried switching the GPU to the other slot ? Usually the one closest to the CPU has the most chance to deliver full performance, depending on motherboard vendor and/or bios version.

Next : can you run the Unigine Valley benchmark on "Extreme" setting and report the result back ? 
After hitting the "Run" button, you need to hit the "Benchmark" button in the top left corner.

My results are attached (it's a DirectX 11 benchmark). Only the occasional stutter here and there, but otherwise a smooth benchmark for me.

![UnigineValleyExtremeResults_freak2fast4u](https://user-images.githubusercontent.com/3486369/223766562-9638dc3a-1613-488b-8b27-22cd549fae84.png)

The OS version and VRAM are misreported, it is an old benchmark after all :)

**Comment by freak2fast4u** [comment]
This might be relevant to your interest as well : https://www.destructoid.com/how-to-play-the-apex-legends-directx12-beta/

**Comment by SilasDhayanand** [comment]
> Oh, I forgot these two questions :
> 
> 1. Does it lag straight away or does it start lagging after a while ? I ask this question because the Arc Control Center has trouble managing the GPU fan speeds (it even got disabled in 2023 versions of the drivers), and you might be bumping into thermal throttling, especially if it's an Intel LE card. It was my case at first, and then I ran into this genius video where some very useful guy explains how to enable fan curve control (even though it doesn't work as good as it should, at least the fans ramp to 2200-2300rpm instead of idling at 600-1000rpm) : https://www.youtube.com/watch?v=biTl_M_REeI
> 2. Are you absolutely certain you enabled Resizable BAR and 4G+ decoding in the BIOS ? This is a firm requirement for using Intel Arc GPUs, else your performance will suffer big time.

I have made that tweak to enable the fan curve after noticing unusually high temps and now it stays around 72 to 75C. Also I've enable above 4g decoding and rebar on my mobo bios. Thank you

**Comment by Arturo-Intel** [comment]
@SilasDhayanand its ok to close this case?

**Comment by freak2fast4u** [comment]
@Arturo-Intel : I vote to close this ticket

**Comment by Arturo-Intel** [comment]
@IGCIT can we close this case please?
