### ISSUE TITLE
Very poor performance with Ray-Traced Reflections in The Ascent

### ISSUE THREAD

**Issue by paulober** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#255]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

The Ascent

### Game Platform [Required]

- [X] Steam
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 7 5800X

### Graphic Card [Required]

Intel Arc A770 LE

### GPU Driver Version [Required]

- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [X] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu-report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10842595/ssu-report.txt)

### Description and steps to reproduce [Required]

The Ascent runs on my PC with all settings at maximum and RT Shadows + RT Ambiont Exclusion enabled at about 80 fps on my UWQHD monitor, which is excellent.
But when I enable the most beautiful aspect of RT, RT Reflections, the frame rate unfortunately drops to 20 fps and below. This seems to me to be a problem with the driver, correct me if I'm wrong about that. I know RT Reflections is pretty expensive, but a 75% drop is a bit too crazy as far as I know.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

3440x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

All graphics settings to its maximum

### Device / Platform name

Desktop

**Comment by Arturo-Intel** [comment]
Hello @paulober!

Yes, reflection with RT reflections is very expensive, but not 75% FPS drop expensive I can agree on that.

I will try to reproduce this behavior in the lab, but in the meantime please try with the latest version of the beta driver ([4125](https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html)), Remember to do a clean install [using DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) and see if there is any improvement

If anything comes up I will share it here.
Thank you for your feedback

**Comment by paulober** [comment]
@Arturo-Intel Thanks for taking on this. 
I can confirm that this issue still exists with driver 4146 (new stable release, as i'm not comfortable using DDU as I don't trust it to remove ALL details of the old driver from every spot in my OS installtion).

**Comment by Arturo-Intel** [comment]
hello @paulober 
https://youtu.be/4EEHn7LWrwk

This is the game running on RTX 3060, the performance behaves as you describe (75% of FPS drop when ray tracing is enabled) meaning this is something that the developers need to fix. There is not much we can do in our side.

One thing I noticed is that with DSSL and ray tracing enabled (with RTX 3060) you can have a good 70FPS, 
Wouldn't be nice if the devs integrate XeSS also?

@IGCIT we can close this case
-- r2

**Comment by paulober** [comment]
@Arturo-Intel Thanks for coming back to this issue again.
Yes, it would be great if they would add XeSS support. I also suggested this to the dev but got no response. It seems like they stopped working on the game a very long time ago and I don't think they'll publish any new fix for this game. It's sad because they game is visually stunning and fun to play.

Maybe it's time to start working an again on a drop in replacement dll for the DLSS one to sneak in XeSS support but this comes with some drawbacks in performance compared to a native implementation.

@IGCIT Yes, close

**Comment by Arturo-Intel** [comment]
@paulober yes, its a shame, the game is really good (I caught my self playing this a little to much hehehe).
Im not sure if sneaking the dlls will be enough to enable XeSS, but who knows..

**Comment by paulober** [comment]
@Arturo-Intel I mean like this https://github.com/PotatoOfDoom/CyberFSR2 but for XeSS. But I'm not sure it this would work with XeSS as DLSS swap because if found the differences in some parts of the API rather big than between DLSS and FSR2.
