### ISSUE TITLE
Support for Oculus PCVR

### ISSUE THREAD

**Issue by spatialfree** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#256]
### Application [Required]

Oculus

### Processor / Processor Number [Required]

13600k

### Graphic Card [Required]

A750

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Get the Arc gpu's on the supported cards list.

### Additional notes

I realize oculus pcvr is slowly being killed by Meta *down to just streaming to standalone*. But as a dev with older vr hardware this would be a game changer this would mean a lot to me and others I want to recommend the card to.

**Comment by Arturo-Intel** [comment]
Hello @spatialfree,

Intel Arc graphics support for VR headsets continues to evolve as we ramp our products and add updates to our software stack. At this time we are unable to provide a target date for when each VR headset will be enabled.

Thank you for your feedback and suggestions. 

@IGCIT Please close this case.

**Comment by kpsam2000Intel** [comment]
Also this need enabling from Oculus side for Direct display, nothing from Intel!
