### ISSUE TITLE
[output] active signal resolution does not change, when new lower res mode is selected

### ISSUE THREAD

**Issue by mitzsch** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#259]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

not applicable/windows

### Processor / Processor Number [Required]

AMD Ryzen 5 5500

### Graphic Card [Required]

Intel ARC A770 16Gb LE

### GPU Driver Version [Required]

- [X] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

PC:
AMD Ryzen 5 5500
16Gb RAM 
Gigabyte Aourus M B450 - F63
Samsung 850 Pro - 256Gb
Realtek 1GbE Nic

Intel ARC A770 LE 
ResizableBAR enabled

### Description and steps to reproduce [Required]

Just try to change the resolution to a lower resolution. For example on a 4K Tv with an active 2160p mode - select a 1080p mode. It does not matter if done through the windows display settings, windows display device properties or the Intel® Graphics Command Center - the active display resolution stays at the edid recommended mode. In my case that is 3840x2160. The desktop however is rescaled to the newly selected mode...
In my case, the TV is connected through a DP to HDMI adapter made by club3D (cec-1080). All EDID modes are correctly shown in windows. The HDMI port on the card itself is not strong enough to output an image... 

Would be awesome if this could be "fixed"! Thanks! :)

### Device / Platform

Self build x86 PC

**Comment by Karen-Intel** [comment]
Hi @mitzsch 

Thank you for sharing! Sure, I will check it out. I'll let you know if I can confirm the same behavior on a similar system and get back to you if I need more info, stay tuned!

Karen

**Comment by Karen-Intel** [comment]
Hi @mitzsch thank you for your patience!
I've been checking the steps you posted here but I have not been able to reproduce this behavior
If I get it right, you're using a DP adapter to HDMI and then plugged to your TV>HDMI, only 1 monitor 4K Resolution?

Also, can you confirm that you have installed the latest driver (v.4146) performing a clean install with [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html)?

And about the HDMI port, it should have output, can you confirm if it does show anything plugged to a lower res monitor?
I have mine plugged and no issues at all

Thanks!
Karen

**Comment by mitzsch** [comment]
Hi @Karen-Intel 
Thanks for having had a look at this! Hm, this is interesting. I will try again - starting with a DDU reinstall of the v.4146 driver.

> If I get it right, you're using a DP adapter to HDMI and then plugged to your TV>HDMI, only 1 monitor 4K Resolution?

Exactly, well an AVR is in the chain. 

_GPU -> DPtoHDMI -> AVR -> TV_

Doing this with the internal HDMI does not produce an image, you can see a small "ah, the Tv is getting a signal" moment but the Tv then says "no signal". The only way I can get an image with the HDMI port on the card is with a direct-to-TV HDMI connection. However, I did not test how it's behaving there, regarding resolution changing. I will also test this!

As soon as I have done my testing I will report back! Thanks!

Alex

**Comment by mitzsch** [comment]
Hi @Karen-Intel 

Sorry for the delayed answer! I have now done all testing and here are the results.

First of all, I generated a system info txt with the Intel System Support Utility after the DDU reinstall.
[ssu-game-driver.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11009133/ssu-game-driver.txt)

I reinstalled driver **31.0.101.4148** - 4146 was not available for download again =>

<img width="284" alt="Screenshot 2023-03-17 105036" src="https://user-images.githubusercontent.com/43502191/226122087-8fa25f31-8418-4e5a-adb2-4d11b4769dad.png">

I also tried to install the Pro driver but that didn't work - I guess they are only for the Intel pro workstation GPUs...

---
At first I thought nothing has changed as I started with the windows change resolution dialog. This one here 
=> 
<img width="341" alt="Screenshot 2023-03-17 105648" src="https://user-images.githubusercontent.com/43502191/226122260-59ae124a-3a79-4148-b7a8-b62e3c21f55f.png">


with the same result as written in my initial post. The active signal resolution was still 3840x2160 and the desktop resolution was 1920x1080. Shown here 
=> 
<img width="387" alt="Screenshot 2023-03-17 1050061" src="https://user-images.githubusercontent.com/43502191/226122409-9c45a890-0821-4658-90c3-38593c47bce8.png">

This was done with the following "PC-to-TV" chain =>
`A770 DP -> DPtoHDMI Adapter -> AVR -> LG OLED`

---
With the direct-to-TV connection (`A770 HDMI -> LG OLED`) the results were the same.  
=>
<img width="340" alt="Screenshot 2023-03-17 1102381" src="https://user-images.githubusercontent.com/43502191/226122605-2e2e6f22-2be3-48cf-bccd-ec5435e84520.png">

---
Then I tried the _Intel graphics control center_ (downloaded from the windows store) and changed the resolution there: I didn´t expect it to be different but I was wrong - Now the output resolution was also changed!!
=> 
<img width="362" alt="Screenshot 2023-03-17 1151131" src="https://user-images.githubusercontent.com/43502191/226122828-fe7abb4c-9fff-4011-8e44-c0b0b93b48cc.png">
![Screenshot 2023-03-17 1151581](https://user-images.githubusercontent.com/43502191/226122829-79b71ca3-3ef0-47fd-8304-82d417d60b70.png)

This is great!! Also, it did not made any difference between a direct HDMI to TV or with the DPtoHDMI and the AVR in the chain - with both setups and the resolution being changed through the Intel graphics control center the output resolution also changed correctly to the newly selected one.

---
Now, where is my problem?

Well, it's kinda unfortunate that the resolution can only be changed through the "proprietary" Intel graphics control center and not through the windows randr win32 API. (The one from my second screenshot) (AMD and Nvidia are capable of changing the modes through this menu)
This essentially locks out programs that rely on this windows api to change the resolution - applications like KODI or Plex HTPC  to name only two. 

Would it be possible to get this added/fixed?

**Comment by Karen-Intel** [comment]
@mitzsch GM!
Woah that's quite some testing you performed!

And if course, I will report this behavior internally so we can have a fix in upcoming releases.
Jut FYI, it may take a while for it to be posted so I will make sure to report it internally and update this thread :), so please do not close this post 

And as a clarification, graphics driver version 4146 is still available, which is the [official release.](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html). The one you're using right now is a[ beta release](https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html). 
Thank you for your help, talk to you soon.

Karen

**Comment by Arturo-Intel** [comment]
Fix can be found in 4255
@IGCIT can we close this case?

**Comment by mitzsch** [comment]
@Karen-Intel @Arturo-Intel 

Unfortunately, it's not fixed. It's not working and behaves exactly like before, even with the newest beta version 31.0.101.4578. :/
