### ISSUE TITLE
Ridge racer unbounded crash

### ISSUE THREAD

**Issue by hididi31** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#26]
#### Game _[Required]_
Ridge racer unbounded 

---
#### CPU _[Required]_
I7 1160 g7

---
#### GPU Driver Version _[Required]_
Last

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_:Directx
**API Version** _(example DirectX 12)_:DirectX 9

---
#### Windows Build Number _[Required]_
Last build

---
#### Description _[Required]_
Games crash when starting driving
---
#### Steps To Reproduce _[Required]_

Launch game start, and when you start race it crash
---
#### Screenshots _[Optional]_

---

**Comment by leoben2** [comment]
reproduced, unfortunately there will be other games in front of the queue here.

**Comment by hididi31** [comment]
Thank you for you Re reply. If you Can fix this game I future update I ll be very happy. Anyway thanks for your workLe 1 avr. 2021 08:06, leoben2 ***@***.***> a écrit :
reproduced, unfortunately there will be other games in front of the queue here.

**Comment by hididi31** [comment]
> reproduced, unfortunately there will be other games in front of the queue here.



> reproduced, unfortunately there will be other games in front of the queue here.

Just want say you thank you vert much to fix the game in last update

**Comment by hididi31** [comment]
Thank you very much to fix that game in last GPU update.
