### ISSUE TITLE
HEVC decoding broken

### ISSUE THREAD

**Issue by straaat** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#260]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 11 with HEVC video extensions

### Processor / Processor Number [Required]

12th Gen Intel(R) Core(TM) i7-12700H

### Graphic Card [Required]

Iris Xe + Arc A370M

### GPU Driver Version [Required]

- [X] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10899508/igcit_ssu.txt)

### Description and steps to reproduce [Required]

I have a laptop with i7-12700H cpu + Arc A370M gpu.

With driver 4091 installed, I can play a video recorded by my iPhone in UHD/60p encoded in HEVC just fine in Windows Media Player (11.2212.32.0) or other built-in apps on Windows 11 22H2 (22621.1344) using HEVC video extensions (2.0.60532.0).

After upgrading to the latest driver 4146, the video window stays black or green, audio is playing but no video. Switching back to the previous driver fixes the problem.

When the A370M is on version 4146 and the integrated Xe is on 4091, the video's play fine while the iGPU is used. When I force an app to use the Arc GPU the problem reappears.

### Device / Platform

Lenovo VB82 / Lenovo Slim 7i (16” Intel)

**Comment by Karen-Intel** [comment]
Hi @straaat!

Thank you for sharing and catching this strange behavior. Question, did you uninstall the graphics driver with[ DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) before upgrading from v.4091 to v.4146 on both systems? (Just confirming, you may already have) Please let me know, I will be working on this with you

Thanks!

Karen

**Comment by straaat** [comment]
I used the clean install option using the installer from Intel website.

**Comment by straaat** [comment]
Same issue after using DDU to clean up and fresh driver installation.

**Comment by Karen-Intel** [comment]
Hi @straaat thank you for confirming!
I will go ahead and double check the regression you mention. If I need any other evidence I will get back to you
Thanks!

Karen

**Comment by Karen-Intel** [comment]
Hii @straaat just following up pending items
We had an issue with our Iris Xe system so we're replicating with Desktop machines driver v.4255 and have not been able to reproduce the issue.
Once we get hands on a system like yours I will update again in this thread. Also, if you could check on your end with the latest driver and see any changes, please let me know
Thanks
Karen

**Comment by straaat** [comment]
I tested both 4255 and 4257, problem is still there.

With the Xe on driver 4092, there is no problem.

**Comment by Karen-Intel** [comment]
Thanks @straaat we will update once we get hands on an Iris Xe system to confirm the regression on our end
Keep you posted

Karen

**Comment by Karen-Intel** [comment]
Hi @straaat help needed
Can you please share the video that's failing for you? 
We've tested a HEVC video on our end in a system just like yours and are still unable to reproduce so, we haven't been able to confirm the regression.

Thanks

Karen

**Comment by straaat** [comment]
Here is a video cut to 1s to fit within github 10MB limit:

https://user-images.githubusercontent.com/63163765/230092976-89d6449b-f899-4836-903e-ca7e388e356b.MOV

Full video you can download from Onedrive (70MB):
https://1drv.ms/v/s!AlMSXLxZAMmVpaV8hQxGzx3C-87sRw?e=LsvGA3

These videos will play in VLC for example but (with the recent drivers) not the built-in Windows apps like Photos or Media Player.
