### ISSUE TITLE
Overwatch 2 - Poor Performance on 4146

### ISSUE THREAD

**Issue by jkoch2** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#263]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Overwatch 2

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [X] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7-12700KF

### Graphic Card [Required]

A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10949164/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Running Overwatch 2 on driver 4125 with the settings listed runs fine with no stuttering. Switching to the 4146 driver results in excessive stuttering. The only thing that stands out is that with the new 4146 driver is that Task Manager shows 4 cores being pushed to 100% usage whereas on 4125 there seems to be normal CPU load.

While running Overwatch 2 in training area on 4125:
![Overwatch 2 - 4125](https://user-images.githubusercontent.com/49571866/224505668-57b8283e-068b-40ef-b204-5d1b6f627106.png)

While running Overwatch 2 in training area on 4146:
![Overwatch 2 - 4146](https://user-images.githubusercontent.com/49571866/224505670-aff06df8-0610-4204-a99b-c46726decd8b.png)

Steps to reproduce:

1. Run DDU to remove all traces of old driver and clear DirectX shader cache. 
2. Install 4146 driver.
3. Launch Overwatch 2 and enter a match or training area. 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![Overwatch 2 - Settings 1](https://user-images.githubusercontent.com/49571866/224505447-86c0ca3d-80ea-4e26-a2d6-d7f2ebc51ddb.png)
![Overwatch 2 - Settings 2](https://user-images.githubusercontent.com/49571866/224505454-2a7f7095-8c03-4f5e-8718-5ebf093f08ac.png)

**Comment by Arturo-Intel** [comment]
hello @jkoch2 !

I do see the CPU usage and the stuttering on the game, but after a while (5 min or so) the usage of the CPU desist and the stuttering disappears, does this happen in your side?

![image](https://user-images.githubusercontent.com/92489452/234333975-b9f9d0dc-98e1-4ef3-b538-a7112d7467fb.png)
![image](https://user-images.githubusercontent.com/92489452/234334000-aa5c398e-52e4-41b4-aafd-8b5c3e4d717c.png)

5 min (or so) later:
![image](https://user-images.githubusercontent.com/92489452/234334228-ac02c647-3aff-4f3a-8df9-6cacaf552046.png)
![image](https://user-images.githubusercontent.com/92489452/234334200-5a860d18-4049-4f62-b600-8f652cdd7d5b.png)

**Comment by Arturo-Intel** [comment]
@jkoch2  No worries! Glad to see this behavior is no more!
@IGCIT Can we close this case?
