### ISSUE TITLE
BSOD "VIDEO_SCHEDULER_INTERNAL_ERROR (119)" when playing RDR2 on Vulkan

### ISSUE THREAD

**Issue by martin-ngyn** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#264]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Red Dead Redemption 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Intel Arc A750 Challenger D 8GB OC

### GPU Driver Version [Required]

- [X] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10949758/ssulog.txt)

### Description and steps to reproduce [Required]

When playing Red Dead Redemption 2 on Vulkan, occassionally run into a BSOD "VIDEO_SCHEDULER_INTERNAL_ERROR (119)".

This tends to happen during cutscenes where I think there's heavier processing. Sometimes happens during normal gameplay.

Occurs on low/medium graphics qualities (performance/balanced graphics settings which is what it is called in Red Dead Redemption 2).

Here are a couple of minidumps from windows https://drive.google.com/drive/folders/1HwEmxW1AA8p5_wwRCznLW33S_y7hI-W9?usp=sharing.

This bug only occurs when the graphics API is set to use Vulkan. Changing this to use DX 12 causes the bug to not happen anymore, however shadows and lighting is poor.

Computer was formatted to install clean drivers and not have any remnant Nvidia drivers left.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://user-images.githubusercontent.com/81234267/224518659-82afe1a8-af23-4f75-9525-a2317d6e0451.png)

**Comment by Karen-Intel** [comment]
Hi @martin-ngyn 

Thank you for sharing your findings!
Looks like this behavior has already been reported before and a fix is already under development
Just fyi the fix may take from 3 to 6 months to be included. 
Please keep your drivers up to date and remember not to close this post until a fix has been released

Thanks!
Karen

**Comment by martin-ngyn** [comment]
I've tested this for about 30 mins with Vulkan and it seems okay. I've finished the game quite a while ago so I'm not really willing to play for too long.

I'll close this issue, but if anyone else still have issues feel free to re-open.
