### ISSUE TITLE
Intel Arc A370M has constant current draw of around 12W leading to bad battery lifre

### ISSUE THREAD

**Issue by electricEngineer** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#267]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 11

### Processor / Processor Number [Required]

i7-12700H

### Graphic Card [Required]

A370M

### GPU Driver Version [Required]

- [X] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10960811/igcit_ssu.txt)

### Description and steps to reproduce [Required]

From boot on my gpu is drawing constantly 12W in idle. Find here an excerpt of HWiNFO running for 2 hours in idle.
![GPU Constant power draw](https://user-images.githubusercontent.com/58144377/224802317-1083a94d-8501-4df5-bdae-3327963df93f.png)

I didn't recognized it immediately because I use my laptop mostly plugged in. But now the idle power consumtion on battery is in the ballpark of 20-25W. In the first months it was by about 7-10W. The GPU utilization is most of the time 0% according to the task manager.

### Device / Platform

Lenovo Yoga 7

**Comment by Karen-Intel** [comment]
@Arturo-Intel no updates from customer with latest drivers

Please close
