### ISSUE TITLE
Battlefield 2042 BSOD VIDEO_TDR_FAILURE caused by igdkmdnd64.sys

### ISSUE THREAD

**Issue by lshyrilser1** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#268]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Battlefield 2042

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7-13700K

### Graphic Card [Required]

Intel Arc A770 16GB

### GPU Driver Version [Required]

- [x] 31.0.101.4148
- [x] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[info.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10985447/info.txt)

### Description and steps to reproduce [Required]

Install Battlefield 2042 through Steam and launch. Will load EasyAntiCheat, load the boot screen, then will crash

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

None since can't get into menu

**Comment by Karen-Intel** [comment]
Hey @lshyrilser1 thank you for posting your findings w/driver v.4146
I will verify on my end and get back to you in case I need additional info

Keep you posted

Karen

**Comment by Karen-Intel** [comment]
Hi @lshyrilser1 

I've been working on reproducing the issue you report but I have not been able to reproduce :(
I have a Desktop 13900K system + ARC 770 + driver v.4146
There is a [new official driver version](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html) released today. I will keep on doing some debug with this version
Can you please upgrade your driver? If you get to do it try [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html), in my experience, it helps a lot with strange behaviors like the one you're experiencing.

Hope to hear from you soon

Karen

**Comment by lshyrilser1** [comment]
Thank you for looking into it. 

I will try this and report back my findings

**Comment by Karen-Intel** [comment]
Hi @lshyrilser1 just following up pending cases

Can you confirm if the issue is still present?

Thanks

Karen

**Comment by Arturo-Intel** [comment]
hello @lshyrilser1 
Do you were able to reproduce this issue with the latest stable driver? [4255](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html)?
