### ISSUE TITLE
Ty the Tasmanian Tiger 3 Crashing

### ISSUE THREAD

**Issue by a-One-Fan** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#271]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Ty the Tasmanian Tiger 3

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 7 3700x

### Graphic Card [Required]

Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11010288/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Try to enter the final level. The game will consistently crash, sometimes freezing (though still generating its own crash log). 
See video: https://youtu.be/EnjnhMB8vAI

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Everything is set to max, MSAA and SSAO are disabled due to other issues, performance and graphical artifacts respectively.
![Settings pic](https://imgur.com/roxIU8m.png)

### Device / Platform name

PC

### Crash dumps [Required, if applicable]

The IGCIT helper didn't produce any relevant dumps after a reboot and reproducing the issue. Also, 7zip files can't be uploaded here...
Attached are the mdmp the game itself created, and the game's own log.
[ty3_4108_crash_2023_3_19T5_24_58C0.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11010285/ty3_4108_crash_2023_3_19T5_24_58C0.zip)

### Save game

[savegame.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11010295/savegame.zip)
Location: \<Steam-folder\>\\userdata\\\<user-id\>\\411980\\remote\\
First save slot, 84% completion.

**Comment by a-One-Fan** [comment]
To add to this, the issue doesn't happen on Ubuntu, and this is a link to the game: https://store.steampowered.com/app/411980/TY_the_Tasmanian_Tiger_3/

**Comment by Karen-Intel** [comment]
Hi @a-One-Fan thank you for posting your findings
Questions:
1. I am unable to see the video you posted, it says it is private, could you update the link's privacy and repost?
2. Maybe you have already done that but, was the driver upgrade performed with [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html)? 

Talk to you soon

Karen

**Comment by a-One-Fan** [comment]
> Hi @a-One-Fan thank you for posting your findings Questions:
> 
> 1. I am unable to see the video you posted, it says it is private, could you update the link's privacy and repost?
> 2. Maybe you have already done that but, was the driver upgrade performed with [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html)?
> 
> Talk to you soon
> 
> Karen

Hey! Sorry, I fixed the video; I did use DDU for the Windows driver before playing the game.

**Comment by Karen-Intel** [comment]
Hi @a-One-Fan thank you for the update. We have an official driver that was released yesterday v.4255
I will keep on debugging this behavior and update this thread

Have a great weekend :)

Karen

**Comment by a-One-Fan** [comment]
Hey! I uninstalled the current driver with DDU again and did a quick test with 4255, the issue persists. Nonetheless, my weekend is fine. 
You have a great weekend too!

**Comment by Karen-Intel** [comment]
Hi @a-One-Fan just finished debugging with your save game

I'm testing with a 13900K Desktop PC + ARC 770 LE + driver v.4255
I've been able to replicate the crash which I'm thinking was triggered by the recording app.
I was trying to record the screen at the same time with OBS and it crashed for me. 
However, if I play the game without recording with OBS or recording with ARC Control, [the issue didn't occur.](https://www.barbasainz.com/registro-de-deudores-alimentarios-morosos/)

Could you verify on your end? Just to confirm my theory with OBS, try to record your screen using ARC Control and see if it fails in the same spot, which didn't fail for me using it, but it did fail while recording with OBS

Thanks! 

Karen

**Comment by a-One-Fan** [comment]
Hello @Karen-Intel , I took the initiative and also made a new partition and a clean install of Windows 11, only installing the 4255 drivers, Steam, rebooting, the game (+steam installing runtimes). The issue persists, regardless of whether I'm recording or not (and whether I'm on the brand new Windows 11, or the old one).
After recording, I also installed AV1 for the built-in media player. Here is a new SSU just in case:  
[igcit_ssu_ty3_crashing_new.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11115916/igcit_ssu_ty3_crashing_new.txt)
Here is the video of the crashing, recorded with Arc Control: https://www.youtube.com/watch?v=iPJIdsMM4Cw
After the video, I also tested with Windows 11's "game mode" disabled and Steam's in-game overlay disabled, and it still happens.

**Comment by Karen-Intel** [comment]
Hi @a-One-Fan thank you for the update
Okay, then allow me a bit of more time to continue investigate the issue, specially without OBS :)
Will get back soon

Karen

**Comment by a-One-Fan** [comment]
Hello @Karen-Intel , I tested a little more. The issue doesn't happen with the lowest settings, which are the default for a new install. These settings are not stored in the save file (or the steam cloud), they're per-install; when I tested the new install, I changed the settings to what I had in the screenshot. The settings specifically need to be the higher ones I am using. Sorry for not mentioning this and wasting your time, but this should help reproduce the issue.

**Comment by Karen-Intel** [comment]
Hi @a-One-Fan 

Okay! That definitely will help me. I will make some more tests with the machine I used before and get back to you 
And no worries, time is never wasted. I'm here to assist you

Talk to you soon :)

Karen

**Comment by rmorera-intel** [comment]
Hi @a-One-Fan ,

Thank you for reporting this issue. Our priority is to target the most popular games and apps to focus our efforts on providing a high quality, stable experience for the broadest set of users. We will continue to improve our software performance and compatibility throughout 2024 and beyond. While we can’t accommodate your request at this time, please watch [this article](https://www.intel.com/content/www/us/en/support/articles/000095313.html) on our website for any possible changes to this situation.

**Comment by a-One-Fan** [comment]
@rmorera-intel https://www.intel.com/content/www/us/en/support/articles/000095313.html does not lead to an article, it leads to  https://www.intel.com/content/www/us/en/support.html

**Comment by rmorera-intel** [comment]
The article is in the process of getting published (there is some caching in the server) so please check back in the next hours. I apologize for the delay.
