### ISSUE TITLE
PC bluescreens sometimes when starting from sleep mode which restarts the PC

### ISSUE THREAD

**Issue by paulober** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#272]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 11 Pro

### Processor / Processor Number [Required]

Ryzen 7 5800X

### Graphic Card [Required]

Intel ARC A770 (16 GB)

### GPU Driver Version [Required]

- [ ] 31.0.101.4148
- [X] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

10.0.22621.1413

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11032174/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Don't know how to reproduce on other PCs, but here is how it works on mine:

- Do some work, maybe some unsave text files open, visual studio code stuff and youtube
- Then put the PC into sleep mode via the start menu power button for this
- Go about an hour away from the computer
- Come back and press the blinking power button on the desktop
- You'll notice that some fans ramp up, all is lighting up
- Than all stops and you here tipical click and stuff stops in order to reboot
- Now it boots like from shutdown

### Device / Platform

Desktop (MSI B550m-pro vdh wifi)

### Application / Windows logs

Here are two crashes from today and yesterday from both crashes all Windows System event logs and Windows Applications event logs:
[systemLogRebootOnResume1+2.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11032212/systemLogRebootOnResume1%2B2.zip)
[systemLogRebootOnResume1+2_1033.zip Metadata](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11032293/systemLogRebootOnResume1%2B2_1033.zip)

Simplified:
- It starts with "OS was started at time ..."
- The system was previously shut down unexpectedly on 03/21/2023 at 17:42:08.
- The active system time is 8 seconds.
- [Critical] The system was restarted without being properly shut down first. This error can occur if the system stopped responding or crashed, or the power was unexpectedly interrupted.
- Intel(R) Graphics Firmware Interface Auxiliary Device firmware update is disabled.
- The Intel(R) Graphics System Controller Firmware Interface is being reset.
- Windows cannot load the extensible performance indicator DLL "C:\Windows\system32\sysmain.dll" (Win32 error code The specified module was not found.).

And many more errors...

**Comment by Karen-Intel** [comment]
Hi @paulober thank you for posting your findings.
Question: Your SSU shows you're using driver version 4091, however you ticked the 4146 box. Can you confirm what is the right driver version?
Also, perhaps you already did this but, was the driver upgrade done with [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html)? Just checking. 
I have a similar system I can use to perform some experiments but I'll wait for your feedback on these two inquiries

Keep me posted

Karen

**Comment by paulober** [comment]
@Karen-Intel Sorry, i haven't regenerated the SSU report. But yes, i'm on the driver version i've selected in the issue.

**Comment by Karen-Intel** [comment]
Hey @paulober okay, no issues. What about the DDU usage? I just want to discard there could be some old files messing around with the sleeping states. Can you confirm? Thanks

Karen

**Comment by paulober** [comment]
@Karen-Intel I don't like DDU and it's purpose as a third part won't be able to remove the older drive stuff as well as a fresh OS install. Therefore the system i experience this issue with is only about 3 and a half months old and had only the stable public releases of the Intel Arc Driver installed. I also never messed with any additional GPUs and GPU drivers on this system.

**Comment by Karen-Intel** [comment]
@paulober Hi again
It is indeed one of DDUs usages, however, it is also recommended to use it when there are issues showing, that way we can discard precisely that the driver is the one to blame. 
BSODs might be related to a lot of things, so the first step is to ensure we have a clean driver install.
I am already checking the logs you sent me (thank you) and will investigate on my end if there's similar behavior reported on other systems with a similar configuration to yours, so I'll be back soon with my findings.

Good day

Karen

**Comment by paulober** [comment]
I also don't have a bluescreen as the GPU does not work during the time the bluescreen crash happens but i've seen some of these crashes ago a log in the Windows logs that a bluescreen happened every time have this crash and then it automatically restarts.

**Comment by dylanh117** [comment]
I'll give another follow up tomorrow or over the weekend, but it seems like my problem has been fixed after using DDU. Like you, I had just done a fresh Windows install a few months ago & this is the only GPU that's been used. I don't know why I'd have to remove & reinstall the drivers, but it's seemed to work.

**Comment by Karen-Intel** [comment]
@dylanh117 thanks a lot for posting what you found after using DDU :)
Please keep us posted as if we keep on seeing the issue/issues I will be glad to report them and gather all the relevant info so we can get a fix for you

Talk to you soon!

Karen

**Comment by dylanh117** [comment]
@Karen-Intel I think I can confidently say that DDU fixed my issue. I have had no issues w/ resuming work after my PC goes to sleep since then.

**Comment by Karen-Intel** [comment]
Hi @paulober can you confirm if you've tried DDU and if it has fixed your issue? 
Just following up pending cases
Thanks

Karen

**Comment by paulober** [comment]
@Karen-Intel no, i haven't tried DDU. 
But i can push a new issue i've observed with the GPU firmware/driver itself. When you start your monitor after starting the Desktop. It's a relatively new premium Lenovo DisplayPort 1.4 monitor. But i also observed it with other displays connected over DisplaPort.

**Comment by Karen-Intel** [comment]
@paulober Okay
Also FYI, a similar issue(s) has already been reported with DP which we are actively working on, there's no need to open a new one.
 In the meantime, is it okay if we close the issue? We haven't had any recent reports of similar failures with driver 4255
Thanks

**Comment by paulober** [comment]
@Karen-Intel Ok, I'm glad to hear that you are already working on it.
And yes, you can close this problem now. I will open it again if the situation gets worse, as of right now I have not experienced this problem again with the current stable driver version.
