### ISSUE TITLE
Emulator encounters a problem creating the compute pipelines

### ISSUE THREAD

**Issue by Zero3K** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#273]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

HPS2x64

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

Available from Sourceforge.net

### Processor / Processor Number [Required]

Intel Core i7-1195G7

### Graphic Card [Required]

Intel Iris Xe

### GPU Driver Version [Required]

- [ ] 31.0.101.4148
- [X] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [X] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

I cannot get the program to run. Its specs can be found at https://en.wikipedia.org/wiki/GPD_Win_Max.

### Description and steps to reproduce [Required]

I encountered it when just running the program. It can be found as part of the archive at https://sourceforge.net/projects/hpsx64/files/latest/download. Here is a screenshot of what is shown when it is ran:

![image](https://user-images.githubusercontent.com/6194332/226761084-8cb56775-2b7c-499b-b751-dab39a5dcae1.png)

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

800x600

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

The settings are the default ones.

### Device / Platform name

GPD WIN MAX 2021

**Comment by Zero3K** [comment]
This looks similar to the issue mentioned at https://community.intel.com/t5/Graphics/Resident-Evil-7-crashes-at-startup-intel-Iris-Plus-G4/td-p/647803. A support person mentioned that a fix was given to Capcom and was included in an update to the mentioned game. If it is the same, then I just need someone to make a patch for HPS1x64 and HPS2x64's source code that fixes the issue and give me its contents so I can post it on the discussion board for the emulators.

**Comment by Zero3K** [comment]
I guess not.

**Comment by IGCIT** [comment]
> Can you offer him a fix though? It seems to be the same issue that Resident Evil 7 was having.

i can't, sorry

**Comment by Zero3K** [comment]
Maybe you can ask the person who provided the fix to Capcom.

**Comment by Zero3K** [comment]
I wonder why HPS1x64 works but not HPS2x64.
