### ISSUE TITLE
Sonic Frontiers - Photo Mode produces black image aside from a few effects - Intel Arc A770 16GB

### ISSUE THREAD

**Issue by gh192** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#275]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Sonic Frontiers

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

12th Gen Intel Core i7-12700

### Graphic Card [Required]

Intel Arc A770 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11067177/igcit_ssu.txt)

### Description and steps to reproduce [Required]

When opening the photo mode in sonic frontiers from the pause menu, the preview shows the scene being rendered wrong with everything being black, with some graphical glitches present and some effects being rendered fine. Going into photo mode shows the same result, and moving the camera around shows that this is real-time rendering that is still occuring.

The graphics are being rendered correctly outside of photo mode.
![20230324232421_1](https://user-images.githubusercontent.com/35262882/227660817-307402b9-6c12-4dbf-b2e5-5683d52354bc.jpg)
![20230324232424_1](https://user-images.githubusercontent.com/35262882/227660821-4da19f4f-2ae7-481c-827f-181e3637f3da.jpg)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![20230324232444_1](https://user-images.githubusercontent.com/35262882/227660854-cc4e35d2-f526-4f8c-a3a1-3516f5403cf2.jpg)
![20230324232456_1](https://user-images.githubusercontent.com/35262882/227660857-6fd49798-ebad-49ea-b5b8-a12401c667ae.jpg)
![20230324232511_1](https://user-images.githubusercontent.com/35262882/227660858-a027bbc1-4d6e-45c1-a3b8-9ca1ddfa1299.jpg)

**Comment by Karen-Intel** [comment]
Hi @gh192 thank you for your patience.
I have been able to reproduce the strange behavior you reported with Photo Mode
I'm using a 13900K system with A770 LE + driver v.4255
I will be reporting it internally asap. Just FYI for the fix to be released may take a while (3-6 months) so please keep your drivers up to date and do not close this post, I will make sure to be back whenever I have updates

Thank you so much for helping us report this issue! Have a great day

Karen

**Comment by EstebanIntel** [comment]
Hi @gh192,

I have good news: driver [32.0.101.6127](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) has been published and it introduces a fix for the issue with Sonic Frontiers photo mode. Please try this driver and if the issue persists let me know. By the way, I know this was reported a long time ago and I do apologize for the time it took to see any progress, so I also want to thank you for your patience and for supporting Intel Arc Graphics.

**Comment by EstebanIntel** [comment]
Hi @gh192,

Any chance you were able to test the fix?
