### ISSUE TITLE
Performance issues in dx12 games(逆水寒), and problems with xess

### ISSUE THREAD

**Issue by zhao-i** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#279]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

逆水寒

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

NetEasy

### Processor / Processor Number [Required]

i3-12100

### Graphic Card [Required]

A750

### GPU Driver Version [Required]

- [ ] 31.0.101.4257
- [X] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11129579/igcit_ssu.txt)

### Description and steps to reproduce [Required]

- Select dx12 in the game launcher and start the game.

- The game quality is set to the highest, xess set to performance

- Select a player body and zoom in

1. When XESS is enabled in the game, the layers are misaligned, and picture becomes blurred.
As a comparison, I used dlss and it worked fine.
2. Frame production is very erratic, especially when there are many character models, the frame rate is less than 20.
The game used dx12 api, not dx11, not dx9!
I don't think these problems should arise, so how to solve or optimize these problems?

(The recorded video is too large to upload)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![1](https://user-images.githubusercontent.com/84286379/229288987-b02ccbe0-1914-4f49-b08f-b07304b6dd10.png)
![2](https://user-images.githubusercontent.com/84286379/229288996-147d5c15-ed73-4a7b-a8ad-32be21e56a84.png)
![3](https://user-images.githubusercontent.com/84286379/229289001-1b39e7a6-85b1-4af1-8d88-483fabdb2bc3.png)

**Comment by Karen-Intel** [comment]
Hii @zhao-i thank you for posting your findings :)

Question: can you please share the link to access the game?

Thanks

**Comment by zhao-i** [comment]
Hi @Karen-Intel 
https://n.163.com ,
https://n.163.com/download/ 
 (I tested it using the standard version)

**Comment by zhao-i** [comment]
Maybe you noticed, the XESS product page contains the game.
![image](https://user-images.githubusercontent.com/84286379/229686773-79af317f-721f-4e5e-8f6b-86126f8dc101.png)

**Comment by Karen-Intel** [comment]
@zhao-i Gotcha
Allow me some time to perform experiments and will get back to you

Karen

**Comment by Karen-Intel** [comment]
Hey @zhao-i we need help.
We are in a different geo and looks like to register an account we cannot add a foreign number for SMS verification
Could you please create an account for us? Just to test on our end

![image](https://user-images.githubusercontent.com/91162218/231836215-7a3109d6-53d7-440e-90a1-6741013e16aa.png)

Apologies on the delay, we were looking for options on our end and couldn't find a solution

Thanks!

Karen

**Comment by zhao-i** [comment]
@Karen-Intel 
I have sent to your mail.
It has gone through the necessary mobile phone number binding and real-name authentication.
you can test anything with it.
Hope everything goes smoothly!

**Comment by Karen-Intel** [comment]
Thank you @zhao-i , I could successfully log in.

Now, I have enabled the settings just as you have them (DX12 Enabled and XeSS on performance) but can't seem to see that blurriness or the misaligned layers you mention when zooming on characters. 
Could you post the video you mentioned somewhere where we could visualize it?
 You could also add pictures referring to the texture that appears as corrupted.
Now about the FPS, would be great if we could see where you have detected those drops, is it in the overall game, is it in an specific area?

Thank you so much for your help

Karen

**Comment by zhao-i** [comment]
@Karen-Intel 
I have not reproduced the problem of layer misalignment.
Bad performance : [https://pan.baidu.com/s/1ddHyrc7U-2koISgJM0ycbQ?pwd=usk6](baidu cloud disk)

**Comment by Arturo-Intel** [comment]
@zhao-i 
Can you post the video in other site? we can access to the baidu.com without a account and for that we need a Chinese phone.
![image](https://user-images.githubusercontent.com/92489452/232843713-d24175d7-09ef-4ad9-8024-f6640c456334.png)
![image](https://user-images.githubusercontent.com/92489452/232843745-2e72e69f-7258-4b54-9738-8a2d66ad1a76.png)

**Comment by zhao-i** [comment]
@Arturo-Intel 
try this: https://drive.google.com/file/d/1uPtSuH92ubnPtrdhR1SXPn769VpBU4ep/view?usp=sharing

**Comment by Karen-Intel** [comment]
Hey @zhao-i just a quick update
We're already debugging the issue, with the videos you sent now we know what to look for.
Just FYI our native language is not Chinese so, it would  take a while for us to play the game :( 
Can you help us advancing the account you shared to the point where the artifacts are showing? 
We want to advance as much as we can but the language barrier is limiting quite a bit and if we are able to reproduce the artifacts in our machines, the development team most likely will need access to the account too.

Appreciate your help

Karen

**Comment by zhao-i** [comment]
I have controlled the character to stay in the blue temple (yaoguang city).
In fact, you can access almost all game maps now, except for some instances with level restrictions.
About how to reach those test maps, the xiaonuan(![233543849-cee57fd0-f1d9-42a0-a710-1736a10e2acb](https://user-images.githubusercontent.com/84286379/233544046-2e32050f-3b9e-46a7-aab8-fa56a6566283.png)) in the upper right corner will tell you.
![image](https://user-images.githubusercontent.com/84286379/233543574-f87dadd7-585d-4dcc-a395-6281a88b8ec5.png)

**Comment by Karen-Intel** [comment]
@zhao-i Hi! and thank you so much for all the help.

Testing is in progress so we will be back soon with our findings, testing in 2 different configurations

Have a great weekend.

Karen

**Comment by zhao-i** [comment]
Not works.
I used DDU in safe mode.
4314 installed.
https://user-images.githubusercontent.com/84286379/234870484-7deb9510-9c2d-4cdd-9bb3-64998e57570a.mp4

**Comment by Karen-Intel** [comment]
Hey @zhao-i here's what we have found in the 3 configs we have tested (following your very same configuration with DX12, etc)

Config 1: Intel RTL 13900K + A750 + driver v. 31.0.101.4314
Config 2: Intel RKL 11900K + RTX 3060 + driver v. 31.0.101.4255
Config 3: Intel RTL 13900K + RTX 3060 + driver v. 31.0.13.3168

1. The odd choppy blocks on menus are not reproducible in any of the 3 configs we tested. This behavior might be related to your Windows configuration as the 3 tests were performed after a fresh Windows install 
2. The low FPS behavior is reproducible on both, Intel and Nvidia. Here's the [evidence for NVIDIA ](https://www.youtube.com/watch?v=RtuyjVxpASg) which leads me to think it might be an issue of the game :(. 
You can see 12-20 FPS in this single temple so probably the issue related to -low performance, crowd related- might be related to it too

We are sorry there's not much we can do but the issues we have seen might be related to the game itself. Please let us know if there's anything else we can help with

Karen

**Comment by zhao-i** [comment]
@Karen-Intel 
![snap_1682771218566](https://user-images.githubusercontent.com/84286379/235304450-7a34d2a3-f35f-442e-9bd9-149557d7b0c2.jpg)
![snap_1682770791995](https://user-images.githubusercontent.com/84286379/235304456-0c96998e-430c-4b13-9952-7edd0c32d568.jpg)
![snap_1682772697749](https://user-images.githubusercontent.com/84286379/235304466-ecdecb1f-85d0-4a95-8429-4c95249c2b9a.jpg)
![snap_1682773416900](https://user-images.githubusercontent.com/84286379/235304471-bd2d4cb6-2e54-46be-b901-b6fc1c9c4a10.jpg)

**Comment by zhao-i** [comment]
@Karen-Intel 
as is known to all, Arc's non-dx12 performance is extremely poor.
Tested: 

    - DX11 (high crowd density) average 28 fps
    - DX12 (high crowd density) average 23 fps
    - 
    - DX11(blue temple) average 76 fps
    - DX11(blue temple) average 66 fps

Lost 15%~10% performance, relative to dx11.
But I don't care about the solution to this problem anymore, it's hard to locate and wastes too much time, so be it.
Thanks.

**Comment by zhao-i** [comment]
.
