### ISSUE TITLE
Call of Duty Warzone crash Freeze

### ISSUE THREAD

**Issue by hididi31** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#28]
#### Game _[Required]_
Call of Duty warzone

---
#### CPU _[Required]_

I7 1160g7
---
#### GPU Driver Version _[Required]_

Last build
---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_:DirectX
**API Version** _(example DirectX 12)_:

---
#### Windows Build Number _[Required]_
Last build

---
#### Description _[Required]_
Very bad allocations of memory. (16gb). Long loadings, suddenly freeze also Windows. Crash. À few times thé game working can play 
---
#### Steps To Reproduce _[Required]_
Just launch game, choose battle royale mode verdansk and after seing thé very bad performance

---
#### Screenshots _[Optional]_

---

**Comment by Valkirie** [comment]
Thanks for sharing but closing this one as it has been reported already on issue #23
