### ISSUE TITLE
Genshin Impact has problems in loading

### ISSUE THREAD

**Issue by zhao-i** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#280]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Genshin Impact

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Other game platform

mihoyo

### Processor / Processor Number [Required]

i3-12100

### Graphic Card [Required]

Arc 750

### GPU Driver Version [Required]

- [ ] 31.0.101.4257
- [X] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11171295/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Start the computer as usual, then start the game. 
Game cannot start normally, CPU utilization rate 100%, the system is stuck state.
The recorded issue is in the zip.
[2023-04-06 22-02-46.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11171459/2023-04-06.22-02-46.zip)

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

default setting

**Comment by zhao-i** [comment]
additional remarks: this problem arises randomly

**Comment by Karen-Intel** [comment]
Hey @zhao-i  thank you for posting your findings.
I will make sure to test in a system similar to yours and get back in case I have questions

Talk to you soon
Karen

**Comment by Arturo-Intel** [comment]
Hello @zhao-i !

It looks the game is running on the iGPU not in the ARC, I was able to reproduce the same behavior forcing the game to use the iGPU

**Comment by zhao-i** [comment]
@Arturo-Intel 
I watched this video.
Then I launch the game with iGPU it work fine as expected, just low frame rate and 100% iGPU usage, not 100% CPU usage.
Maybe 100% cpu usage is caused by something else.

**Comment by zhao-i** [comment]
@Arturo-Intel 
Can you open that zip file and have a look again?
Look at the usage of cpu and all gpu, while the game is running.

**Comment by zhao-i** [comment]
@Arturo-Intel 
Okay, I will use DDU to reinstall the driver, If this problem persists, I will reply again.

**Comment by Arturo-Intel** [comment]
@zhao-i Any news? 
The DDU works?

**Comment by zhao-i** [comment]
@Arturo-Intel 
not works,
this problem happened once (**after I ran another game**).
I used DDU and installed 4311

**Comment by zhao-i** [comment]
@Arturo-Intel 
Note, this problem happened again, after I finished a match of lol.
I closed lol and launch Genshin, problem recurrence.

**Comment by Arturo-Intel** [comment]
Hmm I am not able to reproduce it, let me do some more tests

**Comment by zhao-i** [comment]
so be it,
restart solves all problems,
thanks.
