### ISSUE TITLE
World of Warplanes(DX9) - Low fps looking at certain areas

### ISSUE THREAD

**Issue by zrmdsxa** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#281]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

World of Warplanes

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

Wargaming Game Center

### Processor / Processor Number [Required]

Ryzen 7600X

### Graphic Card [Required]

A750 LE

### GPU Driver Version [Required]

- [ ] 31.0.101.4257
- [X] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11174788/report.txt)

### Description and steps to reproduce [Required]

Low FPS: Look at these areas in the map 'Northern Bridgehead' and 'Cold Peak'.

![image](https://user-images.githubusercontent.com/5502880/230505393-aa51a78b-b21c-4cdc-ad16-8c77a980db29.png)
![image](https://user-images.githubusercontent.com/5502880/230505425-d568d4f4-2c81-46d6-b42c-27c13fe40f09.png)

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1009

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![image](https://user-images.githubusercontent.com/5502880/230505279-a8e74dae-1207-454a-919b-c3e7d8ada54e.png)

**Comment by IGCIT** [comment]
hi @zrmdsxa 

can you please open a new issue for OBS crash?
it makes it easier to keep track of the issues.

thanks

**Comment by Karen-Intel** [comment]
Hi @zrmdsxa thank you for posting your findings. In this post we will focus in World of Warplanes
I will make sure to test in a system similar to yours and get back in case I have questions

Stay tuned!
Karen

**Comment by Karen-Intel** [comment]
@zrmdsxa hi again

Like I posted in the other thread, please let us know if you have tried [DDU[](url)](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) when you updated your driver? I am still investigating this behavior and have not been able to reproduce.
Thanks!

Karen

**Comment by zrmdsxa** [comment]
I have ran DDU and the low fps issue is still there in the maps Cold Peak and Northern Bridgehead.

These are the fps I get within the first 10 seconds of the battle starting. Only Cold Peak and Northern Bridgehead have low fps because of problem areas in the map that are in view at the start of the battle.

Albion: 120-130fps
Alpine Gambit: 100-120fps
Archipelago: 80-110fps
Arctic Region: 130-150fps
Asian Border: 80-120fps
**Cold Peak: 30fps
Northern Bridgehead: 40fps**
Old Fortress: 80-90fps
Peripheral Mission: 125fps
Plateau: 130-150fps
Road to Rome: 120-130fps
Scorching Sands: 125fps
Sea Gate: 80-100fps

If you didn't know already, you can get to the Cold Peak and Northern Bridgehead maps quickly by going to the training room and creating a room and then selecting those maps. You also won't have to pay any repair fees by using a tier1 plane in the training room.

**Comment by Karen-Intel** [comment]
Hey @zrmdsxa thank you I will test this with the AMD system soon and get back to you :)

Karen

**Comment by Karen-Intel** [comment]
Hey @zrmdsxa hello again :)

We were finally able to reproduce the FPS drop in specific map areas in our system: 12900K + ARC A770 + Gfx driver version 4314.
We are already reporting this behavior internally, just FYI the fix may take ~ 3 to 6 months to be released.
Please keep this post open in case we need to update and thank you for all your help!

Talk to you soon

Karen

**Comment by Arturo-Intel** [comment]
hello @zrmdsxa 
I was doing some tests with the [101.4382](https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html?) driver and notice that if I change the graphics config to this:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/c673928f-b0ac-49b4-b9f8-c8c46d0001e2)

I will have double the FPS on Cold Peak:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/e92de7c7-d593-4daa-aa0e-8c62f73750ab)

If I keep your original settings I have around 30fps with this driver. 
--r2

**Comment by zrmdsxa** [comment]
> hello @zrmdsxa I was doing some tests with the [101.4382](https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html?) driver and notice that if I change the graphics config to this: ![image](https://user-images.githubusercontent.com/92489452/242744890-c673928f-b0ac-49b4-b9f8-c8c46d0001e2.png)
> 
> I will have double the FPS on Cold Peak: ![image](https://user-images.githubusercontent.com/92489452/242744834-e92de7c7-d593-4daa-aa0e-8c62f73750ab.png)
> 
> If I keep your original settings I have around 30fps with this driver. --r2

Hello, @Arturo-Intel  the problem I have with Cold peak is looking in the west direction. If I look east, I have 100 fps but if I look west, it drops to 24 fps

**Comment by zrmdsxa** [comment]
Hello again I have found the cause of the problem to be Foliage Quality set to very low. Setting it one setting higher to low has made the problem go away for both maps

**Comment by Arturo-Intel** [comment]
Oh nice, and what about the other levels, does the FPS increase?

**Comment by zrmdsxa** [comment]
The fps seems to be about the same for the other maps. They didn't have fps drops when looking at certain areas.

**Comment by zrmdsxa** [comment]
@Arturo-Intel setting the foliage quality higher will decrease the fps by a lot. So it seems like having it on low is the safest choice.

**Comment by zrmdsxa** [comment]
Hello please ignore my previous post. My rebar stopped working and I had to reinstall drivers to get rebar working again.

This is what my graph looks like when I switch from low to very low on cold peak
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5502880/ec927c7f-084c-4771-bdf7-6da27e9c22e4)

**Comment by Arturo-Intel** [comment]
@zrmdsxa 
Using the latest driver (101.4514) I can reproduce the follow behavior: If I set Foliage Quality set to "very low", the FPS drops to low 20s, but if I set it to "very high" the FPS goes up to 70FPS, as you can see in the video, all this selecting cold peak level 
 
https://youtu.be/FvBmXaNmuLw

This is following the same behavior you share but with "very high" to "very low".
>
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/d7dfff61-5c1f-4331-86aa-f7cfbdfb09a5)

Does selecting above the "very low" option affects to your stream? I seems to me that is better to have more FPS.

I will share this data to the devs team. I hope we can have good news soon...
Sorry for the long silent 
--r2

**Comment by Arturo-Intel** [comment]
@zrmdsxa Can you try using the [latest driver? (31.0.101.5534) ](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)

**Comment by zrmdsxa** [comment]
There appears to be no fps drops with this driver using very low foliage settings in cold peak and northern bridgehead

**Comment by Arturo-Intel** [comment]
@zrmdsxa thanks for the confirmation.
Closing this case.
