### ISSUE TITLE
EA Launcher opens and BSOD w/ DRIVER_VERIFIER_DMA_VIOLATION

### ISSUE THREAD

**Issue by gargamel314** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#283]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

EA App (Launcher)

### Processor / Processor Number [Required]

i7-13700K

### Graphic Card [Required]

Intel Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [X] 31.0.101.4125
- [ ] 31.0.101.4123
- [X] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

Before finding a work around, I did not remember to get the SSU report. I did manage to take a screenshot and a video, however.

### Description and steps to reproduce [Required]

This app will run fine for weeks, even months, and then without warning one day you open it and it will crash Windows with a BSOD which says "Stopcode: DRIVER_VERIFIER_DMA_VIOLATION." Once that happens, it occur every time you open the app. Fully uninstalling, rebooting, and reinstalling the EA App did not help, even when Revo Uninstaller was used to clean up artifacts and registry keys. It would even exhibit the same behavior in Windows Safe Mode. Also, it would completely wipe out the Windows Start Menu and the start menu would revert to the layout and icons that show up when you first install Windows. The "New Device Experience" (where Windows tries to install bloatware apps and a free Microsoft 365 Trial would initiate again like you just installed Windows. Just trying to run the installer - it would install, and then try to open and immediately crash again. 

I was able to resolve this finally by rebooting into Safe Mode, running DDU and uninstalling the Windows Drivers. I was able to reinstall the same drivers and the EA launcher app, with no crashes. This is the 3rd time over the past 2 months that I've had this happen and I've had to fix this. After the 2nd time, I reinstalled Windows 11, so this 3rd time is after a full Windows 11 Pro Reinstall. 

https://user-images.githubusercontent.com/124757309/230703890-7e47348f-ecb4-4fbc-9c9d-e8eb5da053d4.mp4

![EA_App_BSOD Screenshot](https://user-images.githubusercontent.com/124757309/230703884-035accc5-40ad-4f78-b73c-17eac0ea37f8.jpg)

### Device / Platform

ASUS Strix Z690-A D4

### Crash dumps [Required, if applicable]

[igcit-dumps_b14e9b41.7z-decKey.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11182499/igcit-dumps_b14e9b41.7z-decKey.txt)

### Application / Windows logs

[6_24 BSOD Crash Windows Events.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11182518/6_24.BSOD.Crash.Windows.Events.zip)
[6_27 BSOD Crash Windows Events.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11182519/6_27.BSOD.Crash.Windows.Events.zip)

**Comment by Arturo-Intel** [comment]
Hi @gargamel314 

I am having troubles to replicate this behavior, and I notice you marked all the driver versions from 4091 to 4257, meaning you were able to test on all those versions

Can you reproduce the issue on command? 
And if you do, can you share the steps to reproduce it?

**Comment by Arturo-Intel** [comment]
I see, well I will keep with my tests then
ty for your quick response

**Comment by gargamel314** [comment]
Thank you very much for your diligence, sir!

**Comment by gargamel314** [comment]
I wanted to add some extra information in reproducing this bug. I made it happen again this morning. Usually I open the EA launcher app and launch from there with no issue. Today I was putting my Start Menu back together (this error totally wipes out the start menu), and I created a shortcut directly to the EXE file in the Windows start menu. I accidentally clicked it while I was trying to rename it, and it triggered this BSOD error as soon as the EA app loaded to launch it. EA app was not running in the background at the time (I have that turned off). 

This does involve Star Wars Jedi Fallen Order, but it does not happen in game, it happens before the game even begins to load.

In the past with my NVIDIA card this was never an issue, it would just launch the EA App, and then a few seconds later SWJFO would start with no drama. Ocassionally it would just load the EA App and you'd have to click the button from the launcher to start the game.

So here are the steps to reproduce it (i think):

1. Install Star Wars Jedi: Fallen Order through the EA App. 
2. Go to to the game folder and right-click the starwarsjedifallenorder.exe, click Pin to Start. You'll find this in Jedi Fallen Order\SwGame\Binaries\Win64
4. You may have to have already run it from the launcher a couple times for this to happen. Once it happens, every time you even open the EA app, or even double-clicking the app icon in the notification area of the taskbar, it will go straight to that BSOD as soon as it opens a window. You can't even uninstall/reinstall it to fix the problem, but last time uninstalling and reinstalling the Intel Arc A770 Driver fixed it. 

I'm currently deleting the new shortcuts I made, and will never attempt that again! wow. I'm also attaching a copy of my Intel SSU log since I didn't do that before, now that this error is happening again. 

[ssu - EA App BSOD.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11240020/ssu.-.EA.App.BSOD.txt)

**Comment by gargamel314** [comment]
Occurred again on driver 4369.  This time I did not open the game directly from the EXE, it happened when I started the launcher.

Uninstalling the driver w/ DDU and reinstalling fixed it.

**Comment by gargamel314** [comment]
I have absolutely no idea why it would be enabled. Are you saying that's what would be causing this BSOD? I never enabled it myself. 

If it is, it's persisted through 2 installations of Windows 11. I reinstalled Windows 11 fresh back in March, in fact I think this issue was one of the reasons why I did. Unfortunately, this issue has shown 

I haven't gotten the same BSOD error in a few months, though. Same behavior from the EA app, minus the BSOD during the last 2 occurrences [(see #386)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/386)

**Comment by Arturo-Intel** [comment]
@gargamel314 Did you get your new a770 already? If so, did you manage to reproduce this behavior?

-- r2

**Comment by gargamel314** [comment]
I have not had any problems since getting the new A770 a few weeks ago. I'll report back here if anything happens.

**Comment by gargamel314** [comment]
> Is your Xe attached via a thunderbolt egpu, there is an open windows issue for a crash matching this where Verifier is fully turned off where Kernel DMA Protection interacts with external pci(e) enclosures

it's an Arc A770 16GB plugged directly into the x16 PCIe slot. No thunderbolt or riser cables in use.

**Comment by Squall-Leonhart** [comment]
This can be closed unless gargamel has experienced any issues with the replacement.
