### ISSUE TITLE
Random Crashing in Returnal

### ISSUE THREAD

**Issue by chrissphinx** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#285]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Returnal™

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7-13700KF

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

- [ ] 31.0.101.4257
- [X] 31.0.101.4255
- [ ] 31.0.101.4148
- [X] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11206570/igcit_ssu.txt)

### Description and steps to reproduce [Required]

I guess I'm the lucky winner who's trying to play this game on a PC in 2023 with some pilot hardware. Had pretty rock-solid performance with driver ver 31.0.101.4146 but recently updated to 31.0.101.4255 and Returnal randomly crashes and generally has worse performance. Turning down to low settings seemed like it may run for a while, but higher settings always results in a crash (eventually). It is random so sometimes it happens immediately after game boots but other times it doesn't happen for 30 minutes.

Tried to mitigate issue by providing `-dx11` launch option to game but this resulted in very nasty lag spikes every ~30 seconds.

Finally rolled back intel gfx driver to 31.0.101.4255 and performance is great again. Does 31.0.101.4257 fix issue? I don't see that version on the [intel driver support assistant site](https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html).

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Default Epic settings

**Comment by Arturo-Intel** [comment]
Hey @chrissphinx ! 
Remember to use [DDU ](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) to do a clean install

**Comment by chrissphinx** [comment]
@Arturo-Intel Thanks for the suggestion, though there was a clean install option in the installer when I rolled back to 31.0.101.4146 which I selected. Are you saying I should use this tool to try out the beta? Does the beta driver installer not have a clean install option?

**Comment by chrissphinx** [comment]
Attempting to enable crash dumps using IGCIT Helper appears not to work with this error dialog:

![image](https://user-images.githubusercontent.com/2583639/231502557-6dcbde71-74ba-4742-9e04-be0699c83012.png)

**Comment by chrissphinx** [comment]
Understood, but after switching to beta driver 31.0.101.4257 there has not been a crash in ~30 minutes. I did not use DDU as @Arturo-Intel suggested, but **did** select the clean install option when driver install was ran. Returnal benchmark run was unremarkable.

Switching back to 31.0.101.4255 and I was not able to reproduce the issue, of course. 😞 Last patch to Returnal was March 9th and the issue seemed to coincide with updating from .4146 to .4255 but as I cannot capture a crash, then I recommend issue can be closed.

**Comment by Arturo-Intel** [comment]
@IGCIT can you please close this? :)
