### ISSUE TITLE
Call of Duty: Black Ops Cold War - Graphical Artifacts During Movie/Cutscenes

### ISSUE THREAD

**Issue by DoragonHunter** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#286]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Call of Duty: Black Ops Cold War

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [X] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 7 5800X3D (8-Core / 16-Threads)

### Graphic Card [Required]

Ryzen 7 5800X3D (8-Core / 16-Threads)

### GPU Driver Version [Required]

- [X] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11235058/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Graphical artifact/pixelation can be seen at the left side of the screen when cutscenes/loading movie/movie is played in the game. This also affects the intro movie and the campaign missions.

Steps to Reproduce:
1. Start the game as usual.
2. Note the left artifacting when the logo/movie intro is played. This also happens in cutscenes inside the Campaign missions & loading screens.
![BO1](https://user-images.githubusercontent.com/94206312/232104590-879c89bc-c5e2-4c3f-b4f9-c53f3f491376.png)
![BO2](https://user-images.githubusercontent.com/94206312/232104653-54c2b75e-1c0b-4395-ab6a-37a7476bc65c.png)
![BO3](https://user-images.githubusercontent.com/94206312/232104699-b99ddd8f-e8d1-4e61-aec9-4ce9fefb6d82.png)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

3440x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![Settings](https://user-images.githubusercontent.com/94206312/232104626-8bfff577-a514-4cae-8bf4-147b00a7288c.png)

**Comment by Karen-Intel** [comment]
Heeey @DoragonHunter nice to hear from you again!

We'll check the Graphical artifacts on our end and get back here in case we have questions.

Karen

**Comment by Karen-Intel** [comment]
Heey @DoragonHunter 
Just FYI, I was able to reproduce the issue with driver v4311 in a 13900k system with A770
As in the other post, I am already in the process of reporting it internally so we can have a fix ~3 to 6 months aprox.

Please keep the post open, we will come back and update this thread. 

Thank you for your help, have a great weekend.

Karen

**Comment by ewahl-osc** [comment]
This has gotten worse and worse for me.   In the most recent 4953 drivers 1/2 the screen is garbage now. 

![Screenshot (3)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91157568/9372b9bd-c679-4e2b-92c7-23e13c8ee6a8)

**Comment by Karen-Intel** [comment]
The dev team is already aware of this issue and we will post an update once you can verify in a public release

Karen

**Comment by ewahl-osc** [comment]
Do you mean use WHQL only drivers?  If not, please define "verify in a public release" so that we may confirm it.

**Comment by Karen-Intel** [comment]
Fixes can be included on both. We will verify first and as soon as we see improvements will tell you which one to test with
