### ISSUE TITLE
Assassin's Creed Origins poor performance on 4255+

### ISSUE THREAD

**Issue by trelkins3** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#289]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Assassin's Creed Origins

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7 3700X

### Graphic Card [Required]

Arc A770 (Predator BiFrost 16 GB)

### GPU Driver Version [Required]

- [X] 31.0.101.4311
- [ ] 31.0.101.4257
- [X] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11301813/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Launch game and go to 'Options' -> 'Graphics' -> 'Performance Tools' and run the game benchmark on any settings. Alternatively, and more reliably, launch game and simply play it. Press 'F1' to enable performance metrics and tracking in the HUD.

Framerate inconsistencies and stuttering are immediately apparent and appear to be completely independent of the game's graphical settings. Wide swings from 80+ fps to < 20 fps in some areas, especially those that are densely tessellated or heavily populated by NPCs (Alexandria - the main hub city - is _especially_ bad). Performance in open areas such as random patches of desert is noticeably better.

I observed similarly bad (in fact almost identical) performance across 1080p, 1440p, and 4k in fullscreen mode over a vast variety of settings configurations. Common fixes such as disabling volumetric fog, lowering ambient occlusion, disabling SSAO, and reducing clutter and textures also appear to have no effect on performance whatsoever. Dynamic Resolution and Adaptive Anti-Aliasing similarly have no effect. Using different graphical presets does nothing.

Tried on both 4255 and 4311. 

I have seen forum posts while Googling this issue that indicate Assassin's Creed Odyssey may have similar problems.

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [x] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

From C:\Users\[Username]\Documents\Assassin's Creed Origins\ACO file:
```
[Graphics]
AdapterVendorID=32902
AdapterDeviceID=22176
MonitorDesc=
DisplayIndex=0
WindowPosX=160
WindowPosY=90
FullscreenWidth=1920
FullscreenHeight=1080
WindowedWidth=1920
WindowedHeight=1080
LastCustomWindowWidth=-1
LastCustomWindowHeight=-1
WindowMaximised=0
RefreshRate=144
WindowMode=3
VSyncMode=0
MaxFPS=0
PixelDensity=1.00000
IsUserEditedWindowedDisplaySize=0
LastUsedFullscreenMode=0
AdaptiveQuality=3
Antialiasing=3
Bloom=1
Character=2
CharacterTexture=2
Cloud=0
Clutter=2
CrowdDensity=0
Culling=0
DOF=1
Environment=2
Fog=0
Lighting=0
Particle=0
PostEffect=0
Reflection=1
Shadow=2
SSAO=0
Terrain=0
Tessellation=1
Texture=2
TextureFiltering=2
Water=1
Wind=0
[Options]
SensitivityIndex=4
AimSensitivityIndex=4
AccelerationIndex=0
Controller Feedback=4294967295
InvertMouseCameraControlX=0
InvertMouseCameraControlY=0
EnableCameraAssistanceForMouse=1
FOVScale=1.00000
LockSensitivity=350.00000
LockCursorToTheWindow=0
```

### Device / Platform name

Windows 11

**Comment by trelkins3** [comment]
Also just tried running it in 1080p windowed mode in a suuuuper tiny window and had the exact same problem, which indicates to me that this is a driver issue rather than a hardware performance problem.

**Comment by Karen-Intel** [comment]
Hi @trelkins3 thank you for submitting your findings and all the additional details. 

We are already working on testing the game in a similar configuration so we will get back soon with our results :)

Stay tuned!

Karen

**Comment by trelkins3** [comment]
@Karen-Intel Fantastic news! Been looking forward to playing it for a while, thanks for letting me know :)

**Comment by Karen-Intel** [comment]
Hey @trelkins3 and @AndrejfSantos just did some testing using the latest [DDU version ](https://www.wagnardsoft.com/forums/viewtopic.php?t=4491) and the latest GFX Driver release[ v4314](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html)

I'm attaching in this [.zip file ](https://drive.google.com/drive/folders/1CvmdfVMiBFeSRaEoQ_XYUE4y87U6Jk03?usp=sharing)the results I got from the benchmark. The best performance results I got were in HD resolution using the default settings, so probably you will see an improvement using the latest driver version.

![benchmark_results](https://user-images.githubusercontent.com/91162218/234729701-e7bb1ff1-671e-49ed-9985-103343ff34e8.jpg)

Please give it a go, using DDU of course, it also has great improvements.
For the time being, we can use the benchmark as a baseline for the 3 of us to compare and if we keep seeing discrepancies after following the same driver and driver upgrade method I will gladly report the issue internally for you.

Hope to hear from you soon

Karen

**Comment by trelkins3** [comment]
@Karen-Intel Thanks for the update! I performed a fresh install of v4314 using DDU. Unfortunately I did not see a performance boost; it actually seems to have lowered the frame score I've been getting on the benchmark by about ~2% in 1080p, 1440p, and 4k resolution configurations.

I can upload screenshots if you'd like but I want to try a couple things I hadn't tried previously. I also neglected to mention (in case it matters) that I do have Resizable BAR and Above 4G Decoding enabled in my BIOS.

I have suspicions it may be a CPU constraint or problem with Ubisoft's software. I am going to do a bit of tinkering and testing and I'll report back if I find any magic fixes.

**Comment by AndrejfSantos** [comment]
So, just used the latest [DDU version ](https://www.wagnardsoft.com/forums/viewtopic.php?t=4491)and the latest GFX Driver release[ v4314](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html),
Here are my results on Odyssey:

![o](https://user-images.githubusercontent.com/5563293/234805121-f179458f-c5f8-4d08-8182-1344f5d59595.png)

The low 6 is still very noticeable, also during the run GPU activity was 100% the whole time so its definitely the bottleneck

Apologies to [trelkins3](https://github.com/trelkins3) and [Karen-Intel](https://github.com/Karen-Intel) for using this tread for Odyssey, I just thought the issue might be the same as its the same game engine

**Comment by trelkins3** [comment]
Okay, I found a fix. Buckle up, this will be somewhat long.

Before I updated from v4255 to v4314, this is the performance I was seeing with the in game benchmark using the 'High' preset on 1920x1080p resolution:
![old_driver_1080p_high](https://user-images.githubusercontent.com/22403959/234935618-b1cfd2d1-ba3e-4d06-aea6-9066395eb7d4.jpg)

Not great. I used DDU (excellent idea, thank you @Karen-Intel) to install v4314 and ran the benchmark again. Unfortunately, the performance was about the same and actually dropped slightly using the same settings. I forgot to take a screenshot, but it looked almost exactly like the image above.

So: what if it's a CPU problem and not an Arc or driver issue? I moved the game to an NVMe M.2 SSD, told Windows 11 to 'run as administrator', set the process priority to "high" using the task manager, and even tried closing Chrome and Ubisoft Connect while running the benchmark. I was able to improve the score to **~5300**, about a **7% improvement**. Still not good enough.

While Googling, I stumbled across an open source package called [dxvk](https://github.com/doitsujin/dxvk/releases/tag/v2.1). It is a Vulkan-based translation layer for DX9/10/11. I was skeptical because it doesn't formally have Windows support, but I found [this Reddit post](https://www.reddit.com/r/pcgaming/comments/mlfcsc/a_guide_to_dxvk_on_windows/) and decided to give it a shot. It's as easy as downloading the release and moving the correct .dll files (there are 2 for DX11) into the game's base installation folder.

The results were massive and instant. Using dxvk, on v4314, 'high' preset, 1080p resolution:
![with_dxvk_1080p_high](https://user-images.githubusercontent.com/22403959/234937086-0710f049-357f-4540-86f9-1a522e9fe008.jpg)

This is **2.24 times** the frame score of the original benchmark - a **124%** improvement in performance. Pretty good! There were a couple weird spikes where the game froze, but I believe it's because the shaders were being compiled. It went away after a couple benchmark runs and I haven't seen it since. I even un-modified the process priority and the results were the same.

I am now getting ~75 fps average on 1440p, 'very high' preset. Woohoo!

@AndrejfSantos I would highly recommend trying dxvk. According to [this article](https://www.gamingonlinux.com/2022/12/intel-using-dxvk-part-of-steam-proton-for-their-windows-arc-gpu-dx-9-drivers/), Intel actually _already_ uses dxvk for improving performance drastically in some DX9 games. If possible to relay to the internal team @Karen-Intel, I think it may be worth investigating using dxvk for some DX11 titles as well. It seems like the Arc has some DX11 translation problems - maybe this is a possible fix for certain particularly problematic games if the team is already using it for DX9?

Have not tried with Odyssey, but I'm assuming it will help since (like Andrej said) it's the same game engine.

**Comment by AndrejfSantos** [comment]
Massive improvements, about 2x as well:
![o2](https://user-images.githubusercontent.com/5563293/234951222-f2c971f4-0422-478c-8da0-93311b844ea5.png)

So yeah the issue is the same and both game follow the same pattern.
Another thing I noticed is that this time the GPU wasnt always at 100%, so whatever the reason, it was working less and outputting 2x

**Comment by trelkins3** [comment]
@Karen-Intel I'm satisfied - although I wonder if there's a way we can tag this somehow for anyone specifically looking for Assassin's Creed help here in the future. I will let you close as I'm not sure if there's a 'right' way to do it.

Thank you for your help as well, much appreciated!
