### ISSUE TITLE
Open GL very bad driver or performance

### ISSUE THREAD

**Issue by hididi31** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#29]
#### Game _[Required]_
All games need open gl and emulatord

---
#### CPU _[Required]_
I7 1160g7

---
#### GPU Driver Version _[Required]_
Last build

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_:OpenGL
**API Version** _(example DirectX 12)_:

---
#### Windows Build Number _[Required]_

Last build
---
#### Description _[Required]_
Very bad performance 
---
#### Steps To Reproduce _[Required]_
Just launch game as Rage fort exemple or citra3ds and constat thé OpenGL driver of the last tiger lake is very bad

---
#### Screenshots _[Optional]_

---

**Comment by Valkirie** [comment]
Thanks for sharing but closing this one report as we need software-specific issues to have a chance to get them fixed.
When related to emulation we only accept reports coming from developers as we need a lot of details.
