### ISSUE TITLE
[A750][13900K+Z790] Absurd DPC latency during W11 desktop usage freezes mouse, stutters audio etc.

### ISSUE THREAD

**Issue by dcominottim** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#292]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

General desktop usage

### Processor / Processor Number [Required]

13900K

### Graphic Card [Required]

Arc 750

### GPU Driver Version [Required]

- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [X] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[intel-ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11322765/intel-ssu.txt)

### Description and steps to reproduce [Required]

During general desktop usage, in situations of CPU/storage spikes (e.g.: launching an application, opening a video file, running an installer etc.) with an A750 card, there are huge DPC latency spikes that result in mouse freezes for 1-2 seconds and audio stuttering/crackling. I often have Discord, Edge, an Hyper-V virtual machine, and Plex Media Server running most of the time. If I replace the Intel card with an NVIDIA one, the problem goes away. (Obs.: I fully uninstall the NVIDIA drivers using DDU when using the Arc card.) I use LatencyMon to monitor DPC latency.

### Application / Windows logs

![image](https://user-images.githubusercontent.com/4914233/234287455-af1e0485-4faf-499e-9e61-b6d9a2be886e.png)

**Comment by Arturo-Intel** [comment]
Hello @dcominottim,

Did you start seeing this lag in the driver v4255? 
Did you try with the 4311? 

I will replicate this on our lab, keep you posted!

--r2

**Comment by dcominottim** [comment]
Hi, @Arturo-Intel -- thanks for the message!

I have edited the OP -- I am actually on driver v4255, the latest stable offered to me.

I don't know if the issue manifested in previous versions because I wasn't using the A750 again until about a week ago.

I will try driver v4311 and let you know the results.

**Comment by akarnokd** [comment]
Hi. I've been experiencing similar audio stutter/crackling, although not this drastic - no mouse issues or freezes. I'm on a 13700k+B760, Win 11. Should I open a separate issue?

**Comment by dcominottim** [comment]
From my end, it seems the latest beta driver v4311 has solved the issues, @Arturo-Intel. 

@akarnokd, if you're not on the latest beta, I suggest you try it, too.

**Comment by Vegas7** [comment]
Suggest giving 4314 a try, with the audio stuttering issue fix.

**Comment by Karen-Intel** [comment]
Hi @Vegas7 have you also tested the latest driver release? [v.4314](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html)
We also have anew [DDU version](https://www.wagnardsoft.com/forums/viewtopic.php?t=4491), can you please give it a go? 

@dcominottim if the newest releases have fixed the issue for you, would you agree to close this post?

Thank you and please let us know

Karen

**Comment by Arturo-Intel** [comment]
I think we can close the issue @IGCIT
