### ISSUE TITLE
Arc control breaks on screen resolution change

### ISSUE THREAD

**Issue by IGCIT** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#298]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Arc Control

### Processor / Processor Number [Required]

i9-11900KB

### Graphic Card [Required]

Arc A770

### GPU Driver Version [Required]

- [X] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11359996/igcit_ssu.txt)

### Description and steps to reproduce [Required]

make sure arc control is running in system tray
my screen resolution is 1080

1)  go to display settings and change resolution to 1280x720 and apply
2) change the resolution back to 1920x1080 and apply
3) open arc control from system tray

arc control window has wrong dimensions and it is now frozen, so you must close it from tray context menu and restart the application from start menu

**Comment by Karen-Intel** [comment]
Hey @IGCIT thank you for posting your findings!

I'm already reporting this behavior internally as I was able to reproduce with latest beta driver in a 13900K machine +ARC A770 +Gfx v.4335.
It is most likely a regression so probably we would have updates in a couple months. Let's leave this post open until a fix has been released.

Thank you for your help!

Karen

**Comment by Karen-Intel** [comment]
Hey @IGCIT what is the vBIOS version of your ARC? You can find it under ARC Control > Settings Gear > System info

Thank you :)

Karen

**Comment by IGCIT** [comment]
20.1053.0

**Comment by Karen-Intel** [comment]
Hey @IGCIT can you check performance of this issue with the latest ARC Control version? The one with v.4575 :)

Thanks

Karen

**Comment by IGCIT** [comment]
fixed, thanks
