### ISSUE TITLE
Git Reports Issue

### ISSUE THREAD

**Issue by IGCIT** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#3]
Submitter: Jeff
Game: Any software.
CPU: i5-1035G7
GPU Driver Version: 27.20.100.8190
Rendering API: NA (happens inside and outside of games)
API [DirectX, OpenGL, Vulkan]:(happens inside and outside of games)

API Version (example DirectX 12): (happens inside and outside of games)

Windows Build Number: 19041
Description: Frequent 0x116: VIDEO_TDR_FAILURE BSODs, roughly 2-3 times daily
Screenshots NA
Steps To Reproduce: Normal use in Google Chrome or Games
Notes Driver 8109 is the only driver that does not suffer catastrophic performance in the games that I play (Fallout 4, Dishonored 2)--will submit other issues for those. But this is the only problem that plagues 8109 in my experience.

**Comment by Valkirie** [comment]
Closing this issue. VIDEO_TDR_FAILURE is most certainly due to agressive undervolting.
