### ISSUE TITLE
Detroit - Become Human not working

### ISSUE THREAD

**Issue by kyh96403** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#30]
#### Game _[Required]_
Detroit - Become Human

---
#### CPU _[Required]_
1035G7
1160G7

---
#### GPU Driver Version _[Required]_
All

---
#### Rendering API _[Required]_
Vulkan

**API** _[DirectX, OpenGL, Vulkan]_:
**API Version** _(example DirectX 12)_:

---
#### Windows Build Number _[Required]_
20H2

---
#### Description _[Required]_
Not working, just nothing

---
#### Steps To Reproduce _[Required]_
just launch

---
#### Screenshots _[Optional]_

---

**Comment by Valkirie** [comment]
Thanks for sharing but closing this one. Duplication of #16.
Will edit/comment the original post to add the IceLake SKUS mentioned here.
