### ISSUE TITLE
Lightroom new denoiser artifacts to DNG

### ISSUE THREAD

**Issue by bearshen** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#300]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Adobe Lightroom

### Processor / Processor Number [Required]

AMD Ryzen 5 5600X

### Graphic Card [Required]

Intel Arc A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

# SSU Scan Information
Scan Info:
 Version:"2.5.0.15"
 Date:"04/29/2023"
 Time:"00:00:22.9670608"

# Scanned Hardware
Computer:
          BaseBoard Manufacturer:"ASUSTeK COMPUTER INC."
          BIOS Mode:"Legacy"
          BIOS Version/Date:"American Megatrends Inc. 4408 , 10/28/2022 12:00 AM"
          CD or DVD:"Not Available"
          Embedded Controller Version:"255.255"
          Platform Role:"Desktop"
          Processor:"AMD Ryzen 5 5600X 6-Core Processor              , AuthenticAMD"
          Secure Boot State:"Off"
          SMBIOS Version:"3.3"
          Sound Card:"High Definition Audio Device"
          System Manufacturer:"System manufacturer"
          System Model:"System Product Name"
          System SKU:"SKU"
          System Type:"x64-based PC"
          - "Display"
               Intel ® Graphics Driver Version:"Not Available"
               - "Intel(R) Arc(TM) A770 Graphics"
                    Adapter Compatibility:"Intel Corporation"
                    Adapter DAC Type:"Internal"
                    Adapter RAM:"1.00 GB"
                    Availability:"Running or Full Power"
                    Bits Per Pixel:"32"
                    - "Caption":"Intel(R) Arc(TM) A770 Graphics"
                         Link:"http://www.intel.com/content/www/us/en/search.html?keyword=Arc+A770+Graphics"
                    CoInstallers:"oem9.inf,iDG2DH_w10_DS,Internal,Intel(R) Arc(TM) A770 Graphics Family"
                    Color Table Entries:"4294967296"
                    Dedicated Video Memory:"Not Available"
                    Driver:"igdkmdnd64.sys"
                    Driver Date:"04/20/2023 05:00 PM"
                    Driver Path:"C:\Windows\system32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_be925909b882ee5b\igdkmdnd64.sys"
                    Driver Provider:"Intel Corporation"
                    Driver Version:"31.0.101.4335"
                    INF:"oem9.inf"
                    INF Section:"iDG2DH_w10_DS"
                    Install Date:"Not Available"
                    Installed Drivers:"C:\Windows\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_be925909b882ee5b\igdumdim64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_be925909b882ee5b\igd10iumd64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_be925909b882ee5b\igd10iumd64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_be925909b882ee5b\igd12umd64.dll"
                    Last Error Code:"Not Available"
                    Last Error Code Description:"Not Available"
                    Last Reset:"Not Available"
                    Location:"PCI bus 11, device 0, function 0"
                    Manufacturer:"Intel Corporation"
                    Microsoft DirectX* Version:"DirectX 12"
                    Monochrome:"No"
                    Number of Colors:"4294967296"
                    Number of Video Pages:"Not Available"
                    PNP Device ID:"PCI\VEN_8086&DEV_56A0&SUBSYS_10208086&REV_08\6&12FFFB42&0&00080019"
                    Power Management Capabilities:"Not Available"
                    Power Management Supported:"Not Available"
                    Refresh Rate - Current:"120 Hz"
                    Refresh Rate - Maximum:"164 Hz"
                    Refresh Rate - Minimum:"23 Hz"
                    Resolution:"3440 X 1440"
                    Scan Mode:"Noninterlaced"
                    Service Name:"igfxnd"
                    Status:"OK"
                    Video Architecture:"VGA"
                    Video Memory:"Unknown"
                    Video Processor:"Intel(R) Arc(TM) A770 Graphics Family"
          - "Memory"
               Physical Memory (Available):"18.39 GB"
               Physical Memory (Installed):"32 GB"
               Physical Memory (Total):"31.91 GB"
               - "BANK 0"
                    Capacity:"16 GB"
                    Channel:"DIMM_A1"
                    Configured Clock Speed:"3000 MHz"
                    Configured Voltage:"1200 millivolts"
                    Data Width:"64 bits"
                    Form Factor:"DIMM"
                    Interleave Position:"Not Available"
                    Manufacturer:"Corsair"
                    Maximum Voltage:"Not Available"
                    Memory Type:"Unknown"
                    Minimum Voltage:"Not Available"
                    Part Number:"CMW32GX4M2C3000C15"
                    Serial Number:"00000000"
                    Status:"Not Available"
                    Type:"Not Available"
               - "BANK 2"
                    Capacity:"16 GB"
                    Channel:"DIMM_B1"
                    Configured Clock Speed:"3000 MHz"
                    Configured Voltage:"1200 millivolts"
                    Data Width:"64 bits"
                    Form Factor:"DIMM"
                    Interleave Position:"Not Available"
                    Manufacturer:"Corsair"
                    Maximum Voltage:"Not Available"
                    Memory Type:"Unknown"
                    Minimum Voltage:"Not Available"
                    Part Number:"CMW32GX4M2C3000C15"
                    Serial Number:"00000000"
                    Status:"Not Available"
                    Type:"Not Available"
          - "Motherboard"
               Availability:"Running or Full Power"
               BIOS:"4408, ALASKA - 1072009"
               Caption:"Motherboard"
               Chipset:"Not Available"
               Date:"10/27/2022 05:00 PM"
               Install Date:"Not Available"
               Last Error Code:"Not Available"
               Last Error Code Description:"Not Available"
               Manufacturer:"ASUSTeK COMPUTER INC."
               Model:"Not Available"
               Part Number:"Not Available"
               PNP Device ID:"ACPI\PNP0C01\C8"
               Power Management Capabilities:"Not Available"
               Power Management Supported:"Not Available"
               Product:"ROG STRIX X570-I GAMING"
               Serial Number:"210484583902489"
               Status:"OK"
               Version:"Rev X.0x"
          - "Networking"
               Intel ® Network Connections Install Options:"Not Available"
               Intel ® Network Connections Version:"Not Available"
               Intel ® PROSet/Wireless Software Version:"Not Available"
               - "Bluetooth Device (Personal Area Network)"
                    Availability:"Running or Full Power"
                    Caption:"Bluetooth Device (Personal Area Network)"
                    CoInstallers:"Not Available"
                    Default IP Gateway:"Not Available"
                    DHCP Enabled:"Yes"
                    DHCP Lease Expires:"Not Available"
                    DHCP Lease Obtained:"Not Available"
                    DHCP Server:"Not Available"
                    Driver:"bthpan.sys"
                    Driver Date:"06/21/2006 12:00 AM"
                    Driver Path:"C:\Windows\system32\drivers\bthpan.sys"
                    Driver Provider:"Microsoft"
                    Driver Version:"10.0.22621.1555"
                    Index:"0013"
                    INF:"bthpan.inf"
                    INF Section:"BthPan.Install"
                    Install Date:"Not Available"
                    Installed:"Yes"
                    IP Address:"Not Available"
                    IP Subnet:"Not Available"
                    Last Error Code:"Not Available"
                    Last Error Code Description:"Not Available"
                    Last Reset:"04/29/2023 03:23 PM"
                    Location:"Not Available"
                    MAC Address:"B4:0E:DE:6A:E7:D4"
                    Manufacturer:"Microsoft"
                    Media Type:
                    Net Connection ID:"Bluetooth Network Connection"
                    NetCfgInstanceId:"{865F8A3E-56FE-4306-B0C3-BA21E430F157}"
                    Number of VLANs:"0"
                    PNP Device ID:"BTH\MS_BTHPAN\9&3331EA41&0&2"
                    Port:"Not Available"
                    Power Management (Low Power):"Not Available"
                    Power Management (Wake On LAN):"Not Available"
                    Power Management (Wake on Magic Packet):"Not Available"
                    Power Management Capabilities:"Not Available"
                    Power Management Supported:"No"
                    Product Type:"Bluetooth Device (Personal Area Network)"
                    Service Name:"BthPan"
                    Status:"Enabled"
                    Team Name:"Not in a team"
                    Temperature:
                    Type:"Ethernet 802.3"
                    - "Service Bindings"
                         Client for Microsoft Networks:
                         File and Printer Sharing for Microsoft Networks:
                         Internet Protocol Version 4 (TCP/IPv4):
                         Internet Protocol Version 6 (TCP/IPv6):
                         Link-Layer Topology Discovery Mapper I/O Driver:
                         Link-Layer Topology Discovery Responder:
                         Microsoft LLDP Protocol Driver:
               - "Intel(R) I211 Gigabit Network Connection"
                    Availability:"Running or Full Power"
                    - "Caption":"Intel(R) I211 Gigabit Network Connection"
                         Link:"http://www.intel.com/content/www/us/en/search.html?keyword=I211+Gigabit+Network+Connection"
                    CoInstallers:"Not Available"
                    Default IP Gateway:"192.168.1.1"
                    DHCP Enabled:"Yes"
                    DHCP Lease Expires:"04/29/2023 06:23 PM"
                    DHCP Lease Obtained:"04/29/2023 04:23 PM"
                    DHCP Server:"192.168.1.1"
                    Driver:"e1i68x64.sys"
                    Driver Date:"06/24/2021 12:00 AM"
                    Driver Path:"C:\Windows\system32\drivers\e1i68x64.sys"
                    Driver Provider:"Microsoft"
                    Driver Version:"12.19.1.32"
                    ETrackID:"Not Available"
                    Index:"0001"
                    INF:"net1ic64.inf"
                    INF Section:"E1539.10.0.1.19H1"
                    Install Date:"Not Available"
                    Installed:"Yes"
                    IP Address:"192.168.1.156;fe80::b5dd:4fcd:89ee:f50a"
                    IP Subnet:"255.255.255.0;64"
                    Last Error Code:"Not Available"
                    Last Error Code Description:"Not Available"
                    Last Reset:"04/29/2023 03:23 PM"
                    Location:"PCI bus 5, device 0, function 0"
                    MAC Address:"7C:10:C9:3C:4D:FA"
                    Manufacturer:"Intel Corporation"
                    Media Type:
                    Net Connection ID:"Ethernet"
                    NetCfgInstanceId:"{2F358AFD-9F52-461E-AFAB-D39F43E89B63}"
                    Number of VLANs:"0"
                    NVM Version:"Not Available"
                    Part Number:"Not Available"
                    PNP Device ID:"PCI\VEN_8086&DEV_1539&SUBSYS_85F01043&REV_03\7C10C9FFFF3C4DFA00"
                    Port:"Not Available"
                    Power Management (Low Power):"Active: Yes, Enable: Yes"
                    Power Management (Wake On LAN):"Active: Yes, Enable: Yes"
                    Power Management (Wake on Magic Packet):"Active: Yes, EnableWakeOnMagicPacketOnly: No"
                    Power Management Capabilities:"Not Available"
                    Power Management Supported:"No"
                    Product Type:"Intel(R) I211 Gigabit Network Connection"
                    Service Name:"e1i68x64"
                    Status:"Enabled"
                    Team Name:"Not in a team"
                    Temperature:
                    Type:"Ethernet 802.3"
                    - "Service Bindings"
                         Bridge Driver:
                         Client for Microsoft Networks:
                         File and Printer Sharing for Microsoft Networks:
                         Internet Protocol Version 4 (TCP/IPv4):
                         Internet Protocol Version 6 (TCP/IPv6):
                         Link-Layer Topology Discovery Mapper I/O Driver:
                         Link-Layer Topology Discovery Responder:
                         Microsoft LLDP Protocol Driver:
                         QoS Packet Scheduler:
                    - "Settings"
                         *FlowControl:Flow Control:"Rx & Tx Enabled (3)"
                         *InterruptModeration:Interrupt Moderation:"Enabled (1)"
                         *IPChecksumOffloadIPv4:IPv4 Checksum Offload:"Rx & Tx Enabled (3)"
                         *JumboPacket:Jumbo Packet:"Disabled (1514)"
                         *LsoV2IPv4:Large Send Offload V2 (IPv4):"Enabled (1)"
                         *LsoV2IPv6:Large Send Offload V2 (IPv6):"Enabled (1)"
                         *NumRssQueues:Maximum Number of RSS Queues:"2 Queues (2)"
                         *PMARPOffload:ARP Offload:"Enabled (1)"
                         *PMNSOffload:NS Offload:"Enabled (1)"
                         *PriorityVLANTag:Packet Priority & VLAN:"Packet Priority & VLAN Enabled (3)"
                         *PtpHardwareTimestamp:"Disabled (0)"
                         *ReceiveBuffers:Receive Buffers:"256 (256)"
                         *RSS:Receive Side Scaling:"Enabled (1)"
                         *SoftwareTimestamp:"Disabled (0)"
                         *SpeedDuplex:Speed & Duplex:"Auto Negotiation (0)"
                         *TCPChecksumOffloadIPv4:TCP Checksum Offload (IPv4):"Rx & Tx Enabled (3)"
                         *TCPChecksumOffloadIPv6:TCP Checksum Offload (IPv6):"Rx & Tx Enabled (3)"
                         *TransmitBuffers:Transmit Buffers:"512 (512)"
                         *UDPChecksumOffloadIPv4:UDP Checksum Offload (IPv4):"Rx & Tx Enabled (3)"
                         *UDPChecksumOffloadIPv6:UDP Checksum Offload (IPv6):"Rx & Tx Enabled (3)"
                         AdaptiveIFS:Adaptive Inter-Frame Spacing:"Disabled (0)"
                         EEELinkAdvertisement:"1 (1)"
                         ITR:Interrupt Moderation Rate:"Adaptive (65535)"
                         LogLinkStateEvent:Log Link State Event:"Enabled (51)"
                         MasterSlave:Gigabit Master Slave Mode:"Auto Detect (0)"
                         ReduceSpeedOnPowerDown:Reduce Speed On Power Down:"Enabled (1)"
                         WaitAutoNegComplete:Wait for Link:"Auto Detect (2)"
               - "Intel(R) Wi-Fi 6 AX200 160MHz"
                    Access Point:
                    Authentication:
                    Availability:"Running or Full Power"
                    - "Caption":"Intel(R) Wi-Fi 6 AX200 160MHz"
                         Link:"http://www.intel.com/content/www/us/en/search.html?keyword=Wi+Fi+6+AX200+160MHz"
                    Channel:
                    Cipher:
                    CoInstallers:"Not Available"
                    Connection Mode:
                    Default IP Gateway:"Not Available"
                    DHCP Enabled:"Yes"
                    DHCP Lease Expires:"Not Available"
                    DHCP Lease Obtained:"Not Available"
                    DHCP Server:"Not Available"
                    Driver:"Netwtw10.sys"
                    Driver Date:"01/17/2023 12:00 AM"
                    Driver Path:"C:\Windows\system32\drivers\Netwtw10.sys"
                    Driver Provider:"Intel"
                    Driver Version:"22.200.0.6"
                    Index:"0002"
                    INF:"oem32.inf"
                    INF Section:"Install_GEN_QSR_CcP_200_AX_2x2_WinT"
                    Install Date:"Not Available"
                    Installed:"Yes"
                    IP Address:"Not Available"
                    IP Subnet:"Not Available"
                    Last Error Code:"Not Available"
                    Last Error Code Description:"Not Available"
                    Last Reset:"04/29/2023 03:23 PM"
                    Location:"PCI bus 4, device 0, function 0"
                    MAC Address:"B4:0E:DE:6A:E7:D0"
                    Manufacturer:"Intel Corporation"
                    Media Type:
                    Net Connection ID:"Wi-Fi"
                    NetCfgInstanceId:"{802DB221-AF25-462F-BAAF-6E4ABB48F36B}"
                    Network Name:"Wi-Fi"
                    Network Type:
                    Number of VLANs:"0"
                    PNP Device ID:"PCI\VEN_8086&DEV_2723&SUBSYS_00848086&REV_1A\6&13EE9B71&0&0018000A"
                    Port:"Not Available"
                    Power Management (Low Power):"Not Available"
                    Power Management (Wake On LAN):"Not Available"
                    Power Management (Wake on Magic Packet):"Not Available"
                    Power Management Capabilities:"Not Available"
                    Power Management Supported:"No"
                    Product Type:"Intel(R) Wi-Fi 6 AX200 160MHz"
                    Profile:
                    Radio Type:
                    Receive Rate:
                    Service Name:"Netwtw10"
                    Signal Strength:
                    State:"disconnected"
                    Status:"Enabled"
                    Team Name:"Not in a team"
                    Temperature:
                    Transmit Rate:
                    Type:"Ethernet 802.3"
                    - "Service Bindings"
                         Bridge Driver:
                         Client for Microsoft Networks:
                         File and Printer Sharing for Microsoft Networks:
                         Internet Protocol Version 4 (TCP/IPv4):
                         Internet Protocol Version 6 (TCP/IPv6):
                         Link-Layer Topology Discovery Mapper I/O Driver:
                         Link-Layer Topology Discovery Responder:
                         Microsoft LLDP Protocol Driver:
                         QoS Packet Scheduler:
                    - "Settings"
                         *DeviceSleepOnDisconnect:Sleep on WoWLAN Disconnect:"Disabled (0)"
                         *PacketCoalescing:Packet Coalescing:"Enabled (1)"
                         *PMARPOffload:ARP offload for WoWLAN:"Enabled (1)"
                         *PMNSOffload:NS offload for WoWLAN:"Enabled (1)"
                         *PMWiFiRekeyOffload:GTK rekeying for WoWLAN:"Enabled (1)"
                         *WakeOnMagicPacket:Wake on Magic Packet:"Enabled (1)"
                         *WakeOnPattern:Wake on Pattern Match:"Enabled (1)"
                         ChannelWidth24:Channel Width for 2.4GHz:"Auto (1)"
                         ChannelWidth52:Channel Width for 5GHz:"Auto (1)"
                         CtsToItself:Mixed Mode Protection:"RTS/CTS Enabled (0)"
                         FatChannelIntolerant:Fat Channel Intolerant:"Disabled (0)"
                         IbssTxPower:Transmit Power:"5. Highest (100)"
                         IEEE11nMode:802.11n/ac/ax Wireless Mode:"4. 802.11ax (3)"
                         MIMOPowerSaveMode:MIMO Power Save Mode:"Auto SMPS (0)"
                         RoamAggressiveness:Roaming Aggressiveness:"3. Medium (2)"
                         RoamingPreferredBandType:Preferred Band:"1. No Preference (0)"
                         ThroughputBoosterEnabled:Throughput Booster:"Disabled (0)"
                         uAPSDSupport:U-APSD support:"Disabled (0)"
                         WirelessMode:802.11a/b/g Wireless Mode:"6. Dual Band 802.11a/b/g (34)"
          - "Operating System"
               .Net Framework Version:"4.0,4.8"
               Boot Device:"\Device\HarddiskVolume1"
               Locale:"United States"
               OS Manufacturer:"Microsoft Corporation"
               OS Name:"Microsoft Windows 11 Pro"
               Other OS Description:"Not Available"
               Page File:"C:\pagefile.sys"
               Page File Space:"2.00 GB"
               Physical Memory (Available):"18.41 GB"
               Physical Memory (Installed):"32 GB"
               Physical Memory (Total):"31.91 GB"
               System Directory:"C:\Windows\system32"
               Version:"10.0.22621 Build 22621"
               Virtual Memory (Available):"9.61 GB"
               Virtual Memory (Total):"33.91 GB"
               Windows Directory:"C:\Windows"
               - "Installed Updates"
                    KB2151757:"Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219 [2/2/2023]"
                    KB2467173:"Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219 [2/2/2023]"
                    KB2468871:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2468871:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2468871v2:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2468871v2:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2478063:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2478063:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2533523:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2533523:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2544514:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2544514:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2600211:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2600211:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2600217:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2600217:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB5012170:"Security Update [1/23/2023]"
                    KB5022497:"Update [2/15/2023]"
                    KB5025239:"Security Update [4/12/2023]"
                    KB5025749:"Security Update [4/12/2023]"
                    KB982573:"Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219 [2/2/2023]"
                    SP1:"Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219 [Not Available]"
          - "Processor"
               Not Available:
          - "Storage"
               - "Samsung SSD 850 PRO 512GB"
                    Capablities:"Random Access, Supports Writing, SMART Notification"
                    Caption:"Samsung SSD 850 PRO 512GB"
                    Cylinder - Total:"62260"
                    Description:"Disk drive"
                    Driver:"Not Available"
                    Driver Date:"06/21/2006 12:00 AM"
                    Driver Version:"10.0.22621.608"
                    Error Code:"Device is working properly"
                    Firmware Revision:"EXM02B6Q"
                    Heads - Total:"255"
                    Index:"1"
                    INF:"disk.inf"
                    Install Date:"Not Available"
                    Interface Type:"IDE"
                    Manufacturer:"(Standard disk drives)"
                    Model:"Samsung SSD 850 PRO 512GB"
                    Name:"\\.\PHYSICALDRIVE1"
                    Partitions:"1"
                    Physical Sector Size:"512"
                    PNP Device ID:"SCSI\DISK&VEN_SAMSUNG&PROD_SSD_850_PRO_512G\7&1EEDC5B6&0&050000"
                    Policies:"Read Retention Priority=EqualPriority, Write Retention Priority=EqualPriority, Scalar Prefetch=Not Available, Block Prefetch=Not Available"
                    Sectors - Per Track:"63"
                    Sectors - Total:"1000206900"
                    Serial Number:"S250NSAG510905B"
                    Size:"476.94 GB"
                    Size – Available:"476.08 GB"
                    SMART Attributes:"Self-Test: 255 minutes, OK, Short Self-Test: 2 minutes, OK"
                    Status:"OK"
                    Tracks - Per Cylinder:"255"
                    Tracks - Total:"15876300"
                    - "E:"
                         Availability:"Not Available"
                         Caption:"E:"
                         Compression Method:"Not Compressed"
                         Description:"Local Fixed Disk"
                         File System:"NTFS"
                         Name:"LEGACY"
                         Serial Number:"E0994CEB"
                         Size:"476.94 GB"
                         Size – Available:"476.08 GB"
                         Status:"Not Available"
                         Volume Dirty:"No"
                    - "SMART"
                         0x05  Reallocated Sector Count:0:"0"
                         0x09  Power-On Hours:14201:"0"
                         0x0C  Power Cycle Count:401:"0"
                         0xB1  Wear Range Delta:61:"89"
                         0xB3  Used Reserved Block Count Total:0:"0"
                         0xB5  Program Fail Count Total:0:"0"
                         0xB6  Erase Fail Count:0:"0"
                         0xB7  SATA Downshift Count:0:"0"
                         0xBB  Uncorrectable Error Count:0:"0"
                         0xBE  Temperature - Current:36° C:"0"
                         0xBE  Temperature - Highest:Not Available:"0"
                         0xBE  Temperature - Lowest:Not Available:"0"
                         0xC3  Hardware ECC Recovered:0:"0"
                         0xC7  CRC Error Count:0:"0"
                         0xEB  Good Block Count:85:"0"
                         0xF1  Total LBAs Written:27875532419:"0"
               - "Samsung SSD 970 EVO 1TB"
                    Capablities:"Random Access, Supports Writing"
                    Caption:"Samsung SSD 970 EVO 1TB"
                    Cylinder - Total:"121601"
                    Description:"Disk drive"
                    Driver:"Not Available"
                    Driver Date:"06/21/2006 12:00 AM"
                    Driver Version:"10.0.22621.608"
                    Error Code:"Device is working properly"
                    Firmware Revision:"2B2QEXE7"
                    Heads - Total:"255"
                    Index:"2"
                    INF:"disk.inf"
                    Install Date:"Not Available"
                    Interface Type:"SCSI"
                    Manufacturer:"(Standard disk drives)"
                    Model:"Samsung SSD 970 EVO 1TB"
                    Name:"\\.\PHYSICALDRIVE2"
                    Partitions:"3"
                    Physical Sector Size:"4096"
                    PNP Device ID:"SCSI\DISK&VEN_NVME&PROD_SAMSUNG_SSD_970\5&2CDD3922&0&000000"
                    Policies:"Read Retention Priority=EqualPriority, Write Retention Priority=EqualPriority, Scalar Prefetch=Not Available, Block Prefetch=Not Available"
                    SCSI Bus:"0"
                    SCSI LUN:"0"
                    SCSI Port:"2"
                    Sectors - Per Track:"63"
                    Sectors - Total:"1953520065"
                    Serial Number:"0025_3857_91B0_0317."
                    Size:"931.51 GB"
                    Size – Available:"760.47 GB"
                    Status:"OK"
                    Tracks - Per Cylinder:"255"
                    Tracks - Total:"31008255"
                    - "C:"
                         Availability:"Not Available"
                         Caption:"C:"
                         Compression Method:"Not Compressed"
                         Description:"Local Fixed Disk"
                         File System:"NTFS"
                         Name:"Not Available"
                         Serial Number:"D2AC7CFA"
                         Size:"930.73 GB"
                         Size – Available:"760.48 GB"
                         Status:"Not Available"
                         Volume Dirty:"No"
               - "ZA3840NM10001"
                    Capablities:"Random Access, Supports Writing, SMART Notification"
                    Caption:"ZA3840NM10001"
                    Cylinder - Total:"466945"
                    Description:"Disk drive"
                    Driver:"Not Available"
                    Driver Date:"06/21/2006 12:00 AM"
                    Driver Version:"10.0.22621.608"
                    Error Code:"Device is working properly"
                    Firmware Revision:"SF442147"
                    Heads - Total:"255"
                    Index:"0"
                    INF:"disk.inf"
                    Install Date:"Not Available"
                    Interface Type:"IDE"
                    Manufacturer:"(Standard disk drives)"
                    Model:"ZA3840NM10001"
                    Name:"\\.\PHYSICALDRIVE0"
                    Partitions:"1"
                    Physical Sector Size:"4096"
                    PNP Device ID:"SCSI\DISK&VEN_&PROD_ZA3840NM10001\7&1EEDC5B6&0&040000"
                    Policies:"Read Retention Priority=EqualPriority, Write Retention Priority=EqualPriority, Scalar Prefetch=Not Available, Block Prefetch=Not Available"
                    Sectors - Per Track:"63"
                    Sectors - Total:"7501471425"
                    Serial Number:"HKT01V4R"
                    Size:"3.49 TB"
                    Size – Available:"3.09 TB"
                    SMART Attributes:"Self-Test: 30 minutes, OK, Short Self-Test: 1 minutes, OK"
                    Status:"OK"
                    Tracks - Per Cylinder:"255"
                    Tracks - Total:"119070975"
                    - "D:"
                         Availability:"Not Available"
                         Caption:"D:"
                         Compression Method:"Not Compressed"
                         Description:"Local Fixed Disk"
                         File System:"NTFS"
                         Name:"New Volume"
                         Serial Number:"C2673487"
                         Size:"3576.97 GB"
                         Size – Available:"3167.57 GB"
                         Status:"Not Available"
                         Volume Dirty:"No"
                    - "SMART"
                         0x01  Raw Read Error Rate:91:"90"
                         0x05  Reallocated Sector Count:0:"0"
                         0x09  Power-On Hours:9379:"0"
                         0x0C  Power Cycle Count:176:"0"
                         0xAA  Available Reserved Space:0:"0"
                         0xAB  Program Fail Count:0:"0"
                         0xAC  Erase Fail Count:0:"0"
                         0xAD  Wear Leveling Count:14:"0"
                         0xAE  Power-off Retract Count:95:"0"
                         0xB1  Wear Range Delta:0:"89"
                         0xB7  SATA Downshift Count:0:"0"
                         0xBB  Uncorrectable Error Count:0:"0"
                         0xC2  Internal Device Temperature:41° C:"0"
                         0xC3  Hardware ECC Recovered:0:"0"
                         0xC6  Uncorrectable Sector Count:0:"0"
                         0xC7  CRC Error Count:0:"0"
                         0xE6  Drive Life Protection Status:100:"91"
                         0xE7  Temperature:Not Available:"10"
                         0xE8  Available Reserved Space:0:"3"
                         0xE9  Media Wearout Indicator:3180:"0"
                         0xF1  Total LBAs Written:3448:"0"
                         0xF2  Total LBAs Read:2561:"0"
                         0xF3  Total LBAs Written Expanded:39281774942770:"3"
...#SSU#...

### Description and steps to reproduce [Required]

![Screenshot 2023-04-29 163006](https://user-images.githubusercontent.com/354090/235328201-ab0abeb6-e742-4c78-8039-fb24e6b23dae.png)

**Comment by Karen-Intel** [comment]
Hey @bearshen thank you for posting your findings.

I am the engineer assigned to your case. I will be performing some tests and get back to you in case I have questions

Karen

**Comment by Karen-Intel** [comment]
Hey @bearshen I think I was able to reproduce the issue. 
[Here's how it looks](https://www.youtube.com/watch?v=HQAOIrDQCZg)

Can you confirm if that's exactly what you're seeing? The preview pretty much saves DNG to Sepia and I do not see any Denoise effect.

Also, do you happen to have a CR2 file to confirm if there's actually any Denoise effect going on? I just see the sepia coloring but the picture I used may not be a good example. If you can please share a DNG or CR2 file with noise as I have pending to check on an NVIDIA system too.

Thank you

Karen

**Comment by bearshen** [comment]
I have tried multiple Sony and Fuji RAW files and they all outputs sepia like. I don't use CR2 files. Based on what I understand, file format shouldn't matter anyways.

**Comment by Karen-Intel** [comment]
@bearshen gotcha. I will create later some noisy pictures with my camera just to test

Okay, FYI, I am already reporting this strange -sepia- behavior internally. 
To have a fix released may take between 3 to 6 months so, please keep this post open, as in case I have any updates for you I will add them in this thread.

Thank you so much for your help, have a great weekend!

Karen

**Comment by Karen-Intel** [comment]
Hey @bearshen good news!

A fix for this issue has been released in our latest Beta Driver version [v.4499](https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html). I have verified on my end and I checked it works
Can you please confirm? 

Thank you
Karen

**Comment by bearshen** [comment]
Thank you. I can confirm this working.
