### ISSUE TITLE
About Vulkan Video

### ISSUE THREAD

**Issue by ghost** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#301]

**Comment by Karen-Intel** [comment]
Hey @arm64-v9a thank you for your post!

I am the engineer in charge of following this up so I will carefully review your case and get back here in case I need any extra info.

Stay tuned!

Karen

**Comment by FarisR99** [comment]
I think this is just an error on the naming of the 2 engines in Task Manager. The left is actually Video Encode and the right is Video Decode. This is based on my testing of my Intel iGPU UHD 770 with the following:

`ffmpeg -hwaccel qsv -hwaccel_output_format qsv -i input.mkv -c:v h264_qsv -preset fast -b:v 5M output.mkv`
Both charts show a spike/load

`ffmpeg -i input.mkv -c:v h264_qsv -preset fast -b:v 5M output.mkv`
Only the left chart shows a spike

**Comment by Arturo-Intel** [comment]
Do you think this way of naming the engines are from the ffmpeg tool? or the from Intel drivers?

**Comment by FarisR99** [comment]
The names of the engines are in Windows Task Manager regardless of whether ffmpeg is installed or not so they cannot come from ffmpeg - I assume they come from drivers

My NVIDIA GPU reports `Video Encode` on the left and `Video Decode` on the right in task manager, whereas my Intel iGPU reports `Video Decode` and `Video Decode 1`.

**Comment by Arturo-Intel** [comment]
gotcha!, will work on this

--r2

**Comment by FarisR99** [comment]
>  `ffmpeg.exe -init_hw_device d3d11va:X -hwaccel d3d11va -hwaccel_output_format d3d11 -i video -an -f null -`

Can confirm running 2 instances in parallel causes both decode engines to show spikes, whereas one instance only shows load on one engine
