### ISSUE TITLE
VA-API

### ISSUE THREAD

**Issue by ghost** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#302]
### Application [Required]

FFmpeg, mpv

### Processor / Processor Number [Required]

11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

### Graphic Card [Required]

Intel(R) UHD Graphics

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [x] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [X] Other (Please specify)

### Other Windows build number

25352.1

### Describe the feature [Required]

VA-API currently supports win32, but the only vaapi driver we have available is vaon12, so it does not support HEVC Rext codec and VP9 encoding, will Intel include native VA-API drivers in its Windows drivers in the future?

**Comment by Karen-Intel** [comment]
Hey @arm64-v9a thank you for your suggestion!

I will make sure to share the details with the development team. In case I get any info I will get back here to post any updates

Talk to you soon

Karen

**Comment by Karen-Intel** [comment]
@IGCIT can you help us close this one? It has been submitted as a FR :)

Karen
