### ISSUE TITLE
Edit/Update 23 May 2023 - HDMI options for color format & color depth: Arc Control and IGCC conflicting information (maybe (?) relevant)

### ISSUE THREAD

**Issue by LancerDawg75** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#304]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Graphics Command Center

### Processor / Processor Number [Required]

AMD Ryzen 5800X3D

### Graphic Card [Required]

Intel Arc A770 Limited Edition

### GPU Driver Version [Required]

- [X] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[2 May 2023 SSU.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11365624/2.May.2023.SSU.txt)

### Description and steps to reproduce [Required]

Using an HDTV as a display (Sony Bravia 32-EX300 (Japan model)) via HDMI. However, I do not have any options regarding the ability to change the color format or depth despite using a native HDMI connection which should show up in IGCC. 

I have checked on another PC that I have that uses the Pentium Gold G7400 + Biostar B660 MX-E using the integrated graphics with another smaller (26-inch) but more recent Sony Bravia HDTV. The color format does show up and I was able to change that to Full Range RGB, but the ability to change color depth is stuck to 8-bit. Since I could not change the depth and any information to maybe force the change, I really couldn't find . With that, I ended up purchasing a used Radeon RX550 2048SP GPU and was able to change the color format to HDMI 12-bit Deep Color

Back to the current system that I use regularly:

- I am not using any adapters.

- To test if it is the Arc + IGCC, I performed: 

- DDU in Safe Mode for the Arc Driver
- Removed the A770 
- Swapped it for a Colorful iGame GTX 1080Ti VulcanX OC using Game Ready 531.68. I was able to change the format and color depth to my desired options
- Repeated a Safe Mode DDU driver removal for the Geforce GPU
- Replaced with PowerColor Radeon RX 5700XT Red Devil using Adrenaline 23.4.3. Again, I was able to change the format and color depth
- Both previous cards and the Bravia TV showed that 12-bit was activated on the Bravia OSD
- Performed Safe Mode DDU again, and replaced the Arc A770 back in my system. IGCC still does not show the options 
- Tried three different HDMI 2.1 cables (Infinnet, CableMatters Premium Braided, Hori Official Sony PS5 HDMI 2.1) - no change
- Tried different HDMI ports on the TV - no change 

At this point, I am not entirely sure what else to try. For some reason, Intel graphics solutions in either integrated or discrete form seem to not like or fully recognize both my HDMI 1.4 spec HDTVs. 

### Device / Platform

Not Applicable

**Comment by Arturo-Intel** [comment]
Hello @LancerDawg75 

Thank you for the details on this case, this will help us a lot to find the root cause, 

I will reproduce this in our lab,
Keep you posted
-- r2

**Comment by Vegas7** [comment]
A770 LE uses eDP to HDMI, so it's not native HDMI.

**Comment by LancerDawg75** [comment]
> A770 LE uses eDP to HDMI, so it's not native HDMI.

That’s……not consistent with the documentation.
https://www.intel.com/content/www/us/en/support/articles/000092899/graphics.html

**Comment by nyanmisaka** [comment]
![image](https://user-images.githubusercontent.com/14953024/236512046-2dd59b64-46a6-49dc-a4a0-8f8da33646a3.png)

![image](https://user-images.githubusercontent.com/14953024/236512086-ac10c22a-7f50-42e4-b995-24c71fa1d797.png)

This Realtek RTD2173 eDP to HDMI converter chip is the cause, it is used on A750 and A770 but not on A380. So there's no such issue on A380. The same issue happens on intel NUC11, it uses the same Realtek chip and has no color depth options for HDMI ports.

**Comment by LancerDawg75** [comment]
Ah, I see now. 
Although, even on my integrated Pentium Gold (when I was using it until I swapped it out for a RX550), it did allow for color format, showed color depth, but didn't have options for the change. 

Back to the Arc LE versions, - had I known that, I would have opted for the Predator Bifrost, unless that variant also has the Realtek chip in it as well. 

Now the question becomes - was this the only way to achieve the use of both HDMI and DP (which I think not if all other cards outside of Intel are able to do so) or was this the cheapest way to do so?

**Comment by LancerDawg75** [comment]
[Looks like this is not the only post to bring this issue along except that 10-bit color is only allowed while in HDR, but SDR](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/179)

And the conversation regarding it[ continues forward on the Intel Community on a fairly lengthy discussion](https://community.intel.com/t5/Graphics/INTEL-ARC-A770-16GB-Missing-10Bit-Screen-Configuration-Option/m-p/1482332#M117185) regarding that if the Arc LE GPUs are supposed to be able to support HDMI 2.x, then the options should be there as it seems the hardware is there to support a higher color depth. 

The conversation highlights (if I am understanding this correctly):

- It is linked back to here stating that changing color depth is not possible on Display Port due to it "being hardcoded to work only when HDR is enabled"
- Arun states that changing color depth is only possible when using native HDMI outputs (which this card does have)
- The argument on here is because the Arc LE series uses the Realtek RTD2173 DP to HDMI PCON, that because it's not possible to change color depth in DP, then it stands to reason because it's not a true HDMI IC solution, then you need to accept that you will not be able to change the color depth even when connected to HDMI
- However, going back to that Intel Community post there has been a feature request sent to be able to allow color depth change via DP. So this states that the hardware is indeed there to be able allow color depth change (and possibly color format)
- Andres offers the documentation by Intel stating that the only way to get color format and depth change is to do so by way of using integrated graphics (if ya got it) to make the changes
- Contributor states (with using Wikipedia for the DP 2.0 specifications) that ARC states in its technical specs that it is DP 2.0, and using the Wikipedia media graphic - that color depth should be supported
- Another contributor states that the feature is "promised" for DP 2.0...so that means it could happen or not, but part of the reason is the delay by VESA and the VESA CTS, so...until that happens (?) there is no reason to put a priority on it
- Andres states that it is being investigated, but there is no guarantee of a favorable outcome. The only solution (in the current state) is to contact Intel Customer Support and request a refund

**Comment by LancerDawg75** [comment]
A couple of days ago, I updated to the most recent WHQL driver, and with Arc Control, it now shows display information. 
Looking at the display information, Arc Control shows that despite it being connected via HDMI, AC states that it is Display Port. This might be part of the reason why HDMI options are not there - the PCON (or something else) does not detect it correctly. 

However, if I go to the log files in Intel Graphics Command Center, (Location: C:\ProgramData\Intel\GCC) the GPU has a problem identifying any display info. For example, here is a snippet of the log text files in question - specifically the "DisplayInfo" portion 

```
2023-05-15 07:51:09.0468 DEBUG 	ConfigService. Using AllComponents filter for logging. 
2023-05-15 07:51:09.0468 ERROR 	DisplayInfo. Something went wrong with getting proper adapter type 
2023-05-15 07:51:09.0625 ERROR 	DriverEscapeBuilder. InvokeDriverEscape->D3DKMTEscape failed. Escape Code::207 Error Code: 
```
I'll also attach the full file log file as there are other errors as well that I am not sure if they are related, but to the engineers, it may bring more clarity. 

I may be oversimplifying it, but from what I can gather, Arc and probably even NUCs with Xe Graphics, do not know what they are connecting to - at all. 

I have tried to use a CalDigit Active DP to HDMI adapter because I started experiencing issues with Arc sometimes losing the connection with my SonyTV when the display sleeps. However, it's so sporadic, I doubt it could be replicated reliably. Some days, it doesn't happen at all for a few days, and then another few days, it will make the disconnection sound when the display is put to sleep and then:

- The display will wake up: The resolution is the same, but the scaling has changed. It will overscan the display
- Windows settings in the Display section "monitor" goes from "Sony TV" to "Wired Display" 
- Advanced Display Settings for monitor information changes from "Generic Monitor" to "Digital Flat Display (640x480)"

This can be rectified by simply unplugging the HDMI cable from the Arc and plugging it back in.
However, using the CalDigit adapter has lessened the issue - at least so far, I haven't had the problem again, but it's only been a little over a week. 

That being said....I can't really say if it really is an issue with the RTD2173. I can't test it because I think the CalDigit adapter I have uses a Parade Technologies converter. However, there are DP to HDMI adapters that are based on the RTD2173 such as [ones branded by Delock](https://www.delock.com/produkt/63118/merkmale.html). 

What I think I can possibly test, is to try my adapter to my systems that have different cards (1080ti and RX550), If I plug them into the DP connections to an HDMI input. I'll update with additional commentary later on this week. If someone else or maybe you guys and gals at Intel have an adapter that is based on RTD2173, and then an AMD or Nvidia card with DP connections and see if either NVCP and Adrenaline will still detect it as HDMI instead of DP. 


![arcdisplayinfo](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/705b0a7f-c476-4f87-b544-e2dae347b3d5)
[gcc_svc_log_2023-05-15.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11545023/gcc_svc_log_2023-05-15.txt)
[gcc_svc_log_2023-05-19.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11545273/gcc_svc_log_2023-05-19.txt)
[gcc_svc_log_2023-05-20.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11545279/gcc_svc_log_2023-05-20.txt)
[gcc_svc_log_2023-05-22.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11545284/gcc_svc_log_2023-05-22.txt)
[gcc_svc_log_2023-05-23.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11545298/gcc_svc_log_2023-05-23.txt)

**Comment by BearBale** [comment]
I am a user of Acer PREDATOR BIFROST Intel Arc A770 OC from Taiwan
my english is not good so i use google translate to talk to you

I have 1 intel A770LE graphics card and 2 Acer A770 OC graphics cards
Monitor: Philips 328P6VUBREB

Intel A770LE, the chip used by the HDMI interface is Realtek RTD2173
Acer A7770 OC, the chip used by the HDMI interface is Synopsys VMM7100

Acer A770 OC VMM7100 Image: https://i.ibb.co/gvz3Q1L/iaFx1V.png
(Sorry, I'm using GitHub for the first time, I don't know how to insert pictures in the text)

I use the Club 3D HDMI + Micro USB to DisplayPort 4K120Hz or 8K30Hz M/F Active Adapter (CAC-1335)
Try to convert the HDMI2.1 interface of the above two different A770 graphics cards to DisplayPort, connect to Philips 328P6VUBREB

https://www.club-3d.com/en/detail/2609/hdmi_micro_usb_to_displayport_4k120hz_or_8k30hz_m-f_active_adapter/

intel A770LE: Intel Graphics Command Center shows HDMI output but no color depth option

Acer A770 OC: not working, black screen

I have a friend who has used an intel arc graphics card for a long time (and is also a member of the Jellyfin maintainer)
He said: If it is an intel graphics card, the HDMI interface is provided through PCON, no matter what method is used, the color depth cannot be adjusted

Provide this article for my reference
https://www.intel.com/content/www/us/en/support/articles/000093213/graphics.html

The official intel forum also mentioned this issue, and the official staff "Andres_Intel and Carlos_L_Intel" said that they are still working on this issue

(At that time, it was said that it would take 12 months at the slowest to fix this problem)

https://community.intel.com/t5/Graphics/INTEL-ARC-A770-16GB-Missing-10Bit-Screen-Configuration-Option/td-p/1479225/page/2

But Intel officials want to close the discussion on this issue and the progress of the solution

I'm very worried that Intel will eventually give up on fixing the problem of not being able to choose the color depth

**Comment by LancerDawg75** [comment]
@BearBale 

> "my english is not good so i use google translate to talk to you"

No problem, I live in Japan, and there are times that my Japanese isn't as strong and I often need/use DeepL to get me there.

-------------------------
>"Synopsys VMM7100"

Okay, so the Acer Predator has the same issue as well. That only leaves the ASRock Phantom Gaming A770 OC 8GB that has two HDMI ports. One is connected to a PCON, and supposedly the other HDMI port is a native port. This is making me think that this is a firmware/hardware issue OR this is something that Intel itself never put into consideration or both.

------------------------
> I use the Club 3D HDMI + Micro USB to DisplayPort 4K120Hz or 8K30Hz M/F Active Adapter (CAC-1335)

I'm using the [CalDigit DP 2.0 to HDMI 2.1 active adapter](https://www.amazon.co.jp/-/en/DP20-HDMI21/dp/B0BY3SW376/). The upside is that the issue that I put in my comments before has not happened anymore. Downside of course, no way to change the format and depth. I've been trying to find more info on what IC is used in the adapter, but I have not found anything regarding it. Either way, the more stable display has made the purchase worth it. 

------------------------
> I have a friend who has used an intel arc graphics card for a long time (and is also a member of the Jellyfin maintainer)
He said: If it is an intel graphics card, the HDMI interface is provided through PCON, no matter what method is used, the color depth cannot be adjusted

> Provide this article for my reference
https://www.intel.com/content/www/us/en/support/articles/000093213/graphics.html

Yes, I have read that too, in fact, I think I have linked them in some of my previous follow up commentary that looks like Intel does not want to do anything about it.

What is puzzling - the ability of the hardware is there, it just seems like (with all the resources Intel has), they can't figure out how to get any graphics hardware to properly detect display info (as seen in my Intel Graphics Command Center log) and GPUs (outside of Intel, it seems) have been able to do this for more than a decade now. 

In fact, here is some proof of that. 

When it comes to AMD (using a Radeon RX550 640SP) and using my CalDigit DP to HDMI adapter, it still reports it as DisplayPort. However, I am still able to change color format and color depth - displaying on a 26" Sony Bravia TV

![hdmi adapter rx550 adrenaline](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/6377b2bf-74f4-46f4-b72b-585a524d496b)

![hdmi adapter rx550 windows display](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/e89bf3f8-95a6-4b67-abba-2a2423c4c25f)

On my wife's GTX 1080ti, but with a IIyama ProLite XB2781HSU via HDMI and using the adapter, Nvidia Control Panel properly identifies it as an HDMI connection. However, it is a ProLite monitor so it doesn't have the ability to use 10-bit or 12-bit color

Looking over this conversation from the Intel Communities forum (although this is a about a Tiger Lake NUC, but still - it's Xe):
https://community.intel.com/t5/Graphics/HDMI-Resync-fails-10-bpc-12-bpc-on-NUC11TNKv7-Tiger-Lake-UP3-GT2/m-p/1415726

Given what MUC has provided with technical data sheets, there is no reason why the Realtek RTD2173 can not be capable of being able to change color format and depth. This is definitely on Intel. 

The question is:

-  is a limitation of the firmware itself - if so, then Intel needs to get with Realtek and figure out a way to make a downloadable firmware upgrade to address this because every other GPU on the planet is capable of it
- or a limitation of the Xe architecture - which that is a huge oversight on their part. They can't go into Battlemage and anything going forward with this glaring oversight 

This sets a tone that says to us consumers what we already know. "Corporations are not your friends..." by saying:
 "We are doing it this way because HDMI has licensing and royalty fees where as DisplayPort does not. Deal with it."
https://en.wikipedia.org/wiki/DisplayPort#Comparison_with_HDMI

**Comment by Arturo-Intel** [comment]
@LancerDawg75 Hey, did you try it with the IFWI update? 
If you did, can you share if this new IFWI affects in any way the HDMI color formar/depth? 
--r2

**Comment by LancerDawg75** [comment]
Hey @Arturo-Intel 

Yes, I have tried it with the new firmware update.  It hasn't changed the ability to change color format depth or format. 
Although, I'm using the non-beta version of Intel GCC, so I might hit that up on the MS Store and see if that changes anything.

Interesting FYI though - In Arc Control, it still sees it as DisplayPort, HOWEVER, if I use Intel Graphics Command Center, it does recognize it as HDMI. 

Really, it seems like the only way that I can adjust color format and depth going forward on a non-Intel platform PC is:

- Change over to an Intel CPU with integrated graphics (as KF series would probably also run into this problem due to lack of integrated graphics)
- Add in a low power variant of a Radeon or GeForce card as a secondary card since their hardware and software does allow the ability to change said format and depth. 

I really hope that the engineers really look hard into this and make some drastic changes when Battlemage comes along because GPUs from competing manufacturers has been around for decades. DeepLink and other Intel based features I can understand, [ but limiting this setting and pretty much telling us that we need to go full Intel to have it (ie: you need an Intel iGPU in order to do this) is not really acceptable. ](https://www.intel.com/content/www/us/en/support/articles/000092899/graphics.html)

Another thing of interest, I did post something else regarding the firmware/HDMI update on Post #500 

Given that there is another driver update (that I'm sure also probably has the HDMI/firmware update packaged along with it) I'll try it with the latest to see if that changes anything.  That being said, do you want me to put the update here, or on 500, or both? I can do both if that helps you out more.

**Comment by Arturo-Intel** [comment]
@LancerDawg75 I think we can have the updates on the #500 and close this. At the end, you [need Intel iGPU to change color depth/format](https://www.intel.com/content/www/us/en/support/articles/000092899/graphics.html). I dont like it either, but this is the only way so far. 

Either way, we provided your feedback to our dev teams since the begining of this case and be sure that they are aware about it, so I think is likely that we will see this in the next Intel Arc iteration. 

So if you are agree, we can close this case.
--r2

**Comment by BearBale** [comment]
> @LancerDawg75 I think we can have the updates on the #500 and close this. At the end, you [need Intel iGPU to change color depth/format](https://www.intel.com/content/www/us/en/support/articles/000092899/graphics.html). I dont like it either, but this is the only way so far.
> 
> Either way, we provided your feedback to our dev teams since the begining of this case and be sure that they are aware about it, so I think is likely that we will see this in the next Intel Arc iteration.
> 
> So if you are agree, we can close this case. --r2

WTF?

Is every official member of Intel garbage who can’t work and still get paid?

I have 3 Arc A770 graphics cards, and then I waited for you for a year, and finally asked the user to replace the CPU with an iGPU to solve the color depth problem?

You can buy 3 Arc A770 graphics cards for the price of 1 3090. I believe you said it can't be solved after more than a year?

Why don't NV & AMD have this problem?

**Comment by LancerDawg75** [comment]
@Arturo-Intel and @BearBale 

That really is a hard pill to swallow. 

I'm still working on trying to find a [DeLock DP to HDMI adapter](https://www.delock.com/produkt/63118/merkmale.html) as that does have the same Realtek RTD2173 PCON in it. 

If that adapter works on a Radeon or GeForce card and still allows Adreanlin or NV Control Panel to adjust depth and format it's going to be hard for Tom and Ryan to find an excuse for that (Although, when you hear it from Shrout....you gotta doubt!)

This is squarely on the Intel logic board engineers. 

I know this is not on you or Karen and Joseph. You're front line.....but whoever you report to -- they do need to know that it is inexcusable given that this has been a thing for over a decade

**Comment by LancerDawg75** [comment]
Anyway, here is my post to close....

If we want to continue this further, there is always post #500 as I am updating the status of the HDMI firmware update on my system. (Yay, small sample size...)

I can always reference this post again for relevance to any future issues regarding the schematics, nomenclature/architecture, etc etc. 

I probably should try to find out Realtek's technical support and see what they say about it.

**Comment by BearBale** [comment]
> @LancerDawg75 I think we can have the updates on the #500 and close this. At the end, you [need Intel iGPU to change color depth/format](https://www.intel.com/content/www/us/en/support/articles/000092899/graphics.html). I dont like it either, but this is the only way so far.
> 
> Either way, we provided your feedback to our dev teams since the begining of this case and be sure that they are aware about it, so I think is likely that we will see this in the next Intel Arc iteration.
> 
> So if you are agree, we can close this case. --r2

All your niggas say "intel graphics card is the best it"
All my bitches say "all intel products is trash it"

fuxk you,intel

**Comment by Arturo-Intel** [comment]
Ok... 
anyway here is some info about Arc and color depth: https://www.intel.com/content/www/us/en/support/articles/000092899/graphics.html

and using an native HDMI you can change the color depth like this: 
https://www.intel.com/content/www/us/en/support/articles/000087657/graphics.html

**Comment by LancerDawg75** [comment]
@Arturo-Intel 

.....and that's fine (but not really "fine"). We have already had the article links stating why it can't be changed in Arc cards at least three times already (if not more).

The problem is, information from the Intel forums by people say that the PCON (RTD2173) is capable of being able to have those options due to the schematics.

But let's just say, for the sake of the argument, that it is truly the case that the DisplayPort protocol "translation" treats an HDTV (or monitor with HDMI that has deep color options) like a computer monitor and there isn't a way to change depth and format -- due to the lack of HDMI port not being "native".

Then the obvious solution to send to your bosses is to simply add an IC native HDMI chipset to the next Arc iteration, no? 

Will Intel have to pay royalties to the HDMI consortium? Yes. However, if that was a problem, then nothing in the Intel line would have native HDMI support (ie: Integrated Graphics) because it would be too expensive.

Like I said, I'm not hammering on you. You are not on the team that designed the logic board and card configuration of Alchemist being taped out. However, it is important to some of us as this was something that is literally automatic on AMD or Nvidia and has been since GPUs were sold to us with HDMI or mini-HDMI connections.

It's simply an egregious oversight on their part.
