### ISSUE TITLE
Failed to create DX11 render device

### ISSUE THREAD

**Issue by brainlag** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#308]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Any DirectX App

### Processor / Processor Number [Required]

AMD Ryzen 7 5700X

### Graphic Card [Required]

A750

### GPU Driver Version [Required]

- [ ] 31.0.101.4335
- [X] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11412197/ssu.txt)

### Description and steps to reproduce [Required]

I think this problem occurs more often on multi monitor setups.

Basically it works like this, I start the PC and then start a Game which works. Then on the second monitor I start a video in chrome, twitch or whatever. As long as the game runs there is no problem. But when I close the game and watch some movies for an hour or two then I can't start any Game anymore. Is pretty reproducible, like 8/10 times it does not work. Today I didn't even start a game, just watched a video for 1h then couldn't start any game. 

Maybe different bug but I think it's the root problem, watching videos on both monitors crashes a lot. Both monitors go black for 2-3 sec, then resumes like normal. Also I can reproducible crash the video player on twitch by mouse over some overlay elements. (For clarification, all videos are played within Chrome Browser)

Monitor setup: 

Main monitor: DisplayPort 144Hz (supports VRR)
Second: HDMI 60Hz (no VRR, only has HDMI)

**Comment by Karen-Intel** [comment]
@brainlag hey, thank you for your submission!

Hmm that sounds like something familiar. Allow me a few hours and before EOD I will provide an update for you if I was able to reproduce the issue

Karen

**Comment by AndrewC772** [comment]
I have the same issues as well seems to crash for DX10 and DX11 for me simultaneously and applications like wallpaper engine that rely on the gpu error out the same way. I don't have the video playback issues though with the monitor going black.
CPU: Ryzen 9 3900x 
GPU: A770 LE Driver: 31.0.101.4314
OS: Windows 11 22H2

**Comment by Karen-Intel** [comment]
Hey @AndrewC772  and @brainlag thank you for the details
I'm still testing as I have not been able to reproduce the issue yet. Allow me some time to debug a bit more
BRB soon

Karen

**Comment by 92lucio92** [comment]
Seems similar to my issue: https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/221

Can you check though dxdiag if you are in the same situation as me while you can't run any dx app?

**Comment by AndrewC772** [comment]
> Seems similar to my issue: #221
> 
> Can you check though dxdiag if you are in the same situation as me while you can't run any dx app?

Not sure if its the same my dx diag seems to report it is fine but the dx10 and dx 11 apps will sometimes just crash[
[DxDiag.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11713578/DxDiag.txt)
](url)

**Comment by Karen-Intel** [comment]
Hey @brainlag this issue has been opened for a while but no consistent reproduction on our end. Could you test on latest driver v.4887 and let us know your results?

Ty

Karen

**Comment by Karen-Intel** [comment]
Hey @IGCIT can we close this? Customer has not replied in the last week

Karen
