### ISSUE TITLE
Windows crash on cold boot or resume from sleep

### ISSUE THREAD

**Issue by Jafea7** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#309]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 10 Pro

### Processor / Processor Number [Required]

AMD Ryzen 5 5600X 6-Core Processor

### Graphic Card [Required]

Intel Arc A750 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11441000/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Almost every time I boot the computer I get the following:
Initial state of the system is normally monitor off, computer off, but it doesn't matter if the monitor is on or in sleep state.
 - turn on monitor
 - turn on computer within ~2 seconds
 - get the BIOS logo screen
 - initial Windows load screen, (Newton balls in a circle), that usually 'stutters' in their cycle which indicates that I'm going to get the following
 - screen will go black and I may get the following display or the monitor will go to sleep with no input ![IMG20230505110441](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/73450040/e16a467e-205b-4e57-a25e-fa206d77e5bc)
 - pushing the reset button will always cause the computer to boot normally

With the computer running normally, if it goes into Sleep mode then it will not resume normal display when it wakes, instead I get the following:
![IMG20230509195420](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/73450040/514e8bd7-2e0e-4167-8231-6d8ed551c595)

This has happened despite:
 - multiple driver versions, (4091-4335),
 - change of motherboard, previously MSI B450M Mortar Max, currently ASUS B550M Plus WiFi II,
 - reinstall of the Windows 10 OS,
 - changing monitors, HP Z23i or Dell U2211H,
 - regardless of DP (including any DP port) or HDMI output port,
 - changing cables, HDMI->DVI adapter, DP->DP 1.4 (2 of).

This then requires either resetting the system or power down/up.

The Windows Reliability History shows that Windows stopped working for the following reason:
`The computer has rebooted from a bugcheck.  The bugcheck was: 0x00000116 (0xffff948ff0445010, 0xfffff804802b6540, 0xffffffffc0000001, 0x0000000000000004).`

The display is always ok once the system is running, (and stays running), no other problems in evidence.

### Crash dumps [Required, if applicable]

[050923-11562-01.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11441014/050923-11562-01.zip)

**Comment by Arturo-Intel** [comment]
hi @Jafea7,

:(, it looks to me that you have a problem with your Arc card :/ Just to confirm can you please do a clean reinstall of the latest driver ([DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) in safe mode), meanwhile i will go with the warranty team to ask for guidance on this case.

**Comment by jpovixwm** [comment]
I'm experiencing pretty much the same behavior with my A750 LE and AMD Ryzen 9 5900X.
Before switching to the A750, I also tried an Arc A380 from ASRock which also exhibited this issue. Actually, I went through two separate units of the ASRock A380 because of another (unrelated) issue, and I think that both of them did what is described in this issue, which leads me to believe that this isn't really a problem with @Jafea7's unit.

My specs:
- Mobo: MSI X370 Gaming Pro Carbon
- CPU: AMD Ryzen 9 5900X
- GPU: Intel Arc A750 LE
- PSU: MSI MPG A1000G PCIE5

[Intel System Support Utility report](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11453497/igcit_ssu.txt)

Once Windows boots, it can run stable with no issues as long as I don't let Windows put my monitors to sleep.
For now, I've simply configured "Turn off the display" in Power Plan Settings to "Never" and I disable my monitors via a 3rd party program "DisplayFusion". (I've got two monitors plus a TV and I've created a profile in DisplayFusion where only the TV is active - if I load this profile and turn off the TV, then all of my displays are effectively disabled).

**Comment by jpovixwm** [comment]
Yes, I did use DDU when updating from v4314 to v4335.

**Comment by Jafea7** [comment]
> @jpovixwm Thanks for the info!... Just to be sure, did you use DDU when updating your drivers? so far the issue is being seeing in A380 and A750 i wonder if this also could be reproducible in A770? I will continue to work on this case in the lab.
> 
> Thanks for your patience --r2

I believe this [post](https://www.reddit.com/r/IntelArc/comments/139vwo3/after_nearly_5d_of_use/) on Reddit is reporting similar, bugcheck when resuming from low power state on an A770 LE.
It's what (finally!) prompted me to create an issue report.

Yes, I have tried uninstalling drivers using DDU before installing updates, there was no change.  Also, I do not have Arc Control or the Intel Driver Updater installed, just the graphics driver.

Thing is, at boot it will do it the majority of the time but will never do it if I have to restart, at cold boot only and not 100% of the time.
For example, this morning it booted up fine even though I forgot that the monitor wasn't plugged into the card.

Whereas, resuming from Sleep or having turned the monitor off to go do something else for awhile and then turning it on will cause it happen 100% of the time, (afaicr).

@jpovixwm Interesting info re. DisplayFusion as I also have that and didn't think to try using it to put the monitor to sleep.

**Comment by jpovixwm** [comment]
I only get the cold boot problems if "Turn on fast startup" is enabled in Control Panel -> Power Options -> "Choose what the power buttons do", which is the default for a fresh Windows installation.
If I uncheck this setting, cold boot actually becomes much quicker and the PC doesn't crash. I've done a full shutdown & cold boot cycle several times and it all went well. As soon as I enabled fast startup again, the issues came back.

**Comment by Karen-Intel** [comment]
Hey @Jafea7 we're back with some results

We have a new driver release[ v.4639](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html).
I have done some tests (leaving my PC in idle for periods of 45 minutes > 1 hour and a half > 13 hours) and it has resumed from sleep without any issues, using this driver version.

Could you please give it a go?
We also recommend to use the latest [DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html) version for the upgrade.

If the crashes are still happening please let us know. We will be helping with more tests and research if necessary

Thank you

Karen

**Comment by Jafea7** [comment]
@Karen-Intel
First the good news:
As mentioned by @jpovixwm disabling "Turn on fast startup" appears to have fixed the cold boot problem so far, I've yet to have it happen in the half dozen times or so that I've booted since I disabled it, (before that I would have been guaranteed of at least 4 times out of 6 failing).

The bad news:
I DDU'd the previous version drivers and installed v.4369, did Start->Power->Sleep, waited 10 minutes and then woke the system and got the same screen as my original post along with bugcheck 0x00000116.

Dump file:
[051823-12937-01.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11507177/051823-12937-01.zip)

**Comment by Karen-Intel** [comment]
@Jafea7 yeah we have another issue reporting the same behavior so it is already in progress internally
You might be aware already of our driver cadence but we are sure we will see updates soon.
Please lets keep this post open and thank you for sharing all the evidence and dump files, it helps us a lot.

Talk to you soon!

Karen

**Comment by Jafea7** [comment]
Hi @Karen-Intel , sorry been away for a few days.

DDU'd the previous drivers and installed v.4382:
Start->Power->Sleep ... After approx. 10-15 secs the computer woke up, without any action on my part, with the following screen:

![IMG20230606143310](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/73450040/1701e696-96c6-49e0-9ab2-1fc76ae4f511)

And the resultant bugcheck:
`The computer has rebooted from a bugcheck.  The bugcheck was: 0x00000116 (0xffffcc094c68f010, 0xfffff801809366d0, 0xffffffffc0000001, 0x0000000000000004). A dump was saved in: C:\Windows\Minidump\060623-11390-01.dmp. Report Id: 8e5a9f74-2df5-4dfb-a7ff-6cefd9083efa.`

Dump attached:
[060623-11390-01.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11659973/060623-11390-01.zip)


A side note: v.4382 is now reporting my A750 as using 33-39W when idle, whereas the previous v.4369 was around 7-11W when idle, (no changes to BIOS or Windows Power settings).

**Comment by Karen-Intel** [comment]
Hey @Jafea7 thank you for submitting your latest dump. 

I think I have a solid case now and will add it to my existent report. 
I will let you know in this thread when a fix has been included in a public release (Which may take a while so I appreciate your patience)
Let's keep the post open and thank you so so much for your help

Karen

**Comment by Jafea7** [comment]
Early days but the system seems to wake from sleep without a problem using v4514 drivers atm.

**Comment by Karen-Intel** [comment]
Hey @Jafea7 thank you so much for your confirmation!

Indeed we're getting several improvements with this driver. Would you like to wait a bit more or can we close this bug for the time being? We can reopen in the future if the issue shows up again

Karen

**Comment by Jafea7** [comment]
I think that you can close this bug report at this time, it seems to be running well.

Thank you for the work you've put in.
