### ISSUE TITLE
Shadow of Tomb Raider

### ISSUE THREAD

**Issue by MrDiagnose** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#311]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Shadow of The Tomb Raider Definitive Edition (Epic Games Version)

### Processor / Processor Number [Required]

Ryzen 5 3400g

### Graphic Card [Required]

Intel Arc a750 LE

### GPU Driver Version [Required]

- [ ] 31.0.101.4335
- [X] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11461052/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Shadow of the Tomb Raider: Definitive Edition (epic version) is giving me black screen in the earthquake scene where you have to run I have Intel arc a750 driver 31.0.101.4314 tried running it using amd gpu worked fine so my guess is Intel gpu has issues with it
[Shadow of tomb raider glitch](https://www.youtube.com/watch?v=RxMsZPJ4BdA)

**Comment by BelleNottelling** [comment]
When I played this game awhile ago, I was also able to replicate this exact same behavior with my A770. It happened both with or without RT enabled, XeSS on/off. Changing the visual settings didn't seem to change anything. The only way I was able to get past that part of the game was to boot it up in DX11 mode. Performance was comparatively terrible, but the screen didn't go completely black so it could actually be played.
Even outside of that issue, I know I personally just had issues with the game random crashing.

For the dev's info, this is what that part of the game *should* look like:
https://youtu.be/Tdkws4svu3U?t=149
This part of the game happens after you discover the location the "Mission of San Juan". It takes a decent bit of playtime to get to

**Comment by MrDiagnose** [comment]
a guy on discord said that turning off screen effect in that particular scene fixes the black screen issue but I don't have the game installed currently so can't test it myself

**Comment by Karen-Intel** [comment]
Hey @MrDiagnose no worries we will test this ourselves. We will get back with our findings soon

Karen

**Comment by Karen-Intel** [comment]
Heeeey @MrDiagnose sorry for the delay. It took is a while indeed to get to that part of the game
We were finally able to reproduce the issue and we have also confirmed the screen effect option -off might work as a WA but the best is to report this internally.
Just FYI our driver cadence for fixes to be released can take from 3 up to 6 months, but let's keep this post open please in case we have updates sooner.
Thank you so much for your help and your patience, talk to you soon

Karen

**Comment by Karen-Intel** [comment]
Hey @MrDiagnose the fix for this issue was included in driver version 5590/5592, could you help me confirm on your end please?
On my end I cannot see the issue anymore :)

Karen

**Comment by MrDiagnose** [comment]
thanks it works without glitches now https://www.youtube.com/watch?v=KcRbsIaRt4U
