### ISSUE TITLE
Virtualization not supported driver freeze

### ISSUE THREAD

**Issue by AuracleTech** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#314]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 11

### Processor / Processor Number [Required]

AMD Ryzen 7 2700 Eight-Core Processor, 3200 Mhz, 8 Core(s), 16 Logical Processor(s)

### Graphic Card [Required]

A770

### GPU Driver Version [Required]

- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [X] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[5-15-2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11482613/5-15-2023.txt)

### Description and steps to reproduce [Required]

- Activate SVM (virtualization)
- Boot up windows
- Enable windows feature Windows Sandbox ( Windows Pro exclusive )
- Boot up windows, windows freeze, non responding on main menu
- Disable SVM to fix issue

Side note : Why do you ask for driver version if you also have a checkbox `Device is using the Latest drivers *` it makes no sense.
Also note that I cannot use the latest drivers because it result in the same result of when I activates virtualization, windows freezes on boot and PC is unusable so I am forced to use older drivers

### Device / Platform

Windows 11

**Comment by DoragonHunter** [comment]
Please ensure resizable bar is turned on and CSM is turned off.

**Comment by AuracleTech** [comment]
I do not have re-bar this is why I use an older version of arc drivers
New versions literally doesn't run if you do not have re-bar which makes no sense
Even though it says its not required it is, or else Id use it...
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/40531871/067f99be-895d-4997-91f2-9b8a9ea65cc0)

**Comment by AuracleTech** [comment]
Considering this issue might be solved in the latest driver update I will first open an issue I face with the latest update which prevents me from using it then I'll re-test SVM once there.
