### ISSUE TITLE
Doom eternal

### ISSUE THREAD

**Issue by IGCIT** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#32]
#### Checklist [README]

- [x] Device is not undervolted nor overclocked.
- [x] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [x] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]

---Doom eternal 
#### Processor / Processor Number [Required]
i7-1165G7 

#### GPU Driver Version [Required]
- [x] 27.20.100.9466 (*latest*)
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [x] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [x] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1. Game keeps stuttering constantly having hitches while playing. Even though it can easily run at 50fps on intel xe
2. 
3. 

---
#### Device / Platform [Optional][Recommended]
GPD win 3 intel xe

---
#### Game Settings [Optional][Recommended]

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---

**Comment by leoben2** [comment]
we can't see this behavior. Are there any thermal limits your system is hitting maybe?

**Comment by IGCIT** [comment]
@leoben2 
no limits, the device is fully unlocked and the os is optimized for performance, temps are good (70-80)

it is just some specific places, the game runs great at ~40 fps but in those parts fps drop to 3-4

for ex.
40fps, you rotate the camera and look at a wall, fps drops to 3, you then rotate the camera again and fps are back to 40
there is clearly something that is not working nicely with intel gpu

or another example
https://youtu.be/3O5dPSzmzkw?t=784

look at that thing that rotates in front of you, every time it completes a rotation fps will drop to almost 0 and the game freezes for ~1 second


here it is my save, i m an other point that is affected by a huge fps drop when the monster came out, since latest doom update it now also crashes the game

unfortunately, you cant just import my save, so heres how (not tested)
https://www.reddit.com/r/Doom/comments/j2qk4l/how_to_doom_eternal_import_a_savegame/

[doometesave.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/6242378/doometesave.zip)

let me know if you are not able to import it

i m here
https://youtu.be/3O5dPSzmzkw?t=1907

i cannot kill that monster because of low fps and constant freezes, and as i said, now crashes, if you go back fps are back to normal

sorry, i should have added all this before but i ve been busy

**Comment by IGCIT** [comment]
finally tested the new driver

crash has been fixed, yet you cannot progress further in the game due to fps being too low (1-2)

requoting my previous message:

`i m here
https://youtu.be/3O5dPSzmzkw?t=1907

i cannot kill that monster because of low fps and constant freezes`

**Comment by Valkirie** [comment]
@leoben2 latest drivers 27.20.100.9466 is still having huge hiccups in framerate.

**Comment by iAmGhost** [comment]
I'm using same device and I found that Microsoft Store version of Doom Eternal with 27.20.100.9313 driver is much playable. There's still some hiccups but less frequent, recovers faster, no permanent freeze.

However Steam version of Doom Eternal will crash while launching with 9313 driver. Crashing fixed on 9466/9616 but it's unplayable because of freezing.

**Comment by Valkirie** [comment]
> I'm using same device and I found that Microsoft Store version of Doom Eternal with 27.20.100.9313 driver is much playable. There's still some hiccups but less frequent, recovers faster, no permanent freeze.
> 
> However Steam version of Doom Eternal will crash while launching with 9313 driver. Crashing fixed on 9466/9616 but it's unplayable because of freezing.

Thanks that's a very useful comment.

**Comment by iAmGhost** [comment]
Here's footage from Huaban, who is suffering same issue:
https://youtu.be/xA_bmzkjjwc

**Comment by iAmGhost** [comment]
It looks like this issue is mentioned from [Known issues in Release Notes of new beta driver](https://downloadmirror.intel.com/30522/eng/ReleaseNotes_100.9667%20BETA.pdf)

**Comment by iAmGhost** [comment]
[Changelog of 30.0.100.9805](https://downloadmirror.intel.com/646152/releasenotes_100.9805.pdf) says this is fixed but still happening for me.

**Comment by halljames** [comment]
Still happening on the latest Beta Drivers 30.0.100.9862

Device : Onexplayer
Settings: Low
i7-1165G7
Windows 10 21H1 (May 2021 Update)

Game initially runs fine, but after a few seconds of moving around, game starts to stutter severely, and eventually crash
https://youtu.be/18nmIlEtHfk

**Comment by Velocity535** [comment]
> 
> 
> Still happening on the latest Beta Drivers 30.0.100.9862
> 
> Device : Onexplayer
> Settings: Low
> i7-1165G7
> Windows 10 21H1 (May 2021 Update)
> 
> Game initially runs fine, but after a few seconds of moving around, game starts to stutter severely, and eventually crash
> https://youtu.be/18nmIlEtHfk

I'm having the same issue.
GPD Win 3 1165G7
Doom Eternal Game Pass, Low Settings
Win 10 21H1, Intel 9862 Drivers (Happened on older drivers too, albeit a even a little worse)

Get about 20FPS for maybe 4 seconds, then it lags uncontrollably.

**Comment by dmdelacy** [comment]
Is this only failing on a GPD device? Is the screen rotated? and do you use an app that creates a seperate displayable buffer to log framerates and things like that?

**Comment by A-w-x** [comment]
yes, GPD devices, like most gaming UMPCs, if not all, have rotated screens

**Comment by PacoAvelar** [comment]
I just tested with a GPD win 3 on windows 11 driver.
I dont I dont see any stutter like the mentioned above (even at 95-98C ) 

https://youtu.be/s_AhzMrZkL0

however, there are some glitches

**Comment by dmdelacy** [comment]
Are you using a tool to measure fps?  Can you disable that? Seems possible that the overlay from that or from Steam might be contributing to the stutter  I dont have a GPD3 so am going to try it on a similar system

**Comment by PacoAvelar** [comment]
> Are you using a tool to measure fps? Can you disable that? Seems possible that the overlay from that or from Steam might be contributing to the stutter I dont have a GPD3 so am going to try it on a similar system


I just disabled, rebooted to kill all overlay processes, launched the game and the same "freezes" happen

**Comment by estebanr863** [comment]
Hi all,

The new driver version 30.0.101.1069 can now be downloaded at https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html.

This driver includes the possible fix for the performance issue reported. Please help us test it and let us know.

**Comment by IGCIT** [comment]
i'm finally able to progress further in the game, it is no longer running at 2fps on my device
a few drops still remain, but lowest is 28 now

i'll keep this open for 1-2 days and i'll play the game some more tomorrow.
if no new issues are found, this will be closed :)
