### ISSUE TITLE
Capture feature not working under latest driver v31.0.101.4369 and Arc Control v1.68.4938.6

### ISSUE THREAD

**Issue by BigNish7** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#322]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control v1.68.4938.6

### Processor / Processor Number [Required]

Intel Core i9 13900KS

### Graphic Card [Required]

Intel Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

22621.1702

### Intel System Support Utility report

[System Support Log - Sunday, 21 May 2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11539245/System.Support.Log.-.Sunday.21.May.2023.txt)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/382e812d-947d-4479-b752-92586f710476)

### Description and steps to reproduce [Required]

I noticed that the Capture feature in the Studio section of Arc Control was not working after I did a Clean Installation upgrade from the BETA version  31.0.101.4335 (I did not instal Arc Control only the driver) to the latest WHQL v31.0.101.4369. 

While I have installed and upgraded every new driver (both WHQL and BETA versions) it's the first time I have installed Arc Control since driver version 31.0.101.4146.

The Capture feature worked successfully for earlier drivers and versions of Arc Control. I therefore conducted an investigation by installing a series of WHQL Arc drivers and their bundled Arc Control versions on my PC. For each test, I removed the driver/Arc Control using DDU and when installing each new version I did a 'Clean Install' and did the suggested reboot. Once rebooted, I tested whether the Capture feature worked.

My test results were:
Driver 31.0.101.4091: Arc Control: 1.64.4583.3: Capture working = YES
Driver 31.0.101.4146: Arc Control: 1.64.4584.4: Capture working = YES
Driver 31.0.101.4255: Arc Control: 1.66.4728.1: Capture working = YES
Driver 31.0.101.4314: Arc Control: 1.66.4728.1: Capture working = YES
Driver 31.0.101.4369: Arc Control: 1.68.4938.6: Capture working = NO

The error I received was the gool 'ol "Could not start Capture. Device operation failure. Make sure your're not connected to a VPN. Error code: -17

In all of the tests of Capture under the multiple driver and Arc Control versions I did not change my system hardware, and I don't have a VPN installed.

**Comment by Karen-Intel** [comment]
Hey @BigNish7 I was able to perform a quick test on my A750 and I was able to record in 4K resolution for a few minutes with ARC Control v. 1.68.4938.6
Question: Which DDU version did you use?  [This is the one we recommend](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html)
My system is pretty similar to yours, only that I have a A750 instead of an A770 and my board is a ROG STRIX Z690-A Gaming Wifi D4 but I have not had any issues. 
We can keep on testing and see if we are able to repro or wait for another user that can consistently reproduce it :) I will get back on the lab and test on a A770 and see if we have any luck there

Talk to you soon

Karen

**Comment by Karen-Intel** [comment]
Hey @BigNish7 a few more questions:
- HW Details on your Display Setup? Are you using HDMI only? DP only? Does it happen with single, multimonitor? What is your display's resolution? Have you tested going lower/higher resolution and then attempt recording?
- Are you testing with the default settings? Did you modify anything?
- What is the IFWI of your A770?  Go to Gear > System Info > IFWI version

Just trying to find a specific combination and continue attempting reproducing :)

Thanks, talk to you soon

Karen

**Comment by BigNish7** [comment]
Hi @Karen-Intel. I think I have found the issue, but before I get to what I found, here are the answers to your questions.

- My display is an ASUS TUF Gaming VG28UQL1A. It is a 4k 144Hz panel. I upgraded the firmware to V030. I am connected to my panel via a single DisplayPort cable via one of the A770's DP OUT ports and the panel's single DP2.1 IN port. In addition to the DP cable, I also run a USB cable from the back panel of my PC to the USB Hub on my panel - this allowed me to upgrade the panel's firmware and also use the panel's speakers if I don't want to use my headphones. I only have a single monitor. My display's resolution is 4k and I have it set (in Win 11) to run at 144Hz on the desktop. I tried getting Capture to run at 144Hz/120Hz/60Hz but it had no effect.
- I am testing with the default settings. I have not modified anything.
- The IFWI of my A770 is 20.1053.3

Now to what I found! Given your question re using the default settings, I started playing around with the Capture settings. First, I tried to change the Resolution settings from the default 720p to 1080p/1440p/2160p, but these had no effect.

However, I then looked at the Audio Device options. The default is Headphones (Realtek USB Audio). I changed this from the dropdown list of options to 'Disabled' and to my surprise and pleasure Capture worked as expected! I then tried all the options in the dropdown list and got the following:

Audio Device: Disabled -> Capture working = **YES**
Audio Device: VGA28UQL1A (HD Audio Driver for Display Audio) -> Capture Working = **YES** 
Audio Device: System Default -> Capture working = **NO**
Audio Device: Headphones (Realtek USB Audio) -> Capture working = **NO**
Audio Device: Realtek Digital Output (Realtek USB Audio) -> Capture working = **NO**

It seems, for my PC at least, that there is an issue between the Realtek audio driver and Arc Control v1.68,4938.6 which did not exist in earlier Arc Control versions. Given your MB is a ROG STRIX Z690-A Gaming, what version of Reatlek audio do you have installed? Perhaps the issue is with the fact that I am also connecting my PC to my panel with a USB cable?

Looking at Device Manager I found the following:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/011ba036-e990-4ddf-a1f8-8d9567b446a2)

I have 2 x HD Audio Driver for Display Audio installed. This is audio driver that comes bundled with the GPU driver.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/f0072ef5-1186-47a6-8c25-2e91a6763488)

I have 1 x Realtek USB Audio driver. I have driver version 6.3.9600.2342 installed.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/68e9241e-4f52-4957-a4b3-b2a5d2ff2513)

This was a really interesting result and I trust helps get to the root cause of my issue.

**Comment by Karen-Intel** [comment]
Hey @BigNish7 thank you for the wholesome testing you just performed.

Re 1: You see two HD Audio Devices for Display audio as one is the primary and the other is some sort of a sub function.
If you check on the details you will see they are pointing to the same system32 files, which means their functionality is related.
Also, if you plug in another monitor that is audio capable (monitor or connector) you will see another device with the same name. So I don't think the USB cable plugged to the monitor has anything to do with it.

Re 2: Now about the Realtek Audio, I think I have a very old one, as I don't use it too much (10.0.22621.1) and I'm thinking there might be an issue with this Realtek driver. The best would be to go to the ODM's page and download the recommended version. If there's still an issue, Realtek can easily get in touch with us (Intel) to investigate why it isn't working with ARC Control latest version, but it must be reported in the Realtek forum. 
Perhaps it has to do with the Default audio device not working, I really can't tell.

Re 3. I did some more testing just to confirm if there was an issue with the Realtek drivers and it worked as expected. 
Even without having the device plugged in, you can hear audio and see that ARC Control is able to capture in my Samsung Odyssey 4k Monitor) I'm leaving 4 attempts I did with the devices I have available and all of them record audio and capture is working fine. [Sorry for the quality, I'm trying not to load the Google Drive much.
](https://drive.google.com/drive/folders/1A2qeSYcEv0HQpBCfkY46SKLGH-h6v1zO)

Hope this helps! If there's anything I can do let me know.

Karen

**Comment by BigNish7** [comment]
Hi @Karen-Intel. I fixed the issue. I completely uninstalled the Realtek USB Audio driver and associated software (i.e. Sonic Studio III). I reinstalled the driver (6.3.9600.2342 which is the latest on the ASUS support page for my MB). I am happy to report that Capture now works perfectly. 

Interestingly opening the Advanced Tab of Sonic Studio 3 that loads along with the driver shows a reference to Arc Control. I am not familiar with what Intel Arc Control Assist might be, but it certainly caught my eye. I am assuming it is the ability to use the effects that Sonic Studio III can give if you are using the Intel Arc audio driver? 

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/fdadfb36-6d33-40f1-a196-adf466ac8476)

Thank you for all your assistance in supporting me with this issue - I really appreciated it.

**Comment by BigNish7** [comment]
Hi @Karen-Intel . Ok, spoke too soon unfortunately. I played around with the Inteal Arc sttiings in Sonic Studio III and Capture stopped working :-(. I then removed Sonic Sudio III and the other bloatware like Sonic Radar that came with the Realtek driver, and looking at Device Manager, I see that I have just the Realtek USB 2,0 driver v10.0.22621.1. I think this is what your system has. 

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/c6dc3397-6f3a-4fe7-a613-39fd67984962)


I am happy to say that now Capture works perfectly again as expected. It seems that, for me at least, the latest version of Arc Control does not play nicely with Somic Studio III and/or the other Realtek stuff that comes bundled with the driver. I think now I am good to go and we can close this issue.


https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/67a91013-e12d-43df-ba0e-49b52c7d4a9b

**Comment by Karen-Intel** [comment]
@BigNish7 hey GM

Yeei I'm glad capture through ARC Control works as expected for you! 
It's a shame that some tools do not have full compatibility with ARC yet but integration takes a while. 
Thank you so much for your help, have a wonderful weekend

Hey @IGCIT can you help close this one please? Realtek audio driver was causing issues with ARC Control Capture but after an update it works now.

Thanks

Karen

**Comment by BigNish7** [comment]
Just for clarity, the 'upgrade' to solve this issue was actually the removal of some drivers and applications that came bundled with the Realtek driver v6.3.9600.2342. 

It was found that Sonic Studio III v3.16.23.0 was preventing the Capture feature of Intel Arc Control. Sonic Studio III had captured Intel Arc Control somehow. 

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/f8e49d49-13e2-4076-9cf7-cc864ab84442)

If any adjustment was made e.g. switching DEVICE ROUTING from OFF to ON and/or SONIC STUDIO EFFECTS from OFF to ON, the CAPTURE feature of Arc Control stopped working if any Realtek related Audio Device was selected. 

Capture did work as expected if Audio Device was set to either 'Disabled' or 'VG28UQLiA (HD Audio for Display Audio).

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/5eb54b41-675b-4b84-8652-7f082f5e30ce)

To get Capture working again across the whole range of Audio Device options, required the following:
1. Removal of the Realtek USB Audio program from the installed Apps

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/1622d145-52ab-42eb-bf52-940a26d4eb3a)

2. Uninstalling both the Realtek USB Audio and Sonic Studio Virtual Mixer from Device Manager

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/1bf198b4-be7e-4901-b8a7-20578ed3c49a)
