### ISSUE TITLE
Artifacts when forcing x16 anisotropic filtering in hunt showdown

### ISSUE THREAD

**Issue by Azonnali** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#323]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Hunt: Showdown

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5600

### Graphic Card [Required]

A770 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SysReport.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11568112/SysReport.txt)

### Description and steps to reproduce [Required]

Just set the anisotropic filtering to x16 in the intel arc control center and launch the game.
![Screenshot (22)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/37149444/9a96d116-f89e-48b0-a5fc-f183f7ac03d1)
![Screenshot (23)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/37149444/707b4a81-512e-43c0-be8a-6e3e473d5cd4)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Resolution: 2560x1440
Window Mode: Fullscreen Window
Render Resolution Scale: 85
Gamma: 1.0
VRAM Usage Target: 80
Global Graphics Quality: Custom
Object Quality: High
Texture Quality: High
Texture Filtering: 16x
Anti Aliasing: SMAA 2TX
Lighting Quality: High
Shadow Quality: High
Effect Quality: High
Post-Process Quality: High
Particle Quality: High
Performance Stats: Warning Icons Only
VSync: Off
Max FPS: 60
Depth of Field: on
Motion Blur: off
Surface Format Optimization: Off
Toggle GPU Tesselation: off
Use 2 Pass Rendering: on 
Use 2 Pass Lighting; on

**Comment by Karen-Intel** [comment]
Hey @Azonnali thank you for your submission!

I will check this strange behavior on my end and get back here in case I have/need information

Stay tuned!

Karen

**Comment by Pashamolochko** [comment]
greetings, the same problem exists in many online games, when you forcibly change the anisotropic filtering in the driver to x16 or x2, in warface it generally causes a smoke bug, it becomes with some stripes

**Comment by Karen-Intel** [comment]
@Azonnali Hey

Just a quick update, I was able to repro the same behavior you spotted with the latest beta driver
I will make sure to report it internally asap. Just FYI our driver cadence can be from ~3 to 6 months but we may have fixes way sooner so, let's keep this post open in case we have any updates.

@Pashamolochko ty for your report. If you could open a new thread that would be great, as we need to create a report per gane, thanks

Karen

**Comment by BuyMyMojo** [comment]
artifacts can appear in certain games when forcing it on but the option is still way more useful for more games that don't feature the option than the few games that have artifacts.

leaving it up to the user like Nvidia and AMD does is a much nicer solution as it allows for more in-depth customisation, if you want less user reports you could have it display a popup like changing GPU voltage

**Comment by BuyMyMojo** [comment]
> Hi everyone,
> 
> We removed the Anisotropic filtering option in ARC Control so the option is now controlled exclusively through the each game's GRAPHICS MENU Section.
> 
> Please file a new bug if any issue occurs when activation Anisotropic Filtering within the game.
> 
> I'm closing this bug now.

what do we do in the case of games not having the option?

Games such as Palworld, The Finals, Cult of the Lamb, Cities: Skylines II, Persona 5 Royal, Warhammer 40,000: Darktide and even Armored Core VI: Fires of Rubicon
