### ISSUE TITLE
new features in intel arc control

### ISSUE THREAD

**Issue by Pashamolochko** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#325]
### Application [Required]

Intel arc controi

### Processor / Processor Number [Required]

i5 12400

### Graphic Card [Required]

intel arc a380

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

greetings, I would like to see in intel arc control the functions of detailed configuration of global gaming parameters, like competitors amd and NVIDIA, and at the moment there are very few settings, a new point of adaptive intel tessellation has recently been noticed, which is already good, but it would be nice if there were sets, for example, with a given quality-balance-performance, as well as, many users are waiting for fps limits using the intel arc control driver, and it would also not be bad to implement a function to reduce delays in games like similar Nvidia Reflex functions, thanks in advance for the feedback, all the best)

**Comment by Arturo-Intel** [comment]
@Pashamolochko thank you for your feedback,

Rest assure we will share this feature request to our dev team 
if we have any news about it, we will posted here :) 
--r2

**Comment by Karen-Intel** [comment]
Hey @IGCIT can you help us close this one? Idea has been submitted on our end

Karen
