### ISSUE TITLE
Super Robot Wars 30: Crashes to desktop when using the "Mission" radio button and MSAA corruption

### ISSUE THREAD

**Issue by LancerDawg75** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#328]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Super Robot Wars 30

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3D

### Graphic Card [Required]

Intel Arc A770 Limited Edition

### GPU Driver Version [Required]

- [X] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11599150/igcit_ssu.txt)

### Description and steps to reproduce [Required]

When running the game, it starts up as normal, but going through the menus, if I use "Move" it pauses for a bit, but goes to the map. However, if I select "Mission" from the game menu, it immediately crashes to desktop. Tried to use DXVK to see if that would remedy the issue, but it does not help with MSAA issue or the crashing to desktop. 

Trying to find the configuration file to see if I can reset the MSAA as I can't see the rest of the settings or any of the menus to be able to revert back to MSAA off

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Resolution: 1080p - Borderless 
MSAA Off but with any MSAA applied leads to screen corruption
Detail: Max Settings
Vsync: On
Frame Rate: 60fps

![MSAAx4 corruption](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/47959f42-55e5-4d1c-8328-3c2d1102b27d)
![MSAA corruption](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/9443e7df-a771-4ba5-a07c-fac7e2d783ff)

### Crash dumps [Required, if applicable]
[Event Viewer SRW30.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11600005/Event.Viewer.SRW30.txt)

_No response_

**Comment by Arturo-Intel** [comment]
Hi @LancerDawg75 

We will replicate this in the lab and if we need more info will come back to you!

Keep you posted, 
--r2

**Comment by LancerDawg75** [comment]
Update: 18 July 2023 - tried beta driver 4575. Issue still persists although a slight change. This time, selecting "move" gets you to the map, but the minute you select a destination, it will just hang - it may or may not crash to desktop. Selecting "MIssion" will send you to a black screen. Again, it will hang, but compared to the previous driver version, the application will just hang and stay there - it does not crash immediately like before. 

I haven't tried using MSAA. I'm sure the same issue will crop up. Using MSAA in this game seems to be something that only GTX/RTX cards can use because I remember back when I had an AMD GPU, the game worked, but if you had any MSAA engaged, it would break the battle animation into a sort of garbled diagonal split screen.

**Comment by LancerDawg75** [comment]
Update 3 August 2023 - tried it one more time with 4577 - also added DXVK gpl-async. 

Interestingly, I tried to start a new game with SRW30. It will go through all the motions of the storyline and allow me to play the actual RTS portion of battle and plays the battle animations without issue. The only issue just seems to be when you need to use either the move or missions portion of the menu. 

There is something about SRW30's map that causes Arc to freeze for awhile and then crash to desktop. It just takes longer to crash to desktop if I use Vulkan as opposed to DX11.

**Comment by Joseph-Intel** [comment]
Hi @LancerDawg75 I was able to recently test V.4644 and i haven't been able to see the crashing issue. Would you be able to confirm on your end and lets us know? If you are would you be able to either send a video of the steps or tell me each step to reproduce the crash issue?

Thanks!

I DO see the corruption when turning on MSAA.

**Comment by LancerDawg75** [comment]
@Joseph-Intel 

Hey, thanks for getting back to me. Apologies for not updating as I go along. I try to be prompt with that as I like to think that when I do put updates/testing on my posts that maybe I'm being of help to you guys. 

I did try it recently with v4644, and I'm still getting the same issue with it crashing to desktop once I either use Move or Mission

Move - does work until you select a mission. Once you press it on a mission, it freezes, and the Windows "I'm thinkin' about it" circle comes up and then, eventually crashes. 

Mission - instantly freezes

I am going to try some different tests here to see if it is my Windows installation that is causing it. 

I have already tried resetting my BIOS to defaults to see if it maybe was related to my PBO settings (setting it lower for efficiency and better temps + Curve Optimizer of -25) or because of one setting in DRAM that I had to manually adjust to the advertised parameters of my memory kit - No Joy

Although one interesting aspect of my testing, I tried installing a Radeon RX 550 2048SP card in the secondary PCI-E slot of my system and pointed the game towards that card. It did the same thing. 

With that said, I tried to play the game on a fresh start. In either card, it works. It plays through perfectly. It's just when I get to the map to either do "Move" or "Mission" it crashes.  This leads me to believe that there was an update or just the Windows install overall that is doing this. What sucks is - this is the only game it does it on and throws out the exception error in Event Viewer.

I'm going to try a DISM Restore Health routine to see if that helps it. 
If not, I'm going to try and uninstall Steam, and move the installation out of the protected area of Program Files (x86) to see if that changes anything. 

If that doesn't change anything, then I might have to reinstall Windows 11 completely. (Yay) and hope that helps it.

As far as MSAA goes...it's an issue on Radeon as well, but not in the same way. MSAA will corrupt the battle animation on Radeon. Play it on a GeForce card - it runs perfectly no matter what the MSAA setting.

**Comment by Joseph-Intel** [comment]
@LancerDawg75  I will add this to my notes. I will also do some more testing on my side and let you know my results.

**Comment by LancerDawg75** [comment]
Update: 30 Aug 2023 

- DISM Restore Health routine didn't change the end outcome
- Moving the Steam installation to a different location didn't change the outcome

At this point, I have to try doing a complete reinstall of Windows

**Comment by Joseph-Intel** [comment]
Hi @LancerDawg75 I was able to do more testing and I am still unable to produce the crashing issue [https://youtu.be/-KIZdBlZGDU](url) I added a video to ensure i was following your steps properly. Were you able to reproduce the issue? I recommend doing DDU before a whole system reinstall.

**Comment by LancerDawg75** [comment]
I finally got around to reinstalling Windows 11. Apologies. It took me awhile, because I had bought a SATA SSD to boot off of WIndows (Crucial MX500 1TB) and when I was going through the motions, it just died mid installation. Had to wait for a new one to come down from Amazon, and yesterday, I finally get to try it out.

At the base installation with 4672, and then at least installing my chipset drivers for my system. Move and Mission worked. I'm slowly installing things one by one and trying to play the game as I go to see if something I installed triggers the exception error. The last thing I feel I have to try is Sophos Home Premium. I don't think it's the issue because it has run before with my AV installed, but that was with my previous 1080ti....

It may have just been my previous install had issues....but I'll keep you updated.

**Comment by LancerDawg75** [comment]
Update: 9 Sep 2023: Installed my AV, and it is still working. I can get past Move and Mission. 

At this point, I think I really don't have any other plausible explanation other than there was something in the previous install that wouldn't allow SRW30 to execute move or mission without throwing an exception error.  

If this is okay with you, @Joseph-Intel .....I'll close the ticket. I can't think of anything else other than to chalk it up to a corrupted/damaged install that just seemed to only affect SRW30.

**Comment by Joseph-Intel** [comment]
@LancerDawg75 Please let us know if something else comes up! We will be here to help. 

@IGCIT Would you be able to help out and close the ticket? The customer wants to close and will reopen if they have any other concerns.
