### ISSUE TITLE
Yakuza: Like A Dragon - inconsistent/poor performance (DirectX 11)

### ISSUE THREAD

**Issue by LancerDawg75** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#329]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Yakuza: Like A Dragon

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3D

### Graphic Card [Required]

Intel Arc A770 Limited Edition

### GPU Driver Version [Required]

- [X] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11609393/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Game starts normally. Performance is all over the place with framerates. Worst offending location is walking towards Hamakita Park where frames can drop into the mid to high teens. Generally the framerates will be around high 20's-low/mid 50's with the occasional 60fps target that I have with V-Sync enabled in game.

When you enter into battle, the frame rates are between high 30's to 60fps

I will post another comment trying to see if DXVK GPL-ASYNC will clear it up. 

Game Settings Details will be posted in the form of screenshots
I'll post telemetry in the form of a screenshot and CapFrameX in DX11 first. 
The next comment I make will post them while running DXVK

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![Graphics 1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/ca49f6b8-c954-4d51-af5a-cdcf90e3f9b2)
![Graphics 2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/1f77e8b5-1d7c-47ef-9fda-2e41eb45f3fa)
![LAD DX11](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/ccd5ed03-363e-4107-b57f-7bc668138172)
![CF-X LAD Hamakita Park](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/b30b7990-fd42-4f25-a957-d58e30528e74)
![CFX LAD Battle](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/cdf33e38-b82d-477a-bc59-27bc6f219e35)
![LAD DX11 Around Buldings](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/acd0456f-793c-4f8f-ae1a-3e4bddc088e0)

### Crash dumps [Required, if applicable]

Not Applicable

**Comment by LancerDawg75** [comment]
Update: 1 May 2023

Inserted DXVK GPL-ASYNC 2.1 into the root folder to where LAD is located. Using that clears up the frame rate and pacing issues.
Attached
- Screenshot with the telemetry on
- Cap Frame X FPS and frametime analysis
- DXVK D311 and dxgi logs (Probably not relevant)

![LAD DXVK GPL ASYNC 21](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/fd07821f-9268-4c4b-93cc-88393ac06e41)
![LAD CFX DXVK FPS](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/b0f0e8c6-3f2a-4e10-b684-fe33ac57675a)
![LAD CFX DXVK FT](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/b75430ec-ce7e-412b-9fe9-a110abcc46e5)

[YakuzaLikeADragon_d3d11.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11616903/YakuzaLikeADragon_d3d11.log)

[YakuzaLikeADragon_dxgi.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11616904/YakuzaLikeADragon_dxgi.log)

**Comment by Karen-Intel** [comment]
Hey @LancerDawg75 thank you for your report

We were actually testing this ourselves and already in process of reporting the performance changes using dxvk
This is a WA that has been applied in some games and in previous cases we have closed the post (which you can reopen if needed)

@IGCIT can you help us close this post? Game performance improved by adding dxvk WA

Thank you!

Karen

**Comment by LancerDawg75** [comment]
@Karen-Intel Thanks for the reply. I thought of doing the DXVK testing myself because I felt, "Man, you guys have got enough tasks already"

I'll also edit the header to show that DXVK is the current solution/workaround until the time comes around (hopefully) that we won't need other users to do so.
