### ISSUE TITLE
Monster Jam Steel Titans 2 glitches on grass

### ISSUE THREAD

**Issue by IBJamon** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#33]
#### Game _[Required]_
Monster Jam Steel Titans 2 https://store.steampowered.com/app/1205480/Monster_Jam_Steel_Titans_2/

---
#### CPU _[Required]_
i5-1035G7, m3 7Y30 (I tested it on both)
(a.k.a. GPD Win Max, and GPD Win 2)

---
#### GPU Driver Version _[Required]_
9136 (latest)

---
#### Rendering API _[Required]_
Unknown; it uses Unreal Engine 4

---
#### Windows Build Number _[Required]_
Windows 10 20H2 

---
#### Description _[Required]_
While playing the game, grass flickers with black triangles quite often.  Screenshot attached.

---
#### Steps To Reproduce _[Required]_
Play the game; it's pretty obvious

---
#### Screenshots _[Optional]_
![20210305110724_1](https://user-images.githubusercontent.com/4131880/110162921-fa308080-7db4-11eb-8e51-6882819ccf25.jpg)

---

**Comment by leoben2** [comment]
This is under debug now.

**Comment by estebanr863** [comment]
Hi @IBJamon,

The fix for this issue was included in driver version 30.0.100.9955. Can you please test this with the [latest drivers](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html)?

**Comment by IBJamon** [comment]
I believe it's fixed now.  Thanks!
