### ISSUE TITLE
Visual artifacts in Teardown

### ISSUE THREAD

**Issue by BelleNottelling** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#332]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Teardown

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11630502/igcit_ssu.zip)

### Description and steps to reproduce [Required]

Easiest way to replicate this is to open the game, break something, and then quickly pan the camera when facing whatever you just broke. (a tree in this example)
Here's a screenshot I captured of it:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17304943/f7281380-6bd3-4d88-b85d-959fe79fe47e)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Fullscreen mode, 2560x1440 resolution with the resolution scaling set to 100%
Quality set to "high" which is the highest-in-game preset.
V-sync set to "adaptive" as recommended by the game. (Anything else tends to have horrific frame-pacing, which seems to be an issue with the game engine)

**Comment by BelleNottelling** [comment]
Some more observations:

Water doesn't seem to be aligned correctly, causing visible lines on the surface:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17304943/e596a7a0-9325-4cc2-ab99-5939c0d8e957)

The issue I originally reported appears to be specific to the camera angle, map, and what's visible on screen. To reproduce it easiest, I suggest loading up the "marina" map in sandbox (you need to first go to `options` -> `game` -> and then click `Unlock all levels` under the "Sandbox" settings. This will allow you to load any map without first unlocking it in the campaign. Then knock down a tree, face towards the water / horizon and start turning the camera. Should make it pretty quick and easy to reproduce the green ghosting that trails behind objects.

Additionally, some in-game lights flicker a bit, but not in a way that looks intentional. The quickest and easiest way I have found to reproduce this is to load up the "Evertides" map and then head out the front of the mall to the parking lot. There is a sign at the back of it that has the odd lighting (most visible in the day). You can also use the "change weather" option from the pause menu to change it to night.

Example in the day: https://www.youtube.com/watch?v=3oaOlCcHFoY
Example at night: https://www.youtube.com/watch?v=TxrKbISacRI
(Note: both were tested at 1440p. The Day one was just only captured in 1080p)

You can see that the bricks and the billboard both seem to be somewhat flickering / fluctuating in brightness. It's possible that this is intentional, but it looks quite odd and not having an Nvidia GPU to compare to I can only assume this is a bug. It's also noteworthy that it seems to be fairly dependent on the angle you are facing these objects.

**Comment by Karen-Intel** [comment]
Hey @BelleNottelling thank you for the evidences you shared. I could see the evidences
Question, have you tried including the DXVK package in the game? 
We have detected it as a potential [WA ] for games in DX11 (https://www.reddit.com/r/pcgaming/comments/mlfcsc/a_guide_to_dxvk_on_windows/)so, just wondering if you could try and see if there's any effect in the green artifacts

Thanks please let me know

Karen

**Comment by Karen-Intel** [comment]
Thanks. FYI I have been able to reproduce in the latest drivers so I will make sure to report the issue asap

Our driver cadence for fixes takes ~ 3-6 months to have a fix released but in case we have updates I will post them here

Keep you posted!

Karen

**Comment by BelleNottelling** [comment]
Super.
Thanks, Karen 😄

**Comment by Karen-Intel** [comment]
@Arturo-Intel can you help us close this one? 
Issue is not present with latest driver v/5084 and game's latest patch puiblished on December 19th :)

Karen

**Comment by BelleNottelling** [comment]
Yeah, this issue was open long enough the game got a new DX12 renderer that's enabled by default so I'm not surprised to hear it works better
