### ISSUE TITLE
Printscreen captures are behind what's actually on screen

### ISSUE THREAD

**Issue by BelleNottelling** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#334]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Any / printscreen

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11641894/igcit_ssu.zip)

### Description and steps to reproduce [Required]

This one is.. odd.
Whenver I use the "print-screen" button to capture what's on my screen, the capture always frequently appears to be multiple seconds behind what's actually on-screen, sometimes as much as 30 seconds to a full minute. 

So if I try to take a screenshot of something, I get whatever *would have* been on my screen roughly 30 seconds ago.
It's quite confusing and pretty annoying when I am trying to grab a quick screenshot of something to share it with friends - I often end up sitting there hitting the print-screen button repeatedly in the hopes that it captures something up to date.

Here's a video I capture where I am loading up into a game, performing some actions, using the print-screen button, and then pasting the capture into paint. Sorry about the momentary black screens when I alt-tab. The switch was instant for me so I guess OBS takes a moment to catch up. Hopefully it's still good enough to make out what's happening:
https://www.youtube.com/watch?v=oMvPWiA7aME

I took a printscreen 3 different times:
 - Once after I stopped the car for the first time. When I pasted that one into Paint, it was a capture of the Teardown pause menu I was on before driving the car.
 - Then again after pasting the first capture as I wanted to see if that one would be caught up or not, and it was.
 - And then one final time at the end of the clip when I hit the breaks in the truck & the capture was from a few seconds before I stopped. 

From what I have seen, It feels like the longer it's been since the last capture, the further behind it is.

I know for certain I have seen it with OGL, DX12, and Vulkan games. I'm pretty sure I have also experienced this problem when trying to make captures of the desktop, although I can't recall a specific situation where I had that issue at the moment so that might be made up and in my head.

**Comment by Karen-Intel** [comment]
Hey @BelleNottelling thank you for your submission

Allow us to do some testing and get back to you in case we can repro :)

Stay tuned!

Karen

**Comment by BelleNottelling** [comment]
> Hey @BelleNottelling thank you for your submission
> 
> Allow us to do some testing and get back to you in case we can repro :)
> 
> Stay tuned!
> 
> Karen

Thanks!

**Comment by Karen-Intel** [comment]
Hey @BelleNottelling a few on my findings.

I don't have Snipping tool automatically mapped to PRT SC but I attempted a screenshot by pressing Windows logo + Shift + S
I do see a delay, you can see it here.
However, by attempting a screenshot with I have a 3rd party app (Lightshot) active whenever I press PRT SC, it takes screenshots at the exact timestamp.
I will be reporting this behavior internally as I was able to also reproduce in a system with NVIDIA GPU and I don't see it there.
(BTW I have an update I will post in the Teardown thread you will see in a sec)

Let's keep this post open please, thank you!

Karen

**Comment by BelleNottelling** [comment]
Key, @Karen-Intel 
I appreciate the testing, but snipping tool and print screen are at the moment separate in functionality. (For now, as they have changed the **default** behavior in [KB5025310](https://www.windowslatest.com/2023/04/09/windows-11-kb5025310-changes-how-the-print-screen-key-works/))
In fact, I have in the past needed to specifically use print screen because of the [open issue](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/197) that effects snipping tool & causes it to stop working. In my experience, when snipping tool fails to even launch print screen still can be used to capture a screen shot and I have many time used that workaround, pasted the captured screenshot into paint, cropped it down to what I needed, and then copied and pasted that into whatever I was working on.

I tried googling to see if anyone else has complained about this issue and I didn't find anything. I also asked 3 different people if they have even once seen print screen capture previous data and they said they hadn't. On top of that I don't at all recall it being an issue when I had my 10 series NVIDIA GPU.

I can report the issue on the MS forums, but I'd certainly appreciate if you could verify it on your end by actually testing print screen rather than snipping tool.

Thank you

**Comment by Karen-Intel** [comment]
Hey @BelleNottelling okay, I will test on both my machines using PRT SC and post my results  as soon as I can

Karen

**Comment by BelleNottelling** [comment]
Thank you, @Karen-Intel!
I appreciate it

**Comment by BelleNottelling** [comment]
Something else I would like to point out is that even with the test you performed, the difference in delay between the A770 and RTX 3060 is MASSIVE.

## A770
Snipping tool appears at [47 seconds into the video](https://youtu.be/a2Xz9qQPQvY). The image that it captured actually appears to be from before the game even started to be recorded, as even if you slow the video down to 0.25 playback speed, the logo that snipping tool captured was more rotated than when it first appeared in the recording. (Just under two seconds into the video)

### Snipping tool
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17304943/6b34d4bb-5d33-4045-891b-0b8bfd2924fc)

### First frame the logo was recorded
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17304943/f45e9de2-1672-49ac-af97-bb181e88deee)

It's important to note that the logo that appears when you start Teardown rotates counter-clockwise until is it level and then it morphs to become their final logo. This means the capture performed with the A770 was a bit more than 45 seconds behind what was actually on-screen.

## RTX 3060
This one was a bit harder to time, but I downloaded it and used Davinci Resolve so I'd get a little bit more fine-tuned control with it. In the clip with the RTX 3060, snipping tool appears at 9.15 seconds.

### Snipping tool
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17304943/84233d1c-86bb-492d-a99d-1c63b97312c2)

### Matching timestamp for the snip
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17304943/5bae8588-238e-4ae1-b6e7-f6bb82219b59)

This one is likely a bit less accurate, but it's pretty close to the frame that snipping tool captured. It appeared 4.16 seconds.

So that means for the RTX 3060, the capture you made with snipping tool was roughly 5 seconds behind what was actually on-screen. Compared to the A770 which was roughly 45 seconds behind.

That means the A770 capture was **9 times** as delayed as the one you captured on the RTX 3060.
Now I will admit, it is possible these results were thrown off because of the game loading, but that matches the behavior I have seen repeatedly across multiple games regardless of how long they have been open and loaded in.

Something else to note is that in the case that a delay is indeed normal behavior when capturing content on screen, 5 seconds is small enough that people are much less likely to actually notice it and even if they did, it's small enough they would likely forget about it, which I think is backed up by the fact that now 0 out of 4 people (another responded) I have asked have never noticed it capturing data that was previously on screen. 45 seconds on the other hand is a **significant** delay and something that would be pretty much impossible for someone to not notice.

So even in a situation where the capture is displaying previous frames and that is the expected behavior, the A770 is 9 times as delayed as the NVIDIA card. I would absolutely consider that a bug myself.

**Comment by Karen-Intel** [comment]
Hey @BelleNottelling I managed to get some results for you

Systems we tested on:
-13900k + A750 + v4382 = Printscreen key having a delay on Open GL Games. Verified on Teardown and Ty the Tasmanian Tiger
-12900k + A770+ v4382 = Printscreen key having a delay on Open GL Games. Verified on Teardown
- Nvidia RTX 3060 + latest driver + Printscreen = Printscreen key having a delay on OpenGL games. Verified on Teardown
and Ty the Tasmanian Tiger. 

About this:
> 
> That means the A770 capture was **9 times** as delayed as the one you captured on the RTX 3060. Now I will admit, it is possible these results were thrown off because of the game loading, but that matches the behavior I have seen repeatedly across multiple games regardless of how long they have been open and loaded in.
> 

It was actually the time the game started to load and when I moved to the other screen + the time the snipping tool took to open + the time I took to press WIN + SHIFT + Me and my sloppy fingers. In the latest tests we performed the screen captures took place when the game had already loaded and wee had spotted this before in the 3 systems I highlighted above.  

For a real performance matching we would have to measure both systems in similar conditions at almost the exact time + consider the time it takes for NVIDIA and INTEL to make OpenGL Calls + the time it takes for the OS to create and save the screenshot, etc.

Summarizing
1. The issue is a sort of lag in OpenGL + Printscreen/Snipping tool 
2. NVIDIA and Intel are showing similar behaviors
3. The issue points out to be related more to MS than to the GFX drivers (NVIDIA and Intel)

Again, I'd recommend to make the report in MS forums too. 
They're the ones that can help us identify if this is an issue related to the GFX drivers or if it is a behavior they're already aware of. We've also looked for other reports (internally and externally) without any luck so if you could help us report it, would be great. Thanks

Karen

**Comment by BelleNottelling** [comment]
Hello. @Karen-Intel 
I think you have misunderstood me.

> It was actually the time the game started to load and when I moved to the other screen + the time the snipping tool took to open + the time I took to press WIN + SHIFT + Me and my sloppy fingers. In the latest tests we performed the screen captures took place when the game had already loaded and wee had spotted this before in the 3 systems I highlighted above.

I was not timing how long it took for the print screen to appear on screen. I do not care about that. The issue is that the the frame that was captured is **old**. In the case of the A770 test, the frame that was captured when you tested it was **forty five seconds** behind behind what was actually on screen. It captured one of if not the very first frame of the game that was the very **start** of the Tuxedo Labs logo.

I have experienced that very same issue in DirectX12, OpenGL, and Vulkan games *repeatedly* for the couple of months that I have owned the A770 and I have **never once** noticed such a problem in **years** that I daily drive a GTX 1070 TI. Even if I did, it was so minor that I instantly forgot. I personally noticed this issue literally the very same day I installed my A770 months ago and I can recall the exact situation even today.

If you are comparing how far into the past the captured frame is between the Intel and NVIDIA cards are and I am completely misunderstanding what you meant by with that reply then I sincerely apologize for my frustrated response, but right now it does not feel like you are actually understanding the problem I am experiencing.

Furthermore, I'd like to reiterate that with the A770 the captured frame seems to be more caught up with what's actually on screen if you are doing back-to-back usage of the print screen button rather than just random one-off captures so please take that into consideration when performing tests.

> Again, I'd recommend to make the report in MS forums too.

Please point me in the direction of the correct forum to post to.
Is it the ones hosted at https://answers.microsoft.com?

Thank you.

**Comment by Karen-Intel** [comment]
Hey @BelleNottelling no worries

Just to be clear, we do understand the issue, but we need more info to investigate it further, that's all, specially because we're seeing similar behaviors on both NVIDIA and Intel.
Adding the different programming APIs adds a bit more of complexity to the case. We'd need to find out what happens with OpenGL and DX (with all its flavors) the calls that are happening while the game is being played + the OS (where the buffer comes in place that stores the set of frames as target for the SS) + the hardware and its drivers.

**And the reason why I'm pointing to the OS is because other 3rd party tools (Lightshot, Steam screen capture) work fine and have no issues in NVIDIA or Intel, meaning no delays at all.**

The forum I am referring to is the[ MS tech community forums ](https://techcommunity.microsoft.com/t5/forums/searchpage/)
and I just checked and anything related to screenshots, snipping tool or printscreen is kinda old and they have nothing related to SS on games yet. 

Would be good to start the thread because we do need their feedback too. 

Thank you

Karen

**Comment by BelleNottelling** [comment]
Hi, @Karen-Intel 
Sorry for the delay response, I've been caught up in some other things.

Truthfully, I have first hand experienced the kind of support that Microsoft gives to their *enterprise* **partners** (not even customers, contractually agreed upon partners) and frankly even what they called their premium support was absolutely abysmal and was often a massive waste of time.

Maybe their forum will be different, but I'm not patient enough to find out and want absolutely nothing to do with MS support.
Take care.
