### ISSUE TITLE
Wrong Arc GPU Power consumption in both Arc control and GPU-Z

### ISSUE THREAD

**Issue by MichaelWang666** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#335]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Idle 

### Processor / Processor Number [Required]

i7 13700k

### Graphic Card [Required]

770LE

### GPU Driver Version [Required]

- [X] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

swich the integrated graphic to A770 LE,  the GPU Core power consumption jump to 4000W +.  Besides when use HDMI port connect to LG G2 TV run at 4k@120Hz.  the idle power consumption never goes below 45w. 

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/104514573/ca556db3-8704-4650-b718-8f7cc24a04ed)

### Description and steps to reproduce [Required]

Just switch the graphic from integrated one to A770 LE

**Comment by Karen-Intel** [comment]
Hey @MichaelWang666 that is a very strange behavior

It may be most likely a telemetry issue but just to discard, please help me with the following:

1. To discard any issue with the card, just check that everything is well plugged and I'd even test with another power cable from the power supply to the mobo (just a suggestion)
2. Have you tried performing a driver update with DDU? If not please do, you can also remove ARC Control manually from Programs and files and re attempt a driver reinstall
3. If issue persists, please perform a regression to driver v.4255 and share your numbers.
4. Can you please share your numbers too but for the IGPU? 

Looking at my pc this is what I am seeing and I was making some changes in my build this morning. (Motion sometimes messes things up, however everything looks normal)
I have a 4K monitor @144 Hz and another one HD @60Hz plugged

![ARC Control - Power Consumption](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/315fa169-ba43-4ede-9a1f-69734c8826b6)

Hoping to hear from you soon

Karen

**Comment by nyanmisaka** [comment]
Fixed in GPU-Z 2.54.0.

> With this release, we've added the ability to monitor and log the real-time video memory read/write bandwidth usage for Intel Arc GPUs. Power monitoring for Intel Arc GPUs was broken after a recent driver update, this is fixed now.

https://www.techpowerup.com/310336/techpowerup-gpu-z-2-54-0-released

**Comment by Joseph-Intel** [comment]
hi @nyanmisaka I was able to test out with arc control version 1.73.5335.2 bundled with graphics driver V.4826. I am seeing that both GPU Z and arc control showing the same information. Would you be able to test this out and let us know your results?

**Comment by nyanmisaka** [comment]
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/9e8ab18b-eb3e-45ef-8b05-c2bbe413e96c)

**Comment by freak2fast4u** [comment]
As of today (latest GPU-Z and latest Arc drivers), power usage is reported the same for my A770LE : 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/754cd389-2a98-4378-9d13-576f9d599172)

**Comment by Joseph-Intel** [comment]
@freak2fast4u  Hi, Then would you say this issue has been resolved? Or is there anything else I would be able to help you with?

**Comment by freak2fast4u** [comment]
@Joseph-Intel : there's something specific about op's configuration which I can't relate to : monitoring GPU power consumption when switching from an Intel iGPU to Intel Arc. I have a Ryzen 7800X3D and can't replicate his specific situation (Arc Control doesn't monitor Ryzen IGFX chip AFAICT). @MichaelWang666 : is this still a problem for you ?

**Comment by Joseph-Intel** [comment]
@IGCIT Can we close this one out?
