### ISSUE TITLE
Crysis Remastered glitch when looking at the sky

### ISSUE THREAD

**Issue by IBJamon** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#34]
#### Game _[Required]_
Crysis Remastered

---
#### CPU _[Required]_
i5 1035G7 (GPD Win Max)

---
#### GPU Driver Version _[Required]_
9316, but this bug has existed for a while

---
#### Rendering API _[Required]_
I believe DX11, but unverified

---
#### Windows Build Number _[Required]_
Windows 10 20H2

---
#### Description _[Required]_
When looking up at a sunlit sky, the sky textures will repeat in a grid-like pattern.

---
#### Steps To Reproduce _[Required]_
Start the game; you can even see it while diving from a new game.

---
#### Screenshots _[Optional]_
![20210305_141135](https://user-images.githubusercontent.com/4131880/110169213-00772a80-7dbe-11eb-8b0a-a5c2dc9d4741.jpg)
I had to take this from my camera, since I disable fullscreen optimization and it's not on Steam

---

**Comment by leoben2** [comment]
We reproduced this, not sure when we can get to this one though as a few other games are in front of this in the debug queue.

**Comment by estebanr863** [comment]
Hi @IBJamon,

This issue was reported internally and is now on our driver development team’s queue. However, just to set the right expectations, given the current load on the dev team, this fix could take between 3 to 6 months to be included in a driver release.

**Comment by EstebanIntel** [comment]
Hi @IBJamon, 

after a long debugging process, this issue was root caused to a bug on the game side. We escalated the issue to the game developer, but been this an old game, no resources are available on their side to work on fixing this bug. So unfortunately, this will not get fixed.
