### ISSUE TITLE
Hardware Accelerated content stutters when viewed on multiple screens at once

### ISSUE THREAD

**Issue by GottaSlay** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#342]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Microsoft Edge

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3d

### Graphic Card [Required]

Acer Intel Arc A770 Predator BiFrost OC

### GPU Driver Version [Required]

- [X] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11741508/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Play two instances of YouTube videos on two different screens and they will both begin to freeze and stutter.
Pausing one video will then make the other one play smoothly.
The same freezing and stuttering also occurs when browsing hardware accelerated content whilst watching a video.
Current Microsoft Edge version: 114.0.1823.43

**Comment by GottaSlay** [comment]
One of them is using HDMI yes.

**Comment by GottaSlay** [comment]
It used to begin right when the videos started and both were non-fullscreened.

I have just cleared my cache and restarted the browser and now videos no longer stutter when played on both monitors. I didn't get to try out whether the problem occured on other browsers as well but now Edge seems to work after clearing cache.

I'll keep an eye out in case the problem reoccurs. Thank you!

**Comment by Arturo-Intel** [comment]
Glad to help, 
QQ tho, in what vids where you able to reproduce the issue?  4K, 8K? or just random videos?

--r2

**Comment by GottaSlay** [comment]
Videos mainly 1080P and higher. I was thinking it was a problem with Hardware Acceleration since the stuttering also seemed to happen if I scrolled through hardware accelerated content whilst watching a video on the side.

**Comment by martin-ngyn** [comment]
I also have this issue. I haven't cleared my browser cache yet in case you still want data from me.

ASRock Intel Arc A750
Driver 31.0.101.4369
AMD Ryzen 5 3600
32GB RAM
Google Chrome Version 114.0.5735.134 (Official Build) (64-bit)

Both monitors are 1440p. Main one playing games is 144hz, the side monitor is 75hz.

When I play Genshin Impact on my main monitor, when playing a stream maximised on the side monitor, the stream lags. 

I find streams when the graphics card is doing more work. For example, playing Genshin Impact on as maximum graphics as possible, with a full screen stream. When I play something less intensive (Honkai Star Rail) and/or the stream is not fully maximised, then the stream doesn't lag.

Here are my Genshin settings. I find I can lag when I view a Reddit video (using Reddit player). I also lag whenever I watch a stream from https://gaki-no-tsukai.stream/peertube in full screen.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/8bd2cdac-3cad-4af2-a9ce-5d4f6932c12d)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/adae3463-ee0d-4e58-8b8a-55a70d2d4e01)

**Comment by Arturo-Intel** [comment]
@martin-ngyn, @GottaSlay  Ok, It seems to be a pattern here, and it looks like the VRAM is getting full, hence the stuttering/lag in the video.
I reproduce this yesterday playing Diablo 4 and having in the other monitor a youtube video playlist, but i was using firefox. 
Cleaning my cache fixes the issue (until it gets full again, I guess).

I think we have a solid case here, I will start sharing this info to our internal teams, I will keep you posted here
-- r2

**Comment by GottaSlay** [comment]
Confirming I've also been re-experiencing the stuttering after a while of clearing cache.

**Comment by Karen-Intel** [comment]
Hi guys have you tested with the latest driver version? Please let us know if there's any improvement

TY

Karen

**Comment by GottaSlay** [comment]
I've been using .4644 since it was released and for a couple days I no longer experienced stuttering but now it has come back again. 

For an example I was just watching Twitch on the second monitor and YouTube on the main monitor and both of the playbacks kept freezing and stuttering. Once I switched tabs to Github on one of the monitors. The other one continued playing the video smoothly again.

**Comment by GottaSlay** [comment]
Hey. I've been using .4669 for a few days now and haven't experienced any stuttering yet. Still keeping an eye on things but seems good so far!

**Comment by Arturo-Intel** [comment]
@GottaSlay did you try it with the latest beta? ([101.4826](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html?))

Also, remeber to use [DDU in safemode](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) when updating the driver.

Please let us know if any changes
-- r2

**Comment by GottaSlay** [comment]
I see .4885 has just come out. I will DDU my drivers in safemode and report back after a couple days of usage.

**Comment by GottaSlay** [comment]
@Arturo-Intel I've DDU'd my drivers in safemode and installed the driver version .4885 and am still running into the stuttering issue.

**Comment by Karen-Intel** [comment]
Hey all, just leaving here an internal tracking number for this issue: 14020322444
Issue is still a WIP in our end, we will provide an update as soon as we get it :)

Karen

**Comment by Squall-Leonhart** [comment]
Theres no need for intel to investigate this, its a behavior of the Windows compositor when presenting contents to multiple displays with mismatched refresh rates,  the content on the faster monitor will stutter as the slower display reduces presentation rates under the current compositor design where all screens are drawn as a single surface.

**Comment by GottaSlay** [comment]
Hey! Any updates regarding the issue? Issue still happens on driver .5330 and Microsoft Edge version 121.0.2277.128

**Comment by Karen-Intel** [comment]
Hey @GottaSlay we have not had many updates about this issue. 
Please send me a video of the evidence with the latest driver and I will make sure to verify on our end and create a new report. 
Ty for the heads up

Thanks

Karen

**Comment by GottaSlay** [comment]
Thanks for the quick response! I will soon get back to you with a video once the issue reproduces itself. I just restarted my computer and that seems to make things work properly for a while. However the problem always comes back after a while and remains very persistent when it does.

Anyhow I will post a video soon when the problem reoccurs. :)
