### ISSUE TITLE
Can't use the IGCIT Driver Switch Helper

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#346]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

IGCIT Driver Switch

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 19.06.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11785975/Intel.SSU.19.06.2023.txt)

### Description and steps to reproduce [Required]

Put the drivers .exe files in the Drivers folder of IGCIT -> It'll say that no drivers have been found, because drivers should be in a .zip format, although the Arc drivers are in a .exe format

### Device / Platform

ASUS Prime Z790 WiFi D4

**Comment by IGCIT** [comment]
hi, was so busy with other things that i didn't notice zip format was removed, i will check what changed

**Comment by TheWonderfulTartiflette** [comment]
> could you ask for the .zip download to be offered again. It was a good solution to avoid installing ISDA just to get a new version of Arc Control. Perhaps has long as the selection isn't addressed in the .exe installer.

I don't think you need DSA to install new Arc drivers, you can have them either from Arc Control or directly from [Intel's website](https://www.intel.fr/content/www/fr/fr/download/729157/intel-arc-iris-xe-graphics-beta-windows.html?)

**Comment by Vipitis** [comment]
my issue is that you can only install arc control via the driver installer. And you can chose to not install arc control and IDSA. But you cannot chose to install Arc Control but not IDSA. Meaning there is no way to install/update Arc Control ever since the 42xx drivers introduced the compressed installer and we no longer have the .zip

**Comment by IGCIT** [comment]
> could you ask for the .zip download to be offered again. It was a good solution to avoid installing ISDA just to get a new version of Arc Control. Perhaps has long as the selection isn't addressed in the .exe installer.

extract the exe with 7z
you can uncheck ISDA when installing iirc, just select custom install

**Comment by Vipitis** [comment]
you can uncheck IDSA, yes. But that also unchecks Arc Control. You can do driver, driver +IDSA, driver +IDSA + Arc Control. You cannot do driver +Arc Control or just Arc Control.

**Comment by IGCIT** [comment]
> you can uncheck IDSA, yes. But that also unchecks Arc Control. You can do driver, driver +IDSA, driver +IDSA + Arc Control. You cannot do driver +Arc Control or just Arc Control.

i see, you can open a feature request about this here
