### ISSUE TITLE
Gigapixel AI Is Unusable & Unstable with Intel Arc

### ISSUE THREAD

**Issue by BelleNottelling** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#349]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Topaz Labs Gigapixel AI

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11802952/igcit_ssu.zip)

## Description
Simply launching and doing nothing with Gigapixel AI will cause the application itself to gradually drop from ~100FPS to single digit framerates until it eventually just outright crashes. It usually takes ~5-10min and is short enough that users with slow internet speeds likely can't even download the AI models.

During this time, Windows also becomes sluggish and laggy. This has been an issue for the entirety of the time I have owned the A770 despite the fact that Gigapixel AI came bundled with the GPU. In that time, I have upgraded my computer and performed a clean install of Windows, but the issue still persists.

Here's a (rather long despite speeding it up) gif showing the frame-rate decreasing by just leaving the application open:
![Animation](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17304943/f1cecba1-37cb-4c4c-9dda-e615ea43232d)

## Reproduction steps
1. Open up Topaz Labs Gigapixel AI
2. Wait

**Comment by Karen-Intel** [comment]
Hey @BelleNottelling thank you for reporting this

I was able to confirm the same behavior on my 13900k system + A750 + GFX v.4502
I know we have some issues reported already with Gigapixel AI but will add the details of this behavior you found.

Please keep this post open, I will get back as soon as I have news on the fix in a public release.

Have a great weekend

Karen

**Comment by BelleNottelling** [comment]
Thanks, @Karen-Intel 
I hope you also have a great weekend!

**Comment by rmorera-intel** [comment]
Hi @BelleNottelling can you please retest this issue with our latest driver [32.0.101.6078](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) 

Best Regards,
Ronald M.

**Comment by BelleNottelling** [comment]
@rmorera-intel I sold my arc GPU over a year ago so I can't

**Comment by rmorera-intel** [comment]
I'm sorry to hear that, hopefully you can give us a shot with our Battlemage lineup. 
Our debug team confirmed they no longer see the issue so I'll close this bug report.
