### ISSUE TITLE
WRC 9 crash (regression)

### ISSUE THREAD

**Issue by IBJamon** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#35]
#### Game _[Required]_
WRC 9 FIA World Rally Championship

---
#### CPU _[Required]_
i5-1035G7 (GPD Win Max)

---
#### GPU Driver Version _[Required]_
9316 (crashes on older ones I tested also)

---
#### Rendering API _[Required]_
DirectX 11 and 12 both crash
**API** _[DirectX, OpenGL, Vulkan]_:
**API Version** _(example DirectX 12)_:

---
#### Windows Build Number _[Required]_
Windows 10 20H2 (19042.867)

---
#### Description _[Required]_
WRC 9 will crash either when about to load the main menu, or if it gets past that, when starting a race.  Rarely, it'll get past those two and just crash later.

---
#### Steps To Reproduce _[Required]_
Start the game.  If you get that far, try to start a race.  I have noticed that if I change drivers that boot, it's more likely to work, but if I boot up with that driver it is most likely to crash.

---
#### Game graphics settings (screenshot or text) _[Optional]_ _[Recommended]_
I've tried a variety of settings (when I had it working), and usually went with all Low without any luck.

---
#### Screenshots _[Optional]_

---
#### Save game _(if possible, could help solve the issue faster)_ _[Optional]_

---
#### Game custom logs (if available) _[Optional]_ _[Recommended]_

I'm going to try to add a game crash zip to this issue; I am updating this ticket on another PC.

---
#### Additional notes _[Optional]_

On my GPD Win Max (i5 1035-G7) I find that WRC 9 will crash when it gets to the main menu.  Sometimes it can get to a race before crashing, but it rarely survives.  This is on the 9136 driver.  If I downgrade to the 9168 driver, it works well and I haven't experienced a crash (at least not right away).

**Comment by hididi31** [comment]
WRC 9 working Fine on 1160g7. But there is some glitch. For exemple lightning and lightning bolt

**Comment by IBJamon** [comment]
Yeah, it's strange, because it doesn't crash for me on my older GPD Win 2 (m3-7Y30).

Also, after I posted this bug, I noticed that it does crash on other driver versions; it seems to work okay for the first race after a driver change, but it'll crash any second time loadings.

I also notice that it crashes when there is the chance for a black screen.  So, in between levels, or when starting up for the first time - any time there is loading, if it takes more than a second or so, it's guaranteed to crash.

**Comment by IBJamon** [comment]
Attached is a crash dump from the game.  Since it actually shows it's the driver crashing, I suspect this will be helpful.

[0c51fd60-d783-4369-9d86-50104bc46ab9.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/6243344/0c51fd60-d783-4369-9d86-50104bc46ab9.zip)

**Comment by Valkirie** [comment]
Hey @leoben2, just a quick ping as this one was reported two weeks ago.

**Comment by IBJamon** [comment]
This seems MASSIVELY improved with the 9466 driver.  I'm still trying to reproduce the issue, and so far so good.

**Comment by IBJamon** [comment]
I believe the issue can be closed.  I'll keep testing the game since the crash was so repeatable with new drivers, but I think we're good here finally!
