### ISSUE TITLE
Bad performance in Halo: The Master Chief Collection

### ISSUE THREAD

**Issue by BelleNottelling** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#350]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Halo: The Master Chief Collection

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11803851/igcit_ssu.zip)

### Description and steps to reproduce [Required]

Looks like Halo: MCC is yet another DX11 title that needs a fair bit of driver TLC.
So far I have only played Halo: Reach specifically, however all of the games in the MCC use DX11 and I believe they share the same game engine so the issue should apply across the board.

The FPS is frequently quite bad. To get the game to be even remotely playable, I need to use the "performance" quality preset. Sometimes it will be running at 144fps and is smooth, but it also very often suffers frame-rate drops down to ~20 FPS, they seem to hit mostly when facing a large, open space, but I've even seen it while inside of buildings.

Despite the FPS drops, neither the CPU or GPU are under any kind of heavy utilization so it appears to just be a bottleneck in the drivers slowing things down.

I haven't tried DXVK in this game as it uses anti-cheat. You can launch the game without anti-cheat, but it then completely disables achievements (according to the PC gaming wiki), so I also wouldn't consider that to be an unacceptable workaround for the FPS problems. 

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

The "performance" preset with no other settings changed.

**Comment by Arturo-Intel** [comment]
@BelleNottelling Yes, another one to the list. DX11 are not performing well on the actual state of the drivers, but rest assure this problem is well know and is work in progress by our dev drivers teams. 
I cant give you an exactly ETA of when the fix will arrive, it depends on a lot of things that are outside my control.
What I can do is share you news of this mater thought this thread. 

Thank you for sharing this and your patience.
-- r2

**Comment by BelleNottelling** [comment]
> @BelleNottelling Yes, another one to the list. DX11 are not performing well on the actual state of the drivers, but rest assure this problem is well know and is work in progress by our dev drivers teams. I cant give you an exactly ETA of when the fix will arrive, it depends on a lot of things that are outside my control. What I can do is share you news of this mater thought this thread.
> 
> Thank you for sharing this and your patience. -- r2

Thank you

**Comment by chopstix2594** [comment]
Performance is still poor on driver 4826, but I decided to give DXVK (2.3) a try and it runs flawlessly. (And indeed, launching the game with EAC enabled won't work with DXVK installed)

**Comment by Karen-Intel** [comment]
Hi all, just leaving here our internal number for tracking purposes: 16021489943
Issue is still a WIP in our end, we will provide updates as soon as we get them

Karen

**Comment by Pleune** [comment]
Just to link here, #575 mentions that driver 4952 fixes performance for the steam version. I can personally confirm that this is true of driver 4953 and the steam version of MCC.
