### ISSUE TITLE
New text that hasn't been translated in French in Arc Control

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#352]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 21.06.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11808110/Intel.SSU.21.06.2023.txt)

### Description and steps to reproduce [Required]

Go to the Settings -> App preferences -> Notifications in the French Arc Control 

### Device / Platform

ASUS Prime P Z790 WiFi D4

**Comment by TheWonderfulTartiflette** [comment]
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/240f43ff-fdad-43da-804d-1f053a9c4835)

**Comment by Karen-Intel** [comment]
Heey @TheWonderfulTartiflette thank you for your report

I am reporting this to the team in charge and once I have an update I will let you know in this thread so, let's keep it open

Talk to you soon!

Karen

**Comment by Vivek-Intel** [comment]
Hi @TheWonderfulTartiflette 

Can you please help verify issue with latest Arc control panel on Latest Intel Arc Display driver - 101.4676

We verified and it seems to be working as expected.
![Frech Localisation with latest arc control works fine](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/114637913/31eff179-b9bc-4cfb-badd-17e2fe8e55ad)
