### ISSUE TITLE
No value in the "Xe-Core" section in Arc Control

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#353]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 21.06.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11808116/Intel.SSU.21.06.2023.txt)

### Description and steps to reproduce [Required]

Go to the Settings -> System info -> Hardware -> Xe-Cores : No value will appear. Closing Arc Control and reopening it, and using the standalone version instead of the overlay doesn't do anything

**Comment by Karen-Intel** [comment]
Hey @TheWonderfulTartiflette thank you for reporting this :)

I have just confirmed the same info you're seeing. 
I will find out why it is showing like that = filing a bug and doing some regressions.

I will let you know when we have a target fix for this but in the meantime let's not close this bug. Thank you for your help!]

Karen

**Comment by TheWonderfulTartiflette** [comment]
> Hey @TheWonderfulTartiflette thank you for reporting this :)
> 
> I have just confirmed the same info you're seeing. I will find out why it is showing like that = filing a bug and doing some regressions.
> 
> I will let you know when we have a target fix for this but in the meantime let's not close this bug. Thank you for your help!]
> 
> Karen

In 4576, there is a value now for the Xe-Core, but it's 512 which is completely wrong

**Comment by Karen-Intel** [comment]
> > Hey @TheWonderfulTartiflette thank you for reporting this :)
> > I have just confirmed the same info you're seeing. I will find out why it is showing like that = filing a bug and doing some regressions.
> > I will let you know when we have a target fix for this but in the meantime let's not close this bug. Thank you for your help!]
> > Karen
> 
> In 4576, there is a value now for the Xe-Core, but it's 512 which is completely wrong

Actually it is accurate. The info under Xe Cores is calculated in Execution Units
1 Core = 16 Execution Units
In your case, A770 LE has 32 Xe Cores x 16 EU = 512

In the [ARK Page ](https://ark.intel.com/content/www/us/en/ark/products/229151/intel-arc-a770-graphics-16gb.html)you will find information regarding XMX Engines, which are the same as Execution Units
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/fa766be6-2a88-4f17-9a6e-e10f4d10709c)

Karen

**Comment by TheWonderfulTartiflette** [comment]
> > > Hey @TheWonderfulTartiflette thank you for reporting this :)
> > > I have just confirmed the same info you're seeing. I will find out why it is showing like that = filing a bug and doing some regressions.
> > > I will let you know when we have a target fix for this but in the meantime let's not close this bug. Thank you for your help!]
> > > Karen
> > 
> > In 4576, there is a value now for the Xe-Core, but it's 512 which is completely wrong
> 
> Actually it is accurate. The info under Xe Cores is calculated in Execution Units
> 1 Core = 16 Execution Units
> In your case, A770 LE has 32 Xe Cores x 16 EU = 512
> 
> In the [ARK Page ](https://ark.intel.com/content/www/us/en/ark/products/229151/intel-arc-a770-graphics-16gb.html)you will find information regarding XMX Engines, which are the same as Execution Units
> 
> ![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/fa766be6-2a88-4f17-9a6e-e10f4d10709c)
> 
> Karen
> 

Yeah but in Arc Control, the 512 value is next to "Xe-Cores", not "Xe Matrix Extensions" or "Execution Units"
If the 512 value is really right, then it would be the text displayed next to it that would have to be changed, no?

**Comment by Karen-Intel** [comment]
Right, I'm actually opening a report for this, as you say it can be misleading :)
I will keep you up to date and hopefully we will have some changes in upcoming releases 

Karen

**Comment by Karen-Intel** [comment]
@IGCIT can you help us close this one? Xe Core value is available in Execution units and it wasn't available before.
For the right unit to show in ARC Control under XE Cores, it has been marked as future improvement.

TY 

Karen

**Comment by Karen-Intel** [comment]
Internal tracking number: 16021872873

**Comment by Vivek-Intel** [comment]
Just an update on this issue :

Our priority is to target the most popular games and apps issues to focus our efforts on providing a high quality, stable experience for the broadest set of users. We will continue to improve our software performance and compatibility but as of now we will not able to accommodate this request.

As of now we have removed this option from Arc control panel but be assured that we will re-implement this option once we have proper interface to support this. Thank you for your understanding.

**Comment by freak2fast4u** [comment]
Rev 4952 reports 256 Xe-Cores now, which seems to correspond to nothing. 

@Vivek-Intel : Should we conclude that this information will be temporarily removed from Arc Control starting with the next release ? This seems low priority indeed, but only if this value isn't used by other software as an input for configuration of a graphics or compute pipeline. Who knows what software leverages this information other than Arc Control ... ?
I could definitely see some compute API using that number to define a number of workers/threads, so unless the number of Xe Cores/EUs is properly available elsewhere, this could negatively impact the performance of the card in such software.
