### ISSUE TITLE
Black Desert Online - Bright flashing lights, broken textures

### ISSUE THREAD

**Issue by GottaSlay** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#354]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Black Desert Online

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3d

### Graphic Card [Required]

Acer Intel Arc A770 Predator BiFrost OC

### GPU Driver Version [Required]

- [X] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11819105/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Broken dirt dust textures around the player character.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/fe600c19-d417-4cd7-8140-138da7ac6dd4)

Strange red lines coming from another player's mount.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/6d186800-6747-4d37-87b0-fa8a780d24ea)

I have also encountered bright flashing lights and other very strong graphical errors. I haven't found a way to reproduce the issues consistently and the artifacting seems to happen randomly. One thing that I have noticed is that once the artifacting begins. It is usually here to stay until I restart PC. 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/31f5c5a3-9a33-4588-b8c9-d42c2e0f1c34)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/53478394-b1eb-4367-a315-09abc84e6537)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/952661cd-7073-4b1b-8be2-7360e0fd095a)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/36fc0ce4-a445-4460-b563-d6d2dc1f4d2c)

Under the Effects tab. Everything is running at default settings except the Photo Filter has been set to Vibrance.

**Comment by GottaSlay** [comment]
Here's a big one that kept reappering every time I exited the in-game options menu. The part where the lines cross each other is where my cursor would fade away after exiting the options menu. 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/9934bd13-99f1-4016-8a64-b56bba2572dc)

**Comment by Karen-Intel** [comment]
Heey @GottaSlay thanks for your report
Proceeding to do some research about this bug as well as some testing in the lab.
If I need any additional info will get back to you

Karen

**Comment by GottaSlay** [comment]
Also with a prior version yes. Version: 31.0.101.4382. That and .4499 are the only drivers I've used so far.

**Comment by Joseph-Intel** [comment]
Hi @GottaSlay I was able to test this out on our newest driver V.4672 and i have not been able to reproduce the lighting or the cursor issue [https://youtu.be/i2rQ8ImLmFo](url). Would you be able to test on your end and let us know your results?

Thanks!

**Comment by GottaSlay** [comment]
Hey! I haven't played for a while but I'll take a look at it and report back. Reproducing the issue was very odd and inconsistent back then. Maybe I'll find a pattern to it.

**Comment by Joseph-Intel** [comment]
Hi @GottaSlay I am checking in to see if you were able to come up with anything.

**Comment by GottaSlay** [comment]
Hello, sorry for delay. I was unable to reproduce the issue. I didn't see the reported issues happening any more after I had reinstalled the game.
