### ISSUE TITLE
Star Citizen lens flares way too strong

### ISSUE THREAD

**Issue by UmbraAtrox** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#355]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Star Citizen

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

Standalone Starcitizen launcher

### Processor / Processor Number [Required]

i5-12600k

### Graphic Card [Required]

A750 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[intl.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11828147/intl.txt)

### Description and steps to reproduce [Required]

So basically all the lensflares are overblown. I asked in SC discord and reddit who said it's an Arc issue, so here i am. 
Game uses Vulkan afaik. (gen12 renderer)

https://www.youtube.com/watch?v=MBFsGsb2N9o This is how the game looks. It's not with all lights, but in this particular trading center in New Babbage it happens every time. Planet surface looks like this during certain times of day 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/33509547/f48d9652-362e-4c2e-b2ac-fdc4fa14f33a)

I tried 4369, 4499 beta and now 4502. Used DDU between installations, and cleared Starcitizen shadercache. I tried every available setting from min to max.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Any

### Device / Platform name

Windows Computer

**Comment by Karen-Intel** [comment]
Hey @UmbraAtrox thanks a lot for your report

We will do some testing in the lab and get back to you if we are able to repro or have questions.
Stay tuned!

Karen

**Comment by leinir** [comment]
There's a matching ticket on the intel insiders community discord with further information - i'm sure someone on your team can get you a link if you've not found it already :)

**Comment by UmbraAtrox** [comment]
Thank you, i didn't know there is a intel discord. I found the server and the topic. Looks like info about this was passed in february 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/33509547/ff271596-f602-4877-8f4e-5a04a1eb6c84)

but this post after says  "D3D11 shader cache" i assume they are looking for a DX11 bug or did their data collection when the DX11 renderer was still the default for the game?
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/33509547/2ad8e3a7-1bec-46a3-b143-205a313825bc)

Afaik SC made the switch from DX11 to Vulkan with implementing their "Gen12"-renderer, and right now it definitely happens with that. In the SC-console r_Gen12 returns which renderer it currently is using, where 2 was the default for me.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/33509547/0a6eb204-5dbe-463a-bc5e-6632836f4f30)

**Comment by leinir** [comment]
On Friday, 23 June 2023 12:42:29 BST UmbraAtrox wrote:
> Thank you, i didn't know there is a intel discord. I found the server and
> the topic. Looks like info about this was passed in february
> ![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/a
> ssets/33509547/ff271596-f602-4877-8f4e-5a04a1eb6c84)

  That's the one! :)

> but this post after says  "D3D11 shader cache" i assume they are looking for
> a DX11 bug or did their data collection when the DX11 renderer was still
> the default for the game?
> ![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/a
> ssets/33509547/2ad8e3a7-1bec-46a3-b143-205a313825bc)
>
> Afaik SC made the switch from DX11 to Vulkan with implementing their
> "Gen12"-renderer, and right now it definitely happens with that. In the
> SC-console r_Gen12 returns which renderer it currently is using, where 2
> was the default for me.
> ![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/a
> ssets/33509547/0a6eb204-5dbe-463a-bc5e-6632836f4f30)

  That part, i'm afraid, is a pretty common mistake: Gen12 is not yet Vulkan 
based, it's still running on DX11. The initial implementation of Vulkan would 
hopefully arrive in the next short while, but until then, DX11 is what we've 
got outside of the CIG offices. This follows the ancient tradition of CIG being 
good at naming things ;)

-- 
..dan / leinir..
http://leinir.dk/

**Comment by Karen-Intel** [comment]
Hey @leinir and @UmbraAtrox just FYI

Our development team is currently working on the issue. 
I am including the impact of the issue posted in both GitHub and Discord channels as we have two dedicated threads to it now.

I will provide an update here the moment I receive an update about the fix. Thank you for your help

Karen

**Comment by UmbraAtrox** [comment]
I noticed the issue still has the [Info: Needs Replication] tag, do you need step by step instructions to replicate this? Still happens on 31.0.101.4644.

**Comment by Karen-Intel** [comment]
Hey @UmbraAtrox nope we have already reproduced the issue, the tag remains there as common practice. 
We're still waiting for a fix to be released and we may have news soon but atm we're still waiting, ty for your patience.

Karen

**Comment by UmbraAtrox** [comment]
Fixed in 4826. Thanks intel <3
