### ISSUE TITLE
Intel DSA tells me that a custom driver from ASUS is required for my A770

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#356]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Driver and Support Assistant

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [ ] 31.0.101.4502
- [X] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 22.06.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11832528/Intel.SSU.22.06.2023.txt)

### Description and steps to reproduce [Required]

On 4499, try to use DSA to get 4502

### Device / Platform

ASUS PrimeP Z790 WiFi D4

**Comment by TheWonderfulTartiflette** [comment]
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/969325de-73b4-488f-af7c-934bcfaf4250)

**Comment by TheWonderfulTartiflette** [comment]
It says that a custom driver for my GPU is currently installed but this is false, I downloaded 4499 directly from the .exe file Intel gives on their website

**Comment by TheWonderfulTartiflette** [comment]
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/bf33a0f4-c06d-495e-807c-af11abdc7f63)
And tells me that my drivers are up to date, refusing to update them. Arc Control also tells me that my drivers are up to date, but I think this is more because Arc Control's updater is broken

**Comment by Karen-Intel** [comment]
Hey @TheWonderfulTartiflette 

IDSA is a tool that works with several other products, not only with Intel iGPU drivers

I asked around and the best is to follow [this article](https://www.intel.com/content/www/us/en/support/articles/000056654/software/software-applications.html), in order to report an issue with IDSA + the info they need you to provide.

Hope that helps. @IGCIT can you help us close this one? IDSA issues are handled in a different channel 

Karen
