### ISSUE TITLE
IGCIT Helper- Object reference not set to an instance of an object when trying to enable crash dumps.

### ISSUE THREAD

**Issue by darekuklinski** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#358]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

IGCIT

### Processor / Processor Number [Required]

AMD Ryzen 5 3600

### Graphic Card [Required]

Intel Arc a770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11851615/igcit_ssu.txt)

### Description and steps to reproduce [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/51094756/42eab8ca-3dee-430b-a5d1-0fb01d2e8696)
1. Run IGCIT
2. click Tools>Crash dumps> Enable
3. in pop-up window click YES

**Comment by Arturo-Intel** [comment]
@IGCIT you take this one?

**Comment by IGCIT** [comment]
> @IGCIT you take this one?

yes

**Comment by IGCIT** [comment]
hi @darekuklinski, i cannot reproduce on my system, but i'm going to rewrite the app anyway, so i will send you the new app once ready to test

**Comment by IGCIT** [comment]
hi @darekuklinski, can you please try with this one
[helper.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11938590/helper.zip)

**Comment by darekuklinski** [comment]
Hi, after clicking enable there is this in logs
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/51094756/db5949de-d63e-46bf-8f4e-be07bde350ee)

**Comment by darekuklinski** [comment]
looks like app have different behaviour when run as standard user, and other when run as Administrator
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/51094756/75630c60-a0f2-48cc-bb96-1e1df2b1cd2f)

**Comment by IGCIT** [comment]
> Hi, after clicking enable there is this in logs ![image](https://user-images.githubusercontent.com/51094756/250626327-db5949de-d63e-46bf-8f4e-be07bde350ee.png)

ah yes, forgot to mention crash dumps options require admin rights

thanks, not sure why you get that error, maybe you used debloat scripts or disabled stuff in windows?
anyway, i will fix it tomorrow and post a new test that should work

**Comment by IGCIT** [comment]
[helper.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11948616/helper.zip)
