### ISSUE TITLE
Blender rendering with Cycles freezes/crashes when multiple instances are rendering at once

### ISSUE THREAD

**Issue by a-One-Fan** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#360]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Blender 3.5.1

### Processor / Processor Number [Required]

Ryzen 7 3700x

### Graphic Card [Required]

Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu_4502.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11854577/igcit_ssu_4502.txt)

### Description and steps to reproduce [Required]

Blender is free. The issue also happens on a recent 3.6 beta, so likely any recent Blender version will also work. It has portable versions as well, so no need to even install. Grab one, run it, edit > preferences > system, switch to OneAPI and untick the CPU if it's ticked:

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/100067309/0a42972d-0362-4f49-9ce2-f17af996154f)

Save the preferences from the hamburger menu on the bottom left. Close Blender?

Open two instances of Blender. Any file should work, you can keep using the startup file. In the render properties (on the right side, the first icon, the back of camera / front of microwave icon), use the Cycles render engine with the GPU Compute device. Below that, under sampling > render, disable noise threshold and set the samples to something high so it can keep rendering for a while (e.g. type in `2**20`). 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/100067309/5e62a9c7-5381-4205-8f12-5cac9ecf2106)

Make each start rendering (Render > Image, or press F12).
One or both instances might rapidly slow down, after a while both will halt completely, artifacts might have shown up, one instance might crash (crashes seem to be rare), and if no crash happens, you will get the following error on one of the instances:

```
Error: oneAPI kernel "integrator_terminated_paths_array" execution error: got runtime exception "Provided range is out of integer limits. Pass `-fno-sycl-id-queries-fit-in-int' to disable range check. -30 (PI_ERROR_INVALID_VALUE)"
```
(You can do window > toggle system console to be able to copy it more easily)

Rendering with multiple instances like this is mainly useful to have one instance do CPU work like calculating modifiers as the other does GPU work, beyond other possible things like working as a render is going on. 

### Application / Windows logs

```
Error: oneAPI kernel "integrator_terminated_paths_array" execution error: got runtime exception "Provided range is out of integer limits. Pass `-fno-sycl-id-queries-fit-in-int' to disable range check. -30 (PI_ERROR_INVALID_VALUE)"
```

Log file generated by running debug_log.cmd: 
[blender_debug_output.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11854772/blender_debug_output.txt)

**Comment by Karen-Intel** [comment]
Hey @a-One-Fan thank you for your submission!

I was able to repro the same behavior which pretty much shows up after rendering 2 objects at a time and one of the screens freezes.
I am reporting it internally ASAP and will update this thread once we have any updates or a fix in a public release. In the meantime, let's keep this post open.
Question: Have you reported this issue in another forum?

Thanks

Karen

**Comment by a-One-Fan** [comment]
Hello!
>  Question: Have you reported this issue in another forum?
I have not reported this elsewhere. Someone else might have reported this issue elsewhere but I can't know that for certain. I contemplated making an issue on Blender's issue tracker, however I decided that this is most likely an issue I should report here instead.

**Comment by Karen-Intel** [comment]
Hey @a-One-Fan what's your experience with latest drivers on this issue?
It should not occur anymore. Can you confirm? Thanks

Karen

**Comment by a-One-Fan** [comment]
@Karen-Intel I can't reproduce this anymore, seems fixed.

**Comment by Karen-Intel** [comment]
Thanks a lot for confirming @a-One-Fan! Will be closing this one out ;)
