### ISSUE TITLE
[black sqares]

### ISSUE THREAD

**Issue by Promixius** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#361]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Eve online

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

Eve online launcher

### Processor / Processor Number [Required]

Ryzen 7 3700X

### Graphic Card [Required]

A770

### GPU Driver Version [Required]

- [X] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11856536/igcit_ssu.txt)

### Description and steps to reproduce [Required]

After updating to the latest drivers explosions will not be correctly displayed it leaves white trails all over the screen and the explosions will have big black squares all over it.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![2023-06-24 13_08_32-EVE](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/20387868/05fd284c-aa36-4bbb-9147-df8139859852)

**Comment by Promixius** [comment]
few second video clip to show could not be uploaded here but placed it on mega link here
https://mega.nz/file/NaligIpJ#wxRVb_woBbJpBeAN4QSWwShy4dkdvdVSwU-wQkiBoFw

**Comment by Arturo-Intel** [comment]
@Promixius Hey... did you try with the latest drivers? ([101.5074](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html))

**Comment by Promixius** [comment]
Hey
So I did a ddu and installed those drivers the result is a little bit of change in behavior but still very messy

Link to video
https://mega.nz/file/gKNDhBLS#iXxEzk3ORmZyEr8LpwDq3rIRKXZlYpDyXr9coMdqEHI

If I decrease shaders to medium instead of high most of it goes away to a playable state.

**Comment by Arturo-Intel** [comment]
Is there a way to reproduce it without going to deep into the game?

**Comment by Promixius** [comment]
I will do some tests with starter ships when I get home Friday and let you know

**Comment by Arturo-Intel** [comment]
> I will do some tests with starter ships when I get home Friday and let you know

@Promixius Hey any news with this?

**Comment by rmorera-intel** [comment]
We didn't get any reply so we'll proceed to close this one.
