### ISSUE TITLE
Fortnite DX12 not working with Driver 4502

### ISSUE THREAD

**Issue by Darklegion1978** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#362]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Fornite

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 5600X

### Graphic Card [Required]

Intel Arc A770 Phantom Gaming D 8GB OC

### GPU Driver Version [Required]

- [ ] 31.0.101.4502
- [X] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11869220/ssu.txt)

### Description and steps to reproduce [Required]

With the new WHQL Driver, Fortnite wont start with DX12, it just repeats to start  with DX11.
You can switch as often as you like, after rebooting Fortnite its still on DX11.

With Beta Driver 4499, DX12 works well.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

3440 x 1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

All Settings for testing purpose on Low Settings, without Raytracing

**Comment by Arturo-Intel** [comment]
@Darklegion1978 
Thank you for sharing this, will replicate this on the lab, seems 4502 is missing some of the improvements that comes with 4499, will check this with the drivers team. 

I am a little curious: using the 4499 you can play on better quality? with DX12 and with a good FPS?
--r2

**Comment by Darklegion1978** [comment]
@Arturo-Intel Thanks for your Answer, till today each Driver Version, if Beta or WHQL worked perfect with DX12 on Fortnite. FPS are awesome and i fixed them to 120 FPS in Fortnite, without any drops or problems. Just the new WHQL Driver wont work with DX12.

**Comment by Darklegion1978** [comment]
@Arturo-Intel small Update, with the new Beta Driver 4514, DX12 is also working with Fortnite. Tested today. Greetings

**Comment by IGCIT** [comment]
Thanks for the update, closing as fixed in 4514 driver
