### ISSUE TITLE
feature request for driver installer: just install arc control

### ISSUE THREAD

**Issue by Vipitis** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#364]
### Application [Required]

Intel Graphics Driver installer

### Processor / Processor Number [Required]

i5 6600K

### Graphic Card [Required]

A750 LE

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [X] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

The graphics driver installer .exe has never allowed you to install just Driver + Arc Control and **NOT** get IDSA. If you uncheck IDSA you can no longer check Arc Control. (also the indentation makes no sense, maybe this has never been intended this way).

before the 4225 driver version, we still had a .zip download for the driver intaller. It was possible to delete the IDSA installer from the unpacked folder and then install just the driver. Then install Arc Control manually via the installer. This workaround is no longer possible with the new self unpacking driver.

### Additional notes

This has been *known* since at least August 2022 and shown as an issue in this [GN video](https://youtu.be/MjYSeT-T5uk?t=820)(timestamped). So has it been on the list of 43 acknowledged issues [by Lisa](https://community.intel.com/t5/Blogs/Products-and-Solutions/Gaming/Engineering-Arc-8-19-2022/post/1407637)?

**Comment by stalker-svk** [comment]
you can uninstall IDSA via Programs and features and keep the arc control center, I do it every time after installing new version

**Comment by Karen-Intel** [comment]
Hey @Vipitis thank you for your submission!

Also like @stalker-svk mentioned you can uninstall it but I will make sure to share this info with the ARC Control team
Thank you!

Karen

**Comment by Gabriela-Intel** [comment]
@IGCIT Please close this one.
