### ISSUE TITLE
feature request for driver installer and Arc Control: localization options

### ISSUE THREAD

**Issue by Vipitis** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#365]
### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

i5 6600K

### Graphic Card [Required]

A750 LE

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [X] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

The intel arc driver installer as well as arc control will be localized to your system language, if you want to or not.
There should be an option to chose what language you want the installer to run with and also what language you want to use for Arc Control. 
Perhaps it could be a option within Arc Control too?

Before the February release of the new "desktop standalone" mode of Arc Control with driver 31.0.101.4091 you were able to simply rename the files in `C:\Program Files\Intel\Intel Arc Control\locales` to get whatever language you want. This is no longer possible as the actual translations seem to be stored elsewhere and that subfolder might just be a leftover.

**Comment by Karen-Intel** [comment]
Hey @Vipitis thank you for your submission!

I will make sure to share this info with the ARC Control team. We appreciate your suggestions!

Karen

**Comment by Gabriela-Intel** [comment]
By the way, you can run the installer using the command line and `-g <lcid>` to change the language of the installer UI. You can see the the lcids for the supported languages in the screenshot below.

You can check `--help` to see more custom install options.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/114173691/ce6e0752-3e68-4ac1-b58d-1e0c8d2f3684)

@IGCIT Please close
