### ISSUE TITLE
BSOD:  0x139: KERNEL_SECURITY_CHECK_FAILURE while installing beta drivers (But I'm fairly sure it was my fault (maybe?))

### ISSUE THREAD

**Issue by LancerDawg75** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#369]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel XE/Arc Driver Package 31.0.101.4514

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3D

### Graphic Card [Required]

Intel Arc A770 Limited Edition

### GPU Driver Version [Required]

- [X] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu - 28 Jun 2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11891284/igcit_ssu.-.28.Jun.2023.txt)

### Description and steps to reproduce [Required]

I am going to preface this to say:

- This might have been my fault
- Not sure if this is just isolated to my system

The BSOD that I encountered:
[Bug Check 0x139: KERNEL_SECURITY_CHECK_FAILURE](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x139--kernel-security-check-failure)

First Attempt: 
Got the new beta driver and ran the install application. Went through the motions and it threw a BSOD towards the end of the installation process but it still seemed like the driver package installed correctly.

Second Attempt:
Ran the installation again, and started a repair procedure. Installation going through the motions. BSOD tripped again around the application's firmware and update check. This time, the audio drivers did not install.

Third Attempt:
Before trying again, I remembered recently that I changed a setting in Windows Security.
 - Device Security > Core Isolation > Kernel-Mode Hardware-enforced Stack Protection 
 - Disabled the setting and rebooted the system
 - Ran the installation again. Started the Repair Procedure + Clean Installation option
 - Installation first stated that there was no supported GPU for the install, but it still successfully installed both the graphics + audio driver with the request of a reboot
 - Driver Support Agent isn't running in the system tray (unless this was a new feature offered in this package)

So far, I don't seem to have any issue. I'll update if there are any more further issues. If so, I will attempt a DDU with the Stack Protection still disabled to see if that changes anything, But as for now, I think it was the Stack Protection that tripped something in the driver set. 

With that said, I am not sure if this affects all driver installations and/or it is relegated to the AMD platform, or it's just an isolated case to me only, but that this may be a workaround if you get the same BSOD as I did.

### Crash dumps [Required, if applicable]

[062823-5218-01.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11891883/062823-5218-01.zip)

### Application / Windows logs

[Event Viewer Bug Check 28 Jun 2023.docx](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11891838/Event.Viewer.Bug.Check.28.Jun.2023.docx)

**Comment by pcslide** [comment]
When I was on v.4369,  I once got BSOD: 0x139 when trying to connect remotely through RDP.  Since that was a no-no for me, I rolled arc driver all the way back to v.3959.  

Here is a summary of that incident:
Crash Time        : 5/22/2023 3:59:44 PM
Bug Check String  : 
Bug Check Code    : 0x00000139
Parameter 1       : 00000000`00000003
Parameter 2       : ffffc680`51a95660
Parameter 3       : ffffc680`51a955b8
Parameter 4       : 00000000`00000000
Caused By Driver  : ntoskrnl.exe
Caused By Address : ntoskrnl.exe+3fbc10
File Description  : NT Kernel & System
Product Name      : Microsoft® Windows® Operating System
Company           : Microsoft Corporation
File Version      : 10.0.19041.2965 (WinBuild.160101.0800)
Processor         : x64
Crash Address     : ntoskrnl.exe+3fbc10

**Comment by LancerDawg75** [comment]
Eh, my wife said while I was out getting some stuff that it BSOD'ed again while watching something on YouTube, so I'm going to DDU and try the beta driver again. If it happens again, I'll just end up rolling back to the WHQL version as I had no issue with that.

**Comment by LancerDawg75** [comment]
Update 28 June 2023 -- 21:56

Performed a safe mode DDU (Kernel Mode HESP still disabled) and reinstalled the drivers. So far, so good.

**Comment by Karen-Intel** [comment]
@LancerDawg75 phew you scared us for a minute!

Glad it worked using DDU! We will be on the lookout in case any other user reports the same behavior :)

Karen

**Comment by LancerDawg75** [comment]
@Karen-Intel Sorry! 

I think HESP had something to do with it. But again, I'm just not entirely sure. I think from the time that I bought Arc, HESP was always off, or when I would try to turn it on and reboot, it would be off again. Interestingly enough, it actually stayed on after the last Windows Cumulative Update.  

In any case, I'm used to it. Going through the motions with Arc is actually pretty similar to the early days of when I was running Vega 64. So I am a bit used to submitting feedback.

**Comment by pcslide** [comment]
@LancerDawg75 
I didn't follow you.  Did you mean the issue is resolved on your side by disabling HESP?  Or did you mean it was DDU, that regardless of HESP, solved the issue ?
I asked that because after some digging I found HESP relies on hardware virtualization.  And If I recall clearly, I got BSOD: 0x139 when running WSL2.

**Comment by LancerDawg75** [comment]
@pcslide 

I'll try to clarify.

- When I was on the previous WHQL driver version, HESP was enabled. This was a few days ago.
- I attempted to install the latest beta version while HESP was enabled
- I ran into BSODs with the first two attempts --**during the installation**--
 - The first attempt BSOD occurred towards the tail end of installation
  - The second attempt (re-install the driver package via the "repair" procedure), the install procedure BSODed again, but a lot sooner. It started right after the status indicated that it was checking for any firmware update 
 - At this point, this is where I disabled HESP
 - Third Attempt (reinstall driver via the repair procedure + clean install option checked) This time the installation finished without issue
 
So what I was trying to convey is that I couldn't install the driver package properly with HESP on. I have not tested it yet, I but I feel that I could turn it back on and not have any further issues, but if I have to install an updated driver, I might run into the issue again. 

However, while it did finally install properly, I still ran into a BSOD later on. My wife saw that it did BSOD when a YouTube video was paused. Looking at the Event Viewer, it seemed to have suffered a [0x116: VIDEO_TDR_FAILURE](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x116---video-tdr-failure).

This made me feel that the repair procedure with the clean install option enabled ....did not properly execute a clean install. 

So with that, with HESP still disabled (because I'm afraid that I will not be able to install with it on) I performed a safe mode DDU clean and restart of the GPU drivers. 

Reinstalled the latest beta driver again. (4th attempt). It installed without issues, and so far, I haven't had any other BSODs again.

**Comment by Karen-Intel** [comment]
@LancerDawg75 Hi

Did you see the same Kernel failure after all these days? If not, is it okay if we close this bug?

Thanks a lot :)

Karen

**Comment by LancerDawg75** [comment]
@Karen-Intel 

I haven't had any issues since disabling HESP/Kernel DMA Protection. I think that was the issue. However, since I'm the only one, I can't say that HESP is the definitive cause. It might be for those running AMD platforms and it might be related to my Windows install. But also, I rolled back to 4502 anyway because of the HEVC issue. 

Eh, we can close it. It's not like anyone else is reporting similar behavior.

**Comment by Karen-Intel** [comment]
@LancerDawg75 thank you! If you see any other issue, please let us know 

@IGCIT please help us close this one. We have not been able to repro and it is not occurring to our customer anymore.

Thanks

Karen
