### ISSUE TITLE
Star wars Battlefront 2 crash

### ISSUE THREAD

**Issue by hididi31** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#37]
#### Game _[Required]_
star Wars battlefront crash

---
#### CPU _[Required]_
I7-1160g7

---
#### GPU Driver Version _[Required]_
Latest official Intel GPU driver

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_:DirectX
**API Version** _(example DirectX 12)_:DirectX 11

---
#### Windows Build Number _[Required]_
Latest build

---
#### Description _[Required]_
The game random crash after playing some seconds or Max few minutes. 
---
#### Steps To Reproduce _[Required]_
Just play and the game will crashing during multiplayer 
Gaming
---
#### Screenshots _[Optional]_

---

**Comment by hididi31** [comment]
Hello I reply to you for battlefield 5 just copy my answer try to provide more détails Windows 10.0.19042 build 19042I7 1160g7 last GPU driver16gb ramOneGXproIt happens with all games using the frostbyte engine from Dice  so battlefront battlefield 1 , battlefield 5, Need for speed playback, nfs heat. The games run Fine but can crash suddenlyLaunching games on OriginTell me if need more infoThanksLe 1 avr. 2021 07:57, leoben2 ***@***.***> a écrit :
Seems like there's a common theme of app crashes on your specific system. I'm suspecting you may have a platform level stability issue here.

**Comment by estebanr863** [comment]
Hi all,

I would appreciate it if some of you can try to reproduce this issue with the latest driver 30.0.100.9955

**Comment by estebanr863** [comment]
Hi, I just tried this myself and was able to play without any issues. @hididi31 can you please try it?

**Comment by mva94** [comment]
@estebanr863 I'm going to take your words and @PacoAvelar since you both tested it.
@hididi31 isn't part of this community anymore and hasn't been active in a while
