### ISSUE TITLE
Voltage offset in Arc Control seems.. wrong?

### ISSUE THREAD

**Issue by BelleNottelling** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#372]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11902248/igcit_ssu.zip)

### Description and steps to reproduce [Required]

Admittedly this is more of a question than an actual issue, but it *might* be something that needs to be changed / fixed?

When you apply a voltage offset inside of Arc Control, the actual change in voltage seems to be half of the amount you enter, but the wording within Arc Control suggest that it applies whatever you enter there an offset to the stock voltages.

So, I expect that if the card is sitting at `1097mV` and I add a `100mV` offset that it'll increase to `~1197mV`, but instead it actually increases to `1127mV` and sometimes jumps to `1157mV`, which would be roughly half of what I entered.
Likewise, trying a `200mV` offset only increases the voltage to `1160-1200(ish) mV` which would still be roughly half of what was entered. So I'm just not sure if I am misunderstanding how the offset is supposed to work, or if this behavior is actually not what should be expected.

**Comment by Karen-Intel** [comment]
Hey @BelleNottelling thank you for reporting this

Allow me to do some testing in the lab and I will get back to you with my findings

Karen

**Comment by Karen-Intel** [comment]
Hey @BelleNottelling did some quick tests in the lab

In my case the Voltage sits at ~795~807 mV, when I added + 125 mV  II do not see the GPU Wattage increasing.
Of course if you rely any process on the GPU it will increase.
I will ask anyways what's supposed to happen once we slide the GPU Voltage Offset bar
Let's keep this post open, I will let you know once I have any update

Karen

**Comment by BelleNottelling** [comment]
Hello, @Karen-Intel 
I've just watched this scatterbencher video on Arc OCing: https://www.youtube.com/watch?v=CIDQrNdfABA.
He made an important clarification: In his testing, the voltage offset slider does not actually offset the the voltage the card runs at, but rather it unlocks what would otherwise be restricted parts of the V/F curve

**Comment by Karen-Intel** [comment]
@BelleNottelling yeah that's what I found out also 
In that case the voltage offset is not wrong but we're not seeing clearly how is the unlocking being done
Would you rather want this one to be treated as a feature request instead of a bug?

Thanks

Karen

**Comment by BelleNottelling** [comment]
> Would you rather want this one to be treated as a feature request instead of a bug?

#384 can probably be turned into an issue for actual voltage offset functionality and this one can serve as a "bug" as the interface does not accurately represent what that option is *actually* doing, which is not ideal when people are looking to overclock

**Comment by Karen-Intel** [comment]
Hi all, leaving here an internal report number for tracking purposes:18034418487
We will provide an update as soon as possible, ty

Karen
