### ISSUE TITLE
Arc Control performance graph 'value line' oscillates back and forth slightly

### ISSUE THREAD

**Issue by BigNish7** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#373]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control v1.69.5033.3

### Processor / Processor Number [Required]

Intel i9 13900KS

### Graphic Card [Required]

Intel Arc A770LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

22621.1928

### Intel System Support Utility report

[System Support Log_BigNish7_30 June 2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11914822/System.Support.Log_BigNish7_30.June.2023.txt)

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/41939688-45b8-4b99-bccf-ff85bd36ec5e

### Description and steps to reproduce [Required]

The Performance Graphs in Arc Control's (v1.69.5033.3) Live Telemetry section allows individual values to be read off each graph by positioning the mouse over any of the graphs. A dotted vertical line then appears and a value is given relating to the position of the vertical dotted line.

I have noticed that the vertical dotted line across all visible graphs is not fixed, but oscillates (or wiggles) back and forth slightly. The value associated with the dotted line does not change due to the oscillations however. It only changes as the background graphs change.    

I have attached a video showing the oscillations. While not a major issue, it is kind of funky!

**Comment by Karen-Intel** [comment]
Hey @BigNish7!

Funky indeed LOL

Quick update! I've been able to repro. It is not a major issue indeed, but the best would be to report it which I will do so.
Let's leave this post open :)

Once I get any updates, I will let you know

Karen

**Comment by freak2fast4u** [comment]
Using 4824 WHQL right now, this seems fixed. 
@BigNish7 : is this still a problem for you ?

**Comment by BigNish7** [comment]
Hi @freak2fast4u nice to hear from you. I am sorry to say that this is still occurring for me.

I tried the 4824 WHQL version (Arc Control 1.73.5334.1):

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/a13c7227-cf03-4656-b1b0-e7cf6811956c

And also 4826 BETA version (Arc Control 1.73.5335.2):

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/1ef365c2-3fa1-4a0f-8941-77f318ee94dc

They both are still exhibiting this funky behaviour. It's not a major issue for me - just a bit weird.

**Comment by Karen-Intel** [comment]
@BigNish7 can you confirm if you're not seeing this behavior on your end anymore?

I have just checked with ARC Control v.1.73.5335.2 in driver v.5074 and I do not see it :)

Thanks!

Karen

**Comment by BigNish7** [comment]
Hi Karen

Nice to hear from you as always. I checked and I still see it in 1.73.5335.2 and driver 5074. I will upload a video to the subject thread.

Sorry for the bad news - not that it is a major issue at all.

Kindest regards,

BigNish7

> 
> On ,Wed Dec 13 2023 08:05:34 GMT+1030 (Australian Central Daylight Time),

**Comment by BigNish7** [comment]
Hi all - quick check and its still occurring for me in BETA driver v5074.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/e1c833b9-db40-42b1-a76a-6ee778e56b14

Regards,

BigNish7

**Comment by Karen-Intel** [comment]
Hi @BigNish7 update in this case:
The slightly movement has been identified as an expected behavior.
The graph is moving constantly with the updated values. 
So when you move your mouse cursor over it tries to adjust the value to be displayed = not an issue.

@Arturo-Intel could you help me close this one? It has been identified as expected :)

Karen
