### ISSUE TITLE
Hardware Accelerated playback on MPC-HC, SMPlayer, or VLC with an HEVC encode causes black or green screen (latest beta)

### ISSUE THREAD

**Issue by LancerDawg75** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#374]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

MPC-HC/SMPlayer/VLC/Windows 11 MP

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3D

### GPU Driver Version [Required]

- [X] 31.0.101.2125
- [ ] 31.0.101.2121

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

Not sure if this is applicable, but if you guys request it, I'll create one

### Description and steps to reproduce [Required]

More or less, any media video that I have that  is encoded with HEVC, there isn't any video. Audio works and the subtitles (as long as they are softsubs) they show up while using beta 31.0.101.4125

I've tried it with my main media player MPC-HC using madVR + LAV and the solution, as it stands, is to go into the LAV video filter menu and disable hardware encoding. (Select "None")

With SMPlayer, it presents a green screen, audio works, subs work. Again, as long as I go into options and turn off hardware decoding, it will work

Same result with VLC. Everything but video works, but as soon as I switch over to full software decoding. It works. 

Using Windows Media Player Legacy also works with HEVC files, but since it's legacy that means it's relying on software encoding for that. 

The default Windows 11 Media player also exhibits the same issue

I didn't have this issue with the previous and latest WHQL (31.0.101.4502) driver, so I will be rolling back to that in the meantime unless someone else has some other insight that I am not thinking of or the engineers want some additional info/logs.

I will add some screenshots using MPC-HC: 
![media mp-hc hevc swdecode](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/cc3221f0-ea5e-458a-b891-0306761cdec6)
![media mpc-hc hevc hw](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/179ac4ac-de5b-492a-80ed-056b8ffc7314)

### Crash dumps [Required, if applicable]

N/A

### Application / Windows logs

N/A (maybe?)

**Comment by LancerDawg75** [comment]
Update - 4 July 2023: Performed a safe mode DDU and rolled back to WHQL 4502. HEVC playback with hardware acceleration works like before. 
![media mp-hc hevc arc whql hw](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/2db9e63d-19ef-4658-9a92-749995f27f50)

**Comment by Karen-Intel** [comment]
@LancerDawg75 thank you for confirming the regression!

We are already in process of submitting this bug so the development team is aware of it. Once we have any update I will let you know

Karen

**Comment by LancerDawg75** [comment]
@Karen-Intel 

Update: 17 July 2023 - installed beta driver package 4575 and so far, it seems as if the issue with HEVC playback has been rectified.

If this is satisfactory for the response team, I'll close the ticket or IGCIT can. 

![Screenshot 2023-07-17 051320](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/2963d0c7-8c55-452a-b4e5-082b27aa9f21)

**Comment by Karen-Intel** [comment]
Hey @LancerDawg75 yeeei I'm glad you have been able to confirm there's no issue anymore!

I think we can close this thread for the time being.
@IGCIT can you help us close this one? Customer has confirmed issue is not happening anymore with latest beta (4575)

Karen
