### ISSUE TITLE
Total War Rome Remastered pixelated graphics

### ISSUE THREAD

**Issue by dsuded** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#375]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Total War Rome Remastered

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i9 10850K

### Graphic Card [Required]

Intel Arc A770 16 GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11926437/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Graphics is very pixelated in battles. It seems that the higher the graphics settings are the more pixelated it is.
These images are taken from Ultra settings.
![20230701150545_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/20488959/5d4bcf6f-2a0b-4ef9-9865-12ded1ea3bd0)
![20230701150549_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/20488959/b6b77837-b681-49f0-8735-e37af38e1046)
![20230701150558_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/20488959/ac086655-108f-4d8e-b384-4b4729da57fc)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![20230701165932_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/20488959/cf88912b-1149-4e20-b28d-0cea3e8359b4)

**Comment by dsuded** [comment]
Seems that anisotropic filtering is the cause, when I set to trilinear it looks ok:

Trilinear:
![trilinear](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/20488959/2973a349-cd86-4b0b-a7a4-4aaabb006980)

Anisotropic 16x:
![anisotropicx16](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/20488959/c36fcf23-9a94-4d71-b61a-5ac434249571)

**Comment by Karen-Intel** [comment]
Hey @dsuded thank you for your submission!

I know we have an issue already opened for the anisotropic filtering with a couple games, I will add the info for this game too, so it can be included in future improvements

Karen

**Comment by rmorera-intel** [comment]
Hi @dsuded I re-tested this game with our latest driver 31.0.101.5085/31.0.101.5122 (WHQL Certified) and could not observe graphic glitches nor pixelation (perhaps I'm missing something?)
Please re-test and let me know your findings.

**Comment by rmorera-intel** [comment]
We removed the Anisotropic filtering option in ARC Control so the option is now controlled exclusively through the each game's GRAPHICS MENU Section.
Please file a new bug if any issue occurs when activation Anisotropic Filtering within the game.

I'm closing this bug now.
