### ISSUE TITLE
Spotify occasionally becomes completely unresponsive

### ISSUE THREAD

**Issue by BelleNottelling** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#376]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Spotify (Desktop)

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11928550/igcit_ssu.zip)
This is a few days old (from the 28th). Let me know if you need me to make a new one

### Description and steps to reproduce [Required]

Occasionally, the Spotify app will stop responding to clicks. Windows doesn't show it as unresponsive, but clicking within it does nothing. I am able to close the window by clicking on the `X`, but when attempting to re-launch it gives a "The Spotify application is not responding" error message, forcing me to task-kill it and it's child processes before I can launch it again.

This seems to happen when I leave the Spotify app open and not playing music for a few hours. (In this instance, I noticed it when going to play music after having my PC turned on for ~5 hours). I searched the Spotify community forum, but I was unable to find anyone else on there with the same issues and I didn't find anything when googling.

**Comment by Karen-Intel** [comment]
Hey @BelleNottelling thanks for your report

Understood, allow me to do some testing with the Spotify app and will get back to you with my results

K

**Comment by Karen-Intel** [comment]
Debug update 
After 5 hours of testing non-stop, while playing 2 episodes of a podcast (~2 hrs and a half each) Spotify has not broken at all or show any 
Next stage: Leave system in idle with Spotify open and see if it gets broken or shows an error message

Karen

**Comment by Karen-Intel** [comment]
Debug update #2

After leaving the system 10 hours in idle, with Spotify app open and not playing anything, attempted to press play.
Playback resumed succesfully without any issues, slowness or any strange behavior
GPU A750 running at ~4%, Memory 33%

**Comment by BelleNottelling** [comment]
> Debug update #2

Thanks for the update, @Karen-Intel.
I just verified I am also using the same version of Spotify as you are:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17304943/6099ce84-6481-47f7-a511-3fa3894b4ced)

I've only experienced this issue a handful of times, so it's quite intermittent and I don't know how to reliably reproduce it unfortunately.
If there's some way I can help you debug it, please let me know

**Comment by Karen-Intel** [comment]
Debug update #3

After leaving system in idle for 9 hours, this time the playback button would be greyed out and would not let me play anything.
To re-enable playback, I'd have to hit the play button whitin any playlist > The green one

This seems to happen with music playlist. Last test was performed with a podcast that also has video and behavior could not be reproduced.

Next stage: prepare a system with NVIDIA 3060 + Spotify and leave overnight and see if the playback button is active

Karen

**Comment by BelleNottelling** [comment]
> this time the playback button would be greyed out and would not let me play anything.
> To re-enable playback, I'd have to hit the play button whitin any playlist or artist

Hm.. That doesn't really sound like what I experienced. The Spotify interface was completely unresponsive to any interaction and had to be task-killed before I could use it again. I'll try to remember to capture a recording of the behavior whenever I see it again

**Comment by Karen-Intel** [comment]
Yeaaah sorry @BelleNottelling that's the only strange behavior I could find. I'll be on the lookout for your update, I hope you can repro the issue :)

K

**Comment by BelleNottelling** [comment]
> Yeaaah sorry @BelleNottelling that's the only strange behavior I could find. I'll be on the lookout for your update, I hope you can repro the issue :)
> 
> K

Sounds good, is there anything specific I can do when I happens next to help you and your team debug it?

**Comment by Ilya-intel** [comment]
@BelleNottelling 
It's almost a week I have Spotify in the background and it works OK for me.
Could you try to use latest available driver? 
https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html

**Comment by BelleNottelling** [comment]
@Ilya-intel 
I don't have an Arc GPU anymore. Thanks, though.
