### ISSUE TITLE
Star wars Squadrons crash

### ISSUE THREAD

**Issue by hididi31** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#38]
#### Game _[Required]_
Star Wars Squadron 

---
#### CPU _[Required]_
I7 116G7

---
#### GPU Driver Version _[Required]_
Latest Intel driver

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_:Direct x
**API Version** _(example DirectX 12)_:Directx 11

---
#### Windows Build Number _[Required]_
Latest build

---
#### Description _[Required]_
The game random crash during campaign mode
---
#### Steps To Reproduce _[Required]_
Just play the campaign and the game will crash after few seconds or minutes. 

---
#### Screenshots _[Optional]_

---

**Comment by leoben2** [comment]
not able to repro this either, need more system details to proceed.

**Comment by hididi31** [comment]
Hello I reply to you for battlefield 5 just copy my answer try to provide more détails Windows 10.0.19042 build 19042I7 1160g7 last GPU driver16gb ramOneGXproIt happens with all games using the frostbyte engine from Dice  so battlefront battlefield 1 , battlefield 5, Need for speed playback, nfs heat. Launching games on OriginTell me if need more infoThanksLe 1 avr. 2021 07:56, leoben2 ***@***.***> a écrit :
not able to repro this either, need more system details to proceed.

**Comment by mva94** [comment]
@Saracchini let's wait for intel to see if they can reproduce it

**Comment by hididi31** [comment]
Hello , sorry don t have any device with tiger lake now. Change it à few week ago

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by estebanr863** [comment]
Hi @mva and @Saracchini, we tested this for over 4 hours and got no crashes.

**Comment by Saracchini** [comment]
@estebanr863 .
It is a bit late but I can confirm the issue can be closed. Played for almost 2 hours in Story and Practice mode (the later used to crash) and no issues.
