### ISSUE TITLE
Cyberpunk freezes when set to fullscreen

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#383]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Cyberpunk 2077

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [X] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 05.07.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11961197/Intel.SSU.05.07.2023.txt)

### Description and steps to reproduce [Required]

Try to play in fullscreen

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

Any

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

From all the settings tinkering I did, I found that nothing fixes the issue.
Here's a OneDrive link of the issue : https://1drv.ms/u/s!AmnzYyniwxuygaMBgfcWjLk7AZHeVQ?e=HJbmll (you'll need to download it, OneDrive doesn't support AV1 previews)
The recording doesn't illustrate perfectly what I was seeing: When you see the black screens in the video, it means that I was doing Alt Tabs. This is the only way to refresh once what is displayed. If I don't do it, I simply can't see what I'm doing at all, even though the game actually runs in the background

### Device / Platform name

ASUS Prime Z790 WiFi D4

**Comment by Karen-Intel** [comment]
@TheWonderfulTartiflette hey

Okay. Download is already in progress and once we finish debugging I will get back with my findings

Thanks

Karen

**Comment by TheWonderfulTartiflette** [comment]
I have an only 1080p@144Hz monitor with DisplayPort. Hot unplugging and replugging does not do anything for me. I tried resetting display drivers (Win Ctrl Shift B), nothing more still by the way. Same for changing the render resolution in game, changing the refresh rate with windows, enabling VSync in game as well

**Comment by Karen-Intel** [comment]
@TheWonderfulTartiflette okay just wanted to confirm. 

Then I think my team will be able to repro without any difficulty with 1 or 2 monitors. 
Just share w/me the details of your monitor to add them in my report. I am already in process of filing this issue so let's keep this post open ok? Any update I will let you know

Karen

**Comment by TheWonderfulTartiflette** [comment]
Thanks a lot. It's an 24" Samsung Odyssey G3 LF24G35TFWUXEN, FreeSync Premium is enabled, running 1080p@144Hz. Would there be any more valuable info about it?

**Comment by Karen-Intel** [comment]
> Thanks a lot. It's an 24" Samsung Odyssey G3 LF24G35TFWUXEN, FreeSync Premium is enabled, running 1080p@144Hz. Would there be any more valuable info about it?

Hmm perhaps just what you have under Graphics > Display > Advanced. If I need anything else I will let you know

Talk to you soon

Karen

**Comment by TheWonderfulTartiflette** [comment]
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/13f18601-49fa-4c1a-ab7d-f625c8d66d58)
(Desktop Mode; Active signal mode; Color depth; Color format; Color space)

**Comment by Karen-Intel** [comment]
Hey @TheWonderfulTartiflette help needed

I am unable to repro the same issue with driver v.4575. Could you give it a go?
Please let me know if you're able to repro, thanks

Karen

**Comment by TheWonderfulTartiflette** [comment]
Hey, any update? Still happens, even on 4578

**Comment by Karen-Intel** [comment]
Heey @TheWonderfulTartiflette after I could not repro with v4575 my team has not been able to repro either. Allow me some time this week to double check and hopefully repro again. Keep you posted! I have the power thread for this game in the queue too, ty in advance

Karen

**Comment by TheWonderfulTartiflette** [comment]
Disabled

**Comment by Ilya-intel** [comment]
@TheWonderfulTartiflette 
I tried CP2077 on several systems with different chipsets and couldn't replicate the behavior.
So, my suggestions are:
1. Test with another display, if possible.
2. Wait for 2.0 patch which might (or might not) fix such issues.
3. Try DDU again and install latest available driver from here: https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html

**Comment by Ilya-intel** [comment]
Hi @TheWonderfulTartiflette ,
Have you managed to test the new 2.0 game version?

**Comment by Ilya-intel** [comment]
@IGCIT 
Thread is abandoned, please close.

**Comment by TheWonderfulTartiflette** [comment]
My bad I forgot it sorry, I have put a reminder to test this as soon as I get home, sorry

**Comment by TheWonderfulTartiflette** [comment]
So yes indeed it has been fixed with the 2.0 version, thanks :)
