### ISSUE TITLE
Undervolt Arc GPUs

### ISSUE THREAD

**Issue by BelleNottelling** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#384]
### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE 16GB

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Arc control doesn't allow for undervolting (neither does the graphics control library if I am understanding it's documentation correctly).
Being able to overvolt the GPUs is great when you are trying to push the limits of the card, but even stock these GPUs are lacking in efficiency and having the ability to undervolt them could give significant gains in power efficiency and drop in temperatures depending on the silicone. I know it's not exactly a 1:1 comparison & I have no idea how binned the Arc GPUs are, but it's fairly typical for Intels CPUs to be able to take a 50-100 mV undervolt while retaining stability, so it could be really handy to be able to undervolt the GPUs as well.

**Comment by Karen-Intel** [comment]
Hey @BelleNottelling!

There's a lot of ongoing work to improve ARC Control. I will make sure to share this info with the team in charge :)

Have a great weekend.

K

**Comment by Karen-Intel** [comment]
Submitted through feature requests :)
