### ISSUE TITLE
Using Parsec for an extended period of time causes the GPU Decoder to stop working

### ISSUE THREAD

**Issue by M4th12** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#385]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Parsec

### Processor / Processor Number [Required]

AMD Ryzen 1700X

### Graphic Card [Required]

Intel Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12025801/ssulog.txt)

### Description and steps to reproduce [Required]

When you use Parsec for an extender period (2-4h) the decoder crash and you need to restart the system to get back to work
Im using D3D11 Rendering with H265 enabled

### Device / Platform

B450 Motherboard

### Application / Windows logs

[parsec-log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12025904/parsec-log.txt)

**Comment by M4th12** [comment]
Hi @Arturo-Intel,
Leaving it idle, the decoder continues to work, but if you start running games or other apps, after a long time the decoder stops working

**Comment by Felipe-Intel** [comment]
@M4th12 Is this still happening with driver v.5084?

**Comment by M4th12** [comment]
No now it doesn't happen anymore, if anything sometimes the streaming freezes for a few seconds but after that it resumes
