### ISSUE TITLE
Pixel issue in different applications when hdr is enabled

### ISSUE THREAD

**Issue by Dlegend123** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#389]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Monster Hunter Stories 2: Wings of Ruin

### Processor / Processor Number [Required]

13700k

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12063363/SSU.txt)

### Description and steps to reproduce [Required]

Be on a dark/Black scene in the applications when HDR is enabled in Windows Settings. You should see some pixels having a different color than black. I've seen them green in Monster Hunter Stories 2: Wings of Ruin and white in Days Gone. The issue occurred in:

- PotPlayer, 

- the loading screens for:
1. Monster Hunter Stories 2: Wings of Ruin, 
2. games in CITRA, 
3. Days Gone

**Comment by Karen-Intel** [comment]
Hey @Dlegend123 thank you for your submission!

We will make sure to make some tests in the lab and get back to you in case we need additional info

Karem

**Comment by Dlegend123** [comment]
the issue seems to be due to using an lcd panel
