### ISSUE TITLE
Bannerlord tree graphical bug

### ISSUE THREAD

**Issue by Sherlocatt** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#391]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Mount and Blade Bannerlord

### Game Platform [Required]

- [ ] Steam
- [x] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i3 12100f

### Graphic Card [Required]

arc a750

### GPU Driver Version [Required]

- [ ] 31.0.101.4575
- [X] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12064604/igcit_ssu.txt)

### Description and steps to reproduce [Required]

I downloaded bannerlord, maxed out settings, except some of the unrelated graphic setitng like motion blur. And when ı launched the game, tree models were low quality and flicky. And it didnt change in any graphical setting. I set it to low, it was same. I looked at other players that use arc or iris xe and they were having the same trouble. This tree problem is permanent just start the game look to map and zoom to trees. And it doesnt happen in game war scenes, just in map.

This what they are looking like in my game.
![Ekran görüntüsü 2023-07-16 001813](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/139656622/2e4fdcbe-1cc5-449e-b32e-8bced5045079)

Other people that has this issue:
https://community.intel.com/t5/Gaming-on-Intel-Processors-with/Mount-amp-Blade-2-Bannerlord-Tree-Rendering-Issue-on-Campaign/m-p/1436327
https://forums.taleworlds.com/index.php?threads/graphical-issues-with-trees-on-campaign-map.455424/#post-9844018)
https://forums.taleworlds.com/index.php?threads/graphic-issues-in-intel-arc-graphic-cards-grass-trees-campaign-map.457528/
https://steamcommunity.com/app/261550/discussions/17/3821906444737420823/

Also there is a problem with games screen space reflections option. whn ı tun it on and do a benchmark, water looks flicky. And ı am in best quality antialiasing option. İf you max everything and make benchmark from settings of the game, you will understand what ı say.

And there is one more problem and ı dont know if its about the game or my graphics card or any of my components.  Some of the objects thumbnails look color reversed and blacksmith look color reversed. But map and other things are normal. İt didnt happen when ı started the game but after ı played like 1 hour it happened. And this happened to me one time and when ı restarted the game it was fixed.  I dont know if its reproducable. 

![Ekran görüntüsü 2023-07-16 000953](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/139656622/0a16c0a1-f554-461d-a687-6f3cec7c4d85)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Motiun blur and screen space reflections off. 

### Crash dumps [Required, if applicable]

No crash.

**Comment by Sherlocatt** [comment]
About tree bug, ı think its about thier transparency. bacause when ı angle it to sky, they disappear.

**Comment by Karen-Intel** [comment]
@Sherlocatt Hii and thank you for your report

Will be checking this on our systems and in case we need any info we'll get back here

Talk to you soon

Karen

**Comment by Sherlocatt** [comment]
I tried 4577 driver and problem still continues.

**Comment by Sherlocatt** [comment]
Sorry ı clicked completed but problem still continues in driver 4577.

**Comment by Ilya-intel** [comment]
@Sherlocatt 
Just wanted to let you know that this issue being investigated by our developers. I will let you know in this thread when the fix will be published. And just for reference, here's the BUG ID for quick check through other channels, if needed - 16021462113.

**Comment by Sherlocatt** [comment]
Hey, if its fixed will you gonna say anything in here? Or it will be on update notes?

**Comment by Ilya-intel** [comment]
@Sherlocatt 
I'll send you a note here when a fix will be available.

**Comment by Sherlocatt** [comment]
Still continues in 4952. For clarification.

**Comment by Sherlocatt** [comment]
Problem is fixed. I am in 5084 version of drivers and 1.2.8 version of bannerlord. I hope it wont happen again and thanks for helping me out. By the way ı didnt have the game since november. I dont know if it was fixed before this update.

**Comment by Ilya-intel** [comment]
@Sherlocatt 
Thanks for reporting, this fix was just published, good timing :)
