### ISSUE TITLE
 Need for speed unbound and  Need for speed heat having car tire disappearing glitch

### ISSUE THREAD

**Issue by xGLANZEx** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#392]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Need for speed heat and need for speed unbound

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

amd ryzen 5 5600g

### Graphic Card [Required]

Intel arc a750 limited edition

### GPU Driver Version [Required]

- [X] 31.0.101.4575
- [X] 31.0.101.4514
- [X] 31.0.101.4502
- [X] 31.0.101.4499
- [X] 31.0.101.4382
- [X] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [X] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

i dont have that software

### Description and steps to reproduce [Required]

race and wander around the city for a hour 
This issue will occur in nfs heat faster as compare to nfs unbound

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

all setting medium

### Device / Platform name

ryzen 5 5600g, gskill trident 16 gb ram, asrcock b450m steel legend, xpg ssd, intel arc a750 limited edition

### Crash dumps [Required, if applicable]

game is not crashing 

### Save game

game is autosave

**Comment by xGLANZEx** [comment]
![Screenshot (144)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/129430439/bc66f80f-cffd-4627-9f69-c77140195874)
here the photo from ingame

**Comment by Karen-Intel** [comment]
Hey @xGLANZEx thank you for your report

We already have an issue related to these games: https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/307 even tho the symptom is different, might be releated to a series of renders. I will add the details from this report anyways and see if we have any updates soon

Karen

**Comment by Karen-Intel** [comment]
Adding internal tracking number for reference: 14019323627

**Comment by rmorera-intel** [comment]
Hi everyone, this issue should be fixed with driver [32.0.101.6127 and newer](https://www.intel.com/content/www/us/en/download-center/home.html). 
Please try it out and let me know your feedback.

**Comment by Chipboard** [comment]
> Hi everyone, this issue should be fixed with driver [32.0.101.6127 and newer](https://www.intel.com/content/www/us/en/download-center/home.html). Please try it out and let me know your feedback.

No, it is not fixed in present day with the latest drivers on Intel Arc A750
