### ISSUE TITLE
Vulkan(WSI) Issues

### ISSUE THREAD

**Issue by ghost** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#395]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

mpv, libplacebo

### Processor / Processor Number [Required]

11800H

### Graphic Card [Required]

Intel(R) UHD Graphics

### GPU Driver Version [Required]

- [X] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12072956/igcit_ssu.txt)

### Description and steps to reproduce [Required]

1. If the iGPU (maybe the dGPU has the same issue?) is not connected to any monitor, it will not expose any 10bit/16bit surface
```
vulkaninfo.exe
GPU id : 1 (Intel(R) UHD Graphics):
        Surface type = VK_KHR_win32_surface
        Formats: count = 4
                SurfaceFormat[0]:
                        format = FORMAT_B8G8R8A8_UNORM
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[1]:
                        format = FORMAT_B8G8R8A8_SRGB
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[2]:
                        format = FORMAT_R8G8B8A8_UNORM
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[3]:
                        format = FORMAT_R8G8B8A8_SRGB
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
```
2. Intel's Vulkan driver does not implement the `FORMAT_A2B10G10R10_UNORM_PACK32+COLOR_SPACE_SRGB_NONLINEAR_KHR` surface format, which results in mpv not being able to achieve 10bit output under winvk.
`mpv --no-config --gpu-context=winvk --vo=gpu-next --target-colorspace-hint=yes --target-trc=pq --target-prim=bt.2020 INPUT`
```
[   0.267][v][vo/gpu-next/libplacebo] Available surface configurations:
[   0.267][v][vo/gpu-next/libplacebo]     0: VK_FORMAT_B8G8R8A8_UNORM                 VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
[   0.267][v][vo/gpu-next/libplacebo]     1: VK_FORMAT_B8G8R8A8_SRGB                  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
[   0.268][v][vo/gpu-next/libplacebo]     2: VK_FORMAT_R8G8B8A8_UNORM                 VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
[   0.268][v][vo/gpu-next/libplacebo]     3: VK_FORMAT_R8G8B8A8_SRGB                  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
[   0.268][v][vo/gpu-next/libplacebo]     4: VK_FORMAT_R16G16B16A16_SFLOAT            VK_COLOR_SPACE_HDR10_ST2084_EXT
[   0.268][v][vo/gpu-next/libplacebo]     5: VK_FORMAT_A2R10G10B10_UNORM_PACK32       VK_COLOR_SPACE_HDR10_ST2084_EXT
[   0.268][v][vo/gpu-next/libplacebo] Picked surface configuration 0: VK_FORMAT_B8G8R8A8_UNORM + VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
```

### Device / Platform

System SKU LENOVO_MT_82JD_BU_idea_FM_IDEAPAD

### Crash dumps [Required, if applicable]

N/A

### Application / Windows logs

vulkaninfo1 [vk.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12072039/vk.txt)(Display connected to dGPU)
vulkaninfo2 [vk.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12072052/vk.txt)(Display connected to iGPU)

**Comment by Arturo-Intel** [comment]
Hey! @arm64-v9a I was able to reproduce this on my end, at least with the iGPU (will try with the dGPU later). 
I will contact the drivers team to see what is happening here.

Keep you posted
-- r2

**Comment by Vivek-Intel** [comment]
@IGCIT please help close this issue , user inactive to confirm if MPV can work as he expected without --fs option
