### ISSUE TITLE
Graphical glitches in Uncharted 4

### ISSUE THREAD

**Issue by TimoMueller** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#399]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Uncharted 4: A Thief's End

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i7-1165G7

### Graphic Card [Required]

Intel Iris Xe Graphics - 96 EUs

### GPU Driver Version [Required]

- [X] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12075280/SSU.txt)

### Description and steps to reproduce [Required]

Start the game and load a save game (the issues were nicely visible in chapter 11 with the NPC).

https://www.youtube.com/watch?v=var_7o2prtI

![20230718043501_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1918290/96e0eb30-2172-424c-b757-b77923f84691)
![20230718043518_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1918290/feb580b0-011c-4d11-a972-f053ff0c0142)

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![20230718043427_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1918290/e4041a74-c501-49f3-9fa9-ba93a90d9c46)
![20230718043436_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1918290/f0a84b9d-d7b7-4d3b-bb66-5155f75ab3a7)

### Device / Platform name

GPD Win 3

### Save game

[saves.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12075360/saves.zip)

**Comment by Karen-Intel** [comment]
Hey @TimoMueller could not find Uncharted 4 in Steam
Are you referring to the Legacy of thieves Collection?

Thanks

Karen

**Comment by TimoMueller** [comment]
Yes. It's "Uncharted 4: A Thief's End" from the "Uncharted: Legacy of Thieves Collection" on Steam.

**Comment by Karen-Intel** [comment]
> Yes. It's "Uncharted 4: A Thief's End" from the "Uncharted: Legacy of Thieves Collection" on Steam.

Ty :) Just making sure we download the right one. I will post my findings soon 

Karen

**Comment by Karen-Intel** [comment]
Update on this case: Waiting for a fix to be released
Internal tracking number: 05973550
Keeping case open

Karen

**Comment by Karen-Intel** [comment]
Hey @TimoMueller can you verify this issue with latest driver release and let us know?

Thanks

Karen

**Comment by Karen-Intel** [comment]
No updates with latest drivers. @IGCIT can you help close this one please
Thanks

Karen
