### ISSUE TITLE
FFmpeg QSV decoder/hwaccel losing Dolby Vision metadata

### ISSUE THREAD

**Issue by arm64-v9a** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#403]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

FFmpeg, libplacebo

### Processor / Processor Number [Required]

11800H

### Graphic Card [Required]

Intel(R) UHD Graphics

### GPU Driver Version [Required]

- [X] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [X] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12071572/igcit_ssu.txt)

### Description and steps to reproduce [Required]

```
ffmpeg -init_hw_device vulkan=vk:Intel -filter_hw_device vk -init_hw_device d3d11va=dx:Intel -init_hw_device qsv=qsv@dx -hwaccel qsv -hwaccel_output_format p010 -i DolbyVisionVideo -vf libplacebo -c:a copy -c:v hevc_qsv DV.mkv
```
```
ffmpeg -init_hw_device vulkan=vk:Intel -filter_hw_device vk -init_hw_device d3d11va=dx:Intel -init_hw_device qsv=qsv@dx -c:v hevc_qsv -i DolbyVisionVideo -vf libplacebo -c:a copy -c:v hevc_qsv DV.mkv
```
libplacebo is a Vulkan filter that can tone-mapping DV video to normal pq/bt.2020 HDR video, but qsv decoder/hwaccel will lose the DV metadata, resulting in distorted colors in the output video.

Note that if you want to run the libplacebo filter on Intel GPUs, you have to build it with git master FFmpeg+libplacebo, otherwise it won't work.

### Device / Platform

System SKU LENOVO_MT_82JD_BU_idea_FM_IDEAPAD

### Crash dumps [Required, if applicable]

N/A

### Application / Windows logs

N/A

**Comment by Karen-Intel** [comment]
@arm64-v9a for the time being, our Graphics team is the one that handles these type of issues too so, we will make sure to debug it on our end and provide an update as soon as we can

Thanks

Karen

**Comment by nyanmisaka** [comment]
You should not open issues here. Apparently this is a limitation of FFmpeg.
In FFmpeg, only hw accelerator can pass DoVi metadata, while QSV is hw decoder.

**Comment by nyanmisaka** [comment]
Better to file a feature request in OneVPL, maybe they'll consider exposing the parsed DoVi metadata to FFmpeg via the OneVPL interface (such as for HDR10 - [mfxExtMasteringDisplayColourVolume](https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md#mfxExtMasteringDisplayColourVolume)). But DoVi is not like HDR10, it is not an open standard, so there may be licensing issues involved.

**Comment by nyanmisaka** [comment]
See https://github.com/FFmpeg/FFmpeg/commit/ad67ea9eeed2cc8edab8662b7503ce4a49247b1d

**Comment by Arturo-Intel** [comment]
@arm64-v9a as @nyanmisaka says it is better if an issue is open directly to the software developer, if there is something that we (Intel) need to work to support any feature from the software, the communication must be between the software dev and Intel.

I see the feature is already there, lets see what the devs comes up, 

@IGCIT I think we can close this issue
