### ISSUE TITLE
Detroit: Become Human - Crash while playing

### ISSUE THREAD

**Issue by YUCLing** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#404]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Detroit: Become Human

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i9-12900KS

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

- [X] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12131317/igcit_ssu.txt)

### Description and steps to reproduce [Required]

~~Start the game and finish a chapter.~~

The game crashes randomly, but in many cases, it happens after finishing a chapter for me.

~~MSI Afterburner is also running if required.~~ Still happens without MSI Afterburner.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

3840x2160

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![TX39KOSWLAR9NFA)VHFT157](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/f5f85eae-94b6-4fc3-a3eb-723bc14acad4)
![8DV~I)K48LCADVP0@E99) N](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/4f475fe7-6dc5-4a5c-b346-804438ccc6dc)
![P2JQ1A1 7XP%(_ 4JK9E`M](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/7204a4c8-8ec1-40b7-8194-89946b3f9dbc)

### Crash dumps [Required, if applicable]

[dumps.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12131331/dumps.zip)
[without_msi_afterburner.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12131411/without_msi_afterburner.zip)

**Comment by Karen-Intel** [comment]
Hey @YUCLing thank you for your report. I think I have been able to repro this silent crash

I will keep on doing some debug and report this issue internally. If I need anything else or have an update I will get back here

Karen

**Comment by YUCLing** [comment]
I'm using WHQL one

**Comment by Karen-Intel** [comment]
> I'm using the WHQL one, and I'm playing the game now, crashes happen from time to time.

TY for the fast response. I have already submitted an internal report about this issue :)
Let's hope I can bring good news soon, I'll keep you posted

Karen

**Comment by rmorera-intel** [comment]
Hi @YUCLing this should be fixed now, please try with driver [32.0.101.6083](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)

**Comment by rmorera-intel** [comment]
I'm closing this one now. If the issue persists or re-appears please open a new bug and reference this one.

Best Regards,
