### ISSUE TITLE
After update drivers, i have a problem with video output.

### ISSUE THREAD

**Issue by Dzherili** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#407]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Any

### Processor / Processor Number [Required]

13th Gen Intel(R) Core(TM) i5-13400F

### Graphic Card [Required]

Intel Arc A-770 LE

### GPU Driver Version [Required]

- [ ] 31.0.101.4576
- [X] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12174461/igcit_ssu.txt)

### Description and steps to reproduce [Required]

After update drivers to 4575 WHQL version, i have a problem with video output after booting into windows, my monitor don't recognize signal from pc. Fix problem when unplug cable from pc and plug back OR change input source on monitor and return back then monitor recognize signal. 
On drivers 4502 WHQL work perfectly.

Steps.

Update driver from 4502 WHQL to 4575 WHQL.
Reboot PC
Boot Windows
Monitor says, no signal.
Unplug cable from pc and plug back after this monitor recognize signal.

**Comment by Dzherili** [comment]
Yes i used DDU and tried update drivers 4502 to 4575 with Arc Control , same problem.

Ok i'm installed v4576 and it's work without problem)

Thanks)

**Comment by Karen-Intel** [comment]
@IGCIT can you help us close this case? User confirmed not having the issue anymore w/v4576 :)

Karen
