### ISSUE TITLE
Ratchet & Clank: Rift Apart flickering and blocky artifacts in glass materials' RT reflections

### ISSUE THREAD

**Issue by a-One-Fan** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#408]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Ratchet & Clank: Rift Apart

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 7 3700x

### Graphic Card [Required]

Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu_4576.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12177063/igcit_ssu_4576.txt)

### Description and steps to reproduce [Required]

Dynamic resolution needs to be enabled.
Raytraced reflections need to be enabled.

Play through the tutorial. Glass will show up after around 5-10 minutes of gameplay. Observe artifacty glass, which has its reflections flicker and sometimes have blocky artifacts.

Example video: https://www.youtube.com/watch?v=6QtVqIpjfjU

Example image:

![image](https://media.discordapp.net/attachments/940688440402530364/1133866995113283695/image.png)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

The High settings preset (for "Graphics") was used. Here is a picture of the non-presetable "Display" settings:

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/100067309/3fa35757-ebbc-4a27-9198-47417faa0562)

**Comment by a-One-Fan** [comment]
While the other issue got fixed, this one is still around with the game version 1.728.0.0
I guess I really misjudged that other issue, my bad

**Comment by Arturo-Intel** [comment]
@a-One-Fan 
Using .5081 the issue cant be reproduce
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/dce3004e-1dfb-45c7-a087-8eab07997aea)

--r2

**Comment by a-One-Fan** [comment]
@Arturo-Intel Sorry, I'm still getting the bug. Sometimes it might not be very visible and nefarious's dome might not become artifacty right away. After the train-ish sequence, you're flung in an area that leads to a room with glass windows, the issue is more visible with those windows and you can make a save there and test more easily. The windows will flicker much more often. The same blocky artifacts will sometimes be visible.

This seems to be caused by dynamic resolution, as with it specifically off the windows don't flicker and I don't remember seeing any nefarious dome problems.

Here is a new video: https://www.youtube.com/watch?v=Q7UpgqDYYgU

**Comment by rmorera-intel** [comment]
Hi again @a-One-Fan 
I just got word from our dev team that this issue should be fixed with the latest patch from the game developer.
Also make sure you are using our latest driver [101.5330.](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)
Please re-test and let me know your feedback.

Best Regards,
Ronald M.

**Comment by rmorera-intel** [comment]
I'll go ahead and close this one. If the issue reappears please create a new bug report and reference this one.
