### ISSUE TITLE
Watch Dogs Legion

### ISSUE THREAD

**Issue by hididi31** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#41]
#### Game _[Required]_
Watch Dogs legion

---
#### CPU _[Required]_
I7-1160G7

---
#### GPU Driver Version _[Required]_
Latest official driver

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_:Direct X
**API Version** _(example DirectX 12)_:Direct X12

---
#### Windows Build Number _[Required]_
Latest

---
#### Description _[Required]_
With Directx12 the game have too many glitch and bad color. 
With direct X 11 it s working but very bad performance. 
---
#### Steps To Reproduce _[Required]_
Just try game with défaut direct X 12 settings 

---
#### Screenshots _[Optional]_

---

**Comment by leoben2** [comment]
we're trying to reproduce this. Don't expect performance to be good on TGL. It's way below min spec.

**Comment by nielo360** [comment]
I get a good 27-34fps on my gpd win max with ice lake on dx11 with low resolution. Dx 12 is broken on ice lake as well everything is red, its a driver issue.

**Comment by hididi31** [comment]
Yes I Don t expect super performance on tiger lake but when I M using default dx12 with glitch and missing corlort he game run much better than dx11. I report the bug for trying improve the perf of tiger lake and dx12 for other games. Le 1 avr. 2021 07:54, leoben2 ***@***.***> a écrit :
we're trying to reproduce this. Don't expect performance to be good on TGL. It's way below min spec.

**Comment by hididi31** [comment]
You got 30 fps in town ? With the i7 1160 g7 Don t have more than 20 fps. I report bug with dx12 so wé ll see if they fix it but apparently no hopeLe 1 avr. 2021 15:43, nielo360 ***@***.***> a écrit :
I get a good 27-34fps on my gpd win max with ice lake on dx11 with low resolution. Dx 12 is broken on ice lake as well everything is red, its a driver issue.

**Comment by PacoAvelar** [comment]
I just booted and played from New game up to the bunker (40 mins) on:
i7 1165G7
16 GB ram
Win 11
GPU Driver 9805
Screen resolution 720p,
Resolution scale -75%
In game settings to low


No red issues with DX12, performance ~28 fps average on the benchmark 
DX11, performance of ~29 fps average on the benchmark

**Comment by mva94** [comment]
@PacoAvelar so would you say issues are solved ? Need to test this one

**Comment by craiggx** [comment]
@hididi31 Hi there. We're Looking into this issue on TGL and found the issue fixed on the latest Intel DCH driver found here: https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html

Could you check on your system and let us know if it still happens with the latest driver?

**Comment by IGCIT** [comment]
hi @craiggx, he no longer have an intel device.

@pacoa-kdbg can you please re-test the game with latest driver so we can close this? thank you :)

**Comment by mva94** [comment]
Hi @craiggx 
I own the game so I will be able to check from the 15th of January when I get my new intel device

**Comment by estebanr863** [comment]
Hello all,

We are not seen the issue on the latest driver version. Can anyone else help us verify?

**Comment by estebanr863** [comment]
Hi @IGCIT and @mva94,

We have confirmed in our lab this issue is no longer happening on driver version 30.0.101.1191. Can this issue be closed?

**Comment by mva94** [comment]
Hey @estebanr863 I just finished installing the game 

Will check
