### ISSUE TITLE
Call of Duty:Black Ops Cold War - Crashes on loadout choosing [MP\ZM]

### ISSUE THREAD

**Issue by jumofogit** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#411]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Call of Duty:Black Ops Cold War

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-1155G7

### Graphic Card [Required]

Intel Iris Xe

### GPU Driver Version [Required]

- [X] 31.0.101.4577
- [X] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[info.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12227299/info.txt)

### Description and steps to reproduce [Required]

Load up into Zombies or Multiplayer with latest BETA driver or 31.0.101.3491 one, After that, you are gonna get a crash after loading a map, while you need to choose loadout, doesn't showing last ones.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Everything at minimum, even render scale,

### Device / Platform name

MSI Modern 14 B11MOU-1051RU

### Crash dumps [Required, if applicable]

There isn't any left :(

**Comment by jumofogit** [comment]
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/411
Exact crash moments screenshot. They are pretty much same.

**Comment by Karen-Intel** [comment]
Hi @jumofogit I could load a map and a match without any issue. Did you use DDU by any chance to upgrade your driver?

If you could share a video of the exact moment when it crashes, that would be fantastic

TY

Karen

**Comment by jumofogit** [comment]
Sure, I'll rebuy game soon and record this. Do I need to update to the last driver?

**Comment by jumofogit** [comment]
Wait, on which driver you ran the game sucsessfully?

**Comment by Karen-Intel** [comment]
@jumofogit I ran it with v.4577 WHQL
I got in Zombies, selected Golova Outbreak and match loaded 
I see some graphical corruptions that I will be reporting but at least I need to know how much you play for the crash to happen
TY

Karen

**Comment by jumofogit** [comment]
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116519368/8166ebc6-bf8c-4fae-a99a-f7dfc4e6ccd3)
Gonna be on line soon.

**Comment by Karen-Intel** [comment]
@jumofogit no problem! Happy to help :)

Karen
