### ISSUE TITLE
Minecraft lag (seems to be memory related)

### ISSUE THREAD

**Issue by Danjhop4** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#412]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Minecraft 

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

Windows 11

### Processor / Processor Number [Required]

i7 1165g7

### Graphic Card [Required]

Iris xe (latest windows driver no admin idk gpu driver version)

### GPU Driver Version [Required]

- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [x] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [X] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

Lastest

### Intel System Support Utility report

N/a I don’t have admin only windows update
Latest driver from there 

### Description and steps to reproduce [Required]

It gets worse during updates or random there’s no way to force it or stop it 

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

![](https://cdn.discordapp.com/attachments/1091763354525245450/1092495879862222858/img.png)

### Game resolution [Required]

Auto

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Max render settings and chunk range lower settings
Are the same java 17 to 21 22  java garbage collection all the time even with 10 gig memory on all game versions so I have ruled out game version bugs

### Device / Platform name

B

**Comment by Danjhop4** [comment]
FPS seems to be limited by the lag had 100s of fps at times before

**Comment by Danjhop4** [comment]
My specs are in the pic

**Comment by Danjhop4** [comment]
Not allowed to download anything

**Comment by IGCIT** [comment]
if i'm reading correctly, your device is running a 1 year old driver, and a lot has changed for Xe graphics recently.

if you cannot update your driver, please understand that i will have to close this issue because that driver is too old, otherwise, please install latest driver [31.0.101.4577](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?) and try again.

**Comment by Karen-Intel** [comment]
Hey @Danjhop4 sometimes the driver rollbacks just by itself in Windows
Please make sure to reinstall your driver using the latest one IGCIT just mentioned, confirm you do have the right version in device manager and let us know how it works

Karen

**Comment by Danjhop4** [comment]
> if i'm reading correctly, your device is running a 1 year old driver, and a lot has changed for Xe graphics recently.
> 
> if you cannot update your driver, please understand that i will have to close this issue because that driver is too old, otherwise, please install latest driver [31.0.101.4577](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html?) and try again.

I can’t since that type of install needs admin and my admin would refuse

**Comment by Danjhop4** [comment]
if you close it I will have to remake it just push it via windows update so I can update I am sorry but I can’t update it’s not possible

**Comment by Karen-Intel** [comment]
@Danjhop4 we're very sorry but we definitely need you to have the latest driver to continue debugging the issue.
Once you're able to upgrade it and if you still see any issue, you're welcome to open another thread :)

@IGCIT can we proceed to close this one? User cannot upgrade his system's driver due to local access blocking and we cannot debug issues reported with old driver versions.

TY

Karen

**Comment by EliezYT** [comment]
This awful Minecraft performance is still happening as show in my post from a few months ago #368. There is bad performance in OpenGL applications/games still even after all these updates nothing has changed.
