### ISSUE TITLE
Driver 4577 WHQL - missing fan curve adjustments (Performance Tuning.js changes causes errors)

### ISSUE THREAD

**Issue by LancerDawg75** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#413]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control (Performance Tuning)

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3D

### Graphic Card [Required]

Intel Arc A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

Not Applicable

### Description and steps to reproduce [Required]

Saw on the IntelArc subreddit that fan control is missing again on this driver version. So, tried it out myself, and indeed, it is missing. Tried to use the old performance_tuning.js trick. The specific line has moved from 112 to 170. After editing the particular line....

If you choose:

- the fixed fan percentage adjustment slider, it will show up, but if you apply anything, you will get an notification windows error that it cannot be applied
- the fan curve option, nothing shows up for the fan curve. If you press apply, same notification error. 
- attempt to reset to defaults - it throws the sliders all the way to its lowest values

So, I restored the js file back to its original state, restarted Arc Control  -- and tried just to see if the rest is affected. If I move the power slider even one watt above, the same error notification will show up. 

It's kind of late over here, so when I wake up next, I'll try to DDU and see if that changes anything. 
As of right now, performance tuning isn't working right or the install went horribly wrong. 

![arc perftunejs-1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/d6986412-22a8-439e-aa1a-c1a8f26321d6)
![arcperftune-2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/7b875ca1-a21a-4060-aef5-180f84b9ba5f)

**Comment by Karen-Intel** [comment]
Hey @LancerDawg75 that is weird

I am able to see the fan curve option without doing any modifications in performance_tuning.js file
I'm using v.4577 and the ARC Control version I have is 1.70.5984.2

![ARC Control - Fan Curve showing in v 4577](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/bcbc73b7-b0b9-4d1a-a558-253dd28a77d4)

Perhaps using DDU is a good idea. 

Karen

**Comment by LancerDawg75** [comment]
@Karen-Intel 

I performed a DDU and everything is working correctly. So, I'll chalk it up to a flawed install. 

Not related: ASRock recently dropped a new BIOS revision for my motherboard (AGESA 1.2.0.A) and I'm about to try it out and see if the BIOS side of power management states might work properly in regard to the post I created in Issue #303 

My guess of the outcome (given the reply I got from ASRock before):
![noiredoubt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/b382ee6f-534e-4c9a-a229-c52eb331d1da)

**Comment by Darklegion1978** [comment]
Good Morning,

the failure you had with the Fan Control, is every time when you install a new Driver Version without to restart the PC.

I had it also, also with the last Driver Versions.
As long as you wont restart, you get also the failure message, with error applying the tuning settings.

The express install via Arc Control is fine, but a clean install is better, and never forget to restart your PC. ;)

Greetings Roman

**Comment by LancerDawg75** [comment]
That may have been the case, actually because I think I didn't perform a system restart at that time. 

....but I DDU the driver package anyway and restarted and everything works.  Thanks for that information. I will now ensure that I restart every time a new install or update comes across.

**Comment by Valkill27** [comment]
> Hey @LancerDawg75 that is weird
> 
> I am able to see the fan curve option without doing any modifications in performance_tuning.js file I'm using v.4577 and the ARC Control version I have is 1.70.5984.2
> 
> ![ARC Control - Fan Curve showing in v 4577](https://user-images.githubusercontent.com/91162218/257605684-bcbc73b7-b0b9-4d1a-a558-253dd28a77d4.jpeg)
> 
> Perhaps using DDU is a good idea.
> 
> Karen

It's very cool that the useless curve works, but when will a setting below 30% rpm setting be available? Even you can't have it run below 30% fan speeds

Predictions or something? A770 for example can not cool passively not on Sparkle A770 not on Acer A770, while the temperature in the apartment is about 21-23 degrees Celsius.

I turned on the Acer fan disconnects before I saw 70 degrees on the card.... And after reaching 70 degrees even then the fan turns on and off in an endless cycle. We need RPMs down to 15-20% 

I turned on the Acer fan disconnects before I saw 70 degrees on the card.... And after reaching 70 degrees even then the fan turns on and off in an endless cycle. We need RPMs down to 15-20%
