### ISSUE TITLE
Forza Horizon 3 is not starting on Intel Arc A750

### ISSUE THREAD

**Issue by TFXGAME** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#415]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Forza Horizon 3

### Game Platform [Required]

- [ ] Steam
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i9-9990xe

### Graphic Card [Required]

Intel Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4578
- [X] 31.0.101.4577
- [X] 31.0.101.4576
- [X] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [X] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

# SSU Scan Information
Scan Info:
 Version:"2.5.0.34"
 Date:"08/04/2023"
 Time:"00:00:15.5435344"

# Scanned Hardware
Computer:
          BaseBoard Manufacturer:"ASUSTeK COMPUTER INC."
          BIOS Mode:"UEFI"
          BIOS Version/Date:"American Megatrends Inc. 1403 , 05/23/2022 12:00 AM"
          CD or DVD:"ASUS DRW-24F1MT"
          Embedded Controller Version:"255.255"
          Platform Role:"Desktop"
          Processor:"Intel(R) Core(TM) i9-9990XE CPU @ 4.00GHz , GenuineIntel"
          Secure Boot State:"On"
          SMBIOS Version:"3.2"
          Sound Card:"High Definition Audio Device"
          System Manufacturer:"System manufacturer"
          System Model:"System Product Name"
          System SKU:"ASUS_MB_KBLX"
          System Type:"x64-based PC"
          - "Display"
               Intel ® Graphics Driver Version:"Not Available"
               - "Intel(R) Arc(TM) A750 Graphics"
                    Adapter Compatibility:"Intel Corporation"
                    Adapter DAC Type:"Internal"
                    Adapter RAM:"1.00 GB"
                    Availability:"Running or Full Power"
                    Bits Per Pixel:"32"
                    - "Caption":"Intel(R) Arc(TM) A750 Graphics"
                         Link:"http://www.intel.com/content/www/us/en/search.html?keyword=Arc+A750+Graphics"
                    CoInstallers:"oem4.inf,iDG2D_Client_w10_DS,Internal,Intel(R) Arc(TM) A750 Graphics Family"
                    Color Table Entries:"4294967296"
                    Dedicated Video Memory:"Not Available"
                    Driver:"igdkmdnd64.sys"
                    Driver Date:"07/24/2023 03:00 AM"
                    Driver Path:"C:\Windows\system32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_2085233d391e873c\igdkmdnd64.sys"
                    Driver Provider:"Intel Corporation"
                    Driver Version:"31.0.101.4577"
                    INF:"oem4.inf"
                    INF Section:"iDG2D_Client_w10_DS"
                    Install Date:"Not Available"
                    Installed Drivers:"C:\Windows\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_2085233d391e873c\igdumdim64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_2085233d391e873c\igd10iumd64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_2085233d391e873c\igd10iumd64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_2085233d391e873c\igd12umd64.dll"
                    Last Error Code:"Not Available"
                    Last Error Code Description:"Not Available"
                    Last Reset:"Not Available"
                    Location:"PCI bus 25, device 0, function 0"
                    Manufacturer:"Intel Corporation"
                    Microsoft DirectX* Version:"DirectX 12"
                    Monochrome:"No"
                    Number of Colors:"4294967296"
                    Number of Video Pages:"Not Available"
                    PNP Device ID:"PCI\VEN_8086&DEV_56A1&SUBSYS_10218086&REV_08\6&2F91B45A&0&00080000"
                    Power Management Capabilities:"Not Available"
                    Power Management Supported:"Not Available"
                    Refresh Rate - Current:"60 Hz"
                    Refresh Rate - Maximum:"75 Hz"
                    Refresh Rate - Minimum:"23 Hz"
                    Resolution:"3840 X 2160"
                    Scan Mode:"Noninterlaced"
                    Service Name:"igfxnd"
                    Status:"OK"
                    Video Architecture:"VGA"
                    Video Memory:"Unknown"
                    Video Processor:"Intel(R) Arc(TM) A750 Graphics Family"
          - "Memory"
               Physical Memory (Available):"26.21 GB"
               Physical Memory (Installed):"32 GB"
               Physical Memory (Total):"31.69 GB"
               - "NODE 1"
                    Capacity:"16 GB"
                    Channel:"DIMM_A1"
                    Configured Clock Speed:"3200 MHz"
                    Configured Voltage:"1200 millivolts"
                    Data Width:"64 bits"
                    Form Factor:"DIMM"
                    Interleave Position:"Not Available"
                    Manufacturer:"Kingston"
                    Maximum Voltage:"Not Available"
                    Memory Type:"Unknown"
                    Minimum Voltage:"Not Available"
                    Part Number:"KF3200C16D4/16GX"
                    Serial Number:"BDE93CDB"
                    Status:"Not Available"
                    Type:"Synchronous"
               - "NODE 1"
                    Capacity:"16 GB"
                    Channel:"DIMM_C1"
                    Configured Clock Speed:"3200 MHz"
                    Configured Voltage:"1200 millivolts"
                    Data Width:"64 bits"
                    Form Factor:"DIMM"
                    Interleave Position:"Not Available"
                    Manufacturer:"Kingston"
                    Maximum Voltage:"Not Available"
                    Memory Type:"Unknown"
                    Minimum Voltage:"Not Available"
                    Part Number:"KF3200C16D4/16GX"
                    Serial Number:"F8A958D6"
                    Status:"Not Available"
                    Type:"Synchronous"
          - "Motherboard"
               Availability:"Running or Full Power"
               BIOS:"1403, ALASKA - 1072009"
               Caption:"Motherboard"
               Chipset:"Intel"
               Date:"05/23/2022 03:00 AM"
               Install Date:"Not Available"
               Last Error Code:"Not Available"
               Last Error Code Description:"Not Available"
               Manufacturer:"ASUSTeK COMPUTER INC."
               Model:"Not Available"
               Part Number:"Not Available"
               PNP Device ID:"Not Available"
               Power Management Capabilities:"Not Available"
               Power Management Supported:"Not Available"
               Product:"PRIME X299-A II"
               Serial Number:"220196981900230"
               Status:"OK"
               Version:"Rev 1.xx"
          - "Networking"
               Intel ® Network Connections Install Options:"Not Available"
               Intel ® Network Connections Version:"Not Available"
               Intel ® PROSet/Wireless Software Version:"Not Available"
               - "Intel(R) Ethernet Connection (2) I219-V"
                    Availability:"Running or Full Power"
                    - "Caption":"Intel(R) Ethernet Connection (2) I219-V"
                         Link:"http://www.intel.com/content/www/us/en/search.html?keyword=Ethernet+Connection+(2)+I219+V"
                    CoInstallers:"Not Available"
                    Default IP Gateway:"192.168.0.1"
                    DHCP Enabled:"Yes"
                    DHCP Lease Expires:"08/04/2023 06:59 PM"
                    DHCP Lease Obtained:"08/04/2023 04:59 PM"
                    DHCP Server:"192.168.0.1"
                    Driver:"e1i65x64.sys"
                    Driver Date:"06/12/2018 12:00 AM"
                    Driver Path:"C:\Windows\system32\drivers\e1i65x64.sys"
                    Driver Provider:"Microsoft"
                    Driver Version:"12.17.10.8"
                    ETrackID:"Not Available"
                    Index:"0001"
                    INF:"net1ic64.inf"
                    INF Section:"E15B8.10.0.1"
                    Install Date:"Not Available"
                    Installed:"Yes"
                    IP Address:"192.168.0.137;fe80::fae5:8c46:a4e1:6b78"
                    IP Subnet:"255.255.255.0;64"
                    Last Error Code:"Not Available"
                    Last Error Code Description:"Not Available"
                    Last Reset:"08/04/2023 12:02 PM"
                    Location:"PCI bus 0, device 31, function 6"
                    MAC Address:"50:EB:F6:B6:0C:A0"
                    Manufacturer:"Intel Corporation"
                    Net Connection ID:"Ethernet"
                    NetCfgInstanceId:"{26656D62-FFFF-49AE-9F53-11B86DDC93A9}"
                    NVM Version:"Not Available"
                    Part Number:"FFFFFF-0FF"
                    PNP Device ID:"PCI\VEN_8086&DEV_15B8&SUBSYS_86721043&REV_00\3&11583659&0&FE"
                    Port:"Not Available"
                    Power Management (Low Power):"Active: Yes, Enable: Yes"
                    Power Management (Wake On LAN):"Active: Yes, Enable: Yes"
                    Power Management (Wake on Magic Packet):"Active: Yes, EnableWakeOnMagicPacketOnly: No"
                    Power Management Capabilities:"Not Available"
                    Power Management Supported:"No"
                    Product Type:"Intel(R) Ethernet Connection (2) I219-V"
                    Service Name:"e1i65x64"
                    Status:"Enabled"
                    Type:"Ethernet 802.3"
                    - "Service Bindings"
                         Client for Microsoft Networks:
                         File and Printer Sharing for Microsoft Networks:
                         Internet Protocol Version 4 (TCP/IPv4):
                         Internet Protocol Version 6 (TCP/IPv6):
                         Link-Layer Topology Discovery Mapper I/O Driver:
                         Link-Layer Topology Discovery Responder:
                         Microsoft LLDP Protocol Driver:
                         QoS Packet Scheduler:
                    - "Settings"
                         *FlowControl:Flow Control:"Rx & Tx Enabled (3)"
                         *InterruptModeration:Interrupt Moderation:"Enabled (1)"
                         *IPChecksumOffloadIPv4:IPv4 Checksum Offload:"Rx & Tx Enabled (3)"
                         *JumboPacket:Jumbo Packet:"Disabled (1514)"
                         *LsoV2IPv4:Large Send Offload V2 (IPv4):"Enabled (1)"
                         *LsoV2IPv6:Large Send Offload V2 (IPv6):"Enabled (1)"
                         *PMARPOffload:ARP Offload:"Enabled (1)"
                         *PMNSOffload:NS Offload:"Enabled (1)"
                         *PriorityVLANTag:Packet Priority & VLAN:"Packet Priority & VLAN Enabled (3)"
                         *ReceiveBuffers:Receive Buffers:"256 (256)"
                         *SpeedDuplex:Speed & Duplex:"Auto Negotiation (0)"
                         *TCPChecksumOffloadIPv4:TCP Checksum Offload (IPv4):"Rx & Tx Enabled (3)"
                         *TCPChecksumOffloadIPv6:TCP Checksum Offload (IPv6):"Rx & Tx Enabled (3)"
                         *TransmitBuffers:Transmit Buffers:"512 (512)"
                         *UDPChecksumOffloadIPv4:UDP Checksum Offload (IPv4):"Rx & Tx Enabled (3)"
                         *UDPChecksumOffloadIPv6:UDP Checksum Offload (IPv6):"Rx & Tx Enabled (3)"
                         AdaptiveIFS:Adaptive Inter-Frame Spacing:"Disabled (0)"
                         ITR:Interrupt Moderation Rate:"Adaptive (65535)"
                         LogLinkStateEvent:Log Link State Event:"Enabled (51)"
                         MasterSlave:Gigabit Master Slave Mode:"Auto Detect (0)"
                         WaitAutoNegComplete:Wait for Link:"Auto Detect (2)"
          - "Operating System"
               .Net Framework Version:"4.0,4.8"
               Boot Device:"\Device\HarddiskVolume1"
               Internet Browser:"Mozilla Firefox, Internet Explorer,11.789, Microsoft Edge,115.0"
               Locale:"United States"
               OS Manufacturer:"Microsoft Corporation"
               OS Name:"Microsoft Windows 10 Pro"
               Other OS Description:"Not Available"
               Page File:"C:\pagefile.sys"
               Page File Space:"5.00 GB"
               Physical Memory (Available):"26.19 GB"
               Physical Memory (Installed):"32 GB"
               Physical Memory (Total):"31.69 GB"
               System Directory:"C:\Windows\system32"
               Version:"10.0.19044 Build 19044"
               Virtual Memory (Available):"28.24 GB"
               Virtual Memory (Total):"36.69 GB"
               Windows Directory:"C:\Windows"
               - "Installed Updates"
                    KB2468871:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2468871:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2468871v2:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2468871v2:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2478063:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2478063:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2533523:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2533523:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2544514:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2544514:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2600211:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2600211:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2600217:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2600217:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB5003791:"Update [10/6/2021]"
                    KB5005699:"Security Update [10/6/2021]"
                    KB5020683:"Update [8/3/2023]"
                    KB5026037:"Update [8/3/2023]"
                    KB5026879:"Update [8/3/2023]"
                    KB5027122:"Update [8/3/2023]"
                    KB5027215:"Security Update [8/3/2023]"
          - "Processor"
               - "Intel(R) Core(TM) i9-9990XE CPU @ 4.00GHz"
                    Architecture:"x64"
                    ATPO:"Not Available"
                    Availability:"Running or Full Power"
                    Caption:"Intel64 Family 6 Model 85 Stepping 4"
                    - "Chipset Name":"Intel(R) Core(TM) i9-9990XE CPU @ 4.00GHz"
                         Link:"http://www.intel.com/content/www/us/en/search.html?keyword=Core+i9+9990XE+CPU+"
                    CPU Speed:"4.01 GHz"
                    Current Voltage:"2.2 volts"
                    Driver:"Not Available"
                    Driver Date:"04/21/2009 12:00 AM"
                    Driver Path:"C:\Windows\system32\drivers\intelppm.sys"
                    Driver Provider:"Microsoft"
                    Driver Version:"10.0.19041.2728"
                    Ext. Family:"Not Available"
                    Family:"Intel Xeon™"
                    FPO:"Not Available"
                    INF:"cpu.inf"
                    INF Section:"IntelPPM_Inst.NT"
                    Install Date:"Not Available"
                    Last Error Code:"Not Available"
                    Level 1 Cache:"14 x 896 KB"
                    Level 2 Cache:"14 x 14336 KB"
                    Level 3 Cache:"19.25 MB"
                    Load:"1%"
                    Manufacturer:"GenuineIntel"
                    Model:"85"
                    Name:"Intel(R) Core(TM) i9-9990XE CPU @ 4.00GHz"
                    Number of Cores:"14"
                    Number of Cores Enabled:"14"
                    Number of Logical Processors:"14"
                    Part Number:"Not Available"
                    Power Management Capabilities:"Not Available"
                    Power Management Supported:"No"
                    Processor ID:"BFEBFBFF00050654"
                    Revision:"21764"
                    Serial Number:"Not Available"
                    Service Name:"intelppm"
                    Status:"OK"
                    Stepping:"4"
                    Version:"Not Available"
          - "Storage"
               - "Samsung SSD 860 EVO 2TB"
                    Capablities:"Random Access, Supports Writing, SMART Notification"
                    Caption:"Samsung SSD 860 EVO 2TB"
                    Cylinder - Total:"243201"
                    Description:"Disk drive"
                    Driver:"Not Available"
                    Driver Date:"06/21/2006 12:00 AM"
                    Driver Version:"10.0.19041.1865"
                    Error Code:"Device is working properly"
                    Firmware Revision:"RVT04B6Q"
                    Heads - Total:"255"
                    Index:"0"
                    INF:"disk.inf"
                    Install Date:"Not Available"
                    Interface Type:"SCSI"
                    Manufacturer:"(Standard disk drives)"
                    Model:"Samsung SSD 860 EVO 2TB"
                    Name:"\\.\PHYSICALDRIVE0"
                    Partitions:"3"
                    Physical Sector Size:"512"
                    PNP Device ID:"SCSI\DISK&VEN_SAMSUNG&PROD_SSD\4&A61BEFE&0&000400"
                    Policies:"Read Retention Priority=EqualPriority, Write Retention Priority=EqualPriority, Scalar Prefetch=Not Available, Block Prefetch=Not Available"
                    SCSI Bus:"0"
                    SCSI LUN:"0"
                    SCSI Port:"0"
                    Sectors - Per Track:"63"
                    Sectors - Total:"3907024065"
                    Serial Number:"S3YVNR0NB01099X"
                    Size:"1.82 TB"
                    Size – Available:"403.26 GB"
                    SMART Attributes:"Self-Test: 160 minutes, OK, Short Self-Test: 2 minutes, OK"
                    Status:"OK"
                    Tracks - Per Cylinder:"255"
                    Tracks - Total:"62016255"
                    - "C:"
                         Availability:"Not Available"
                         Caption:"C:"
                         Compression Method:"Not Compressed"
                         Description:"Local Fixed Disk"
                         File System:"NTFS"
                         Name:"Not Available"
                         Serial Number:"4620E807"
                         Size:"1862.40 GB"
                         Size – Available:"403.27 GB"
                         Status:"Not Available"
                         Volume Dirty:"No"
                    - "SMART"
                         0x05  Reallocated Sector Count:0:"10"
                         0x09  Power-On Hours:2229:"0"
                         0x0C  Power Cycle Count:289:"0"
                         0xB1  Wear Range Delta:4:"0"
                         0xB3  Used Reserved Block Count Total:0:"10"
                         0xB5  Program Fail Count Total:0:"10"
                         0xB6  Erase Fail Count:0:"10"
                         0xB7  SATA Downshift Count:0:"10"
                         0xBB  Uncorrectable Error Count:0:"0"
                         0xBE  Temperature - Current:28° C:"0"
                         0xBE  Temperature - Highest:Not Available:"0"
                         0xBE  Temperature - Lowest:Not Available:"0"
                         0xC3  Hardware ECC Recovered:0:"0"
                         0xC7  CRC Error Count:0:"0"
                         0xEB  Good Block Count:22:"0"
                         0xF1  Total LBAs Written:16079552738:"0"
...#SSU#...

### Description and steps to reproduce [Required]

Start game from desktop shortcut. Game window opens for 10 seconds and closes.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Game cannot start even after reinstalling.

**Comment by TFXGAME** [comment]
Description:
Faulting application name: forza_x64_release_final.exe, version: 0.0.0.0, time stamp: 0x5b171431
Faulting module name: forza_x64_release_final.exe, version: 0.0.0.0, time stamp: 0x5b171431
Exception code: 0xc0000005
Fault offset: 0x0000000001f28dec
Faulting process id: 0x1958
Faulting application start time: 0x01d9c6ddbb48e729
Faulting application path: C:\Program Files\WindowsApps\Microsoft.OpusPG_1.0.125.2_x64__8wekyb3d8bbwe\forza_x64_release_final.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.OpusPG_1.0.125.2_x64__8wekyb3d8bbwe\forza_x64_release_final.exe
Report Id: e78a890c-b6b5-4306-82d0-466b5c8df5c7
Faulting package full name: Microsoft.OpusPG_1.0.125.2_x64__8wekyb3d8bbwe
Faulting package-relative application ID: OpusReleaseFinal

**Comment by TFXGAME** [comment]
Game works only if GPU drivers are uninstalled, but very slowly.

**Comment by Karen-Intel** [comment]
Hey @TFXGAME can you tell us in which GEO are you? :)

Thanks

Karen

**Comment by TFXGAME** [comment]
Europe UTC+2 :)

**Comment by Karen-Intel** [comment]
Hey @TFXGAME unfortunately the game[ is not available in MS Store since 2020 ](https://support.xbox.com/en-US/help/games-apps/game-closures/forza-horizon-3-retirement), which means we're not able to legally purchase it and repro the same behavior you're reporting. 

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/a735a8a1-40b2-435b-b454-d3e34f0323f6)

@IGCIT can you please close this one? The game cannot be legally purchased in MS Store since 2020, thanks

Karen

**Comment by Squall-Leonhart** [comment]
What a nonsense reason to close an issue
 ask in the lab to see if a coworker has it, or set up to get data remotely from a user!

Or do what any other sensible IHV does and ask Microsoft for a key!
you have a devrel contact for a reason.

**Comment by kunit1** [comment]
They're not serious about getting close to %100 compatibility unfortunately. Many issues are closed with a generic "focus on the most popular games" This was also a response on actually popular games. They either under funded as a division or they simply don't care.

**Comment by Squall-Leonhart** [comment]
They are now GPU in handheld systems, they best be funding and hiring people that care.

**Comment by BiZkViT96** [comment]
Good news everyone, there is a fix that makes it possible to run the game.

https://github.com/Yahavcd/FH3ArcFix
