### ISSUE TITLE
Update windows catalog for new drivers

### ISSUE THREAD

**Issue by Danjhop4** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#417]
### Application [Required]

Minecraft

### Processor / Processor Number [Required]

I7-1165g7

### Graphic Card [Required]

Iris xe

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Other Windows build number

Lastest

### Describe the feature [Required]

![](https://cdn.discordapp.com/attachments/1007343453669171353/1137351573320781915/new.png)

as of 14/6/2023 the lastest driver is no we’re near the latest and not every one has admin to update to report bugs can you update windows newest when you post the manual install versions have to use windows update

**Comment by Danjhop4** [comment]
may of updated after this pic

**Comment by Danjhop4** [comment]
Not sure

**Comment by Danjhop4** [comment]
![](https://cdn.discordapp.com/attachments/1007343453669171353/1137351573320781915/new.png)
New picture

**Comment by Gabriela-Intel** [comment]
Hi @Danjhop4. I see you're reporting this for integrated graphics :) We submit a new driver to Windows Update about once every 4 months for integrated.

I'll pass along the feedback to the team to see if there is any way we can up that frequency. Thank you for taking the time to report this!

@IGCIT Please close.

**Comment by Danjhop4** [comment]
@Gabriela-Intel how soon can that be

**Comment by Gabriela-Intel** [comment]
I've passed along that feedback but it's up to the corresponding teams to make a decision on if it is feasible and if so, when that will be done. So I can't really provide a date for that. If we DO hear back on it, I'll follow up again here.

**Comment by Danjhop4** [comment]
@Gabriela-Intel I made this same request it got closed still a issue on 24h2
