### ISSUE TITLE
Little Nightmares II Enhanced Edition - Fatal error upon launch

### ISSUE THREAD

**Issue by Kikuzyu** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#418]
### Checklist [README]

- [x] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Little Nightmares II Enhanced Edition

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel i5 10600k

### Graphic Card [Required]

ASRock Intel Arc A770 Phantom Gaming 8GB 

### GPU Driver Version [Required]

- [X] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[dx_info_9848.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12269222/dx_info_9848.txt)

### Description and steps to reproduce [Required]

Download the game and start it choosing the "Enhanced Edition" option to reproduce the issue.
If the game is started in Normal Edition it plays without issues. I even tried changing the in-game quality settings from Ultra to High to Medium to Low one by one in Normal Edition, to then restart in Enhanced Edition, but to no use.
I can only guess that this is a problem related to UE4, but I am not sure.
Here's the screenshot of the error window:
![Helios Fatal Error](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/111080307/bb26f90b-b6bf-4f1c-b9a2-58effd483ab6)
I read many ways to attempt to fix this issue, from disabling cloud save to deleting the Helios folder in Appdata local, but none worked.
I am not even sure if this issue is related to the gpu drivers, but I figured I'd give it a shot regardless reporting it.
I look forward to updates on this matter.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

I tried all ultra, all high, all medium, all low, but the issue persists.

### Crash dumps [Required, if applicable]

[UE4CC-Windows-3122A64A4183287068B2EFA24C8DBD34_0000.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12269212/UE4CC-Windows-3122A64A4183287068B2EFA24C8DBD34_0000.zip)

**Comment by Karen-Intel** [comment]
Hey @Kikuzyu thank you for your report!

Just tested the game in one of the lab machines and I am unable to repro
After launching the game, I selected 'Little Nightmares II Enhanced Edition"

It would load without issues in my UHD 770 and also in my ARC A750

Please make sure to verify you have the game set in High Performance: System > Display > Graphics
You can look for the game by clicking in browse and looking for the game location under SteamLibrary > SteamApps > Common > Little Nightmares II > EnhancedEdition > Little_Nightmares_II_Enhanced.exe
Click in options and set the game in High performance to make sure it is using your ARC 770

Also, if you haven't, please upgrade your driver using [DDU]  (https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) and try again :)

Last test was done using Gfx v.4577 and the game launched without any issues.

Can you give it a go? Thanks

Karen

**Comment by Kikuzyu** [comment]
> Hey @Kikuzyu thank you for your report!
> 
> Just tested the game in one of the lab machines and I am unable to repro After launching the game, I selected 'Little Nightmares II Enhanced Edition"
> 
> It would load without issues in my UHD 770 and also in my ARC A750
> 
> Please make sure to verify you have the game set in High Performance: System > Display > Graphics You can look for the game by clicking in browse and looking for the game location under SteamLibrary > SteamApps > Common > Little Nightmares II > EnhancedEdition > Little_Nightmares_II_Enhanced.exe Click in options and set the game in High performance to make sure it is using your ARC 770
> 
> Also, if you haven't, please upgrade your driver using [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) and try again :)
> 
> Last test was done using Gfx v.4577 and the game launched without any issues.
> 
> Can you give it a go? Thanks
> 
> Karen

Hello Karen, thanks for your help.
As you suggested I performed a DDU in safe mode, rebooted and let windows reinstall the drivers itself: it installed versions 4314 for Arc and 2111 (I think) for Intel UHD 630.
I then tried to launch the game and surprisingly, it worked, though it was very laggy.
I then performed another DDU in safe mode, this time disabling windows update automatic updates, and after rebooting I reinstalled versions 4577 and 2125 from their respective .exes. Sadly, though, the game now presents the same fatal error as before.
Now I will try to downgrade my UHD 630 drivers to a previous version and see if it helps. I will instead keep the 4577 version for my Arc gpu.
I will update as soon as I'm done testing.
Thank you for your time!

**Comment by Kikuzyu** [comment]
> > Hey @Kikuzyu thank you for your report!
> > Just tested the game in one of the lab machines and I am unable to repro After launching the game, I selected 'Little Nightmares II Enhanced Edition"
> > It would load without issues in my UHD 770 and also in my ARC A750
> > Please make sure to verify you have the game set in High Performance: System > Display > Graphics You can look for the game by clicking in browse and looking for the game location under SteamLibrary > SteamApps > Common > Little Nightmares II > EnhancedEdition > Little_Nightmares_II_Enhanced.exe Click in options and set the game in High performance to make sure it is using your ARC 770
> > Also, if you haven't, please upgrade your driver using [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) and try again :)
> > Last test was done using Gfx v.4577 and the game launched without any issues.
> > Can you give it a go? Thanks
> > Karen
> 
> Hello Karen, thanks for your help. As you suggested I performed a DDU in safe mode, rebooted and let windows reinstall the drivers itself: it installed versions 4314 for Arc and 2111 (I think) for Intel UHD 630. I then tried to launch the game and surprisingly, it worked, though it was very laggy. I then performed another DDU in safe mode, this time disabling windows update automatic updates, and after rebooting I reinstalled versions 4577 and 2125 from their respective .exes. Sadly, though, the game now presents the same fatal error as before. Now I will try to downgrade my UHD 630 drivers to a previous version and see if it helps. I will instead keep the 4577 version for my Arc gpu. I will update as soon as I'm done testing. Thank you for your time!

Update: even downgrading the UHD 630 drivers didn't help.
I will attempt disabling the iGPU entirely and see if it does anything.

**Comment by Kikuzyu** [comment]
I have updates on this matter: surprisingly, I was able to launch the game using drivers 4314. I then tried 4369 and fatal error occurred again.
I will explain more thoroughly: I clean installed 4314, rebooted, opened steam and launched the enhanced version of the game.
I immediately opened task manager to monitor the .exe activity and at first it had and insane 100% CPU spike when launched; with 4369 and up at this moment it would instead crash.
After this spike that lasted around 5-10 seconds, the game window adapted itself and then the game started. I was able to finally play it with the 4314 version of drivers. Differently from what I wrote above, it wasn't laggy at all. 117 consistent FPS, 100% GPU usage.

What could have triggered the crashing behavior in 4369 and up? Are there significant changes between the two versions?

**Comment by Kikuzyu** [comment]
I found another way apart from using older drivers: disabling the iGPU. It seems the UHD 630 plays some role in crashing the game. I will still keep this thread opened as it still involves an Intel GPU.

@Karen-Intel , you said you could run the game using a UHD 770 gpu, so I'm now wondering: are there strong differences between 770 and 630 in terms of compatibility?

**Comment by Karen-Intel** [comment]
Hey @Kikuzyu 

About UHD 770, it uses the same driver ARC uses that's why performance is quite better.
Little Nightmares II was released on 2021, for sure it will have better performance with newer HW and you have confirmed it yourself by testing it only with Intel ARC. About UHD 630, it has moved to [Graphics driver legacy support](https://www.intel.com/content/www/us/en/support/articles/000091662/graphics.html). As the last driver update for this product happened in June 15th 2023, we may have a new driver update for legacy products by EOY.

We could submit a report internally but take in consideration that any report regarding legacy support products will get on queue behind existing issues for newer products. In case you find any issue with your Intel ARC, please let us know.
Hope it helps!

Karen

**Comment by Karen-Intel** [comment]
@IGCIT can you help us close this one? Issue falls in legacy support and not happening in newer products. TY

Karen
