### ISSUE TITLE
Can't get the fans to go to 0%

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#419]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 07.08.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12284714/Intel.SSU.07.08.2023.txt)

### Description and steps to reproduce [Required]

Set the fan curve to be at 0%, the fan will spin most at 800RPM, which is low, but not 0

### Device / Platform

ASUS Prime Z790-P WiFi D4

**Comment by TheWonderfulTartiflette** [comment]
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/eb5fd6d9-69be-447a-82e7-29c3bb5ab993)

**Comment by Karen-Intel** [comment]
Hey @TheWonderfulTartiflette I tried to setup fans with the same configuration you have in the image and they took a couple seconds to fully stop. In your case, they're not stopping at all?

If I'm missing anything, let me know

Karen

**Comment by TheWonderfulTartiflette** [comment]
> Hey @TheWonderfulTartiflette I tried to setup fans with the same configuration you have in the image and they took a couple seconds to fully stop. If I change the Fan Speed Control to automatic they resume spinning. In your case, they're not stopping at all?
> 
> If I'm missing anything, let me know
> 
> Karen

Oh yes my bad sorry, this issue was present on older drivers, not anymore, my bad

**Comment by Arturo-Intel** [comment]
@IGCIT can we close this case? thank you

--r2

**Comment by TheWonderfulTartiflette** [comment]
Sure, sorry

Le jeu. 10 août 2023, 20:34, Arturo-Intel ***@***.***> a
écrit :
