### ISSUE TITLE
Super resolution feature request

### ISSUE THREAD

**Issue by Powermann293** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#421]
### Application [Required]

Arc Control

### Processor / Processor Number [Required]

Ryzen 3700X

### Graphic Card [Required]

A770 16GB

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [X] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

A super resolution feature similar to what's in AMD's Adrenalin drivers. Allowing me to choose a higher resolution to set in Windows than my display's resolution. This can be useful in certain instances like recording a desktop and needing as much resolution to show small parts of the screen as possible.

**Comment by Gabriela-Intel** [comment]
Thanks @Powermann293 for the feedback! I'll pass along the information on this feature request. :)

@IGCIT Please close this one. We'll track the progress of the feedback internally.
