### ISSUE TITLE
Adobe Premiere Pro 2023: Hardware acceleration not working at all

### ISSUE THREAD

**Issue by nyanmisaka** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#424]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Adobe Premiere Pro 2023

### Processor / Processor Number [Required]

AMD Ryzen 7 5700G

### Graphic Card [Required]

Intel(R) Arc(TM) A380 Graphics

### GPU Driver Version [Required]

- [X] 31.0.101.4578
- [X] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12313191/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Adobe Premiere Pro was supposed to take advantage of the Arc graphics card's hardware acceleration during video playback, but it didn't and instead used the CPU. Sometimes this results in 100% CPU usage.

1. Open the Premiere Pro 2023 and create a new project "Untitled".
2. Make sure the hardware acceleration for Intel is enabled in "Edit->Preferences->Media"
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/162b0632-8350-4292-985d-779b0401ae5b)

3. Import any common H.264 or HEVC media in the bottom left corner. And then drop them to the right side. Just in case if you need a sample video. (https://4kmedia.org/sony-camping-in-nature-4k-demo/)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/8dac396b-169a-4b9f-9d48-82a159649388)

4. Click the playback button or drag the progress bar.
5. Watch the usage of Video Decode 0/1 in task manager. And you will see the media engines are not being used. Instead, the CPU is decoding the video.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/1de80289-57b3-4d17-93f6-6a7626b1907d)

**Adobe is listed as a partner in the [Arc graphics brochure](https://www.intel.com/content/www/us/en/products/docs/discrete-gpus/arc/creator.html). Many people buy Arc graphics to work in video editing software such as Premiere Pro. Given that this already works fine on UHD and Xe integrated graphics, I don't think it should be that difficult to fix this.**
![adobe](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/3c51f064-659c-4c9e-b04c-05b8208fa8ac)

**The creator apps on the bug list haven't been cared for in a long time. We need an urgent fix.**
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/c8c1427b-6a3f-4dfa-b83e-37678c1f9fe3)

**Comment by Karen-Intel** [comment]
Hi! Thank you for your report!

Just FYI, our dev team is already aware and working [on this issue ](https://www.intel.com/content/www/us/en/support/articles/000095402/graphics.html) 

Out of curiosity, have you tried with the Adobe Premiere Pro Beta version?  Adobe Creative Cloud > All Apps - Categories > Beta Apps

Thanks

Karen

**Comment by nyanmisaka** [comment]
I tried but it didn't help. Adobe Media Encoder 2023 also has the same problem.

**Comment by Karen-Intel** [comment]
Hey @nyanmisaka actually HW acceleration is working on Adobe Pr Pro Beta version. 
Our article will be updated shortly with this information

![Adobe Premiere Beta 1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/2f7a991b-e107-46d1-8fc3-9f12b390da78)
![Adobe Premiere Beta 2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/418a9e3f-b540-4bae-ab3e-e929bcd7ecac)

Here's how it looks on my end. If I'm missing anything let me know

Karen

**Comment by nyanmisaka** [comment]
Seems like I was using an outdated beta version. I will try again and get back to you.

**Comment by nyanmisaka** [comment]
Confirmed that this should be fixed in the latest Premiere Pro and Media Encoder 2024 Beta.

https://www.pugetsystems.com/labs/articles/intel-arc-gpu-hardware-decoding-and-encoding-performance-in-premiere-pro-24-beta/
