### ISSUE TITLE
Sins of a Solar Empire 2 - Space is Red / Surfaces are Red on play

### ISSUE THREAD

**Issue by n3cron** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#427]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Sins of a Solar Empire 2

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

13700K

### Graphic Card [Required]

UHD 770

### GPU Driver Version [Required]

- [X] 31.0.101.4578
- [X] 31.0.101.4577
- [X] 31.0.101.4576
- [X] 31.0.101.4575
- [X] 31.0.101.4514
- [X] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12329966/igcit_ssu.txt)

### Description and steps to reproduce [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/56698544/8373b9dc-0f7b-4c85-94ec-89f7f6a749f1)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/56698544/ea95c4dc-1cbb-43bf-87d7-72ab16d7c3d9)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/56698544/4915e364-1781-4b15-bee3-f428ea31094b)

This issue happens when you simply play the game, without AMD/Nvidia Cards.
To reproduce is simply play the game with at least an Intel Intel(R) UHD Graphics 770
Users from community have reported to happen on older generations iGPUs as well. (Intel HD/UHD 5xx, 6xx,) and Intel(R) Iris(R) Xe Graphics

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

Any Resolution

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

<img width="704" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/56698544/39682373-6222-446d-8d22-2aa634b46821">
<img width="763" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/56698544/d5487ce3-051c-433a-ab3f-875670023738">
<img width="753" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/56698544/68d6733f-578a-4c3d-9834-e82d3044d56e">

### Crash dumps [Required, if applicable]

The game had no crashes so far, but I did not play it with this issue.

Its not playable under this issue: 
<img width="1279" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/56698544/3e4dafaa-9a76-4101-8b2d-89a7308dc25e">

### Save game

Not required simply start a new Game.

This Issue even happens in the main menu: 
<img width="1279" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/56698544/e1860ea2-7b05-4913-9ed7-e5d8c9761903">

**Comment by Arturo-Intel** [comment]
Hi @n3cron 
I was able to reproduce this issue in a UHD 770
Will continue with the process and create a case to our devs team.

I will keep you posted here if any news comes
--r2

**Comment by Arturo-Intel** [comment]
@n3cron hey! can you try with latest beta driver version? ([101.4826](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html?)) 

https://youtu.be/pWfitjvwqnM
--r2

**Comment by n3cron** [comment]
Hi Arturo,

i updated to the latest beta driver and the issue is solved 

<img width="842" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/56698544/0bf026a4-10f6-4a7a-8e53-a03b0123e4fd">

Thank you! Am I allowed to ask you what has been the reason for this "bug"?

**Comment by Arturo-Intel** [comment]
Thank you for verifing this.
The root cause I dont know exactly, but could it be the changes and fixes for the Dx11/Dx9 support. 

@IGCIT can we close this case, ty

**Comment by n3cron** [comment]
Thanks sase closed.
