### ISSUE TITLE
Flashing when trying to use Virtual Desktop with SteamVR, and cannot launch games

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#429]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Virtual Desktop / SteamVR

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 14.08.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12339578/Intel.SSU.14.08.2023.txt)

### Description and steps to reproduce [Required]

Try to use Virtual Desktop with SteamVR, nothing more

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

N/A

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

N/A

### Device / Platform name

ASUS PRIME Z790-P WiFi D4

### Crash dumps [Required, if applicable]

No crash

**Comment by TheWonderfulTartiflette** [comment]
It would be nice to add an “Other notes” section when filing a report here

For the flashing part, it occurs in SteamVR Home and in the SteamVR tutorial. Only the 3D part is flashing, the overlay (when pressing quickly the menu button) does not flash
A strange thing I've found is that normally the game tracks your head of course, but in those occurrences, it displays a single frame, flashing. For SteamVR Home, it's the menu panel where you spawn, and in the SteamVR tutorial, it's in front of the white couch where you spawn

For the games not opening part, I have 3 VR games, Dirt Rally 2.0, MSFS 2020 and The Lab.
Dirt Rally 2.0 just shows as a 2D image like if I was watching a screen, and displays a single frame. The game on my PC screen is running, but on my Quest with VD, it's a still frame
For MSFS, I don't remember what went wrong, but I can't play it in VR
For The Lab, it just does not launch

**Comment by TheWonderfulTartiflette** [comment]
[Reddit post that I created in which I asked for help](https://www.reddit.com/r/OculusQuest/comments/15nbn3o/i_cannot_do_anything_with_vd/)
The creator of VD says here that it may be Intel's fault in their drivers
[How it looks in the headset](https://1drv.ms/v/s!AmnzYyniwxuygaNqvwd0JV-BMkWmLg?e=XIP16j), and the [SteamVR performance graph](https://imgur.com/a/Zt1ySNP)

**Comment by PetanoCZ** [comment]
I have same issues on different platform. I am happy to help once you need me. Also replied in #425
