### ISSUE TITLE
Not a Feature Request, its a Release Notes Request :) Arc A770 new V-Bios with Driver Version 31.0.101.4644

### ISSUE THREAD

**Issue by Darklegion1978** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#431]
### Application [Required]

Release Notes

### Processor / Processor Number [Required]

Ryzen 5 5600X

### Graphic Card [Required]

Intel Arc A770 Phantom Gaming D 8GB OC

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

I have seen, that after installing the new WHQL Driver 31.0.101.4644, also a new V-Bios was installed on the Card.

The old V-Bios was 20.1053.0 and now the Arc Control and GPU-Z shows a Version of 20.1064.0

I can find nothing about it in the release notes. 

Can someone pls tell me whats changed, differences, why the V-Bios was updated?
And maybe it could be postet also in the Release Notes, would be a good way ;)

Thanks a lot and Greetings

**Comment by Darklegion1978** [comment]
![Screenshot 2023-08-16 065350](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/123353653/51d1bde5-8c01-4a5e-b7d5-bd86fcc36bfc)

**Comment by BiZkViT96** [comment]
Not only does this Game On driver release support hot new games for August, it also upgrades the firmware on some Intel Arc graphics cards. This latest version brings stability improvements, better fan behavior, bug fixes, and better compatibility with HDMI connections.

https://game.intel.com/story/intel-arc-graphics-game-on-driver-madden-nfl-24-wayfinder/

**Comment by Darklegion1978** [comment]
Thanks a lot @BiZkViT96
