### ISSUE TITLE
Guild Wars 2 performance loss since switch to Chromium Embedded Framework

### ISSUE THREAD

**Issue by Ramontique** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#432]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Guild Wars 2

### Processor / Processor Number [Required]

12th Gen Intel(R) Core(TM) i3-12100F

### Graphic Card [Required]

Intel Arc A750 Challenger D 8GB OC

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12359072/igcit_ssu.txt)

### Description and steps to reproduce [Required]

In April ArenaNet switched the embedded framework used for the in-game trading post from Coherent to Chromium.

This causes up to 50% frame loss on my Intel Arc A750. This is most noticeable in "heavy" areas.

As a temporary solution you could use the command line parameter -usecoherent to force Guild Wars 2 to use the old embedded frame work.

With Coherent: https://imgur.com/HloQrDZ
With Chromium: https://imgur.com/MHEwAVK
(note that I've capped the in-game fps at 60. Without the cap the Coherent version was running around 83 fps)

However in July ArenaNet removed Coherent from the game.

I have reported this issue back in April (and a couple of times after that) on the official Guild Wars 2 forums but it got ignored.

It seems like the way that ArenaNet implemented the Chromium Embedded Framework is causing excessive overhead or is disabling previous optimizations that Intel made for Guild Wars 2 within the Arc drivers.

Seeing how the new expansion will be released next week (Tuesday August 22 2023) it would be really nice if Intel Arc users could enjoy this game once again in it's former/full glory.

### Device / Platform

N/A It's a custom build system

**Comment by Arturo-Intel** [comment]
hi @Ramontique 
Can you share me the post created in the ArenaNet forum?
This can help us to get a good estimated player base and push this case through the priority pipeline

-- r2

**Comment by Ramontique** [comment]
Hallo @Arturo-Intel 

Here's my original post from April 18 2023: 
[https://en-forum.guildwars2.com/topic/129974-chromium-causing-20-fps-loss-in-bussy-areas-on-intel-arc/#comment-1949019](url)

This is the post from July 18 2023 (my post got merged with another post, mine is #3):
[https://en-forum.guildwars2.com/topic/134063-usecoherent-and-dx9-no-longer-working-with-patch-merged/](url)

My name is Ramontique.9852 on the ArenaNet forum.

If you require further assistance I'll be glad to help

**Comment by GottaSlay** [comment]
I didn't get to try out Coherent with Intel Arc nor have I posted on the forums but I can certainly say that the FPS is strangely low on my A770+5800X3D setup as well. getting the exact same FPS at the same spot as OP. Game is utilizing about 50% of the GPU

**Comment by Ramontique** [comment]
This might be related or not. Changing my power settings in Windows 11 has a big effect on the fps.

This is with the power plan set to "Power saver":
https://i.imgur.com/WQuYP88.jpeg

And this is with the power plan set to "High Performance" ("Balanced" has a similar effect):
https://i.imgur.com/OJboy44.jpeg

Not only is my CPU speed increased a lot but also my GPU activity goes up.

This doesn't directly explain why Guild wars 2 with CoherentUI had a much better frame rate than with Chromium Embedded Framework.

I hope this information might help.

**Comment by Arturo-Intel** [comment]
@Ramontique 
Using driver 101.5081 I was getting 144fps (capped to 60 on cinematics) with the default configuration (no change on the graphic engine used), I assume it was using Chromium engine. Is there a way to verify this?

-- r2

**Comment by Ramontique** [comment]
> @Ramontique Using driver 101.5081 I was getting 144fps (capped to 60 on cinematics) with the default configuration (no change on the graphic engine used), I assume it was using Chromium engine. Is there a way to verify this?
> 
> EDIT: was using HIGH setup on graphics and 2560x1440 res
> 
> -- r2

The issue seems to be fixed with driver version 31.0.101.4952 which contained Guild Wars 2 specific fixes:

Guild Wars 2* (DX11)
Up to 53% average FPS uplift at 1080p with Ultra settings

It's only under the most extreme situation where "janky" frame time is a bit noticeable. This includes heavy crowded situations in World vs World and meta events during the new maps. However this might actually be a CPU issue because I'm only running on a i3 12100f.

**Comment by Arturo-Intel** [comment]
@Ramontique thx for the confirmation

Will close this

**Comment by Arturo-Intel** [comment]
Ok. thank you for the confirmation @Ramontique .
Will close this case now. 

Please open a new case if this or another behavior comes up with this game.

-- r2
