### ISSUE TITLE
expand the "Known Issues" section in the release notes

### ISSUE THREAD

**Issue by Xamrica** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#434]
### Application [Required]

Intel website - Driver release notes

### Processor / Processor Number [Required]

Any

### Graphic Card [Required]

Any

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [X] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Add all verified issues on Github and Intel Forums to the "known issues"-section of the driver release notes.
That would greatly help people to see if an issue is already been worked on.
TY

**Comment by Karen-Intel** [comment]
Hi @Xamrica thank you for your suggestion

I'm already taking notes and yeah the more info the better. Hopefully we will see some changes soon!

Karen

**Comment by Gabriela-Intel** [comment]
Like Karen mentioned, thanks for the feedback! We'll pass it along to the team that works on the driver Release Notes.

@IGCIT Please close this one.
