### ISSUE TITLE
T

### ISSUE THREAD

**Issue by Danjhop4** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#435]
### Application [Required]

T

### Processor / Processor Number [Required]

T

### Graphic Card [Required]

T

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Other Windows build number

T

### Describe the feature [Required]

T

### Additional notes

T

**Comment by jpovixwm** [comment]
T
