### ISSUE TITLE
outdated installation_readme.txt

### ISSUE THREAD

**Issue by Vipitis** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#436]
### Application [Required]

Intel Graphics Driver installer

### Processor / Processor Number [Required]

i5 6600K

### Graphic Card [Required]

A750 LE

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [X] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

If you download the driver installer, and rename the `.exe` to `.7z` you can open and extract it's components. This step was recommended to me for just installing Arc Control (if you previously hadn't checked in for example, but the IDSA requirement seem to be fixed .. couldn't test it myself). There is also three text files:
* `licneses.txt`
* `readme.txt`
* `installation_readme.txt`

My issues are with the 3rd file. It includes Section `VI.   INSTALLATION SWITCHES` which details various command line arguments you can call with the `installer.exe` and what I found made me really happy. For example you can specify a language for the installer which is one of the features I was looking for. Sadly the instructions are incorrect (like there are no hex codes at the top). 

It also looks like the actual information is outdated if you run the installer and look at it's built in `--help`.

Could you please update the readme and provide clearer instructions for running the installer with custom behavior.

**Comment by Karen-Intel** [comment]
Hey @Vipitis let me find out! I will keep you posted here

Karen

**Comment by Gabriela-Intel** [comment]
@Vipitis Thanks for reporting this! I was able to successfully change the language of the installer by using -g <lcid>.

The lcid for the supported languages are:
ar-SA,cs-CZ,da-DK,de-DE,el-GR,en-US,es-ES,fi-FI,fr-FR,he-IL,hr-HR,hu-HU,it-IT,ja-JP,ko-KR,nb-NO,nl-NL,pl-PL,pt-BR,pt-PT,qps-Ploc,ro-RO,ru-RU,sk-SK,sl-SI,sv-SE,th-TH,tr-TR,uk-UA,zh-CN,zh-TW

I'll let the installer team know about this so it can be updated. Thanks so much for reporting!! Do you mind if we close this one out?

**Comment by Vipitis** [comment]
hey @Gabriela-Intel glad to hear it's been looked at. 

Feel free to close once the readme has been updated and shipped with the next driver bundle.
the `installation_readme.txt` (to some degree the readme.txt as well) is outdated in more respect then just the listed language codes... (from driver 4900 bundle)
for example:
- **Platforms** does not list 14th Gen products
- **INSTALLATION INSTRUCTIONS** mentions you can download a .zip file (no longer possible since February)
- **VI.   INSTALLATION SWITCHES** does not mention `-p`, `-f`, `-p`, `-u`, `--nodrv`, `--ver`, `--help` (which doesn't work, but you can get the help print via an incorrect flag), `--res`, `--unsigned`, `--outputFullLog`, `--noExtras`.

If you are providing the users with instructions, ensure they are up to date with the software that ships. If any of those options aren't meant to be exposed to users, consider hiding them from the error print.

**Comment by Gabriela-Intel** [comment]
Sorry for the late reply on this @Vipitis. A few changes to the installation_readme have already been implemented since I last responded. There's a few more coming our way soon, so do note that it isn't fully updated just yet. 

I'll post here again once I see those changes are done.

**Comment by Gabriela-Intel** [comment]
@Vipitis Our [latest driver](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html?) (published today) should include all of these updates. Can you please take a look? :)

**Comment by Vipitis** [comment]
thanks, looks a lot better. Will wait for the next table driver release to actually try this out. Feel free to close this issue.

**Comment by Gabriela-Intel** [comment]
Thanks for confirming!

@IGCIT Proceed with closing.

**Comment by Vipitis** [comment]
Finally had a chance to try it. Flags seem to not work with the self extracting installer. So you have to manually extract it yourself, the. Run the `installer.exe` with flags.
