### ISSUE TITLE
iRacing very low performance

### ISSUE THREAD

**Issue by jacob1218** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#438]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

iRacing

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

iRacing's launcher (game is also available through Steam)

### Processor / Processor Number [Required]

AMD Ryzen 5 3600X

### Graphic Card [Required]

Intel ARC A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12380837/ssu.txt)

### Description and steps to reproduce [Required]

Match the settings below exactly for the reproduction of the results, and you do need to set it exactly like this in both the graphics and replay tab.
[pmcap-iRacingSim64DX11.exe-230818-073841.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12380872/pmcap-iRacingSim64DX11.exe-230818-073841.zip)

Replay is linked here. Start in the race session and use the #12 car (last place) in the cockpit camera. If the replay doesn't load, ensure you have the ARCA Menards Chevrolet Impala and Homestead Miami Speedway purchased and installed.
https://cdn.discordapp.com/attachments/1142105912207745156/1142108228851863623/subses60353811.7z

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/6559034/051e8544-ac52-431b-bfd9-80a0c47731da)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/6559034/ad54624c-74b5-4074-ae2c-bdfd8439751f)

**Comment by Karen-Intel** [comment]
Hey @jacob1218 ty for your report!

Noted, allow us some time to debug in our lab machines and in case we have questions/results we will get back to you. Talk to you soon!

Karen

**Comment by Ilya-intel** [comment]
@jacob1218 
I've tried the game with settings provided and gives me stable FPS without any lags. Could you try uninstall previous graphics drivers using DDU and install latest available from here: https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html

![iracing3](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/bbcfe2ed-1a82-465d-b77b-08e77a716fbf)
![iracing2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/8319f94f-ca30-4019-b60a-ebc4a0ab4a36)
![iracing](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/0002a5c9-ef27-4189-aca5-e4c78aa45410)

**Comment by Ilya-intel** [comment]
Hi @jacob1218 ,
Have you tried latest driver?

**Comment by Ilya-intel** [comment]
@IGCIT 
Case seems to be abandoned. Please close it.
