### ISSUE TITLE
Intel PresentMon Beta graphs autoscales up, but not down

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#439]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel PresentMon Beta

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 18.08.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12383629/Intel.SSU.18.08.2023.txt)

### Description and steps to reproduce [Required]

Try to use PresentMon with the frametime graphs. Make them go really high for a sec (like by changing a graphical setting), and you'll see that it won't go down, even though nowhere in the graph now gets even closer to that max value of the right axis
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/3ab68e99-b07e-4eeb-ab8f-0d2cf59030a6)
In this screenshot, I've enabled path tracing without any XeSS, which resulted in the worst frametimes you could imagine, they went up to around 230ms, but I've disabled since 5 minutes ago, and the scale doesn't go down, which makes the graph reading impossible as I'm now trying to see a difference of 0.5ms, in a graph axis that goes up to 109ms

### Device / Platform

ASUS Prime Z790-P WiFi D4

**Comment by abrfilho** [comment]
I tried to replicate here, the graph scaled down as soon as the high values disappeared from the screen.

The program is still beta, when I tried to replicate here, at first it didn't detected the process, I had to close PresentMon and open again, the worked without a problem.

**Comment by Karen-Intel** [comment]
> I tried to replicate here, the graph scaled down as soon as the high values disappeared from the screen.
> 
> The program is still beta, when I tried to replicate here, at first it didn't detected the process, I had to close PresentMon and open again, the worked without a problem.

Same happened to me, I will add this behavior to a new report anyways :) Ty

Karen

**Comment by TheWonderfulTartiflette** [comment]
Along with fixing the not scaling down issue, I think it would be really nice to have the option to always make the graphs start at 0. Because right now, in FH5, the frametime graph is scaled at 6-10ms, which makes the GPU Busy line look like it's miles away from the frametime line, misleading the user into thinking that the game isn't GPU-limited

**Comment by Karen-Intel** [comment]
Hi guys! Just got info regarding Present Mon:
The team would like to have everything centralized in a single GitHub so they requested us to help us to submit any PM issue in their [GitHub issues forum](https://github.com/GameTechDev/PresentMon/issues)
In the meantime, we will be closing this case. @IGCIT could you do the honors please? TY

Karen
