### ISSUE TITLE
v101.4644 breaks DP output

### ISSUE THREAD

**Issue by pcslide** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#440]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

windows 10

### Processor / Processor Number [Required]

Ryzen 5500

### Graphic Card [Required]

Asus DG1

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12384825/igcit_ssu.txt)

I had to use a remote connection to generate an ISSU report, below is display info. with driver v.101.4578
Computer:
          - "Display"
               Intel ® Graphics Driver Version:"Not Available"
               - "Intel(R) Iris(R) Xe Graphics"
                    Adapter Compatibility:"Intel Corporation"
                    Adapter DAC Type:"Internal"
                    Adapter RAM:"1.00 GB"
                    Availability:"Running or Full Power"
                    Bits Per Pixel:"32"
                    - "Caption":"Intel(R) Iris(R) Xe Graphics"
                         Link:"http://www.intel.com/content/www/us/en/search.html?keyword=Iris+Xe+Graphics"
                    CoInstallers:"oem1.inf,iDG1D_w10_DS,Internal,Intel(R) Iris(R) Xe Graphics Family"
                    Color Table Entries:"4294967296"
                    Dedicated Video Memory:"Not Available"
                    Driver:"igdkmdnd64.sys"
                    Driver Date:"07/26/2023 08:00 AM"
                    Driver Path:"C:\windows\system32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_fc4d3a092020e913\igdkmdnd64.sys"
                    Driver Provider:"Intel Corporation"
                    Driver Version:"31.0.101.4578"
                    INF:"oem1.inf"
                    INF Section:"iDG1D_w10_DS"
                    Install Date:"Not Available"
                    Installed Drivers:"C:\windows\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_fc4d3a092020e913\igdumdim64.dll,C:\windows\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_fc4d3a092020e913\igd10iumd64.dll,C:\windows\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_fc4d3a092020e913\igd10iumd64.dll,C:\windows\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_fc4d3a092020e913\igd12umd64.dll"
                    Last Error Code:"Not Available"
                    Last Error Code Description:"Not Available"
                    Last Reset:"Not Available"
                    Location:"PCI bus 3, device 0, function 0"
                    Manufacturer:"Intel Corporation"
                    Microsoft DirectX* Version:"11.X"
                    Monochrome:"No"
                    Number of Colors:"4294967296"
                    Number of Video Pages:"Not Available"
                    PNP Device ID:"PCI\VEN_8086&DEV_4908&SUBSYS_80001043&REV_01\6&2292FF2F&0&00080009"
                    Power Management Capabilities:"Not Available"
                    Power Management Supported:"Not Available"
                    Refresh Rate - Current:"59 Hz"
                    Refresh Rate - Maximum:"59 Hz"
                    Refresh Rate - Minimum:"59 Hz"
                    Resolution:"2560 X 1440"
                    Scan Mode:"Noninterlaced"
                    Service Name:"igfxnd"
                    Status:"OK"
                    Video Architecture:"VGA"
                    Video Memory:"Unknown"
                    Video Processor:"Intel(R) Iris(R) Xe Graphics Family"
...#SSU#...

### Description and steps to reproduce [Required]

Used DDU to remove the old driver
Installed v.4644
This was how my display looked and I had to use a remote connection to generate an ISSU report
Removing the driver and a system restart get the display back to normal.
FYI, I use an Apple Mini DisplayPort to Dual-Link DVI Adapter to connect my display, the display is totally fine with v101.4578 under windows.  Similar issues happened in some versions of v101.****  drivers, but not before v.101.1631, not in v.101.3959, not after v.101.4255.
I hope this time, we can get to the bottom of why this issue was reintroduced the third time, literally.  Cause, I have had similar issues with this card in Linux with both Kernel driver and Intel's DKMS driver to this day.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/59794570/ddd5385f-7d4a-46ca-b52b-41c91af0c509

**Comment by pcslide** [comment]
From ISSU report, it seems, with driver v101.4644, the graphic card did not detect resolutions supported by my display correctly.  My display supports 2560 X 1440 input only, yet  with driver v.4644, the graphic card use 1920 X 1080 as its default output.   I knew most 1440p display on the market works with a lower resolution as an input, unfortunately, mine doesn't.

**Comment by pcslide** [comment]
Brand is JOINASIA  and model is E270IPS.  To clarify, with v.4644, the display works fine until Windows starts to load, and it works  in safe mode in Windows.
Here is its EDID(I didn't touch anything)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/59794570/16ffeb97-875e-466f-abdc-e1839e4e7c1f)

**Comment by pcslide** [comment]
On which version of the driver would you want me to run dxdiag?

**Comment by Arturo-Intel** [comment]
Would be helpful if you share both: 4644 and the latest one where it was working well

**Comment by pcslide** [comment]
@Arturo-Intel 
[DxDiag_start_blindfold@101.4644.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12423103/DxDiag_start_blindfold%40101.4644.txt)
[DxDiag_from_remote@101.4644.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12423105/DxDiag_from_remote%40101.4644.txt)
[DxDiag@101.4578.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12423106/DxDiag%40101.4578.txt)

**Comment by fancycookin** [comment]
Seems similar to our issues over at #433

**Comment by Arturo-Intel** [comment]
@pcslide Can you try with the latest version? (101.4885)

--r2

**Comment by pcslide** [comment]
@Arturo-Intel  This issue was resolved with version 101.4887
