### ISSUE TITLE
Presentmon.exe won't show CPU Temp or Power, other system details

### ISSUE THREAD

**Issue by gargamel314** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#441]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel PresentMon 

### Processor / Processor Number [Required]

i7-13700K

### Graphic Card [Required]

Intel Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU - Intel PresentMon.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12386323/SSU.-.Intel.PresentMon.txt)

### Description and steps to reproduce [Required]

Present Mon is such a cool utility! It won't show me a lot of details that aren't directly related to my A770, such as: CPU Temperature, CPU Power, or anything regarding the PSU. I'm particularly concerned about the CPU Temperature. MSI Afterburner and HWiNFO64 have no trouble displaying these. Am I missing something?

No real steps to reproduce other than just starting up an application and PresentMon. The image I am posting is from Topaz Video Enhance AI during a render (that will probably fail because that bug isn't fixed yet).  Notice how CPU Temp and CPU Power come back as "NA" though the Utilization and Frequency show just fine. 

![Screenshot 2023-08-19 125138](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/124757309/9a88e769-2a4a-4044-96ad-933a369a1ae5)

### Device / Platform

ASUS Strix Z690-A D4

### Crash dumps [Required, if applicable]

N/A - no crashes, just errors.

**Comment by Karen-Intel** [comment]
Hey @gargamel314 nice to see you around again!

Yep, I could repro the Widgets for CPU Power and Temperature showing NA (In readout mode or Graph)
I will keep on checking the other fields in case I find other ones showing as NA.
Allow me to report this internally and provide any updates here so let's keep the post open! Ty as always for your help :)

Karen

**Comment by gargamel314** [comment]
Hooray! Thank you, you are superheroes!

**Comment by Karen-Intel** [comment]
Hi @gargamel314  Just got info regarding Present Mon:
The team would like to have everything centralized in a single GitHub so they requested us to help us to submit any PM issue in their [GitHub issues forum](https://github.com/GameTechDev/PresentMon/issues)
In the meantime, we will be closing this case. @IGCIT could you do the honors please? TY

Karen
