### ISSUE TITLE
Adaptive Tessellation causes DX11 games to crash

### ISSUE THREAD

**Issue by Azonnali** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#442]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Hunt: Showdown

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5600

### Graphic Card [Required]

A770 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12387992/Report.txt)

### Description and steps to reproduce [Required]

Play Hunt: Showdown (also tested this with Genshin Impact - if I should open another issue let me know) and turn on Adaptive Tessellation in the Arc Control Panel (I left it at the default 50 %). The games crash after a random time (screen freezes, sound still plays and after a while it closes). Every DX12 title I have doesn't crash with Adaptive Tessellation turned on so it seems to be a dx11 issue. Not every dx11 game seems to be affected though as Valorant runs fine.

Turn Adaptive Tessellation off and it runs without issues.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Resolution: 2560x1440
Window Mode: Fullscreen Window
Render Resolution Scale: 85
Gamma: 1.0
VRAM Usage Target: 80
Global Graphics Quality: Custom
Object Quality: High
Texture Quality: High
Texture Filtering: 16x
Anti Aliasing: SMAA 2TX
Lighting Quality: High
Shadow Quality: High
Effect Quality: High
Post-Process Quality: High
Particle Quality: High
Performance Stats: Warning Icons Only
VSync: Off
Max FPS: 60
Depth of Field: on
Motion Blur: off
Surface Format Optimization: Off
Toggle GPU Tesselation: off
Use 2 Pass Rendering: on
Use 2 Pass Lighting; on

### Device / Platform name

Windows 11

**Comment by Ilya-intel** [comment]
@Azonnali 
I've tried running Hunt for several hours and haven't face crash or freeze.
Do you enable Adaptive Tessellation as a Global Setting or apply it to the specific game profile?
Also, there is a new driver release available, could you try it? (https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)

**Comment by Azonnali** [comment]
I enable it as a global setting. I clean installed the driver with DDU and haven't had a crash in the 3 matches I played since but I'll keep testing - also with Genshin.

**Comment by Azonnali** [comment]
After some testing: With the latest driver Hunt doesnt crash. Reinstalled the old driver and it crashes again. But as it is fixed I will close.
