### ISSUE TITLE
Parallel-rdp Texture Glitches

### ISSUE THREAD

**Issue by Azonnali** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#443]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Ares

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

Ares Emulator

### Processor / Processor Number [Required]

Ryzen 5600

### Graphic Card [Required]

A770 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12388001/Report.txt)

### Description and steps to reproduce [Required]

Every N64 Emulator using parallel-rdp as a plugin for the Video interface (VI) emulation has texture issues with Arc. 

The performance is fine but textures do not go where they should. 
(See issue https://github.com/Themaister/parallel-rdp/issues/54 I opened there).

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/37149444/6d3be963-dc3c-4296-a913-892a8e967164)

The image is from SM64 but every N64 game like the free Floppy Bird version have this issue. 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

320x240

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Default settings, you can not change the settings in ares anyway.

### Device / Platform name

Windows 11

**Comment by IGCIT** [comment]
Hi,
please contact parallel-rdp developer about this, and if the developer verifies this as driver fault, an issue can be opened by parallel-rdp developer with in-depth details and sample code to reproduce.

thanks for your understanding

**Comment by freak2fast4u** [comment]
It could very well have something to do with this (straight from the parallel-rdp readme) : 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/43045fd1-2a2b-4f36-9f54-c352daf16a54)

I'm not sure who's job it is to implement such data "padding" in this case (intel driver devs vs game engine/emulator devs), but the parallel-rdp author specifically stated there's an edge case for intel under windows. 

Questions to the intel devs : would this break compatibility on your end to implement in the driver directly ? Is this in your range of responsibility to begin with ? 

In any case, I've reproduced this issue, be it with simple64 or RetroArch's Parallel-RDP N64 core.
