### ISSUE TITLE
CS:GO freezes randomly

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#444]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Counter-Strike: Global Offensive

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 20.08.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12388559/Intel.SSU.20.08.2023.txt)

### Description and steps to reproduce [Required]

Play CS:GO, on any map, any game mode. The display freeze happens every 10 hours of playtime I'd say, but this is extremely problematic because ranked games in CS:GO are really important games, and they tend to be long, like an hour.

I can still hear the game running in the background, but the CPU and GPU are not being used at all in the task manager (GPU at 4% when normally it's at 95% when playing CSGO). No CPU core is maxed out, when normally 3 or 4 are maxed out when playing CSGO.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Everything to Max

### Device / Platform name

ASUS PRIME Z790-P WiFi D4

### Crash dumps [Required, if applicable]

The game doesn't crash, but was still able to get this from eventvwr : https://drive.google.com/file/d/1Mbqx2YC0U5Ge4Tkv5wyQddiYs8HESkPc/view?usp=sharing

**Comment by TheWonderfulTartiflette** [comment]
Steam crashes as well

**Comment by TheWonderfulTartiflette** [comment]
And now this is happening every 20 minutes, making the game unplayable

**Comment by TheWonderfulTartiflette** [comment]
And even in Windowed mode

**Comment by TheWonderfulTartiflette** [comment]
.dmp file for it btw : https://drive.google.com/file/d/1MiJ2HgukChoaNrbdy3ewyLaksExsQcej/view?usp=sharing
May not be related to the exact event viewer file I linked, but the .dmp is still linked to the same kind of CS:GO crash

**Comment by freak2fast4u** [comment]
For the first time ever today since I own my Intel Arc A770 card, CS:GO freezed on me exactly like described above, using driver 101.4644. 

I had a freezeframe of whatever was left on the screen at that moment, but the game was still "working" (I would hear the game audio and my teammates yelling down the microphone "where are you ??" :D).

The closest thing I could find related to that crash/freeze is a kernel dump I found in C:\Windows\LiveKernelReports\WATCHDOG\ with some dxgmms2/dxgkrnl references : 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/f23b3dab-0ed5-44b2-8b85-edf38ace2ed0)

Here's the full kernel dump : 
[WATCHDOG-20230826-0025.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12444054/WATCHDOG-20230826-0025.zip)

Fellow SSU report : [igcit_ssu_20230826_csgocrash_anon.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12444058/igcit_ssu_20230826_csgocrash_anon.txt)

**Comment by TheWonderfulTartiflette** [comment]
And here's what Steam looks like just after the game crashes : 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/4014d3d8-9ea0-44d8-b18a-2e8d92672c3f)

**Comment by freak2fast4u** [comment]
Even though I encountered this specific problem several times at the same period I commented initially, I haven't encountered this specific problem for a while. @TheWonderfulTartiflette, does this still happen for you ?

**Comment by TheWonderfulTartiflette** [comment]
@freak2fast4u nope, but I got to say that I haven't played CSGO a lot recently. Shall I close this issue, and reopen it if I encounter the freezes again?

**Comment by IGCIT** [comment]
> Shall I close this issue, and reopen it if I encounter the freezes again?

yes
