### ISSUE TITLE
Tearing mitigation mode: Smart VSync not functional on several titles

### ISSUE THREAD

**Issue by WouterNed** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#445]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Call of the Sea | A Short Hike | Hardspace: Shipbreaker

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel i5-13400F

### Graphic Card [Required]

Intel Arc A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [x] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [X] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSULOG.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12389346/SSULOG.txt)

### Description and steps to reproduce [Required]

The Smart VSync mode is not functional for me for the games that were currently installed on my PC and thus the GPU runs uncapped and at a 100% load. These titles are: A short Hike, Call of the Sea, Hardspace: Shipbreaker. This means ~1200fps, ~400fps and ~230fps for these games in their menus, respectively. I would expect it to be a steady 75fps, matching my monitor refresh rate.

- The game is added in Intel ARC Control, and in the dropdown menu for the Tearing Mitigation Mode, Smart VSync is selected. This is also applied globally, but I thought this was a more surefire way to force the setting (the issue was also present before adding the game to ARC Control, being on the global setting).
- The game is started, and Call of the Sea and Hardspace: Shipbreaker begin to run uncapped. A short Hike has VSync enabled by default in the ingame graphics settings, but will also run uncapped when VSync is disabled ingame.
- When selecting the Tearing Mitigation Mode "VSync On" for these games, it still runs uncapped for Call of the Sea and Hardspace: Shipbreaker, but strangely enough it works for A short Hike, bring the FPS back to 75Hz.

Fullscreen/Borderless windowed didn't make a difference in A Short Hike

For these games i can just enable the ingame VSync, it's pretty much guaranteed to stay above 75Hz anyway, but for other titles I'd like to take advantage of my freesync capable monitor. So the Smart VSync mode would be ideal, VSync limiting the FPS to 75Hz, but if it's lower than that the Variable Refresh Rate kicks in until 48Hz. The Variable Refresh Rate setting  doesn't make a difference if it's enabled or disabled by the way.

[Edit: Tried running A short Hike in Vulkan through DXVK, as the titles I tried all used DX11, and it still was uncapped despite being in the 'Smart VSync' mode.]

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![Screenshot (2)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/52256913/ace5195c-1d04-4eb3-9658-37835ed3f79d)
![Screenshot (3)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/52256913/ec0d3bbb-c3ba-4ac8-9663-ce765c398951)
![Screenshot (4)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/52256913/6f54a326-dc1f-4718-a800-5fde9db077f8)
Hardspace: Shipbreaker doesn't have a graphics menu in the title screen, but I'd assume VSync is disabled ingame since it's running uncapped

**Comment by szmigieldesign** [comment]
I've never been able to use v-sync other than the regular on or off in multiple titles, with turning the v-sync on in Arc Control resulting in very poor performance (in contrast to simply setting v-sync in game without forcing it in the panel).

**Comment by Ilya-intel** [comment]
@WouterNed 
I'll try to help you with this case.
Just give me some time to get all this games and try to replicate the reported behavior.

**Comment by Ilya-intel** [comment]
@WouterNed 
I've tested all three titles and Smart V-Sync seems to work OK.
Could you test latest driver available?
https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html

![ArcC](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/6a2afc25-5339-43eb-8154-ee4a653ddb4e)
![AShortHike](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/ff9ee104-e13b-4c9f-b45a-ccf71a560b10)
![CallOfTheSea](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/a4e19d56-73e0-4eb3-8a20-9ed5bf9c500b)
![Hardspace](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/3b4d75b8-8c06-400a-845c-88b82664b882)

**Comment by WouterNed** [comment]
Hi! I just installed the latest drivers, clean install, and unfortunately this issue persists. Tried setting my monitor to 60Hz in windows, but it remains uncapped, unfortunately.

There has been a development though, I didn't test it before switching to the new drivers, but the setting "VSync On" now works in Hardspace: Shipbreaker and Call of the Sea, but doesn't on A Short Hike, the opposite of what I previously experienced.

Is there anything else that I can try to help narrow the issue down?

**Comment by Ilya-intel** [comment]
@WouterNed 
Do you have any applications that might interfere with Arc Control? Like Nvidia Control Panel or AMD Software?
Also, have you tried reinstalling the drivers using DDU tool?

**Comment by WouterNed** [comment]
Hi! No, not that i know of. It's a new build, so i did a fresh install and haven't installed any nvidia or amd card. Also no antivirus besides windows defender. I'll try reinstalling the drivers using DDU when i'm home.

**Comment by WouterNed** [comment]
(Nor did i install the software associated with those cards)

**Comment by WouterNed** [comment]
Ok, I uninstalled the drivers using DDU, and subsequently installed the newest (.4676) drivers. All 3 now are capped when using the option of "VSync On", however they are unfortunately still uncapped when using "Smart VSync".

[PS. I've read a bit about about variable refresh rate and VSync, and I've come to the conclusion that the regular VSync option is the correct one for my use case. So I don't really want or need to use the "Smart VSync" option, it's just weird that it doesn't work on my machine]

**Comment by Ilya-intel** [comment]
@WouterNed 
Probably this is somehow related to OS and would require Windows reinstallation in case you need Smart Sync in future.

Feel free to close this thread if you don't need additional help.

**Comment by WouterNed** [comment]
@Ilya-intel Ah, yeah Windows reinstallation is a bit too much work for a feature that I don't use. Thanks for the help in troubleshooting!
