### ISSUE TITLE
Game crashes when MSAA is enabled or horrible performance with it

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#446]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Forza Horizon 5

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 21.08.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12399739/Intel.SSU.21.08.2023.txt)

### Description and steps to reproduce [Required]

Try to enable MSAA 16X in FH5. It will either crash, or you'rfe going to get -50% performance less with bad frametimes

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Max

### Crash dumps [Required, if applicable]

This is another exception code than the one from the issue I made earlier, here it is : https://drive.google.com/file/d/1Md2jYfjc0FwgLMvfRv7ehHavKsjJlQup/view?usp=sharing

**Comment by kestrelgone** [comment]
I've been experiencing this too with my Arc A770M, though I'm on the Microsoft Store version of the game.  Any MSAA setting except off will cause the game to crash for me.  The steps to reproduce are:

1- Start the game and select 'Start Game' and 'Continue' to proceed to the first player menu (the game will sometimes crash after this step).
2- From this menu, select 'Back' and 'Back' again at the subsequent menu.
3 - Enjoy the crash.

One additional thing I have noticed is that in Step 2, if 'Back' and then 'Drive' is selected, the crash doesn't happen.
Hope this can help track down the culprit!

**Comment by Karen-Intel** [comment]
Hey @TheWonderfulTartiflette how do you force MSAA to run x16? 
In my game settings it just show MSAA 8x as the top option 
@kestrelgone could you share a quick vid on how to repro the crash? I tried to follow the steps to reproduce you posted but I wonder if I'm missing anything. Ty

Karen

**Comment by kestrelgone** [comment]
Sure, Karen.  This video is from Step 2 as listed above.  I had the MSAA set at x2, but I think any setting from x2 to x8 should trigger the crash.  Just make sure to select 'Back' and not 'Drive'.  'Drive' triggers a short video of the car driving away from the player's house that, for some reason, prevents the crash.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/45089025/e43a6b24-da66-45a1-bf26-2cdc1ed897a3

Here are the video/graphic settings.  I've been changing them repeatedly trying to improve some really terrible texture pop-in that I'm experiencing, but no other setting combination seems to affect the crash one way or another.  Good luck!
  
![Forza Video Settings - 01](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/45089025/0b60e6fe-aafe-43a9-b5c9-62ec0720f09b)
![Forza Video Settings - 02](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/45089025/f36790f1-f217-4e9f-ab7b-ee77fb67ad6b)
![Forza Video Settings - 03](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/45089025/f8f2ecea-60c7-4b4c-ab2e-bea384e77ca4)
![Forza Video Settings - 04](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/45089025/6e569739-aaba-4c9e-b1b4-2dd3621c5b3f)

**Comment by TheWonderfulTartiflette** [comment]
> Hey @TheWonderfulTartiflette how do you force MSAA to run x16 in FH5? 
> In my game settings it shows MSAA 8x as the top option 
> @kestrelgone could you share a quick vid on how to repro the crash? I tried to follow the steps to reproduce you posted but I wonder if I'm missing anything. Also share your game settings please, video and graphics, Ty
> 
> Karen

My bad I indeed meant MSAA 8X

**Comment by TheWonderfulTartiflette** [comment]
Idk if it's related, but when I change the MSAA setting in CS:GO, it crashes instantly
