### ISSUE TITLE
Asrock Cards and Default OC Speed

### ISSUE THREAD

**Issue by Darklegion1978** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#450]
### Application [Required]

OC Cards from Asrock

### Processor / Processor Number [Required]

Ryzen 5 5600X

### Graphic Card [Required]

Intel Arc A770 Phantom Gaming D 8GB OC

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Its often discused, and we seen a change.

I have, till Intel started with his graphics card an OC Variant from Asrock A770 8Gb.
Asrock is promoting it with an higher Default Clock Speed of 2200MHz.

Till today, the Card runs just with the original Clock Speed as the original Intel Card, 2100MHz as all can see in GPU-Z and HW Info.

With the new Driver and FW Update, the Asrock A380 got an higher Clock Speed, its getting a little more to its regular OC Speed.

Could you be so kind, and let us know, when the A770 would get these Update to use its regular Clock Speed of 2200MHz and not the original one of 2100MHz?

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/123353653/0bc0b4a4-b661-4bdc-83ec-35e2f1415274)

Greetings

**Comment by Darklegion1978** [comment]
The Screens from the Asrock A380 Card

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/123353653/851e956d-ce8e-4dd7-b965-d1dc0b651227)

**Comment by Darklegion1978** [comment]
Seen the Release Notes of the new Driver 4669 :(
I guess, all Partner Cards would never show the real Clock Speed as promoted :(

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/123353653/472cc0f0-9365-4ef4-a0cb-16a0a614a3dc)

**Comment by Gabriela-Intel** [comment]
@Darklegion1978 Are you okay with us closing this one out?

**Comment by Gabriela-Intel** [comment]
@IGCIT Close this one. Thanks!
