### ISSUE TITLE
Adjust date format in Arc Control to system preference or make it unambiguous

### ISSUE THREAD

**Issue by WouterNed** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#451]
### Application [Required]

Arc Control

### Processor / Processor Number [Required]

Intel i5-13400F

### Graphic Card [Required]

Intel Arc A770 LE

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [X] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

This is arguably a small nitpick. In the Driver section of Arc Control, the current driver version is displayed with a corresponding date. This date is in the format of MDY, which is not the format of DMY that I specified on my machine and is the standard in my part of the world. This creates ambiguity. Usually this works itself out, as with a number above 12 in it it's clear what the date is supposed to be, but for the latest driver (101.4644) it's unclear at first sight. 8/11/2023 in my mind is the eighth of november, but I guess it's supposed to be the eleventh of august as november is still in the future.

My feature request is to either:
- Display this date in the date format used by the system

or:
- Display this date in an unambiguous format, such as ISO 8601 YYYY-MM-DD or by writing out the name of the month (11 August 2023)

P.S. The same MDY format is used on the intel driver website, but on the website they state the date for the 101.4644 driver is the 15th of august?

### Additional notes

![AmbigiousDate](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/52256913/5b71117b-33ec-4c00-88d6-98b193ed467f)

**Comment by Arturo-Intel** [comment]
@WouterNed thank you for your feedback, we will share this to our Arc control dev team

**Comment by Gabriela-Intel** [comment]
@IGCIT Please close this one out
