### ISSUE TITLE
Control 2019 crashing on directx12

### ISSUE THREAD

**Issue by MrDiagnose** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#453]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Control 2019

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 3400g

### Graphic Card [Required]

Intel Arc a750 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12429600/igcit_ssu.txt)

### Description and steps to reproduce [Required]

The game crashes after displaying the sponsors

![sponsers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/23004075/864bf9a9-6dbf-4076-b06a-281a1e0c9aff)

https://youtu.be/jFq60knwgMI

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

can't even get to settings the game becomes unresponsive then crashes after displaying

![sponsers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/23004075/864bf9a9-6dbf-4076-b06a-281a1e0c9aff)

**Comment by Karen-Intel** [comment]
Hi @MrDiagnose thank you for your report!
FYI,[ I have not been able to reproduce](https://www.youtube.com/watch?v=CDuqVfE6fN0) the immediate crash after the credits.
I am using a 13900k + A770 w/driver v4644. 
Allow me to share a few recommendations (perform them 1 step at a time, meaning make changes and test the game):
- Make sure to use the [latest DDU version ](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html)to upgrade your driver.
- I see you do have a Radeon APU as well, try to disable it, test only with Intel ARC enabled and see if it launches. Make sure to verify your Vega 11 is also updated to the [latest driver version in the AMD Website.](https://www.amd.com/en/support/apu/amd-ryzen-processors/amd-ryzen-5-desktop-processors-radeon-vega-graphics/amd-ryzen-5-1)
- [There's a new BIOS version for your system](https://www.asus.com/motherboards-components/motherboards/prime/prime-a320m-k/helpdesk_bios/?model2Name=PRIME-A320M-K), would be good to update it as well
- If after all these recommendations your game still crashes, please share the .dmp file that is created in the Control game folder and let us know in this thread to try to replicate the game crash in other system configurations.

Keep me posted

Karen

**Comment by MrDiagnose** [comment]
ok disabling igpu works :) but i couldn't find the *.dmp file in the control game directory
