### ISSUE TITLE
The Last of Us Part 1 Model Glitching

### ISSUE THREAD

**Issue by Chri2992** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#454]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

The Last of Us Part 1

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7-12700k

### Graphic Card [Required]

Intel Arc A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [X] 31.0.101.4577
- [ ] 31.0.101.4576
- [X] 31.0.101.4575
- [ ] 31.0.101.4514
- [X] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel_System_Support_Utility_Report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12433738/Intel_System_Support_Utility_Report.txt)

### Description and steps to reproduce [Required]

Video files are too big attached is a link to them in a drive. Game seems to have issues rendering cloths and hair very commonly. Resolution, graphics settings, and vsync do not seem to fix the problem. I've tried talking to the developers to no avail so I was hoping you guys could help with the issue. 

https://drive.google.com/drive/folders/1SPnRwqpCIszDKO0DM6jWB8iHMIr5GW-x?usp=sharing

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560*1440 or 1920*1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

[The Last Of Us Graphics Settings 1.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12433890/The.Last.Of.Us.Graphics.Settings.1.zip)

### Crash dumps [Required, if applicable]

[compressed_dumps.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12433744/compressed_dumps.zip)

### Save game

[SAVEFILE11.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12433747/SAVEFILE11.zip)

**Comment by Chri2992** [comment]
I forgot to note, it is the 16GB version of the A770

**Comment by Karen-Intel** [comment]
Hey @Chri2992 Ty!
Adding to debug queue, let me try to repro and will get back to you as soon as I get results. Stay tuned!

Kareb

**Comment by Karen-Intel** [comment]
Hey @Chri2992 could you please re-share your save game? I downloaded the one you attached but it takes me to the beginning of the game before the credits :(

Ty

Karen

**Comment by Chri2992** [comment]
[SAVEFILE17.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12459031/SAVEFILE17.zip)

Hi @Karen-Intel, Sorry the previous file is not working, I uploaded a different file that should put you right at a cutscene where a majority of the glitching is happening.

**Comment by Karen-Intel** [comment]
Hi @Chri2992 that was very helpful, thank you :)

I could definitely see the hair corruptions and some models glitching in black. I will make sure to create an internal report and update this thread as soon as we get any news. Just FYI and consideration, fixes might take from 3 up to 6 months to be released (just for you to have an idea of timing expectations) 
Please keep this post open :) and TYSM for your help!

Karen

**Comment by Chri2992** [comment]
Thank you for the update! Looking forward to hearing about the results.

**Comment by rmorera-intel** [comment]
Thank you for reporting this issue. Our priority is to target the most popular games and apps to focus our efforts on providing a high quality, stable experience for the broadest set of users. We will continue to improve our software performance and compatibility throughout 2024 and beyond. While we can’t accommodate your request at this time, please watch [this article](https://www.intel.com/content/www/us/en/support/articles/000096374/graphics.html) on our website for any possible changes to this situation.
