### ISSUE TITLE
Global Illumination is not available on Genshin Impact despite meeting minimum requirements

### ISSUE THREAD

**Issue by martin-ngyn** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#455]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Genshin Impact

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

Native installation

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Intel Arc A750

### GPU Driver Version [Required]

- [x] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[intel arc a750 ssu log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12447242/intel.arc.a750.ssu.log.txt)

### Description and steps to reproduce [Required]

Meet system requirements for Global Illumination (https://www.hoyolab.com/article/20899860):

Minimum Specifications for Global Illumination:

Operating System: Windows 10 64-bit

Processor: 9th Generation Intel® Core i5™-9400F or equivalent

Discrete Graphics Card: NVIDIA® GeForce® GTX 1050 Ti or equivalent

VRAM: 4 GB or more

RAM: 16 GB or more

Then open graphics setting. You won't find Global Illumination as an option to toggle on.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/c92eb036-cf56-4c07-ba5d-8fb7cd7544e4)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/81234267/01feb16c-ed41-4b61-b4ff-31bd8db29203)

**Comment by Billy-Hostage** [comment]
For those who searching for a solution, you can turn Global Illumination on by using [Collapse](https://github.com/CollapseLauncher/Collapse), an open source alt game launcher for hoyoverse's games.
It seems like that the devs treat all Intel GPUs as intergrated gpus and did not do proper testing on arc gpus. Or maybe there are more hidden issues we don't know yet.
Until they fix this, I will stick with Collapse Launcher.

**Comment by Arturo-Intel** [comment]
Using 5081 driver and the default launcher ( not using Collapse) I can see the Global Illumination option available 

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/702681cf-fb45-48e0-a3c3-a461e45cc6ef)
