### ISSUE TITLE
X-Plane 11 - Graphical glitch with SSAO

### ISSUE THREAD

**Issue by YUCLing** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#456]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

X-Plane 11

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i9-12900KS

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

- [X] 31.0.101.4669
- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [X] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12445417/igcit_ssu.txt)

### Description and steps to reproduce [Required]

After I change Visual Effects from HDR to HDR+SSAO, this happens
<img width="1712" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/f85a520c-b8e9-454b-a4b3-2e3321a1a805">
<img width="1712" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/f6741f12-924b-4909-9915-25a5629106ef">
<img width="1712" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/fb987d8f-18a2-45a7-ac2d-06256494dc8e">

**Tested with the following configurations**

- Driver 4644, Vulkan
- Driver 4669, Vulkan
- Driver 4669, OpenGL

**Tested locations**

- KJFK
- ZGGG
- YAUS

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

Resizable window mode

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

<img width="759" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/3a08f6ae-0e29-45eb-b3b1-63a78669b82e">

**Comment by Karen-Intel** [comment]
Hi @YUCLing thank you for your report. Adding this one to debug queue and after a couple experiments we will let you know if we were able to repro. Stay tuned!

Karen

**Comment by Gabriela-Intel** [comment]
Thanks so much @YUCLing  for reporting this issue!  Our priority is to target the most popular games and apps to focus our efforts on providing a high quality, stable experience for the broadest set of users. We will continue improving our software performance and compatibility throughout 2024 and beyond. 

Unfortunately, we can't fulfill your request right now :/ but we're always updating our plans. Keep an eye on our [website](https://www.intel.com/content/www/us/en/support/articles/000097068/graphics.html) our support article for any possible changes to this issue.
