### ISSUE TITLE
Kingdom Hearts 2 - Game Running in Slow Motion + Constant FPS Drops

### ISSUE THREAD

**Issue by KingYozora** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#46]
Kingdom Hearts 2 from the 1.5+2.5 PC Collection

---
i5-1035G7

---
Driver Version: 27.20.100.9316

---

DirectX 12

---
Windows Build Number 20H2 19042.870

---
Description: Bunch of frame drops below 60fps on Intel GPUs and game runs in slow motion even when running at 60fps during battle when playing as Roxas in the beginning of the game.  This does not happen on my weaker Nvidia 740M GPU or my integrated AMD APUs.  Only happens with Intel GPU.

---
Steps To Reproduce:  Just play the beginning part with Roxas.

---
Game graphics settings: 720p vsync off or on.  Changing resolutions and V-Sync does not help fix the slow motion or the frame drops.

---
Screenshots _[Optional]_

---
Save game _(if possible, could help solve the issue faster)_ _[Optional]_

---
Game custom logs (if available) _[Optional]_ _[Recommended]_

---
Additional notes _[Optional]_

**Comment by estebanr863** [comment]
Hi @KingYozora, we are trying to reproduce this issue, but so far, we haven't been successful. Does the issue happen for you under certain settings or at some specific point of the game?

**Comment by estebanr863** [comment]
Hi @IGCIT and @Valkirie,

Any chance one of you can help reproduce this issue? We are not seen it in our lab.

**Comment by KingYozora** [comment]
> Hi @IGCIT and @Valkirie,
> 
> Any chance one of you can help reproduce this issue? We are not seen it in our lab.

I sent my GPD Win 3 in for repairs a few weeks ago, so I can't test it out now.  Maybe next week.

**Comment by estebanr863** [comment]
HI @KingYozora,

Did you get your device back?

**Comment by KingYozora** [comment]
> HI @KingYozora,
> 
> Did you get your device back?

Yes.  Slow down seems fixed when playing as Sora (brown hair guy), but when playing as Roxas (blond hair guy) in the beginning, the fps drops when attacking.  This only happens when attacking and when Roxas is doing the attack pose animation.  

Its no big deal since you only play as Roxas for the first hour of the game.

**Comment by estebanr863** [comment]
Hi @KingYozora,

We are not seen any issues with the [latest drivers](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html). Can you please perform a [clean instal](https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html)l with this driver version and try again?

**Comment by KingYozora** [comment]
> Hi @KingYozora,
> 
> We are not seen any issues with the [latest drivers](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html). Can you please perform a [clean instal](https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html)l with this driver version and try again?

Slow down seems fixed on that driver.

**Comment by estebanr863** [comment]
Good news! Thanks for testing!

@IGCIT @mva can this be closed?
