### ISSUE TITLE
AOC 24G2

### ISSUE THREAD

**Issue by DukeJukemEG** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#460]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

the entire operating system

### Processor / Processor Number [Required]

12400f

### Graphic Card [Required]

a770

### GPU Driver Version [Required]

- [X] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[453.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12459357/453.txt)

### Description and steps to reproduce [Required]

try to enable freesync. freesync not supported on AOC 24g2. nice job. its a piece of software. why would i use a monitor without vrr on. im done. goodbye

**Comment by Karen-Intel** [comment]
Hi @DukeJukemEG thank you for your report!
This behavior has been reported before by other users and in different channels so the dev team is currently working on it :)
We will have news soon I hope, this is the internal number we have, just leaving it here for reference: 15013186965

Karen

**Comment by montvna** [comment]
looking forward to this fix 😁

**Comment by montvna** [comment]
Hey everyone ! It appears that this has now been fixed, currently on 4885

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88950672/89f21b8b-9f44-4d1b-bfe9-a64c40eb382e)
