### ISSUE TITLE
VRChat crashes on startup with Intel Arc A770 when using SteamVR (before 4499 it was good)

### ISSUE THREAD

**Issue by zabergan** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#461]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

VRChat

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Other game platform

SteamVR

### Processor / Processor Number [Required]

Intel Core i7 8700k

### Graphic Card [Required]

Intel Arc a770 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4669
- [X] 31.0.101.4644
- [X] 31.0.101.4578
- [X] 31.0.101.4577
- [X] 31.0.101.4576
- [X] 31.0.101.4575
- [X] 31.0.101.4514
- [X] 31.0.101.4502
- [X] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [X] Windows 11 21H2
- [X] Windows 10 22H2
- [X] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12467546/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Connect VR headset to PC (I used wireless Virtualdesktop)
Open SteamVR
Open VRChat
Game does not open, makes an error dump in %appdata%/LocalLow/VRChat/VRChat

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

It does not start, cannot provide any details.

### Device / Platform name

SteamVR

### Crash dumps [Required, if applicable]

[output_log_2023-08-29_18-58-22.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12467471/output_log_2023-08-29_18-58-22.zip)

**Comment by BuyMyMojo** [comment]
Try dissabling resizable bar, I have found this fix3es VRC crashes for me. it's not a solution obviously since it makes everything else run worse but at least it boots...
