### ISSUE TITLE
CS:GO stutters since 4669

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#462]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Counter-Strike: Global Offensive

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

https://drive.google.com/file/d/1MjQKNNfGNhL41WWPfeP5u6xhzCGO6lJh/view?usp=sharing

### Description and steps to reproduce [Required]

I've played a game of 30 minutes, and I had like 4 stutters. They were around 1 second each

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Max

**Comment by SopaDeMacaco-UmaDelicia** [comment]
In 20 days valve will update cs:go to cs2 which has vulkan renderer `(-vulkan)` launch option, the problem should fix itself. 😁

**Comment by freak2fast4u** [comment]
> In 20 days valve will update cs:go to cs2 which has vulkan renderer (`-vulkan` launch option), the problem should be fixed by itself. 😁

Well, having tried the default DX11 renderer for CS2 myself, I can say I'm impressed already, I felt no micro-stutters nor frame-pacing issues after a few hours of deathmatch on various maps (A770 16GB here), it's buttery smooth. FPS is lower than in CS:GO but the frame pacing is way more consistent, which is a win overall imho. On high settings (not ultra) I'm hovering around ~150fps, which is good enough for me. Ultra goes close or below 100fps way too often for me to consider it "playable" (for competitive shooting games in general).

**Comment by SopaDeMacaco-UmaDelicia** [comment]
> Well, having tried the default DX11 renderer for CS2 myself, I can say I'm impressed already, I felt no micro-stutters nor frame-pacing issues after a few hours of deathmatch on various maps (A770 16GB here), it's buttery smooth. FPS is lower than in CS:GO but the frame pacing is way more consistent, which is a win overall imho. On high settings (not ultra) I'm hovering around ~150fps, which is good enough for me. Ultra goes close or below 100fps way too often for me to consider it "playable" (for competitive shooting games in general).

And how's vulkan? It should have even smaller driver overhead. I don't have beta sadly.

**Comment by freak2fast4u** [comment]
In it's current state, using the "-vulkan" option in CS2 introduces 1 sec freezes (particularly at the beginning of a game, much less so after that), micro-stuttering and even graphical glitches (entire structural elements of the map go full-black for a few frames and pop back into existence). I don't know which part is from Intel's vulkan driver or which is from Valve's vulkan source 2 implementation, but it isn't usable ATM. That's why it's behind a flag and not the default ;)

I encountered none of the aforementioned problems using the default (DX11) renderer.

**Comment by Arturo-Intel** [comment]
@TheWonderfulTartiflette do you still experiment stutters using the default renderer? (DX11)

**Comment by freak2fast4u** [comment]
@Arturo-Intel : that would be DX9, considering OP was talking about CS:GO and we went off a tangent about CS2, sorry for the off-topic comments ^^"

I can confirm stutters in CS:GO are still a thing on Arc these days (noticed some playing last week), even on 4826 beta.
I do remember a period where CS:GO was smooth on Arc (somewhere in the summer), but I wasn't tracking versions as closely as now, so maybe some late regression in the DX9 segment of the driver (after all those efforts y'all put into fixing it *sob*).

**Comment by SopaDeMacaco-UmaDelicia** [comment]
CS:GO is dead. The problem fixed itself.

**Comment by Gabriela-Intel** [comment]
@TheWonderfulTartiflette As @SopaDeMacaco-UmaDelicia mentioned, CS2 has totally replaced CSGO. Let us know if you continue to see the issue with CS2.

**Comment by Gabriela-Intel** [comment]
@IGCIT No update from OP so far. Please close.
