### ISSUE TITLE
Starfield does not launch 

### ISSUE THREAD

**Issue by 3EyedBlinky** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#463]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Starfield 

### Game Platform [Required]

- [X] Steam
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

7950X3d

### Graphic Card [Required]

Arc A770

### GPU Driver Version [Required]

- [X] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

N/A

### Description and steps to reproduce [Required]

You guys can probably delete this but I wanted to get it in front of actual people in case remotely true. 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

4K

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Max settings

**Comment by Karen-Intel** [comment]
Hi @3EyedBlinky heeeey! Thank you for reporting this and for the exclusive ;)

We will check it as soon as it is out, stay tuned!

Karen

**Comment by 3EyedBlinky** [comment]
In case you want more context, or a person to reach out to, that has reviewed the game and identified the bug on their Arc PC 
[https://www.digitaltrends.com/computing/starfield-pc-performance-best-settings-fsr-2/#:~:text=Starfield%20system%20requirements,-Before%20getting%20to&text=Based%20on%20my%20benchmarks%2C%20it,at%20the%20same%20graphics%20preset](url)

**Comment by IGCIT** [comment]
hi,

thanks for sharing, please note that review copies may not be final.

since the game is not out yet, and a day-1 patch may be provided to fix reviewers issues, i'm proceeding to close this for now, but feel free to fill missing info and reopen if you get access to the game once out and the issue persists :)

**Comment by 3EyedBlinky** [comment]
This should be re opened :P https://twitter.com/IntelGraphics/status/1697395355229331631?s=20

**Comment by juzi5201314** [comment]
This should open. The problem exists and has not been resolved

**Comment by IGCIT** [comment]
> This should open. The problem exists and has not been resolved

this issue is incomplete and not valid as it is, if you have the game already, please open a new one.

thanks
