### ISSUE TITLE
Immortals of Aveum Crashes on Arc a750

### ISSUE THREAD

**Issue by kunit1** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#464]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Immortals of Aveum

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

12600K

### Graphic Card [Required]

Arc a750

### GPU Driver Version [Required]

- [X] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

N/A

### Description and steps to reproduce [Required]

Play the first mission of the game. While following Luna after going up on the chains the game freezes for a second and then an Unreal Engine Crash window comes up with the following text: 

LowLevelFatalError [File:E:\Jenkins\GAME-Ascendant-Hardening_Build\Engine\Source\Runtime\D3D12RHI\Private\D3D12Util.cpp] [Line: 868] CurrentQueue.Device->GetDevice()->GetDeviceRemovedReason() failed at E:\Jenkins\GAME-Ascendant-Hardening_Build\Engine\Source\Runtime\D3D12RHI\Private\D3D12Submission.cpp:910 with error 887A0006

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

All settings set to high, FSR Set to Quality

**Comment by IGCIT** [comment]
hi @kunit1, can you please provide the [ssu](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/How-to-generate-Intel-System-Support-Utility-report) log?

thanks

**Comment by kunit1** [comment]
I can't replicate the issue anymore. I'll close this one for now and open a new one if I can replicate it reliably again.
