### ISSUE TITLE
Starfield does not launch on Intel Arc Graphics

### ISSUE THREAD

**Issue by jjennway** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#465]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Starfield

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7 3700X

### Graphic Card [Required]

Intel Arc 770 16gb (Acer Predator)

### GPU Driver Version [Required]

- [X] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12498280/ssu.txt)
Starfield mentioned here: 
Problem signature:
P1: Starfield.exe
P2: 1.7.23.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

+++ WER9 +++:
Fault bucket 2068634714265132436, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

### Description and steps to reproduce [Required]

Launching the game from steam or the .exe doesn't open the game, just a high CPU and memory process. Leaving the process running for a couple minutes opened a blank white screen that crashed when I clicked on it.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/24259847/acb68570-5471-422e-bdc1-204b56198053)

**Comment by Semenius** [comment]
Similar situation, but bit diffrent specs:
13700K
A770 LE
Win11 22H2

**Comment by akarnokd** [comment]
Sorry to interject.
i7 13700K + A770LE, Driver 4577<sup>*</sup>. The game does launch for me after about 20 minutes of high memory & CPU usage. I get into the main menu. It compiles shaders. I can change settings. Using Low preset. 

If I click new game, half the time it CTDs. The other half. I get into the elevator scene with total blurry image. If I hit ESC (when the game let's me), I see the menu. If I return to the game, 75% of the time it CTDs, still blurry.

In the Windows Event viewer, I get an entry in System "Display 4101: A(z) igfxnd stopped responing and successfully recovered."

<sup>*</sup>I know, I know, not the latest. I didn't want to risk bricking my card with the firmware change and not be able to play Starfield due to that.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/fe49482c-8867-43cd-9a06-378106f37d24)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/91f8b934-2ac5-486f-96b1-21208423f029)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/062037f5-6999-4b6e-ad52-5fd0abc1066d)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/f13062e2-ac76-488c-b16c-68a2168b98da)

**Comment by DealsBeam** [comment]
Intel is aware of the issues and are working on it https://twitter.com/IntelGraphics/status/1697395355229331631

**Comment by RhanCandia** [comment]
Can confirm. Game launches on my A750 after more than 30 minutes of CPU, RAM, and Disk activity. Could be the game packages decompression or something since it's EA.

Can start new game. Character is responsive when control is given. Can hear the NPCs. But the graphics is broken.

![Screenshot 2023-09-02 114059](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/7951366/535e92ff-bee4-4162-b23b-54728e2279dc)
![Screenshot 2023-09-02 114246](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/7951366/42e585f3-f222-4354-b2df-7bcd58c8b35f)

**Comment by HueSplat** [comment]
I know Intel is aware, perhaps this info may be of some use?
Same graphic corruption here, occurs on all graphics quality presets, even minimum with everything possible turned off.
Game will also at times crash when starting (eg selecting new game) and sometimes during gameplay it will also crash, not that the game is actually playable at all anyway.

101.4644 & 101.4669 I attempted all "game compatibility" settings in Arc control which triggered a shader recompile with every change (side note, i though this setting did not apply to DX12?)

Short video of graphic corruption, same as above screenshots.
https://youtu.be/Al-ud0JlZJQ

A770 LE
7800X3D
W11 22H2 (22621.2215) & W11 23H2 22631.2265
Microsoft Store/Xbox version of Starfield

These are the list of drivers I tried, there were others i tried at random but thought id actually take notes properly. DDU and reboots between drivers.
101.3490 THE GAME HAS CRASHED Error code: (0x1)
101.3729 trouble installing - SKIP
101.3790 trouble installing - SKIP
101.3793 THE GAME HAS CRASHED Error code: (0x1)
101.3802 THE GAME HAS CRASHED Error code: (0x1)
101.3959 THE GAME HAS CRASHED Error code: (0x1)
101.3975 THE GAME HAS CRASHED Error code: (0x1)
101.4032 THE GAME HAS CRASHED Error code: (0x1)
101.4090 THE GAME HAS CRASHED Error code: (0x1)
101.4091 THE GAME HAS CRASHED Error code: (0x1)
101.4123 THE GAME HAS CRASHED Error code: (0x1)
101.4125 THE GAME HAS CRASHED Error code: (0x1)
101.4146 5FPS, graphic corruption (same as latest beta and WHQL but low FPS)
101.4148 5FPS, graphic corruption (same as latest beta and WHQL but low FPS)

101.4644 graphic corruption
101.4669 graphic corruption
![Screenshot 2023-09-02 180052](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/121140049/045f2f72-e766-40ac-a4b3-8c23974450b1)

**Comment by Karen-Intel** [comment]
Hi everyone! We have a new driver posting [v.4672](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) . You can check the last comms in [Intel Graphics Facebook page ](https://m.facebook.com/story.php?story_fbid=pfbid02vjQzaoQtf8SE3DermzvLs6Fo3LBABLVs5xFHbcyrRwF2L8QieWYdDD8TDCLmXAc3l&id=100064502419621&mibextid=9R9pXO) too. Please let us know if you see improvements with this version :)
TY
Karen

**Comment by jjennway** [comment]
Thank you for the quick fix! Game lauches now, I see artifacts when Depth of Field or any upscaling methods are enabled. With those two disabled things seem smooth on high preset.

**Comment by BuyMyMojo** [comment]
With the latest driver it still took about 30 minutes to get past being stuck in the task manager and once it got to the bathesda logo intro video it crashed (Visuals stopped but with music until it tells me to force close it).

On second boot it launched just fine and compiled shaders which took a long time but other then that it runs fine.

I'll take some perf recordings with Intel PresentMon later when I get time (1440p medium settings FSR2 replaced with XeSS 50% render res).

**Comment by 3EyedBlinky** [comment]
Latest driver the game is running albeit I would not exactly call it stable. It crashed no error to desktop when getting to the games first combat sequence. This was running on High default graphic preset on my 4K monitor. CPU Ryzen 7950X3D with both latest BIOS and AMD chipset drivers. Running perfmon beta, the game seems entirely gpu bottlenecked which would make sense, but the gpu power draw was oddly low around 150-160w with 100% usage. This seems to coincide with the general consensus that the game is having issues with properly utilizing all gpu's. Hoping to see improvements overtime as fps being 22-35fps at a upscaled 62% res FSR 2 seems.... low. Thanks for getting the game running though for everyone excited to try it. Also, if anyone has an ear in Bethesda's ear lets get XeSS support soon as possible.

**Comment by toriko2** [comment]
Game seems to launch for me as well! Though VRAM usage is oddly high ~9 GB even on lowest settings at 720p, compared to the rtx 3060 which uses ~4GB. This I'd imagine causes slowdown on the a750

**Comment by BuyMyMojo** [comment]
I have now had a crash from inside of a building while loops. I moused over a toilet paper roll and it froze and crashed on me.

Crash:
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/04dccb2c-ab7b-480f-a336-b37b60887a1a

The transparent plastic curtains also seem to be rendered incorrectly:
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/06e6f9cc-48ad-49a3-837a-3f3a30f11265

**Comment by BuyMyMojo** [comment]
I have captured the weird light leaking I have encountered and another crash right after (This is using FS2)

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/7396fb1b-32ea-4970-8d38-d076aabba3d1

**Comment by BuyMyMojo** [comment]
Okay it seems transparencies are very broken in general. eye lashes, eye brows, random glass vials, the plastic curtains are all broken. the only one *partially* visible is the curtains since they at least have a blur kinda effect.

**Comment by Arturo-Intel** [comment]
@BuyMyMojo can you open a new issue for the transparencies being broken? and another for the ~30 min loading time.
It is better to track each of the issues in separated threads 

-- r2

**Comment by Arturo-Intel** [comment]
@jjennway its ok the close this issue now? It not crashing any more right?

-- r2

**Comment by 3EyedBlinky** [comment]
> @jjennway its ok the close this issue now? It not crashing any more right?
> 
> -- r2

The game launches, so in a sense this is resolved, but the game absolutely still crashes, for others, should they open another ticket specific to game unexpectedly quitting? Not sure how much is on Bethesda's side vs the driver itself at this point.

**Comment by Arturo-Intel** [comment]
> The game launches, so in a sense this is resolved, but the game absolutely still crashes, for others, should they open another ticket specific to game unexpectedly quitting? Not sure how much is on Bethesda's side vs the driver itself at this point.

Yes, please open a new case for each one of the issues, it is better for everybody :)

**Comment by jjennway** [comment]
Yeah I'd agree we should close this issue and open new issues for the new issues people are seeing.
