### ISSUE TITLE
Parsec Virtual Desktop Adapter conflicts with Arc Control

### ISSUE THREAD

**Issue by d-mccoy** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#466]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3D

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

19045.3324

### Intel System Support Utility report

[IntelSystemSupportUtilityReport-CERBERUS.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12504977/IntelSystemSupportUtilityReport-CERBERUS.txt)

### Description and steps to reproduce [Required]

- Fresh install of Windows 10
- Install latest version of Intel Arc drivers and utilities (currently driver version 31.0.101.4669)
- Allow installer to Reboot PC
- Once rebooted and back in Windows, notice that no method of launching the Intel Arc Control software will work
- Check Task Manager and notice 6 running Background processes: Intel Arc Control, Intel Arc Control Assist (four of them), and Intel Arc Control Service
- If you click End Task on all six background processes, you can then launch Intel Arc Control -- but notice that none of the performance/tuning options are functional
- Notice that if you open Services.msc and manually restart Intel Arc Control Service that there is a 1/5 chance that the Arc Control Software will now function properly.

**Comment by J0dla** [comment]
Check #401

**Comment by d-mccoy** [comment]
Exact issue! Disabled Parsec Virtual Display Adapter and Arc Control starts right up and I can modify fan curve/performance options again.

While this "fixed" my issue, it makes Parsec mostly useless to me now. A fix at some point would be ideal.

Cheers!

**Comment by Arturo-Intel** [comment]
@d-mccoy  can you change the the case name to something like "Parsec Virtual Desktop Adapter conflicts with Arc control"?
This way we can track in this case this particular issue

--r2

**Comment by d-mccoy** [comment]
Done! @Arturo-Intel

**Comment by Felipe-Intel** [comment]
Hello @d-mccoy. Is this still happening with driver[ latest driver 31.0.101.5085](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)?

**Comment by d-mccoy** [comment]
This was fixed with a driver release sometime since the end of September, IIRC. I don't remember which one specifically, though. But yes, fixed!

**Comment by Arturo-Intel** [comment]
@d-mccoy Thanks for the confirmation
