### ISSUE TITLE
Exoprimal Poor Performance and Memory Leak

### ISSUE THREAD

**Issue by Code-Vlue** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#468]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Exoprimal

### Game Platform [Required]

- [ ] Steam
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12509535/ssulog.txt)

### Description and steps to reproduce [Required]

Game show a massive performance loss from High to Ultra settings, loss of about 40-50%. When compared to other cards of the same speed the game runs half as slow at Ultra settings. In addition contributing to this performance is the massive memory leak issue. The game will chew through 10-11GB of video memory dipping into the system shared pool when the game says it should only be consuming around 7GB and has been confirmed to on other cards.

Note: The memory leak issue persists no matter the settings chosen

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Ultra preset, VRS turned on.

**Comment by Karen-Intel** [comment]
Hey @Code-Vlue can you let us know if you still see the same behavior with our latest driver? TY

Karen

**Comment by Code-Vlue** [comment]
Hey @Karen-Intel as of driver 4826 behavior is still the same. When it comes to performance and memory usage.

**Comment by Code-Vlue** [comment]
@Karen-Intel to be a bit more in depth the memory issue is still there and performance is still poor at ultra but seems like there may have been a slight improvement however at high settings now I am no longer able to hold a stead 60FPS like I was before, it dripping down to mid to low 50s at times now.

**Comment by Code-Vlue** [comment]
https://youtu.be/8v3eUUW2GOQ

Here is a gameplay clip, in the clip and specific map the frame rate actually is quite improved at ultra, at high there are a few dips. It seems like some of the more intense dips may be more obvious on specific maps with more dinosaurs on screen. Also showed an example of the memory issue.

**Comment by Code-Vlue** [comment]
I was able to replicate the issue and capture it this time.

https://youtu.be/gybn4saOomw

**Comment by Code-Vlue** [comment]
Disabling Memory Integrity and Virtualization based security in windows increases performance a bit. High settings seem to be able to lock to 60FPS again most the time, issues at Ultra still persist.

**Comment by Code-Vlue** [comment]
Two transparent barriers next to each other drop FPS drastically, replication clip included.
https://youtu.be/DncF30zOL60

**Comment by Code-Vlue** [comment]
![Screenshot 2023-10-01 185834](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/142824040/45841ef5-a2a2-4ac6-beb8-0bebbdb19902)
Some textures do not load in completely, this may be due to the memory allocation/leak issue mentioned before.

**Comment by Code-Vlue** [comment]
Memory leak at High/Ultra texture settings has worsened, showing 100% VRAM usage most times and 90% of my 24GB of RAM used (around 30-40% with game closed). Performance seems to be massively improved until VRAM fills and spills over into RAM then performance tanks. Memory leak occurs at all texture settings but medium seems to be the best setting to minimize the impact of it. If medium textures are used all other settings can be maxed out without performance issues. The remainder of this games issues seems to be linked to the memory issue.

**Comment by Karen-Intel** [comment]
Hey @Code-Vlue Ty for reporting this :) Allow us to do some testing in the lab and will provide an update as soon as possible

Ty

Karen

**Comment by Code-Vlue** [comment]
Thank you @Karen-Intel I will also continue to add any new information that I see in gameplay if there is any.

**Comment by Joseph-Intel** [comment]
Hi @Code-Vlue I was able to test this out with our latest V1014953 graphics drivers. I did see all my vram used and RAM used but it didn't seem like the graphics card was the one taking the RAM. during these test i didn't encounter any stuttering maybe dropping to 50 fps when there is a lot on the screen which should be normal. Would you be able to test this out again on updated drivers and let me know your results?

**Comment by Joseph-Intel** [comment]
No worries! @Code-Vlue  Sounds like a game issue itself that may improve with future game updates. Closing this out soon. Let me know if you have other concerns about this.

**Comment by Joseph-Intel** [comment]
@IGCIT can we get help closing this out?
