### ISSUE TITLE
Dark souls 3 crashes

### ISSUE THREAD

**Issue by mva94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#47]
#### Game _[Required]_
Dark souls 3

---
#### CPU _[Required]_
I7 1165g7

---
#### GPU Driver Version _[Required]_

27.20.100.9466
---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_:
**API Version** _(example DirectX 12)_:

directx11
---
#### Windows Build Number _[Required]_

latest
---
#### Description _[Required]_

after 5-10 minutes randomly crashes and brings you back to desktop without an error message 
---
#### Steps To Reproduce _[RequiredGame]_

Just game and you should go through the crash

---
#### Game graphics settings (screenshot or text) _[Optional]_ _[Recommended]_

---
#### Screenshots _[Optional]_

---
#### Save game _(if possible, could help solve the issue faster)_ _[Optional]_

---
#### Game custom logs (if available) _[Optional]_ _[Recommended]_

---
#### Additional notes _[Optional]_
@leoben2

**Comment by Valkirie** [comment]
@mva94 can you double check now ?

**Comment by mva94** [comment]
Will do

⁣Télécharger BlueMail pour Android ​

Le 16 sept. 2021 à 17:16, à 17:16, Lesueur Benjamin ***@***.***> a écrit:
***@***.*** can you double check now ?

**Comment by estebanr863** [comment]
Hi @PacoAvelar,

This graphics corruption issue was reported internally and is now on our driver development team’s queue. However, just to set the right expectations, given the current load on the dev team, this fix could take between 3 to 6 months to be included in a driver release.

**Comment by pacoa-kdbg** [comment]
Hi @estebanr863 

Elden ring suffers from the same issue 

https://www.youtube.com/watch?v=ZIoO0-DaSQM


Can you at least put an update to/if the problem is the same ?

Elden ring scene is just after the tutorial, entering the first door (less than 5 minutes in game after character creation )

**Comment by gmartins-henrique** [comment]
Testing using 30.0.101.1934 and it is still an issue.
On elden ring it works fine, but dark souls 3 still has the same issue 

https://user-images.githubusercontent.com/13962266/166390877-2a79257e-428b-4a03-b247-36ebe7a6ba96.mp4

**Comment by mva94** [comment]
@estebanr863 will test it out tomorrow!

**Comment by estebanr863** [comment]
Hi @mva94,

Were you able to test this?

**Comment by estebanr863** [comment]
Hi @mva94,

Got the chance to test this?

**Comment by mva94** [comment]
@estebanr863 hey 
I tested the game it doesnt crashes anymore though its full of graphical glitches now ...
