### ISSUE TITLE
Arc Control keeps making Windows focus on it

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#472]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 05.09.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12521456/Intel.SSU.05.09.2023.txt)

### Description and steps to reproduce [Required]

While I was playing FH5, I noticed that my Windows taskbar kept showing up, so I installed Focus Logger which helps me know which program is changing focus, and I noticed that Arc Control, for EVERY focus switch I make, Arc Control appears alongside the app I want. Moreover, when I force Arc Control to close through the little arrow on the Task Bar, the problem goes away. Moremoreover, when enabling the Arc Control overlay while playing, then closing it, the taskbar doesn't go away as well even when clicking the game's icon, making the same issue appear
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/96834253-397a-4689-98fc-adda7d718820)

**Comment by Karen-Intel** [comment]
@TheWonderfulTartiflette can you check this behavior w/driver version 4826? We've closed a few ARC Control issues with this version

TY!

Karen

**Comment by TheWonderfulTartiflette** [comment]
@Karen-Intel still happens. I haven't seen the exact issue yet, as I said that it's difficult to repro, but I still see Arc Control constantly focusing itself, even if the end user isn't bothered by it

**Comment by Gabriela-Intel** [comment]
Hi @TheWonderfulTartiflette sorry to ask again but are you still observing that the task bar keeps appearing when using our latest drivers?

As for Arc Control constantly running in the background, some of the configurations that can be set in Arc Control need to be applied when Windows starts so that's why there is always a background service running. This shouldn't impact your gaming or PC experience though.

**Comment by TheWonderfulTartiflette** [comment]
@Gabriela-Intel no, but I have to say that even with the same drivers, the issue appearance was really inconsistent

**Comment by Gabriela-Intel** [comment]
@TheWonderfulTartiflette We haven't been able to observe this behavior. Since its really sporadic , do you mind if we close? You can open up a new issue if you see that this issue becomes more persistent.

**Comment by TheWonderfulTartiflette** [comment]
@Gabriela-Intel sure , no problem, thanks

**Comment by Gabriela-Intel** [comment]
Thanks! @IGCIT Proceed with closing, thanks :)
