### ISSUE TITLE
Starfield FSR and Unplayable Performance Issues

### ISSUE THREAD

**Issue by Code-Vlue** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#473]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Starfield

### Game Platform [Required]

- [ ] Steam
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12529917/ssulog.txt)

### Description and steps to reproduce [Required]

Game is unplayable in current state, frame rate drops below 30 no matter what settings are set at 1080P, CAS upscaling seems to work fine but FSR puts a black or blue border around the game when it adjusts scale dynamically. FSR also causes a sharp performance impact however this may not be the case, due to the current state of the game performance between settings is almost immeasurable since the frame rate will fluctuate wildly. There are times it will hit 30 or slightly above but the next moment it will dip down into the 20's or teens.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Game was tried at all settings presets except in most cases would change FSR upscaling to CAS. Trying non preset settings would seem to cause more issues.

**Comment by TheWonderfulTartiflette** [comment]
I confirm I'm having all of these issues as well, though for me, the black/blue border is only when setting the render scale to 50%

**Comment by TheWonderfulTartiflette** [comment]
Aaaand crash.. with nothing to show in the Diagnostic Data Viewer or the EventViewer

**Comment by TheWonderfulTartiflette** [comment]
Now getting black screens when I am on a game's store page on Steam [like this](https://drive.google.com/file/d/1xmCPAc9M8UifUn4OTJmkldhbefP-_hjE/view?usp=sharing)
Intel reps, should I open another “Issue” on GitHub to write every bug I encounter, or should I do it here?

**Comment by TheWonderfulTartiflette** [comment]
[And now this](https://drive.google.com/file/d/1Ms8tTcpOU5IWKqjLKm6mLToepHT7r_Hi/view?usp=sharing), I don't even know how to describe it

**Comment by Karen-Intel** [comment]
Hey @Code-Vlue this situation should have changed with drivers v4672 and the latest,[ v 4676](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)
Can you please confirm so? TY

Karen

**Comment by Code-Vlue** [comment]
@Karen-Intel initial testing shows that the borders are gone due to dynamic resolution and at the low preset at 1080P loading a save where before I got low 20FPS it now gets 29-30FPS so just at playable levels, I will have to do some more testing when I am able to do some in depth play but at the moment it looks like it may at least be playable.

**Comment by Code-Vlue** [comment]
correction, testing more shows the black bars are still present, performance does seem to be improved though.
![Screenshot 2023-09-11 193501](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/142824040/236c03bf-6a41-4564-b59e-e4835140d35d)

**Comment by Code-Vlue** [comment]
@Karen-Intel Further testing after this still shows spots where the FPS can drop into the low 20's as well even at low preset, dynamic resolution also dropping down to a pixelated mess.

**Comment by Code-Vlue** [comment]
@Karen-Intel Update, started the game today and performance is back up, seems to be inconsistent.

**Comment by Code-Vlue** [comment]
@Karen-Intel Can confirm after a few minutes of play performance drops drastically, GPU however holds its clock speed and stays at 100% usage.

**Comment by Karen-Intel** [comment]
Hey @Code-Vlue we already have an internal report related to this, leaving it here for your reference: 14020107573

Karen

**Comment by Code-Vlue** [comment]
@Karen-Intel Awesome thanks for letting me know.

**Comment by Code-Vlue** [comment]
Performance is massively increased in most recent driver 4885, can now run at high preset around 30FPS, blue and black dynamic scaling bars are still present though and unfortunately can't turn dynamic res off to get rid of them because performance plummets to unplayable.

**Comment by Code-Vlue** [comment]
Using the XeSS mod gets rid of the dynamic scaling bug.
