### ISSUE TITLE
Starfield Light leak, transparency rendering issues, planet display issues and possible crashing related to looting

### ISSUE THREAD

**Issue by BuyMyMojo** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#474]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Starfield

### Game Platform [Required]

- [X] Steam
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

5600x

### Graphic Card [Required]

Intel Arc A770 Limited Edition

### GPU Driver Version [Required]

- [X] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[2023-09-06.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12528756/2023-09-06.txt)

### Description and steps to reproduce [Required]

For light leak:
Go inside of a structure on any planet and eventually there will be random streaks of lights.

(This video isn't as good since it's just from normal gameplay with the flickering happeningrandomly through the frame but you can again see the transparency issue when then glass is missing from the tanks)

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/e4af21b4-4d7a-471e-a097-cee81e52b0ef

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/79dad954-a46c-4e03-bbc8-820f667d8ec0

Planet rendering:
On the low preset and only when starting with the low preset even after changing settings it will display triangle on the ground no matter what setting is changes.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/6e458d0d-0c6b-4c42-b601-03806669a325

Transparency:
Boot up the game and eye brows, eye lashes, the glass on vials and bottles and the transparent plastic curtains will all be basically nonexistent

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/ff46968f-5856-4825-81f7-7fbbde10f86e

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/4f2b90b2-ce97-4cc1-a8a4-ecd821557400

This cammo effect is meant to have a shimmer to it not just a ghostly outline:

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/78740c5a-4278-466e-8100-e45be385e9fb

Missing facial hair + helmet visor:

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/f23e59bd-d905-4c6f-8d24-18febc215c97

Crashing:
Randomly when looking at some clutter to pick up I have experinced ccrashing

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/c0b237d8-650d-4525-a8c2-a03636fd5b45

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

I did try with all basic presets with toggling Dynamic res, vrs and FSR on and off. All issues besides of the planet rendering apply to all presets

### Crash dumps [Required, if applicable]

Will add soon™️. wrote out most of this post and didn't want to reboot to enable the log collection lol.

### Save game

Light leak + No window save:
[Save18_29937C46_4D6F676F_001322_20230904232532_10_0_4.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12529040/Save18_29937C46_4D6F676F_001322_20230904232532_10_0_4.zip)

No facial hair or helmet transparency save:
[Save21_29937C46_4D6F676F_001352_20230905012109_10_0_4.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12529156/Save21_29937C46_4D6F676F_001352_20230905012109_10_0_4.zip)

**Comment by BuyMyMojo** [comment]
I got a crash dump from the tool:
[compressed_dumps.20230906.153012.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12533492/compressed_dumps.20230906.153012.zip)

**Comment by Karen-Intel** [comment]
Hey @BuyMyMojo good news!

I bring you a fresh driver[ v.4676](https://www.intel.com/content/www/us/en/download/785597/788015/intel-arc-iris-xe-graphics-windows.html) where I can see significant improvement in transparency rendering and other features.

Could you help me verify these improvements? TY

Karen

**Comment by BuyMyMojo** [comment]
With each driver update it seems to take around 30 minutes on first launch (For this driver I timed it and it took nearly 29 minutes on the dot) then it crashes before reaching the main menu but then works just fine after that crash.

Can confirm transparencies and facial hair are working as intended! 👍
![Photo_2023-09-08-224112](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/b866ab7f-5f7f-4220-81d4-205711d7cc35)

But while getting that picture I noticed the light leak again lol

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/83efaa6f-cb51-4285-abed-fcae359106b0

I'll report back after some actual play time 👍

**Comment by BuyMyMojo** [comment]
I have found a repeatable location to see the light leak in action:

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/92b938d2-01a2-4378-96cf-5039d4434eee

**Comment by BuyMyMojo** [comment]
A new crash dump:

[compressed_dumps.20230909.205039.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12565554/compressed_dumps.20230909.205039.zip)

**Comment by BuyMyMojo** [comment]
The fog in front of this type of cave creates a kind of glowing effect around the entrance:

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/331d9e9a-73d0-46ae-b8f1-eed54983c5f9

**Comment by Karen-Intel** [comment]
Ty @BuyMyMojo for your report :) Allow me to create an internal case with the evidences you shared + the ones I can find :)
If we have updates in upcoming driver updates or if a fix for this issue will take the usual cadence, I will let you know.

I'll get back with the Internal number for you soon :)

Karen

**Comment by Karen-Intel** [comment]
Hey @BuyMyMojo can you verify with our latest driver v.5186 and let us know? Thanks

Karen

**Comment by Arturo-Intel** [comment]
@BuyMyMojo If you still see any or other bugs in Starfield, please open a new case for each of them (easy to track, faster to respond)
Closing this case.
