### ISSUE TITLE
List of bugs in Starfield I encounter(ed) with driver 4672

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#476]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Starfield

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 06.09.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12539060/Intel.SSU.06.09.2023.txt)

### Description and steps to reproduce [Required]

Way too many bugs and issues I encountered, so I decided to list them all in a single issue, sorry if it's not the best thing to do, tell me if it's the case I'll open multiple Issues. I'll edit it as I discover new issues

There are 11 issues I have encountered so far

Bad average performance : 40FPS on the **lowest** setting, w/o any upscaling. Typically, when I hit 40FPS in a game, it's on Cyberpunk, no upscaling, and everything set to maximum. Alongside this, I noticed that the game draws very little power, way more dramatic than Cyberpunk does, and I don't think that this would be considered “normal” here. Enabling the FSR2.2 upscaling only provides marginal gains (going from 30FPS to 35FPS, no upscaling and FSR2.2 51% render scale upscaling respectively)
![image](https://user-images.githubusercontent.com/44057002/266032866-76fa9c37-e790-47b5-aaae-013b11714e06.png)

Bad frametimes: Just look at this:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/25c9e613-b922-4b51-9e4b-0ba486acc557)

Blue hue in the right and bottom of the screen : When setting the game on Low, I'll get big black borders around the screen. On Medium, I'm getting a blue hue and the black borders, and on High I'm getting black borders. I noticed that this has to do with the render scale of FSR
![image](https://user-images.githubusercontent.com/44057002/266031063-da4febb1-5795-4154-92ab-4a0a36065a6a.png)

Crash : I crashed once just when waking up in the introduction scene after having touched the weird thing that made you unconscious. Nothing to report in EventViewer, nor in the Diagnostic Data Viewer.

Graphical glitch with YouTube's player : When Alt Tabbing out of the game, and opening a YouTube tab, you may see [this super weird glitch](https://drive.google.com/file/d/1Ms8tTcpOU5IWKqjLKm6mLToepHT7r_Hi/view), it happens even on YT Music. Chrome 116.0.5845.141, with HW Acceleration on. I won't even bother trying w/o HW Acceleration, I'm sure it'll fix the issue.
(Wow by watching the screen capture, I realize that first the glitch isn't present on the screen recording, and that everything is shifted to the right even though in OBS it shows fine. The glitch I encountered was really weird: It was basically the game being in YouTube's video player, and constantly running on the left, exactly like in the Steam game's store page issue, just without black screen)
(Rerewatching the video, seems like the "shifting to the right" thing was only when I was watching it for the first time. Another, another graphic glitch with video players)

Black screens : When the game is running in the background and looking at a game's store page on Steam, I got intermittent black screens. [Video](https://drive.google.com/file/d/1xmCPAc9M8UifUn4OTJmkldhbefP-_hjE/view?usp=sharing). Seems like I even got one just right now, when I clicked on “Edit” this GitHub “Issue”

No eyebrows: Just no eyebrows, simple as that. [Doesn't seem like I'm the only one](https://www.reddit.com/r/IntelArc/comments/169f9qn/starfield_no_eyebrows_other_than_crashing_every/)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/44710c6d-6f5e-4b0d-9eb3-302d4471dffa)

Weird shadowing : There are shadows where there shouldn't be when using FSR2.2 at 100% render scale
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/c2a41dc1-655d-4ee6-af62-53e571956b14)

Crash : Another crash, when meeting Barrett for the first time. It crashed like 5 seconds after I had set the graphics to Ultra, no upscaling

Trailing shadows: It really looks like a very bad ray tracing artifact. When a character is moving, you'll see his shadow, but there is a trail behind this shadow as well

Crash : Another crash, when exiting the inventory menu while in Berrett's ship. Medium graphics, no FSR. After this crash, I can't launch. I could get EventViewer files with it : https://drive.google.com/file/d/1MtLfvybRmgMHy98_58IvhCGZ7G1vwzON/view?usp=sharing (it says that there are other log files, but I couldn't find them)

I'll stop playing the game for now, cause this is clearly completely broken, even with the driver that supposedly "fixed" the issues

### Device / Platform

ASUS Prime Z790-P WiFi D4

**Comment by Arturo-Intel** [comment]
@TheWonderfulTartiflette hi, thank you for the big list of cases you found. 
Please open one case for each of them, it would be a lot easier to track them

-- r2

**Comment by TheWonderfulTartiflette** [comment]
@Arturo-Intel sure I've done it thanks, I'll close this case now
