### ISSUE TITLE
Request to unlock perfomance tuning for arc mobile GPU's

### ISSUE THREAD

**Issue by muumilapsus** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#477]
### Application [Required]

Intel Arc Control Software

### Processor / Processor Number [Required]

i7-12700H

### Graphic Card [Required]

Intel Arc A770M

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Requesting intel's gpu team to unlock voltage and clock tuning on mobile arc gpu's.
This is possible on other gpu brands, and here's hoping it will be possible on Intel cards as well in the future.

Other than that, keep up the good work!

**Comment by Gabriela-Intel** [comment]
Thanks so much for taking the time to provide feedback @muumilapsus! :) We'll pass along the feedback.

@IGCIT Please close this issue.
