### ISSUE TITLE
Graphical glitch with YouTube's and Steam's video players when Starfield is running in the background

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#480]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

YouTube (Chrome), Steam

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 06.09.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12548058/Intel.SSU.06.09.2023.txt)

### Description and steps to reproduce [Required]

When Alt Tabbing out of the game, and opening a YouTube tab, you may see [this super weird glitch](https://drive.google.com/file/d/1Ms8tTcpOU5IWKqjLKm6mLToepHT7r_Hi/view), it happens even on YT Music. Chrome 116.0.5845.141, with HW Acceleration on. I won't even bother trying w/o HW Acceleration, I'm sure it'll fix the issue.
(Wow by watching the screen capture, I realize that first the glitch isn't present on the screen recording, and that everything is shifted to the right even though in OBS it shows fine. The glitch I encountered was really weird: It was basically the game being in YouTube's video player, and constantly running on the left, exactly like in the Steam game's store page issue, just without black screen)
(Rerewatching the video, seems like the "shifting to the right" thing was only when I was watching it for the first time. Another, another graphic glitch with video players)

This happens with Steam's video player as well like here https://drive.google.com/file/d/1xmCPAc9M8UifUn4OTJmkldhbefP-_hjE/view?usp=sharing (don't mojd the black screens)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Any

### Device / Platform name

ASUS PRIME Z790-P WiFi D4

**Comment by Karen-Intel** [comment]
Hey @TheWonderfulTartiflette has this behavior been reproducible w/driver v.4676?
Please let me know :)

Karen

**Comment by TheWonderfulTartiflette** [comment]
Sorry but I won't be able to try to replicate issues for Starfield, I refunded the game

**Comment by Karen-Intel** [comment]
@TheWonderfulTartiflette no worrries, I will be checking your other threads and let you know when the game is shipshape :D 

Karen

**Comment by Karen-Intel** [comment]
Hey @IGCIT can we close this one for the time being? I have not been able to repro the issue and the customer has refunded the game. Ty

Karen
