### ISSUE TITLE
Bad average performance in Starfield

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#481]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Starfield

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 06.09.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12547997/Intel.SSU.06.09.2023.txt)

### Description and steps to reproduce [Required]

40FPS on the lowest setting, w/o any upscaling. Typically, when I hit 40FPS in a game, it's on Cyberpunk, no upscaling, and everything set to maximum. Alongside this, I noticed that the game draws very little power, way more dramatic than Cyberpunk does, and I don't think that this would be considered “normal” here. Enabling the FSR2.2 upscaling only provides marginal gains (going from 30FPS to 35FPS, no upscaling and FSR2.2 51% render scale upscaling respectively)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/c72fa872-e66b-4b94-a7f2-29d7fe7cd43b)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Medium

### Device / Platform name

ASUS PRIME Z790-P WiFi D4

**Comment by Karen-Intel** [comment]
Hey @TheWonderfulTartiflette ty for reporting this :)
Just FYI it has been reported internally already and our development team is currently working on improving Starfield's overall FPS and performance.
Sharing intrenal tracking number FYI: 14020107573. If we have news sooner I'll let you know

Karen

**Comment by rmorera-intel** [comment]
Hi @TheWonderfulTartiflette sorry for not updating this in a while. Most performance issues with Starfield were fixed since driver 31.0.101.4887 and newer.
Please try it out and if you notice any other bug please file a new report.

Best Regards,
Ronald M.
