### ISSUE TITLE
Crashes in Starfield

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#484]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Starfield

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 06.09.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12548044/Intel.SSU.06.09.2023.txt)

### Description and steps to reproduce [Required]

 I crashed once just when waking up in the introduction scene after having touched the weird thing that made you unconscious. Nothing to report in EventViewer, nor in the Diagnostic Data Viewer.

Another crash, when meeting Barrett for the first time. It crashed like 5 seconds after I had set the graphics to Ultra, no upscaling

Another another crash, when exiting the inventory menu while in Berrett's ship. Medium graphics, no FSR. After this crash, I can't launch. I could get EventViewer files with it : https://drive.google.com/file/d/1MtLfvybRmgMHy98_58IvhCGZ7G1vwzON/view?usp=sharing (it says that there are other log files, but I couldn't find them)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Any

### Device / Platform name

ASUS PRIME Z790-P WiFi D4

**Comment by Karen-Intel** [comment]
Hi all!

FYI this behavior has been reported already and it is under investigation. As long as we have any update we will post it in this thread. Internal number for reference: 14020258162

Karen

**Comment by akarnokd** [comment]
Hi, sorry to interject here.

I have found a location which guaranteed crashes my game with `Current Render Pass:Transparency RenderPass`. It is supposed to be some kind of lavae.

i7 13700K, A770LE, 64GB RAM, Win 11. *Driver 4672 - this is the most stable for me.*

I've read driver 4676 fixed transparency rendering issues, however, it is unclear if that included crashes or just visual glitches.

My save: https://drive.google.com/file/d/1hdoSs09Cp-JZ1F8keynjqv68bfAzVuU5/view?usp=sharing

Go forward towards the natural formation.

**Comment by Karen-Intel** [comment]
Ty @akarnokd yeah I've been able to repro the crashes consistently with the latest version 4824 so we may need to wait for upcoming fixes.

Karen

**Comment by akarnokd** [comment]
Hi. Saw there is a new driver with stability fixes (4885). It may take some time before I can upgrade from 4672 so could someome verify if my save above and this save (Autonomous Dogstar Factory's lava pit) no longer crashes the driver? Thank you.

https://drive.google.com/file/d/1heT6HoBcQRzWVxyRhH865h7fOxEQucpq/view?usp=sharing

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/f0666a97-4b07-474f-b212-0d04980258bb)

**Comment by akarnokd** [comment]
Hi. I've installed the driver 4885 and checked both my saves above -> no crashes with them! Now I can look down:

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/6855178d-e763-4ae0-a2af-9b39b2315d48)

**Comment by Karen-Intel** [comment]
Yeei @akarnokd thank you for confirming!

I think the post owner doesn't have the game anymore so, I think we can close this one for the time being :)

@IGCIT Could you help closing this one? TY

Karen
