### ISSUE TITLE
Black screens when Starfield is in the background

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#485]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Starfield

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 06.09.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12548066/Intel.SSU.06.09.2023.txt)

### Description and steps to reproduce [Required]

When the game is running in the background and looking at a game's store page on Steam, I got intermittent black screens. [Video](https://drive.google.com/file/d/1xmCPAc9M8UifUn4OTJmkldhbefP-_hjE/view?usp=sharing). Seems like I even got one just right now, when I clicked on “Edit” this GitHub “Issue”

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Any

### Device / Platform name

ASUS PRIME Z790-P WiFi D4

**Comment by Karen-Intel** [comment]
Hey @TheWonderfulTartiflette have you spotted this behavior with other games or just Starfield?
Also, can you share if you have HDMI plugged or DP?
I mention this as I used to see this same behavior in a system that had a driver that had not be cleaned with DDU for a while and it was necessary to use it

Please let me know, thanks

Karen

**Comment by TheWonderfulTartiflette** [comment]
No, it's the first game with such an issue, and I'm on DP

**Comment by Arturo-Intel** [comment]
@TheWonderfulTartiflette Do you still seeing this behavior in your end?

**Comment by TheWonderfulTartiflette** [comment]
@Arturo-Intel Sorry, it's been a long time now since I refunded the game, maybe other people could help you

**Comment by Arturo-Intel** [comment]
Its ok, thanks for the quick response

**Comment by akarnokd** [comment]
> maybe other people could help you

FWIW,

Playing Starfield since 4672, now on 5186. I never encountered this singal loss when tabbed out. On one occasion with driver 4885, I had a short signal loss while inside the game. Luckily, never since with the game. 

In general, I had some random signal loss which appears to have been due to having a website open (Netflix, AppleTV+, Spotify, Amazon Prime) that requires HDCP compliant monitor (mine isn't).

1920x1080 60Hz HDMI 1.4a monitor, i7 13700K, A770LE, Windows 11 22H2 & 23H2.
