### ISSUE TITLE
No eyebrows in Starfield

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#486]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Starfield

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 06.09.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12548078/Intel.SSU.06.09.2023.txt)

### Description and steps to reproduce [Required]

Just no eyebrows, simple as that. [Doesn't seem like I'm the only one](https://www.reddit.com/r/IntelArc/comments/169f9qn/starfield_no_eyebrows_other_than_crashing_every/)

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Any

### Device / Platform name

ASUS PRIME Z790-P WiFi D4

**Comment by Sherlocatt** [comment]
I have this issue too.

**Comment by Karen-Intel** [comment]
Hi guys!

@TheWonderfulTartiflette ty for your report :)

Intel is already aware of this issue and working hard on getting the best experience for you in Starfield
Sharing internal bug ID just for tracking purposes: 14020258116. 
Any update about changes we will let you know in this thread :)

Karen

**Comment by Karen-Intel** [comment]
Hey @TheWonderfulTartiflette good news!

I bring you a fresh driver[ v.4676](https://www.intel.com/content/www/us/en/download/785597/788015/intel-arc-iris-xe-graphics-windows.html) where I can see significant improvement in the eyebrows

Could you help me verify these improvements and also update the other threads if they are still present or not? TY

Karen

**Comment by Code-Vlue** [comment]
@Karen-Intel Checked on an A750 with the newest driver and looks like my character has eyebrows now.

**Comment by IGCIT** [comment]
closing as fixed in driver 4676
