### ISSUE TITLE
Crashing during landing cinematic - Planet Jemison

### ISSUE THREAD

**Issue by hugh0269** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#490]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Starfield

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 9 7900x

### Graphic Card [Required]

Intel Arc A770 16GB (Intel LE)

### GPU Driver Version [Required]

- [X] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12553980/ssulog.txt)

### Description and steps to reproduce [Required]

Unable to land at any marked location on the planet Jemison, particularly new Atlantis city. Game consistently will crash during the landing cinematic even when tested at a variety of settings (at at monitor native 4k, and 100% scaled and 50% scaled 1080p), it appears that reducing settings may loosely correlates with the cinematic playing longer before a crash. I haven't tested if this behavior persists with other locations, saves, or characters.

I located and attached some 'GPU crash logs' from game files. The final crash was observed running the game (and monitor) at 1080p with FSR running at 50% (as per provided game settings)

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [x] Fullscreen
- [ ] Windowed
- [x] Borderless Windowed

### Detailed game settings [Required]

<img width="425" alt="final settings 1" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/34612798/eaf7a863-e9d6-48ac-aead-2ce05f24df25">
<img width="428" alt="final settings 2" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/34612798/d349b25f-e476-41df-b44d-7baac4f66d19">

### Device / Platform name

Custom Build ATX Desktop PC

### Crash dumps [Required, if applicable]

[GPU_CRASH__2023_9_8_7_51.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12553939/GPU_CRASH__2023_9_8_7_51.zip)
[GPU_CRASH__2023_9_8_8_2.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12553940/GPU_CRASH__2023_9_8_8_2.zip)
[GPU_CRASH__2023_9_8_8_4.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12553941/GPU_CRASH__2023_9_8_8_4.zip)
[GPU_CRASH__2023_9_8_7_44.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12553942/GPU_CRASH__2023_9_8_7_44.zip)
[GPU_CRASH__2023_9_8_7_47.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12553943/GPU_CRASH__2023_9_8_7_47.zip)
[GPU_CRASH__2023_9_8_7_48.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12553944/GPU_CRASH__2023_9_8_7_48.zip)

### Save game

[Quicksave0_73BA0AF3_48656E7279_000329_20230906112250_3_0_4.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12553954/Quicksave0_73BA0AF3_48656E7279_000329_20230906112250_3_0_4.zip)

**Comment by hugh0269** [comment]
Noticed Windows had silently installed different AMD driver than expected (for CPU on board graphics). Reinstalled AMD recommended drivers and was still able to repeat the crash (identical settings to original report)
[ssulog-updated.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12554048/ssulog-updated.txt)

**Comment by hugh0269** [comment]
yeah the issue is not resolved I'm just dumb

> Noticed Windows had silently installed different AMD driver than expected (for CPU on board graphics). Reinstalled AMD recommended drivers and was still able to repeat the crash (identical settings to original report) [ssulog-updated.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12554048/ssulog-updated.txt)

**Comment by Ilya-intel** [comment]
Hey @hugh0269 ,
The game was recently updated with a patch, do you still see the issue?

**Comment by Ilya-intel** [comment]
@IGCIT 
Case seems to be abandoned. Please close it.
