### ISSUE TITLE
Arc Control Performance Tuning sets different settings after driver update.

### ISSUE THREAD

**Issue by Code-Vlue** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#491]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Arc Control

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4676
- [X] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12562976/ssulog.txt)

### Description and steps to reproduce [Required]

I have settings that I use from time to time with performance tuning, 33 on performance and max on power limit, on driver update the last 2 drivers it sets the settings to, stock power limit, +40mV and 32 on performance slider.

**Comment by Code-Vlue** [comment]
With the most recent 4824 drivers it seems that the performance tuning settings stayed the same after driver update.

**Comment by Karen-Intel** [comment]
@Code-Vlue TY for the clarification. Can we consider this issue as solved? TY

Karen

**Comment by Code-Vlue** [comment]
@Karen-Intel Yes the issue is resolved, thank you!

**Comment by Karen-Intel** [comment]
@IGCIT can you do the honors please? Thanks!

Karen
