### ISSUE TITLE
Battlefield 2042 Hair Rendered Improperly

### ISSUE THREAD

**Issue by Code-Vlue** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#493]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Battlefield 2042

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12564453/ssulog.txt)

### Description and steps to reproduce [Required]

Hair seems to be rendered improperly on some characters in game.
![Screenshot 2023-09-08 215112](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/142824040/a60cebea-d9eb-4bf6-9ba1-bc7c808a484e)
![Screenshot 2023-09-08 215121](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/142824040/eea58133-1f8b-4995-ab57-bdd2005deb2d)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

All Ultra quality with HBAO, Low High Fidelity Objects, and Raytracing off.

**Comment by Code-Vlue** [comment]
Issue is now resolved as of driver 4826.

**Comment by Code-Vlue** [comment]
Reopening issue, issue seems to still occur after some more in game testing.

**Comment by Joseph-Intel** [comment]
hi @Code-Vlue Have you seen this issue on the latest driver V1014972?

**Comment by Code-Vlue** [comment]
> hi @Code-Vlue Have you seen this issue on the latest driver V1014972?

Sorry I actually don't have an Arc GPU to be able to check anymore.

**Comment by IGCIT** [comment]
closing since OP cannot test anymore, if someone else come in with the same issue, we will reopen
