### ISSUE TITLE
Valorant Shuttering and no Multithereading

### ISSUE THREAD

**Issue by Emijor** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#494]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Valorant

### Processor / Processor Number [Required]

Intel i5 13600K

### Graphic Card [Required]

Intel Arc A770 Limited Edition

### GPU Driver Version [Required]

- [X] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12565294/ssulog.txt)

### Description and steps to reproduce [Required]

Just install the Intel Arc A770 Graphicscard into Ur pc and install Valorant and go for a round. for the Multithreading option go to Settings and then go to Video and then u can see the Multithreading Option is missing.

**Comment by IGCIT** [comment]
hi @Emijor 

multi-threading is not yet supported, see #248

**Comment by Emijor** [comment]
ahh i see , thank you!

**Comment by Karen-Intel** [comment]
@Emijor can we close this case then? Please let us know. Thanks

Karen

**Comment by Emijor** [comment]
yes. please
