### ISSUE TITLE
Crash in FH5

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#495]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Forza Horizon 5

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 09.09.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12565900/Intel.SSU.09.09.2023.txt)

### Description and steps to reproduce [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/03243a8b-1724-49ed-9e32-c6d93c5abe8d)
First time I've encountered this bug since 4676. May be related, but not entirely sure

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Max, XeSS Ultra Quality

**Comment by TheWonderfulTartiflette** [comment]
And Arc Control Assist crashes as well
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/aca51721-695f-4409-b905-02ee23fd50dc)

**Comment by TheWonderfulTartiflette** [comment]
When looking at the Diagnostic Data Viewer, even Desktop Windows Manager crashes. Whenever I launch the game, it always crashes, I can't seem to avoid the crash

**Comment by TheWonderfulTartiflette** [comment]
[Yay, another crash](https://drive.google.com/drive/folders/1Mvej1XG6a-cp2IWt1wkbNXMyJhrnx1Vu?usp=sharing)

**Comment by Arturo-Intel** [comment]
Can you share your game settings pls?
I cant reproduce it at all. I can play the game with any trouble

**Comment by TheWonderfulTartiflette** [comment]
Seems like I crashed even though XeSS was disabled on launch
https://drive.google.com/file/d/1KOIb3gMJe02jJ6AuSM9RA5anLhvxyc2k/view?usp=sharing

**Comment by Karen-Intel** [comment]
Hi all! Doing some recent testing w/driver v/4826 and no crashes at all in FH5 after playing for more than 20 minutes
MSAA 8x XeSS disabled 4k Res
Might be related to local configuration. @TheWonderfulTartiflette if you haven't updated your driver with DDU please do so and let us know when you have done it. Ty

Karen

**Comment by TheWonderfulTartiflette** [comment]
@Karen-Intel Sorry, even with a DDU, didn't fix anything. These Diagnostic Data Viewer infos might help?
Exception code : 0xc0000005
Error offset : 0x0000000000922d12
Failing process ID : 0x0x7444

**Comment by TheWonderfulTartiflette** [comment]
[Intel SSU 20.09.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12672923/Intel.SSU.20.09.2023.txt)
And an SSU, in case my PC has changed since

**Comment by TheWonderfulTartiflette** [comment]
[Again, crashing (cannot start the game at all), and now the error window is making my Windows freak out](https://drive.google.com/file/d/16p0aqGFd7o71THMhq5cJYVbulkz5AuXm/view?usp=sharing)
(the bugged rectangle zone is where the error window is located)

**Comment by TheWonderfulTartiflette** [comment]
I'd relly need help on this one please, even reinstalling the whole game doesn't do anything, I cannot start it at all

**Comment by TheWonderfulTartiflette** [comment]
I really don't want to look like I'm forcing, but I'm still having issues even with the latest driver. Here's an EventViewer file : https://drive.google.com/file/d/1NLOdmVtOa3TjLaqUBO38ngwnkVQDQ2Li/view?usp=sharing

**Comment by Karen-Intel** [comment]
Hi @TheWonderfulTartiflette we have done several testing with the latest 3 driver versions (current + regressions) and we are unable to repro the same behavior at all. Have you tried checking your OS integrity? You can also attempt creating a new user session and give it a go or test your card in another system and see how it behaves.

I had similar issues in an older system a while ago and had to install the OS from scratch as the card was working fine in another computer. Perhaps you have to do that if you haven't done it yet. Let us know if there's anything we can do to help!

Karen

**Comment by TheWonderfulTartiflette** [comment]
@Karen-Intel I've tried it with a new user on my PC, and exact same result. I've provided a ton of logs and crashdumps, so maybe you could look into them to figure what's wrong with the card?

**Comment by Arturo-Intel** [comment]
@TheWonderfulTartiflette 
The mayor problem here (and almost all of the other cases you open) is that we are unable to reproduce it. 
There is a good amount of log/video evidence provided to prove this.
I appreciate a lot the info you share but we can't go and create cases without any replication from our lab.

And without replication, seems to be the problem is in your local, that's why Karen suggested to test your card in other system to verify this theory.

Please go ahead and try it,
--r2

**Comment by TheWonderfulTartiflette** [comment]
Deeply sorry for this, it seems that it was MSI Afterburner who caused problems with FH5, I should have been more careful about the apps running that could interfere, sorry for so much time wasted

**Comment by Arturo-Intel** [comment]
@TheWonderfulTartiflette 
no worries at all, glad it is all working as expected.
