### ISSUE TITLE
CSGO Crash

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#496]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Counter-Strike: Global Offensive

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 09.09.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12566640/Intel.SSU.09.09.2023.txt)

### Description and steps to reproduce [Required]

Not much to say, just crashed while I was playing, no error code but a EventViewer file

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Max

### Crash dumps [Required, if applicable]

https://drive.google.com/file/d/1MvV4psJWLDbrtJbG_NUuu1tfUZLoIaSA/view?usp=sharing

**Comment by Arturo-Intel** [comment]
Hi @TheWonderfulTartiflette, this crash happens only once? or its recurring?

**Comment by TheWonderfulTartiflette** [comment]
@Bryce-7995 clearly it's not the first time that my CSGO is crashing
But I cannot say for sure that the EventViewer files are the same/that the cause of the crash is the same

**Comment by Arturo-Intel** [comment]
Ok, got it, ty for the info

**Comment by Arturo-Intel** [comment]
@TheWonderfulTartiflette is this the same issue as #444 ?

**Comment by TheWonderfulTartiflette** [comment]
No not that much. In #444, the game freezes but doesn't crash by itself, whereas here, it closes by itself

**Comment by freak2fast4u** [comment]
Crash still occuring on 4826 beta drivers.

Sadly, in the folder containing the csgo.exe file, the .mdmp files are empty (0KB in size), so no useful information to extract from there.

evtx file for reference (prolly not super useful at this point) : [csgo_dangerzone_crash_1.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12701254/csgo_dangerzone_crash_1.zip)

The problem seems to happen more frequently in the "Danger Zone" game mode.

**Comment by Gabriela-Intel** [comment]
Hi @freak2fast4u! Have you checked out the issue with CS2 using the latest drivers? I'm sure you noticed that CS2 has totally replaced CSGO so let us know if you continue to see the issue with CS2.

**Comment by freak2fast4u** [comment]
This issue is indeed moot now, and I already opened another crash issue later for CS2 with mdmp files here : https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/532 (not the same problem).

**Comment by Gabriela-Intel** [comment]
I'll take a look at the other issue :)

@IGCIT You can close this one out. Thanks!
