### ISSUE TITLE
Topaz AI version 2.0.0 Crashes on ARC 770 (4676)

### ISSUE THREAD

**Issue by mkohlman** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#498]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Topaz AI - Version 2.0.0

### Processor / Processor Number [Required]

11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz / BFEBFBFF000A0671

### Graphic Card [Required]

ASRock Phantom Gaming Arc A770 8GB - BIOS 20.1064.0

### GPU Driver Version [Required]

- [X] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

# SSU Scan Information
Scan Info:
 Version:"2.5.0.34"
 Date:"09/09/2023"
 Time:"00:00:22.0734741"

# Scanned Hardware
Computer:
          BaseBoard Manufacturer:"ASUSTeK COMPUTER INC."
          BIOS Mode:"UEFI"
          BIOS Version/Date:"American Megatrends Inc. 1701 , 12/12/2022 12:00 AM"
          CD or DVD:"HL-DT-ST BD-RE  WH16NS60"
          Embedded Controller Version:"255.255"
          Platform Role:"Desktop"
          Processor:"11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz , GenuineIntel"
          Secure Boot State:"Off"
          SMBIOS Version:"3.3"
          Sound Card:"NVIDIA Virtual Audio Device (Wave Extensible) (WDM)"
          Sound Card:"USB Audio Device"
          Sound Card:"Realtek High Definition Audio"
          System Manufacturer:"ASUS"
          System Model:"System Product Name"
          System SKU:"SKU"
          System Type:"x64-based PC"
          - "Display"
               Intel ® Graphics Driver Version:"27.20.100.9466"
               - "Intel(R) Arc(TM) A770 Graphics"
                    Adapter Compatibility:"Intel Corporation"
                    Adapter DAC Type:"Internal"
                    Adapter RAM:"1.00 GB"
                    Availability:"Running or Full Power"
                    Bits Per Pixel:"32"
                    - "Caption":"Intel(R) Arc(TM) A770 Graphics"
                         Link:"http://www.intel.com/content/www/us/en/search.html?keyword=Arc+A770+Graphics"
                    CoInstallers:"oem123.inf,iDG2_Client_FWU_w10_DS,Internal,Intel(R) Arc(TM) A770 Graphics Family"
                    Color Table Entries:"4294967296"
                    Dedicated Video Memory:"Not Available"
                    Driver:"igdkmdnd64.sys"
                    Driver Date:"09/06/2023 05:00 PM"
                    Driver Path:"C:\WINDOWS\system32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_92631f344de8baad\igdkmdnd64.sys"
                    Driver Provider:"Intel Corporation"
                    Driver Version:"31.0.101.4676"
                    INF:"oem123.inf"
                    INF Section:"iDG2_Client_FWU_w10_DS"
                    Install Date:"Not Available"
                    Installed Drivers:"C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_92631f344de8baad\igdumdim64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_92631f344de8baad\igd10iumd64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_92631f344de8baad\igd10iumd64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_92631f344de8baad\igd12umd64.dll"
                    Last Error Code:"Not Available"
                    Last Error Code Description:"Not Available"
                    Last Reset:"Not Available"
                    Location:"PCI bus 3, device 0, function 0"
                    Manufacturer:"Intel Corporation"
                    Microsoft DirectX* Version:"DirectX 12"
                    Monochrome:"No"
                    Number of Colors:"4294967296"
                    Number of Video Pages:"Not Available"
                    PNP Device ID:"PCI\VEN_8086&DEV_56A0&SUBSYS_60011849&REV_08\6&2445A8C7&0&00080008"
                    Power Management Capabilities:"Not Available"
                    Power Management Supported:"Not Available"
                    Refresh Rate - Current:"119 Hz"
                    Refresh Rate - Maximum:"120 Hz"
                    Refresh Rate - Minimum:"59 Hz"
                    Resolution:"5120 X 1440"
                    Scan Mode:"Noninterlaced"
                    Service Name:"igfxnd"
                    Status:"OK"
                    Video Architecture:"VGA"
                    Video Memory:"Unknown"
                    Video Processor:"Intel(R) Arc(TM) A770 Graphics Family"
          - "Memory"
               Physical Memory (Available):"18.72 GB"
               Physical Memory (Installed):"32 GB"
               Physical Memory (Total):"31.80 GB"
               - "BANK 0"
                    Capacity:"16 GB"
                    Channel:"Controller0-ChannelA-DIMM1"
                    Configured Clock Speed:"3600 MHz"
                    Configured Voltage:"1200 millivolts"
                    Data Width:"64 bits"
                    Form Factor:"DIMM"
                    Interleave Position:"First position"
                    Manufacturer:"G Skill Intl"
                    Maximum Voltage:"Not Available"
                    Memory Type:"Unknown"
                    Minimum Voltage:"Not Available"
                    Part Number:"F4-3600C16-16GTZNC"
                    Serial Number:"00000000"
                    Status:"Not Available"
                    Type:"Synchronous"
               - "BANK 1"
                    Capacity:"16 GB"
                    Channel:"Controller0-ChannelB-DIMM1"
                    Configured Clock Speed:"3600 MHz"
                    Configured Voltage:"1200 millivolts"
                    Data Width:"64 bits"
                    Form Factor:"DIMM"
                    Interleave Position:"Second position"
                    Manufacturer:"G Skill Intl"
                    Maximum Voltage:"Not Available"
                    Memory Type:"Unknown"
                    Minimum Voltage:"Not Available"
                    Part Number:"F4-3600C16-16GTZNC"
                    Serial Number:"00000000"
                    Status:"Not Available"
                    Type:"Synchronous"
          - "Motherboard"
               Availability:"Running or Full Power"
               BIOS:"1701, ALASKA - 1072009"
               Caption:"Motherboard"
               - "Chipset":"Intel(R)"
                    Link:"http://www.intel.com/content/www/us/en/search.html?keyword="
               Date:"12/11/2022 04:00 PM"
               Install Date:"Not Available"
               Last Error Code:"Not Available"
               Last Error Code Description:"Not Available"
               Manufacturer:"ASUSTeK COMPUTER INC."
               Model:"Not Available"
               Part Number:"Not Available"
               PNP Device ID:"Not Available"
               Power Management Capabilities:"Not Available"
               Power Management Supported:"Not Available"
               Product:"PRIME Z590-A"
               Serial Number:"210179478403743"
               Status:"OK"
               Version:"Rev 1.xx"
          - "Networking"
               Intel ® Network Connections Install Options:"Not Available"
               Intel ® Network Connections Version:"Not Available"
               Intel ® PROSet/Wireless Software Version:"Not Available"
               - "Bluetooth Device (Personal Area Network)"
                    Availability:"Running or Full Power"
                    Caption:"Bluetooth Device (Personal Area Network)"
                    CoInstallers:"Not Available"
                    Default IP Gateway:"Not Available"
                    DHCP Enabled:"Yes"
                    DHCP Lease Expires:"Not Available"
                    DHCP Lease Obtained:"Not Available"
                    DHCP Server:"Not Available"
                    Driver:"bthpan.sys"
                    Driver Date:"06/21/2006 12:00 AM"
                    Driver Path:"C:\WINDOWS\system32\drivers\bthpan.sys"
                    Driver Provider:"Microsoft"
                    Driver Version:"10.0.22621.1610"
                    Index:"0002"
                    INF:"bthpan.inf"
                    INF Section:"BthPan.Install"
                    Install Date:"Not Available"
                    Installed:"Yes"
                    IP Address:"Not Available"
                    IP Subnet:"Not Available"
                    Last Error Code:"Not Available"
                    Last Error Code Description:"Not Available"
                    Last Reset:"09/09/2023 08:39 AM"
                    Location:"Not Available"
                    MAC Address:"00:E0:4C:70:07:03"
                    Manufacturer:"Microsoft"
                    Net Connection ID:"Bluetooth Network Connection"
                    NetCfgInstanceId:"{291AE2FE-E093-4DF4-985A-5A0E3714AD81}"
                    PNP Device ID:"BTH\MS_BTHPAN\7&155AC7C&0&2"
                    Port:"Not Available"
                    Power Management (Low Power):"Not Available"
                    Power Management (Wake On LAN):"Not Available"
                    Power Management (Wake on Magic Packet):"Not Available"
                    Power Management Capabilities:"Not Available"
                    Power Management Supported:"No"
                    Product Type:"Bluetooth Device (Personal Area Network)"
                    Service Name:"BthPan"
                    Status:"Enabled"
                    Type:"Ethernet 802.3"
                    - "Service Bindings"
                         Client for Microsoft Networks:
                         File and Printer Sharing for Microsoft Networks:
                         Internet Protocol Version 4 (TCP/IPv4):
                         Internet Protocol Version 6 (TCP/IPv6):
                         Link-Layer Topology Discovery Mapper I/O Driver:
                         Link-Layer Topology Discovery Responder:
                         Microsoft LLDP Protocol Driver:
                         VMware Bridge Protocol:
               - "Intel(R) Ethernet Controller (3) I225-V #2"
                    Availability:"Running or Full Power"
                    - "Caption":"Intel(R) Ethernet Controller (3) I225-V #2"
                         Link:"http://www.intel.com/content/www/us/en/search.html?keyword=Ethernet+Controller+(3)+I225+V+%232"
                    CoInstallers:"Not Available"
                    Default IP Gateway:"172.31.31.1"
                    DHCP Enabled:"Yes"
                    DHCP Lease Expires:"09/10/2023 08:39 AM"
                    DHCP Lease Obtained:"09/09/2023 08:39 AM"
                    DHCP Server:"172.31.31.1"
                    Driver:"e2fn.sys"
                    Driver Date:"06/29/2023 12:00 AM"
                    Driver Path:"C:\WINDOWS\system32\DriverStore\FileRepository\e2fn.inf_amd64_fcb868ac03f43b71\e2fn.sys"
                    Driver Provider:"Intel"
                    Driver Version:"2.1.3.15"
                    ETrackID:"Not Available"
                    Index:"0014"
                    INF:"oem96.inf"
                    INF Section:"I225.10.0.1..21390"
                    Install Date:"Not Available"
                    Installed:"Yes"
                    IP Address:"172.31.31.31;fe80::50cb:6901:a898:8240"
                    IP Subnet:"255.255.255.0;64"
                    Last Error Code:"Not Available"
                    Last Error Code Description:"Not Available"
                    Last Reset:"09/09/2023 08:39 AM"
                    Location:"PCI bus 7, device 0, function 0"
                    MAC Address:"F0:2F:74:AD:49:34"
                    Manufacturer:"Intel"
                    Net Connection ID:"Ethernet 2"
                    NetCfgInstanceId:"{E69403EF-89E4-4F8E-BB10-7EC56DA3AFE9}"
                    NVM Version:"Not Available"
                    Part Number:"Not Available"
                    PNP Device ID:"PCI\VEN_8086&DEV_15F3&SUBSYS_87D21043&REV_03\F02F74FFFFAD493400"
                    Port:"Not Available"
                    Power Management (Low Power):"Active: Yes, Enable: Yes"
                    Power Management (Wake On LAN):"Active: Yes, Enable: Yes"
                    Power Management (Wake on Magic Packet):"Active: Yes, EnableWakeOnMagicPacketOnly: No"
                    Power Management Capabilities:"Not Available"
                    Power Management Supported:"No"
                    Product Type:"Intel(R) Ethernet Controller (3) I225-V"
                    Service Name:"e2fnexpress"
                    Status:"Enabled"
                    Type:"Ethernet 802.3"
                    - "Service Bindings"
                         Bridge Driver:
                         Client for Microsoft Networks:
                         File and Printer Sharing for Microsoft Networks:
                         Internet Protocol Version 4 (TCP/IPv4):
                         Internet Protocol Version 6 (TCP/IPv6):
                         Link-Layer Topology Discovery Mapper I/O Driver:
                         Link-Layer Topology Discovery Responder:
                         Microsoft LLDP Protocol Driver:
                         QoS Packet Scheduler:
                         VMware Bridge Protocol:
                    - "Settings"
                         *FlowControl:Flow Control:"Unknown (4)"
                         *IdleRestriction:Idle power down restriction:"Disabled (0)"
                         *InterruptModeration:Interrupt Moderation:"Enabled (1)"
                         *IPChecksumOffloadIPv4:IPv4 Checksum Offload:"Rx & Tx Enabled (3)"
                         *JumboPacket:Jumbo Packet:"Disabled (1514)"
                         *LsoV2IPv4:Large Send Offload V2 (IPv4):"Enabled (1)"
                         *LsoV2IPv6:Large Send Offload V2 (IPv6):"Enabled (1)"
                         *PMARPOffload:ARP Offload:"Enabled (1)"
                         *PMNSOffload:NS Offload:"Enabled (1)"
                         *PriorityVLANTag:Packet Priority & VLAN:"Packet Priority & VLAN Enabled (3)"
                         *SpeedDuplex:Speed & Duplex:"Auto Negotiation (0)"
                         *TCPChecksumOffloadIPv4:TCP Checksum Offload (IPv4):"Rx & Tx Enabled (3)"
                         *TCPChecksumOffloadIPv6:TCP Checksum Offload (IPv6):"Rx & Tx Enabled (3)"
                         *UDPChecksumOffloadIPv4:UDP Checksum Offload (IPv4):"Rx & Tx Enabled (3)"
                         *UDPChecksumOffloadIPv6:UDP Checksum Offload (IPv6):"Rx & Tx Enabled (3)"
                         *WakeOnMagicPacket:Wake on Magic Packet:"Enabled (1)"
                         *WakeOnPattern:Wake on Pattern Match:"Enabled (1)"
                         ITR:Interrupt Moderation Rate:"Low (64)"
                         WakeOnMagicPacketFromS5:Wake On Magic Packet From S5:"Enabled (1)"
               - "VMware Virtual Ethernet Adapter for VMnet1"
                    Availability:"Running or Full Power"
                    Caption:"VMware Virtual Ethernet Adapter for VMnet1"
                    CoInstallers:"vnetinst.dll,VNL_AdapterCoinstaller"
                    Default IP Gateway:"Not Available"
                    DHCP Enabled:"No"
                    DHCP Lease Expires:"Not Available"
                    DHCP Lease Obtained:"Not Available"
                    DHCP Server:"Not Available"
                    Driver:"vmnetadapter.sys"
                    Driver Date:"01/03/2023 12:00 AM"
                    Driver Path:"C:\WINDOWS\system32\DRIVERS\vmnetadapter.sys"
                    Driver Provider:"VMware, Inc."
                    Driver Version:"14.0.0.7"
                    Index:"0003"
                    INF:"oem19.inf"
                    INF Section:"VMnetAdapter1.Install"
                    Install Date:"Not Available"
                    Installed:"Yes"
                    IP Address:"172.31.33.1;fe80::369a:6609:8dea:e723"
                    IP Subnet:"255.255.255.0;64"
                    Last Error Code:"Not Available"
                    Last Error Code Description:"Not Available"
                    Last Reset:"09/09/2023 08:39 AM"
                    Location:"Not Available"
                    MAC Address:"00:50:56:C0:00:01"
                    Manufacturer:"VMware, Inc."
                    Net Connection ID:"VMware Network Adapter VMnet1"
                    NetCfgInstanceId:"{DB64DF33-AA30-4B9D-882E-B2582891877B}"
                    PNP Device ID:"ROOT\VMWARE\0000"
                    Port:"Not Available"
                    Power Management (Low Power):"Not Available"
                    Power Management (Wake On LAN):"Not Available"
                    Power Management (Wake on Magic Packet):"Not Available"
                    Power Management Capabilities:"Not Available"
                    Power Management Supported:"No"
                    Product Type:"VMware Virtual Ethernet Adapter for VMnet1"
                    Service Name:"VMnetAdapter"
                    Status:"Enabled"
                    Type:"Ethernet 802.3"
                    - "Service Bindings"
                         Client for Microsoft Networks:
                         File and Printer Sharing for Microsoft Networks:
                         Internet Protocol Version 4 (TCP/IPv4):
                         Internet Protocol Version 6 (TCP/IPv6):
                         Link-Layer Topology Discovery Mapper I/O Driver:
                         Link-Layer Topology Discovery Responder:
                         Microsoft LLDP Protocol Driver:
                    - "Settings"
                         *JumboPacket:Jumbo Packet:"Disabled (1514) (1514)"
                         *PriorityVLANTag:Priority / VLAN tag:"Priority & VLAN Enabled (3)"
                         *WakeOnMagicPacket:Wake on magic packet:"Enabled (1)"
                         *WakeOnPattern:Wake on pattern match:"Enabled (1)"
                         EnableWakeOnLan:Wake on LAN:"Enabled (1)"
               - "VMware Virtual Ethernet Adapter for VMnet8"
                    Availability:"Running or Full Power"
                    Caption:"VMware Virtual Ethernet Adapter for VMnet8"
                    CoInstallers:"vnetinst.dll,VNL_AdapterCoinstaller"
                    Default IP Gateway:"Not Available"
                    DHCP Enabled:"No"
                    DHCP Lease Expires:"Not Available"
                    DHCP Lease Obtained:"Not Available"
                    DHCP Server:"Not Available"
                    Driver:"vmnetadapter.sys"
                    Driver Date:"01/03/2023 12:00 AM"
                    Driver Path:"C:\WINDOWS\system32\DRIVERS\vmnetadapter.sys"
                    Driver Provider:"VMware, Inc."
                    Driver Version:"14.0.0.7"
                    Index:"0004"
                    INF:"oem19.inf"
                    INF Section:"VMnetAdapter8.Install"
                    Install Date:"Not Available"
                    Installed:"Yes"
                    IP Address:"172.31.32.1;fe80::5b6e:1666:f8bf:a6cd"
                    IP Subnet:"255.255.255.0;64"
                    Last Error Code:"Not Available"
                    Last Error Code Description:"Not Available"
                    Last Reset:"09/09/2023 08:39 AM"
                    Location:"Not Available"
                    MAC Address:"00:50:56:C0:00:08"
                    Manufacturer:"VMware, Inc."
                    Net Connection ID:"VMware Network Adapter VMnet8"
                    NetCfgInstanceId:"{E61C78E1-ECC9-41D0-BC81-B9B717C97930}"
                    PNP Device ID:"ROOT\VMWARE\0001"
                    Port:"Not Available"
                    Power Management (Low Power):"Not Available"
                    Power Management (Wake On LAN):"Not Available"
                    Power Management (Wake on Magic Packet):"Not Available"
                    Power Management Capabilities:"Not Available"
                    Power Management Supported:"No"
                    Product Type:"VMware Virtual Ethernet Adapter for VMnet8"
                    Service Name:"VMnetAdapter"
                    Status:"Enabled"
                    Type:"Ethernet 802.3"
                    - "Service Bindings"
                         Client for Microsoft Networks:
                         File and Printer Sharing for Microsoft Networks:
                         Internet Protocol Version 4 (TCP/IPv4):
                         Internet Protocol Version 6 (TCP/IPv6):
                         Link-Layer Topology Discovery Mapper I/O Driver:
                         Link-Layer Topology Discovery Responder:
                         Microsoft LLDP Protocol Driver:
                    - "Settings"
                         *JumboPacket:Jumbo Packet:"Disabled (1514) (1514)"
                         *PriorityVLANTag:Priority / VLAN tag:"Priority & VLAN Enabled (3)"
                         *WakeOnMagicPacket:Wake on magic packet:"Enabled (1)"
                         *WakeOnPattern:Wake on pattern match:"Enabled (1)"
                         EnableWakeOnLan:Wake on LAN:"Enabled (1)"
          - "Operating System"
               .Net Framework Version:"2.0,3.0,3.5,4.0,4.8"
               Boot Device:"\Device\HarddiskVolume5"
               Internet Browser:"Google Chrome,116.0, Internet Explorer,11.1, Microsoft Edge,116.0"
               Locale:"United States"
               OS Manufacturer:"Microsoft Corporation"
               OS Name:"Microsoft Windows 11 Pro"
               Other OS Description:"Not Available"
               Page File:"C:\pagefile.sys"
               Page File Space:"5.00 GB"
               Physical Memory (Available):"18.73 GB"
               Physical Memory (Installed):"32 GB"
               Physical Memory (Total):"31.80 GB"
               System Directory:"C:\WINDOWS\system32"
               Version:"10.0.22631 Build 22631"
               Virtual Memory (Available):"19.53 GB"
               Virtual Memory (Total):"36.80 GB"
               Windows Directory:"C:\WINDOWS"
               - "Installed Updates"
                    KB2151757:"Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219 [7/3/2022]"
                    KB2467173:"Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219 [7/3/2022]"
                    KB2468871:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2468871:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2468871v2:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2468871v2:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2478063:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2478063:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2533523:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2533523:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2544514:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2544514:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2600211:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB2600211:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2600217:"Microsoft .NET Framework 4 Extended [Not Available]"
                    KB2600217:"Microsoft .NET Framework 4 Client Profile [Not Available]"
                    KB5012170:"Security Update [12/7/2022]"
                    KB5018863:"Update [10/28/2022]"
                    KB5023595:"Update [3/7/2023]"
                    KB5027397:"Update [9/7/2023]"
                    KB5028948:"Update [8/9/2023]"
                    KB5030316:"Update [9/7/2023]"
                    KB5030318:"Update [9/6/2023]"
                    KB982573:"Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219 [7/3/2022]"
                    Microsoft ASP.NET Core 7.0.10 - Shared Framework (x64):".NET [8/16/2023]"
                    Microsoft ASP.NET Core 7.0.7 - Shared Framework (x64):".NET [8/27/2023]"
                    SP1:"Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219 [Not Available]"
          - "Processor"
               - "11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz"
                    Architecture:"x64"
                    ATPO:"Not Available"
                    Availability:"Running or Full Power"
                    Caption:"Intel64 Family 6 Model 167 Stepping 1"
                    - "Chipset Name":"11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz"
                         Link:"http://www.intel.com/content/www/us/en/search.html?keyword=11th+Gen++Core+i7+11700K+"
                    CPU Speed:"3.60 GHz"
                    Current Voltage:"1.6 volts"
                    Driver:"Not Available"
                    Driver Date:"04/21/2009 12:00 AM"
                    Driver Path:"C:\WINDOWS\system32\drivers\intelppm.sys"
                    Driver Provider:"Microsoft"
                    Driver Version:"10.0.22621.2048"
                    Ext. Family:"Not Available"
                    Family:"Intel Core™ i7-2760QM"
                    FPO:"Not Available"
                    INF:"cpu.inf"
                    INF Section:"IntelPPM_Inst.NT"
                    Install Date:"Not Available"
                    Last Error Code:"Not Available"
                    Level 1 Cache:"8 x 384 KB"
                    Level 2 Cache:"8 x 4096 KB"
                    Level 3 Cache:"16 MB"
                    Load:"2%"
                    Manufacturer:"GenuineIntel"
                    Model:"167"
                    Name:"11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz"
                    Number of Cores:"8"
                    Number of Cores Enabled:"8"
                    Number of Logical Processors:"16"
                    Part Number:"To Be Filled By O.E.M."
                    Power Management Capabilities:"Not Available"
                    Power Management Supported:"No"
                    Processor ID:"BFEBFBFF000A0671"
                    Revision:"Not Available"
                    Serial Number:"To Be Filled By O.E.M."
                    Service Name:"intelppm"
                    Status:"OK"
                    Stepping:"1"
                    Version:"Not Available"
          - "Storage"
               - "Intel Raid 1 Volume"
                    Capablities:"Random Access, Supports Writing, SMART Notification"
                    - "Caption":"Intel Raid 1 Volume"
                         Link:"http://www.intel.com/content/www/us/en/search.html?keyword=Intel+Raid+1+Volume"
                    Cylinder - Total:"249037"
                    Description:"Disk drive"
                    Driver:"Not Available"
                    Driver Date:"06/21/2006 12:00 AM"
                    Driver Version:"10.0.22621.1690"
                    Error Code:"Device is working properly"
                    - "Firmware Revision":"1.0.00"
                         Link:"http://www.intel.com/content/www/us/en/support/solid-state-drives/000017245.html?wapkw=ssd+firmware"
                    Heads - Total:"255"
                    Index:"2"
                    INF:"disk.inf"
                    Install Date:"Not Available"
                    Interface Type:"SCSI"
                    Manufacturer:"(Standard disk drives)"
                    Model:"Intel Raid 1 Volume"
                    Name:"\\.\PHYSICALDRIVE2"
                    Partitions:"3"
                    Physical Sector Size:"512"
                    PNP Device ID:"SCSI\DISK&VEN_INTEL&PROD_RAID_1_VOLUME\4&B278A0A&0&060800"
                    Policies:"Read Retention Priority=EqualPriority, Write Retention Priority=EqualPriority, Scalar Prefetch=Not Available, Block Prefetch=Not Available"
                    SCSI Bus:"6"
                    SCSI LUN:"0"
                    SCSI Port:"1"
                    Sectors - Per Track:"63"
                    Sectors - Total:"4000779405"
                    Serial Number:"System Volume:1"
                    Size:"1.86 TB"
                    Size – Available:"1.61 TB"
                    Status:"OK"
                    Tracks - Per Cylinder:"255"
                    Tracks - Total:"63504435"
                    - "C:"
                         Availability:"Not Available"
                         Caption:"C:"
                         Compression Method:"Not Compressed"
                         Description:"Local Fixed Disk"
                         File System:"NTFS"
                         Name:"Not Available"
                         Serial Number:"3A6E9530"
                         Size:"1907.04 GB"
                         Size – Available:"1651.61 GB"
                         Status:"Not Available"
                         Volume Dirty:"No"
               - "Intel Raid 1 Volume"
                    Capablities:"Random Access, Supports Writing, SMART Notification"
                    - "Caption":"Intel Raid 1 Volume"
                         Link:"http://www.intel.com/content/www/us/en/search.html?keyword=Intel+Raid+1+Volume"
                    Cylinder - Total:"243200"
                    Description:"Disk drive"
                    Driver:"Not Available"
                    Driver Date:"06/21/2006 12:00 AM"
                    Driver Version:"10.0.22621.1690"
                    Error Code:"Device is working properly"
                    - "Firmware Revision":"1.0.00"
                         Link:"http://www.intel.com/content/www/us/en/support/solid-state-drives/000017245.html?wapkw=ssd+firmware"
                    Heads - Total:"255"
                    Index:"1"
                    INF:"disk.inf"
                    Install Date:"Not Available"
                    Interface Type:"SCSI"
                    Manufacturer:"(Standard disk drives)"
                    Model:"Intel Raid 1 Volume"
                    Name:"\\.\PHYSICALDRIVE1"
                    Partitions:"1"
                    Physical Sector Size:"4096"
                    PNP Device ID:"SCSI\DISK&VEN_INTEL&PROD_RAID_1_VOLUME\4&B278A0A&0&060400"
                    Policies:"Read Retention Priority=EqualPriority, Write Retention Priority=EqualPriority, Scalar Prefetch=Not Available, Block Prefetch=Not Available"
                    SCSI Bus:"6"
                    SCSI LUN:"0"
                    SCSI Port:"1"
                    Sectors - Per Track:"63"
                    Sectors - Total:"3907008000"
                    Serial Number:"VMs Volume"
                    Size:"1.82 TB"
                    Size – Available:"865.36 GB"
                    Status:"OK"
                    Tracks - Per Cylinder:"255"
                    Tracks - Total:"62016000"
                    - "F:"
                         Availability:"Not Available"
                         Caption:"F:"
                         Compression Method:"Not Compressed"
                         Description:"Local Fixed Disk"
                         File System:"NTFS"
                         Name:"VMs Volume"
                         Serial Number:"E06C1FF8"
                         Size:"1863.00 GB"
                         Size – Available:"865.36 GB"
                         Status:"Not Available"
                         Volume Dirty:"No"
               - "Intel Raid 10 Volume"
                    Capablities:"Random Access, Supports Writing, SMART Notification"
                    - "Caption":"Intel Raid 10 Volume"
                         Link:"http://www.intel.com/content/www/us/en/search.html?keyword=Intel+Raid+10+Volume"
                    Cylinder - Total:"1459201"
                    Description:"Disk drive"
                    Driver:"Not Available"
                    Driver Date:"06/21/2006 12:00 AM"
                    Driver Version:"10.0.22621.1690"
                    Error Code:"Device is working properly"
                    - "Firmware Revision":"1.0.00"
                         Link:"http://www.intel.com/content/www/us/en/support/solid-state-drives/000017245.html?wapkw=ssd+firmware"
                    Heads - Total:"255"
                    Index:"0"
                    INF:"disk.inf"
                    Install Date:"Not Available"
                    Interface Type:"SCSI"
                    Manufacturer:"(Standard disk drives)"
                    Model:"Intel Raid 10 Volume"
                    Name:"\\.\PHYSICALDRIVE0"
                    Partitions:"1"
                    Physical Sector Size:"4096"
                    PNP Device ID:"SCSI\DISK&VEN_INTEL&PROD_RAID_10_VOLUME\4&B278A0A&0&060000"
                    Policies:"Read Retention Priority=EqualPriority, Write Retention Priority=EqualPriority, Scalar Prefetch=Not Available, Block Prefetch=Not Available"
                    SCSI Bus:"6"
                    SCSI LUN:"0"
                    SCSI Port:"1"
                    Sectors - Per Track:"63"
                    Sectors - Total:"23442064065"
                    Serial Number:"Data Volume"
                    Size:"10.92 TB"
                    Size – Available:"1.34 TB"
                    Status:"OK"
                    Tracks - Per Cylinder:"255"
                    Tracks - Total:"372096255"
                    - "D:"
                         Availability:"Not Available"
                         Caption:"D:"
                         Compression Method:"Not Compressed"
                         Description:"Local Fixed Disk"
                         File System:"NTFS"
                         Name:"Data Volume"
                         Serial Number:"6807864F"
                         Size:"11178.04 GB"
                         Size – Available:"1368.56 GB"
                         Status:"Not Available"
                         Volume Dirty:"No"
...#SSU#...

### Description and steps to reproduce [Required]

Open an image in Topaz Photo AI, version 2.0.0 and simply let it autoanalyze the photo. Application will fault a few minutes into the anaylysis, with the application fault listed in Windows Event Manager.

### Device / Platform

ASUS Z590 Mainboard - Custom System

### Application / Windows logs

Faulting application name: Topaz Photo AI.exe, version: 2.0.0.0, time stamp: 0x64fa2b16
Faulting module name: igdrcl64.dll, version: 23.20.101.4676, time stamp: 0x64f9f2d9
Exception code: 0xc0000005
Fault offset: 0x00000000001e6f68
Faulting process id: 0x0x1164
Faulting application start time: 0x0x1D9E376B220499A
Faulting application path: C:\Program Files\Topaz Labs LLC\Topaz Photo AI\Topaz Photo AI.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_92631f344de8baad\igdrcl64.dll
Report Id: de382761-86af-4161-b0e7-91085e6def21
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Arturo-Intel** [comment]
@mkohlman Hey, did you try with the latest beta driver? [101.4826](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html?)

I was able to open an image with topaz AI 2.0.2 without any problem
https://youtu.be/_4G2cHEoa0E

--r2

**Comment by Arturo-Intel** [comment]
@mkohlman did you have opportunity to verify it with Topaz AI 2.0.2?

**Comment by Karen-Intel** [comment]
@IGCIT can we please close this one? Issue is not reproducible with latest driver. If customer replies back with a persistent issue we can reopen anytime :)

Karen
