### ISSUE TITLE
Destiny 2 "Problem Reading Game content"

### ISSUE THREAD

**Issue by Valkirie** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#5]
#### Game _[Required]_
Destiny 2

---
#### CPU _[Required]_
Intel(R) Core(TM) i5-1035G7

---
#### GPU Driver Version _[Required]_
Intel(R) Iris(R) Plus Graphics

---
#### Rendering API _[Required]_
**API** _[DirectX, OpenGL, Vulkan]_: DirectX
**API Version** _(example DirectX 12)_: 11

---
#### Windows Build Number _[Required]_
Windows 10 20H2

---
#### Description _[Required]_
Destiny 2 crash to desktop after you picked your character and joined a map.

**Comment by Valkirie** [comment]
A fix is in production but no data has been shared by Intel.

**Comment by THFourteen** [comment]
Tried the latest driver (9168 ) on same CPU and build, same crash.

**Comment by THFourteen** [comment]
Any news on this one @Valkirie?

**Comment by Valkirie** [comment]
> Any news on this one @Valkirie?
As of end of January, still no ETA.

**Comment by Valkirie** [comment]
@leoben2 Any update from Bungie on this one ?

**Comment by mva94** [comment]
Would be great to see this game solved

**Comment by ricera** [comment]
Yeah, I'd like to see Destiny 2 working properly, too.

**Comment by ChiefyGoodness** [comment]
I hope they eventually resolve this, because I'd really like to be able to play Destiny 2 again.

**Comment by Valkirie** [comment]
My most anticipated game as well. Trust me i'm going to chase Intel here but truly it's Bungie'd job to get this one fixed.

**Comment by ricera** [comment]
Out of curiosity, can we get an explanation of what the problem is on Bungie's end? Some light googling mentioned something about their anti-cheat interfering with the Intel driver, which sounds odd.

**Comment by Valkirie** [comment]
A patch from Bungie is expected in Jully to address that issue!

**Comment by ricera** [comment]
That's awesome! Thanks for the news!

**Comment by ricera** [comment]
@Valkirie, is this the relevant patch? https://www.bungie.net/en/News/Article/50448

At the bottom, it mentions fixing crashing when launching on Intel Integrated Graphics.

**Comment by Valkirie** [comment]
> @Valkirie, is this the relevant patch? https://www.bungie.net/en/News/Article/50448
> 
> At the bottom, it mentions fixing crashing when launching on Intel Integrated Graphics.

Indeed. Crash is fixed. Closing.
