### ISSUE TITLE
Arc Control issues setting performance tuning settings after already being set

### ISSUE THREAD

**Issue by Code-Vlue** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#502]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Arc Control

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12601090/ssulog.txt)

### Description and steps to reproduce [Required]

When performance tuning has been set initially even if you try to set to something different it will shows its been changed but wont change the actual clock/power/ect. Only way to set it is to push reset default values and then set all the settings again.

**Comment by Gabriela-Intel** [comment]
@Code-Vlue Thanks for taking the time to report this. :)

There's a known issue with Arc Control Performance Tuning settings that is super similar to what you're reporting here and it's planned to be resolved in the next version of Arc Control. 

I'll follow up again here once it's published in a new driver so you can test it out.

**Comment by Gabriela-Intel** [comment]
@Code-Vlue Would you mind checking if you still see this issue using v74 of Arc Control? It's available with the driver we posted today (12/14) [here](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html?).

**Comment by Gabriela-Intel** [comment]
@Code-Vlue Have you had the chance to check this?

**Comment by Gabriela-Intel** [comment]
@IGCIT I think we can close this one. We don't have an update from OP. Thanks!
