### ISSUE TITLE
Starfield crash frequency increased after most recent driver update

### ISSUE THREAD

**Issue by Code-Vlue** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#503]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Starfield

### Game Platform [Required]

- [ ] Steam
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12603084/ssulog.txt)

### Description and steps to reproduce [Required]

Driver version is actually 4824 but that isn't an option yet, since the driver update the frequency at which the game crashes has increased dramatically to the point of even further unplayability.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Low and Medium presets were used.

**Comment by IGCIT** [comment]
hi @Code-Vlue, is this a ticket for 4824 driver?

**Comment by Karen-Intel** [comment]
Hey @Code-Vlue yeah I detected that too.  Allow me to report it internally and as we're having subsequent driver updates I will all the behavior we found with the latest driver to our internal report, stay tuned!

Karen

**Comment by BuyMyMojo** [comment]
Confriming replication here too 👍

**Comment by BuyMyMojo** [comment]
completely unable to start with the latest drivers

**Comment by Code-Vlue** [comment]
@BuyMyMojo I just checked with the most recent drivers as well and I was able to load into the game, however some difference in our system configurations may be causing yours to not start. I'm running a Ryzen 3 3600 and A750.

**Comment by Karen-Intel** [comment]
Hi all! Well I was able to run the game with latest driver v.4826 (Using DDU) there are still improvements needed but it does launch on my end too

Karen

**Comment by Code-Vlue** [comment]
@Karen-Intel I also used DDU when I installed the driver before this one so if you haven't tried that @BuyMyMojo it might be a good bet.

**Comment by BuyMyMojo** [comment]
I'll give it a shot and report back 👍

**Comment by BuyMyMojo** [comment]
So I tried doing DDU and now I am running into all kinda of weird errors so I thought it might have been corupt when downloading and now I think I found a new issue.
None of the SHA1 hashes on the download page line up.

Both 7zip and PeaZip give me the same SHA1 hash but they do not line up with the ones shown on the download page:

gfx_win_101.4676.exe 7z: `9869e096488cab8cbe855085308742528f6e77ad` yours: `7F388BD2CE2C963E7903290245DE9B142B678154`

gfx_win_101.4824.exe 7z: `d94b2ff84a2dad17877c63e1738da266d9ccbc34` yours: `14D569E6331A6ABF63952F29F59232D174F80CFD`

gfx_win_101.4826.exe 7z: `c9e5fcde843af894efcbd14f7b6af3b144465824` yours: `3DBF5FAA88FA6E4140AF36A605944E93BAA06ADB`

all fresh downloads to test this

**Comment by BuyMyMojo** [comment]
update: my ram was being faulty so it messed up both the downloading and hashing... fixed now

**Comment by Karen-Intel** [comment]
@BuyMyMojo good news! So can you finally launch the game? :3 

Karen

**Comment by BuyMyMojo** [comment]
not quite.. I don't think it's a ram issue anymore. that was for sure causing a lot of issues but now I can't even install the driver

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/1a888f88-6975-4e6b-9125-b4c26d9b9344)

**Comment by BiZkViT96** [comment]
@BuyMyMojo Post Error log.

**Comment by Code-Vlue** [comment]
@BuyMyMojo That's interesting I've never seen something like that happen, did you run DDU in safe mode?

**Comment by BuyMyMojo** [comment]
> @BuyMyMojo Post Error log.

Sorry I forgot to check it!

> @BuyMyMojo That's interesting I've never seen something like that happen, did you run DDU in safe mode?

I did 👍 

But it is fixed now and I was able to boot into starfield. I swapped my ram over to another set of sticks that I had, I guess my new ram is completely bust.

if this error springs up again I'll make sure to grab the log, sorry!

**Comment by Code-Vlue** [comment]
@BuyMyMojo No worries, glad you got it all figured out.

**Comment by Danjhop4** [comment]
When Is a new driver coming to windows update

**Comment by Promixius** [comment]
> When Is a new driver coming to windows update

Really hope you are not thinking the driver are coming in windows update.
go to intels website for updates, or check Arc control panel.

**Comment by Danjhop4** [comment]
@Promixius i don’t have admin to do it by hand so windows update is the only choice I have

**Comment by rmorera-intel** [comment]
Hi everyone. Sorry for not updating this one in a while... I believe the crashing issue with Starfield was fixed months ago since driver 101.4676.
Our latest driver is 32.0.101.6083 so if you still experience this issue try with it.
