### ISSUE TITLE
Updating ARC driver triggers 'Platform Not Supported' warning image

### ISSUE THREAD

**Issue by BigNish7** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#504]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Driver

### Processor / Processor Number [Required]

Intel Core i9 13900KS

### Graphic Card [Required]

Intel ARC A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [X] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

22621.2134

### Intel System Support Utility report

[System Support Log_BigNish7_14 September 2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12609924/System.Support.Log_BigNish7_14.September.2023.txt)

### Description and steps to reproduce [Required]

This issue has been occurring now for several ARC driver updates. It occurs with either WHQL or BETA driver updates, 

When I update my ARC driver, I get an image on my monitor that includes a text box which reads 'Platform Not Supported' along with some explanatory text. I just click on the OKAY button at the bottom of the text box and the image disappears and the driver update installation proceeds without any issues. 

I have so far not bothered to report it as the driver updates were not affected, but I am keen to understand what it is about my PC that is triggering this warning and how I can make it stop as it should not be happening. 

I have attached a video of the issue. Sorry about the poor quality. I captured it via my iPhone so it is a bit shaky.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/1622101e-190f-4343-acaf-3f462106c65c

### Device / Platform

DESKTOP-ECBGJIO

**Comment by Arturo-Intel** [comment]
@BigNish7 after the nstallation is finished and you restart your pc, the message is still there?

**Comment by BigNish7** [comment]
Hi @Arturo-Intel ,

Thank you for your prompt response and thoughts on my issue. I did some further testing and found the following:

1. I deleted the 31.0.101.4824 driver using DDU v18.0.6.7
2. I installed the 31.0.101.4672 WHQL driver via the self-extracting exe file I had previously downloaded and saved to my PC. The installation went smoothly and did not trigger the 'Platform Not Supported' warning image.
3. I rebooted my PC.
4. I then installed the 31.0.101.4824 driver via the self-extracting .exe file, but this time **did not** check the 'Clean Installation' checkbox.  The installation proceeded **without** triggering the 'Platform Not Supported' image. 
5. After rebooting, I went back to Step 1 and used DDU to again remove the 4824 driver. I installed the 4672 deriver again and rebooted my PC.
6. I installed the 4824 driver (as per step 4) but this time I checked the "Clean Installation' checkbox. This triggered the 'Platform Not Supported' warning image. Instead of clicking 'OKAY' and removing the image, I left it on my screen to see if it would still be present after a reboot as per your suggestion. However, at a point in the driver installation, my monitor went black/blank and when the image returned the 'Platform Not Supported' image was no longer there and the driver installation process proceeded as normal. As the image disappeared part way through the installation process it was gone by the time the installation finished.
7. After rebooting, I can confirm that the image did not reappear.

I trust that this helps in the investigation. It looks like it is triggered by the 'Clean Installation' option when installing over a previous version.     

I guess my issue is that regardless of the installation process, my platform obviously can support the installation of the driver and ARC Control as I have an A770 LE card and therefore I should not be getting the warning.

I sincerely trust that the above makes sense. 

P.S. I noticed after removing and reinstalling the drivers, some of my taskbar icons have defaulted to using generic images. I will create a separate issue for this behaviour. When I used DDU to remove the driver, the task bar icons returned to using their specific images.

**Comment by Gabriela-Intel** [comment]
Can you check if you still see this pop up when installing our latest driver (101.4953)? I saw similar behavior with our previous drivers but I'm not seeing anymore with the latest.

**Comment by BigNish7** [comment]
Hi @Gabriela-Intel. Thank you very much for reaching out. I am very pleased to say that I am no longer receiving the 'Platform Not Supported' pop up. I am happy to close this issue.

**Comment by BigNish7** [comment]
Dang! @Gabriela-Intel I spoke too soon! 

My current method for installing ARC drivers is to download the .exe for the new driver, remove the current driver with DDU via a Safe Boot, and once the old driver is cleaned out and my PC has rebooted, I install the .exe of the ne driver as if it was brand new. 

However this time to try something different for a change, when updating from 4952 (non WHQL) to 4953 (WHQL), I did not use DDU to remove 4952. I simply double clicked the 4953 .exe and checked the "Clean Installation" checkbox. Unfortunately I got the "Platform Not Supported" pop-up again. As per my post dated Sep 15, it seems that the pop-up is triggered when the 'Clean Installation' checkbox is ticked. It does not appear if the new driver is being installed over the old driver and 'Clean Installation' is not ticked, or the old driver is completely removed via DDU and the new driver is installed afresh. 

I will say however I have not tried clicking on the 'Customize" button and then clicking on the "Clean Installation' checkbox when installing an updated driver after removing the old driver with DDU. I figured that it was going to be a clean installation anyway as I have already removed any trace of a previous ARC driver with DDU. However I could try this as a test. Let me know if it is worth trying this. 

Sorry I did not have better news.

**Comment by Gabriela-Intel** [comment]
Ah yes thanks @BigNish7! I filed a bug to the Arc Control team (id 14020908703 for your reference). We also found a few more instances where this pop up appears so hopefully the team can improve this. I'll follow up again here once I have an update on your bug.

**Comment by Gabriela-Intel** [comment]
@BigNish7 The "Platform not supported" warning has been gone for a few releases now so I think we can go ahead and close this :)
@IGCIT
