### ISSUE TITLE
Intel DSA does not update automatically the drivers

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#505]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Driver and Support Assistant

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4824
- [X] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 14.09.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12611476/Intel.SSU.14.09.2023.txt)

### Description and steps to reproduce [Required]

Even with the "By checking this box, you agree that Intel® Driver and Support Assistant will automatically download new updates to this device as soon as they are released" box checked, it won't. It will only show a notification in Windows that a new driver is ready. It's been like this since I own the card

### Device / Platform

ASUS Prime Z790-P WiFi D4

**Comment by Karen-Intel** [comment]
@IGCIT can we please close this one? Issue has been marked as FUTURE and we can reopen once automatic driver update is available

TY

Karen

**Comment by freak2fast4u** [comment]
Before closing, please note that the Xe-based iGPUs also don't seem to be supported by DSA.
We witnessed this with a friends Intel i5 1235U : https://www.intel.com/content/www/us/en/products/sku/226266/intel-core-i51235u-processor-12m-cache-up-to-4-40-ghz-with-ipu/specifications.html

The "Downloads" page forwards you to the Intel Arc drivers (they can be installed manually and function as expected), but DSA won't even suggest downloading them from the webpage, even if motherboard/wlan/bt/lan drivers were updated.

**Comment by Gabriela-Intel** [comment]
Hi @freak2fast4u! Regarding your original issue, I discussed this with the IDSA team and based on your description it appears that this is expected behavior. The feature auto downloads the driver, but does not install it.

By the way, if you have encounter more issues with IDSA in the future or would like to request any feature improvements to IDSA, you can do that by posting to any of our Communities posted [here:](https://community.intel.com) instead. 

Thanks! :)

@GCIT Please close this out.
