### ISSUE TITLE
Installing 4824 made my PC reboot by itself due to hardware error

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#506]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 14.09.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12611486/Intel.SSU.14.09.2023.txt)

### Description and steps to reproduce [Required]

LKD_0x141_Tdr:6_IMAGE_igdkmdnd64.sys_GEN12_0_KMD_SCHEDULER_ERROR
It happened when I was installing the new drivers. With a bluescreen, but I won't be able to say what error was shown in the bluescreen, I didn't see it, but I know it happened (“Problem Event Name: BlueScreen”)

### Device / Platform

ASUS Prime Z790-P WiFi D4

### Crash dumps [Required, if applicable]

https://drive.google.com/drive/folders/1MzG8mAnpQN6A2oGZIKeNbEt4D7yN4W4o?usp=sharing

**Comment by Arturo-Intel** [comment]
@TheWonderfulTartiflette Are you seeing the BSOD with the latest drivers?

**Comment by TheWonderfulTartiflette** [comment]
@Arturo-Intel no, I haven't seen this since those drivers

**Comment by Arturo-Intel** [comment]
@TheWonderfulTartiflette thanks for the confirmation. I will close this issue then.

If you see again this behavior, please open a new case. :)
