### ISSUE TITLE
Have, in PresentMon or the Arc Control overlay, a “VRR enabled?” line

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#508]
### Application [Required]

Intel Arc Control or Intel PresentMon Beta

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

I know there's a switch in Arc Control to enable VRR or not, but as VRR has to be in specific conditions in order to be used, I think it would be nice to let the user know if VRR is enabled or not through an overlay line in Arc Control or PresentMon Beta

**Comment by Gabriela-Intel** [comment]
@TheWonderfulTartiflette Thanks for the feedback! I'll pass it along to the team.

@IGCIT Please close.
