### ISSUE TITLE
Driver 4824 ARC Control "memory leak" 1.73.5334.1

### ISSUE THREAD

**Issue by J0dla** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#511]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel ArcControl

### Processor / Processor Number [Required]

5700G

### Graphic Card [Required]

A380

### GPU Driver Version [Required]

- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12620942/igcit_ssu.zip)

### Description and steps to reproduce [Required]

Normal computer use and process will start eating RAM with every minute
![arc_memory_leak](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/17433864/b3b877d7-890c-4f89-a1ac-12a34fb00451)
Assist process is eating a lot.
Arc Control version: 1.73.5334.1

**Comment by gargamel314** [comment]
Yeah this is pretty bad

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/124757309/4f5fc3d6-0c92-4ff2-8f4f-5bf4997870a1)

**Comment by keiths7** [comment]
I have the same problem

**Comment by leroy20317** [comment]
me too   A770  12400   Windows 11 22H2

**Comment by Yomi0** [comment]
<img width="938" alt="Screenshot 2023-09-18 084456" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3170531/1fa84e7e-73a0-4cf9-b901-e096234f317b">
<img width="1269" alt="Screenshot 2023-09-18 084440" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3170531/70881110-6fdd-4bc0-a7da-5df0387d4974">

**Comment by Arturo-Intel** [comment]
@J0dla Can you do me a favor, please disable the AMD gpu you have on your system and check if this behavior continues.

**Comment by J0dla** [comment]
@Arturo-Intel i disabled igpu and its gone i think, 
My best so far solution to this is to turn off autostart and use it only when need it, remembering to close it.

**Comment by Arturo-Intel** [comment]
Another work around could be: 

- Uninstall driver 31.0.101.4824 using [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html)
- Install driver 31.0.101.4676 which includes the previous version of Intel Arc Control (1.71). 
- Perform a custom installation of driver 31.0.101.4824 unchecking the Arc Control installation option
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/521b7f94-2ac2-4b9d-b3a5-80017776c4ca)
This way you can have the latest driver and Arc Control 1.71

Our dev teams are already working on a solution for this issue, thank you for your patience.

--r2

**Comment by J0dla** [comment]
@Arturo-Intel oh yeah but what about #401 ? yep

**Comment by Arturo-Intel** [comment]
Aww man, ok, well then turn off autostart and use it only when you need it seem the best WA for you.

I will keep you posted if there is any news on this case.
-- r2

**Comment by J0dla** [comment]
@Arturo-Intel looks like resolved for me in 4826 that contains 1.73.5335.2

**Comment by Arturo-Intel** [comment]
Perfect, @J0dla If theres any unpleasent behavior, please open a new case so we can track it

@IGCIT can we close this case please?
