### ISSUE TITLE
Godot (4.1.1) losses vulkan device with Intel Arc

### ISSUE THREAD

**Issue by BuyMyMojo** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#512]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Godot

### Processor / Processor Number [Required]

AMD 5600x

### Graphic Card [Required]

Arc A770

### GPU Driver Version [Required]

- [X] 31.0.101.4824
- [X] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[2023-09-17.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12640908/2023-09-17.txt)

### Description and steps to reproduce [Required]

Running Godot 4.1.1 (And latest github build, will test on Godot 4.0 and 3.X at some point soon) disable vsync(EDIT: it happens with vsync on too!) and run a 3d scene it will eventually freeze but not crash and throw `VK_ERROR_DEVICE_LOST` errors. This happens when building the game to be standalone too.

The first time I noticed this was when I wanted to take a look at the [Debug Menu Demo](https://godotengine.org/asset-library/asset/1903) and the issue kept appearing. so I amde my own test project with some simple assets it happened there too.

These crashes can completely freeze all displays for a few seconds before recovering.

I have compiled mty test scene with a few spininng objects and skybox (Slight motion sickness warning) along with it's debug console, just run `release.console.exe` to see the error appear when it does.

Compiled project: https://drive.google.com/file/d/1LUi9qbxbf4ktuuQABhMCCAmuzTpufBEx/view?usp=sharing

For the sake of not running random exe files provided by strangers here is the project files too if you'd prefer to just open them in Godot yourself

Raw project files: https://drive.google.com/file/d/1BnQWRYAH7F5sR-s9c80pZxjH1ZfUmx5o/view?usp=sharing

![Godot_v4 1 1-stable_win64_gkcIGvLwAK](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/5e0a3c0a-330d-4220-b661-5888b5f03a3a)

![ArcControl_aZ6WlFJEwi](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/f5dc5f18-cae4-4f44-b182-1486b7385959)

### Crash dumps [Required, if applicable]

Nothing was caught by the helper

### Application / Windows logs

Event viewer did pick up a crash from the built version:
```
Log Name:      Application
Source:        Application Error
Date:          16/09/2023 11:30:38 PM
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          MOJOPC\hello
Computer:      MojoPC
Description:
Faulting application name: godot.windows.editor.x86_64.exe, version: 4.2.0.0, time stamp: 0x6504ac2a
Faulting module name: godot.windows.editor.x86_64.exe, version: 4.2.0.0, time stamp: 0x6504ac2a
Exception code: 0xc0000005
Fault offset: 0x000000000198ff1e
Faulting process ID: 0x0x2150
Faulting application start time: 0x0x1D9E89F9AFC8085
Faulting application path: R:\Godot\4.2-dev4 2023-09-16\godot.windows.editor.x86_64.exe
Faulting module path: R:\Godot\4.2-dev4 2023-09-16\godot.windows.editor.x86_64.exe
Report ID: faa7d3a0-a8e1-4192-8404-1e5735b51e9f
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2023-09-16T13:30:38.6183472Z" />
    <EventRecordID>51359</EventRecordID>
    <Correlation />
    <Execution ProcessID="23892" ThreadID="19864" />
    <Channel>Application</Channel>
    <Computer>MojoPC</Computer>
    <Security UserID="S-1-5-21-1376549694-142473917-4156327385-1001" />
  </System>
  <EventData>
    <Data Name="AppName">godot.windows.editor.x86_64.exe</Data>
    <Data Name="AppVersion">4.2.0.0</Data>
    <Data Name="AppTimeStamp">6504ac2a</Data>
    <Data Name="ModuleName">godot.windows.editor.x86_64.exe</Data>
    <Data Name="ModuleVersion">4.2.0.0</Data>
    <Data Name="ModuleTimeStamp">6504ac2a</Data>
    <Data Name="ExceptionCode">c0000005</Data>
    <Data Name="FaultingOffset">000000000198ff1e</Data>
    <Data Name="ProcessId">0x2150</Data>
    <Data Name="ProcessCreationTime">0x1d9e89f9afc8085</Data>
    <Data Name="AppPath">R:\Godot\4.2-dev4 2023-09-16\godot.windows.editor.x86_64.exe</Data>
    <Data Name="ModulePath">R:\Godot\4.2-dev4 2023-09-16\godot.windows.editor.x86_64.exe</Data>
    <Data Name="IntegratorReportId">faa7d3a0-a8e1-4192-8404-1e5735b51e9f</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>
```

**Comment by BuyMyMojo** [comment]
No issue on Godot 3.X/GLES3 so it is a bulkan related issue

**Comment by BuyMyMojo** [comment]
Captured this using the Vulkan Configurator:

[VK_Configurator_Log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12641239/VK_Configurator_Log.txt)

**Comment by BuyMyMojo** [comment]
@darksylinc has said it could be the lack of [MSAA support in Storage textures](https://github.com/godotengine/godot/issues/71929#issuecomment-1722288155)?

I tried to open UE5 in vulkan mode and got the same error:
```
LoginId:[censored]
EpicAccountId:[censored]

Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\VulkanRHI\Private\VulkanUtil.cpp] [Line: 1130] VulkanRHI::vkCreateDescriptorPool(Device->GetInstanceHandle(), &PoolInfo, VULKAN_CPU_ALLOCATOR, &DescriptorPool) failed, VkResult=-4 at D:\build\++UE5\Sync\Engine\Source\Runtime\VulkanRHI\Private\VulkanPendingState.cpp:65 with error VK_ERROR_DEVICE_LOST

UnrealEditor_VulkanRHI
UnrealEditor_VulkanRHI
UnrealEditor_VulkanRHI
UnrealEditor_VulkanRHI
UnrealEditor_VulkanRHI
UnrealEditor_VulkanRHI
UnrealEditor_VulkanRHI
UnrealEditor_Renderer
UnrealEditor_RHI
UnrealEditor_RHI
UnrealEditor_RHI
UnrealEditor_RHI
UnrealEditor_RHI
UnrealEditor_RHI
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_RenderCore
UnrealEditor_Core
UnrealEditor_Core
kernel32
ntdll
```

**Comment by Arturo-Intel** [comment]
@BuyMyMojo using:
Intel driver 5081
godot 4.2 

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/cb89b96a-4009-4332-8747-357809c2970b)

I don't see the Vulkan errors.

Will try now with 4.1.1, keep you posted
--r2

**Comment by Arturo-Intel** [comment]
Using driver .5081
GoDot 4.1.1

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/bf46ef23-9cb6-4fa3-aed1-8e8e7148a650)

Cant see the vulkan errors

@BuyMyMojo can you confirm this?
-- r2

**Comment by BuyMyMojo** [comment]
I've had no issues since. they did push a fix on their end this this specific instance in 4.2 but this error can appear randomly for users without an explanation why yet.

if I encounter again I can open a new issue if needed
