### ISSUE TITLE
Display artifacts and monitor refresh reset after waking from sleep

### ISSUE THREAD

**Issue by VibinHippo** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#513]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 11

### Processor / Processor Number [Required]

Ryzen 7 7800X3D

### Graphic Card [Required]

Intel ARC A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12641742/igcit_ssu.txt)

### Description and steps to reproduce [Required]

When I put the computer to sleep and wake it, the monitor refresh rate is reset to 60hz and when I try to switch it back to 165hz, the display repeatedly blacks out with some artifacts and then eventually stopping, however still at 60hz. The only way to fix is to restart the computer.  

Video- https://streamable.com/8we751

### Device / Platform

Monitor- Asus Tuf vg259qr

**Comment by VibinHippo** [comment]
Hi @Karen-Intel ,
Thanks for responding. I am using the furthest DisplayPort to the right (or left, depending on orientation) at the back of the A770. 

Here is a link to the specs: https://www.asus.com/displays-desktops/monitors/tuf-gaming/tuf-gaming-vg259qr/techspec/
In summary, the monitor is 1080p 24.5" 165hz ips 1ms.

**Comment by Felipe-Intel** [comment]
Hello @VibinHippo are you still seeing this with the [ latest driver v5084](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)?

**Comment by VibinHippo** [comment]
Hello @Felipe-Intel, 
After attempting sleeping the PC and turning it back on again, on driver 5084, there is no display corruption however the refresh rate still gets reset from 165hz to 60hz, requiring a restart where it will return back to 165hz. 
I am moving towards the idea that the Arc A770 LE card may not communicate properly with my monitor which is causing the issue (Asus VG259QR, old model without Freesync but with AdaptiveSync and 'Gsync Compatible').

**Comment by Felipe-Intel** [comment]
I'll test this in my monitors (one Asus VP249, one ROG Swift pg32u) and see what happens. I'll update you soon.

**Comment by Felipe-Intel** [comment]
hello @VibinHippo I tested my 2 screens and had no problem with the refresh rate. Both screens kept the refresh rate after coming back from sleep. 
A few things I would suggest are: 

1. Check if you have installed [the monitor's drivers](https://www.asus.com/displays-desktops/monitors/tuf-gaming/tuf-gaming-vg259qr/helpdesk_download?model2Name=TUF-GAMING-VG259QR) (sometimes they have their own drivers). For this, check in device manager if under monitors, it appears as PnP Generic Monitor or if it is listed as the actual model. You may have to manually install them via device manager (right click over the device/update driver/look for files in pc). 

2. Try disconnecting the Arc Card (no need to remove the card, just unplug it from the PSU) and uninstall the Intel drivers and try to replicate with your integrated graphics only. Remember to connect your monitor the the motherboards video output. If issue persist, it is something not related to our drivers.

If issue is not reproducible with only the integrated graphics, then we can try the following

3. Make sure your monitor is connected to the Arc Graphics card and disable your integrated graphics. 
4. Use "the other" interface (HDMI or DP) (this was recommended by Karen a while back).
5. If possible, try to replicate with a different monitor/tv screen. Also, try with different resolutions in your Asus monitor. 
6. Make sure no other graphics related apps you may have installed are overriding Windows settings. You can try a [clean boot](https://support.microsoft.com/en-us/topic/how-to-perform-a-clean-boot-in-windows-da2f9573-6eec-00ad-2f8a-a97a1807f3dd) for this. 
 
Please let me know your results.

**Comment by VibinHippo** [comment]
Hello @Felipe-Intel, 
Thank you for testing the issue out on your end. 
1. I installed the latest monitor driver from the Asus website through device manager, however the refresh rate still reset after waking from sleep and the screen blacking out for short moments was observed again (as seen in the video from the original post). The display blacking out seems to be a sporadic occurrence, where sometimes it happens and sometimes not, as I stated that it was not present in my last reply, which I now realize was incorrect. Both of these were using DisplayPort. 
2. I have tried plugging in DisplayPort into the integrated graphics on the motherboard, setting the refresh rate to 165hz and waking from sleep, and the neither the refresh rate resetting nor the display blacking out were present. 
3. All instances in this thread have been with the integrated graphics disabled (through the bios). I have tried waking from sleep through the Arc card with both DisplayPort and integrated graphics enabled to no avail (unlikely it would have changed anything but worth a try). 
4. However, what _was_ interesting was trying HDMI, setting the refresh rate to 144hz (the HDMI port on the monitor does not support 1080p 165hz), and waking from sleep. Bizarrely, the refresh rate did not reset to 60hz and the display blackouts were not present. 
5. Unfortunately I do not have any DisplayPort monitors that have a higher refresh rate than 60hz. 
6. I am fairly certain no startup applications are overriding Windows settings. I have included attached images of my startup applications. 

Overall, HDMI working fine with the monitor is leading me to suspecting an issue related with DisplayPort on the card. 
I hope this was helpful. 

![1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/68887868/f1e696bc-e4b8-4f8f-be42-35b1223c8209)
![2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/68887868/ef90c20a-c6fd-447a-89f4-69b887350dc0)

**Comment by VibinHippo** [comment]
> Hello @Felipe-Intel, Thank you for testing the issue out on your end.
> 
> 1. I installed the latest monitor driver from the Asus website through device manager, however the refresh rate still reset after waking from sleep and the screen blacking out for short moments was observed again (as seen in the video from the original post). The display blacking out seems to be a sporadic occurrence, where sometimes it happens and sometimes not, as I stated that it was not present in my last reply, which I now realize was incorrect. Both of these were using DisplayPort.
> 2. I have tried plugging in DisplayPort into the integrated graphics on the motherboard, setting the refresh rate to 165hz and waking from sleep, and the neither the refresh rate resetting nor the display blacking out were present.
> 3. All instances in this thread have been with the integrated graphics disabled (through the bios). I have tried waking from sleep through the Arc card with both DisplayPort and integrated graphics enabled to no avail (unlikely it would have changed anything but worth a try).
> 4. However, what _was_ interesting was trying HDMI, setting the refresh rate to 144hz (the HDMI port on the monitor does not support 1080p 165hz), and waking from sleep. Bizarrely, the refresh rate did not reset to 60hz and the display blackouts were not present.
> 5. Unfortunately I do not have any DisplayPort monitors that have a higher refresh rate than 60hz.
> 6. I am fairly certain no startup applications are overriding Windows settings. I have included attached images of my startup applications.
> 
> Overall, HDMI working fine with the monitor is leading me to suspecting an issue related with DisplayPort on the card. I hope this was helpful.
> 
> ![1](https://private-user-images.githubusercontent.com/68887868/296368548-f1e696bc-e4b8-4f8f-be42-35b1223c8209.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwOTU5NTgsIm5iZiI6MTcwNTA5NTY1OCwicGF0aCI6Ii82ODg4Nzg2OC8yOTYzNjg1NDgtZjFlNjk2YmMtZTRiOC00ZjhmLWJlNDItMzViMTIyM2M4MjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDIxNDA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNWVkYzg0MzQwODZjNTQxYTFkZmM4YWJhYjZlOTQyOGU5MzdlMjkxYjBiMjViOTI1MTE3M2M2MTRjYWNjNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dlaQRZvr8CRDgphQteRyNWffIEAGm2TOFKnfGbMHiIU) ![2](https://private-user-images.githubusercontent.com/68887868/296368555-ef90c20a-c6fd-447a-89f4-69b887350dc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwOTU5NTgsIm5iZiI6MTcwNTA5NTY1OCwicGF0aCI6Ii82ODg4Nzg2OC8yOTYzNjg1NTUtZWY5MGMyMGEtYzZmZC00NDdhLTg5ZjQtNjliODg3MzUwZGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDIxNDA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MDJmYjFhY2U2ODQ4MmM4MjAyNGY5YmU0YWYwNDUyOTRiZDQzMzkzZTQ2N2I5ZGU4MjI3NWNmN2Q1ODAxNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VsszAMR9pLv1mPpwomDYbBrxRd5XZr5Ch09KmCfTYRg)

Just to follow up on 5, whilst using DisplayPort connected to the graphics card, I set the resolution to 1280x720 at 165hz and tried waking from sleep. 
After waking from sleep, the refresh rate had reset, the blackouts were present and most interestingly, the resolution was back at 1920x1080. 
After restarting, the refresh rate was back to 165hz (like the previous attempts), but what was unique was that the resolution was back at 1280 x 720.

**Comment by Felipe-Intel** [comment]
thanks @VibinHippo Great feedback. Let me talk to one of my peers and come back to you.

**Comment by Felipe-Intel** [comment]
@VibinHippo please go ahead and create a regular support case in our [customer support portal](https://www.intel.com/content/www/us/en/support/contact-intel.html)
Once it is created, please share the ticket number here so I can pick it up and continue the support there. Thanks in advance.
Please add to that support ticket the IGCC report and please confirm if this issue happens with any of the three DP ports in your Intel Card. Thanks!

**Comment by VibinHippo** [comment]
Hello @Felipe-Intel, 
After further troubleshooting I have come to the conclusion that it is in fact the monitor (Asus Tuf VG259QR) rather than the graphics card. I tried plugging the card into another DisplayPort monitor (1440p 60hz) and, although the FPS change was not possible to be observed, there was no screen flickering at all after waking from sleep. 
I will most likely follow up with Asus in the future. This thread can be marked as resolved. 
Thank you for your time in trying to help me fix this issue!

**Comment by Hennrix** [comment]
I had this Issue on Three Different Systems:

- On The Linux Kernel 5.16, Ubuntu 22.04 Basis, Gnome Shell 42 and Gnome Desktop 42, also known as Pop!_OS 22.04 LTS
- On Fedora 39 
- On Fedora 40
I had this Issue with the Intel Arc 380 and Intel Arc A770 on every Monitor I tested, roughly 6 Brands and 12 different models.
