### ISSUE TITLE
Cities Skylines: Graphics mods result in a significant performance hit

### ISSUE THREAD

**Issue by ygugsa** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#514]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Cities: Skylines

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-12400F

### Graphic Card [Required]

A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12641921/igcit_ssu.txt)

### Description and steps to reproduce [Required]

In the Performance Tuning section of Arc Control, I set the **GPU Performance Boost** to +20.

In the Global Game Settings section of Arc Control:
- Game Compatibility = "Recommended"
- Tearing Mitigation Modes = "Application Choice"
- Sharpening = "Enabled", sharpening strength set to 100%
- Adaptive Tessellation = "On", tessellation quality set to 100%

In Command Center (Beta), I set **Instant Game Tuning** to "on" and disabled **Smart VSync**. The **Adaptive Tessellation** option is off. I tried turning it on, but whenever I exited and reloaded Command Center, it didn't remember my choice. 

**How to reproduce:**
Move to Aspen Avenue and Primrose Street, point the camera towards the highway, and zoom in/out and pan around. Notice how the frame rate becomes inconsistent.
![Further out](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55931832/8b35d277-b1b9-4e0a-860e-6009a1ee9c2a)
![Angle 1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55931832/d0cf5a84-d54b-42ff-be56-f830067eaeec)
![Close up](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55931832/677d23f7-6d1c-4c0b-add6-03d35296f886)

By comparison, when I switch to vanilla LODs (LCtrl + Shift + .) the frame rate increases.
![Vanilla LODs](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55931832/5157c00c-5b84-4df9-8497-e5dddd5cb743)

And when I turn off shadows, the frame rate increases even more.
![Vanilla LODs no Shadows](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55931832/6c0733d8-cc4b-4a55-907a-69550d506ae2)

If I had to hazard a guess, there is something about LODs and shadows that doesn't play nice with Arc for whatever reason. Sub-30 FPS in a city of only 5,300 Cims seems anomalous. Maybe DX11 translation overhead is hitting the CPU too hard? I find having Firefox open in the background reduces frame rate. (The ingame screenshots were taken with Firefox closed.)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2540x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

**Mods used are:**
- Patch Loader Mod v2.2.0
- FPS Booster 0.9.1
- Lumina 1.3 (just for legacy Relight LUTs. Features that overlap with Render It and Theme Mixer are automatically disabled)
- Skyve Beta 3.3.0.0
- Monitor It
- Visibility Control 0.9.5
- Play It
- Render It
- Control It
- Dynamic Resolution
- Theme Mixer 2.5-Reupload

**Ingame graphics settings**
![Game settings](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55931832/6bc062bf-636a-4372-86f7-b1fb8c55fddf)
![LSM](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55931832/dec81b61-2965-434c-a538-e08acd4b4809)
![FPS booster](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55931832/efb0b117-9cbc-4364-a829-c9e1d121e2a4)

- Theme used: CO Temperate Theme
- Render It settings: [render it settings.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12641907/render.it.settings.txt) (I use the RelightNatural LUT, which requires subscribing to Lumina)
- Play It settings: Time of day set to 11:07 a.m.
- Dynamic Resolution is disabled when you load CO scenarios, so internal resolution is 100%.
- All Visibility Control options are set to their default values.
- **Important:** Once loaded into the scenario, ensure that Color Correction Override in the pause menu is set to "None". When I have Lumina enabled alongside Render It, the game will sometimes apply a LUT twice out of nowhere, making the colours look washed out. I have yet to find a fix for this.
![Double LUTs](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55931832/569c30a4-7897-444c-bb0c-b1795fe535f0)
![CCO](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55931832/8787f943-4558-40c9-8b93-0d8c779602cd)

### Device / Platform name

N/A

### Crash dumps [Required, if applicable]

N/A

### Save game

Clean-Up Crew scenario from the Green Cities DLC.

**Comment by Gabriela-Intel** [comment]
@ygugsa To clarify, is the issue reproducible _without_ mods? I see your comment that "By comparison, when I switch to vanilla LODs (LCtrl + Shift + .) the frame rate increases." so just want to double check.

If you're only able to see the issue using mods, then I'd recommend testing them out one by one to see if there is a specific culprit and working with that mod dev to report the issue. Let us know. Thanks!

**Comment by Gabriela-Intel** [comment]
Any update on this?

**Comment by ygugsa** [comment]
> Any update on this?

I will give it another shot with 4972 this weekend, maybe tomorrow if I can find time, and get back to you.

I should also mention I'm not seeing the option in DSA for beta driver opt-ins, but I don't know who to talk to about it.

**Comment by Gabriela-Intel** [comment]
Thanks for the update!

To receive beta updates, uncheck the box under "WHQL Certified Updates" listed under Settings in IDSA.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/114173691/89faa6f2-e64f-4a62-b9ca-217adc82caea)

**Comment by ygugsa** [comment]
> Thanks for the update!
> 
> To receive beta updates, **uncheck** the box under "WHQL Certified Updates" listed under Settings in IDSA.
> 
> ![image](https://private-user-images.githubusercontent.com/114173691/287111665-89faa6f2-e64f-4a62-b9ca-217adc82caea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzOTQzMTcsIm5iZiI6MTcwMTM5NDAxNywicGF0aCI6Ii8xMTQxNzM2OTEvMjg3MTExNjY1LTg5ZmFhNmYyLWU2NGYtNGE2Mi1iOWNhLTIxN2FkYzgyY2FlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQwMTI2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDkyNGM2OTZjYTQ5ZjRkMDQxNmE5ODMzZGY4NTA3NjdhOTM4YTEyNTMwNGI5ZmQ0NDc4M2YxODI5OGQyMTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4rgaYc9rr1aPQ7w0xo-wa8zrHnSWnuwglmO27VdQSqM)

Has the method changed compared to what's on product docs?
![image](https://www.intel.com/content/dam/support/us/en/images/graphics/94115-img1.jpg)
Taken from https://www.intel.com/content/www/us/en/support/articles/000094115/graphics.html

**Comment by Gabriela-Intel** [comment]
Sorry for the late reply! And yes, thanks for catching that. That article needs to be updated. I'll work on fixing that.

**Comment by ygugsa** [comment]
> Sorry for the late reply! And yes, thanks for catching that. That article needs to be updated. I'll work on fixing that.

By the way, will this be for the closed beta where drivers are released a few weeks ahead of general availitability?

**Comment by Gabriela-Intel** [comment]
@ygugsa No, this is not for the closed beta drivers. The closed beta driver testing sign up will be opening up again in the near future, so I'd recommend keeping an eye on our site for when that registration opens up again :)

**Comment by Gabriela-Intel** [comment]
@ygugsa To follow up on this, I just want to reiterate that we don't support issues (even performance issues) seen when using mods. Any issues with mods should go directly to the mod developer. Though I understand that you're still not getting the performance you'd prefer to see even when you're not using any mods. Given that we are discussing CSL1 here and the performance is expected (I saw ~70 fps on average on my end), we are unfortunately limited with our options to move forward with this.

That being said I hope you are okay if we continue with closing this one out.

**Comment by ygugsa** [comment]
> @ygugsa To follow up on this, I just want to reiterate that we don't support issues (even performance issues) seen when using mods. Any issues with mods should go directly to the mod developer. Though I understand that you're still not getting the performance you'd prefer to see even when you're not using any mods. Given that we are discussing CSL1 here and the performance is expected (I saw ~70 fps on average on my end), we are unfortunately limited with our options to move forward with this.
> 
> That being said I hope you are okay if we continue with closing this one out.

You can close it. But please make it clearer in the "new issue" form that performance issues with mods are not covered.

**Comment by Gabriela-Intel** [comment]
I'll this feedback back to the team, thanks!

@IGCIT

**Comment by IGCIT** [comment]
> You can close it. But please make it clearer in the "new issue" form that performance issues with mods are not covered.

this is already mentioned in some way when you open a new issue

![Screenshot_20231222_093433](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/76787191/ad6d08a3-7ecd-4f54-8b64-2a937677f03c)
