### ISSUE TITLE
ARC driver installation seems to force some taskbar icons to show generic images

### ISSUE THREAD

**Issue by BigNish7** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#516]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

MS Windows 11 Pro 22H2

### Processor / Processor Number [Required]

Intel Core i9 13900KS

### Graphic Card [Required]

Intel ARC A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [X] 31.0.101.4672
- [X] 31.0.101.4669
- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [X] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

22621.2283

### Intel System Support Utility report

[System Support Log_BigNish7_14 September 2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12642883/System.Support.Log_BigNish7_14.September.2023.txt)

### Description and steps to reproduce [Required]

I noticed that three of my taskbar icons (Chrome, HWINFO, Intel PresentMon) revert to a generic image after rebooting from installing the ARC Diver. After using DDU to remove the driver, the specific application icons reappear.

The image below is my taskbar with no Intel ARC diver installed:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/a393853b-b87f-4024-808f-ea4a8a346066)

The image below show my taskbar after rebooting as the last step of installing an ARC driver:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116610885/2d2e13b8-6393-4fb2-b31a-145ec880b001)

I don't know why it is only the Chrome, HWINFO and PresentMon icons that are affected.

To do some testing, I did a fresh installation of each of the WHQL divers listed below and used DDU to remove each version before trying the next drive:   

- 31.0.101.4824
- 31.0.101.4672
- 31.0.101.4669
- 31.0.101.4644
- 31.0.101.4314 (to try a much older driver)

The three pesky taskbar icons all showed generic images after rebooting for every one of the driver versions above I tested, and they returned to their proper icons after removing the driver with DDU. 

Any suggestions to why this may be occurring, or any things I could try to fix this issue would be appreciated.  

### Device / Platform

DESKTOP-ECBGJIO

**Comment by Karen-Intel** [comment]
Hey @BigNish7 ty for your report!

Allow us to do some debug on this behavior you've spotted. We'll get back to you soon!

Karen

**Comment by BigNish7** [comment]
Here is some updated info on this issue. I am happy to say that at some point, not entirely sure what triggered it, the 3x generic icons changed back to their respective specific icons. I had not updated/touched the driver or ARC Control settings.

I then upgraded to the latest driver v31.0.101.4885. I did this by removing the .4826 driver using DDU. After the installation process for .4885, I rebooted as recommended and.....dang!, the three same icons had reverted back to their generic versions again. I was back at square one.

However, I have my PC set up to turn off the monitor after 30mins and my PC after 2 hrs under the Balanced power setting in Win 11. I had to leave my PC at some point (longer than 30mns but shorter than 2 hrs) and when I returned my monitor had been turned off, but my PC was still on. I woke up the monitor and the three icons had now stopped being the generic versions  and were showing as their correct specific icons as they should be! 

Still not sure what is causing it, but I wonder if this helps at all?

**Comment by Karen-Intel** [comment]
Hey @BigNish7 I think this might be more related to Windows. I found this [thread,](https://www.lifewire.com/fix-icons-in-windows-11-7368191#:~:text=Open%20Windows%20Task%20Manager%2C%20go,or%20out%2Dof%2Dsync.) please let me know if you see any changes!

Karen
