### ISSUE TITLE
Overwatch 2 massive hitching after every driver update.

### ISSUE THREAD

**Issue by Code-Vlue** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#517]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Overwatch 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [X] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12642921/ssulog.txt)

### Description and steps to reproduce [Required]

Game will have massive hitching after a driver update in the first game you play, hitching can last anywhere from a second to a few seconds where the game stalls out. After playing for a while hitching will become stuttering and eventually smooth out the more you play but that will be reset after a driver update.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Epic settings with custom resolution scale 125% min and 175% Max, dynamic rez on. Sometimes changing settings will also cause the issue to start up again.

**Comment by Vipitis** [comment]
I assume that is expected shader compilation

**Comment by Code-Vlue** [comment]
@Vipitis Still submitting it as an issue since it isn't severe in all games and the compilation causes the game to freeze for a few seconds at a time sometimes in the most severe cases and some games like DX11 ones like Overwatch don't hitch at all on other cards.

**Comment by Code-Vlue** [comment]
GTAV for example will have some slight little stutters until it irons out where as the games I listed have massive hitches.

**Comment by Arturo-Intel** [comment]
@Code-Vlue would be awesome if you create a case for each game you tested, that way we can track individualy each case.
I assume you tested each game using the latest driver and a older one, which driver you used to compare the latest one to verify the massive hitching?

-- r2

**Comment by Code-Vlue** [comment]
@Arturo-Intel I will do some more testing and do that, for now I will switch this to Overwatch since it is one of my most played games and one of the most affected by the issue.

**Comment by Arturo-Intel** [comment]
@Code-Vlue oh ok, can we add "Overwatch" to the case title?
What about the previous driver? it was  31.0.101.4676 when the game didnt had this behavior? (massive hitching)

**Comment by Code-Vlue** [comment]
@Arturo-Intel it has always had hitching that I've just dealt with until now, I didn't put together it was the driver update causing it to hitch again until after the most recent one. Also Overwatch was put in the title.

**Comment by FuzzyQuills** [comment]
This hitching after a driver update in Overwatch 2 is normal I'm afraid; the game has something like 75K shaders to compile on startup unless they've already been built for the installed graphics driver, and in that case it'll be smooth from the get-go.

Other than Intel optimising their shader compiler to compile them quicker, I'm not sure if this is fixable.

**Comment by Code-Vlue** [comment]
@FuzzyQuills I was hoping that wasn't the case, I have used OW2 under DXVK in Linux as well and had hitching but thought it might be something else since I'm coming from am RTX 2060 Super and it didn't have this issue but the shaders must have been precompiled for that GPU in the driver then it seems.

**Comment by FuzzyQuills** [comment]
> @FuzzyQuills I was hoping that wasn't the case, I have used OW2 under DXVK in Linux as well and had hitching but thought it might be something else since I'm coming from am RTX 2060 Super and it didn't have this issue but the shaders must have been precompiled for that GPU in the driver then it seems.

There's also a chance the NVIDIA shader compiler on Windows is more efficient; I noticed the same thing on a really old machine years ago with a measely GT 640.

**Comment by Arturo-Intel** [comment]
@Code-Vlue With .5081 did you get the massive hitching after you update the driver?
-- r2

**Comment by Arturo-Intel** [comment]
Please open a new case if this behavior is still present.
Closing case.
