### ISSUE TITLE
Ghostrunner crashes while loading level

### ISSUE THREAD

**Issue by Yomi0** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#519]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Ghostrunner

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 5900X

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

- [X] 31.0.101.4824
- [X] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [x] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

19045.3448

### Intel System Support Utility report

[ssu_report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12643502/ssu_report.txt)

### Description and steps to reproduce [Required]

This crash happens right after I freed Whisper from his cell, in the middle of the cyberspace mission right after.
https://streamable.com/vgyrri

Here's the crash dialog box, since the video isn't very high quality.

![The UE4-Ghostrunner Game has crashed and will close 9_17_2023 2_41_14 PM](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3170531/83b0698d-7d89-4a25-8073-13b10c2425da)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![Ghostrunner   9_17_2023 2_40_51 PM](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3170531/409c6a9e-b062-4d75-ba83-978102d3fd0e)
![Ghostrunner   9_17_2023 2_40_57 PM](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3170531/c57f4121-a48b-4736-a1aa-6300699e6e8e)

### Save game

[Saved.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12643482/Saved.zip)

**Comment by abrfilho** [comment]
The same error happened to me with Ghostrunner 2 demo.

**Comment by Ilya-intel** [comment]
@Yomi0 
Developers are working on this issue with DX11, but with DX12 it runs well for me.
Do you see the same issue with DX12?

**Comment by Yomi0** [comment]
I'll test and let you know.

**Comment by Yomi0** [comment]
That worked, thanks!

**Comment by Ilya-intel** [comment]
@Yomi0 
Ok, good. FYI devs are working on the DX11 Crash under Bug ID 18033012743.
I'll post here when the fix goes live.

**Comment by Ilya-intel** [comment]
@Yomi0 
Game seems to be pretty stable in DX11 now, could you confirm?

**Comment by Yomi0** [comment]
Still seeing the same crash when I load into the game with DX11.

**Comment by Ilya-intel** [comment]
Hi @Yomi0 ,
We have finally released a big driver fix for big amount of games that greatly improves performance and stability of DX11 titles.
Ghostrunner is one of them.
I've just played and could successfully pass the level reported.
Could you also test and confirm?

**Comment by Ilya-intel** [comment]
Closing this thread.
