### ISSUE TITLE
Paladins Crash on startup

### ISSUE THREAD

**Issue by brendan1234567123** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#52]
#### Checklist [README]

- [ X] Device is not undervolted nor overclocked.
- [X ] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [X ] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Paladins
---
#### Processor / Processor Number [Required]
Intel Core i7-1165G7
---
#### GPU Driver Version [Required]
- [X ] 27.20.100.9466 (*latest*)

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X ] DirectX9

---
#### Windows Build Number [Required]
- [X ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1. Starting the game using steam
2. Game crashes after the splash screen loads
3. 

---
#### Device / Platform [Optional][Recommended]

GPD Win 3 Steam

---
#### Game Settings [Optional][Recommended]

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---

**Comment by mva94** [comment]
@brendan1234567123 that is not an intel issue .
Try the epic store instead of steam and the game don't crash anymore .
For some reason it works no more with steam .
Close the issue if it is solved
