### ISSUE TITLE
Chorus crashes while flying to Asteroid Lair 

### ISSUE THREAD

**Issue by Yomi0** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#520]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Chorus

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 9 5900X

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

- [X] 31.0.101.4824
- [X] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [x] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

19045.3448

### Intel System Support Utility report

[ssu_report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12643528/ssu_report.txt)

### Description and steps to reproduce [Required]

Here's a video link: https://streamable.com/g15ls4

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

3480x2160

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![Chorus   9_17_2023 3_00_31 PM](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3170531/e9162c83-c68f-465b-8c6f-42496663adc8)
![Chorus   9_17_2023 3_00_22 PM](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3170531/640c22a9-f76f-4930-b920-cde34129b888)

### Save game

[SaveGames.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12643524/SaveGames.zip)

**Comment by Arturo-Intel** [comment]
@Yomi0 Do you still see this behavior in your end?
If you do so, can you share the save files?

**Comment by Arturo-Intel** [comment]
Just FYI, this case is being reviewed by our engineering team, 
here is the id: 14020638676

-- r2

**Comment by Yomi0** [comment]
I can check.

**Comment by Yomi0** [comment]
Still crashing with the latest available drivers: 31.0.101.5593
However, the error has changed. See attached images.

<img width="1920" alt="Screenshot 2024-06-29 212318" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3170531/a89c61a5-6fef-470b-bc67-81953be285f1">
<img width="308" alt="Screenshot 2024-06-29 212327" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3170531/084f1323-a441-47bc-985d-8632e6871791">

**Comment by Yomi0** [comment]
I should mention, this does work if the game is launched with `-dx11`, however, as a result, XeSS and ray tracing are disabled.

**Comment by Arturo-Intel** [comment]
@Yomi0 can you try with the latest driver? (32.0.101.5971) I was able to reach our "old friend" without any crash using dx12

**Comment by Yomi0** [comment]
Hey @Arturo-Intel, 

I didn't get a notification for the comment, but I'll test it out.
Thanks!

**Comment by Yomi0** [comment]
It works now, thanks!
