### ISSUE TITLE
More info inside Arc Control overlay

### ISSUE THREAD

**Issue by abrfilho** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#523]
### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

Ryzen 5 5600

### Graphic Card [Required]

Intel Arc A770

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Other Windows build number

22621.2283

### Describe the feature [Required]

I would like to see add to Arc Control more metrics related to the CPU, like temperatures and clocks, not only usage, and related to the game too, like FPS and frametime, or even GPU Busy implemented there, like it's shown with Intel's PresentMon.

**Comment by Gabriela-Intel** [comment]
Thanks for the feedback! We've seen a lot of requests for similar information in Arc Control so I'll make sure the team is aware about it.

@IGCIT You can close this one.
