### ISSUE TITLE
High idle power draw

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#524]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

None

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 19.09.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12656198/Intel.SSU.19.09.2023.txt)

### Description and steps to reproduce [Required]

My GPU is drawing 40W at idle. I have already enabled ASPM, and L1 Substates as stated [here](https://www.intel.com/content/www/us/en/support/articles/000092564/graphics.html). I couldn't find any other info than this on the internet about how to drop it down

### Device / Platform

ASUS Prime Z790-P WiFi D4

**Comment by TheWonderfulTartiflette** [comment]
@Arturo-Intel I've already followed the two steps here, and I only have one 1080p 144Hz

**Comment by TheWonderfulTartiflette** [comment]
@Code-Vlue I'm actually a bit worried about losing performance by doing that, will I ?

**Comment by Code-Vlue** [comment]
@TheWonderfulTartiflette I haven't seen any performance loss in games or in benchmarks, from what I understand the setting with Arc cards is needed to put it into a lower power state, so I'd try setting it to PCIE Link State Max Power Saving and see how it goes.

**Comment by TheWonderfulTartiflette** [comment]
@Code-Vlue Actually I didn't remember, but I already had it enabled in the control panel, so I'm still drawing ~45W at idle with this enabled

**Comment by Code-Vlue** [comment]
@TheWonderfulTartiflette just for the sake of testing maybe try setting the refresh rate to 60hz like @WouterNed mentioned and see what happens to power draw then.

**Comment by TheWonderfulTartiflette** [comment]
@Code-Vlue Same. Should I bother rebooting after applying 60Hz ? I don't want to reboot for nothing you know

**Comment by Code-Vlue** [comment]
@TheWonderfulTartiflette rebooting probably won't make a difference, last thing I would check is in your task manager go to your processes and sort by GPU usage to see if anything is utilizing it in the background you might not know about causing the power usage to stay up.

**Comment by TheWonderfulTartiflette** [comment]
@Code-Vlue GPU's at 1% usage, and the app that takes the most GPU is the Desktop Windows Manager, at 0.2%

**Comment by Code-Vlue** [comment]
@TheWonderfulTartiflette That is odd then, I'm at the extent of what I can help with then because my system is behaving differently than that, I am however using 2 60Hz monitors, one 1080P the other 1280x1024.

**Comment by WouterNed** [comment]
Yeah, I came to the conclusion that it wasn't supported at 1440p@75hz, even though the pixel output was lower than 4k@60. Sorry about that too. I currently play a game which is hard capped at 60fps, so limiting my framerate to 60 isn't a disaster. It even helps with youtube video playback as it doesn't have to be synced to 75hz

I will probably, in time, create some kind of shortcut to switch to 75hz for gaming. 

[Intel's explaination](https://www.intel.com/content/www/us/en/support/articles/000092564/graphics.html#:~:text=Also%20note%20that%20if%20you%20attach%20a%20display%20to%20Arc%20graphics%20with%20a%20refresh%20rate%20over%2060Hz%20requires%20the%20GPU%20to%20run%20at%20slightly%20higher%20clocks%20to%20drive%20the%20pixel%20throughput.)

**Comment by TheWonderfulTartiflette** [comment]
@WouterNed Strange, as even setting Windows to output 1080@60 doesn't solve the issue for my part

**Comment by jpovixwm** [comment]
May be worth a try to update your mobo's BIOS, if there's a newer version available. I had to update my X370 board to see the lowered power consumption. And then only at 4K60, as at 4K120 it's back at ~38 W.
Have you tried measuring the power consumption on the lock screen, after the displays go blank and are put into standby mode?

**Comment by TheWonderfulTartiflette** [comment]
@jpovixwm nope, still, my bios is fully up to date

That would be interesting, but what do you mean by blank display?

**Comment by jpovixwm** [comment]
@TheWonderfulTartiflette I meant that after you lock Windows with Win+L, you get the lock screen, and if you wait for a minute, all connected displays stop receiving video signal and enter standby mode (at least that's what happens with PC displays, as a TV may instead show the "no signal" thingy). I thought this would let you check if the power consumption goes down when nothing is sent to the displays.
Maybe you could get the same effect by physically disconnecting all your displays too.

**Comment by TheWonderfulTartiflette** [comment]
@jpovixwm ah okay I see, I'll test it soon

**Comment by TheWonderfulTartiflette** [comment]
@jpovixwm Seems like physically disconnecting **and** setting it to sleep doe not change the power consumption. 
Here are maybe some “proof” screenshots, as I know this can seem like I'm lying about it
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/2919b838-615f-43a8-ae9f-7243cb5c9e31)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/2b9809da-6332-4798-be1a-63cc9a718d87)
![PXL_20230920_115739795](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/ccc38cd3-a062-492f-a96f-791e5c1e1355)

**Comment by Code-Vlue** [comment]
@TheWonderfulTartiflette Wait I thought that setting was supposed to be enabled in BIOS.

**Comment by TheWonderfulTartiflette** [comment]
@Code-Vlue Well, even when enabling it (setting it to "L1", only thing I can do more) doesn't do anything else

**Comment by TheWonderfulTartiflette** [comment]
@Darklegion1978 no worries, but yeah, I own a limited edition (Intel version)

**Comment by Darklegion1978** [comment]
@TheWonderfulTartiflette Thx a lot. But then im out too.

I just know that Acer wont work with ASPM, they have no fix for theyr FW to get it work with it.
Asrock has an fix on theyr website that ASPM works.

But with the LE Card it normaly should work as you set up your Bios and Windows.

Im sorry ;(

**Comment by WouterNed** [comment]
The only thing I can think of that you could try is reinstalling the drivers using the intel DDU tool. If that doesn't work then i'm out too.

**Comment by TheWonderfulTartiflette** [comment]
@WouterNed well I've already done it for another recent issue, and nothing changed

**Comment by opteronm** [comment]
Have you tried using your CPU integrated graphics as a pass through? Make sure your igpu is enabled in the bios. Connect your hdmi/DP to your motherboard instead of the GPU and boot up. The ARC will be at really low to zero idle power and you can still play games like normal. I’ve been running my PC like this for a couple of months now and it’s great. 

Follow these steps: https://reddit.com/r/IntelArc/s/Q6zmllpQC6

**Comment by TheWonderfulTartiflette** [comment]
@Kawamaha still, just tried your settings (one time with L1 Substates L1.1 & L1.2, and one time with L1 Substates L1.1), but still ~45W of idle

**Comment by TheWonderfulTartiflette** [comment]
So, I've just tried to plug my DisplayPort into my motherboard, and [this is what I'm getting](https://drive.google.com/file/d/1ISrddyRJ5AXz2y0fj1PU6oQpMS0_V5Kj/view?usp=sharing)

This is surely not due to a hardware fault, because when in the UEFI, the problem isn't there

**Comment by TheWonderfulTartiflette** [comment]
Well, seems like it was the “Automatically adjust the application colors” in windows that messed it up
So, I'm now currently using the DP port on my motherboard with the “Multi monitor iGPU” setting enabled in the BIOS, with both GPUs up to date, and my Arc is drawing now around 37 watts. It's a bit less than before, but still not as low as I'm supposed to get

**Comment by muzadull** [comment]
Can anyone with an Intel ARC A770 LE confirm that ASPM works correcly with their card?
Mine seems to disable ASPM on it own despite ASPM being enabled in the bios.

ASPM status on Intel Arc A770:

![Intel Arc ASPM](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/7374351/420591ac-337e-422a-b1b0-95c04cf92299)

ASPM status on NVME:

![NVME aspm](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/7374351/d1d3429b-cc11-4c87-af1e-8c38e7b35a15)

**Comment by muzadull** [comment]
Update:
Motherboard : Gigabyte Z390 M Gaming
CPU : 8600K
GPU : Intel Arc A770 16GB LE

After a new bios provided by gigabyte the gpu does go to idle properly now.

![ARCA770-ASPM-WORKING](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/7374351/9d3b9312-a1ff-4089-92d1-cdbb33e3a500)

**Comment by Felipe-Intel** [comment]
hello @TheWonderfulTartiflette 

I tested with my A770, Driver 5085. MSI Pro Z790-A wifi motherboard, i5-13400, windows 10. After setting the BIOS and Windows options according to the article you consulted, and setting graphics resolution to 1080p@60 I was able to obtain idle power draw below 7 W. For 1440p@60 i got around 8 W

Please contact the manufacturer of your motherboard for further instructions on how to set up the requirements for the low idle power in your specific BIOS settings, according to the instructions on the knowledge article. 

Said that, keep in mind that setting up refresh rates above 60 Hz will prevent the card from entering the low power state, as indicated in the article:
_"Also note that if you attach a display to Arc graphics with a refresh rate over 60Hz requires the GPU to run at slightly higher clocks to drive the pixel throughput. We will be looking at making optimizations in future generations."_

I will close this thread. If you still have issues after consulting the motherboard OEM feel free to open a new case.

**Comment by JamasChuang94** [comment]
> 更新： 主板：技嘉 Z390 M Gaming CPU：8600K GPU：英特尔 Arc A770 16GB LE
> 
> 在技​​嘉提供了新的 BIOS 之后，GPU 现在确实可以正常空闲。
> 
> ![ARCA770-ASPM-工作](https://private-user-images.githubusercontent.com/7374351/292216288-9d3b9312-a1ff-4089-92d1-cdbb33e3a500.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjQ4NTMsIm5iZiI6MTcyMzI2NDU1MywicGF0aCI6Ii83Mzc0MzUxLzI5MjIxNjI4OC05ZDNiOTMxMi1hMWZmLTQwODktOTJkMS1jZGJiMzNlM2E1MDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMDQzNTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTg5ZjJhNGM2YzZlOWFlN2NhNTljZmUzMTQ0YTIyMjYwNmY5N2M4MDk2YjZhNTY1Njk2NGNmNjVlYWVlYmYxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rc89Zd5U0S0PJLB-ssgHIiSzbm-M7X4UisTSBV3dGsA)

This doesn't matter unless you use an iGPU instead of a PCI GPU

**Comment by JamasChuang94** [comment]
> 尝试将“本机 ASPM”设置为自动并将显示器连接到集成 GPU 而不是 Arc。 使用 DDU 并重新安装驱动程序，将 Windows 电源选项中的“链接状态电源管理”设置为“最大节能”。
> 
> ![个人简介](https://private-user-images.githubusercontent.com/60267630/275343371-6701f4f2-35ec-4fc9-ab72-0b5308e13480.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjQ4NTMsIm5iZiI6MTcyMzI2NDU1MywicGF0aCI6Ii82MDI2NzYzMC8yNzUzNDMzNzEtNjcwMWY0ZjItMzVlYy00ZmM5LWFiNzItMGI1MzA4ZTEzNDgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA0MzU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MGJhZTBlNTc5NTcyMTQ4MzQ2ZjUxNGJmYWYzNTQxNWE3MzRlMTkxNDJmNjNiMDhjOTg3Y2FlY2Y2YjMyNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6z8Yn5vcNpv2md6wo5BWl1v-5Yr0wHOOHl8FsrRNOoE) ![信息](https://private-user-images.githubusercontent.com/60267630/275343372-28edfb8a-86ed-4801-ae9b-0f020fdd35cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjQ4NTMsIm5iZiI6MTcyMzI2NDU1MywicGF0aCI6Ii82MDI2NzYzMC8yNzUzNDMzNzItMjhlZGZiOGEtODZlZC00ODAxLWFlOWItMGYwMjBmZGQzNWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA0MzU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNTkyOThiMjQ4ODM1MjhkMWY0MjRmNWQxZTM5MGE1MjNmYWU0ZmE2ZDExNmUwNzg2NGMwODMyYmYwMDU1MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rOHPK1Hend4tu05Cn0DH8oihbNQnqaJaX_5nfwGcZlA) ![英特尔动力](https://private-user-images.githubusercontent.com/60267630/275343374-d8e0c8a9-4354-4cff-9bfa-7fbab9328239.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjQ4NTMsIm5iZiI6MTcyMzI2NDU1MywicGF0aCI6Ii82MDI2NzYzMC8yNzUzNDMzNzQtZDhlMGM4YTktNDM1NC00Y2ZmLTliZmEtN2ZiYWI5MzI4MjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA0MzU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYjc2MjQ4YzlmZGIzNzUwNWRjMmNiNjFiZTg1NzkyOGRiMGMxYWIxM2JjNWVhZjBjMDk4MGRkYjc5NTM4ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JruHJPHW-emC0h8-C4XrMtOV5HIwPlbUbOkEA_OhMoc)

This operation is stupid and troublesome, and it will be very troublesome for users who don't have an iGPU.
AMD and Nvidia graphics cards that are not suitable for iGPU only consume about 7W and 11W in standby mode. Playing 4K video consumes only about 20W
