### ISSUE TITLE
Handbrake AV1 QSV Encoding Broken

### ISSUE THREAD

**Issue by Code-Vlue** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#525]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Handbrake

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12665236/ssulog.txt)

### Description and steps to reproduce [Required]

When using AV1 QSV encoding on handbrake finished encoded file shows as all green video output but audio still plays, GPU usage shows as 100% as well but not max clocks and encoding time is short, sub 20min for 4K video. When file is encoded using QSV H.265 the video will encode as expected, GPU clocks are high with not max GPU usage but encoding time is much higher, around 50 min.

**Comment by Karen-Intel** [comment]
Hey @Code-Vlue can you share the exact option you're using for the green output? I tested with VeryFast 2160p60 4k AVI and HQ2160p60 4K AVI Surround and I'm unable to see the green output. If you could share a video I'd appreciate a ton to see the 2nd issue too :3

Ty

Karen

**Comment by Code-Vlue** [comment]
Sure @Karen-Intel I was using the Hardware Encoding section preset for QSV AV1 4K.

**Comment by Code-Vlue** [comment]
@Karen-Intel Upon further testing the issue seems to be linked to HDR, the AV1 Quick Sync encoder used on Handbrake is able to output 10-bit HDR and the source file had HDR. When converting a file without HDR the preset will work however when I converted an HDR test file it again gave a green screen with audio playing. I have attached the video for example.

Please note the video has been compressed from its original encode to be able to attach to this post.


https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/142824040/6e83f660-d907-42e7-a15f-e8626bf73474

**Comment by Karen-Intel** [comment]
Hey @Code-Vlue can you tell me if [what I'm doing](https://www.youtube.com/watch?v=HGE6OYsQohY) is right?
Perhaps I'm missing something

Ty

Karen

**Comment by Code-Vlue** [comment]
@Karen-Intel You're doing it a little different than I am, I go to the drop down box that says preset, its at the top below title. Also it looks like the file you are encoding is already AV1 where as the one I am encoding is H.264. I've attached pictures to show what to choose and the codec that is being used for the original file.
![Screenshot 2023-09-19 172604edit](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/142824040/ed035d5b-5aac-4d8c-b7ef-3e567add2a82)
![Screenshot 2023-09-19 172726edit](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/142824040/8f4b8769-3439-4d70-b292-d00b823c73aa)

**Comment by Karen-Intel** [comment]
Hey @Code-Vlue results of today's experimets :)

1. I also got a H.264 video, you can see it in the following specs and with Preset: Fast 1080p30 which shows that info

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/1d7d67fc-fdfd-4ae6-ade2-a4568c2d04e5)

If I proceed to start the encode with this preset, output video is not green at all. You can see the miniature there

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/95eedae6-8462-42e0-9520-216d5a31906b)

2. When I select the AVI QSV 2160P 4K Preset (The Default one I have) the video specs change

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/1f2dbc15-7a82-4c57-b120-bfc59892ccbe)

Proceed to encode with the AVI HW Preset, no green output anywhere o.O

Help, I can't repro the green output xD

Karen

**Comment by Code-Vlue** [comment]
@Karen-Intel Odd maybe its something with my specific config then, I'll do some more testing and see if I can figure anything out.

**Comment by Code-Vlue** [comment]
@Karen-Intel That was fast I think I figured it out, seems to be that the green output has to do with variable frame rate on an HDR encode, when I went into the video tab and changed it to constant frame rate and same as source, the video outputs correctly now. The encode even took about 3x as long as before so something about the variable frame rate setting with this kind of encode must cause issues.

**Comment by Karen-Intel** [comment]
@Code-Vlue hmm I just checked my Video encoder settings and I had variable frame rate all the time + same as source. Can you show me the config you have under the Video tab? Thank you

Karen

**Comment by Code-Vlue** [comment]
@Karen-Intel I just left my desk so I'll have to when I get back, I can say though I just tested them back to back, chose the AV1 QSV 4K preset and left it at all default settings and got the green screen, tried again with the only change being from variable frame rate to consistent frame rate and the video renders properly.

**Comment by BiZkViT96** [comment]
I'm annoyed just from reading all this.

@Karen-Intel I understand that you want to help, but he didn't give **any** useful information to you. After you failed to reproduce the problem (surprise) for first time, you should have asked for video file and clear steps on how to reproduce the green screen. Before that, you didn't have to do anything.

@Code-Vlue Upload your original HDR video. Post which version Handbrake you use and step by step instructions on how to get that green screen bug. If you had done it from the very beginning, then all this could have been avoided.

This is shouldn't be a hot and cold game for customer support.

**Comment by Code-Vlue** [comment]
I'm gonna close this issue since it seems to be specific to my system or specific media and can be fixed by a change in setting. Thank you @Karen-Intel for working with me on this issue.
