### ISSUE TITLE
Intel Arc Control - Application Error and becomes unresponsive

### ISSUE THREAD

**Issue by gargamel314** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#526]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

i7-13700K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4826
- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU - Intel Arc Control.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12667363/SSU.-.Intel.Arc.Control.txt)

### Description and steps to reproduce [Required]

No idea how to reproduce - Intel Arc Control starts at boot and this error shows up within 30-60 minutes of being on. So far it's only happened on the desktop, not with any game or specific application open. This error shows up (see attached image) and then the whole Arc Control window becomes completely unresponsive. The window will show up when you select it, but you can't click on any of the tabs on the left (i.e. Drivers, Games, Performance, etc). This happened with Arc Control bundled with v4824, but also happened with v4826 now. Memory leak has not been an issue since v4826.

![Screenshot 2023-09-19 193321](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/124757309/6d35e355-a1a3-4604-9b71-08b1f71636db) This is the same software exception number and code location every time.

### Device / Platform

ASUS Strix Z690-A D4

### Crash dumps [Required, if applicable]

See the above screenshot

**Comment by freak2fast4u** [comment]
When you say "Intel Arc Control starts at boot and this error shows up within 30-60 minutes of being on.", do you mean leaving the Arc Control window open during that time ? Or just having the computer turned on with ArcControl processes in the background ? 

Other than this specific question, I don't seem to have this problem on Windows 10 22H2 / Ryzen 7000 platform, on 4826 beta drivers. Maybe I'll let the UI open for an hour just for fun and see if something happens ;p

As of now, the ArcControl processes use a reasonable amount of RAM, and my system has been running for over 3 hours : 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/f329898e-6ab9-45db-adee-b5bce2f62ee8)

**Comment by gargamel314** [comment]
A lot of times I do leave that window open. I can't be sure if it happened with it open or not.

**Comment by gargamel314** [comment]
Update - no, the same thing happens when you close the window and leave it running in the background.

**Comment by wolf-yuan-6115** [comment]
> Update - no, the same thing happens when you close the window and leave it running in the background.

In my case, it looks like Arc Control has a memory leak issue. It will keep using more and more memory until Windows notices it and throws an error out.

For example, after booting up my machine for 30 minutes, Arc Control already took WHOPPING 16 gigs of ram.

**Comment by Gabriela-Intel** [comment]
@gargamel314 Are you still seeing this issue? We haven't observed this behavior or seen other reports of this so please let us know.

**Comment by Gabriela-Intel** [comment]
Great news! Thanks for confirming.

@IGCIT We can close.
