### ISSUE TITLE
[Graphics Glitch] Atelier Sophie Alchemist of the Mysterious Book

### ISSUE THREAD

**Issue by kurikomoe** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#53]
#### Checklist [README]

- [X] Device is not undervolted nor overclocked.
- [X] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [X] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Atelier Sophie Alchemist of the Mysterious Book
Steam:  https://store.steampowered.com/app/527270/Atelier_Sophie_The_Alchemist_of_the_Mysterious_Book

---
#### Processor / Processor Number [Required]
intel 1165g7

---
#### GPU Driver Version [Required]
- [X] 27.20.100.9466 (*latest*)
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [X] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1. Mostly happens in the real-time rendering of cinematics 
2. The eye texture of the characters disappears.
![screenshots](https://user-images.githubusercontent.com/31176859/119451568-ff73ea80-bd67-11eb-9d26-f84361429a21.png)

---
#### Device / Platform [Optional][Recommended]

OneXPlayer 1165g7, public released version

---
#### Game Settings [Optional][Recommended]

Default settings.

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---

**Comment by estebanr863** [comment]
Hi @kurikomoe,

Can you please let us know what game version was this issues observed on?

**Comment by estebanr863** [comment]
Hi @mva94 and @IGCIT, we cannot reproduce this issue on the latest drivers and @kurikomoe is not responding. Can any of you help test this?

**Comment by kurikomoe** [comment]
Sorry for the late response. I was busy with the end-term exams
The steam store page of this game is:
https://store.steampowered.com/app/527270/Atelier_Sophie_The_Alchemist_of_the_Mysterious_Book/

The version is the latest version from steam (2021/12/24), I believe it's 1.0.0.21

The glitch occurs only in cutscenes with player's eyes

This is the latest screenshot on my onexplayer(1165g7)

![20211224185503_1](https://user-images.githubusercontent.com/31176859/147347337-aa74efff-e571-4288-b158-c4b7fbb09ff6.jpg)




--------------
windows 11
1165g7 with intel 30.0.101.1191 driver
game version: 1.0.0.21

**Comment by estebanr863** [comment]
Hi @kurikomoe,

Unfortunately, if the game version presenting the issue is no longer available, we cannot work on find the root cause of the issue. It is possible that the Deluxe version includes a fix from the developer for this issue, which matches are initial suspicions from looking at your screenshots of some textures not loading, which is usually an issue caused by the game, not the GPU. However, as I mentioned, we cannot confirm these suspicions, since the game version you reported it on is no longer available.

**Comment by kurikomoe** [comment]
It's ok, 
The dx version has replaced the original one, I think it's ok to close this issue.
