### ISSUE TITLE
No screen output on Dual Xeon system W/ ASUS Z10PE-D16, cant boot into windows.

### ISSUE THREAD

**Issue by S0m3guy1** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#530]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Booting Into windows

### Processor / Processor Number [Required]

Intel Xeon E5-2697 V4 X2

### Graphic Card [Required]

ASRock Phantom gaming Arc A770 16GB

### GPU Driver Version [Required]

- [ ] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [X] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

I cant even get into windows to generate the report.

### Description and steps to reproduce [Required]

Install a Arc GPU into a Dual xeon system built using the ASUS Z10PE-D16 WS using the latest bios from asus. 

Card turns on, and power up no problem. I'm able to get the Bios to pull up and get into the sub menus for NIC cards, Raid Cards, ETC... but once it goes into booting windows the screen turns off. I'm able to get two different Nvidia based cards to boot, even with generic drivers. The ARC does not.

### Device / Platform

ASUS, Intel, Samsung

**Comment by Arturo-Intel** [comment]
Hi @S0m3guy1
Unfortunately Xeon is not among supported platforms, you can read about it here: https://www.intel.com/content/www/us/en/support/articles/000091128/graphics.html

Also:
"For configurations not listed in this guide, there may be **performance or stability issues**. We recommend updating to one of the configurations listed for optimal performance with Intel® Arc™ Graphics."

@IGCIT Can you close this case, please?

**Comment by S0m3guy1** [comment]
Xeon isnt listed as specifically not working but ok. Would be really nice if your partners who are selling graphics cards put some kind of disclaimer but hey at least intel got a sale out of me. 

"Additional platforms/motherboards not listed below and with Resizable BAR / Smart Access Memory enabled may also support Intel® Arc™ A-Series graphics. " is also listed below, which leaves a very ambiguous question of what will and wont work.

**Comment by Black6spdZ** [comment]
tried ReBarDxe?
