### ISSUE TITLE
CS2 : crash at random just before gameplay (map finished loading)

### ISSUE THREAD

**Issue by freak2fast4u** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#532]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Counter-Strike 2

### Processor / Processor Number [Required]

Ryzen 7 7800X3D

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

19045.3448

### Intel System Support Utility report

[igcit_ssu_20230922_cs2crashrandom_anon.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12701308/igcit_ssu_20230922_cs2crashrandom_anon.txt)

### Description and steps to reproduce [Required]

Start CS2, join a game (deathmatch for example), and just when the map finishes loading and you were about to start playing, the game hard crashes.
This happens at random, so restarting the procedure will allow gameplay, and once the map is loaded and playable, I don't witness any crashes later on, so it seems specific to some initialization procedure. The minidumps provided below will surely be useful here.

### Crash dumps [Required, if applicable]

[cs2_2023_0920_202712_0_accessviolation.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12701281/cs2_2023_0920_202712_0_accessviolation.zip)
[cs2_2023_0921_165731_0_accessviolation.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12701283/cs2_2023_0921_165731_0_accessviolation.zip)

**Comment by freak2fast4u** [comment]
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/6ea9e883-ce7f-42bd-bb3b-f177350259ee)

**Comment by freak2fast4u** [comment]
Well, a few weeks later I can report that this problem seems to have resolved itself, either via a CS2 update or via a driver update.
However I noticed CS2 now defaults and systematically reverts back to windowed rendering (not fullscreen, nor borderless windowed), no matter how I configure it in game. This could be a temporary fix on their side, or something completely unrelated (maybe the fullscreen alt-tab bug issue ...).

I'll leave this issue open a few more weeks if you don't mind. I'll fiddle with the settings a bit more and see if I can reproduce it again. If I can't, or if you have an internal commit log that mentions this specific issue is supposed to be fixed, I'll gladly close it. 

Cheers :)

**Comment by Gabriela-Intel** [comment]
Sounds good. Thanks for the update @freak2fast4u :)

**Comment by freak2fast4u** [comment]
Alright, it seems solved for me, and versions 4900 and 4952 are just as good in that department.
Case closed, thanks for the fix !

**Comment by Gabriela-Intel** [comment]
Woohoo! Glad to hear that it's fixed.
