### ISSUE TITLE
QQ - Intel Virtual Camera crashes the application

### ISSUE THREAD

**Issue by YUCLing** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#533]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Tencent QQ

### Processor / Processor Number [Required]

Intel Core i9-12900KS

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

- [ ] 31.0.101.4826
- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12706006/igcit_ssu.txt)

### Description and steps to reproduce [Required]

After login, open QQ settings from the main menu, and scroll down to "音视频通话". In my situation, Intel Virtual Camera is default video device. Wait a moment and the application crashed.

### Crash dumps [Required, if applicable]

[crash_data.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12706001/crash_data.zip)

### Application / Windows logs

See `crash_data.zip`.

**Comment by Ilya-intel** [comment]
Hi @YUCLing ,
We don't see the issue with the latest QQ app version.
Could you test it again?

**Comment by YUCLing** [comment]
This issue only exists in versions before the "QQNT" versions. If it's not being supported anymore then I can only ignore this then.
