### ISSUE TITLE
Arc A750 gpu clock drops after gpu bios upgrade from actual august driver

### ISSUE THREAD

**Issue by BartolomeusCro** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#535]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Call of Cthulhu 2018

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 4500

### Graphic Card [Required]

A750

### GPU Driver Version [Required]

- [X] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[09-23-23_a750_bios_20_0_1064_gpuclock_drop.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12706500/09-23-23_a750_bios_20_0_1064_gpuclock_drop.txt)

### Description and steps to reproduce [Required]

Game runs smoothly usually

![1_Screenshot 2023-09-23 193849](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/145841791/fa40df33-6885-48a6-92e4-c6ee3a86f148)

But after gpu's bios update from a new driver wild gpu clock drops appeared:
It's random, in every game, random places. Original gpu frequency is 2400mhz, it can randomly drop for 600 with garbage fps.
![2_Screenshot 2023-09-23 193919](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/145841791/be3e0aab-3c8f-4b64-8b01-1ba4440ac545)

Settings:
![3_Screenshot 2023-09-23 193940](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/145841791/4c9fa659-e9a8-402e-8deb-573f0791a40e)

![4_Screenshot 2023-09-23 195134](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/145841791/eabd7520-852c-4964-9e72-1105c4a6ba3a)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![3_Screenshot 2023-09-23 193940](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/145841791/18da6600-ae02-476d-ae79-54e4fc310b2a)

### Device / Platform name

PC

**Comment by Vivek-Intel** [comment]
@BartolomeusCro Gentle reminder to check with latest driver because there was a VBIOS update after the last used driver

**Comment by Vivek-Intel** [comment]
@IGCIT please help close this issue due to inactivity, user can reopen with updated observation.
