### ISSUE TITLE
Payday 3 Poor Performance

### ISSUE THREAD

**Issue by Code-Vlue** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#536]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Payday 3

### Game Platform [Required]

- [ ] Steam
- [x] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12706740/ssulog.txt)

### Description and steps to reproduce [Required]

Performance is fine in menu but when in game performance tanks and GPU utilization is low.
![Screenshot 2023-09-23 100713](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/142824040/41c823ff-dd34-4ee7-8c87-6bd2a1ed4990)
![Screenshot 2023-09-23 100125](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/142824040/913b36b7-5850-4490-9e46-04f370850347)
![Screenshot 2023-09-23 095644](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/142824040/738bebf0-526c-4df7-857b-3874df55b290)
![Screenshot 2023-09-23 095100](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/142824040/dd5208dd-9890-40e1-90a4-2a6a51bf91d6)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

All ultra settings, native upscaling and AA set to quality.

**Comment by Code-Vlue** [comment]
Tested at all settings levels with Vsync on and off at 1080P, results are the same, game behaves as if the frame rate is being capped in some way or the card is not being utilized fully, high utilization in the menu with Vsync off, in game framerate always drops down to the 30s-20s while card utilization and clocks are low.

**Comment by Code-Vlue** [comment]
Here is a video of the issue replicated.

https://youtu.be/1T4Bp_5cCdE

**Comment by Code-Vlue** [comment]
Also [Noobachyo](https://github.com/Noobachyo) replicated this in issue #537 https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/537

**Comment by Noobachyo** [comment]
> Here is a video of the issue replicated.
> 
> https://youtu.be/1T4Bp_5cCdE


The funny thing is that my a380 has more fps than you have in this video. The video card is also loaded at 60-70%, consumption is around 35-43 watts, with a maximum of 55.

**Comment by Noobachyo** [comment]
> Also [Noobachyo](https://github.com/Noobachyo) replicated this in issue #537

But sometimes the image freezes for a few seconds, but I didn’t see that in your video

**Comment by Code-Vlue** [comment]
@Noobachyo Yeah the usage on mine seems to be really low almost like something in the game or engine is the bottleneck and causing the GPU not to be utilized. But yeah I don't have the freezing issue which I think is due to VRAM utilization, in my issue the VRAM stays below my cards capacity which is 8GB but in the video I watched that you posted it looks like the VRAM utilization exceeds the 6GB of your card which is what's probably causing the freezing time to time.

**Comment by Noobachyo** [comment]
> @Noobachyo Yeah the usage on mine seems to be really low almost like something in the game or engine is the bottleneck and causing the GPU not to be utilized. But yeah I don't have the freezing issue which I think is due to VRAM utilization, in my issue the VRAM stays below my cards capacity which is 8GB but in the video I watched that you posted it looks like the VRAM utilization exceeds the 6GB of your card which is what's probably causing the freezing time to time.

In any case, the game runs great on a 1650 with 4 gigabytes of memory. So this is just another failure of arc cards, not the game and its engine. In 2 games out of 3 there are always some problems. I can't stand it anymore.

**Comment by Code-Vlue** [comment]
> > @Noobachyo Yeah the usage on mine seems to be really low almost like something in the game or engine is the bottleneck and causing the GPU not to be utilized. But yeah I don't have the freezing issue which I think is due to VRAM utilization, in my issue the VRAM stays below my cards capacity which is 8GB but in the video I watched that you posted it looks like the VRAM utilization exceeds the 6GB of your card which is what's probably causing the freezing time to time.
> 
> In any case, the game runs great on a 1650 with 4 gigabytes of memory. So this is just another failure of arc cards, not the game and its engine. In 2 games out of 3 there are always some problems. I can't stand it anymore.

That's understandable, Arc cards are still in their early days and very much an early adopters piece of tech right now since we are just now hitting a year since release, so for me I was fine with it and knew these issues may come up but for most people its probably a bit too much. I'd expect for them to be a lot better here in the next year or two especially since Intel's upcoming Meteor Lake CPUs will have Arc integrated graphics.

**Comment by J0dla** [comment]
@Noobachyo i can confirm on a380 it works ok for me mos of the time it utilizes about 96-99%(medium/high combo). Payday devs mentioned that server problems can cause game stutters etc so not everything is "driver" related. I too experienced one or 2 times stutter mess for a while but mostly some time after that, servers went to dust. I also read,heard that people had problems when their ping was over 100. The more concerning for me were some rare crashes to desktop, but i cant say who is at fault servers, game or driver.

**Comment by Code-Vlue** [comment]
Issue persists with driver 4885

**Comment by Gabriela-Intel** [comment]
Hi all! Sorry for it taking so long for someone to pick up the issue, we're doing our best to work through all of these github issues!

Has anyone had the chance to check out the performance lately when using our latest drivers in the [Download Center](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html?)?

**Comment by Gabriela-Intel** [comment]
Hey @Code-Vlue Have you had the chance to check the performance?

**Comment by Gabriela-Intel** [comment]
@IGCIT Proceed with closing, thanks!
