### ISSUE TITLE
Hometopia poor perfomance 

### ISSUE THREAD

**Issue by ghost** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#539]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Hometopia

### Processor / Processor Number [Required]

i9 13900K

### Graphic Card [Required]

Arc A770

### GPU Driver Version [Required]

- [X] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

N/A

### Description and steps to reproduce [Required]

Playing the game across all settings presets seems to be below 30fps and stuttering.

**Comment by 3EyedBlinky** [comment]
![Screenshot 2023-09-27 180421](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/126843979/781d5287-c265-41a7-8929-4b17389b41a3)

Game is early access granted but I do not believe this perfomance makes sense....although according to the gpu_busy metric, the game is rendering as fast as the frames are being generated.

**Comment by Vivek-Intel** [comment]
There have been some improvement made by game developer towards optimization with Intel Arc.
User need to verify this issue with latest driver and game version:

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/114637913/a5a92ca6-e487-4483-be62-adaa6004b037)

**Comment by Vivek-Intel** [comment]
@IGCIT please help mark close as no response , user can reopen if there is still issue.
