### ISSUE TITLE
[Crash, FIXED] Resident Evil 7 Windows Store Version 

### ISSUE THREAD

**Issue by kurikomoe** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#54]
#### Checklist [README]

- [X] Device is not undervolted nor overclocked.
- [X] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [X] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Resident Evil 7
Windows Store:  https://www.microsoft.com/en-us/p/resident-evil-7-biohazard/bvfdtj1xf6cs

---
#### Processor / Processor Number [Required]
1165g7

---
#### GPU Driver Version [Required]
- [X] 27.20.100.9616 (beta) 
- [X] 27.20.100.9466 (*latest*)
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [x] Windows 10 21H1 (*May 2021 Update*)
- [X] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1. just open the game, wait till capcom logo appears, then it crashes.
2. if you quick click the mouse to skip logos, the game will crash when the `RE Engine` logo appears.

---
#### Device / Platform [Optional][Recommended]

OneXPlayer 1165g7, public sold version.

---
#### Game Settings [Optional][Recommended]

None, cannot get into the game

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---
#### Game custom logs (*if available*) [Optional][Recommended]

![crash log](https://user-images.githubusercontent.com/31176859/119452849-66de6a00-bd69-11eb-9482-96ed2d3fbb07.png)
```text
Faulting application name: re7.exe, version: 0.0.0.0, time stamp: 0x5a031e35
Faulting module name: re7.exe, version: 0.0.0.0, time stamp: 0x5a031e35
Exception code: 0xc0000005
Fault offset: 0x0000000002365102
Faulting process id: 0x9a0
Faulting application start time: 0x01d75130570ffd02
Faulting application path: C:\Program Files\WindowsApps\F024294D.RESIDENTEVIL7biohazard_10.2.1.2_x64__8fty0by30jkny\re7.exe
Faulting module path: C:\Program Files\WindowsApps\F024294D.RESIDENTEVIL7biohazard_10.2.1.2_x64__8fty0by30jkny\re7.exe
Report Id: b4edcf07-25f4-40fc-81d4-d4273b1ceb84
Faulting package full name: F024294D.RESIDENTEVIL7biohazard_10.2.1.2_x64__8fty0by30jkny
Faulting package-relative application ID: runtime
```

**Comment by kurikomoe** [comment]
a fully reinstall windows 21H1 and RE7 windows store version, 27.20.100.9616 beta driver, still crashes on startup

```text
Faulting application name: re7.exe, version: 0.0.0.0, time stamp: 0x5a031e35
Faulting module name: re7.exe, version: 0.0.0.0, time stamp: 0x5a031e35
Exception code: 0xc0000005
Error offset: 0x0000000002365102
Error process ID: 0xfd8
Error application start time: 0x01d752c0ead82f98
Error application path: C:\Program Files\WindowsApps\F024294D.RESIDENTEVIL7biohazard_10.2.1.2_x64__8fty0by30jkny\re7.exe
Error module path: C:\Program Files\WindowsApps\F024294D.RESIDENTEVIL7biohazard_10.2.1.2_x64__8fty0by30jkny\re7.exe
Report ID: e24886ec-5b87-461a-adcc-2edb139c3120
Faulting package full name: F024294D.RESIDENTEVIL7biohazard_10.2.1.2_x64__8fty0by30jkny
Faulting package-relative application ID: runtime
```

**Comment by Valkirie** [comment]
@leoben2 This one is still not fixed as opposed to [this post](https://community.intel.com/t5/Graphics/Resident-Evil-7-crashes-at-startup-intel-Iris-Plus-G4/td-p/647803/page/2) from intel community forum.

**Comment by kurikomoe** [comment]
some said that Re7launcher.exe may work, but sadly for the windows store version (Xbox game pass for pc), there is no way to use re7launcher to bypass the crash.

re7launcher.exe: [https://www.reddit.com/r/gpdwin/comments/j0mlmo/experience_share_about_re7_on_win_max/](https://www.reddit.com/r/gpdwin/comments/j0mlmo/experience_share_about_re7_on_win_max/)

buy another copy of re7 on steam may be a solution, but too costly...  LOL

**Comment by PacoAvelar** [comment]
Issue persist on driver 30.0.100.9955

**Comment by craiggx** [comment]
Hey Kuikomoroe,

We're looking into this issue and we're wondering what game version you were running when you encountered the crash. The Microsoft Store version would also be helpful. Thanks!

**Comment by kurikomoe** [comment]
> Hey Kuikomoroe,
> 
> We're looking into this issue and we're wondering what game version you were running when you encountered the crash. The Microsoft Store version would also be helpful. Thanks!

sure, give me some time to re-download the game from Microsoft

**Comment by kurikomoe** [comment]
It seems that the latest resident evil 7 from the Microsoft store is running perfectly!

I think it's ok to close this issue.
