### ISSUE TITLE
Video Co Pilot Element 3D within Adobe After Effects no functioning

### ISSUE THREAD

**Issue by Warlock-Merlin** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#540]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

After Effects CC 2023 - Element 3D Plugin

### Processor / Processor Number [Required]

Intel i7-1260P

### Graphic Card [Required]

Intel ARC A370M

### GPU Driver Version [Required]

- [X] 31.0.101.4826
- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

22621.2283

### Intel System Support Utility report

[Laptop Spectre.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12745460/Laptop.Spectre.txt)

### Description and steps to reproduce [Required]

When using Video Co Pilot Element 3D the Application plugin framework with After Effects for rendering 3D environments and even just rendering a 3D Text scene just doesn't work at all and only render pure black text. This is on 2.2.3 Element 3D revision. Video Co Pilot uses Nvidia or AMD to render 3d with in Adobe After Effects.

https://www.videocopilot.net/assets/public/misc/Element-GPUs.pdf

I try to set an environment for global Illumination and it doesn't change anything. It would be nice if Intel ARC actually worked with having a legitimate use instead of rendering a $2,500 laptop useless. Whats the point of ARC if you can't even use it for 3D Graphics or anything with in After Effects.

### Device / Platform

HP Spectre 16 X360 2-in-1 Laptop

**Comment by Ilya-intel** [comment]
Hi @Warlock-Merlin  ,
This request for support of additional GPUs should be passed to the software developer of the plugin as it is not an Intel driver issue.
Please reach out to the Video Copilot support.

**Comment by Ilya-intel** [comment]
@IGCIT 
Kindly close this thread since this issue should be passed to Software Developer.
