### ISSUE TITLE
DX9 issue after 4824 with Project Reality (battlefield 2 mod) 

### ISSUE THREAD

**Issue by ksof1** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#543]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Project Reality BF2

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [X] Other (please specify)

### Other game platform

non-launcher bound game

### Processor / Processor Number [Required]

Intel Core i9-12900K

### Graphic Card [Required]

Inter Arc A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4826
- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[prbf2.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12751927/prbf2.txt)

### Description and steps to reproduce [Required]

The game seems to randomly hang and crash during either most intense sequences (when lots of players present on screen at the beginning of the round) or during regular gameplay on the biggest maps in game. 

Now the problem wasn't present before this DX9 driver update was pushed. The game performs way better with new driver (x2 perf boost) but these crashes are making the game unplayable. Using DXVK prevents the game from crashing, but you can not alt-tab out of it (interface disappears). 

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

3440x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

All maximum

### Device / Platform name

PC

### Crash dumps [Required, if applicable]

![Screenshot 2023-09-28 200142](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/144232261/4674101c-6d2c-4d09-85b7-629eba647f06)

**Comment by Ilya-intel** [comment]
Hi @ksof1 ,
For unofficial modifications, issues should be reported by mod developers including homebrew code for isolation.
So kindly reach out to mod developers' support.

**Comment by Ilya-intel** [comment]
@IGCIT 
Kindly close this thread. Issue should be reported to mod developer.
