### ISSUE TITLE
Artificial Intelligence training for Intel Arc Drivers

### ISSUE THREAD

**Issue by sassosa103** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#544]
### Application [Required]

Artificial Intelligence training for Intel Arc Drivers

### Processor / Processor Number [Required]

NA

### Graphic Card [Required]

Intel Arc GPUs

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [X] Other (Please specify)

### Describe the feature [Required]

Dear,

Day by day, as the time is passing, Intel Arc GPUs are developing more and more errors. We are living in 2023 and not 2008. I would like to suggest the team of coders working on Intel Arc GPU drivers to approach the Executives and request them to deploy AI training and learning hardware infrastructure for Intel GPU drivers. Let the AI train and develop the drivers. This is how Nvidia is creating its drivers. This is the only solution.

I hope that this post of mine will be forwarded to the team. 

Thanks.

**Comment by Gabriela-Intel** [comment]
Thanks for sharing your feedback here with us @sassosa103! We'll take it into consideration and pass it along to the appropriate team. :)

@IGCIT Please close
