### ISSUE TITLE
Forspoken v1.22 AMD FSR3 Frame Generation crash on Arc A770

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#545]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Forspoken

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

intel Core i5-13500

### Graphic Card [Required]

intel Arc A770 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU_20230930.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12774017/SSU_20230930.txt)

### Description and steps to reproduce [Required]

When trying to turn on Frame Generation, the game either crashes to Windows desktop with error message: DXGI_ERROR_DEVICE_HUNG or causes BSOD with stop code: VIDEO_SCHEDULER_INTERNAL_ERROR.

[demo video](https://youtu.be/9QHo_DlLvpg?si=GBr0UfRYVuPXdvHm)

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Irrelevant

**Comment by yawnbunny** [comment]
Have you tried a clean driver install with DDU? Others on Reddit have shown it working fine, and a bad driver install is a common problem on Arc.

**Comment by Susie1818** [comment]
Done that. No use. So many unprofessional people are just misunderstanding the purpose of DDU. If the driver is not correctly installed and does require DDU to clean it up, that would be a scenario where the GPU behaves problematically in a wide spectrum, not just on one single feature in one single application and no problem at all with anything else.

**Comment by yawnbunny** [comment]
I had one specific game just black screen shortly after booting while others worked fine and it was related to bad driver install. I figured it was related to bad OC settings since I was tuning things around the same time, but after I removed that variable it still kept happening, and a clean driver install fixed it. It can, sometimes, absolutely be something specific while other applications are unaffected.

**Comment by Arturo-Intel** [comment]
@Susie1818 
I saw in the comments of the shared video that some other users also have the same issue as you.
Do you have the link/source (if apply) where the users are saying this? 
I want to collect info, maybe there is a pattern hidden there

Also Did you try with 4885? 

--r2

**Comment by Susie1818** [comment]
@Arturo-Intel 
> You can try the follow:
> 
> 1. Run [DDU in safe mode](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html)
> 2. Clean install the drivers (use [101.4885](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html))
> 3. [Use the System File Checker tool to repair missing or corrupted system files](https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e)
> 

1. I have done that.
2. I did. Both 4826 and 4885 have the same issue.
3. Have tried the SFC tool, and the same problem persists.

*There is an official patch note saying this is a known issue being investigated by the game devs. Hopefully intel engineers can contact them directly so that both ends collaborate and fix the problem as soon as possible.

![Screenshot](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/124469949/deae0044-ccc3-41fd-8e9b-56246b110163)

**Comment by Susie1818** [comment]
This issue has been resolved with today's Forspoken patch 1.23, but it requires driver version 4952 otherwise it doesn't work.
