### ISSUE TITLE
DirectX unrecoverable error

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#546]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

GTA V / FiveM

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 01.10.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12777333/Intel.SSU.01.10.2023.txt)

### Description and steps to reproduce [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/2df4a3c1-26ea-4f6e-9af4-9fc5b4ffaf1d)
A very recurrent crash I'm encountering in GTA V with FiveM. I doubt this is FiveM's fault, as it says that DirectX encountered the error DXG8_ERROR_DEVICE_REMOVED, that would indicate that the GPU made DirectX think that it got removed

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Max

### Device / Platform name

ASUS PRIME Z790-P WiFi D4

### Crash dumps [Required, if applicable]

https://drive.google.com/file/d/1N9ebwSmThaTQSKScsnOefqFOIT88bNye/view?usp=sharing

**Comment by Arturo-Intel** [comment]
@TheWonderfulTartiflette 
It occurs without the FiveM mods?

**Comment by Arturo-Intel** [comment]
Several users are complaining with the same behavior as yours with diff GPUs, so it seems to be on FIveM side
https://forum.cfx.re/search?q=dxgi_error_device_removed%20order%3Alatest_topic

This is interesting "fix"
>I have a i5 10400f CPU running 3200 MHZ RAM and 3060 12GB, The max ram speed for my CPU is 2666MHZ so i went into BIOS and changed clock speed from 3200 to 2666 and havent had a problem since.


--r2

**Comment by TheWonderfulTartiflette** [comment]
@Arturo-Intel I'm not sure I have any mods installed actually, I only use FiveM for servers

**Comment by Arturo-Intel** [comment]
Can you see this behavior offline?

**Comment by TheWonderfulTartiflette** [comment]
@Arturo-Intel yep I'll try this as soon as possible

**Comment by TheWonderfulTartiflette** [comment]
@TheWonderfulTartiflette Sadly I realized that this issue is really random, there's no specific place or time where this occurs. Sometimes I can play for 50 hours straight without having the error, and sometimes it's less than 10 seconds after I load the game, so I don't think I'd be able to test offline sorry

**Comment by Arturo-Intel** [comment]
Closing this issue
Everything points to be something related to the FiveM servers/mods
