### ISSUE TITLE
ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY BSOD in Stable Diffusion

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#548]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows, Stable Diffusion

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 01.10.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12777849/Intel.SSU.01.10.2023.txt)

### Description and steps to reproduce [Required]

Encountered this bluescreen when I was trying to use Stable Diffusion with the AUTOMATIC1111 WebUI. I was using the Infinite Zoom extension with the CPU (arc doesn't support it). I left everything at default

### Crash dumps [Required, if applicable]

DMP file : https://drive.google.com/file/d/1N9oYpMc6GqP7JpDYOV0YhEYtdRXkKzLQ/view?usp=sharing

**Comment by Arturo-Intel** [comment]
@TheWonderfulTartiflette 
Unfortunately AUTOMATIC1111 WebUI [requires a discrete GPU](https://stable-diffusion-art.com/install-windows/#:~:text=Your%20PC%20should%20run%20Windows%2010%20or%20higher%20with%20a%20discrete%20Nvidia%20video%20card%20(GPU)%20with%204%20GB%20VRAM%20or%20more.%20An%20integrated%20GPU%20will%20not%20work.
) and Intel dGPU are not supported by the software 

>Your PC should run Windows 10 or higher with a discrete Nvidia video card (GPU) with 4 GB VRAM or more. An integrated GPU will not work.


@IGCIT please close this case

**Comment by TheWonderfulTartiflette** [comment]
@Arturo-Intel no no no, A1111 has an OpenVINO implementation, which makes it able to use Arc GPUs. [Look at this, made by Intel itself](https://game.intel.com/story/intel-arc-graphics-generative-ai-art/)

**Comment by Arturo-Intel** [comment]
Ok, let me check it.

**Comment by Arturo-Intel** [comment]
https://github.com/v8hid/infinite-zoom-automatic1111-webui
This is the infinity zoom plugin you were using?

**Comment by TheWonderfulTartiflette** [comment]
@Arturo-Intel yep

**Comment by Arturo-Intel** [comment]
Do you have a specific settings to reproduce the BSOD?

**Comment by TheWonderfulTartiflette** [comment]
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/dfc87816-dffd-46a9-b291-404afb9d069a)
I've used the defaults settings, but I don't remember my prompt (shouldn't matter)

**Comment by Arturo-Intel** [comment]
I was able to create a video

<img width="1468" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/1870a886-24bf-488d-affb-0232567b2d57">

no BSOD, that is why asked.

BTW, I only have the ARC in my system (no igpu) and the software worked well :o

**Comment by TheWonderfulTartiflette** [comment]
Well seems like when I tried it again, I've bluescreened again but with another error, PAGE_FAULT_IN_NON_PAGED_AREA
Here are what the Diagnostic Data Viewer can tell me : https://drive.google.com/drive/folders/1NA0-n19w08WyXF-Oxn0B3y1hK0TolPXL?usp=sharing
I was still doing Infinite Zoom with the default settings. I had the cmd window focused on

**Comment by TheWonderfulTartiflette** [comment]
Btw would be nice to reopen this to be sure that the issue is still not resolved maybe

**Comment by Arturo-Intel** [comment]
@TheWonderfulTartiflette did you see this behavior using the last driver?
