### ISSUE TITLE
Just wondering whether you guys are aware of the driver/architectural overhead issue and CPU dependency problem with the Arc Alchemist

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#549]
### Application [Required]

N/A

### Processor / Processor Number [Required]

N/A

### Graphic Card [Required]

intel Arc A770/A750

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [X] Windows 11 21H1
- [X] Windows 10 22H2
- [X] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Just wondering if you guys are aware of the driver/architectural overhead issue and CPU dependency problem with the Arc Alchemist and if you guys are trying mitigating the problem with the driver updates. Could an engineer here kindly give a definite answer on this topic?

Actually I have seen quite promising progress with the improvement of the Vulkan performance per driver updates, and I have verified that the Vulkan operations on Arc do show relatively very little CPU dependency compared with DX11 and DX12 operations on Arc. So I guess you guys are definitely aware of the problem and are also putting efforts into solving it. Hopefully my guess is right.

### Additional notes

[Reference video](https://youtu.be/T62dRJ35buI)

**Comment by Code-Vlue** [comment]
I have a Ryzen 5 3600 with my A750 and at least from what I've seen, playing games with DXVK usually improves performance quite a bit and DX11/12 have lower performance than expected compared to Vulkan games.

**Comment by Gabriela-Intel** [comment]
Hi! As explained [here](https://www.youtube.com/watch?v=tZHHhTt_fww&t=215s), driver improvements have and continue to be developed to address this. 

There's a couple of DX11 examples of improvements in the video. And just like with DX11, the Vulkan component of the driver is constantly being optimized in many ways; one being reducing the CPU overhead.

**Comment by Gabriela-Intel** [comment]
@IGCIT We can close this issue.
