### ISSUE TITLE
Cyberpunk has major graphics glithes in the new beta 

### ISSUE THREAD

**Issue by nielo360** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#55]
#### Checklist [README]

- [x] Device is not undervolted nor overclocked.
- [x] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [x] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]

---
#### Processor / Processor Number [Required]
i7-1165G7

#### GPU Driver Version [Required]
- [x] 27.20.100.9616

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [x] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [x] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1.  Glitches with lights everywhere at a distance, very bright. Glitches on buildings outside
2. 
3. 

---
#### Device / Platform [Optional][Recommended]
GPD WIN 3

---
#### Game Settings [Optional][Recommended]

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---

**Comment by mva94** [comment]
Indeed there there a lot of artifacts happening which makes the game unplayable. 
I can though notice some improvements in term of framerate when it is playable..
![20210528_145955](https://user-images.githubusercontent.com/78859716/119987706-9c7f8f00-bfc5-11eb-8d1e-3b0f9acd3daf.jpg)

**Comment by mva94** [comment]
@Valkirie you should close it as it's not an issue anymore

**Comment by Valkirie** [comment]
![image](https://user-images.githubusercontent.com/934757/121551403-e7f75b80-ca0f-11eb-9696-3d477dc50707.png)
