### ISSUE TITLE
Discord App crashes when trying to watch a stream from Nvidia RTX 4000 series.

### ISSUE THREAD

**Issue by Vipitis** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#550]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Discord

### Processor / Processor Number [Required]

i5 6600K

### Graphic Card [Required]

A750 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [X] 31.0.101.4672
- [X] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [X] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

(to follow)

### Description and steps to reproduce [Required]

Open Discord. 
un settings -> voice & video -> video codec check all three options (OpenH264, Hardware Acceleration, AV1).

join a voice chat.

have a voice chat participant stream gameplay with an RTX4000 series device (unsure about their settings).
Click "Watch Stream".

App crashes.

other streams work just fine. Unknown if stages cause the same issue. Has been like this for 6+ months. Did not see any relevant issue filed here

**Comment by Ilya-intel** [comment]
Hi @Vipitis,
I've just tried to watch the stream from RTX 4070 Ti, and everything seems to be OK.
Could you share some crash dump files/logs/event viewer logs?

**Comment by jcurrenc** [comment]
I've had similar issues w/ discord crashing while watching streams. It is definitely driver related, not so sure about it being localized to 4000 series GPUs.  It depends on if the discord streamer is steaming the game window vs their whole screen. Discord is probably encoding the video/audio or something in a way that causes a crash.

One fix for me has been removing "Sonic Studio Virtual Mixer" in device manager, then I can open streams but can't stream myself. 

Will try to get some logging of the issues I have been having but Intel could def take a look at discord streaming on Arc gpus.

**Comment by Vipitis** [comment]
I have zero issues streaming myself. It's always an application crash when look at a game stream from RTX 40-series. Have had this with at least 3 different people. Will try to find the time and collect their discord settings as well as look for any event viewer logs. 

It's been like this for a long while, but difficult to test as it requires an external system which I don't currently have.

**Comment by Vipitis** [comment]
I inquired with the known individual. They are using a RTX 4080 and we tried enabling and disabling all the video options in the discord app. It seems like I  get audio from the stream for a few settings.
The only kind of logfile I found is this here 
[000103.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12860932/000103.log) although it doesn't seem human readable. (from `%appdata%\discord\Session Storage`)

**Comment by Ilya-intel** [comment]
@Vipitis 
Am I correct assuming that when the Discord app crashes - there are no error messages or even mentions in the Windows Event Viewer?

**Comment by Ilya-intel** [comment]
@Vipitis 
Have you got a chance to check for some windows logs?

**Comment by Vipitis** [comment]
haven't found the time to go deeper on this. Feel free to mark as stale for now

**Comment by Ilya-intel** [comment]
@IGCIT 
Please close the thread for now.
