### ISSUE TITLE
IGCIT Helper Should Redact Net Connection ID

### ISSUE THREAD

**Issue by aolszowka** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#552]
### Application [Required]

IGCIT Helper

### Processor / Processor Number [Required]

i7-3770k

### Graphic Card [Required]

Intel Arc A380

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [X] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

As part of the IGCIT Helper Tool's redaction/Anonymize function you should consider redacting the `Net Connection ID` property, this may leak information about the network, especially in a Hyper-V setup where the name corresponds to the Virtual Switch Name.

**Comment by IGCIT** [comment]
Hi @aolszowka,

thanks, the helper will be updated to add this to the list :)
