### ISSUE TITLE
Windows Colour profile fails to apply on restart

### ISSUE THREAD

**Issue by ksof1** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#554]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows

### Processor / Processor Number [Required]

Intel Core i9-12900K

### Graphic Card [Required]

Inter Arc A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4885
- [X] 31.0.101.4826
- [X] 31.0.101.4824
- [X] 31.0.101.4676
- [X] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[colour.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12820546/colour.txt)

### Description and steps to reproduce [Required]

![Screenshot 2023-10-05 205636](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/144232261/c1abfef2-6b4d-4819-ad65-70795a3e05b0)
I'm using sRGB profile on monitor and then apply 2.4 gamma via Windows Colour Calibration tool. It works until reboot when it stops applying the settings. Going into HDR and back fixes it. Games don't seem to adhere to Windows Gamma settings very well either. 

### Device / Platform

Windows 11 22h2 Monitor AOC U34G3XM/EU, connected via DP 1.4 cable.

**Comment by Karen-Intel** [comment]
Hey @ksof1 could you please add your monitor specs and the info under Advanced Display information? 
Include also if you're using DP or HDMI and if you're using a converter

Ty

Karen

**Comment by ksof1** [comment]
Monitor AOC U34G3XM/EU, connected via DP 1.4 cable. 

> Also, when you say "It works until reboot when it stops applying the settings" Do you mean that the color profile is not available anymore until you enable and disable HDR

I set monitor gamma in monitor OSD to be sRGB 2.2.
I set Windows Colour Profile to be 2.4 gamma, which should override monitor settings.
It works as intended
I turn the PC off, turn it on the next day or just reboot it - I notice gamma is back to being 2.2, as set by monitor. Windows Colour Settings are ignored.
I go into Display Options in Windows and it says that the profile with 2.4 gamma is applied, while it isn't/
I turn HDR on in windows, turn it off - gamma becomes 2.4, as it was set in windows colour profile. 
Restarting display driver fixes the issue as well.
Reinstalling display driver fixes the issue as well.

Until next reboot.  The issues isn't 100% consistent, but I would say 8/10 times I turn my PC on the Windows gamma isn't applied

**Comment by Karen-Intel** [comment]
Ty for the info @ksof1. Allow me to perform some tests in the lab and provide updates soon :)

Karen

**Comment by Karen-Intel** [comment]
Hey @ksof1 quick update on this. I have not been able to consistently repro the exact same issue.
[In my case,](https://www.youtube.com/watch?v=62Uiavdrwmc) the profile I have after calibrating my display stays there after I reboot the machine. 
I have even shut it down ~2 or 3 times in a series of 10 tests = 10 continuous reboots and shutdowns in between. 
You can even see the darker image as the contrast profile I set up is darker. 
My display is a G8 OLED Samsung display
**I really need a video of the issue on your end** + we need to test in a similar display to yours afterwards.
Ty

Karen

**Comment by ksof1** [comment]
I don't really know what else to add. Colour profile worked fine for the past week, turned the PC on this morning and notice lower contrast again. Made the video but I don't know what else to add. This issue persisted before I reinstalled Windows a few months ago - so it's not "something borked in OC". 

https://drive.google.com/file/d/1TqlSAvw1e5z7KCV2Io6xSTac6Ygqyvqx/view?usp=sharing

**Comment by Karen-Intel** [comment]
Hey @ksof1 after doing some more testing in 2 machines (1 with ARC, another with NVIDIA 3050) I saw the same behavior after many reboots on both systems.
It looks like it is an issue from Microsoft, as I failed to have my color profile in both systems > meaning, I had to recalibrate it again, even tho the profile was there I couldn't select it. 
I'm attaching [my last test here](https://www.youtube.com/watch?v=g7oPinLPIXk) after I recalibrated the NVIDIA system and disabled and enabled HDR. Now after you disable HDR it is expected to have the color profile unavailable. 
A [MS forum thread ](https://answers.microsoft.com/en-us/windows/forum/all/monitor-color-profile-does-not-display-in-display/bef42940-6757-4e79-9890-dd3cc1b485d3)about this issue, seems that other users have already reported it.

@IGCIT Can you help us close this one? Same behavior is happening after many reboots on NVIDIA an Intel GPUs so it is not exclusive to ARC > Color management profile is not available for some reason and display calibration should be done once again. Looks like MS fails to find it, color calibration profile is there tho.

Karen
