### ISSUE TITLE
Settlers 4 artifacts and crash

### ISSUE THREAD

**Issue by hbvdh** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#556]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

The Settlers 4

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [X] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

I7-9800X

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4885
- [X] 31.0.101.4826
- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

Since driver 31.0.101.4824 i get artifacts and crashes in The Settlers 4, version 31.0.101.4672 is ok.
[SSU_2023-10-08.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12841772/SSU_2023-10-08.txt)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/147347844/27675059-2c27-4c02-bb80-7c41e48cc6cd)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/147347844/f7159fad-baa4-4bb2-bfd5-e6d9729d55e0)

### Description and steps to reproduce [Required]

Since driver 31.0.101.4824 i get artifacts and crashes in The Settlers 4, version 31.0.101.4672 is ok.
[SSU_2023-10-08.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12841772/SSU_2023-10-08.txt)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/147347844/27675059-2c27-4c02-bb80-7c41e48cc6cd)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/147347844/f7159fad-baa4-4bb2-bfd5-e6d9729d55e0)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920*1200

### Game VSync [Required]

Off

### Game display mode [Required]

- [x] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

No game settings

**Comment by Arturo-Intel** [comment]
@hbvdh 
Did you try with the 4887 version driver?

**Comment by hbvdh** [comment]
@Arturo-Intel, thanks for the following up, yes I tried 4887 as well, it's the same.

**Comment by hbvdh** [comment]
Any updates?

**Comment by hbvdh** [comment]
Used dgVoodoo2 to "update" dx9 files, now game works properly
