### ISSUE TITLE
Have clearer/more concise categories of GPU usage in Task Manager and HWiNFO (any applications showing specific GPU usage)

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#557]
### Application [Required]

Any application showing specific GPU usage

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Right now, in HWiNFO, we have “D3D “, “Video Decode 0”, “Video Decode 1”, “Video Processing 0”, “Video Processing 1”, “Computing 0”, “Copy Engine”
In Task Manager, it's the same but even worse.
I know that Task Manager and HWiNFO are third-party apps, not developed by Intel, but the names shown next to the values they're receiving are coming from the card itself
Like, with Intel, how am I supposed to know the differences between “Video Decode 0”, “Video Decode 1”, “Video Processing 0” and “Video Processing 1”? What is supposed to be Computing 0? Copy Engine?

For comparison, at NVIDIA, we have “Core”, “Memory Controller”, “Video Engine”, “Bus”, “Memory Usage”, all of which are tons clearer than what we have currently with Intel
And indeed, with NVIDIA, even without searching for anything on the Internet, I know that “Video Engine” is, well, the video engine. Same for the memory controller

I don't know if this is an architectural issue that could be related to how the chip and sensors are made and thus would be impossible to fix with drivers (if that's the case, would be very nice to fix this with Battlemage/Celestial), but if this isn't, it would be really nice to such clear descriptions like NVIDIA's with a new driver update for Arc

Edit : And more than that, have additional categories that Intel doesn't have while NVIDIA does (Memory Controller load, Bus Load)

### Additional notes

NVIDIA : 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/0244ecaf-efad-4ccc-9b50-f94a8a27f498)

Intel : 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/8e2df2cc-524f-453a-822e-9d6acda963a1)

**Comment by nyanmisaka** [comment]
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/f15c35c8-7b59-47de-b0f5-e41756c983eb)

https://www.intel.com/content/www/us/en/products/sku/229151/intel-arc-a770-graphics-16gb/specifications.html

This simply means that your graphics card has multiple video codecs and video processing engines. You can find something similar on AMD's latest RDNA cards. It doesn't seem intuitive to me to combine them when developing applications.

https://intel.github.io/drivers.gpu.control-library/Control/api.html

As for other miscellaneous things, Arc also has corresponding APIs, but whether to implement them depends on the authors of these proprietary closed-source software.

**Comment by TheWonderfulTartiflette** [comment]
I understand that there's not a single engine on the Arc cards, that there has to be an engine each for H264, H265, VP9 and AV1. But I think that what NVIDIA is doing here is to simply take the highest load value between all of these, which makes it far easier for the consumer to know what's happening with their GPU. Developers could still be able to know the precise values with APIs

Plus, when thinking about it, there's still something off : Even if Intel wants to let the user know precisely what's going on, why do 2 “engines” are being used while watching AV1? It seems like there's an engine that is rendering the video, and another one that is decoding the received frames because when I skip through a video, an engine gets maxed out while the other sits at 0%

And moreover, the names “Video Processing 0” and “Video Processing 1”, same for Video Decodes, are not useful at all for anyone that wants to know what's going on with the GPU, they don't convey any difference at all (given what I've said before about two engines being used at the same time while watching AV1)

**Comment by TheWonderfulTartiflette** [comment]
And by the way, it doesn't really make sense that when encoding a video, it uses the "Video Decode" part

**Comment by nyanmisaka** [comment]
In fact MFX engines are multifunctional, they can be configured to do decode or encode. Therefore, it is inaccurate to hardcode it Decode or Encode in taskmgr. Regardless, these are cosmetic issues. I'd rather they prioritize fixing issues with games and productivity apps.

**Comment by TheWonderfulTartiflette** [comment]
I mean, if it's a cosmetic issue, that wouldn't be really hard to fix I think
But is it really cosmetic? Because it shows 4 different categories, when in reality there are only two engines, you see what I mean?

**Comment by nyanmisaka** [comment]
Xe-LP
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/e4ae980f-89e4-4bfb-865d-3a291fc8b48a)

Xe-HPG
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/2b4ed2c1-e1d7-4968-82f5-805efe761732)

It does have four separate video hardware blocks on Xe-HPG. Video process engines are not part of the MFX codecs.
video codec 0
video codec 1
video process/enhance 0
video process/enhance 1

On Linux it shows the same things.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/943c76f5-3175-47a0-8ece-0d0dba57f3ac)

**Comment by TheWonderfulTartiflette** [comment]
I see then, thanks
But why are they named like that though? Video Decode can spike when encoding (with software decoding), and Video Processing doesn't really mean anything

**Comment by nyanmisaka** [comment]
Video process means these operations:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/4e4d5f06-17eb-41fd-ac0e-b7ed30cd86a9)
https://github.com/intel/media-driver#video-processing-features

Video process engines do not automatically engage into your transcoding pipeline. You need to use them manually. For example, the `scale_qsv` and `vpp_qsv` filters in FFmpeg, and the D3D11 video processor calls in Chrome will trigger video process engines.

**Comment by Gabriela-Intel** [comment]
Thanks so much for your detailed feedback @TheWonderfulTartiflette :)

I've submitted your request on the improvement to the team and will be tracking this internally moving forward.

@IGCIT Please close.
