### ISSUE TITLE
Witcher 3 texture flickering when Ray tracing is turned on 

### ISSUE THREAD

**Issue by HairlessApe** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#558]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

The WItcher 3 Next Gen v4.04

### Processor / Processor Number [Required]

i7 4790k

### Graphic Card [Required]

A750

### GPU Driver Version [Required]

- [X] 31.0.101.4887
- [ ] 31.0.101.4885
- [ ] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12877637/igcit_ssu.txt)

### Description and steps to reproduce [Required]

When ray tracing is turned on in the game, textures flicker constantly. 

(https://www.youtube.com/watch?v=4b_bsLXCeaM)

**Comment by Arturo-Intel** [comment]
@HairlessApe 
Thank for the report, we will reproduce this in the lab and get prepare the case.
Can you share the graphical details? (resolution, quality, etc)

-- r2

**Comment by HairlessApe** [comment]
Hi Arturo, the resolution I play at is 2560 x 1440. Ultra+ settings, doesn't matter if raytracing gi is on performance or quality mode, as long as it's turned on the textures flicker. Thanks!

**Comment by Arturo-Intel** [comment]
I dont know if it is possible, but would be nice if you can share your saved game

**Comment by HairlessApe** [comment]
Here it is: (https://easyupload.io/pub3ax)

**Comment by Arturo-Intel** [comment]
@HairlessApe Can you try with .5079? 
I was unable to reproduce the glitch on the shadows

**Comment by HairlessApe** [comment]
@Arturo-Intel 
Ok I have tried the latest driver and it seems to have fixed the problem. Hooray! Thank you for your time and assistance!
