### ISSUE TITLE
Blender's Eevee-Next produces broken images

### ISSUE THREAD

**Issue by a-One-Fan** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#559]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Blender 4.1 a3831fe7af80

### Processor / Processor Number [Required]

Ryzen 7 3700x

### Graphic Card [Required]

Arc A770 LE 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4887 (WHQL)
- [X] 31.0.101.4887
- [ ] 31.0.101.4885
- [ ] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311

### Rendering API [Required]

- [ ] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu_4887_whql.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12889877/igcit_ssu_4887_whql.txt)

### Description and steps to reproduce [Required]

Blend file: [eeveenexttest.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12889899/eeveenexttest.txt) This is a blend file, but since blend files are not allowed to be uploaded, I've changed the extension to txt. Rename it back. Or use your own blend file?

Get the current 4.1 alpha. Eevee-next is no longer an experimental feature, so there should be no need to tweak any settings. Open the file (after renaming it to .blend), switch to material preview shading, see how it looks. Alternatively, make a simple scene yourself, the issue doesn't seem scene-specific.

![eeveenexttest](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/100067309/5b29c5ac-d114-4e32-81c1-0d7c0ea5612c)
Lighting direction looks completely broken and there are 2 small nested rectangles in the bottom left corner inside which shading is different, they look to roughly have the same aspect ratio as the image itself.

An image rendered with regular eevee, as a reference for how things should look:
![eeveeregulartest](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/100067309/51f5cbb6-4729-4e59-bf60-23401705cebc)

**Comment by Arturo-Intel** [comment]
@a-One-Fan 
Thanks for reporting this issue. 
We need to reproduce it in the lab and create the case.
Is eevee-next only in alpha version?

Any news will be posted in this thread :)
-- r2

**Comment by a-One-Fan** [comment]
@Arturo-Intel Yes, Eevee-next is only in the 4.1 alpha. 
In the past it was an experimental feature you needed to enable from the preferences, recently it was changed so it's not and it is in 4.1 by default with no extra settings, and hopefully it will stick through for the beta and the full release.

**Comment by a-One-Fan** [comment]
As a minor update, in newer 4.1 versions Eevee-next is no longer called that explicitly, it's just `EEVEE` now, and there's the old `EEVEE (Legacy)`. Like how Cycles-X isn't called that explicitly, just `Cycles`.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/100067309/a3b93911-b65b-46df-8755-f97da1c7b130)

That file I like posting will no longer reproduce the issue on a newer 4.1 alpha if Blender is fullscreened. To reproduce it, delete the lamps, switch to rendered and then undo, or make the area the viewport takes up smaller, see https://projects.blender.org/blender/blender/issues/115942

**Comment by Arturo-Intel** [comment]
@a-One-Fan Hey! Can you try with 101.5186?
I was unable to reproduce this behavior

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/155d1e5a-a691-473d-8578-d3e691cc74fc)

-- r2

**Comment by Arturo-Intel** [comment]
@a-One-Fan Please open a new case for the other behavior
We prefer to have one case for each problem/behavior you found. 
It is easier to track.

--r2
