### ISSUE TITLE
Doom eternal again is unplayable constant stutter with high framerate 

### ISSUE THREAD

**Issue by nielo360** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#56]
#### Checklist [README]

- [x ] Device is not undervolted nor overclocked.
- [ x] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [ x] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]

---Doom eternal 
#### Processor / Processor Number [Required]
i7-1165G7 

#### GPU Driver Version [Required]
- [x ] 27.20.100.9466 (*latest*)
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ x] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [x ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1. Game keeps stuttering constantly having hitches while playing. Even though it can easily run at 50fps on intel xe
2. 
3. 

---
#### Device / Platform [Optional][Recommended]
GPD win 3 intel xe

---
#### Game Settings [Optional][Recommended]

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---

**Comment by Valkirie** [comment]
Duplicated from #32. Merge the two.
Closing this one, please use #32 to ensure follow-up.
