### ISSUE TITLE
Death Stranding graphical glitch

### ISSUE THREAD

**Issue by Nikaim** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#560]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Death Stranding

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD R9 5900X

### Graphic Card [Required]

Intel Arc A750

### GPU Driver Version [Required]

- [X] 31.0.101.4887
- [ ] 31.0.101.4885
- [ ] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12905427/igcit_ssu.txt)

### Description and steps to reproduce [Required]

After update drive at 4887 in game appear some graphical glitches: ineterface on BB holder, glitch on grass outside buildings. On previous version 4826 all clear. Restore to 4826 remove this bug.
https://youtu.be/d4xPFxe-QRE

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

[<iframe width="1887" height="741" src="https://www.youtube.com/embed/d4xPFxe-QRE" title="Intel ARC A750 Death Stranding graphical glitch at driver v.31.0.101.4887" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>](https://youtu.be/d4xPFxe-QRE?t=243)

### Save game

[manualsave0.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12905733/manualsave0.zip)

**Comment by Arturo-Intel** [comment]
@Nikaim 
Thanks for reporting this issue,
We will replicate in our labs and come back to you if we need more info (thanks for the video :3 )

--r2

**Comment by Ilya-intel** [comment]
@Nikaim 
I've just tried with the same settings as you have and haven't faced these glitches. Have you tried clean driver reinstalling using DDU tool?
![DS](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/72c987dd-e760-4e6c-bb30-7daf682a5dc2)

**Comment by Nikaim** [comment]
DDU, clean install does'n help. But the new 4900 diver solve this problem.
