### ISSUE TITLE
Fortnite - DX12 has multi-second long hitches.

### ISSUE THREAD

**Issue by AaronBottegal** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#561]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Fortnite Battle Royale

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

5800X3D

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4887
- [X] 31.0.101.4885
- [X] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SystemScan.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12908170/SystemScan.txt)

### Description and steps to reproduce [Required]

Play game as normal. Will have hard hitch multiple times per game.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1440p Unlocked.

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![FortB](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/7392428/896c8d3a-9a1c-41ee-b164-58344c58b63d)
![FortA](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/7392428/7f55cf16-08dd-4622-8d48-5552d69e18a1)

### Device / Platform name

Windows 10

### Crash dumps [Required, if applicable]

No hard crashes currently.

### Save game

N/A

**Comment by AaronBottegal** [comment]
Right after this and also today I have had blue screens, with a bad process attachment both times. Probably driver related.

**Comment by AaronBottegal** [comment]
Oops.

**Comment by Karen-Intel** [comment]
@AaronBottegal thanks for your report. Adding it to our debug queue :)

Karen

**Comment by AaronBottegal** [comment]
Still happens with 31.0.101.4900.

**Comment by AaronBottegal** [comment]
Still happens with current BETA driver 31.0.101.4952.

**Comment by Arturo-Intel** [comment]
@AaronBottegal quick question, did you used DDU to install any of the driv

**Comment by AaronBottegal** [comment]
> @AaronBottegal quick question, did you used DDU to install any of the drivers?

Nope. I can't really test any changes with that either, the Fortnite update dances around the hitching issue now with the big update. I haven't experienced any in the past 2 days of playing with the new current beta driver. However, it definitely seemed like a driver stall of some type, definitely a driver issue. Maybe a race condition that happened rarely?

I am really into Linux and have watched Mesa's change log for years, along with helping AMD debug issues in git years ago, so I'm usually pretty hip to what is broken where usually. I sorta know what the software stack looks like for GPU's.

**Comment by Arturo-Intel** [comment]
welp, the thing is i am unable to reproduce it, i will share charts with 3060 and a770 later

**Comment by Arturo-Intel** [comment]
@AaronBottegal thanks for the report, I did got some micro glitches in both cards.. so it seem is related to the game itself.
If you get another strange behavior in the future please open a new case for it.
