### ISSUE TITLE
Drivers attempt to re-install the HDMI firmware

### ISSUE THREAD

**Issue by phyziyx** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#563]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Graphics Driver

### Processor / Processor Number [Required]

i3-10100F (and others)

### Graphic Card [Required]

ARC A770 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4887
- [X] 31.0.101.4885
- [X] 31.0.101.4826
- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [X] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13030661/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Hi, this issue exists from versions 4824 and above, including 4286 and 4887 (which is the latest at the time of writing).

To provide more information about my experience, my first driver installation was 4824, which updated my GPU and HDMI PCON FW.  Then I did a clean Windows install (swapped OS drives) and then installed 4826, which re-did PCON FW only.

Although I am only uploading my logs, I have seen several authentic reports on the Insiders Community Discord from many users.  I can upload their logs possibly as required, however recreating the issue is quite simple.

Excerpt from the driver install log (4826):
```[FwData_Update_Parsing]:File Path    : C:\Windows\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_6716fdeedff684d0\\FWDATA\dg2_intel_a770_config-data.bin
File Type    : 5
File Version : major_version->101-> oem_manuf_data_version->14-> major_vcn->1
The image's 4-ID manifest extenstion matched with the device
[FwData_Update_Parsing]:firmware data version is not compatible with the installed one (OEM version)
[FwData_Update_Parsing]:No Suitable FWData binary found for Upgrade
 
[FwData_Update_Service]: No Image found for FWData update
[GfxFwUpdateThread]: FWData Update Status:(2)
 
HDMI FW Progress:  1%
[CheckIfAnyGPUFWUpdatePending]: No Pending GPU FW left to update
[Signalevent]:Signaling Event Object (Global\IntelGfxGPUFWUpdateCompleted)
```

```
HDMI FW Progress: 96%
HDMI FW Progress: 100%
[UpdateRealtekPconFw]:FlashVersion:0x3 - 0x90 - 0x9326C810 -0x2C6
[PconFwUpdateTharead]:Pcon FW Update successful
Total Failed FW Update Count:0  Total successful FW Update Count:1 
[CreateAndUpdateFwUpdateCompletedRegKey]: Created Reg Key FwUpdateCompleted, 0 
[CreateAndUpdateFwUpdateCompletedRegKey]: Update count written into FwUpdateCompleted, 0 
[CheckIfAnyFWUpdatePending]: No Pending FW left to update
```

### Device / Platform

Desktop / PC

**Comment by Karen-Intel** [comment]
Hey all, ty for your report. We will be looking into this issue :)
Also, if you could share the reports on other channels, can you paste them here? We'd like to add how many users are actually impacted.

Hope to hear from you soon

Karen

**Comment by phyziyx** [comment]
About ten users have reported it from a quick count, however I believe this number to much higheras many users are not aware that it is re-installing the same firmware!?

- akarnokd already reported their issue above.
- 1 user reports that their firmware update fails because HDMI stopped being active they are using 1 HDMI and 2 DP (3 displays).
- Rest of the reports have nothing new to add other my report, all of them have either A750 or A770, however this issue possibly (I assume) exists outside of those two GPUs as well.

**Comment by Mindset-Official** [comment]
I have had this issue as well since the firmware update, it typically fails to install again thankfully, but if I unplug ny display port screen it will actually reinstall the firmware.  I received a scary black screen on one of the driver updates but it has just timed out since and fails the install firmware and installs drivers normally.

**Comment by DealsBeam** [comment]
Intel driver team is aware of this

**Comment by Karen-Intel** [comment]
> Intel driver team is aware of this

Yes it is :). Here's the internal report number for you: 15014177318
It is still a WIP in our end, once I get any updates about a fix in a public release I will let you guys know in this thread

Karen

**Comment by Gabriela-Intel** [comment]
Hey everyone! This should be resolved as of [101.4953](https://www.intel.com/content/www/us/en/download/785597/791578/intel-arc-iris-xe-graphics-windows.html) (published yesterday).

Can you please check out if you're still observing this behavior?

**Comment by akarnokd** [comment]
I confirm (here to) that 4953 did not reinstall the PCon FW.

[IntelGFXFwUpdateToolLog_2023-11-13_20-48-1.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13357576/IntelGFXFwUpdateToolLog_2023-11-13_20-48-1.log)

**Comment by Gabriela-Intel** [comment]
@IGCIT I think we can close this now that we have some confirmation :)

**Comment by phyziyx** [comment]
Can confirm as well that this has been resolved.
