### ISSUE TITLE
The card has delay when outputting the beginning of an audio playback

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#566]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

N/A

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4887
- [ ] 31.0.101.4885
- [ ] 31.0.101.4826
- [ ] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 22.10.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13063663/Intel.SSU.22.10.2023.txt)

### Description and steps to reproduce [Required]

Duplicate of [this](https://community.intel.com/t5/Intel-ARC-Graphics/The-card-has-delay-when-outputting-the-beginning-of-an-audio/td-p/1485273). And not getting any answer here.
This is an issue I'm having since I own this card (March), and the Intel “support” on the community forums told me that they were able to reproduce the issue, yet I have not seen this issue **once** in a driver release note as being a known issue. Of course, this hasn't been fixed either.
I truly understand that fixing issues can take time, but come on, it's been 7 months since this issue exists, many people have complained about this as well in the support thread in the forums. Could this issue be tagged as “high priority” ? Many people are experiencing this issue, and it is extremely annoying when it happens (every time you play audio basically)

### Device / Platform

ASUS Prime Z790-P WiFi D4

**Comment by jpovixwm** [comment]
So again no luck for Windows 10 users. Same as with #294.
Maybe Intel should just officially drop Windows 10 support and be done with it.

**Comment by MarkD1212** [comment]
I have reported this issue previously as well. Now it's a Windows problem, as reported by Karen-Intel? This this really true?

**Comment by TheWonderfulTartiflette** [comment]
Hello, sorry for the idling. I'm on 23H2, and I can confirm that I'm still having this issue. The only difference I could see between 22H2 and 23H2 is that on VLC, on 22H2, every time I jumped to somewhere in the video the issue occurred, but not really anymore.

**Comment by TheWonderfulTartiflette** [comment]
Can we reopen it, please? I'm still completely having this issue

**Comment by TheWonderfulTartiflette** [comment]
Hello @IGCIT , I noticed that you unassigned someone even though I said that I'm still having this issue and asking to reopen it. I cannot reopen it by myself, I think. Was this accidental ?

**Comment by IGCIT** [comment]
hi @TheWonderfulTartiflette, assignee has changed, removed old one in bulk but did not update closed issues since they are closed
sorry, i missed your last message, feel free to ping if an issue persists and want to reopen

**Comment by TheWonderfulTartiflette** [comment]
Thanks a ton @IGCIT , and no actually I didn't try to contact MS support about that, but indeed I'll contact them when they'll be open tomorrow, thanks

**Comment by Squall-Leonhart** [comment]
Is this the delay, aka, *First part of the sound is cut off before the audio stream wakes up the endpoint from low power* issue that also exists on Nvidia and AMD audio drivers?

**Comment by TheWonderfulTartiflette** [comment]
@Squall-Leonhart oh yes that's exactly it, but Nvidia and AMD had it fixed in 23H2, but not for me

**Comment by TheWonderfulTartiflette** [comment]
@IGCIT Hello, so I contacted MS support, and they said that it has something to do with my graphics drivers, because they “checked everything on [their] side”

**Comment by IGCIT** [comment]
i see, i understand your frustration, as pointed by karen, a ticket is already open, so please be patient, keep you os up to date and give them some more time

**Comment by TheWonderfulTartiflette** [comment]
Hi, I just wanted to know how the internal report is going ( 15010605147 ). This is a major issue for people who are experiencing it, and the employees at the [Intel community forum](https://community.intel.com/t5/Intel-ARC-Graphics/The-card-has-delay-when-outputting-the-beginning-of-an-audio/m-p/1482814) haven't said anything since 10 months now

**Comment by MarkD1212** [comment]
I have done a fresh install 22631.3296 with latest ARC driver 5333. Delayed sound through Display Port has not changed. HDMI port is not effected. There has been no action from within Intel community forums. There appears to be two similar threads. https://community.intel.com/t5/Intel-ARC-Graphics/The-card-has-delay-when-outputting-the-beginning-of-an-audio/m-p/1573784 and  https://community.intel.com/t5/Intel-ARC-Graphics/The-card-has-delay-when-outputting-the-beginning-of-an-audio/m-p/1482815

The first threads describes the issue clearly.

There is also was a suggestion it had to do with MS operating system, no update has made any change for me yet.

What further information can I provide you guys at Intel. This ongoing issue has been around for more than a year and so frustrating?  I did advise this, here issue last year, I guess it was closed.  Apologies if I have overlooked it on GitHub.

**Comment by TheWonderfulTartiflette** [comment]
Actually, both of these threads are from me. I think I've made two threads
because a moderator locked the former, so I had to make another one

**Comment by jpovixwm** [comment]
I suppose something like [Sound Keeper](https://veg.by/en/projects/soundkeeper/) could be used as a workaround, for the time being. I haven't tested it, though, as I no longer route my PC's audio via the Arc GPU.

**Comment by Gabriela-Intel** [comment]
As mentioned in #458, I'm asking that you all please report this issue directly to Microsoft. We've already reported this but have not had much traction on it so we are forced to close. Apologies in advance for this taking so much time for it to end up not being resolved.
