### ISSUE TITLE
Intel Arc A380 as TB3 eGPU has finicky unplug behaviors

### ISSUE THREAD

**Issue by ds84182** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#570]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 11

### Processor / Processor Number [Required]

Core i7-1255U

### Graphic Card [Required]

Arc A380

### GPU Driver Version [Required]

31.0.101.4900

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[abomination_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13194143/abomination_ssu.txt)

### Description and steps to reproduce [Required]

I swear this is not preposterous, I wanted to experiment with a "Steam Deck" alternative before Thanksgiving with family :P

1. Put an Arc GPU in an eGPU enclosure
2. Connect it to a laptop/tablet with TB3+
3. Use it for a bit (depending on case tested below)
4. Unplug 💀

## Detach Case 1: Iris x Arc driver version mismatch

This causes an immediate bluescreen on unplug.

The mismatch happens frequently when Windows Update downgrades drivers & when WU installs the Arc drivers for the first time.

## Detach Case 2: Arc driver disables Iris's display controller

Also occurs during a driver update with `Secondary Screen Only` enabled. In this case the Iris driver can do it to the Arc driver.

The laptop display freezes (or stays black) until you turn the display off and back on. On a Surface Pro this can be done via the power button, others will require the sleep key combo.

Attempting to reset the driver with Win+Shift+Ctrl+B in this state results in a full system lockup. Windows is completely dead at this point. Needs a hard shutdown.

---

Can attach a video of the abomination in action, if needed.

Either way, here's a pic! Doesn't it look great? :p

![PXL_20231022_063418217](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/2268005/468011c8-3d2f-4922-aee4-5cd59b0cee94)

### Device / Platform

Surface Pro 9

### Crash dumps [Required, if applicable]

My driver versions currently match, sorry :(

**Comment by Arturo-Intel** [comment]
@ds84182 
its alive, ALIVEEEE!!
You can share the video via YT tho
I am really curious now

**Comment by ds84182** [comment]
The tablet has an Iris iGPU and the "Iris & ARC" driver upgrades both to the same version. The driver installer doesn't upgrade the ARC driver if it isn't plugged in (which is understandable)

**Comment by Ilya-intel** [comment]
Hey @ds84182 ,
I was playing around with different laptops and eGPU + A380 combination, and find out that this BSOD/freeze issue fixed with the latest driver ver. [31.0.101.5074](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html). 


Could you also test it on your setup?

**Comment by Ilya-intel** [comment]
@ds84182 
Did you manage to test your setup again with the new driver?

**Comment by Ilya-intel** [comment]
@IGCIT 
The thread looks abandoned, could you close it?

**Comment by ds84182** [comment]
Wow this got buried in my email. @Ilya-intel I don't have the card in my enclosure at the moment, not sure when I can get a chance to retest it.
