### ISSUE TITLE
Poor performance in For Honor

### ISSUE THREAD

**Issue by Redtreatrick** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#571]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

For Honor

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [X] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 5600

### Graphic Card [Required]

Intel Arc A750 Gunnir

### GPU Driver Version [Required]

31.0.101.4900

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

Operating System:	Майкрософт Windows 10 Pro(10.0.19045 Build 19045)
Physical Memory (Installed):	32 GB
System Type:	x64-based PC
Total Installed Updates:	32 Updates - See Detailed View for more information
Display Adapter(s):	Intel(R) Arc(TM) A750 Graphics	31.0.101.4900
System Manufacturer:	MAXSUN
System Model:	MS-TX B550M
Network Adapter(s):	Realtek PCIe GbE Family Controller	10.66.621.2023
Disk(s):	ST1000DM010-2EP102	593,29 GB (available)	10.0.19041.3636
	TEAM TM8FP6512G	210,32 GB (available)	10.0.19041.3636

### Description and steps to reproduce [Required]

Start the game
Enable FPS counter
Start the match where FPS is unlocked (in menu it's 60)
Notice poor performance and low load of GPU 

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080  1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Does not depend on settings

### Device / Platform name

PC

**Comment by Gabriela-Intel** [comment]
Thanks @Redtreatrick! We'll look into this.

**Comment by Joseph-Intel** [comment]
hi @Redtreatrick thanks for submitting! I was able to test this on graphics driver V 1014953 on high settings i was getting anywhere from 100-120 FPS. Would you be able to provide more detail in what you're experiencing? Would you be able to retest and let me know your results?

**Comment by Redtreatrick** [comment]
hi @Joseph-Intel . I was able to get 200-250 FPS in the same game using Proton Experimental in Steam on Ubuntu so this truly is a DX9 issue. Sadly, Wine adds a huge input delay which is not acceptable in competitive play which I was interested in. Is it possible to add Vulkan support on Windows to reduce the input delay? Obviously, DXVK won't work with Ubisoft's Easy Anti-Cheat

**Comment by Joseph-Intel** [comment]
@Redtreatrick i understand your concern. Would you mind retesting with V1014953 in a Windows environment and letting me know your results and how it feels?

**Comment by Joseph-Intel** [comment]
Hi, @Redtreatrick Wondering if you got the chance to test out the latest driver V1014972. Let us know your results!
thanks

**Comment by Joseph-Intel** [comment]
@IGCIT Please help close this. If customer would like to reopen they can
