### ISSUE TITLE
Transport Fever 2 Device Loss

### ISSUE THREAD

**Issue by meniku** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#572]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Transport Fever 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 9 5900X 12-Core Processor

### Graphic Card [Required]

Intel Arc A770 Graphics

### GPU Driver Version [Required]

31.0.101.4900

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13214526/igcit_ssu.txt)

### Description and steps to reproduce [Required]

1. In Main Menu go to "Map Editor"
2. Use the following settings:
- Climate: Temperate,
- Vehicles: Europe
- Map Size: Small
- Leave everything else to the defaults
3. Start the game
4. After loading is completed, leave the window untouched for a couple of hours until a "Memory Exception" crash appears (might take up to 8 hours or so)

This only happens on the Intel Graphics card, Nvidia/AMD doesn't have those issues

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560x1369

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

[settings.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13216584/settings.zip)

**Comment by Felipe-Intel** [comment]
hello @meniku Is this issue still happening with [driver 101.5085](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)

**Comment by Felipe-Intel** [comment]
Closing issue since there is no response from the submitter.
