### ISSUE TITLE
Starfield Terrain Wireframe Visible

### ISSUE THREAD

**Issue by CookieNachos** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#573]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Starfield

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 5 5600X

### Graphic Card [Required]

Intel Arc A750 LE

### GPU Driver Version [Required]

31.0.101.4900

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13216562/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Start up the game.
Load a save on a planet surface or,
Start a new game.
Finish tutorial. 
Step out on planet.
Look at terrain.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080, 2560x1440, 3840x2160

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![settings 4k](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5190179/3f00023a-06ad-4f8b-a3d8-7b5d1e9012a6)
![Terrain](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5190179/f364631f-245e-480f-86d3-39af8456ff6a)

### Device / Platform name

PC

**Comment by akarnokd** [comment]
I've had this with driver 4672, 4885, 4887 & and all 3 game versions so far. I DDU'd before installing 4887 (my current driver). I verified the game files via Steam.

1080p60 no upscaling, all settings low or off, except VSync on.

*i7 13700K, 64GB RAM, A770LE, Windows 11 22H2, 2TB NvMe 7G/7G SSD*

[My NG+16 or so save - just look down](https://drive.google.com/file/d/1FfOBVb_0Q5richbDuuaOdg1q6MvKl84x/view?usp=sharing)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/98321b0b-7b8c-4a66-a730-d7aef62b887f)

**Comment by akarnokd** [comment]
Driver 4953 WHQL installed after DDUing 4887 non-WHQL. Wireframes are still there.

**Comment by akarnokd** [comment]
Update. Game 1.8.86, Driver 4953. Wireframes still there.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/017739f3-3bf6-4fe9-b4b1-481bf06d4659)

**Comment by akarnokd** [comment]
FYI, driver 4972 still has the wireframe visible.

**Comment by CookieNachos** [comment]
> FYI, driver 4972 still has the wireframe visible.

Can confirm with this. Latest game patch and driver update, wireframe is still visible.

**Comment by Arturo-Intel** [comment]
Hello everyone: 
Just to share our team is aware of this issue and its working on it.
ID reference number: 14020258070

--r2

**Comment by CookieNachos** [comment]
It looks like this may have been fixed with the latest driver 31.0.101.5186

**Comment by akarnokd** [comment]
I can confirm, the wireframe in low is gone with 5186. [Before](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/573#issuecomment-1787856552)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/ad920638-25a9-4716-b56d-2236dd4d2989)

However, the black rectangles in the system view on planets are still there (example: Volii):
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/67018342-bd53-4eb0-8414-b52f2e16d526)

**Comment by Arturo-Intel** [comment]
@akarnokd @CookieNachos 
Thanks for the confirmation!!
Will close this case.

@akarnokd Can you open a new case (or if there is already one open, link it here) for the black rectangles issue?
-- r2

**Comment by akarnokd** [comment]
Black rectangle issue -> #681
