### ISSUE TITLE
Firmware update in the latest driver 31.0.101.4952,1064<-1068

### ISSUE THREAD

**Issue by Pashamolochko** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#576]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel arc control

### Processor / Processor Number [Required]

i3 13100

### Graphic Card [Required]

ASRock Intel Arc A770 Phantom Gaming D OC

### GPU Driver Version [Required]

31.0.101.4952

### Rendering API [Required]

- [X] Vulkan
- [X] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

I have an ASRock Intel Arc A770 Phantom Gaming D OC video card, and after installing the latest driver, a notification about the firmware of the video card appeared, but after installing the version remained the same (1064), although there are some users who wrote that the firmware on LE video cards was updated for (1068), I had an update process, and passed successfully, but there was no flashing of the screen, is there any information about this?

### Description and steps to reproduce [Required]

I have an ASRock Intel Arc A770 Phantom Gaming D OC video card, and after installing the latest driver, a notification about the firmware of the video card appeared, but after installing the version remained the same (1064), although there are some users who wrote that the firmware on LE video cards was updated for (1068), I had an update process, and passed successfully, but there was no flashing of the screen, is there any information about this?

**Comment by Karen-Intel** [comment]
@Pashamolochko did you have your HDMI plugged? Just double checking everything was ok when the driver update started

Karen

**Comment by abrfilho** [comment]
The firmware update was only for Intel LE models, since it's not mentioned in the Release Notes we can't know for sure what changed.
You can track the FW updates here: https://www.techpowerup.com/forums/threads/intel-arc-firmware-compilation-matrix.312440/
As you can see, only the Intel models was tagged to have been updated on the latest firmware.

**Comment by Karen-Intel** [comment]
@abrfilho and @Pashamolochko
For some manufacturers a series of tests must be completed before deploying to every model in production and after Intel releases the driver they place their approval seal. You can check with your card manufacturer what is the driver version they offer.
Now, following these kind of guides for firmware updates is to be proven under your own risk as an incorrect procedure may lead to a misfunctioning card or even losing your warranty.
About the available information regarding the FW update, just remember that in the release notes Intel is considering both driver and firmware updates as one, so information in the RN correspond to both pieces of software. 
Our driver team is releasing updates quite often so you will get a firmware update for your card soon :)

Karen

**Comment by abrfilho** [comment]
> @abrfilho and @Pashamolochko For some manufacturers a series of tests must be completed before deploying to every model in production and after Intel releases the driver they place their approval seal. You can check with your card manufacturer what is the driver version they recommend. Now, following these kind of guides for firmware updates is to be proven under your own risk as an incorrect procedure may lead to a misfunctioning card or even losing your warranty. About the available information regarding the FW update, just remember that in the release notes Intel is considering both driver and firmware updates as one, so information in the RN correspond to both pieces of software. Our driver team is releasing updates quite often so you will get a firmware update for your card soon :)
> 
> Karen

Thanks for the explaining Karen!
I just mentioned the techpowerup page because the author of the post keep track of every change in the driver, and when there's a new FW, he marks which card received.
Regarding the Release Notes, the update that messed the Bifrost fan had a specific mention for firmware inside, I guess correcting AsRock fan behavior, the one that partially corrected Bifrost fan didn't change the FW version, I don't remember if the same firmware was overwritten or the change was inside only the driver and not in the firmware.

**Comment by Arturo-Intel** [comment]
@Pashamolochko  was your question answered? can we close this case?

**Comment by Karen-Intel** [comment]
@Arturo-Intel can you please close this one? No reply in the last month

Karen
