### ISSUE TITLE
Allow other Virtual Cameras inside of Intel Virtual Camera

### ISSUE THREAD

**Issue by BuyMyMojo** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#581]
### Application [Required]

Elgato Camera Hub/ Epoc cam

### Processor / Processor Number [Required]

5900x

### Graphic Card [Required]

A770

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

I use Elgato Epoc cam to use my phone as a camera for streams but it's built in green screen solution isn't as reliable as the Intel Virtual Camera background removal effect so I'd like to use the base camera feed from Epoc inside of the Intel Virtual Camera for it's removal effect but it does not appear inside of the camera list

**Comment by BuyMyMojo** [comment]
With the latest driver I can see Epoc Cam in there at least 👍

**Comment by Gabriela-Intel** [comment]
Hi @BuyMyMojo That's what you were looking for, right? Is there anything else that is missing from your original request? Let me know! Thanks.

**Comment by BuyMyMojo** [comment]
As weird as it sounds having OBS's Virtual Camera might be a good feature too, I know some people use it and a plugin to use their phone as a camera so using that with Intel would be nice but I am satisfied with it currently 👍

**Comment by Gabriela-Intel** [comment]
Got it, thanks! I'll file your feedback so the team can take a look at it. Thanks so much for following up and taking the time to help us improve. :)

@IGCIT We can close now, thanks!
