### ISSUE TITLE
Starfield crashes the GPU on certain planets/effects & requires power cycling

### ISSUE THREAD

**Issue by akarnokd** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#582]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Starfield

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

31.0.101.4887

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13270379/igcit_ssu.txt)

### Description and steps to reproduce [Required]

This happens randomly on planets with apparently a particular dust wind effect. For example, walk around on Kreet for some time.

My screen goes black (with backlight), the game still plays music for 2 seconds, then stops. Then my monitor turns off lacking HDMI input. 

I have to power cycle the machine.

(I have a save for it, but it is made with some mods - [Save](https://drive.google.com/file/d/1GYHM20chOtmOe45CYYD-ESYCp2NL5611/view?usp=sharing), just ignore the mod warning. It's not mods that causing this as I had a very similar crash a few weeks ago with full vanilla game but don't have that save anymore.)

Game settings: Full Screen Borderless, 1080p everything low or off, no upscaling, VSync on. Monitor is a Samsung 24" HDMI 1.4 only, connected via a brand new 8K60 rated cable. Replugging the cable, after the black screen but before power cycling, has no effect.

Attached the event viewer export. What it says is that the igfxnd had to be restarted several times and GSCx64 is being reset.

I'm not new to graphics driver crashes (had plenty of them with 4672 & Starfield), but since 4887, if the card crashes, there is no nice recovery - only power cycling.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/e7ef66c1-a24e-465e-be4c-fb98479f3d66)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/d4f62c13-c041-4144-bb03-149a75287f5c)

### Application / Windows logs

[GPU_CRASH__2023_11_6_17_49.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13270387/GPU_CRASH__2023_11_6_17_49.zip)
[starfield_crash.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13270463/starfield_crash.zip)

**Comment by akarnokd** [comment]
The previous app crash log on some other planet I don't remember exactly, but had a very similar dust wind effect.

[GPU_CRASH__2023_10_27_21_16.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13270545/GPU_CRASH__2023_10_27_21_16.zip)

**Comment by Arturo-Intel** [comment]
@akarnokd hey! did you tried to restart the graphics driver (Win + Ctrl + Shift + B) when the screens goes black? 
I know is not a fix (if it works) but it will remove the power cycling and you can continue playing.

**Comment by akarnokd** [comment]
Yes, I tried that. No effect. Not this time, not the last time (27th October case above).

Also tried typing in `shutdown -r` <kbd>Enter</kbd> blindly in Win+R but no effect. 

Also pressing the power button to trigger ACPI shutdown did nothing. I had to long-press to turn off the machine and then turn it back on.

I do have the power button action on shutdown. "Leállítás" == "Shutdown"
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/2ea533db-7807-4caf-87a0-03593e18cf57)

**Comment by akarnokd** [comment]
[Here is an unmodded save](https://drive.google.com/file/d/1rdTpgk8xzDYpsJkuA8WfxT8CXRXUHOpV/view?usp=sharing) from my previous character, parked on Kreet.

I believe the dust-wind effect causing the driver crash is somewhat random so it may take time and bit of running around to trigger it.

**Comment by akarnokd** [comment]
Sorry for the ping. Don't have new data for 4953 as I haven't played much with it.

To clarify, my bigger issue is the driver/card crashed in a way that renders it inoperable until I power cycle.

**Comment by Felipe-Intel** [comment]
Hello @akarnokd 
Right now our dev teams are working a crash issue in this game. In the meantime, could you please test the newest driver 5074? I'll keep you posted.

**Comment by akarnokd** [comment]
Hi. Thanks for the notification. I'll test the driver tomorrow.

**Comment by akarnokd** [comment]
🥳  Yay, could not reproduce the crash in about an hour running around the planet, including the original save I posted above (with the windstorm) and a different save (on the same planet, clear sky).

Game version: 1.0.88.0
Driver: 5074

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13659563/igcit_ssu.txt)

![starfield_1 0 88 0_settings_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/fce2e143-6cf8-42f7-af9f-704dbf6cc75f)

![starfield_1 0 88 0_settings_2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/baa33669-ddfa-49dd-89ca-81ecc583613a)

**Comment by Felipe-Intel** [comment]
@akarnokd great to hear! Is it OK if we close this one?
