### ISSUE TITLE
Firefox does not use av1 hardware acceleration on Intel Arc GPU

### ISSUE THREAD

**Issue by SopaDeMacaco-UmaDelicia** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#583]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Mozilla Firefox 119

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3D

### Graphic Card [Required]

Intel Arc A770 LE

### GPU Driver Version [Required]

31.0.101.4887

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

Windows 11 23H2

### Intel System Support Utility report

[_av1.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13273452/_av1.txt)

### Description and steps to reproduce [Required]

1. Open a 4k video https://www.youtube.com/watch?v=zCLOJ9j1k2Y with stats for nerds
2. Observe 5-12% of total CPU usage at 4K vp9
3. Go to https://www.youtube.com/account_playback switch to always play av1
4. Observe 15-30% of total CPU usage at 4K av1 and even 80% at 8K
5. Check about:support > media where it says av1 is not hardware accelerated
![media](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/106288630/f8b968a4-6f77-40b3-bc1a-a523508b13db)

**Comment by BiZkViT96** [comment]
Is there any reason why you use such a old driver? Because support will request you to update it. Problem looks like on Firefox side, have you tried ask for help on r/firefox/ or something like that?

**Comment by SopaDeMacaco-UmaDelicia** [comment]
It is latest driver in stable branch. On Linux Firefox does use hardware decoding on A770.

**Comment by abrfilho** [comment]
I tried with Edge here, only VP9 in the linked video, I'm using the latest driver.

**Comment by BiZkViT96** [comment]
Again it doesn't matter what Firefox does on Linux. If driver exposes hardware support, then ball is on Firefox devs side. As was pointed above in Edge AV1 is disabled completely. You should check HW acceleration in other web browser.

About video that you provide, yes there is AV1 variation. Here is Vivaldi with 4K AV1 60 FPS and CPU/GPU clocks is idling.
![2023-11-07 18_29_31-Greenshot](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/f3dcdf99-e02a-4a8f-9d3c-46429b6ba4cd)

If you don't want install Vivaldi just for checking, you can use this .bat to get auto portable version, put the .bat file in your desktop and after launching press R button when it asks.
[VivaldiPortableCreator.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13279502/VivaldiPortableCreator.zip)

Obviously if you will get HW acceleration in Vivaldi then its not a driver problem.

**Comment by freak2fast4u** [comment]
I agree with @BiZkViT96, this has to be a Firefox issue. I did the same test with Vivaldi and got the same results (on 4952 driver version anyway).

However it's possible you might need to select 8K resolution for google to serve you AV1. 4K was randomly served to me as VP9 on that video sometimes, even after I opted for "always AV1" in my account options.

Small side note : on Linux Mint, the natively packaged version of Firefox (119 to this day) doesn't seem to support VAAPI on intel even though all the proper packages "seem" to be installed ("vaapi connection failed" in the about:support page) and Firefox officially turned it on by default in version 115.
It does work out of the box in the Flatpak version though, I just had to find that out the hard way, thanks for the heads up ;)

**Comment by IGCIT** [comment]
hi @SopaDeMacaco-UmaDelicia,

as pointed out by @freak2fast4u and @BiZkViT96 (thanks to both), it seems to be specific to firefox

closing this for now, please contact Mozilla first ([Bugzilla](https://bugzilla.mozilla.org/home)), and, if this is a driver issue, will be reopened

thanks
