### ISSUE TITLE
Dragon Age Inquisition crashing and giving BSODs

### ISSUE THREAD

**Issue by GottaSlay** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#587]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Dragon Age Inquisition

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3D

### Graphic Card [Required]

Acer Intel Arc A770 Predator BiFrost OC

### GPU Driver Version [Required]

31.0.101.4952

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

23H2

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13295063/igcit_ssu.txt)

### Description and steps to reproduce [Required]

I started Dragon Age Inquisiton from Steam and played for about an hour exploring Hinterlands which is a very early area in the game. The game then froze my system for a moment and crashed. After trying again for about an hour or two of gameplay I experienced a BSOD with the message: VIDEO_SCHEDULER_INTERNAL_ERROR

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![1222690_20231108115652_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/1785a68e-3810-4880-809d-3da0e88b767d)

![1222690_20231108115704_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/e69d6879-18be-4cb7-828e-a937b865ab31)

![1222690_20231108115707_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/3c2a6215-aa6d-4404-957e-a96dadcc1da2)

Note: I'm now using DXVK which for some reason is forcing the game on my second screen, that is why the resolution in the screenshots is at 1920x1080. During the crashes the resolution was at 2560x1440

### Crash dumps [Required, if applicable]

[IGO_DragonAgeInquisition_6352.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13328836/IGO_DragonAgeInquisition_6352.log)

### Save game

[Save.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13295222/Save.zip)

**Comment by WouterNed** [comment]
I've been playing DA:I for over 25 hours over the last few weeks, and I haven't experienced a crash or a BSOD yet. I am still on the .4887 driver and i'll upgrade to the latest drivers and verify if I do get crashes this weekend.

I did get 2 freezes in that time, but since that situation was exactly as described [here](https://answers.ea.com/t5/Dragon-Age-Inquisition/dragon-age-inquisition-freezing-completely-while-playing/m-p/4213529), I assumed DA:I was at fault. When looking online there are quite a lot of people who were experiencing crashes with DA:I, so I figured DA:I was just a buggy mess.

Did you try reinstalling the driver with the DDU tool? Looking around this forum it often fixes the problem, which to me sounds like the update path isn't working correctly. Question to the support person: Is upgrading using the .exe on the intel website enough? Or do you also need to use the DDU tool?

**Comment by GottaSlay** [comment]
Since having my initial crashes, I haven't encountered a single one yet and I've been playing for nearly 8 hours in total since then. Previously I managed to play for about an hour or two before crashing. Gonna keep an eye on the situation.

**Comment by GottaSlay** [comment]
I've been trying to replicate my crash in a new playthrough for the past 2 hours without success. Don't know what was happening previously but the game's been running fine now.

**Comment by WouterNed** [comment]
Sorry for the late comment, life got in the way and I didn't play games as much as I'd like. I've been playing DA:I for another 8 hours in the meantime on the .4952 driver, and I literally just got one other system freeze. But nothing akin to your crash.

**Comment by GottaSlay** [comment]
Tested the game for another couple hours after uninstalling previous drivers with DDU in safe mode and then by installing the latest .5081 driver. No crashes this time and the GPU is sitting at around 70C. I'll close the issue.
