### ISSUE TITLE
Kingdom Hearts 1.5+2.5 & Kingdom Hearts 2.8 not starting up with latest drivers

### ISSUE THREAD

**Issue by KingYozora** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#59]
#### Checklist [README]

- [X] Device is not undervolted nor overclocked.
- [X] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [X] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
1. Kingdom Hearts 1.5+2.5 HD Collection
2.  Kingdom Hearts 2.8: Final Chapter Prologue
---
#### Game Platform [Required]
- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [x] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]
i7-1165G7
---
#### GPU Driver Version [Required]
- [X] 27.20.100.9616 (*latest*)
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [X] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1. Try and open both games
2. Wait
3.  Nothing happens

---
#### Device / Platform [Optional][Recommended]
 GPD Win 3

---
#### Game Settings [Optional][Recommended]
 N/A

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---

**Comment by estebanr863** [comment]
Hi @KingYozora, we are able to open the game fine with driver version [30.0.101.1191](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html). Can you please try again with this driver version?

**Comment by estebanr863** [comment]
Hi @KingYozora, did you had the chance to test with driver version [30.0.101.1191](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html)?

**Comment by KingYozora** [comment]
> Hi @KingYozora, did you had the chance to test with driver version [30.0.101.1191](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html)?

Yes they boot with the latest drivers (1191)
