### ISSUE TITLE
Please add the FPS limitation function at the driver level

### ISSUE THREAD

**Issue by Pashamolochko** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#592]
### Application [Required]

intel arc control

### Processor / Processor Number [Required]

i3 13100

### Graphic Card [Required]

intel arc a770

### Rendering API [Required]

- [X] Vulkan
- [X] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Is it planned to add the FPS limitation function to intel arc control,FPS limitation gives a good indicator of temperature reduction and throttle noise is reduced?

**Comment by GottaSlay** [comment]
Would also love to see something like this.

**Comment by Gabriela-Intel** [comment]
Thanks for the feedback! We've noted it down to pass along to the Arc Control team. :)

@IGCIT We're going to close this one out since it is a feature request.
