### ISSUE TITLE
Warcraft failing to find shaders 6 or higher

### ISSUE THREAD

**Issue by danjalical** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#593]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

World of Warcraft Retail

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [X] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

r9 5900x

### Graphic Card [Required]

Arc 750 Limted Edition 8GB

### GPU Driver Version [Required]

31.0.101.4887

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13313581/igcit_ssu.txt)

### Description and steps to reproduce [Required]

While in game try to choose the ray tracing

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/150359695/c82dfca1-18a0-4cf9-8751-a181d666b68a)
![2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/150359695/a701b0cc-f73f-45a6-acd0-2df08dda3922)

set maxed out

**Comment by stalker-svk** [comment]
I can confirm RT now does not work in WoW but it worked with older drivers and windows 11 22H2

**Comment by stalker-svk** [comment]
can anyone try older drivers on windows 11 23H2 and see if the RT works with older drivers?

**Comment by stalker-svk** [comment]
Arc A770, windows 11 23H2, drivers 4953
![Capture](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/137794439/0837a77d-5455-4ad8-afbe-aadda3771656)

**Comment by danjalical** [comment]
Any update on this issue

**Comment by Ilya-intel** [comment]
Hey @danjalical,
This issue is being worked out by our developers.
BUG ID for your reference is: 18035236740.

**Comment by stalker-svk** [comment]
I can confirm that RT shadows works again with newest driver 5186.
The VRS mode still doesn't work but now it says "unsupported for graphics related reasons" and not "requires shader 6 graphics card"

**Comment by Ilya-intel** [comment]
@stalker-svk 
I have just tested with 5186 and VRS can be enabled normally.
Could you clean install driver?

**Comment by Ilya-intel** [comment]
@danjalical 
RT issue is now fixed with 101.5186 driver.

**Comment by danjalical** [comment]
> @danjalical RT issue is now fixed with 101.5186 driver.

I will install this tonight and retest

**Comment by danjalical** [comment]
I con conferm that this option has been resolved, and is now working as of the latest release of both warcraft online & the latest Arc driver on the A750.  I would consider this issue, resolved.
