### ISSUE TITLE
Problems with fans on 2 A770 cards in Intel Arc Control

### ISSUE THREAD

**Issue by Valkill27** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#594]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

1) I5-12400f first 2) Xeon E5-2680v4 after

### Graphic Card [Required]

Acer Predator BiFrost Arc A770 OC andSparkle Arc A770 Titan OC Edition

### GPU Driver Version [Required]

31.0.101.4952

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13313500/ssulog.txt)

### Description and steps to reproduce [Required]

Acer Predator BiFrost A770.

This is the first card ordered.

On startup it turned out to be fan cycling, every 3-4 seconds it would turn on the fans followed by "0db Fan Mod" for 1 second. But it was fine with load, at the same 30% the card could hold a full load. 

So it's not clear why it constantly starts and turns off the fans, I thought the problem is the inability of its cooling to cool the card passively, and then I took it back to the store. 

Since the noise when working with Figma or simple browsing was very annoying. While it could not be if the card did not change revolutions 3-4 seconds from 0 to 1400 revolutions or from 0 to 1000-1200 in the program from Acer, which is already better, but bad.

Sparkle Arc A770 Titan OC Edition

This card is already better, the first 10 minutes I already thought that here it is, the one quiet and when you need powerful..... 

But no. 

The temperature rises not so much in passive mode but still it works the same though with less interval. 51 degrees, the fans turn on at 30% which even with her fans in a quiet computer is not pleasant. Then when the temperature drops to 49 degrees, they turn off. And this cycle already goes a little longer due to a better heatsink than Acer. 

But still the noise in a quiet case is like a bone in my throat. 

As for drivers, we tried different ones and even through DDU or whatever. The result is the same, the fans run without "0db Fan mode" only because of the drivers that do not allow to reduce the fan speed below 30% and maintain the temperature. And 30% power for an unloaded card is too much and it cools its 2% in seconds.

Is it so hard to do? If you don't want to do inside your program, at least make it available for MSI Afterburner. 

I work on my computer 6 to 12 hours a day. There are days when I only have 2d graphics and need to think. But the constant noise of your cards starting up and fading out is horrendous. 

Again, the problem is not with Acer, it's with Sparkle, the problem is with your software, and this has been tested on my old computer and on a friend's new computer with a 12400F processor. 

The cause of the inconvenience and noise is precisely this software threshold of 30% that makes the card roar like a tiger, even though nothing is happening and it could sleep peacefully in "0db Fan Mod".

**Comment by Valkill27** [comment]
The Acer video card has no ability to cool the card passively at all, but it can easily do so with its turbine without any noise. 

The Sparkle graphics card has quite a massive cooling system and simply cannot passively keep it at the right temperature at all times. 

As a user, I critically need the fans to be set to 30%, because listening to this constant noise is unbearable. I returned a normally working card because of this and bought a Sparkle which has the same problem that you are experiencing. 

And so far in a week I have not received a single normal response from you. Not from support... 

Why are you ruining the product and don't want to fix it or respond to it in any way?

**Comment by Karen-Intel** [comment]
Related to #430

**Comment by Valkill27** [comment]
> Related to #430

The transfer is cool, but are you gonna do something about it? The problem's almost half a year old.

**Comment by Karen-Intel** [comment]
I'm not transferring the case, just adding a note so the team in charge is aware of your experience and comments.
We have been actively working on every issue posted here including issue #430 along with many others.

**Comment by Valkill27** [comment]
> I'm not transferring the case, just adding a note so the team in charge is aware of your experience and comments in this new thread. We have been actively working on every issue posted here including issue #430 along with many others.

Hopefully just the normal fan control everyone has.... Except us.

**Comment by Felipe-Intel** [comment]
After further review, the teams involved reaffirmed that the fan curve was built to specifications with minimum 30% PWM as defined by product architecture requirements. This setting/configuration will not be changed as this will cause issues broadly for many more users with different fan configurations.
We'll proceed to close this bug report.
