### ISSUE TITLE
Non ideal performance: Immortals Fenyx Rising

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#595]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Immortals Fenyx Rising

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [X] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

intel Core i5-13500

### Graphic Card [Required]

intel Arc A770

### GPU Driver Version [Required]

31.0.101.4826

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU_20231110.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13315686/SSU_20231110.txt)

### Description and steps to reproduce [Required]

Using DXVK attains 17% performance uplift compared to the native DX11 driver. (DXVK: 96 fps, DX11: 82 fps)

However, DXVK causes screen flickering and blackouts with this particular game, so the experience is not satisfactory. Therefore, I hope the native DX11 driver can be further optimized for this game and achieve the same performance level as DXVK.

Thanks!

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Select the "Very High" graphics settings preset and then set "Anti-aliasing" to "Low".

**Comment by Ilya-intel** [comment]
Hey @Susie1818 ,
Developers are currently working on performance improving of many DX11 titles.
You can expect performance fix to be released in one of the next driver updates.
I'll keep you updated in this thread.

**Comment by Susie1818** [comment]
As I was doing some experiments for [ticket #580](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/580), I also found something related to this issue.

When playing this game using DXVK, there would be excessive and unnecessary attempts of changing monitor refresh rate causing screen blackouts, but if I turned on VSync in this game's video settings, then the blackouts would not happen. I don't know why but it just behaves this way. So, right now actually I can enjoy this game with DXVK as long as I leave the VSync on. I hope this information can be somehow helpful for your debugging.

But, it would still be very appreciated if the dev team can optimize the native DX11 driver so that the Arc GPU can achieve optimal performance without the need of using DXVK anymore. I am looking forward to it. (Native DX11 doesn't cause any screen blackout whether VSync is on or off in this game.)

**Comment by Ilya-intel** [comment]
Hey @Susie1818 ,
It took a while, but we have finally released the big fix for DX11 titles that included into the latest [32.0.101.6127](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) driver.
I've played Immortals: Fenyx Rising a bit it feels much better now.
Could you also confirm the fix on your side?
![Immortals](https://github.com/user-attachments/assets/674e1cb4-2db0-47fc-80af-a8849303a455)

Thanks, Ilya.

**Comment by Susie1818** [comment]
Hi @Ilya-intel,

Driver v6127 does improve a lot compared to previous drivers. Using the "High" graphics preset with anti-aliasing set to "Low", I got 99 FPS average @ 1920×1080 and 88 FPS average @ 2560×1440. However, this improved DX11 driver is still outperformed by DXVK, which now reaches 110 FPS @ 1920×1080 and 97 FPS @ 2560×1440. This means DXVK also gets performance boost from the latest driver v6127 and thus still maintains ~11% advantage over the native DX11.

Thanks for the great job, but there is still some potential left on the table.

**Comment by Ilya-intel** [comment]
Hey @Susie1818 ,
Did you use DXVK 2.4.1? 
Interestingly, I've just tested and it shows comparable or even lower average FPS than DX11...

**Comment by Susie1818** [comment]
Hi @Ilya-intel ,

Yes, I used DXVK 2.4.1.
I tried DDU and reinstalled the driver and retested. I found DXVK probably didn't gain any meaningful uplift from the new driver, and while DX11 has improved significantly, it is still a little bit slower than DXVK.

1920x1080
[Very High] preset with Anti-aliasing = [Low]
DX11 = 92 FPS (was 82 with driver v.4826)
DXVK = 97 FPS (was 96 with driver v.4826)
[High] preset with Anti-aliasing = [Low]
DX11 = 100 FPS
DXVK = 105 FPS

**Comment by Ilya-intel** [comment]
@Susie1818 
Thank you for retesting. 
I will pass this information to the development team, but please note that we cannot guarantee further improvements due to the minimal performance gain observed with DXVK. 
With that said, I will be closing this thread as the game is now performing well.
