### ISSUE TITLE
Intel Arc Reporting Wrong Shader Support

### ISSUE THREAD

**Issue by danjalical** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#596]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Control Panel

### Processor / Processor Number [Required]

r9 5900x

### Graphic Card [Required]

Arc 750

### GPU Driver Version [Required]

31.0.101.4952

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

![Screenshot 2023-11-10 102555](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/150359695/fb3fde6c-f2f2-4f8e-83cf-28b3278adfa8)
[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13318261/igcit_ssu.txt)
![cz3seywax7zb1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/150359695/ef4e4c8e-9a29-45fe-b32f-8e771b7c6377)

### Description and steps to reproduce [Required]

Open control panel and view supported to see 5.1
open gpuz to show it supports 6.6

**Comment by danjalical** [comment]
https://www.reddit.com/r/IntelArc/comments/17r0hvt/stuck_on_shaders_51/

**Comment by Arturo-Intel** [comment]
@danjalical Hey, I am currently getting info about this. 
Thank  you for reporting it.

--r2

**Comment by stalker-svk** [comment]
maybe this is reason why ray traced shadows don't work in world of warcraft

**Comment by stalker-svk** [comment]
latest drivers 5081 still have this issue

**Comment by Gabriela-Intel** [comment]
Sorry for such a long delay... This is fixed as of Arc Control version 1.79.5632.2. To install the latest version of Arc Control, please install our latest driver, [101.5762](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html?).
