### ISSUE TITLE
No Displayport signal from Arc A380 when system wakes from sleep

### ISSUE THREAD

**Issue by forestation** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#597]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows

### Processor / Processor Number [Required]

AMD Ryzen 9 7900

### Graphic Card [Required]

ASRock Challenger Arc A380

### GPU Driver Version [Required]

31.0.101.4952

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Log 2023-11-10.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13323973/Log.2023-11-10.txt)

### Description and steps to reproduce [Required]

Starting about 2 weeks ago, I get no Displayport signal from my A380 card when my system wakes up from sleep. I have always used Displayport to connect my monitor to my PC, and as far as I know I had made no changes to the display drivers, Windows, or BIOS immediately prior to this issue surfacing 2 weeks ago. 

I keep emphasizing Displayport because the issue does not occur if I'm connected via HDMI. With HDMI I get a normal display when the system wakes up from sleep. In fact, I've found that when I'm connected via Displayport and fail to get a Displayport signal when waking from sleep, I can switch the connection to HDMI at that point and the display will work fine. So it's not the entire A380 card that can't be awakened, only the Displayport output.

One other test I did was to connect my monitor via Displayport directly to my Ryzen 7900 iGPU. When I did that there was no issue when waking from sleep, which I think eliminates the monitor or cable as the source of the problem. 

Steps to reproduce issue:

1. Connect monitor to A380 via Displayport
2. Put system to sleep
3. Wake system
4. Monitor displays the message "No signal detected," and goes black

Thank you!

### Device / Platform

ASRock B650M Pro RS Wifi motherboard

**Comment by Karen-Intel** [comment]
Hi there @forestation!

Can you share your display specs and the IFWI version of your A380? can be found in system info (VBios)

Ty

Karen

**Comment by forestation** [comment]
Thanks for response.

Display is 3440 x 1440 x 59Hz
vBIOS version is 20.0.1064

Also, something else weird started happening at the same time about 2 weeks ago:

I use MPC-BE as my video player, and starting 2 weeks ago, there's a ~1 second lag when I open or close any video. During that second my screen goes black and there is no sound. 

Perhaps it is entirely unrelated, but I wanted to point it out. I found this discussion on line which is over my head, but perhaps you might find it useful: https://github.com/Aleksoid1978/VideoRenderer/issues/43#issuecomment-1014110898

**Comment by forestation** [comment]
I've updated to v.4953 of the Intel graphics driver; no change. As for the OS, I've been on Windows 11 for about 4 months, and the problem only surfaced a few weeks ago. 

Here's a summary of the tests I've done:

1. If the system goes to sleep on Displayport, the display will not wake if I stay on Displayport. But if at this point I switch to HDMI the display will wake.
2. If the system goes to sleep on HDMI, the display will wake normally if I stay on HDMI. After it wakes, I can switch to Displayport and get a normal signal. 
3. If the system goes to sleep on HDMI, and I switch to Displayport while it is still asleep, then the display will NOT wake. 
4. When the display fails to wake, disconnecting and reconnecting the cable doesn't help.
5. If I do the above tests with Ryzen iGPU Displayport, then the display wakes normally like HDMI.

Is there a way to capture a log of what's going on when the system wakes from sleep?

The only reason I mentioned the other issue is because it started happening at the same time and some of the discussion online about it seems to vaguely relate to my Displayport problem. For example: 
https://github.com/Aleksoid1978/VideoRenderer/issues/43#issuecomment-1016078283
But you can ignore if it's not helpful.

**Comment by Karen-Intel** [comment]
Hey @forestation hmm gotcha. I'm still unable to repro any of those scenarios :(

About your question, yes there is a way. You can start by downloading the [WAKD ](https://learn.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-analyzer)from Microsoft and running a [Standby test](https://learn.microsoft.com/en-us/windows-hardware/design/device-experiences/using-windows-performance-analyzer-to-analyze-modern-standby-issues)
You may need to leave your computer for an hour at least.

Also, can you share your Display specs? We have seen some specific issues with specific displays and would be worthy to ask around if we have any.

Thanks

Karen

**Comment by forestation** [comment]
I'm not sure what you mean by display specs. I have an LG 34UM88C-P monitor, at 3440 x 1440 x 59.97 Hz

I've downloaded WAKD and can run it if you think it might be helpful. Why do I need to leave the pc in idle state for an hour? The problem happens regardless of how long the pc has been awake or asleep.

**Comment by Karen-Intel** [comment]
1 hour: instructions on the Standby test in Microsoft, as part of the reply for your question

**Comment by forestation** [comment]
Those page seem to be targeted towards developers, so most of it is over my head.

The link you sent me says it's for Win 10. Should i use this instead since I'm on Win 11? https://learn.microsoft.com/en-us/windows-hardware/get-started/adk-install

**Comment by Karen-Intel** [comment]
Yes you can run it on Win 11, I have done a few tests myself on my Win11 
But no issues, there's no need for you to do so, it can be kinda tricky if you're not familiar with it, at least now you know there's a way to know what the computer is doing in sleeping states. 
We can stick to try to repro with similar hw and see if we can reproduce the same behavior :)

Keep you posted!

Karen

**Comment by forestation** [comment]
How can we move forward with this issue?

To get around the Displayport issue I've switched my connection to HDMI, but now I'm getting a new problem. From time to time, and without warning, my display will suddenly "shift" to the right by about 0.5 in, and and then shift back to the normal. 

I've attached two files, the first is a video that shows the display shifting back to normal. (I didn't have the camera ready when the original shift occurred.) The second is a pic where you can see the artifacts on the shifted screen. 

Is it possible that I just have a bad video card?


https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/4413149/ff24ac76-b847-4341-9209-c4453315b7cb

![Shifted display annotated](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/4413149/cc6d060b-eddf-472e-bc90-5a50a7cf1acf)

**Comment by forestation** [comment]
So here's something odd:

I just updated my BIOS to the latest version from ASRock. After the system booted into Windows, I noticed that the Displayport wake problem had gone away. 

At this point I rebooted into BIOS and loaded the AMD EXPO profile for my DRAM. (The BIOS update had reset all settings to default, including the DRAM settings.) This time after I booted into Windows, the Displayport problem came back. 

I then went back into BIOS and reset the DRAM profile back to Auto, but this did not fix the Displayport wake problem.

**Comment by Karen-Intel** [comment]
Hey @forestation we have created an internal report for this issue (Display port off signal when waking from sleep) 
This is the internal number, fyi: 14020658146
If we get any update will let you know :)

Now for the other issue, please open a new thread with instructions on how to repro. 

Thank you

Karen

**Comment by forestation** [comment]
I found out something interesting about the issue today.

Since the card has 3 Displayport outputs, I tested to see if the problem persists with all 3. The answer is yes. No matter which of the 3 ports I used, my display would not resume on that port when the system wakes up from sleep.

However, if at that point I switch my connection to one of the other 2 ports, then the display would be fine. It's only the port that went to sleep that wouldn't wake -- the other 2 ports would wake fine. This was true no matter which of the 3 ports I initially connected to.

This seems to suggest there's a software/driver issue with how Displayport is being put asleep or woken up.

Can I have the issue escalated to an engineer?

**Comment by Karen-Intel** [comment]
> Hey @forestation we have created an internal report for this issue (Display port off signal when waking from sleep) This is the internal number, fyi: 14020658146 If we get any update will let you know :)
> 
> Now for the other issue, please open a new thread with instructions on how to repro.
> 
> Thank you
> 
> Karen

Hey @forestation this issue has been escalated already to our dev team with the internal report I provided before
Which means, we're already working on this.

Karen

**Comment by forestation** [comment]
Does creating an internal report mean someone will investigate this issue?

I'm only concerned with the Displayport sleep/wake issue right now. I brought up the other stuff just in case it would be useful.

**Comment by Karen-Intel** [comment]
> Does creating an internal report mean someone will investigate this issue?
> 
> I'm only concerned with the Displayport sleep/wake issue right now. I brought up the other stuff just in case it would be useful.

Yes that is exactly what that means, we proceed to escalate and share the internal number when there's an investigation ongoing + add more details like the ones you just shared

Karen

**Comment by forestation** [comment]
Ok thanks. I couldn't really tell whether anyone is actively looking into this, given that there was no response for 2 weeks.

**Comment by rmorera-intel** [comment]
Hi @forestation can you please install driver [32.0.101.6130](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) and report back?

**Comment by forestation** [comment]
I gave up and switched to Nvidia a few weeks ago. The problems instantly vanished. 

In the interim I even RMA'ed the A380 card back to ASRock, but the replacement card exhibited similar (though not identical) problems. Like the first card it worked fine for a couple months. But then it started resetting my monitor to 480p (safe settings?) everytime it woke from sleep.

If you believe you've identified the issue and the solution, I can reinstall the A380 card and test it on my system when I have a minute.

**Comment by rmorera-intel** [comment]
Since the replacement card did not exhibit the issue of no signal after waking from sleep I will mark this one as closed.

I still invite you to test the A380 with our latest drivers since there have been plenty of fixes introduced since then. If possible verify if the issue with the video mode being reset still occurs, and if it does please create a new bug report since it is a different issue.

Best Regards,

**Comment by forestation** [comment]
I appreciate you following up after 10 months, and I understand you have an SOP for dealing with customer issues, but treating the two A380 cards as having different problems when the issues are clearly related (and likely arise from the same underlying cause) just adds to my frustration with the Intel Arc experience.

As for driver updates, I was diligently installing them up until I gave up on the card 2 months ago, so that's why I was asking whether there was something specific in the latest release that addresses this issue.
