### ISSUE TITLE
Star Wars Jedi Fallen Ordera crashes after 15-30 mins of play

### ISSUE THREAD

**Issue by gargamel314** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#598]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Star Wars Jedi Fallen Order

### Processor / Processor Number [Required]

i7-13700K

### Graphic Card [Required]

Arc A770 LE 16GB

### GPU Driver Version [Required]

31.0.101.4952

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU - SWJFO.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13324046/SSU.-.SWJFO.txt)

### Description and steps to reproduce [Required]

While playing the game normally, it crashes after 15-30 mins of game play (usually). The video will usually freeze, but audio ccontinues, and then it crashes with error messages resembling below. Occasionally, it will just crash without freezing. This has been a problem for the past 2 months of Intel Arc drivers, I can't tell you when exactly it began. 

Just play the game, crash happens after approx 15-30 mins of game play at stock A770 settings. Seems to happen when using dxvk also. 

### Device / Platform

ASUS Strix Z690-A D4

### Crash dumps [Required, if applicable]

I tried to do this but IGCIT Helper didn't create any logs. 

### Application / Windows logs

Error Messages:

LowLevelFatalError [File:Unknown] [Line: 330] Direct3DDevice->CreateTexture2D(TextureDesc,SubResourceData,OutTexture2D) failed at C:/certp/r4/game/Engine/Source/Runtime/Windows/D3D11RHI/Private/D3D11Texture.cpp:485 with error E_INVALIDARG, Size=-2147483616x-2147483616x1 Format=DXGI_FORMAT_R8_UNORM(0x0000003D), NumMips=1, Flags=D3D11_BIND_RENDER_TARGET D3D11_BIND_SHADER_RESOURCE , Usage:0x0, CPUFlags:0x0, MiscFlags:0x0, SampleCount:0x1, SampleQuality:0x0, SubresPtr:0x0000000000000000, SubresPitch:0, SubresSlicePitch:0 0x00007ff6865c650d starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff6865c5207 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff68659f414 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff6865bb754 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff686aaf588 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff6868352b7 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff6869532e0 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff68694a370 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff6866958c2 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff6868bf9b4 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff6868b7039 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff6860b7b14 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff686ac3d32 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff686ac3db8 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff6861c0cab starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff6861b7f27 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ffb3813257d KERNEL32.DLL!UnknownFunction [] 0x00007ffb3a0eaa58 ntdll.dll!UnknownFunction []

LowLevelFatalError [File:Unknown] [Line: 1145] GameThread timed out waiting for RenderThread after 120.00 secs 0x00007ff6767919f5 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff676795710 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff6755e19f2 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff6755e6910 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff6755e699a starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff6755eee17 starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ff6779360fa starwarsjedifallenorder.exe!UnknownFunction [] 0x00007ffa14ea1050 Activation64.dll!UnknownFunction [] 0x00007ffa14e98f82 Activation64.dll!UnknownFunction [] 0x00007ffa9fb1257d KERNEL32.DLL!UnknownFunction [] 0x00007ffaa0a2aa58 ntdll.dll!UnknownFunction []

[UE4Minidump.dmp](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13324066/UE4Minidump.dmp)

**Comment by Arturo-Intel** [comment]
@gargamel314 Thank you for reporting this.

I 2was able to replicate the freezing but  w/o any crash... 
I was able to continue using windows but the game just got frozen in a cinematic (the sound still was going)

This is was using 101.4952 + 12gen CPU + Arc 770

Will try now with the latest driver

-- r2

**Comment by gargamel314** [comment]
> @gargamel314 Thank you for reporting this.
> 
> I was able to replicate the freezing but w/o any crash... I was able to continue using windows but the game just got frozen in a cinematic (the sound still was going)

Yes, that's usually the behavior I get. If you let it stay frozen for a few minutes it will eventually crash and give you error messages. about 10% of the time it will crash immediately.

**Comment by Arturo-Intel** [comment]
@gargamel314 `did you try with the latest driver? (.4972) I was able to play more than 1hr

**Comment by gargamel314** [comment]
Yes - no crashes! Thanks! Also made it about an hour.

**Comment by gargamel314** [comment]
Confirmed - still a problem!
