### ISSUE TITLE
X-Plane 12 Vulkan drive error, unable to play

### ISSUE THREAD

**Issue by JoB4031** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#599]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

X-Plane 12.0.8

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

Install from vendor

### Processor / Processor Number [Required]

AMD 5800X3D

### Graphic Card [Required]

ARC A380

### GPU Driver Version [Required]

31.0.101.4952

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [X] Other (Please specify)

### Other Windows build number

10.0.19045 Build 19045

### Intel System Support Utility report

[X-Plane 12 Rig setup.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13328091/X-Plane.12.Rig.setup.txt)

### Description and steps to reproduce [Required]

Try to Install X-Plane 12.  This has been an ongoing issue as captured in this forum: https://community.intel.com/t5/Graphics/X-Plane-12-Support/m-p/1485916.  This thread implies the issue is being worked as of summer 2023.  But then a thread from JustSid at X-Plane implies as of August, not to expect a fix https://forums.x-plane.org/index.php?/forums/topic/292919-intel-arc-a750-will-it-run-on-x-plane-12-yet/#comment-2594963.  Is this issue fixable via an updated driver, or is the hardware not able to fully support Vulkan?

I have been using X-Plane 11 via Vulkan with few issues with this same setup.  I am needing to upgrade to the newer software to support ongoing development but the ARC hardware limitation is making this currently impossible.

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Not able to boot the application.

### Device / Platform name

BUSCH-VR-PC

### Crash dumps [Required, if applicable]

X-Plane Log file that says to update drive because it does not fully support Vulkan.

[Log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13328100/Log.txt)

### Save game

No save game, just need to be able to boot into the software.

**Comment by Arturo-Intel** [comment]
@JoB4031  Do you see this message?
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/153bcd52-297e-4686-a724-16ae842cc566)

**Comment by jacob1218** [comment]
Can't find the log, but reading the log, that points to a vulkan feature being missing (vkShaderStorageImageMultisample). If the gam has a way to run in DirectX or maybe even OpenGL mode, try that.

**Comment by BiZkViT96** [comment]
@Arturo-Intel Did you checked installation directory?

**Comment by jacob1218** [comment]
The log was created on my desktop when i tried the demo version

**Comment by Arturo-Intel** [comment]
@BiZkViT96 I run the demo. no installation directory.
@jacob1218 No luck in my side, sad. 
It is called "Log.txt" right? or it has a different name?

**Comment by jacob1218** [comment]
mine was called "X-Plane Installer Log.txt"

**Comment by Arturo-Intel** [comment]
Perfect, found mine too, thank you so much.
We will continue the normal process, any news we will share through this channel 

--r2

**Comment by JoB4031** [comment]
@Arturo-Intel That is the error message I received.  I was able to install X-Plane 12 by installing another graphics card, but if I try and make the ARC card the default monitor X-Plane 12 won't boot but display the same error message.  The error upon install results in the "X-Plane Installer Log.txt" file or if you run X-Plane from a second monitor the "Log.txt" file in the X-Plane directory is what I attached.

@jacob1218 My understanding is that X-Plane 12 is all Vulkan now and no longer OpenGL.

Is the vkShaderStorageImageMultisample vulkan call a feature that ARC cards will be able to support?

Thanks.

**Comment by Arturo-Intel** [comment]
Just sharing some info:
Our team is currently working on root causing this issue, the internal report number is: 14018967671

-- r2

**Comment by Gabriela-Intel** [comment]
Hi @JoB4031! I provided an update regarding this issue in the corresponding [Community Thread](https://community.intel.com/t5/Graphics/X-Plane-12-Support/m-p/1485916) that you referenced earlier. Basically, we did make a fix (not available publicly yet) but there are still some issues that need to be resolved from X-Plane's side. We're working closely with X-Plane devs to get the game going on Intel Arc.

**Comment by BigNish7** [comment]
Hi all - had the same issue. My log file is attached. Great to hear that Intel are onto it.

[Log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13670747/Log.txt)

Kindest regards,

BigNish7

**Comment by Gabriela-Intel** [comment]
Thanks all for your patience. :)

The error has been removed in the latest X-Plane 12 Beta, version 12.1.0. Please update to this beta (instructions [here](https://www.x-plane.com/kb/using-x-plane-betas/)). Note that the fix is NOT available in the public version of X-Plane 12.

Also, make sure to install Arc Graphics driver [101.5186 or newer](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html?).

**Comment by Gabriela-Intel** [comment]
@IGCIT Please close
