### ISSUE TITLE
Mortal Kombat 11 dont connect with WB servers

### ISSUE THREAD

**Issue by SephirothXJPN90** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#60]
#### Checklist [README]

- [x] Device is not undervolted nor overclocked.
- [X] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [X] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Mortal Kombat 11 Ultimate
---
#### Game Platform [Required]
- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]
i7-1165G7
---
#### GPU Driver Version [Required]
- [X] 27.20.100.9616 (*latest*)
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [x] DirectX12
- [x] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [X] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1. Open Game
2. Wait to connect server
3. Dont connect

---
#### Device / Platform [Optional][Recommended]
GPD Win 3

---
#### Game Settings [Optional][Recommended]

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---

**Comment by IGCIT** [comment]
please specify your processor

this seems to be a known issue of the steam version and not related to intel drivers, @Valkirie ?

**Comment by estebanr863** [comment]
Hi @SephirothXJPN90,

Game connection to a server is not related to the Intel Graphics Driver in any way. This is not an issue we can support or resolve. Please contact the game developer or publisher for support on this issue.

Hi @IGCIT,

Can we close this as it is not related to the graphics driver?
