### ISSUE TITLE
Is it possible to add the Firmware Version for my ARC card to the Release Notes document that comes with each driver update?

### ISSUE THREAD

**Issue by BigNish7** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#601]
### Application [Required]

Intel Arc Driver

### Processor / Processor Number [Required]

Intel Core i9 13900KS

### Graphic Card [Required]

Intel ARC A770 LE

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Other Windows build number

22631.2428

### Describe the feature [Required]

To add the Firmware Version to the Release Notes PDF document that is provided with each driver update. This would allow owners like me to check they are on the latest firmware update via ARC Control.

I am assuming that the IFWI(V-BIOS) is the firmware version. Mine is 2.1068.0. I would like to know if this is the latest - e.g. by checking in the Release Notes.

**Comment by Susie1818** [comment]
Since driver 4644, intel began to flash firmware(VBIOS) and did multiple times but never disclose what's changed in the newer firmware. What's worse is that I haven't seen anyone on the Arc subreddit sharing about any benefit from the newer firmware and only seen a lot of people sharing about something wrong (abnormal fan speed, micro stuttering, second display not working, etc.) introduced after the firmware updates.

**Comment by Valkill27** [comment]
The fans from Karen's screenshot where the temperature of the card without load is 73 degrees will confirm that either you heat the card or suffer from noise.

**Comment by Gabriela-Intel** [comment]
Thanks so much for the feedback everyone :) I totally get where you are coming from. I've reached out to the team to have a discussion on possibly adding fw versions to the release notes.

@IGCIT We're going to close this one out since it is a feature request so we cannot promise an ETA on this
