### ISSUE TITLE
Modern Luxury (NSFW) full crash when starting a new game.

### ISSUE THREAD

**Issue by 2besch** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#602]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Modern Luxury (NSFW)

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

Patreon (Free Version - https://www.patreon.com/posts/modern-luxury-v0-91015557)

### Processor / Processor Number [Required]

r7 7700

### Graphic Card [Required]

A770 LE

### GPU Driver Version [Required]

31.0.101.4952

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13348447/igcit_ssu.txt)

### Description and steps to reproduce [Required]

- start a new game from main menu
- wait 5 - 30 seconds (may even load completly and then crash)
- game crashes with "LowLevelFatalError" (see screenshot for details)
![Unbenannt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/150803378/8be8fc7a-769e-48a8-85c3-61e18d9c62da)

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

both all highest possible and lowest possible result in a crash

**Comment by Karen-Intel** [comment]
Hey @2besch good news!

We could reproduce the crash with driver 4952 after loading a new game but we tested it also with v.4953 and the game runs without any issues :)

Can you give it a go and let us know? Remember to use DDU in the upgrade

Karen

**Comment by 2besch** [comment]
Unfortunately still the same for me :/
Even with DDU.
![4953](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/150803378/00bea022-6da2-441e-997f-f54e29714ce7)

**Comment by Karen-Intel** [comment]
Using Intel 13900k with A750 + driver v4953 I haven't had any crash at all and no errors for about 30 minutes as well.

Just make sure you're using the game Graphics Settings in high performance > A770, and as I mentioned the issue is not exclusive to Intel either as the only time I saw the error was with the NVIDIA system.

In NVIDIA 3050, the error occurred with the latest driver (11th Gen + UHD + NVIDIA 3050) but after a couple launches and reducing the Gfx quality the game ran for about 30 minutes without any issue.

Would be good to check with the developer if it's just a matter of shaders not compiling as expected in your AMD + Intel system.

Hope it helps! 

Karen

**Comment by 2besch** [comment]
I wasn't sure what you ment with "Just make sure you're using the game Graphics Settings in high performance > A770". But what I tried confused me even more:

1. tried to run the game on my integrated Graphics

- Deactivated the intel Arc A770
- Game ran without problems (but as expected bad performance)

2. tried disableing the iGPU and run the game on my A770

- Activated the A770 and deactivated the iGPU and restarted the PC
- now the game crashed instantly with the following error
![2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/150803378/3ab64dd5-9c6d-400c-ab6f-0428bf9d7e49)

3. reset

- Activated the iGPU again and restarted
- same instant crash on startup
- tried to redownload the game => still the same.

I don't know whats going on here, but something is very wrong with either the game or the driver.

Any further Ideas woud be welcome.

Otherwise we could close this issue and I talk to the developer.

And just wondering: You said that you could reproduce the issue with v.4952 but then said that the issue was only found with a rtx 3050. So something doesn't add up there.

**Comment by Karen-Intel** [comment]
Hey @2besch yes you're right!

What I meant is that the crash doesn't occur on our end with version 4953, but it did on v.4952.
On the NVIDIA system I mentioned, it also has a UHD as a combo and we tested on both UHD and NVIDIA. 
Disabling the iGPU made the game crash but enabling it with the latest driver for both, worked like a charm (in medium quality of course)

So there might have been some issue with the v.4952 but v4953 works fine for us.

Would be worth to check if on the dev's end there have been issues found in AMD systems + ARC GPUs, specially on shaders.

Oh and what I meant was adding the game in the Game Settings menu to map  it to your ARC GPU
Just look for the .exe and once it is added to the list, click on 'Options' and select 'High performance'

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/54f157c9-66e6-4a97-9069-c1544b63a95b)

Let us know how it goes!

Karen

**Comment by 2besch** [comment]
No difference for me, with the .exe set to A770.

But I found some crash dumps at 
"C:\Users\\{user}\AppData\Local\ModernLuxury\Saved\Crashes" and this is mine:
[UECC-Windows-744B618E401BCEEF47825B8F985D7917_0000.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13357035/UECC-Windows-744B618E401BCEEF47825B8F985D7917_0000.zip)
Maybe this helps?

**Comment by Karen-Intel** [comment]
Yeah, let me check them out + I will arrange to have a system with AMD + ARC soon. 
I will post my findings here

Karen

**Comment by Karen-Intel** [comment]
Hey @2besch, I could start a new game in a Machine with AMD Ryzen 5, Windows 10 and my A380, however it crashes after a while. Most settings I modified them to medium due to the card I'm using. 
However it is crashing for me too, with the same error.
In systems with Intel Processors + ARC the game runs fine and no crashes at all, with the same driver.
Can you please contact the developer and confirm if  AMD + ARC is a supported configuration? 
And if so, which driver was used to test in ARC? This will help us identify a regression and confirm the game used to be playable in a config using AMD + ARC

I'd also need to know the game status, (Alpha or Beta) and an average of users playing this game

TY

Karen

**Comment by Arturo-Intel** [comment]
@2besch any news with contact the dev?

**Comment by 2besch** [comment]
@Arturo-Intel @Karen-Intel  yes:
the error is fixed with the new version of the game (0.2.6.0) and according to the dev: 
"It had most likely something to do with either of these. [...]
-Game engine updated to UE 5.3 [from UE 5.1]
-Plugins updated (DLSS 3)" -dev on discord.
also thanks for all the help.
