### ISSUE TITLE
Vulkan capture rendering issue Godot + Ryujinx

### ISSUE THREAD

**Issue by BuyMyMojo** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#606]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Godot 4.1-4.2Beta6 + Ryujinx 1.1.1087

### Processor / Processor Number [Required]

AMD 5900x

### Graphic Card [Required]

A770

### GPU Driver Version [Required]

31.0.101.4953

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU_2023-11-17.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13381328/SSU_2023-11-17.txt)

### Godot:
Create/open a scene with a rotating or moving camera and use the built in movie capture feature.
it will result in captures that have the rendering issue, it is most visible at the start when whatever buffer is failing is empty so it creates black lines then throughout the capture there will be lines near the top of the screen lagging behind the rest:

First Frame:
![frames00000000](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/f569d265-ebb1-449f-8180-061de3f16d72)

Later frame:
![frames00000083](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/35afe1d2-2200-4f28-91db-59551b5fc482)
![zMzjwKNbIO](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/a36fdb56-9b6d-472a-a85d-8dc42970a436)
![editor_screenshot_2023-11-17T053901](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/d281f062-5ab5-4732-8ca6-d89de3e81f54)

You can also just screenshot in the engine with the built in screenshot keybind:

![editor_screenshot_2023-11-17T053611](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/40550cc3-5939-4f80-945c-e94d1b7ef4ce)
![editor_screenshot_2023-11-17T053632](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/79172169-96df-4e70-9f62-5ffcb6645072)

### Ryujinx:

I specifically got it when playing my legally backed up copy of Super Mario RPG, after moving if you pause the game the same issue occurs:
![ryujinx_capture_2023-11-17_05-07-01](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/9b81f0a7-fb81-4e77-8d8c-4487864c3604)
![ryujinx_capture_2023-11-17_05-07-22](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/6b540870-aeb5-41a5-ae5d-1314527e5a01)
![ryujinx_capture_2023-11-17_05-07-37](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/6b647b7b-aea1-4726-8926-074d45f01952)

My favorute result I got:

![ryujinx_capture_2023-11-17_05-06-26](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/009be00c-5f18-408e-b29d-eb1a74980ec1)

### Application / Windows logs

[godot2023-11-17T05.31.33.log.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13382203/godot2023-11-17T05.31.33.log.zip)

[Ryujinx-Logs.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13381360/Ryujinx-Logs.zip)

**Comment by BuyMyMojo** [comment]
Forgot to include that I opened an issue on Godot's page a while ago about this issue and it did seem to be an Intel Arc windows driver issue

https://github.com/godotengine/godot/issues/81829

**Comment by Karen-Intel** [comment]
Hey @BuyMyMojo can you share the Godot project where you created the scene?

I'll make sure to verify it asap. Thanks

Karen

**Comment by BuyMyMojo** [comment]
[Debug Menu Demo.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13382588/Debug.Menu.Demo.zip)

it is just this asset library scene: https://godotengine.org/asset-library/asset/1903

**Comment by Karen-Intel** [comment]
Hey @BuyMyMojo I did some tests with driver version 4972 and I am unable to reproduce the corruption at the top during the render. Can you check with this driver version please?

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/f1c64a80-6a31-4df8-bc1f-32d10c349733)

However, I am seeing a difference in light/shadow rendering betweeen ARC and NVIDIA in Godot

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/d93da718-8013-4bc6-a8e4-6f842457d6f7)

Please let me know your results!

Karen

**Comment by Karen-Intel** [comment]
Ohhh @BuyMyMojo that video is priceless!
I could definitely repro the issue! 
Give me some time to create my report and share with you the internal tracking number here
And thank you for taking the time of sharing such complete evidence!

Karen

**Comment by Karen-Intel** [comment]
Hey @BuyMyMojo!  Great news!
Can you please verify this issue with our latest driver[ v.5074](https://www.intel.com/content/www/us/en/download/785597/794835/intel-arc-iris-xe-graphics-windows.html)? I just did some tests with Godot and the artifacts in the frames are not showing anymore on my end. 

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/6ceb9263-db3f-498f-9a1e-7f6b239f6b01)

Looking forward to hear from you!

Karen

**Comment by BuyMyMojo** [comment]
downloading an trying now!

**Comment by BuyMyMojo** [comment]
seems fixed to me!
