### ISSUE TITLE
The possibility of reducing the voltage and frequency of the GPU in intel arc control

### ISSUE THREAD

**Issue by Pashamolochko** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#607]
### Application [Required]

intel arc control

### Processor / Processor Number [Required]

i3 13100

### Graphic Card [Required]

ASRock Intel Arc A770 Phantom Gaming D OC

### Rendering API [Required]

- [X] Vulkan
- [X] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Please add the ability to reduce the voltage and frequency of the GPU in Intel arc control, which allows you to reduce the temperature and consumption of the graphics card

**Comment by abrfilho** [comment]
Something like the V/F Curve from MSI Afterburner would be nice.
