### ISSUE TITLE
PresentMon to show the current running API

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#608]
### Application [Required]

intel PresentMon

### Processor / Processor Number [Required]

intel Core i5-13500

### Graphic Card [Required]

intel Arc A770

### Rendering API [Required]

- [X] Vulkan
- [X] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [X] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Recently I have been using intel PresentMon to observe the details of the behavior of my Arc A770. I really like this tool, but I hope it can show which rendering API (D3D12, D3D11, D3D9, VULKAN, etc.) is currently in use like what Riva Tuner Statistics Server does.

**Comment by IGCIT** [comment]
Hi,

PresentMon is a standalone application, as such, please open any issue or feature request in their [github](https://github.com/GameTechDev/PresentMon)

thanks
