### ISSUE TITLE
Starfield 1.8.86 performance regression

### ISSUE THREAD

**Issue by akarnokd** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#609]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Starfield

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

31.0.101.4953

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13418916/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Starfield officially updated to 1.8.86 (main branch, not beta, never had the beta).

Disabled all mods, loaded up my unmodded save, then went around a bit. Framerate was abysmal.

For example, the Lodge, which has barely anything to render used to be 60fps, now it sits at 25fps on average. The Rock on Akila City is now 15 fps.

[Save file inside The Rock](https://drive.google.com/file/d/1XyR3Dt_zZe7SHF4JwJOyw0Nr91GDLsCl/view?usp=sharing)

(Not sure if it helps, but I experienced very similar performance degradation back when 4885 came out - only resolved by 4887.)

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Windowed Borderless 1080p VSync on, everything else turned low or off.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/1aac7f2e-b750-4c19-b2b6-e3af584c26fc)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/99d5cf2f-165e-47ba-b6ad-bf0cf7962076)

### Save game

[Exitsave0_2758134C_4461766964_180021_20231120194744_245_18_4.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13418963/Exitsave0_2758134C_4461766964_180021_20231120194744_245_18_4.zip)

**Comment by akarnokd** [comment]
- 4887 - 1.7.36 run fine, 60fps most indoors, ~40fps in main cities
- 4953 - 1.7.36 run mostly fine, 60fps most indoors, but ~35fps in main cities

**Comment by BiZkViT96** [comment]
@akarnokd Release notes from 31.0.101.4972 driver claims that this problem had been solved.

**Comment by akarnokd** [comment]
Alright, DDU + 4972, performance is back, maybe even better on Akila & New Atlantis.

Although not exactly perfect as I get ~44 fps just by looking at the back wall of the Lodge. If I look everywhere else, I have 60 fps.

Anyway, the main regression has been resolved so I'd consider this issue closed.
