### ISSUE TITLE
ELEX rendering object edges incorrectly

### ISSUE THREAD

**Issue by TimoMueller** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#61]
#### Checklist [README]

- [X] Device is not undervolted nor overclocked.
- [X] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [X] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
ELEX
---
#### Game Platform [Required]
- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
---
#### GPU Driver Version [Required]
- [X] 31.0.101.4032
- [X] 31.0.101.3975 Beta
- [X] 31.0.101.3959
- [...]
- [X] 31.0.101.3222
- [X] 30.0.101.1660
- [X] 30.0.101.1631
- [X] 30.0.101.1404 
- [X] 30.0.101.1192
- [X] 30.0.101.1191
- [X] 30.0.101.1121
- [X] 30.0.101.1069
- [X] 30.0.100.9955
- [X] 30.0.100.9894
- [X] 30.0.100.9862
- [X] 30.0.100.9805
- [X] 30.0.100.9684
- [X] 30.0.100.9667
- [X] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [X] Windows 11 21H2
- [X] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1. Just start the game and you'll see the issue.

---
#### Device / Platform [Optional][Recommended]

GPD WIN3 i7 16 GB

---
#### Game Settings [Optional][Recommended]

Settings are indifferent for this issue.
![ELEX1](https://user-images.githubusercontent.com/1918290/120450650-f3ec7900-c390-11eb-97b6-fb0d13e19bde.png)
![ELEX2](https://user-images.githubusercontent.com/1918290/120450682-f9e25a00-c390-11eb-876f-4978cdfe197d.png)

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---

**Comment by TimoMueller** [comment]
30.0.100.9667 didn't fix this issue.

**Comment by TimoMueller** [comment]
30.0.100.9684 didn't fix this issue.

**Comment by TimoMueller** [comment]
30.0.100.9805 and 30.0.100.9862 didn't fix this issue.

**Comment by TimoMueller** [comment]
Switched to Windows 11.
30.0.100.9894 and 30.0.100.9955 didn‘t fix this issue.

**Comment by estebanr863** [comment]
Hi @TimoMueller, this issue was reported internally, and a fix is in development. I'll let you know once this fix is included in a driver for you to test it.

**Comment by TimoMueller** [comment]
Just a quick reminder that this issue is still happening on 30.0.101.1191 and 30.0.101.1192 (pushed through Windows Update).
ELEX 2 will release on March 1, 2022 and I wonder if I can do another playthrough of ELEX on the Intel Xe beforehand. ;)

**Comment by estebanr863** [comment]
Hi @TimoMueller, our driver development team has this in their queue. I'll let you know once a posible fix is developed and inclued in a driver update.

**Comment by potatoding** [comment]
same graphic issue here. windows 11, driver version is 1340. Any hope for fixing this in next update?

**Comment by TimoMueller** [comment]
It could even help #115 as there is the same graphical issues visible underneath another layer of issues.

**Comment by potatoding** [comment]
@estebanr863 unfortunately, the issue remains.

**Comment by potatoding** [comment]
btw, operating system is win11, cpu is 1195g7, 30.0.101.1404 driver.

**Comment by Nino-Bock** [comment]
Just a quick note it's the same on Win 10.
win10, cpu is 1195g7, 30.0.101.1404 driver

Getting that fixed would be brilliant

**Comment by TimoMueller** [comment]
Issue remains on *.1404 and *.1631
I noticed that the issue got dropped from the known issues in the release notes.
Is that the Intel way of handling issues? Doing nothing and never mentioning them again? :D

That’s not confidence-inspiring when it comes to dedicated Arc graphics cards.

**Comment by estebanr863** [comment]
Hi @TimoMueller 

The release notes are usually used to address known issues on the most recent and most played app and games. We internally track a lot more of known issues than the ones described in the release notes, and it would be very hard to include every single known issue with every single app or game in existence in a single document.

I am personally tracking this specific issue on ELEX. As well as all other issues reported on this site. However, please note that given the current driver development workload and priorities it may take multiple months to include a fix for this issue into a production driver.

**Comment by TimoMueller** [comment]
Hey @estebanr863

Thank you for giving this information. I know that there's a huge department for marketing and stuff ... also how the roadmap will look like.
But the key for building an awesome and passionate community is communication.
Intel Xe Gamers are the early adopters and if they realise that Intel really cares about their interests it could lead to them recommending Intel GPUs to their friends.

The Arc Control looks like a step into the right direction and I hope that we'll see it soon on other GPUs and with a newer driver than this *.1325.

Back to topic: *.1660 didn't fix this issue but it's mentioned in the Release Notes again. Thank you! :)

**Comment by TimoMueller** [comment]
Just a little update: *.3222 didn't fix this issue yet.

**Comment by TimoMueller** [comment]
Issue still present on *.3959 and *.3975 Beta.

**Comment by TimoMueller** [comment]
31.0.101.4032 fixed this issue. :)

**Comment by IntelSupport-Arun** [comment]
@IGCIT , Since the issue has been resolved by the latest driver 31.0.101.4032 please close this case.
