### ISSUE TITLE
EA Sports WRC abysmal framepacing

### ISSUE THREAD

**Issue by ksof1** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#610]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

EA Sports WRC

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i9-12900K

### Graphic Card [Required]

Inter Arc A770 LE

### GPU Driver Version [Required]

31.0.101.4972

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [x] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Ea SPORT WRC framepacing.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13443022/Ea.SPORT.WRC.framepacing.txt)

### Description and steps to reproduce [Required]

The framepacing in EA Sports WRC is horrible. FPS jumps from 90 to 300 to 40 to 90 to 300 to 40 constantly. Lowering FPS by increasing game settings will change the range to 60 => 200 => 30 => 60, etc. 

No other GPU vendor has this of issue. 
![Screenshot 2023-11-10 153722](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/144232261/3546d787-6fe6-46ed-a687-68194284ff5c)
![20231109152406_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/144232261/aa986aa4-444b-410f-9074-56e062777643)
![20231122224938_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/144232261/533a77c6-ee2c-46b7-bcb4-9387c37075ce)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

3440x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Doesn't matter much, lowering Shadow quality and Reflections quality gets FPS up above 60 but the framepacing stays bad regardless of performance range. 

### Device / Platform name

PC

**Comment by Karen-Intel** [comment]
Hey @ksof1! TY for your report. Adding to debug queue

I will report my findings soon, stay tuned!

Karen

**Comment by ksof1** [comment]
Just quick play, framepacing isn't tied to settings. I tried dropping Reflections and Shadow Detail to the very lowest which about doubles average FPS but has no effect on framepacing.

**Comment by ksof1** [comment]
It's been half a year, half a dozen patches from developers, yet the problem still present. The game remains unplayable despite Intel having so-called "Game Ready Drivers" out alongside the release of the game. 

Hello?

**Comment by Karen-Intel** [comment]
Hi, sorry for the late reply

This issue is still under investigation on our end. It has been reported already with the internal report number #16022608923
Just FYI, fixes may take from 3 up to 6 months to be released, we appreciate your patience

Karen

**Comment by rmorera-intel** [comment]
Hi @ksof1 
Driver [32.0.101.6129](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) has been released and it contains substancial improvements on DirectX 11. Please give it a try and let me know your feedback.

**Comment by ksof1** [comment]
> Hi @ksof1 Driver [32.0.101.6129](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) has been released and it contains substantial improvements on DirectX 11/12. Please give it a try and let me know your feedback.

I only see .6127 on your link, not .6129. Are you talking about new unreleased one or the one you sent?

**Comment by rmorera-intel** [comment]
There is a delay due to server caching... here's the direct link: https://downloadmirror.intel.com/836996/gfx_win_101.6129_101.6045.exe
The page will be updated shortly.

**Comment by ksof1** [comment]
> There is a delay due to server caching... here's the direct link: https://downloadmirror.intel.com/836996/gfx_win_101.6129_101.6045.exe The page will be updated shortly.

It seems I have a different issue now with the game itself. The game just crashes before getting to the menu, as it seems to be happening with others:

https://answers.ea.com/t5/Bug-Reports/Update-2-1-0-the-game-crashes-to-desktop-at-launch-at-the-EA/td-p/14146662

So at the moment I can not check whether the performance has changed, until the devs fix the game crashing.

**Comment by rmorera-intel** [comment]
I installed the game today and got the same crash... for now I'm testing by running the game in DirectX 11 (add the -dx11 parameter in Steam) and it didn't crash for me.

**Comment by ksof1** [comment]
> I installed the game today and got the same crash... for now I'm testing by running the game in DirectX 11 (add the -dx11 parameter in Steam) and it didn't crash for me.

In DX11 mode the framepacing seems to be fine, but I need to test more. Will do the same testing as I did a year ago and report back in a couple days.

**Comment by rmorera-intel** [comment]
Thanks for confirming the fix on DX11. I still see the issue on DX12 even after patch 2.1.5 and other users continue to report it on [EA's forum](https://answers.ea.com/t5/Bug-Reports/Update-2-1-0-the-game-crashes-to-desktop-at-launch-at-the-EA/td-p/14146662).

To facilitate bug tracking and findability for other users could you please submit a new bug report for this crashing issue? (you can reference this one).

I'll temporarily close this one so our focus can be the crashing issue.
