### ISSUE TITLE
Deliver Us Mars crashes driver & have to power cycle

### ISSUE THREAD

**Issue by akarnokd** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#614]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Deliver Us Mars

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

31.0.101.4972

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13465307/igcit_ssu.txt)

### Description and steps to reproduce [Required]

In the game, I reached mars and am at the elevator are with a puzzle.

Whenever I try to do the puzzle, the screen goes black, and eventually my monitor turns off. I have to power cycle the machine. So far it happened 3 times at this exact location.

In the event viewer, I see two subsequent `igfxnd` didn't respond and was restored entries.

I had TDR set to 5 seconds TDI to 10 seconds before I started playing this game.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/8863a8d4-56a2-421e-9d2f-b1365c12c326)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/f3802329-c2bf-4b34-a425-e7b734ccac12)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/d954cde9-6be8-4161-9e25-395795955086)

### Crash dumps [Required, if applicable]

[Crashes.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13465312/Crashes.zip)
[ReportArchive.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13465328/ReportArchive.zip)
[WATCHDOG-20231125-2227.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13465329/WATCHDOG-20231125-2227.zip)

### Save game

[DUM_SaveData.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13465311/DUM_SaveData.zip)

c:\Program Files (x86)\Steam\steamapps\common\Deliver Us Mars\DeliverUsMars\Saved\

**Comment by akarnokd** [comment]
Did a run with DX11 mode. No crash.

**Comment by akarnokd** [comment]
Sorry, the game's settings are weird - they don't seem to save properly.
When I replay the location with or without RT effects enabled, sometimes it crashes, sometimes it doesn't.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/518792c5-11f2-4bc9-a825-a706890517cd)

**Comment by Karen-Intel** [comment]
Hi @akarnokd thank you for your report!

This issue has been verified on our end. Sharing with you the internal report number, just for your reference: 18028063978

Any update we will post it in this thread, so please keep it open

Talk to you soon!

Karen

**Comment by akarnokd** [comment]
No more issues with 5522, with or without RT. Probably resolved internally so can be closed?
