### ISSUE TITLE
Weird mirroring effect Assassin's Creed: Syndicate

### ISSUE THREAD

**Issue by ewahl-osc** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#615]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Assassin's Creed Syndicate

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [X] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 5800x3xd

### Graphic Card [Required]

predator A770

### GPU Driver Version [Required]

31.0.101.4972

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [x] DirectX11
- [ ] DirectX10
- [x] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssi.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13494591/ssi.txt)

### Description and steps to reproduce [Required]

This is an older one, so no worries if it's zero priority, but it's gone free for a couple weeks so I imagine many people will pick it up. 

There seems to be an odd offset, "mirroring" effect that overlays the screen and seems to be like a strange see-through layer that gets set into the viewing area.  

Tried all "standard" graphics settings and all seemed to be affected. 

![Assassin's Creed® Syndicate2023-11-28-18-49-42](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91157568/e8c83348-411b-4daa-9eed-c0a93e247ac4)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Set graphics to High, Very High, Ultra, etc.

**Comment by ewahl-osc** [comment]
workaround:
Looks like it is related to MSAA anti-aliasing.  If only FXAA is used, game looks fine.

**Comment by Vivek-Intel** [comment]
HI @ewahl-osc 
This issue happens only when MSAA is enabled and we had this issue submitted to Intel developer team in past. We found that issue is not related with Intel graphics driver but need a fix from game developer side but they are not updating the this title anymore.

We would request you to check this issue with game developer support.

**Comment by kunit1** [comment]
@Vivek-Intel but this issue doesn't appear with Nvidia or AMD cards. So they're clearly doing something that intel isn't to make this game render correctly with MSAA on

**Comment by ewahl-osc** [comment]
Sounds like you need a “known issues” page/list somewhere so you folks (and the customers) do not waste time reporting things like this over and over in the future.

Ed

**Comment by Vivek-Intel** [comment]
@IGCIT please mark this as closed
