### ISSUE TITLE
Cats Hidden In Paris flickers

### ISSUE THREAD

**Issue by akarnokd** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#617]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Cats Hidden In Paris

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770LE

### GPU Driver Version [Required]

31.0.101.4972

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [x] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13517224/igcit_ssu.txt)

### Description and steps to reproduce [Required]

*I understand this won't be a priority, just hoping there is something with it that can lead to better DX9 compatibility in the drivers.*

This is a [free game on Steam](https://store.steampowered.com/app/2313250/Cats_Hidden_in_Paris/). Very basic 2D hidden object game. The game is written in the Clickteam Fusion engine.

When I launch it, I get a white full screen image with occasional flicker of the actual game image. The game defaults to the A770 fine. 

If I force Windows to use the UHD 770 iGPU (same drivers), I only get a white screen with a line near where my taskbar's top would be. No flickering but no ingame image whatsoever.

The fun part. Using DXVK 2.3 X86 DLLs next to the game's exe, the game displays and plays just fine. 

*(Sidenote: when I launch it or close it while using DXVK, I get a momentary black screen, could be some resolution change, freaks me out every time given #614 )*

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/16eed204-66d9-420f-af78-0db3816e8922)

**Comment by akarnokd** [comment]
[Cats Hidden in Paris_d3d9.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13517373/Cats.Hidden.in.Paris_d3d9.log)
[Cats Hidden in Paris_dxgi.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13517375/Cats.Hidden.in.Paris_dxgi.log)

**Comment by akarnokd** [comment]
FYI, Driver 5074, still flickers.

**Comment by akarnokd** [comment]
FYI, Driver 5081 (installed after safemode DDU), still flickers.

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13684739/igcit_ssu.txt)

**Comment by Vivek-Intel** [comment]
@akarnokd Thank you for reporting the issue.
We are working on this issue. I will let you know once fix is merged in public release driver.
As of now you can continue to use DXVK 2.3 X86 DLLs as workaround for this issue on A770.

**Comment by Vivek-Intel** [comment]
@akarnokd can you check with latest driver ?

**Comment by akarnokd** [comment]
DDU clean install 5085. Removed DXVK workaround. Still flickering.

https://www.youtube.com/watch?v=iFRzR7SXBi4

**Comment by akarnokd** [comment]
The issue is fixed with 5186 for me too. Thank you!
