### ISSUE TITLE
ELEX 2 - Frame drops and stutters

### ISSUE THREAD

**Issue by Diomedus94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#619]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

ELEX 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7 7800X3D

### Graphic Card [Required]

Intel ARC A770 16G LE

### GPU Driver Version [Required]

31.0.101.4953

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[system.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13538854/system.txt)

### Description and steps to reproduce [Required]

The game all the time stutter and have frame drops.
Can not attach any file from the game becasue it dont crash during gameplay.
It has two rendering API, DX11 and BETA DX12, the DX12 doesnt even work.
It has two launch option on steam, only DX11 launch option works the default one crash.
I tried DXVK 2.3 but it still stutter.
I tried DXVK 2.3 GPlasync and it works really well.

Here i add guide what i need to do with DXVK to play the game smoothly.
https://www.reddit.com/r/IntelArc/comments/186r95f/elex_2_dxvk_23_gplasync_arc_a770_16g_1440p_win_11/

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2 560 x 1 440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![4kiwuhmjva3c1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/152784041/bd0da17a-c534-43c6-85ba-a7c28be9fa24)
![rf2hyrzfva3c1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/152784041/4eb4a696-c4fb-4a76-b33e-966edb6f2571)

**Comment by Felipe-Intel** [comment]
Hello @Diomedus94, both of these are known issues. Please check back later our knowledge articles for updates on this title issues. 

[ELEX 2* Bad Framerate with Intel® Arc™ A770 Graphics](https://www.intel.com/content/www/us/en/support/articles/000095931.html)

[ELEX 2 crashes with default API](https://www.intel.com/content/www/us/en/support/articles/000095930.html)

If you have no further questions, I'll proceed to close this ticket.
