### ISSUE TITLE
ELEX 2 - DX12 BETA crash instatly

### ISSUE THREAD

**Issue by Diomedus94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#620]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

ELEX 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7 7800X3D

### Graphic Card [Required]

Intel ARC A770 16G LE

### GPU Driver Version [Required]

31.0.101.4953

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[system.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13539200/system.txt)

### Description and steps to reproduce [Required]

The DX12 BETA on steam doesnt star, crash instatly after black screen

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2 560 x 1 440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![elex 2 beta](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/152784041/c76da077-c735-4fa6-a7ed-a25a2cfa7118)

**Comment by Diomedus94** [comment]
The URL doesnt work it just show default support page

**Comment by Felipe-Intel** [comment]
Thanks for the heads-up, I just noticed it too. I'll report it. The contents are the same as the article for the framedrops: known issue. This same link should work within the next couple of days. You can use it later to check if there is new info on this title. 
Please let me know if I can close this ticket and ticket #619

**Comment by Diomedus94** [comment]
If you are not doing anything else then yes you can close it  :)
