### ISSUE TITLE
Intel Arc application/overlay always opening on the Remote Desktop Connection host

### ISSUE THREAD

**Issue by ceedveed** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#621]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 10

### Processor / Processor Number [Required]

Intel i7 9700

### Graphic Card [Required]

Intel Arc A380

### GPU Driver Version [Required]

31.0.101.4972

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13540266/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Use Remote Desktop Connection to connect to a PC that has Intel Arc installed. The Intel Arc desktop application or overlay always opens in the remote session when connection is established.

To clarify, the RDC host has Intel Arc. The RDC client does not have Intel Arc.

**Comment by Arturo-Intel** [comment]
@ceedveed Just to double check
When you remote connect to a PC with an ARC installed, the Arc control pops out inside the "Remote Desktop window" right?

**Comment by ceedveed** [comment]
> @ceedveed Just to double check When you remote connect to a PC with an ARC installed, the Arc control pops out inside the "Remote Desktop window" right?

Yes. Arc control is opening in the remote desktop window immediately after the connection is established.

**Comment by Vivek-Intel** [comment]
@ceedveed I verified issue with latest drivers (101.5074) and could not find any issue so can you please check below steps and confirm if issue occurs. 

1: Install driver and arc control panel (101.5074) on host system 
2: lets say client do not have arc control panel installed at all or any other system.
3: Try to connect client from host computer
4: remote connection is fine and arc control panel is not launched at all.

Where as if you try to connect to client which has Arc control panel installed then it is expected to have arc control panel launched on client (will be seen in remote desktop window) on every remote session connection.

**Comment by ceedveed** [comment]
> Where as if you try to connect to client which has Arc control panel installed then it is expected to have arc control panel launched on client (will be seen in remote desktop window) on every remote session connection.

I'm wasn't connecting to the client (no ARC) _from_ the host computer (ARC). I was connecting in the way that was described in your quoted paragraph above.

Even though this behavior is expected like you mentioned, is there a way to disable ARC control from automatically opening? Can you also help me understand why this is the default behavior?

**Comment by Vivek-Intel** [comment]
@ceedveed can you try removing arc control panel from startup and check if it stops opening up automatically when you establish remote connection.

Task manager --startup apps --arc control panel--disabled **OR** Setting--Apps--Startup--arc control panel--turn it off.

**Comment by ceedveed** [comment]
> @ceedveed can you try removing arc control panel from startup and check if it stops opening up automatically when you establish remote connection.
> 
> Task manager --startup apps --arc control panel--disabled **OR** Setting--Apps--Startup--arc control panel--turn it off.

I tested this in a slightly different way by exiting the ARC control panel. I assume this way is similar to disabling ARC startup and restarting. Doing this stops ARC control from opening when the remote connection is established.

However, this means I no longer have ARC control running in the background to check for driver updates. A workaround is to use Intel Driver and Support Assistant. I don't see this as a fix though.

Is it not possible to stop this behavior without resorting to disabling ARC control from running at Windows boot or exiting the ARC control application?

**Comment by Vivek-Intel** [comment]
> Is it not possible to stop this behavior without resorting to disabling ARC control from running at Windows boot or exiting the ARC control application?
 
As per current design flow, you would need to manually check for driver updates by manually invoking arc control panel if you remove from startup menu or use IDSA to update the drivers. (Intel driver support assistant as you already mentioned.)

**Comment by ceedveed** [comment]
> > Is it not possible to stop this behavior without resorting to disabling ARC control from running at Windows boot or exiting the ARC control application?
> 
> As per current design flow, you would need to manually check for driver updates by manually invoking arc control panel if you remove from startup menu or use IDSA to update the drivers. (Intel driver support assistant as you already mentioned.)

Thanks. I would propose an option to disable this behavior. Here is my use case:

The PC that uses ARC is only used for rendering videos and I only need to access this machine using a remote desktop connection. I often disconnect and reconnect remotely when I am not next to the machine in an office building so that I can check on progress, initiate new workflows/renders, and do other things on the remote PC.

The automatic opening of ARC is annoying because I need to close it every time I remote connect to the PC. This behavior is not present on AMD or Nvidia. I don't understand the utility of having ARC open automatically. Therefore, I would propose a new feature to disable this behavior.

For now I will use workarounds.

**Comment by Vivek-Intel** [comment]
> The automatic opening of ARC is annoying because I need to close it every time I remote connect to the PC. This behavior is not present on AMD or Nvidia. I don't understand the utility of having ARC open automatically. Therefore, I would propose a new feature to disable this behavior.
> 
> For now I will use workarounds.

@ceedveed I understand your concern. I have submitted feature request to get a toggle option either on install page or in arc control but please know that we can not commit any date or its implementation.

I would suggest to use workaround as of now.

@IGCIT please help mark this case as closed.

**Comment by aloknakate** [comment]
IntelArcControl team has got a lot of request regarding this behavior. Though this is expected behavior right now, we are in process of fixing this. 
The remote desktop session initiation will not invoke ArcControl app (if in background or closed)
