### ISSUE TITLE
Sharp drop in performance with MSAA in Assassin's Creed Syndicate

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#622]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Assassin's Creed Syndicate

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [X] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

31.0.101.4953

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 04.12.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13544864/Intel.SSU.04.12.2023.txt)

### Description and steps to reproduce [Required]

In the game, the FPS goes from 112 with FXAA enabled to 40 with FXAA + MSAA 4X. Yes, it's normal that MSAA drops performance, but absolutely not to this degree. It goes along #541 and #509 where I said that Arc cards almost always have issues with MSAA in games.
I haven't tested with 4972, but I'm sure that the issue persists, because since I own my Arc, this issue exists

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Low

### Device / Platform name

ASUS PRIME Z790-P WiFi D4

**Comment by Vivek-Intel** [comment]
@TheWonderfulTartiflette can you please uninstall existing driver using DDU and check with latest driver. are you getting fps around 112, is it only inside the factory (before door opens) or through out the game with VXAA or AA off ?

FYI, there is a known issue (game developer's) causing transparent looking corruption on Arc when MSAA is enabled in this game.
[Article ](https://www.intel.com/content/www/us/en/support/articles/000097646/graphics.html)

**Comment by Vivek-Intel** [comment]
@TheWonderfulTartiflette we are looking into to improve overall FPS improvement for this game, will let you know once we hear more about this. Please check FPS once after DDU because we do not see 100+fps at any point in the game.

**Comment by MillionsToOne** [comment]
For me the game breaks the shaders when enabling MSAA. The best I can do is FXAA unless I want to get flickering.

**Comment by Vivek-Intel** [comment]
@TheWonderfulTartiflette did you get a chance to confirm FPS again ?

**Comment by Vivek-Intel** [comment]
@TheWonderfulTartiflette can you check FPS with l[atest driver ](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)- 
this driver has some FPS improvements on this title, please help verify at your end as well.

**Comment by TheWonderfulTartiflette** [comment]
Sure, I'll try that tomorrow

**Comment by TheWonderfulTartiflette** [comment]
I can't test in the same spot as this post, but now, without MSAA I'"m getting 74FPS, and with 4X, 40FPS

**Comment by Vivek-Intel** [comment]
@TheWonderfulTartiflette we will be closing this thread and refer to article above.
@IGCIT please close this one.
