### ISSUE TITLE
Snowrunner - Stutters and Frame drops

### ISSUE THREAD

**Issue by Diomedus94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#623]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Snowrunner

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7 7800X3D

### Graphic Card [Required]

Intel ARC A770 16G LE

### GPU Driver Version [Required]

31.0.101.4953

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[system.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13552096/system.txt)

### Description and steps to reproduce [Required]

By Intel support site it say the snowrunner game is resolved, i had newer drivers and it still stutter and drop frames.
https://www.intel.com/content/www/us/en/support/articles/000093850/graphics/intel-arc-dedicated-graphics-family.html?wapkw=snowrunner

I needet to use DXVK 2.3 with GPLasync to play it smoothly, guide here:
https://www.reddit.com/r/IntelArc/comments/1857smd/snowrunner_dxvk_23_gplasync_arc_a770_16g_1440p/

Before DXVK i had about 30-50FPS, with DXVK without the FPS cap i can have about 100FPS.

Try DON map, it had the worst performance.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2 560 x 1 440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![snowrunenr 1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/152784041/4274dfff-cd93-471a-a292-cc9e709e742f)
![snowrunner 2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/152784041/627d1d8a-f0e6-4924-8bd6-c3ca33ecad47)

**Comment by Nikaim** [comment]
It looks like there is a problem with rendering water surfaces. When there is water in sight, performance drops. Watch the video.
https://youtu.be/omamOuSqcwY?si=Y4BVDvBalyIQr5lO

**Comment by Diomedus94** [comment]
Interesting it looks like some problem with light boucing of water or rendering the water, as it is liquid it have some properties and mass and physics is applied to it and you can cross it and the water will do volumetric waves, but using DXVK wrappers solve those problems with too much frame drops, maybe just translating DX11 library to DX12 would solve the problem. But i am on side to optimize the drivers to better handle the water, i looked to some older issues on other games with water and it looks like to me at least the drivers have some problem with light and water cobination.

**Comment by Ilya-intel** [comment]
Hey @Diomedus94 ,
We're aware of the issue. Currently it's being worked out by developers, and you can expect the fix in one of the next driver updates.

**Comment by Diomedus94** [comment]
@Ilya-intel arent those issues mean to be active until the problem was fixed ?

**Comment by Ilya-intel** [comment]
@Diomedus94 
Sure, but this fix is already on the go and the only question is when it will be added to the driver.
But we can keep it open, if you want.

**Comment by Diomedus94** [comment]
@Ilya-intel it was just a question, the logic behind it was weird, if this is like "to do list" but from community the logic is "we are working on it, some pleoples can add their findings, then done, chceck, close it with results, next",

You can close it, for me at least my work was done to inform about the problem, because it was nowhere to find that you are continuing to working on it.

**Comment by Ilya-intel** [comment]
@IGCIT 
Let's keep this case open until fix release.

**Comment by Nikaim** [comment]
Improved performance at 5194 driver same as dxvk: https://youtu.be/JAtqCDyiz4E

**Comment by Diomedus94** [comment]
Closing ticked myself, issue was resolved with driver 5194 as seen on video from Nikaim.

https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html

Snowrunner* (DX11)

    Up to 71% average FPS uplift at 1080p with Ultra settings

Would love to try myself but my Intel GPU is borrowed to friend.
