### ISSUE TITLE
Homeworld Remastered Collection - some settings cause the remastered game + multiplayer to crash when loading to map.

### ISSUE THREAD

**Issue by Diomedus94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#624]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Homeworld Remastered Collection

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7 7800X3D

### Graphic Card [Required]

Intel ARC A770 16G LE

### GPU Driver Version [Required]

31.0.101.4953

### Rendering API [Required]

- [ ] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[system.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13552283/system.txt)

### Description and steps to reproduce [Required]

The Texture Quality and Texture Size Limit settings if they are too high they cause the game to crash when loading to the MAP.
Having them the lowest setting possible bring the most stability.
It doesnt affect the Classics HW1 and Classics HW2 only the Remastered HW1, HW2 and Multiplayer (see screenshot lower)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2 560 x 1 440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![homeworld](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/152784041/c58e568d-2773-4176-922b-3771284736fe)
![launcher](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/152784041/91db9398-2918-4780-bfe5-04238279a4eb)
I needet it on windowed it doesnt allow me to take screenshot on fullscreen.

**Comment by Ilya-intel** [comment]
Hi @Diomedus94 ,
I've reported this issue to developers.
I'll keep you updated in this thread.
The BUG ID for reference: 18035643245.

**Comment by Diomedus94** [comment]
Thank you, really appreciate it.

**Comment by Ilya-intel** [comment]
Hi @Diomedus94 ,
We appreciate your report on this matter. Our approach is to concentrate on the widely-used games and applications, dedicating our resources to ensure a superior and reliable experience for a vast user base. Our commitment to enhancing the software's performance and compatibility will persist into 2024 and further. Although we are unable to fulfill your request currently, we encourage you to keep an eye on our website's [article](https://www.intel.com/content/www/us/en/support/articles/000097842.html) for any updates regarding this issue.

**Comment by Ilya-intel** [comment]
@IGCIT 
Please close this thread.
