### ISSUE TITLE
Fallout 4 - low framerate, sometimes stutters, under utillitize GPU

### ISSUE THREAD

**Issue by Diomedus94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#625]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Fallout 4

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7 7800X3D

### Graphic Card [Required]

Intel ARC A770 16G LE

### GPU Driver Version [Required]

31.0.101.4953

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[system.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13606047/system.txt)

### Description and steps to reproduce [Required]

Fallout 4 runs bad, under 60 fps, low framerate and sometimes stutters

Need to use DXVK 2.3-1 GPLasync to run it smoothly.
https://www.reddit.com/r/IntelArc/comments/18d78yg/fallout_4_dxvk_23_gplasync_arc_a770_16g_1440p_win/

After DXVK it can run 120FPS most of the time never drops under 60.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2 560 x 1 440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![fal 4 settings 2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/152784041/9a8e6caa-729e-40df-9a80-4b3d9be4b852)
![fl4 settings 1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/152784041/bfb97c73-aeb1-40b6-8c54-3573f0914f89)

**Comment by Felipe-Intel** [comment]
Hello @Diomedus94 I tested this game with driver 5084 and was able to see 112FPS average at 1080 Low (monitor can only go up to 1080). Can't test in 1440 because my other monitor seems to cap the FPS to 30 at this resolution (still working on it). 
Can you test on your side if the issue still happens with our latest driver? If it still happens, please provide a capframex capture of your gameplay (2 minutes is fine) with this driver and the IGCC report.

**Comment by Diomedus94** [comment]
At this moment i cant test the game, i dont have the GPU installed and i lend it to my friend for him to try it.

But from memory what i can remember the game on 1440p everything on max, 4953 driver, runs bad, like stutters, GPU usage around 60% and framerate wasnt stable only sometimes it reach 60FPS, using DXVK 2.3 + GPLasync it runs better like 120FPS and only few framedrops under 120FPS.

I can ask my friend from Romania if he can try it for me and make a video but you can try it yourself.

Here is what testing methodology i propose.
- use 1080p if you have only that resolution monitor
- crank every game setting on maximum that will make sure that your GPU will be occupiend
- use intel ARC control monitoring tool to see what kind of GPU ulitization you get  
- use Steam launucher FPS monitor to see what kind of FPS you get
- if GPU utillization is under 90%, the game stutter and cant mantain stable 60FPS then it is for sure driver optimalization

Then you can try my DXVK guide on this github post that will redirect you to reddit and see what kind of performance you get.

I know this is not standart procedure and it would normally not be problem for me to recreate the performance issue in a few minutes.

**Comment by Felipe-Intel** [comment]
Noted. I will try and let you know.

**Comment by Felipe-Intel** [comment]
@Diomedus94 Issue has been reported to our development teams under bugID 14021274061. I'll come back to you when I have news about this.

**Comment by Felipe-Intel** [comment]
Hello @Diomedus94 
This issue should not be seen with the recent driver releases. Could you please check on your side with our latest driver [101.5382](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)?

**Comment by Felipe-Intel** [comment]
Closing this thread due to inactivity.
