### ISSUE TITLE
Unreal Tournament 2004: "Please enable Direct3D acceleration" in D3D8 mode, works with the buggy OpenGL Renderer

### ISSUE THREAD

**Issue by Pawlicker** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#626]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Unreal Tournament 2004

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

GOG

### Processor / Processor Number [Required]

AMD Ryzen 5800x

### Graphic Card [Required]

Intel ARC A750

### GPU Driver Version [Required]

31.0.101.4972

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[intellog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13608542/intellog.txt)

### Description and steps to reproduce [Required]

When launching UT2004 without modifying files or using DXVK, the game simply generates an error if the ini file is not modified to use the OpenGL renderer, which is known to have bugs with stencil lighting, blobs, among other things. Using d8vk also allows the game to launch and render properly.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92184373/1824d76c-fa2c-4252-8539-993b249d8eb7)

Log: Log file open, 12/07/23 22:14:41
Init: Name subsystem initialized
Init: Detected: Microsoft Windows NT 6.2 (Build: 9200)
Init: Version: 3369 (128.29)
Init: Compiled: Nov 23 2005 16:23:34
Init: Command line: 
Init: Character set: Unicode
Init: Base directory: C:\GOG Games\Unreal Tournament 2004\System\
Init: Ini:UT2004.ini   UserIni:User.ini
Init: Build label: UT2004 Build UT2004_Build_[2005-11-23_16.22]
Init: Object subsystem initialized
Log: Splash screen filename is '..\Help\UT2004Logo.bmp'
Log: 	igdumdim32.dll/Intel(R) Arc(TM) A750 Graphics
Log: 	igdumdim32.dll/Intel(R) Arc(TM) A750 Graphics
Critical: Please enable Direct3D acceleration. You can do this by starting dxdiag and enabling Direct3D Acceleration in the Display1/2 tab after installing DirectX 8.1b (or later) and the latest drivers for your graphics card.
Critical: Windows GetLastError: The operation completed successfully. (0)
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing UWindowsClient::ShutdownAfterError
Critical: GetDeviceCaps
Critical: UD3DRenderDevice::Init
Critical: UGameEngine::Init
Critical: InitEngine
Critical: FMallocWindows::Free
Critical: FMallocWindows::Realloc
Critical: 0000016B 0 FArray
Critical: FArray::Realloc
Critical: 0*2
Critical: FMallocWindows::Free
Critical: FMallocWindows::Free
Exit: Exiting.
Log: FileManager: Reading 0 GByte 16 MByte 324 KByte 740 Bytes from HD took 0.057000 seconds (0.041000 reading, 0.016000 seeking).
Log: FileManager: 0.006000 seconds spent with misc. duties
Uninitialized: Name subsystem shut down
Uninitialized: Log file closed, 12/07/23 22:14:43

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

Cannot set

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Default ut2004.ini

**Comment by Karen-Intel** [comment]
Hey @Pawlicker can you share where to download the game from?

Ty

Karen

**Comment by yawnbunny** [comment]
Try version 5074, it came out just some hours ago and it fixed my issues with most D3D8 games, including Unreal Engine titles.

**Comment by Pawlicker** [comment]
> Hey @Pawlicker can you share where to download the game from?
> 
> Ty
> 
> Karen

You can't buy it anymore digitally, only on eBay.
https://www.ebay.com/sch/i.html?campid=5338192028&kw=unreal%20tournament%202004&mkcid=1&mkrid=711-53200-19255-0&toolid=20004

I did just try 5074 and the game now works perfectly. Here's a log of it launching. 
[UT2004.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13609337/UT2004.log)

**Comment by Karen-Intel** [comment]
Wonderful! Thank you for confirming guys!
