### ISSUE TITLE
GPD Win Max 2021 (1195G7) No Display Out of Sleep (S3 or Modern Standby) on Drivers 5074 and Newer

### ISSUE THREAD

**Issue by ReddestDream** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#627]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 11 (Entire OS/Any App)

### Processor / Processor Number [Required]

1195G7

### Graphic Card [Required]

Intel Iris Xe

### GPU Driver Version [Required]

31.0.101.5074

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

Can get later if necessary. Device is currently downgraded to 4972 to avoid losing display. Device is on latest BIOS (1.18).

### Description and steps to reproduce [Required]

Attempt to put GPD Win Max 2021 to sleep (S3) on the new 5074 driver. Internal screen never comes back on (stays black). No way to get internal display back on. External display out still works, so nothing has crashed. 5074 likely cannot turn the MIPI display on the Win Max 2021 back on out of sleep correctly. Downgrading to 4972 corrects this issue and the display comes back on out of sleep as expected. I have had one other person on the GPD Discord confirm, but I am looking for further confirmation. Thanks!

### Device / Platform

GPD Win Max 2021

**Comment by ReddestDream** [comment]
This issue also occurs on 5081. I've attached an SSU from while the issue is actively occurring (no main display). I have an external display attached over HDMI so that I can see after testing sleep since the internal display doesn't come back on. Thanks!
[SSU GPD WIN MAX 2021 5081.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13697292/SSU.GPD.WIN.MAX.2021.5081.txt)

**Comment by ReddestDream** [comment]
I've also attached the SSU from the system downgraded to 4972 with working internal display after it was kicked back on. Thanks!
[SSU GPD WIN MAX 2021 4972.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13697407/SSU.GPD.WIN.MAX.2021.4972.txt)

**Comment by ciphray** [comment]
this also occurs with modern standby

**Comment by ReddestDream** [comment]
Got more info that this also occurs if you use Modern Standby instead S3. Modern standby doesn't work properly on the Win Max 2021 since the fans never go off, but, nonetheless, using it doesn't fix this issue.

**Comment by ReddestDream** [comment]
This issue is likely to affect the Tiger Lake Win 3 as well, but I don't have one and I don't have any confirmation.

**Comment by ReddestDream** [comment]
Confirmation that this issue doesn't seem to affect TGL devices that do not have MIPI displays.

**Comment by Felipe-Intel** [comment]
Hello @ReddestDream have you tried drivers 5081 and/or 5084? We are still looking for a device the meet the handheld characteristics. We tried a couple of TGL systems but this issue doesn't happen on those, as you say, probably because those don't have direct-connect MIPI display.

**Comment by ReddestDream** [comment]
Thanks for getting back and investigating! I have not had a chance to test 5084 yet, but I'm hoping to do so later this week. I agree based on what I've heard from others that a direct-connect MIPI display is likely going to be necessary to reproduce the issue. Thanks again!

**Comment by ReddestDream** [comment]
I have now tested 5084, and it has the same issue as 5074 and 5081. @Felipe-Intel Thanks!

**Comment by Felipe-Intel** [comment]
@ReddestDream after a more search, we haven't found yet a system with similar characteristic to your device. 
Have you contacted [GPD Support](https://www.gpd.hk/fw) for this issue? If you haven't, please report this to them and if they determine it is something with the driver itself, they can come to us with their debug results. Does that make sense to you? I'll keep this thread open until you get an answer from them. In the meantime, I'll keep looking for help here.

**Comment by ReddestDream** [comment]
Yeah. I'll reach out to GPD about this. It's been working for years though, but I will admit they did have to do a BIOS update a few months after release to fix Intel Graphics driver issues causing the exact same problem at that time. Might be time for another one if they can still do it . . . Just because you are the only one using some feature doesn't mean you get to set the spec.

S3 wake worked on Linux last I check, but it only started working correctly in the last year or so. I'll test that and 5085 and get back to you with more info. If I can find the commit and/or those responsible for the fix on the Linux, that may help as well.

Thanks!

**Comment by Felipe-Intel** [comment]
Thanks for all your help with this @ReddestDream. I will proceed to close this thread. After you get info from the OEM, if you need anything from us, feel free to open a new case and refer to this one. I would recommend to [open a web ticket](https://www.intel.com/content/www/us/en/support/contact-intel.html) and mention this case there, and share the case number here (I think you can re-open this one? if not go ahead and create a new one).
