### ISSUE TITLE
Can't launch Detroit Become Human at all

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#628]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Detroit: Become Human

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

31.0.101.4953

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 08.12.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13619443/Intel.SSU.08.12.2023.txt)

### Description and steps to reproduce [Required]

Not much to say, it just shows this error when trying to launch it. Maybe it's a driver regression, not sure, because the game was able to run before. I tried to restart my computer, verify files and reinstall the game
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/b4dfbeff-b5b9-4cd2-8559-dd1c2c02f634)

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

I don't remember, maybe Medium

### Device / Platform name

ASUS PRIME Z790-P WiFi D4

**Comment by Karen-Intel** [comment]
@TheWonderfulTartiflette hello again!

The game is launching fine for me, I finished the first mission playing for about 20-25 minutes

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/18028839-af13-4972-a437-e3b413262bef)

Here are my graphics settings and everything else is in low quality

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/4d444199-49f8-491b-afc8-fdc52143bf8f)

Can you share your game settings please? Thanks

Karen

**Comment by Diomedus94** [comment]
@TheWonderfulTartiflette try install latest drivers 31.0.101.5074 with uninstalling older drivers with DDU software in windows safe boot minimal
https://pureinfotech.com/start-windows-11-safe-mode/
https://www.guru3d.com/download/display-driver-uninstaller-download/
@Karen-Intel he cant show you his settings what i understant what he mean that he cant even start the game, for what i saw in Intel ARC subreddit this is problem for most of the peoples.

**Comment by Diomedus94** [comment]
@TheWonderfulTartiflette i have a question, any chance you have installed Armoury Crate because you are running ASUS motherboard, the software is piece of trash and can cause games to suddenly stop working on Intel ARC cards.
If YES then go to BIOS and disable it and then uninstall it.
https://www.asus.com/support/FAQ/1043788/

**Comment by TheWonderfulTartiflette** [comment]
@Diomedus94 Nope, even with 5074, the issue persists. And no, I already disabled Armoury Crate

@Karen-Intel I'm not sure that I'm able to do that, because my game doesn't launch, so no screenshot available. All I remember was that FidelityFX sharpening was on, resolution scale at 1.00, FPS Limit at 60, 1080p, and somewhere around medium settings

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44057002/157ba85c-ae6f-4162-898e-5a8d574f5c26)

**Comment by Karen-Intel** [comment]
> @Diomedus94 Nope, even with 5074, the issue persists. And no, I already disabled Armoury Crate
> 
> @Karen-Intel I'm not sure that I'm able to do that, because my game doesn't launch, so no screenshot available. All I remember was that FidelityFX sharpening was on, resolution scale at 1.00, FPS Limit at 60, 1080p, and somewhere around medium settings
> 
> ![image](https://private-user-images.githubusercontent.com/44057002/289268942-157ba85c-ae6f-4162-898e-5a8d574f5c26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTUwMjgsIm5iZiI6MTcwMjMxNDcyOCwicGF0aCI6Ii80NDA1NzAwMi8yODkyNjg5NDItMTU3YmE4NWMtYWU2Zi00MTYyLTg5OGUtNWE4ZDU3NGY1YzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE3MTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4OTFhZmRjMjA4NjdlNzQwM2E4MWNkMDRhMzE2NjE1ZjU4M2I3MjI3NmU0MTEyNjg4ZDhkM2UyZDFlNTcwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ws4vqQ3Y0Y_fcYOsEg78IpA5oyA7AU23MJ5K1aASDbg)

Okey, let me try with those settings and see if I can repro the game not launching at all!

Karen

**Comment by Karen-Intel** [comment]
@TheWonderfulTartiflette update

Game launches for me with 60FPS, 4K resolution and medium settings

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/6dd9d21a-b00b-4923-8f1c-ba36947948b2)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/91162218/43bbf5fc-fe0b-435c-af13-6352a7883f60)

We can wait until someone else reports it through this week but I'd rather make sure to delete every file from the game and reinstall until shaders build one more time. 
I'm using Steam so perhaps someone who has the game on Epic could check? Because on Steam it launches just fine

Karen

**Comment by Diomedus94** [comment]
@Karen-Intel try turning this ON
"FidelityFX sharpening was on, resolution scale at 1.00"
![289621289-43bbf5fc-fe0b-435c-af13-6352a7883f60](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/152784041/ccccad79-3e80-49ee-8b71-1d682ca0f9a9)


@TheWonderfulTartiflette  try to remember what you installed our updated in the time when the game stops working

**Comment by Diomedus94** [comment]
@Karen-Intel https://community.khronos.org/t/what-cause-vk-error-device-lost-error/7474
This is older problem with Vulkan, many peoples had this problem it looks like some driver execution of vulkan but i am not the guy to judge here the problem, on IntelARC subreddit many peoples had problem with this on Detroit Become Human, i can ask there for how many peoples have this problem.

**Comment by Karen-Intel** [comment]
Hi @Diomedus94 thank you! That would be very helpful. We also need hw specs and exact steps to trigger the Vulkan error and if it's happening on other platforms (Steam, Epic). I'd gladly submit the issue internally but I need to be able to repro it first. 
Thanks in advance for your help

Karen

**Comment by IGCIT** [comment]
@TheWonderfulTartiflette for issues like this, it may help to upload your game settings file (removing sensitive data, if any, like ids, etc..), so that it can be imported to test the game with your exact (or almost exact) settings

see [pcgamingwiki](https://www.pcgamingwiki.com/wiki/Detroit:_Become_Human) for file paths

**Comment by TheWonderfulTartiflette** [comment]
@IGCIT Oh sure, thanks. Unfortunately, I wasn't able to locate the graphic settings file, most probably because the game hasn't really been launched since I reinstalled it. I was able to get the save game, hopefully taken from Epic's cloud and not empty, and a basic WindowInfo JSON file : https://drive.google.com/drive/folders/1bkjCaleuQglRxCrQjvIxF1-6LZtUrm8N?usp=sharing

**Comment by Diomedus94** [comment]
@TheWonderfulTartiflette 
![detroit](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/152784041/aaa48ae6-88f0-40e9-953f-dd6e6a69a06b)

there is little note1 on the right upper corner and it contais this below

When running this game without elevated privileges (Run as administrator option), write operations against a location below [%PROGRAMFILES%](https://www.pcgamingwiki.com/wiki/Glossary:Game_data#Shared_applications), [%PROGRAMDATA%](https://www.pcgamingwiki.com/wiki/Glossary:Game_data#Shared_application_data), or [%WINDIR%](https://www.pcgamingwiki.com/wiki/Glossary:Game_data#Windows) might be redirected to [%LOCALAPPDATA%](https://www.pcgamingwiki.com/wiki/Glossary:Game_data#User_application_data)\VirtualStore on Windows Vista and later ([more details](https://www.pcgamingwiki.com/wiki/Game_data#Installation_folder)).

**Comment by Diomedus94** [comment]
@Karen-Intel this second thread is directly from intel subbreddit i just crossposted it from intelARC some peoples give their findings there

https://www.reddit.com/r/intel/comments/18g1fsk/detroit_become_human_intel_arc_question/

![detroit](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/152784041/42114ff9-404d-4945-8201-225dd5e4be8b)

**Comment by IGCIT** [comment]
> @IGCIT Oh sure, thanks. Unfortunately, I wasn't able to locate the graphic settings file, most probably because the game hasn't really been launched since I reinstalled it. I was able to get the save game, hopefully taken from Epic's cloud and not empty, and a basic WindowInfo JSON file : https://drive.google.com/drive/folders/1bkjCaleuQglRxCrQjvIxF1-6LZtUrm8N?usp=sharing

ok, this can actually be a way to reproduce, supposedly it is loading its defaults if no config file is present (that are causing the crash)

you may also want to check for a ShaderCache folder in game install folder (or other game folders) and delete it

**Comment by Karen-Intel** [comment]
@TheWonderfulTartiflette like IGCIT mentions and other users, local configuration might be causing issues for the game to even launch in some machines, but it launches on others (like mine, for instance). 
The game does launch, which has been confirmed for other users in Reddit.

Now about the performance posts on Reddit, @Diomedus94 thank you for all your research! 
We agree that in most cases the game is playable but with bad performance 
We actually have an internal report for that. #15014746133, FYI :) and our dev team is already looking into it.

Karen

**Comment by TheWonderfulTartiflette** [comment]
Okay so, for some reason, this had to do with Epic Games crashing when DBH is launched. I guess it crashes, and makes the GPU do weird things, which causes Vulkan to think that the GPU has been disconnected. Now, when closing Epic Games and launching the game straight from the .exe, it works. Thanks for the help all though :)
Whatever's happening, I think the GPU's at fault here, because I don't think an app crashing should cause Vulkan to think that the GPU has been disconnected

**Comment by TheWonderfulTartiflette** [comment]
Btw for the bad performance issue, I noticed that (for my part) depth of field severely impacts performance

**Comment by Arturo-Intel** [comment]
Do we have a case for the performance posts on Reddit? 
so we can track it separately ? @Karen-Intel

**Comment by TheWonderfulTartiflette** [comment]
Sorry, forgot to close this case, it's resolved now 👍
