### ISSUE TITLE
Deus Ex Mankind Divided D3D12 problem (transparent surfaces?)

### ISSUE THREAD

**Issue by donizettilorenzo** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#629]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Deus Ex Mankind Divided

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i3 8300

### Graphic Card [Required]

ARC A380

### GPU Driver Version [Required]

31.0.101.4972

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [x] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13619846/ssulog.txt)

### Description and steps to reproduce [Required]

Just walk around in the first part of System Rift DLC 

![DXMD_2023_12_08_19_25_40_826](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1938669/6d8c4dca-69a8-47f8-92ef-d0d277f8cfae)
![DXMD_2023_12_08_19_25_48_284](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1938669/cc0ae953-5788-4c08-85b5-b9399b1f09ba)
![DXMD_2023_12_08_19_32_20_901](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1938669/bfc5751b-18f1-45af-b436-f761c59acaa4)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![Senza titolo](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1938669/b4517a81-28e5-4a02-9e74-7741369333b6)

**Comment by donizettilorenzo** [comment]
Just updated to just released 5074, problem is always there:

![DXMD_2023_12_08_20_19_51_651](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1938669/81f6d619-b8fc-465f-af37-c788bb187a2a)
![DXMD_2023_12_08_20_20_41_051](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1938669/ee174dbd-7322-4fe5-be1a-996a176b7048)

**Comment by Vivek-Intel** [comment]
@donizettilorenzo Thanks for reporting the issue. We have created internal bug id for this issue ( 16022812891 for your reference)
We will update as we hear more about the progress on the issue.

**Comment by toriko2** [comment]
For me at least, this issue can be mitigated by setting Game Compatibility to Advanced in the Arc Control panel

**Comment by donizettilorenzo** [comment]
It would be awesome if Intel will explain the difference among all compatibility modes!

**Comment by donizettilorenzo** [comment]
> For me at least, this issue can be mitigated by setting Game Compatibility to Advanced in the Arc Control panel

I can confirm "advanded" profile solves the transparency issue but NOT the "moving tiles" one on some surfaces:

![DXMD_2024_01_13_15_44_33_089](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1938669/13453a8c-ae2b-45cb-826f-d5b11d525e10)

**Comment by Vivek-Intel** [comment]
@donizettilorenzo we had reported this issue to our development team internally  but our priority is to target the most popular games and apps to focus our efforts on providing a high quality, stable experience for the broadest set of users. 
We will continue to improve our software performance and compatibility throughout 2024 and beyond. While we can’t accommodate your request at this time, please watch [this article](https://www.intel.com/content/www/us/en/support/articles/000097767/graphics.html) on our website for any possible changes to this situation.

Appreciate your efforts to find and report this issue.

**Comment by Vivek-Intel** [comment]
@IGCIT please help close this issue.
