### ISSUE TITLE
MegaMan X Legacy Collection 1 and 2 Low performance/BlackScreen

### ISSUE THREAD

**Issue by Saracchini** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#63]
#### Checklist [README]

- [x] Device is not undervolted nor overclocked.
- [x] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [x] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]

MegaMan X Legacy Collection 1 and 2 
---
#### Game Platform [Required]
- [x] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
---
#### GPU Driver Version [Required]
- [ ] 27.20.100.9616 (*latest*)
- [x] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [x] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [x] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

Game has very low performance (30-40 fps), when in older Intel CPUs performance is OK (stable 60 FPS).

1. Init the game
2. Choose either windowed mode or borderless fullscreen
3. Performance is 30-40 fps variable. Bellow the expected game speed (when run 60 fps, game is slowed down severly)
4. 50fps can be reached by disabling fullscreen optimization, starting in borderless fullscreen and switching to fullscreen exclusive
5. That leads to the black screen issue

Black Screen

1. Disable full-screen optimizations (screen is blurry otherwise) 
2. Configure game to use FullScreen exclusive mode
3. Start game
4. Black screen with sounds is shown.
5. Screen is displayed if ALT+TAB is done. Performance is low, however (30-40 fps)

---
#### Device / Platform [Optional][Recommended]

GPD WIN3 i7 16 GB

---
#### Game Settings [Optional][Recommended]

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---

**Comment by RSaracchini** [comment]
Tested with latest beta version: 30.0.100.9667
Issue still persists.

**Comment by RSaracchini** [comment]
Using the following config settings solves the full-screen issue as well the slow down. Game run at 60 fps if these settings are used in the **config.ini**  configuration file :
```
[Render]
PCTargetAPIFallback=Disable
Capability=DirectX12
TargetPlatform=DirectX11
UseDXILShader=Disable
UseOptimizeShader=Enable
LastCrashReport=
UseVendorExtention=Enable
[RenderConfig]
WindowMode=1
VerticalSync=0
GraphicsRendering=2
Resolution=2
RefreshRate=0
```

**Comment by craiggx** [comment]
Hi there, I have some questions about the black screen issue:
Does this happen when you attach an external display to your GPD WIN3?
If so, what adapter are you using to connect to your external display?
Does the black screen happen when you're using only the GPD Win3's display with nothing else connected?

**Comment by Saracchini** [comment]
@craiggx 
No external screen plugged in at all. It is using the Win3 screen solely.
I disabled "Fullscreen optimizations" option in the executable Compatibility Tab since otherwise the game is very blurry. Black screen happens if you set the game to use Fullscreen (not borderless) in game (from other mode like Windowed/Borderless), and open it with this configuration saved. It will be a black screen until you ALT+ENTER the game. 

If you enable "Fullscreen optimizations" option in Compatibility Tab (right-click executable, select properties, in Compatibility). The game runs with worse performance and very blurry when in fullscreen.

**Comment by estebanr863** [comment]
Hi @Saracchini,

After debugging this issue, we discarded the root cause to be Intel's graphics driver. We suspect the issue is caused because the "Full Screen Optimizations" are being disabled. We understand that this was done as a workaround to another issue specific to your device, but we see no issues on other systems using the same CPU and have the "Full Screen Optimizations" enabled. Our only advise going forward is for you to contact the support team of your device manufacturer, as this issue seem to be specific to your device.

**Comment by Saracchini** [comment]
I think so. About the bug I mentioned, it is is not related to the black screen issue.
For me this issue can be closed.
