### ISSUE TITLE
Prey (2017) glitches

### ISSUE THREAD

**Issue by donizettilorenzo** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#630]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Prey (2017)

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i3 8300

### Graphic Card [Required]

ARC A380

### GPU Driver Version [Required]

31.0.101.5074

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13625826/ssulog.txt)

### Description and steps to reproduce [Required]

Just rotate the camera and you'll see shotgun ammo number disappears and other glitches in the scene (see the glass surfaces of the rooms):
![0](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1938669/864f4754-3d2a-4f70-89d7-b282a91eaebe)
![1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1938669/7f0087c6-58ee-478d-a7d3-d059c840604b)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![Prey_2023_12_09_23_22_45_159](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1938669/f01d217f-80cf-4b06-8e7c-36fc91c3bdba)

**Comment by donizettilorenzo** [comment]
Other examples (just rotating the camera)

![0](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1938669/e7691f7d-fa25-4579-90cd-ef7194505d5c)
![1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1938669/2e039ac4-34a7-4742-a78b-2127e0065cbb)

**Comment by Ilya-intel** [comment]
Hi @donizettilorenzo ,
I've just tested a few A380 cards with Prey and didn't see any issues.
Could you try to use DDU to reinstall drivers?

**Comment by donizettilorenzo** [comment]
The driver is correctly installed and the problem presents itself just rotating the camera and it has perfectly deterministic behaviour.

**Comment by donizettilorenzo** [comment]
Level is "Shuttle Bay". Maybe it's a specific level issue.

**Comment by donizettilorenzo** [comment]
Yes, it's a specific level issue and not Intel only: https://www.reddit.com/r/prey/comments/i7mmhn/visual_glitch_in_shuttle_bay_any_idea_how_to_fix/

**Comment by Ilya-intel** [comment]
> Yes, it's a specific level issue and not Intel only: https://www.reddit.com/r/prey/comments/i7mmhn/visual_glitch_in_shuttle_bay_any_idea_how_to_fix/

In this case I'd recommend reporting it to the game devs.

**Comment by Arturo-Intel** [comment]
Please feel free to open a new case if this behavior evolves to something Intel specific.
Closing this issue.
