### ISSUE TITLE
The problem with rendering 

### ISSUE THREAD

**Issue by Pashamolochko** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#631]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

game warface and Hunt: Showdown

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

steam

### Processor / Processor Number [Required]

i3 13100

### Graphic Card [Required]

intel arc a770

### GPU Driver Version [Required]

31.0.101.5074

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

![O92BxI-2aS4](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/2a2797d7-8a99-4ba3-bee3-e40cacf3b4a3)

### Description and steps to reproduce [Required]

The problem with the render in the game warface and Hunt: Showdown, it happens as indicated in the screenshot, and in the game Hunt: Showdown the FPS is quite low, both games are on the CRYENGINE - Crytek"s engine, the graphics setting does not really change anything, there is no focus on the processor

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1920

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Similar behavior on all graphics settings
![O92BxI-2aS4](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/020745e6-53bb-40ed-9e86-83484ca07807)

### Device / Platform name

LGA 1700

**Comment by Pashamolochko** [comment]
![sd2T5Zi08zU](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/63663ec6-6338-4f90-aa4a-a47d24a9b259)

**Comment by Pashamolochko** [comment]
the problem is solved by turning on shaders in the game, only the low FPS in the hunt showdown game remains

**Comment by Vivek-Intel** [comment]
> the problem is solved by turning on shaders in the game, only the low FPS in the hunt showdown game remains

@Pashamolochko Can you please help provide what is avg FPS you are getting with latest drivers ? and also observe CPU and GPU usage 
Also can you check below few setting and see if you get any FPS improvements.
Turn of pass lighting and screen rendering from advance settings, if FPS does not improve try turning on GPU tessellation and let us know your observation.

**Comment by Pashamolochko** [comment]
> > проблема решена включением шейдеров в игре, остается только низкий фпс в игре охота разборки
> 
> @PashamolochkoПодскажите, пожалуйста, какой средний FPS вы получаете с последними драйверами? а также наблюдать за использованием процессора и графического процессора. Также вы можете проверить несколько настроек ниже и посмотреть, получите ли вы какие-либо улучшения FPS. Включите проходное освещение и рендеринг экрана в дополнительных настройках. Если FPS не улучшится, попробуйте включить тесселяцию графического процессора и сообщите нам о своих наблюдениях.

77 fps on average, how do I enable GPU tessellation?
CPU utilization is 30-40%,GPU utilization is 50-70%,video card consumption is from 100 to 160 watts

**Comment by Vivek-Intel** [comment]
> Hunt: Showdown

you will find it under Advance option under graphics setting in the game. please check with toggle on/off it. I have some problem launching this game, will update once I troubleshoot it.

**Comment by Vivek-Intel** [comment]
@Pashamolochko we are looking into low FPS in hunt showdown game, will update once I hear news on this one.

**Comment by Vivek-Intel** [comment]
@Pashamolochko latest driver ([101.5186](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)) has made some improvements for fps in hunt showdown, please help check with this driver.

**Comment by Pashamolochko** [comment]
> @PashamolochkoПоследний драйвер ( [101.5186](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) ) внес некоторые улучшения в частоту кадров при охоте, пожалуйста, помогите проверить этот драйвер.

Hello, the frame rate has increased by the new driver announced in the release, thank you very much for the work done

**Comment by Vivek-Intel** [comment]
Thank you @Pashamolochko for confirmation , please help close this as completed
