### ISSUE TITLE
CMAA2 in Post Processing tab

### ISSUE THREAD

**Issue by donizettilorenzo** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#633]
### Application [Required]

All

### Processor / Processor Number [Required]

All

### Graphic Card [Required]

All Xe based GPUs (ARC and iGPUs)

### Rendering API [Required]

- [X] Vulkan
- [X] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

CMAA2 in Post Processing tab, just it was before.
Thanks!

**Comment by BiZkViT96** [comment]
I noticed it too, but I use iGPU and thought they made it exclusive to discrete GPUs.

**Comment by Gabriela-Intel** [comment]
Thanks for the feedback! I'll pass along the feedback to the team. 

@IGCIT Please close.

**Comment by donizettilorenzo** [comment]
Anisotropic Filtering forcing too is now disappearead.
Please make it return!
