### ISSUE TITLE
Windows Update always downgrade the driver for my iGPU UHD770 everytime I install a new intel GPU driver

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#634]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 10

### Processor / Processor Number [Required]

intel Core i5-13500

### Graphic Card [Required]

intel Arc A770
intel UHD Graphics 770

### GPU Driver Version [Required]

31.0.101.5074

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU_20231211.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13635295/SSU_20231211.txt)

### Description and steps to reproduce [Required]

I have both Arc A770 and UHD770 working on my PC. Every time I installed a new driver, Windows Update would just reinstall a very old version of driver for the iGPU. It left the driver of the A770 untouched, though. I can use the "Roll Back Driver" feature in the Device Manager and then the driver will be recovered to the latest version I just installed, but it's just so annoying. This has happened countless times ever since I started using both GPUs together. If I disable the iGPU in the BIOS then there's no such a problem, but why can't I enable my iGPU in the first place? Especially that intel advertises "DeepLink" as a great feature.

### Application / Windows logs

[Desktop.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13635336/Desktop.zip)

**Comment by akarnokd** [comment]
This has been happening to me ever since I built my computer fresh in February 2023. Windows 11 22H2. I followed several guides to prevent this from happening with no joy.

- I disabled the Windows settings to download drivers -> still happening.
- Hide KB update -> It doesn't show up in the optional updates in general, only after it has been applied and can no longer be hidden.
- Edit policy -> Not available in W11 Home?

Doesn't matter if I have WHQL or Beta drivers, when Patch tuesday comes, I get a downgrade.

It is definitely a long standing Windows Update bug (which could affect other brands too) and apparently the kind MS is not reluctant to acknowledge or fix.

**Comment by Susie1818** [comment]
> having said that, this is windows bad behaviour, this is actually a ticket for windows

I don't think it's 100% Windows' responsibility. Why doesn't intel forward the latest driver version to Windows Update's data center? If intel lets Windows Update's server to be aware of the driver version up to date, then it wouldn't make such a mistake.

**Comment by Arturo-Intel** [comment]
It depends a lot on Windows QA procedures, we are sending newer version of the drivers to them, but it is on their hands if they use it or not.

-- r2

**Comment by ValeZAA** [comment]
>it should never came back in windows update (at least never happened to me)

After using windows update show/hide tool it hides and then eventually comes back. Unfortunate.
