### ISSUE TITLE
Remember Me blackouts

### ISSUE THREAD

**Issue by ewahl-osc** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#635]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Remember Me

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

ryzen 5800x3d

### Graphic Card [Required]

predator A770

### GPU Driver Version [Required]

31.0.101.5074

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssi.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13655311/ssi.txt)

### Description and steps to reproduce [Required]

Under a couple of previous, and the current, driver there are full screen dropouts during gameplay.

Using DXVK 2.3 does fix this and you just drop from 100-120fps to 20 briefly instead. 

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

any

**Comment by ewahl-osc** [comment]
Did not attach screens as full black screen not exactly interesting/capture-able

**Comment by freak2fast4u** [comment]
Same issue here with FF XV : https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/580#issuecomment-1850859905 , and another user is reporting blackouts during fullscreen video playback. I myself also encounter these blackouts under linux so it's driver independent, more likely VBIOS or firmware issue, considering this issue has only cropped up "recently" (somewhere around VBIOS 20.0.1068 rollout date, but we're not sure). 

Do you happen to have an Agon/AOC monitor by any chance ? Maybe Karen from Intel is into to something.

**Comment by IGCIT** [comment]
@Karen-Intel usually added to ssu, line 3464, [Optix MAG27CQ](https://www.msi.com/Monitor/Optix-MAG27CQ/Specification)

**Comment by ewahl-osc** [comment]
MSI Optix MAG27CQ normally at 2560x1440 @ 144Hz for everything I can.
Using DP with a spec 1.4 cable

**Comment by Vivek-Intel** [comment]
@ewahl-osc I tried with Remember Me but could not see any blackout so would appreciate if you can provide some more information:
1: Can you try with latest driver : 101.5081_101.5122
2: If you see issue in above driver, try disabling freesync from display OSD menu and disable VRR from Intel graphics command center
3: is there any specific part in game you see the issue or is it random that can occur anywhere in the begining also ?

**Comment by freak2fast4u** [comment]
I didn't immediately connect the dots regarding the blackouts, but it looks more like this issue instead : https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/638.

Does it look like this (same link as in my comment from yesterday) ? https://youtu.be/8VpjDha1FhE

**Comment by Vivek-Intel** [comment]
@ewahl-osc I could not reproduce issue even once during episode 0 and 1. I would give it a try on AMD + Intel Arc setup see if it is something very specific to it.

**Comment by Vivek-Intel** [comment]
> @ewahl-osc I could not reproduce issue even once during episode 0 and 1. I would give it a try on AMD + Intel Arc setup see if it is something very specific to it.

no blackout on amd+a770 setup as well. I think we would need more specifics on how to reproduce it.

**Comment by ewahl-osc** [comment]
I've not had this issue again in the last 2 driver updates, with or without dxvk in use.  Currently using 5084/5122
