### ISSUE TITLE
Game shines through a sliver on the edge of a Youtube video in Chrome

### ISSUE THREAD

**Issue by akarnokd** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#636]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Chrome + Youtube.com

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

31.0.101.5074

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13659822/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Noticed this since driver 4887. When I have a game open in Borderless Window mode and have a youtube video open, the game shines through on a sliver on the right side of a video.

Desktop resolution: 1920 x 1080, 125% scaling
Youtube video set to Movie mode.
Chrome: 120.0.6099.71 (Hivatalos verzió) (64 bites), but happening since months. Hardware acceleration on.

Game I noticed this (but probably not limited to): Starfield (including 1.8.88.0) DX12, Ship Graveyard Simulator 2 (including 6129) DX11.

https://www.youtube.com/watch?v=Orp6gv-aRLo

**Comment by akarnokd** [comment]
FYI, Still present with 5081 (Installed after safe mode DDU) & 120.0.6099.110

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13684739/igcit_ssu.txt)

**Comment by Ilya-intel** [comment]
@akarnokd 
This issue seems to be related to the browser itself and not to gfx drivers. I've tested on Nvidia and the behavior is the same (see below). So I'd recommend to reach out to Google support.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/d503f10a-873a-4a9a-b675-526e0134a9ed

**Comment by akarnokd** [comment]
Thanks. Will do.
