### ISSUE TITLE
Persona 5R rendering issue when using DXVK.

### ISSUE THREAD

**Issue by BuyMyMojo** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#639]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Persona 5R + DXVK

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD 5900x

### Graphic Card [Required]

A770

### GPU Driver Version [Required]

31.0.101.5074

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU_2023-12-14.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13671772/SSU_2023-12-14.txt)

### Description and steps to reproduce [Required]

When using DXVK to run P5R with Vulkan the menus get a distinct glitchy look which was confirmed by the DXVK support to not be an issue on other cards: https://github.com/doitsujin/dxvk/issues/3745 (Check this issue if you want to get a Apitrace file)

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/19d4f621-ab3c-498d-9569-32eb2fbd46b7

Instructions:
- Download the latest DXVK [artifacts](https://github.com/doitsujin/dxvk/actions/runs/7060498159)
- Extract `d3d11.dll` and `dxgi.dll` next to the Persona 5 executable
- load save slot 16 (provided bellow)
- Press Square on PS4/5 controller or `N` on keyboard to open the messaging app
- close menu with Circle on PS4/5 controller or `C` on keyboard
- open pause menu Trianle on PS45 controller or `Tab` on keyboard
- navigate to System > Config > Graphics settings

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Any as this affects the menu which isn't affected by quality settings

### Save game

Extract the `DATA16` folder into `%APPDATA%\SEGA\P5R\Steam\<user-id>\savedata\` then it'll under the save slot 16 of course

[DATA16.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13671837/DATA16.zip)

**Comment by LancerDawg75** [comment]
I can't see your video for some reason, but I have seen this when I wanted to try P5R under Vulkan, but I really didn't need it as it seems to run fine for me under DX11. 

Although, I'm not running it at 1440p. I'm running it at 1080p with 200% render scale (so, internally....2715x1527) and limited to 60fps.

If you're running it at 1440p native and have the same render scale setting (for you, at 200%, it would be 3620x2036), you might removing dxvk and running it with a lower render scale setting.

**Comment by BuyMyMojo** [comment]
I am running at native 4K trying to hit 120fps, DXVK helps keep it a little higher at least.

This should fix the video:


https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/c2a8edbd-68b7-45d6-826e-155b608b93dd

**Comment by LancerDawg75** [comment]
Yeah, that's the same behavior I saw when I was running DXVK, and trying DXVK Async to see if anything would change. 
I had not tried to see if I would see anything different if I applied the gplasync environment variable, but I doubt it would change anything.

**Comment by rmorera-intel** [comment]
Hello everyone, I just tested this with driver [32.0.101.6130](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) and I cannot see the graphics corruption when running the game with DXVK. More so, we introduced performance improvements and I ran the game at 1440p High presets and got consistent 120fps so DX11 is back at the table in case you want to consider it.

Please try it out.

**Comment by rmorera-intel** [comment]
I'll proceed to close this one since I do not see the issue anymore after testing. If you have any feedback please open a new report and reference this one.
