### ISSUE TITLE
Install freezes at installer finalization (5074 and 5081 -- troubleshooting WIP)

### ISSUE THREAD

**Issue by LancerDawg75** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#641]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Arc Installer Package

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3D

### Graphic Card [Required]

Intel Arc A770 Limited Edition

### GPU Driver Version [Required]

31.0.101.5081

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu 16 Dec 2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13692068/igcit_ssu.16.Dec.2023.txt)

### Description and steps to reproduce [Required]

Since driver version 5074 and currently with 5081, if I DDU the driver first (Safe Mode, of course), reboot, and start the installer -- the installation will go through its motions, but then as soon as it gets to "finalizing installation" -- my display freezes. It doesn't seem like it has crashed. It just seems as if the display driver itself has. 

If I force a shut down and turn it back on, the display and audio driver are installed, but Arc Control has not. If I run the installer again and perform a repair, it will successfully install everything without an issue. 

Additionally, if I perform a driver "update" (ie: running the installer without performing a DDU safe mode run), the installer will perform all its procedures without issue. 

I had thought that maybe there was an issue with the HDMI, so I went back to my CalDigit adapter and tried the same procedure again. The results came back the same if installed Arc drivers from a fresh install procedure. Installer will work correctly if I run the installer via an update path. 

I tried looking through event viewer to see if there would be something that would tell me anything, but nothing really out of the ordinary that points to anything related to the Intel Arc installation procedure. I have provided an SSU, but even I don't see much of anything out of the ordinary.  So, I'm kind of stumped here. 

I'm going to try and go back farther in the driver versions (ie: pre-5074) and see if the problem occurs there when I do a DDU run and see if it re-produces and I'll do an SSU there as well and maybe you guys can see a difference. If nothing happens - I'll have more questions than answers. If it does happen again, it will probably be the same issue that I had here with SRW30 and I'll probably have to nuke the site from orbit with Windows again. 

The first time it happened with 5074, I just handwaved it off because well...we are Arc users after all. ^_^;; 

When the newer driver arrived, I performed the install via the update path because it's generally what I do unless I run into some issue....and I did. I had played DraQue XI-S, but noticed that the core clock was staying static at 2400mhz. When I was done playing the game, the core clock did drop, but only to 1000mhz. I switched over to Spider-Man: Miles Morales and I ended up with a DXGI Device_Hung_Error so it wouldn't launch. Figured that it might have been due to the update path that I took. DDU Safe Mode removed the driver and the installation issue cropped up again. So...this is why I'm sending an issue report.

I will update my progress as I go along.

**Comment by LancerDawg75** [comment]
Oh! Also, @Arturo-Intel -- in reference to issue #304 -- I think there is a workaround/solution?? (I need a wider testing with resources that I don't have....) 

Also, I'm sorry that I added it here. 304 was closed, and I really didn't know how to report this because it isn't exactly an "issue" -- however, if you want me to treat it as one, would it be more in line with sending it as a "Windows Feature"?

This may be in Windows 11 23H2 only, so if you send this up the chain, maybe your end could see if it goes farther back in Windows 11 or Windows 10. 

It seems like on non-HDR HDMI HDTVs, you can go beyond 8-bit color, but it is a Windows setting. 


Here is what it looks like if I have the Auto Color Management switch disabled.
![AutoColorManagementDisabled](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/9777d438-ea90-4956-a0aa-26811e7fb3c5)

If this is off, then the bit depth is at the usual 8-bit. 

Additionally, if I use SSU to look at the DirectX Diagnostics log, I also see this.
![DXDiag-AutoColorManagementDisabled](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/564ca971-8504-4e5a-893c-c31654153552)

Now.....If I enabled the Auto Color Management setting
![AutoColorManagementEnabled](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/4afc6d53-bc35-406c-be38-9f902a473026)

And run SSU again to see the DxDiag display information, a few things change
![SSU-DxDiag-AutoColorManagementEnabled](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/8a20c156-a6a1-464e-90f9-f3790c409ec9)

Looking at some of the Microsoft documents here, the [DISPLAYCONFIG_PIXELFORMAT_NONGDI nomenclature is referenced here](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/ne-wingdi-displayconfig_pixelformat)

Which then leads me to [the surface format of the A2R10G10B10 format here.](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/bb153349(v=vs.85))

The [Microsoft documentation on DXGI color spaces](https://learn.microsoft.com/en-us/windows/win32/api/dxgicommon/ne-dxgicommon-dxgi_color_space_type) which by my SSU DxDiag shows that:
-  Display Color Space: DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709 -- still holds the 0-255 full range.


And then [one more reference to HDR vs non-HDR (sRGB) color formats](https://www.thewindowsclub.com/hdr-wcg-color-problems-windows-10).

**Comment by freak2fast4u** [comment]
Windows 10 22H2 user here, I straight up used the latest DDU and installed fresh from there, since upgrade paths usually don't go well for me, and the install worked, no issues. Could be Windows 11-specific problem ^^"

**Comment by LancerDawg75** [comment]
@freak2fast4u -- I'm pretty certain it is on my end. Just need to figure out where it was. Probably WU critical update fudged it to some degree. I really don't want to start over again, but with event viewer not really showing me anything that looks like could be the culprit. I'm kind of at a bit of a loss. 

I'll work through it. Just not today!!! 
I gotta get my Persona 5 Royal fix in....

**Comment by freak2fast4u** [comment]
Apparently you're not alone : https://www.reddit.com/r/IntelArc/comments/18k4w58/a750_driver_fails_to_install/

**Comment by LancerDawg75** [comment]
I've also been getting a few more VIDEO_TDR_FAILURE BSODs when I wake the Arc card from display sleep lately on the latest driver revision. Yeah, I'm going to have to go back a couple of versions just to see if the reason is the display stopping at driver finalization is the culprit for these issues.

**Comment by LancerDawg75** [comment]
Update: 20 Dec 2023

Reverted back to version 4972. Completed the installation process and recommended reboot without issue. I'm wondering if there has to be something regarding the particular Arc Control version. I'm going to have to test out installing the most recent driver without Arc Control and see if that gives me a successful installation finalization. 

If so, I might try and see if I can extract the Arc Control version from 4972 (I don't know...maybe 7-Zip can accomplish this) and hopefully there is an executable installer if there is an Arc Control folder in the overall 4972 package after installing 5081 without Arc Control for that version.

**Comment by Ilya-intel** [comment]
Hey @LancerDawg75 ,
Which version of the DDU do you use? Could you try the latest one?
I've tested with the 18.0.7.0 and no issues observed.
I've heard there were some problems with driver 5074+ and DDU below 18.0.6.0.

**Comment by LancerDawg75** [comment]
@Ilya-intel I get it regularly updated when notified using the DDU installer. Given that I made this post 3 weeks ago and that the most current version was released 12 Dec 2023, I am fairly certain that I used 18.0.7.0 when I was going through the issues that I had. 

I may try again as I recently updated my motherboard's BIOS to AMD AGESA 1.2.0.B and see if that changes anything.

**Comment by freak2fast4u** [comment]
Welp, I just had the exact same problem installing version 5084. It's the first time it happens to me in almost a year of installing intel arc drivers. 
Even using DDU twice and reinstalling the latest package twice ended up with the same result : black screen during install, no way forward other than pressing the power reset button. 

The only thing I can definitely say was different from my previous updates is that this time, I also ran DDU for my Ryzen GFX drivers before installing the intel driver package. Somehow, I had a feeling that having no fallback driver for the display will result in a black screen during the install procedure (this shouldn't happen, yet it does, Intel plz fix ...).
I tested this out by first installing AMD Adrenalin Drivers for Ryzen, rebooted, then installed the intel driver package, and this time it worked from start to finish in one go. I'm feeling lucky I have an APU at this point. I mean ... a dual-GPU installation might be a technically functional work-around, however that really shouldn't be necessary :D

Also, a certain number of users don't have an APU, or won't bother installing the AMD "APU" drivers either because they don't need them, or they might fear it will interfere with compatibility in certain apps/games, and rightfully so. For example, FF7 remake will try to run on the Ryzen APU when it's enabled, even if Windows is configured to use the "high-performance" GPU (Arc A770 in my case) for the game executable. Many games blacklist "Intel" GPUs as if they were all iGPUs, which isn't the case anymore. It's bad practice from the game devs, but it's a hell of a headache for us Intel Arc users now -_- 
I can see why not installing the APU graphics drivers will be a use-case for some time ...

@LancerDawg75 : the 5800X3D doesn't have an iGPU, and I coincidentally dropped my iGPU drivers, and by doing so I coincidentally generated the same problem you're having. I don't know how Intel users might be affected, but it seems anyone with a CPU that doesn't have an APU or hasn't installed their APU drivers is F'ed for the time being. I hope someone else can join the discussion with new data ...

**Comment by freak2fast4u** [comment]
It seems disabling XMP/DOCP during driver installation helped at least one more person (see issue 667 linked above). They were also on a single-GPU setup (no iGPU, and no room in the case to go dual dGPU like they hoped for).

**Comment by Ilya-intel** [comment]
@freak2fast4u 
Hmmm, interesting. Looks like it is applicable just for some XMP memory configs.
All systems that I've tested had XMP enabled. 
Anyway, we'll keep looking.
Thanks for watching it!

**Comment by LancerDawg75** [comment]
20 January 2023 Update: Currently on 5804, but didn't DDU, and it seems like I haven't had an issue yet. 

However, I still had persistent VIDEO_TDR_FAILURE blue screens of death here and there. I went in and adjusted in the registry the TdrDelay value from 2 to 10, and changed the TdrDdiDelay to a value of 12 and the BSOD for that has gone down to nearly non-existent.

**Comment by freak2fast4u** [comment]
> 20 January 2023 Update: Currently on 5804, but didn't DDU, and it seems like I haven't had an issue yet.
> 
> However, I still had persistent VIDEO_TDR_FAILURE blue screens of death here and there. I went in and adjusted in the registry the TdrDelay value from 2 to 10, and changed the TdrDdiDelay to a value of 12 and the BSOD for that has gone down to nearly non-existent.

OMG this might allow me to prevent FFXV from crashing after a certain number of igfxnd timeouts. I looked into the Tdr reg keys (https://learn.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys) and now I'm almost certain the game crashes because the dx11 driver keeps timing out (crashing) on certain visual effects. The default values suggest the process should crash if the driver timed out more than 5 times every 60 seconds. This has definitely happened to me more that once ! 
I'd rather have a stuttering/freezing mess than have the whole game crash and loose hours of gameplay.  I loosened the same values you did, and also raised TdrLimitCount to 0x0000ffff (65535). 

Thanks for sharing !! Will report back if it works :)

**Comment by LancerDawg75** [comment]
@freak2fast4u Oh yeah...my apologies for not sending a reference link for the MS documentation, but it seems like you found it anyway. That's good. I got the inspiration from older Nvidia posts where people were experiencing frequent Video TDR failures on GeForce cards....so, I thought "Maybe it will work on Arc cards. Worth a shot". 

For me, it seems like it has helped quite a bit, so I hope that it works out for you. When you get the chance after maybe about a week of playing consistently, let us know how changing the values has gone!

**Comment by freak2fast4u** [comment]
Welp, that didn't go as well as planned, but it was worth a try :p 

I never had BSOD's to begin with but I was thinking maybe driver timeouts manifest in different ways depending on the context. I usually have event id 4101 "igfxnd stopped responding" in the event viewer, and the only times I had BSODs was when I was trying to push my DDR5 sticks above DOCP specs, even with some extra voltage. Wierd, but not unexpected either. Maybe I have badly binned sticks that barely meet the spec... 

DXVK 2.1 seems to fit the bill for me ATM (vertex explosions and 10fps out of the blue, but no crashes !). 
DXVK 2.3 crashes just like Intel's native DX11 driver after a while, without any warning signs. 

At least I can see why your tweaked settings might help windows get past having no graphics driver for a few seconds during a driver update. Your finding will surely benefit some, no doubt, so thanks for sharing :)

**Comment by Ilya-intel** [comment]
@LancerDawg75 @freak2fast4u 
Can I ask you to try the following (as a troubleshooting step):
1. Uninstall Driver and all related software using DDU.
2. Restart the system
3. Start latest driver installation but unselect checkbox for Arc Control.
4. Check for freeze.

**Comment by freak2fast4u** [comment]
@Ilya-intel : well, it failed for me, with default TDR settings and with my Ryzen iGPU disabled. 
During driver installation, the screen blinked, changed resolution, blinked again, and then went all black, with no signal to the monitor. Only way forward was to press the reset button. After reboot, the driver seems to be installed, and installing Arc Control seems to work afterwards. 

However, the firmware update log is abnormally short, and shows that the driver install is technically incomplete (the firmware files weren't unzipped in the expected locations for example, so FW flashing couldn't occur) : 
[IntelGFXFwUpdateToolLog_2024-1-23_20-51-3.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14029237/IntelGFXFwUpdateToolLog_2024-1-23_20-51-3.log)

The next big question is : what else is missing, considering the installation was aborted prematurely ? 

I'll re-do this test with tweaked TDR values and edit this post with my results, brb. 

Note: I'm purposefuly disabling the iGPU because enabling it seems to fix the issue for me, but not everyone has an APU. 
Also, I'm interested in having this problem fixed because I'd also like to keep my iGPU disabled for now, as it causes more trouble than it solves for me ATM (ie: games running on the iGPU even when instructed not to because game devs blacklisted intel (i)GPUs years ago as recurring development mal-practice).

**Comment by Ilya-intel** [comment]
@freak2fast4u 
Just tested single-GPU system on Intel platform with default TDR and still no issues :suspect: 
I'll build another AMD system tomorrow and do excessive testing, stay tuned.

**Comment by akarnokd** [comment]
I had no issues installing 5081 and 5085 but **5185** got me today a black screen with mouse cursor. (Each was in safe mode DDU, restart into normal mode with basic driver, install from the sfx). 

Several <kbd>Win+Ctrl+Shift+B</kbd> only got me the same black screen with mouse cursor, over and over. Left it a bit and then reset the machine.

Apparently the installer/system hung before it was supposed to install Arc Control so I did only install that, but didn't repair the drivers. System seems to work okay, Starfield runs samey.

*i7 13700K, A770LE, Windows 23H2*

**Comment by freak2fast4u** [comment]
I found some error logs from my 4 failures of yesterday : 
[driver_install_lockups_5085_20240123.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14043510/driver_install_lockups_5085_20240123.zip)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/42fad00f-d36a-4bbf-8078-b38fbb2e67bd)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/b1a0f78d-8af1-4210-bb00-e5d23e16ceed)

**Comment by Ilya-intel** [comment]
@freak2fast4u @akarnokd @LancerDawg75 
Guys, are you all using DP as video output?

**Comment by freak2fast4u** [comment]
> @freak2fast4u @akarnokd @LancerDawg75 
> Guys, are you all using DP as video output? 

Yep, but I do have an hdmi input and cable available for testing if needed

**Comment by akarnokd** [comment]
I'm using HDMI 1.4, 1920x1080 60Hz, non variable refresh rate. My monitor doesn't have a DP port nor does it support VRR or HDCP.

**Comment by Ilya-intel** [comment]
@freak2fast4u 
Could you try?
I've just tested and seen black screen with DP and not with HDMI.

**Comment by Ilya-intel** [comment]
@akarnokd 
The hang that is being fixed by unchecking Arc Control installation is currently being investigated by developers.

**Comment by freak2fast4u** [comment]
> @freak2fast4u Could you try? I've just tested and seen black screen with DP and not with HDMI.

I'll probably be able to test this on Monday, I'll keep you updated.

**Comment by LancerDawg75** [comment]
> @freak2fast4u @akarnokd @LancerDawg75 Guys, are you all using DP as video output?

I am currently using an active HDMI to DP adapter by CalDigit because under HDMI, it really doesn't like my Sony HDTV at a straight 60hz refresh rate.  

When operating at 60hz, the entire screen will overscan and there is no setting in Windows 11 advanced display settings that will fix it. The workaround is for me to install Intel Graphics Command Center, and set it to:

> Maintain Display Aspect Ratio

When I do that, the display no longer overscans, but the refresh rate is set at 60.02hz. This is not a real problem if I run every game under Borderless Windowed mode, but Fullscreen or Executive Fullscreen, it returns to 60hz and I get overscan of the game being played.

**Comment by Ilya-intel** [comment]
@LancerDawg75 @freak2fast4u 
I've come through several monitors on my AMD system and only one showed such behavior with DP.
So, to gather more data, could you share the EDID info (and model) from your displays that go black during install?

**Comment by freak2fast4u** [comment]
Screenshot taken using MonitorInfoView from NirSoft : ![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/6b803828-420e-484e-89ee-f44c1b34ecda)
(Tool here : https://www.nirsoft.net/utils/monitor_info_view.html)

A raw dump of the EDID data produced by Custom Resolution Utility aka CRU in different formats (tool here : https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU)

[agon_aoc_AG241QX.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14302237/agon_aoc_AG241QX.zip)

The monitor is sometimes labeled as AG241QG4, sometimes as AG241QX (this is what's written on the screen bezel).

**Comment by Ilya-intel** [comment]
@freak2fast4u @LancerDawg75 
Thank you, guys, for giving me all this information.
I've combined it and sent it to developers under ID 18037175579.
I'll keep you updated in this thread.

**Comment by Ilya-intel** [comment]
@freak2fast4u @LancerDawg75 
Hello guys,
The latest driver contains an installer fix that might also resolve the issue in this thread.
Any chance you can try it out?

**Comment by Ilya-intel** [comment]
@freak2fast4u @LancerDawg75 
I'm sorry for taking so long for fixing this, but I've been notified that issue should be fixed by now.
Could you test with the latest ([32.101.0.6127](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)) driver? 
I've tested on my system and it works OK now.
Thanks in advance.

**Comment by LancerDawg75** [comment]
@Ilya-intel Honestly, I'm sorry I've been away this whole time. 

2024 hasn't particularly kind to me, so I've been doing other things like photography and fixing/modding things. Drinking wine. Lots of wine......but there's some light at the end of the tunnel and realizing with some people in my life, there comes a time that even though you don't want to give up on them....sometimes, you have to let them go. 

So, I'm sort of on the mend, and getting back to being me...with that said...

Questions: 

- Do you still need and want me to provide any EDID information regarding my HDTV? I have 6127 installed, but again, I'm still on the DP to HDMI adapter which alleviates the HDTV needing 60.02hz in order to maintain the display ratio.

- I can remove my 2nd monitor and put the HDTV back on HDMI direct. If it still needs 60.02 hz, I'll report back here. 

Also upside that I've seen lately with the driver development -- 12-bit YCbCr finally works! 
It still requires that you need Intel Graphics Command Center for you to change it, but still...I'll take it. 

![12bit 1](https://github.com/user-attachments/assets/6d6aa3f3-bcad-4255-a908-464881c235c5)
![12bit 2](https://github.com/user-attachments/assets/b2fb72f0-c6eb-414e-92d1-3d2bf3965d47)
![12bit 3](https://github.com/user-attachments/assets/93469ef7-824c-4b93-896a-4bd965017cd5)

**Comment by Ilya-intel** [comment]
@LancerDawg75 
Yeah, kindly check the direct connection.
Thanks!

**Comment by LancerDawg75** [comment]
@Ilya-intel 

In regard to the installer finalization issue (which is really the original problem), that seems/feels that it is rectified. 

In the realm of the overscanning issue with an older TV, it is not. 
However, I think that maybe (?) should be made in a different post. 

At the same time, I'm fairly sure that this a minor issue because...again, I'm using a much older HDTV and it can be rectified by throwing more money at it in the form of a HDMI to DP adapter. 

I could try it again as you guys have dropped another driver update today.

**Comment by Ilya-intel** [comment]
@LancerDawg75 
Agree, kindly create separate thread, if you wish for overscan issue to be investigated more by us.
And I'll be closing this thread since installer issue is gone now.
Thank you for your activity and cooperation!
