### ISSUE TITLE
Make VBIOS updates separate from driver packages, and document them

### ISSUE THREAD

**Issue by freak2fast4u** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#642]
### Graphic Card [Required]

All Intel

### Rendering API [Required]

- [X] Not applicable

### Windows Build Number [Required]

- [X] Not applicable 

### Describe the feature [Required]

I believe VBIOS updates would be better off separate from driver packages and documented separately. Could you please make it happen ?

If some driver feature relies upon requires a specific VBIOS version as a dependency, document it, and let the user do the operation through a 1st party tool you provide. Also allow for a downgrade path if for some reason a particular VBIOS has issues for some user(s), independently from the installed driver version. 

At the very least, I would like to have the choice to flash the VBIOS or not from the installer menu, depending on wether I would benefit from that update or not. Being informed is good but insufficient. 

The situation is problematic in another aspect : Windows (users can't opt-out) and Linux (users can't opt-in).
 
Under Linux, as far as I can see, there's no way of updating the VBIOS on Intel Arc graphics cards. A quick search at fwupd.org/lvfs gives no results for Alchemist, DG1, DG2, Arc, A770, and so on. There's already Intel firmware/microcode on fwupd so that would be the most logical thing to do IMHO. 

Is it at least on the roadmap somewhere ? If it isn't, please consider it.

**Comment by Diomedus94** [comment]
Yes documentation for VBIOS firmware updates for intel ARC card would be nice.

First party tool for VBIOS downgrading would be really helpfull on official intel website.

Official VBIOS list website to download to have it one place to be sure to download officiali from Intel.

**Comment by Gabriela-Intel** [comment]
Thanks everyone for your input!

I'm submitting this feedback to the team. We'll see what we can do! :)

I'll be closing this one out since we will be tracking this internally. @IGCIT
