### ISSUE TITLE
Octopath Traveler 2 constantly freezes

### ISSUE THREAD

**Issue by whchan05** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#645]
### Checklist [README]

- [x] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Octopath Traveler 2

### Processor / Processor Number [Required]

5700X

### Graphic Card [Required]

A770 LE

### GPU Driver Version [Required]

31.0.101.5081

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[output 19 Dec 23.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13708657/output.19.Dec.23.txt)

### Description and steps to reproduce [Required]

Just play the game normally for around 20 mins or so. Freezes occur at random intervals.

If you wait long enough after the freeze, a window will pop up saying that UE4 stopped rendering for 120 seconds or something.

**Comment by Joseph-Intel** [comment]
hey @whchan05 Thanks for submitting! I will be taking a look at this and let you know if I have any questions and keep you updated with my findings.

**Comment by Joseph-Intel** [comment]
Hi @whchan05 Just wanted to give you a heads-up. I was able to reproduce the issue so I will be escalating this issue to try to get this fixed. If you have any questions or concerns please to hesitate to ask!

**Comment by Arturo-Intel** [comment]
@whchan05 Just to confirm
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/17c09a1f-dd10-469c-8858-3f7589395e98)

This is what are you seeing?

**Comment by whchan05** [comment]
@Arturo-Intel
Cannot confirm, but likely. I will get back to you tomorrow :)

**Comment by whchan05** [comment]
@Arturo-Intel 
I've just run into the same issue and yes this is the exact same message I've got.
<img width="1275" alt="ot2" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/109796524/8adf313c-0d55-47f7-a1df-bc14adf6c858">

**Comment by Arturo-Intel** [comment]
@whchan05 Did you try with [101.5330](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)? 
I was able to play more than 1hr :)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/5e626794-3700-4be5-ae27-087b07a052c2)

**Comment by Arturo-Intel** [comment]
Thanks for the confirmation! 
Will close this case now.
