### ISSUE TITLE
Intel Video Super Resolution - for watching video

### ISSUE THREAD

**Issue by gargamel314** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#646]
### Application [Required]

Chrome, MSEdge, Firefox

### Processor / Processor Number [Required]

13700K

### Graphic Card [Required]

Intel Arc/Acer Predator Bifrost A770 16GB

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

In March, this feature was teased by VideoCardz (https://videocardz.com/newz/intel-is-also-preparing-video-super-resolution-for-chrome-browsers) and some of us have it enabled, but it's not officially supported. There's no way to control over it, and at times it's not even evident that it's working. This is such a neat feature, and the NVIDIA version of it is implemented right into NVIDIA Control Panel. Can we finally have this, but with functionality in Arc Control?

**Comment by Gabriela-Intel** [comment]
@gargamel314 Thanks so much for the feedback! We'll look into this feature that is mentioned in the article.

@IGCIT You may close this feature request.
