### ISSUE TITLE
Screen Flashes Black When VSCode is Opened.

### ISSUE THREAD

**Issue by CursedAtom** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#647]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Visual Studio Code v1.85.1 (Same issue with Insider version as well)

### Processor / Processor Number [Required]

AMD Ryzen 7900x

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

31.0.101.5081

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13710373/ssulog.txt)

### Description and steps to reproduce [Required]

Prerequisites:
1. Have 2 monitors plugged in to the A770 gpu, one in the HDMI port and one in the DisplayPort port closest to the HDMI port.
2. Set the HDMI monitor as the main display
3. Download and install the latest Visual Studio Code OR the latest Visual Studio Code - Insiders

Steps to reproduce:
1. Open Visual Studio Code
2. The DisplayPort monitor will turn black for 2 or more seconds, sometimes not turning back on until VSCode is closed.

### Device / Platform

Custom Built @ home

### Crash dumps [Required, if applicable]

N/A, no crash occurred. 

### Application / Windows logs

[20231218T212554.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13710409/20231218T212554.zip)
Attached are the Visual Studio Code logs when the issue is occurring.

**Comment by freak2fast4u** [comment]
What are your screen specs ? (exact brand/model)
What does the OSD of your DisplayPort connected screen say about refresh rate ? 
Does it go into freesync mode or does it stay stuck to a constant frequency ? 

We're trying to figure out a very similar issue over here (it's a lengthy thread) : https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/580

Also, did you reboot twice after installing the 5081 driver ? I have a feeling this fixed it for me, because ever since I rebooted one extra time I can't make the issue happen again, though it might still be random, so I'll keep my computer running and checking the screen every morning to see what happens.

**Comment by CursedAtom** [comment]
> What are your screen specs ? (exact brand/model) What does the OSD of your DisplayPort connected screen say about refresh rate ? Does it go into freesync mode or does it stay stuck to a constant frequency ? Does the issue also occur when you launch the windows store ? or maybe another UWP app ?
> 
> We're trying to figure out a very similar issue over here (it's a lengthy thread) : #580
> 
> Also, did you reboot twice after installing the 5081 driver ? I have a feeling this fixed it for me, because ever since I rebooted one extra time I can't make the issue happen again, though it might still be random, so I'll keep my computer running and checking the screen every morning to see what happens.

Monitor 1 (The HDMI monitor) has freesync on, refresh rate of 60hz. It is a Samsung C24F390
Monitor 2 (The DisplayPort monitor) has Adaptive Sync on, refresh rate set to 60hz. It is a Sceptre B30

I am only seeing this issue with Visual Studio Code unfortunately. And yes, I have rebooted my computer multiple times after installing the driver.

**Comment by Karen-Intel** [comment]
Hey @CursedAtom thank you for your report!

Question: did you use [DDU](https://www.guru3d.com/download/display-driver-uninstaller-download/) for the driver upgrade? It is highly recommended, specially when we start seeing strange behaviors

I'm asking because I use VS Code in a similar Setup (Regular 60Hz HDMI HD res + Dp to Mini DP 4K Samsung Odyssey G8 Ultrawide. HDMI has been set as main display, DP as secondary) and [I haven't been able to repro the issue with driver 5081.](https://www.youtube.com/watch?v=u8AAxCDUHfg)

You can see my system is also an AMD. I have done the same tests in a 13900k with and without UHD.

Keep us posted

Karen

**Comment by Nikaim** [comment]
It sounds stupid, but try removing the theme in your browser. I have been using the Grass theme in the Chrome browser for many years (https://chromewebstore.google.com/detail/grass/mmiboiefncpfjihjdedpaoammipkilla?hl=en). After installing the ARK A750, black screens flashes sometimes appeared on DP monitor with FreeSync.

**Comment by CursedAtom** [comment]
> Hey @CursedAtom thank you for your report!
> 
> Question: did you use [DDU](https://www.guru3d.com/download/display-driver-uninstaller-download/) for the driver upgrade? It is highly recommended, specially when we start seeing strange behaviors
> 
> I'm asking because I use VS Code in a similar Setup (Regular 60Hz HDMI HD res + Dp to Mini DP 4K Samsung Odyssey G8 Ultrawide. HDMI has been set as main display, DP as secondary and viceversa) and [I haven't been able to repro the issue with driver 5081.](https://www.youtube.com/watch?v=u8AAxCDUHfg)
> 
> You can see my system is also an AMD. I have done the same tests in a 13900k with and without UHD, same results
> 
> Keep us posted
> 
> Karen

Thank you for the reply Karen, but I had this issue with DDU as well. These issues are still present on a clean windows install with drivers downloaded directly from the Intel website, none installed by Windows itself. I reinstalled windows on this system just a few days ago for an unrelated issue, so there has not been any update history for this driver. The screen will go black any time a window is opened, closed, resized, or minimized on monitor 2. This only happens with VSCode open. Opening tabs on the browser does not cause the black screen, nor does resizing, opening, closing, or minimizing windows on Monitor 1. As I am writing this with VSCode open on monitor 1, the screen is occasionally flashing black when I scroll around. I'll keep this issue updated with anything new I can find.

**Comment by Arturo-Intel** [comment]
@CursedAtom out of curiosity, do you see this behavior if you only have the adaptive sync monitor connected? (HDMI or DPort)

--r2

**Comment by CursedAtom** [comment]
@Arturo-Intel , I just tried and yes, I have the same issue with only the Adaptive Sync monitor connected (It is the DPort monitor). The issue disappears when Adaptive Sync is turned off, but I prefer Adaptive Sync on when gaming because it helps with lower/unstable framerates when I play Minecraft with shaders.

**Comment by Karen-Intel** [comment]
Hmm @CursedAtom that is interesting because my monitor has Adaptive Sync on at all times and I haven't had any issue with VS Code, so I don't think it has to do with drivers (at least in some monitors)

We'll check if we have a Sceptre B30 just to discard, stay tuned and thank you for your quick response!

Karen

**Comment by CursedAtom** [comment]
I have also tried the other DPorts on the card, it has the same issue. I'm going to try this monitor with HDMI and I'll edit this comment with results

**Comment by Karen-Intel** [comment]
@CursedAtom good news. Just found a monitor where I could repro the issue @60 Hz 
Allow me to report this internally and I will share the tracking number with you :)

Karen

**Comment by CursedAtom** [comment]
Thank you Karen. I will keep adaptive sync off for now until this issue is resolved since I need to use VSCode for some projects I'm working on.

**Comment by Karen-Intel** [comment]
Hey @CursedAtom just FYI I have already reported the black flashes with the following number: 14021264864
If we get news or updates about it, I will let you know in this thread so please keep it open :)

Ty for your help!

Karen

**Comment by Karen-Intel** [comment]
Hey @CursedAtom could you please verify the issue with our latest driver[ v.5186](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)?
I haven't been able to repro the flashing with VS Code with Adaptive Sync on in my Samsung G8
Could you help me verify? Appreciate it :)

Karen

**Comment by CursedAtom** [comment]
> Hey @CursedAtom could you please verify the issue with our latest driver[ v.5186](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)?
> 
> I haven't been able to repro the flashing with VS Code with Adaptive Sync on in my Samsung G8
> 
> Could you help me verify? Appreciate it :)
> 
> 
> 
> Karen

I apologize for such a late reply, but I no longer own the Intel Arc A770. I sold it to a friend and bought a different GPU because I needed CUDA support for several applications I use. This is nothing against the Arc GPU lineup, I just needed a different device to use for my applications. Thank you for all of your help, but I will unfortunately not be able to test if this issue is solved.

**Comment by Karen-Intel** [comment]
@CursedAtom thank you for your reply tho :)

We'll be glad to hear from you if you ever need us again

@Arturo-Intel can you do the honors please? Issue is not reproducible anymore with driver v5186 :)

Karen
