### ISSUE TITLE
Arc Performance Overlay - option to choose display it appears on

### ISSUE THREAD

**Issue by zp** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#648]
### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

AMD Ryzen 5900x

### Graphic Card [Required]

Intel Arc A770 16GB

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Exploring the feasibility of this, giving users the option to select the display/monitor the overlay renders on.

This way users can have the overlay active on a secondary display without potentially blocking/interfering with any 'fullscreen' application/game running on their primary display.

![intelarc-overlay-mock](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/170573/52bd2399-c60e-4a62-a96f-2c005a673acd)

Quick little mockup (display 2 is my primary display and i'd like it to render on display 1), though it'd probably be better for a dropdown box that defaults to primary display then has options to override specific displays.

**Comment by Gabriela-Intel** [comment]
Great feedback! I've submitted the feedback for the team to review. We'll make sure this gets passed along to the Arc Control team.

Thanks so much for taking the time to give us details with a mock up :)

@ IGCIT Feedback has been submitted, please close.
