### ISSUE TITLE
Fallout 4 CTD or system crash

### ISSUE THREAD

**Issue by nscreated** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#65]
Game / Application: Fallout 4
Processor: Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz
GPU driver version: 27.20.100.9616 (This has been my experience with every Intel driver after 8190)
Rendering API: DirectX11
Windows build number 19042 (20H2)
Description Fallout 4 crashes roughly after 10-15 minutes of gameplay. Sometimes is only a CTD, other times the entire system locks up permanently and can only be rebooted by holding the power button. Sometimes the system BSODs.
Steps to reproduce Run Fallout 4, no mods, low-medium settings.
Device name: GPD Win Max

Game settings: Only mods are quicksave enabler and console enabler.  fallout4prefs.ini pasted below.
[Display]
flocalShadowMapHalveEveryXUnit=750.0000
focusShadowMapDoubleEveryXUnit=450.0000
fShadowBiasScale=1.0000
fDirShadowDistance=3000
fShadowDistance=3000
uiOrthoShadowFilter=2
uiShadowFilter=2
iShadowMapResolution=2048
uPipboyTargetHeight=700
uPipboyTargetWidth=876
iVolumetricLightingQuality=0
bVolumetricLightingEnable=0
bSAOEnable=0
iDirShadowSplits=2
bVolumetricLightingForceCasters=0
iTiledLightingMinLights=40
bComputeShaderDeferredTiledLighting=1
iMaxFocusShadowsDialogue=4
iMaxFocusShadows=2
bForceIgnoreSmoothness=1
fBlendSplitDirShadow=48
bSinglePassDirShadow=1
bEnableWetnessMaterials=0
fTessFactorMaxDistanceScale=100.0000
sAntiAliasing=FXAA
fLeafAnimDampenDistEnd=4600.0000
fLeafAnimDampenDistStart=3600.0000
fMeshLODFadePercentDefault=1.2000
fMeshLODFadeBoundDefault=256.0000
fMeshLODFadeScalar=1.0000
fMeshLODLevel2FadeTreeDistance=2048.0000
fMeshLODLevel1FadeTreeDistance=2844.0000
fInteriorMeshLODLevel2FadeDist=1950.0000
fInteriorMeshLODLevel1FadeDist=2600.0000
fMeshLODLevel2FadeDist=1600
fMeshLODLevel1FadeDist=4000
iMaxAnisotropy=1
iPresentInterval=1
bTopMostWindow=0
bMaximizeWindow=0
bBorderless=1
bFull Screen=1
iSize H=800
iSize W=1280
bAllowShadowcasterNPCLights=0
iScreenShotIndex=1
fMaxFocusShadowMapDistance=450.0000
bPrecipitationOcclusion=1
iMaxSkinDecalsPerFrame=0
iMaxDecalsPerFrame=0
sD3DDevice="Intel(R) Iris(R) Plus Graphics"
iTexMipMapSkip=2
bEnableRainOcclusion=0
iAdapter=0
[Imagespace]
bDoDepthOfField=1
bScreenSpaceBokeh=0
bMBEnable=0
bLensFlare=0
[Pipboy]
fPipboyEffectColorB=0.0900
fPipboyEffectColorG=1.0000
fPipboyEffectColorR=1.0000
[VATS]
fModMenuEffectHighlightPAColorB=0.4100
fModMenuEffectHighlightPAColorG=0.8200
fModMenuEffectHighlightPAColorR=1.0000
fModMenuEffectPAColorB=0.4100
fModMenuEffectPAColorG=0.8200
fModMenuEffectPAColorR=1.0000
fModMenuEffectHighlightColorB=0.0824
fModMenuEffectHighlightColorG=1.0000
fModMenuEffectHighlightColorR=1.0000
fModMenuEffectColorB=0.4200
fModMenuEffectColorG=0.9900
fModMenuEffectColorR=1.0000
[MAIN]
fSkyCellRefFadeDistance=150000.0000
bCrosshairEnabled=1
fHUDOpacity=1.0000
bSaveOnPause=1
bSaveOnTravel=1
bSaveOnWait=1
bSaveOnRest=1
[LightingShader]
bScreenSpaceSubsurfaceScattering=0
bScreenSpaceReflections=0
[General]
bGamepadEnable=1
bPipboyCompanionEnabled=0
iStoryManagerLoggingEvent=-1
bEnableStoryManagerLogging=0
uGridsToLoad=5
[Interface]
bDialogueSubtitles=1
bGeneralSubtitles=1
iHUDColorB=21
iHUDColorG=255
iHUDColorR=255
bDialogueCameraEnable=1
bShowCompass=1
uHUDActiveEffectWidget=2
[Controls]
fMouseHeadingSensitivity=0.0300
fGamepadHeadingSensitivity=0.6667
bAlwaysRunByDefault=1
bInvertYValues=0
bGamePadRumble=1
[GamePlay]
iDifficulty=6
bShowFloatingQuestMarkers=1
bShowQuestMarkers=1
[Particles]
iMaxDesired=750
[SaveGame]
fAutosaveEveryXMins=10.0000
[AudioMenu]
fAudioMasterVolume=1.0000
fVal7=1.0000
uID7=0
fVal6=1.0000
uID6=0
fVal5=1.0000
uID5=0
fVal4=0.6500
uID4=138006
fVal3=0.6500
uID3=1007612
fVal2=1.0000
uID2=94881
fVal1=0.6500
uID1=466532
fVal0=0.6500
uID0=554685
[Water]
bUseWaterDisplacements=1
bUseWaterRefractions=1
bUseWaterReflections=1
bUseWaterDepth=1
[TerrainManager]
fTreeLoadDistance=12500
fBlockMaximumDistance=100000
fBlockLevel2Distance=75000
fBlockLevel1Distance=25000
fBlockLevel0Distance=15000
fSplitDistanceMult=0.5
bShowLODInEditor=0
[Grass]
fGrassStartFadeDistance=4000
fGrassMaxStartFadeDistance=7000.0000
fGrassMinStartFadeDistance=400.0000
[Decals]
uMaxDecals=0
bDecals=0
bSkinnedDecals=0
uMaxSkinDecals=0
uMaxSkinDecalsPerActor=0
[LOD]
fLODFadeOutMultSkyCell=1.0000
fLODFadeOutMultObjects=20
fLODFadeOutMultItems=6.6
fLODFadeOutMultActors=11
[NVHBAO]
bEnable=0
fBackgroundAOViewDepth=750.0000
bBackgroundAOEnable=1
fDepthThresholdSharpness=100.0000
fDepthThresholdMaxViewDepth=500.0000
bDepthThresholdEnable=0
iDepthClampModeEnum=0
fCoarseAO=1.0000
fDetailAO=0.6500
fBlurSharpnessProfileBackgroundViewDepth=1.0000
fBlurSharpnessProfileForegroundViewDepth=0.0000
fBlurSharpnessProfileForegroundSharpnessScale=4.0000
bBlurSharpnessProfileEnable=0
fBlurSharpness=16.0000
iBlurRadiusEnum=1
bBlurEnable=1
fPowerExponent=2.5000
fBias=0.1000
fRadius=0.6500
[NVFlex]
bNVFlexEnable=0
iQuality=0
iMaxNeighbors2=64
iMaxNeighbors1=48
iMaxNeighbors0=32
iMaxParticles2=32768
iMaxParticles1=16000
iMaxParticles0=6000
fKillRadius2=4000.0000
fKillRadius1=3000.0000
fKillRadius0=2000.0000
bNVFlexInstanceDebris=1
bNVFlexDrawDebris=1
[BlurShaderHDR]
bDoHighDynamicRange=0
[BlurShader]
bUseBlurShader=0
[Launcher]
uLastAspectRatio=2
[Bethesda.net]
uPersistentUuidData3=834639823
uPersistentUuidData2=2296953179
uPersistentUuidData1=3795601326
uPersistentUuidData0=457103762

Immediately preceding my most recent system crash, Event Viewer logged multiple WHEA-Logger warnings containing the following:
`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-WHEA-Logger" Guid="{c26c4f3c-3f66-4e99-8f8a-39405cfed220}" /> 
  <EventID>19</EventID> 
  <Version>0</Version> 
  <Level>3</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2021-06-09T01:55:41.7374409Z" /> 
  <EventRecordID>35080</EventRecordID> 
  <Correlation ActivityID="{e05fccee-b1c3-4b19-b677-6a9709ef4bf4}" /> 
  <Execution ProcessID="4044" ThreadID="3252" /> 
  <Channel>System</Channel> 
  <Computer>DESKTOP-VAID0JE</Computer> 
  <Security UserID="S-1-5-19" /> 
  </System>
- <EventData>
  <Data Name="ErrorSource">0</Data> 
  <Data Name="ApicId">1</Data> 
  <Data Name="MCABank">3</Data> 
  <Data Name="MciStat">0x8c20004000101135</Data> 
  <Data Name="MciAddr">0x47b665b30</Data> 
  <Data Name="MciMisc">0x4612285</Data> 
  <Data Name="ErrorType">9</Data> 
  <Data Name="TransactionType">1</Data> 
  <Data Name="Participation">256</Data> 
  <Data Name="RequestType">3</Data> 
  <Data Name="MemorIO">256</Data> 
  <Data Name="MemHierarchyLvl">1</Data> 
  <Data Name="Timeout">256</Data> 
  <Data Name="OperationType">256</Data> 
  <Data Name="Channel">256</Data> 
  <Data Name="Length">936</Data> 
  <Data Name="RawData">435045521002FFFFFFFF03000200000002000000A803000029370100090615140000000000000000000000000000000000000000000000000000000000000000BDC407CF89B7184EB3C41F732CB57131B248949139377F4BA8F1E0062805C2A350C7E4C8F65AD70100000000000000000000000000000000000000000000000058010000C00000000003000001000000ADCC7698B447DB4BB65E16F193C4F3DB0000000000000000000000000000000002000000000000000000000000000000000000000000000018020000800000000003000000000000B0A03EDC44A19747B95B53FA242B6E1D0000000000000000000000000000000002000000000000000000000000000000000000000000000098020000100100000003000000000000011D1E8AF94257459C33565E5CC3F7E8000000000000000000000000000000000200000000000000000000000000000000000000000000007F010000000000000002010100010000E50607000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000007000000000000000100000000000000E506070000081001BFFBFA7FFFFBEBBF0000000000000000000000000000000000000000000000000000000000000000F50157A5EFE3DE43AC72249B573FAD2C03000000000000009F004D0000000000305B667B040000000000000000000000000000000000000000000000000000000200000001000000BF32108DD25CD701010000000000000000000000000000000000000003000000351110004000208C305B667B04000000852261040000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000</Data> 
  </EventData>
  </Event>`

**Comment by PacoAvelar** [comment]
I was not able to replicate this issue on 
 GPD Win 3 
  - i7 1165G7
  - 16GB
  - Windows 11
  - GPU Driver 30.0.100.9955

**Comment by estebanr863** [comment]
I played 30minutes on a i7 1165G7 + 16GB of RAM on driver 30.0.100.9955 and had no issues. @nscreated can you test with this driver version?

**Comment by estebanr863** [comment]
Hi @nscreated. Did you had a chance to try this with the latest drivers?

**Comment by estebanr863** [comment]
Hi @mva94 and @IGCIT can any of you help and try this with the latest driver?

**Comment by estebanr863** [comment]
Hi @mva94 and @IGCIT, since no one seem to be able to repro this issue, and it is not happening on our side with the latest drivers, can we close this?
