### ISSUE TITLE
Cultic game shows visual anomalies in fullscreen + vsync

### ISSUE THREAD

**Issue by Hasturtium** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#650]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Cultic

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 7 5700GE

### Graphic Card [Required]

Sparkle Elf Intel Arc A380

### GPU Driver Version [Required]

31.0.101.5084

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU Report - Cultic Bug Report 12.23.23.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13760720/Intel.SSU.Report.-.Cultic.Bug.Report.12.23.23.txt)

### Description and steps to reproduce [Required]

When color filtering is enabled within Cultic's in-game menus, there is an intermittent, unpredictable flickering or visual effect that occurs at unpredictable intervals when the game is in fullscreen mode with vsync enabled, but NOT when it is windowed or in a borderless window. An example of the phenomenon can be seen at this YouTube video I captured:

https://youtu.be/7_bUzLmxCzo

I will note that in attempting to capture the error in a previous video, the Arc's built-in encoder did NOT capture the video, suggesting this is some kind of weird interaction with the display. However, I have noticed this bug on an Intel Arc A750 which was connected to an entirely different Acer 1080p165 Hz display at the time on a previous driver release. Toggling game asset quality, dithering, and other in-game configuration options does not seem to cause or contribute to the problem - it is seemingly tied to color filtering. 

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Settings are largely invariant: the issue only occurs in fullscreen mode with vsync on and color filtering enabled. Borderless windowed and windowed mode don't do this; disabling vsync makes the issue go away as well.

### Device / Platform name

Windows 11/ASRock x300 Deskmeet ITX

**Comment by Ilya-intel** [comment]
@Hasturtium 
Thanks for reporting the issue.
I've successfully replicated and reported it to the driver team.
I'll update you on any related updates in this thread.
BUG ID for reference: 18036071860.

**Comment by Ilya-intel** [comment]
Hi @Hasturtium ,
Thank you for reporting this issue. Our priority is to target the most popular games and apps to focus our efforts on providing a high quality, stable experience for the broadest set of users. We will continue to improve our software performance and compatibility throughout 2024 and beyond. 
While we can’t accommodate your request at this time, please watch this [article](https://www.intel.com/content/www/us/en/support/articles/000097843.html) on our website for any possible changes to this situation.
This thread will be closed.

**Comment by Ilya-intel** [comment]
@IGCIT 
Please close this thread.
