### ISSUE TITLE
Very low FPS in the game Just Cause 4 Reloaded

### ISSUE THREAD

**Issue by Pashamolochko** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#651]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Just Cause 4 Reloaded

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

Steam

### Processor / Processor Number [Required]

i5 12400f

### Graphic Card [Required]

Intel arc a770

### GPU Driver Version [Required]

31.0.101.5084

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

![WYX5Y0Ws040](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/3e8e7714-777b-47f2-b5d3-4a69b2c908f8)

### Description and steps to reproduce [Required]

FPS is quite low, on all graphics settings, even lowering the resolution does not improve the situation, and when barrels explode at the beginning of the game, FPS can drop to 10 FPS
![TwL_b9Rx3J8](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/39e1b2cb-3455-4be0-bc05-4d06e5ac2d7f)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1920

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![IowWSf7NAHM](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/8817f969-6338-4d7f-beec-189ec21e8e1c)
![7MhG11FtDrU](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/ccea701b-b757-49b0-883c-d782250f8edb)

### Device / Platform name

LGA 1700

### Crash dumps [Required, if applicable]

![IowWSf7NAHM](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/77bfe792-2b5d-42f3-9a74-1df4b8e8ef37)
![7MhG11FtDrU](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/f8f44488-06c9-4455-af1c-84fa942dd638)

**Comment by BiZkViT96** [comment]
The game is known for its poor performance regardless of hardware.

You should have checked here first https://steamcommunity.com/app/517630/discussions/

People have performance issues even if they have 4090. The only thing that seems to help with stuttering is turning off Leaderboard Display in Gameplay settings.

Also you should check how game runs with different screen settings and with Vsync being OFF.

**Comment by Pashamolochko** [comment]
> Игра известна своей низкой производительностью независимо от оборудования.
> 
> Вы должны были сначала проверить здесь https://steamcommunity.com/app/517630/discussions/
> 
> У людей возникают проблемы с производительностью, даже если у них 4090. Единственное, что помогает справиться с заиканием, — это отключение отображения таблицы лидеров в настройках игрового процесса.
> 
> Также вам следует проверить, как игра работает с различными настройками экрана и с выключенной вертикальной синхронизацией.

everything has been checked and tested, here it is the problem in the driver itself, and there is not an effective use of the video card, as can be seen from the monitoring

**Comment by Nikaim** [comment]
FPS on my PC was greater with the old Radeon R9 290 (40-50), and more than good on the Radeon RX6600XT before it burned out. Now FPS is 25-35 at approximately the same settings on Asrock Challenger [A750 CLD 8GO] , but the picture looks very bad. In this case, the DXVK does not work completely on this game.
https://youtu.be/lYfSII5B_ZQ

**Comment by BiZkViT96** [comment]
@Nikaim I'm not sure why you reacted negatively to my comment. If you had read it and done a little research, you would know that everything I said is true. Unless you're saying that everyone who claimed poor performance is making stuff up, including that person with the 4090 and 9 FPS. Just google "Just Cause 4 low fps", its all over the internet, posts ranges from 6 months to 5 years ago. And I have not said anywhere that Intel driver does not have a severe bottleneck in this game or implied that report is not a valid. I just pointed out that the Internet is full of reports about poor performance, and they all mention completely different hardware configurations.

BTW, your video shows graphic artifacts. Why are you both talking only about poor performance and not mentioning them?

@IGCIT Add Graphical Glitches label.

**Comment by Nikaim** [comment]
It was earlier: https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/81

**Comment by BiZkViT96** [comment]
Oh, well, that sucks. Even the screenshot in that post shows 52% GPU utilization with low FPS. It looks like the only hope is DXVK. Because even if the performance is fixed, Intel GPUs won't be a good choice for this game.

**Comment by Nikaim** [comment]
> In this case, the DXVK does not work completely on this game.

**Comment by BiZkViT96** [comment]
@Nikaim Yes, I know. I mean, the only hope is that if the devs of DXVK will make some progress on this issue. I would not have a high hope for fix from Intel devs, considering bugginess if the game.

**Comment by Nidzhun** [comment]
I can show my expirience with this game. All settings set to low and vsync disabled. I have i7 12700k, ddr5 6000mhz, ssd Samsung 980 pro, arc a770 le, Windows 11 23h2. What i can say, playable with some graphical glitches and artefacts=/

[](https://youtu.be/rfdOu0DFDQA)

**Comment by Wah007** [comment]
I've just got the Arc A770 16GB card and have just discovered that Just Cause 4 has really bad performance with this card. I'm getting 22fps maximum. My old 3060ti got the full 60fps with Vsync on and it ran great.

I was hoping there would be a fix by now, but it seems there is not.

**Comment by Nikaim** [comment]
On 31.0.101.5185 driver perfomace at max setting boost to 85-100 FPS.
[Video}(https://youtu.be/rmSZxIIXgsA?si=wY4-P1F6bxCdD19J)

**Comment by Pashamolochko** [comment]
Hello, the frame rate has increased by the new driver announced in the release, thank you very much for the work done
