### ISSUE TITLE
Fortnite getting poor performance with Windows 11 update

### ISSUE THREAD

**Issue by aengus126** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#652]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Fortnite

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 5600x

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

31.0.101.5122

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13762680/ssulog.txt)

### Description and steps to reproduce [Required]

My current GPU Driver is 31.0.101.5084, not 31.0.101.5122. I was given no other options to select. 

Yesterday I upgraded to Windows 11 from a PC that was already on Windows 10 Pro. Last night I was running Rocket League just fine and didn't really notice anything. However, this morning when I tried playing fortnite, I found that I was only getting like 30 fps and it kept dipping into laggy unplayable bits. 

I tested Minecraft and GTA V as well, and they are both running just fine at their respective fps and gpu utilization. However, specifically just fortnite has given me the issue. I used to get about 120 frames on high settings, but now no matter what settings I use it's less than 60. My GPU is also at 80% utilization when playing according to task manager. 

I tried testing this in DirectX12 as well, but Fortnite wouldn't let me. 

Fortnite with fps counter in the top right. This is on low graphics settings:
![screenshot 1 low graphics](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/78571650/b29402eb-c9e2-4d2a-ac99-dabb1f1b4c6e)

Fortnite with GPU statistics: 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/78571650/327b2a6d-784e-4a82-b215-d1fde38023b5)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/78571650/e9d6d928-d719-4f1f-9fdf-b2f07defe0bc)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/78571650/ed503c30-00bf-4c56-a9b9-9ba41e08a081)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/78571650/f010f066-12f0-480a-9146-4397ed838bf0)

### Device / Platform name

N/A

### Crash dumps [Required, if applicable]

N/A

### Save game

N/A

**Comment by aengus126** [comment]
I tried uninstalling and reinstalling my drivers, which didn't help. I also tried uninstalling Fortnite and reinstalling it, with no luck either.

**Comment by Arturo-Intel** [comment]
@aengus126 Hey, thanks for sharing this.

After some experimentation, I was unable to reproduce this behavior. 
Following your configuration (1080p, Low graphics set, dx11), I was getting around 120fps
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/f34ac592-02bd-474e-9835-72ba9dda6546)
Here's the video:
https://youtu.be/09s98Fkpgfo
As you can see the FPS is really great with this config. 

Don't mind that horrible 5% stuttering,  it is because I was recording the gameplay and getting the fps data at the same time.
If I do not record, the stuttering is below 1%, if any

I am wondering, did you use [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html)to reinstall the driver?

--r2

**Comment by aengus126** [comment]
Thanks Arturo, I just used DDU and booted into safe mode to remove the drivers. Then I used the [Intel Drivers Site](https://www.intel.com/content/www/us/en/products/sku/227954/intel-arc-a750-graphics/downloads.html) to reinstall the drivers because ARC control has been giving me some issues. I went back into Fortnite and I am still getting poor FPS, pretty much the same as before. 

I'll try a few more things out on my own to see if I can get if fixed. Just curious, when you had tried reproducing the issue, were you starting on Windows 10 and then upgrading it to Windows 11, or did you just start on Windows 11? I can't imagine it would make a difference but that's been the only thing I've assumed is what broke it so far. Thanks!

**Comment by Arturo-Intel** [comment]
@aengus126 I just start on Windows 11.  I don't think it will make a difference but who knows...

**Comment by aengus126** [comment]
I ended up doing a fresh install of Windows and that did the trick. I created a windows 11 bootable media drive and then wiped my ssd clean and reapplied the OS. Everything runs fine now. 
It kinda sucks that I had to go through all that just for Fortnite to work better but I understand the Intel GPU brand is pretty new. Or maybe there is just a seriously random bug on Window's end with upgrading windows 10 to windows 11 lol. 
Let me know if you need anything more from me. Thanks!
