### ISSUE TITLE
GPU effects in Davinci Resolve Studio have a flashing bar up the top of exports

### ISSUE THREAD

**Issue by BuyMyMojo** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#653]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Davinci Resolve

### Processor / Processor Number [Required]

5900x

### Graphic Card [Required]

A770

### GPU Driver Version [Required]

31.0.101.5084

### Rendering API [Required]

- [ ] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU_2023-12-14.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13764208/SSU_2023-12-14.txt)

### Description and steps to reproduce [Required]

Video displaying the artifact: https://www.youtube.com/watch?v=8syOoEmRDk0

- Open Davinci Resolve Studio (Paid version for GPU acceleration support)
- Restore provided [project archive (1.18GB)
](https://drive.google.com/file/d/19dmMLOPmVQow_NIOUInQs1tTEMIkVrYv/view?usp=sharing)- Open projects (It has the invert colours effect applies to some clips which is GPU accelerated)
- Go to Deliver Tab
- Export with any settings

Video guide:

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/0bed5fab-cd87-4cf0-b12a-81c9f85043e9

**Comment by Vivek-Intel** [comment]
@BuyMyMojo let me try reproduce at my end. Meanwhile, can you share application version that you are using? are you observing this issue in recent drivers only?

**Comment by BuyMyMojo** [comment]
Davinci Resolve Studio 18.6.3

I've been experiencing this for a couple driver and resolve updates. I'm not exactly sure when it started but I'd say at least 3 or 4 driver versions

**Comment by Vivek-Intel** [comment]
> Davinci Resolve Studio 18.6.3
> 
> I've been experiencing this for a couple driver and resolve updates. I'm not exactly sure when it started but I'd say at least 3 or 4 driver versions

I see there is 18.6.4 available, did you get a chance to update and check ?

**Comment by Vivek-Intel** [comment]
@BuyMyMojo I tried to simulate with 101.5084 and 18.6.4 and I can see there is black bar corruption in exported videos.
Can you try once with updated app.
[no repro video.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13775874/no.repro.video.zip)

**Comment by BuyMyMojo** [comment]
> @BuyMyMojo I tried to simulate with 101.5084 and 18.6.4 and I can see there is black bar corruption in exported videos. Can you try once with updated app. [no repro video.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13775874/no.repro.video.zip)

It can't just be a render of the video, it requires a timeline with GPU accelerated effects. 
If you export `Timeline 1` from that zip there should be the black bars or if you just apply the invert colour effect like so:

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46948241/8f679eb2-20b7-426b-8b76-6f0d9e4413e0

**Comment by Vivek-Intel** [comment]
@BuyMyMojo thanks. I actually did try to play around and add some effects, also checked Arc GPU is selected from preference options in App but I could not see black bar that you are observing in exported video. let me know if I am missing something.

I imported all media from your project and created timelines with effects as you suggested.
uploaded exports [here](https://www.youtube.com/watch?v=BLGhTxvMe-g) and [here](https://www.youtube.com/watch?v=XMtw11Gdvck) for your ref only.

can you confirm that you are using latest version ?

**Comment by BuyMyMojo** [comment]
Got a chance to update, that did fix it. sorry for the trouble
