### ISSUE TITLE
Very low performance on Ghost Recon Wildlands

### ISSUE THREAD

**Issue by MillionsToOne** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#654]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Ghost Recon Wildlands

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [X] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 5 3600 6-Core Processor

### Graphic Card [Required]

Intel Arc A770 LE 16GB

### GPU Driver Version [Required]

31.0.101.5084

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13788220/igcit_ssu.txt)

### Description and steps to reproduce [Required]

1. Install and start the game
2. Set any graphics settings since it runs poorly regardless
3. Get to experience a game that runs at max 50fps with average 20-30fps. Even my GTX 1660 Super runs it at 80fps

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

As I mentioned before, even with every possible setting on low with 1.00x resolution scale, the performance is horrible.

**Comment by MillionsToOne** [comment]
I marked Vulkan also, since I also tried DXVK and got the same result

**Comment by MillionsToOne** [comment]
That's good compared to my 30fps at 1080p

**Comment by Ilya-intel** [comment]
@MillionsToOne 
We're currently working on performance improvement for this title.
I'll post here when a driver with the fix is posted.

**Comment by ewahl-osc** [comment]
Is there an internal report # for this one?

**Comment by Ilya-intel** [comment]
@ewahl-osc 
No, however we expect performance improvements across the majority of DX11 titles, you can see the list of games being improved in the release notes like here:
<img width="709" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/6012f623-772d-46fd-b50f-5f1394d5bf0d">

**Comment by Ilya-intel** [comment]
Hey guys @ewahl-osc @MillionsToOne ,
We have finally released big fix for DX11 titles (you can download the 101.6127 driver [here](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)).
This game also shows much smoother results.
Could you also try it and confirm?
![GR](https://github.com/user-attachments/assets/92d2c15c-4a78-4af3-8ba1-287677e42850)

**Comment by ewahl-osc** [comment]
well now!   That is indeed a rather nice increase in frames!  ( Sad to see it wasn't advertised in the driver notes. )
The most important point here is a 55% increase in the minimum. That is FANTASTIC to see. 

 BENCHMARK STATISTICS 01/05/2024 21:49:08 GPU 1 Driver: 31.0.101.5445
FPS:
Average: 45.37
Min: 30.60
Max: 55.89

today:
BENCHMARK STATISTICS 21/10/2024 20:20:53 GPU 1 Driver: 32.0.101.6127
FPS:
Average: 70.92
Min: 55.23
Max: 79.37 

very high settings, 1440p, etc.

**Comment by Ilya-intel** [comment]
@ewahl-osc 
Yeah, significant improvement for this game!
All, I'll be closing this thread, feel free to open new one for another issues.

**Comment by MillionsToOne** [comment]
Thank you
