### ISSUE TITLE
Either unify the driver version number or simply release a separate package for Core Ultra iGPU.

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#655]
### Application [Required]

Arc driver installer

### Processor / Processor Number [Required]

irrelevant

### Graphic Card [Required]

intel Arc A770

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [X] Windows 11 22H2
- [X] Windows 11 21H1
- [X] Windows 10 22H2
- [X] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Recent driver release 5081+5122 / 5084+5122 took a bizarre naming scheme. Since you guys have been able to unify all the drivers for UHD iGPU and Iris Xe and Arc dGPU, why can't you just also unify the driver for the Core Ultra Arc iGPU? If your purpose is to highlight the new Core Ultra product due to marketing concern, simply release a separate driver installer with a very distinct version number and don't stick so close to the existing intel GPU driver lineage. The two-version method is very anti-consumer and kind of disrespecting the vast existing user base of various intel GPUs that are not Core Ultra iGPUs.

**Comment by Gabriela-Intel** [comment]
Thanks for the feedback @Susie1818. This is actually something we are already actively working on. We know listing out the 2 versions is not the most ideal. :) But this is the best way we could get the driver for all of those products on intel.com on a single landing page.

I don't have an ETA for when it will be 1 unified driver again, but trust me this is only temporary.

@IGCIT Can you close?
