### ISSUE TITLE
Something like Nvidia DLDSR

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#656]
### Application [Required]

All games

### Processor / Processor Number [Required]

intel Core i5-13500

### Graphic Card [Required]

intel Arc A770

### Rendering API [Required]

- [X] Vulkan
- [X] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [X] Windows 11 22H2
- [X] Windows 11 21H1
- [X] Windows 10 22H2
- [X] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Nvidia DLDSR (Deep Learning Dynamic Super Resolution) is an AI downscaler that allows applications to render with an internal resolution that is actually higher than the physical native resolution of the monitor. This is quite useful for the mainstream 1080p monitors with many old games that were not very GPU demanding where our GPU has some headroom to actually work at a high resolution with relative ease. Downscale ratios(presets) are usually 1.33/1.5/2.0 which translate to 1440p/1620p/2160p (internal resolution) downscaling to 1080p. This feature (Nvidia DLDSR) has been proven improving visual quality for 1080p monitors. Simply put, it is just an anti-aliasing solution that produces better visual quality than many AA solutions provided by the game engines (FXAA, MSAA, TAA).

It is a driver level feature, so it doesn't have to be manually integrated into a game by the game devs like XeSS, and it can be applied univerally to any game.

**Comment by Gabriela-Intel** [comment]
Thanks for the feedback! We'll pass this along to the team.

@IGCIT Can you close this please? Thanks!
