### ISSUE TITLE
[Performance Telemetry]: Incorrect report of CPU Activity

### ISSUE THREAD

**Issue by vitduck** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#657]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel(R) Performance Telemetry

### Processor / Processor Number [Required]

AMD Ryzen 7 5800x

### Graphic Card [Required]

Acer Bifrost A770 

### GPU Driver Version [Required]

31.0.101.5122

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ISSU.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13804664/ISSU.txt)

### Description and steps to reproduce [Required]

There is a large discrepancy between `CPU Activity` reported by Intel Arc with respect to one from RTSS. 
The example below is from Sleeping Dogs: Definitive Edition (1980x1080) 

![Screenshot 2024-01-01 222504](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/575950/78d1c9a2-49af-4898-b518-19b5579cc152)

Both apps report almost identical telemetry sans `CPU Activity`. 
This observation extends to other games, in which Intel Telemetry consistently reports too low `CPU Activity`. 
A `1%` CPU usage is unrealistic if not outright wrong even if the game is GPU-bottleneck.

**Comment by Felipe-Intel** [comment]
Hello @vitduck this is expected behavior. Please check [this article](https://www.intel.com/content/www/us/en/support/articles/000094779/graphics.html)
