### ISSUE TITLE
Ghosts 'n Goblins Resurrection Very low performance/ Unable to get Exclusive FullScreen

### ISSUE THREAD

**Issue by Saracchini** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#66]
#### Checklist [README]

- [x] Device is not undervolted nor overclocked.
- [x] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [x] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Ghosts 'n Goblins Resurrection
---
#### Game Platform [Required]
- [x] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
---
#### GPU Driver Version [Required]
- [ ] 27.20.100.9616 (*latest*)
- [x] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [x] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [x] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1.  Open game
2.  Go to Options. Select FullScreen
3. Game still is in windowed mode

Game performance is also very low (1 fps at 720p, 10 fps at 640x480). 

---
#### Device / Platform [Optional][Recommended]

GPD WIN3 i7 16 GB
---
#### Game Settings [Optional][Recommended]

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---
#### Windows mini dump (*small memory dump*) (*if available*) [Optional][Recommended]

---

**Comment by RSaracchini** [comment]
Tested with latest beta version: 30.0.100.9667
Issue still persists.

**Comment by RSaracchini** [comment]
Full-screen issues and performance issues are solved if the following settings are used  **config.ini** configuration file.
```
[Render]
PCTargetAPIFallback=Disable
Capability=DirectX12
TargetPlatform=DirectX11
UseDXILShader=Disable
UseOptimizeShader=Enable
LastCrashReport=
UseVendorExtention=Enable
[RenderConfig]
WindowMode=1
VerticalSync=0
GraphicsRendering=2
Resolution=2
RefreshRate=0
```

**Comment by Valkirie** [comment]
> Full-screen issues and performance issues are solved if the following settings are used **config.ini** configuration file.
> 
> ```
> [Render]
> PCTargetAPIFallback=Disable
> Capability=DirectX12
> TargetPlatform=DirectX11
> UseDXILShader=Disable
> UseOptimizeShader=Enable
> LastCrashReport=
> UseVendorExtention=Enable
> [RenderConfig]
> WindowMode=1
> VerticalSync=0
> GraphicsRendering=2
> Resolution=2
> RefreshRate=0
> ```

Interesting one. Can you also share the default value so that we can compare and understand what's the actual reason ? Was that the DirectX version ?

**Comment by RSaracchini** [comment]
The default (and you cannot change it through the game, it must be manually edited) has those two variable set:

```
TargetPlatform=DirectX12
UseDXILShader=Enable
```

The remainder was left unchanged.
By setting those variables to respectively **_DirectX11_** and **_Disable_**, the game is able to set exclusive full-screen and run fine.

**Comment by IGCIT** [comment]
@Saracchini is this still valid?

**Comment by Saracchini** [comment]
Yes, the game is incredibly slow and unplayable if you use the default settings even in driver 1960. Changing the renderer to DX11 and disabling DXIL shader option (it can be only done through editing config.ini in the executable's folder, it's not possible in-game in any form), and the game is perfectly playable and runs with little effort.

**Comment by Saracchini** [comment]
Also, the game is able to set fullscreen exclusive with the edited config.ini file I mentioned without any issues. It fails consistently if I do use the default settings. So, it may not be a portrait screen issue.

**Comment by estebanr863** [comment]
Hi @Saracchini 

Just wanted to let you know that this issue has been marked as “future” in our internal bug tracking tool. This means that the issue will not be worked on for the time been, as the development team has limited resources and tries to focus first on the issues affecting the most users. This game has gotten [less than 40 peak users in the last six months](https://steamcharts.com/app/1375400), making any issue specific to this game low priority to fix. If in the future our development team has the resources available to come back to this issue, it may be fixed. However, we cannot commit to any timeframe for this.

Since you have determined a [workaround](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/66#issuecomment-863286050) for this issue by editing the config.ini game file, my advice is to continue using that workaround.

**Comment by EstebanIntel** [comment]
Hi @Saracchini, unfortunately, due to the development team limited resources and needing to work on other higher priority game issues, this issue won't be fixed.
