### ISSUE TITLE
Flashing blocky artifacts with hardware encoded video at high GPU usage

### ISSUE THREAD

**Issue by BuyMyMojo** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#660]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel arc control + DaVinci Resolve + OBS

### Processor / Processor Number [Required]

5900x

### Graphic Card [Required]

A770

### GPU Driver Version [Required]

31.0.101.5084

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU_2024-01-02.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13810047/SSU_2024-01-02.txt)

### Description and steps to reproduce [Required]

I believe when using hardware encoding with 100% GPU usage causes these artifacts: https://www.youtube.com/watch?v=sPXX1c9VtEA goto [00:01:25](https://youtu.be/sPXX1c9VtEA?t=85) for a good look at it

The starting 5 minutes and 30 seconds or so where recorded with OBS and the rest of the video was a full screen recording using Intel Arc Control (The third time code is where I swapped)

It has happened to me in the past when exporting a DaVinci resolve timeline with heavy effects but went away when I swapped to software encoding (Still 100% GPU usage as the effects where all still GPU accelerated)

These are specifically at 4K and using the AV1 encoder.

### Application / Windows logs

OBS stopped recording twice when I was using that originally and here is all the log said about that stop:

```
21:29:22.874: ==== Recording Start ===============================================
21:29:22.874: [ffmpeg muxer: 'adv_file_output'] Writing file 'E:/4K/2024-01-02_21-29-22.mp4'...
21:31:44.863: Stopping recording due to OutputTimer timeout
21:31:45.077: [ffmpeg muxer: 'adv_file_output'] Output of file 'E:/4K/2024-01-02_21-29-22.mp4' stopped
21:31:45.077: Output 'adv_file_output': stopping
21:31:45.077: Output 'adv_file_output': Total frames output: 8521
21:31:45.077: Output 'adv_file_output': Total drawn frames: 8532
21:31:45.077: ==== Recording Stop ================================================
```

Full log file:

[2024-01-02 20-20-30.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13810062/2024-01-02.20-20-30.txt)

**Comment by BuyMyMojo** [comment]
while testing for #662 with version `31.0.101.4953` I can confirm that the issue still persists there too when the recording works anyway

**Comment by BuyMyMojo** [comment]
Seems to possibly be fixed with `31.0.101.5085` will report back if something comes up later

**Comment by Gabriela-Intel** [comment]
@BuyMyMojo Have you seen this issue occur again since your last update? Let us know!

**Comment by Gabriela-Intel** [comment]
@IGCIT I don't see any updated on this. Can we close? Thanks!
