### ISSUE TITLE
CoD:Vanguard - poor performance

### ISSUE THREAD

**Issue by jumofogit** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#661]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Call of Duty:Vanguard

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-1155G7

### Graphic Card [Required]

Iris Xe

### GPU Driver Version [Required]

31.0.101.5084

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [X] Other (Please specify)

### Other Windows build number

Windows 10 2004

### Intel System Support Utility report

[vng.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13822245/vng.txt)

### Description and steps to reproduce [Required]

Just launch the game of Shi no Numa, for an example.
![Снимок экрана (15)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116519368/3ff00415-5b81-47d5-b467-ccd7539046c6)
![Снимок экрана (16)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116519368/86d33fea-244c-4894-a0c5-086e4eb4d187)
![Снимок экрана (17)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116519368/390065ac-bbbb-4bc1-9ef2-af7eeaae071f)
![Снимок экрана (18)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116519368/4bb77139-2011-4e08-856e-c511e1ec1d8f)
![Снимок экрана (19)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116519368/f1951a9f-eb74-441f-8485-73443513f586)
![Снимок экрана (20)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116519368/7183594b-fc25-4a32-84eb-7861474a36bb)

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![Снимок экрана (20)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116519368/a4d2f035-9435-4e73-9610-d1d010049e26)
![Снимок экрана (17)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116519368/bfa7bd4d-1a62-40e9-85ea-1d22efa7274b)
![Снимок экрана (18)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116519368/10452680-5258-4a19-a3cd-3b693d734f3c)
![Снимок экрана (19)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116519368/bd9885d5-82e0-4476-a674-dc89f37cc306)

### Device / Platform name

MSI Modern 14 B11MOU

### Crash dumps [Required, if applicable]

no

### Save game

no

**Comment by Ilya-intel** [comment]
@jumofogit 
The Game requires at least GTX 960 GPU. Iris XE with 80 EU is below this minimum system requirement, so this performance is expected on integrated graphics.

**Comment by Ilya-intel** [comment]
@IGCIT Kindly close this thread since there are no more comments.

**Comment by jumofogit** [comment]
no shit, Sherlock
thank you
