### ISSUE TITLE
poor performance dying light 

### ISSUE THREAD

**Issue by Joe-Mil16** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#663]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Dying Light

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 5 3600

### Graphic Card [Required]

ASRock Intel Arc A770 Phantom Gaming D OC

### GPU Driver Version [Required]

31.0.101.5084

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [x] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[3.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13843116/3.txt)

### Description and steps to reproduce [Required]

I have poor performance and freezes in this game and dxvk does not help but only makes it worse only when I reduce the graphics settings to medium and low I get 60 fps

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

high

**Comment by Gabriela-Intel** [comment]
Hi there @Joe-Mil16. Have you tried using DDU yet? I just checked the performance on a Ryzen 9 3900X + A770 system and I'm averaging around ~140 FPS with all High settings (2160x1440) using the latest Arc driver.

**Comment by Joe-Mil16** [comment]
Hello. Yeah i use DDU and last driver dont help me. I have 40-55 fps in the game on high settings

**Comment by Gabriela-Intel** [comment]
Hmm have you tried doing a clean OS install?

**Comment by Joe-Mil16** [comment]
No, but i want clean OS install

**Comment by Gabriela-Intel** [comment]
Can you please perform a clean install then? Instructions [here](https://www.microsoft.com/en-us/windowsinsider/cleaninstall) (please save any work and back up your PC prior to a clean install).

**Comment by Gabriela-Intel** [comment]
Any update @Joe-Mil16?

**Comment by Gabriela-Intel** [comment]
@IGCIT Proceed with closing.
