### ISSUE TITLE
Game frame rate is very low -- Barony

### ISSUE THREAD

**Issue by YeTianXingShi** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#664]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Barony

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-13500

### Graphic Card [Required]

ARC A770

### GPU Driver Version [Required]

31.0.101.5084

### Rendering API [Required]

- [ ] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSUlog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13843560/SSUlog.txt)

### Description and steps to reproduce [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/42585691/be8cfe5a-a5e9-4fad-a25c-2ccaf3edf808)
When you enter the game with the default settings, you will find that the game frame rate is very low, less than 30 frames. Modifying the rendering resolution will not cause the frame rate to change. At the same time, CPU and GPU usage are both low.

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

3840x2160

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

default setting

### Device / Platform name

X86 PC

**Comment by Nidzhun** [comment]
Hello! Try to disable vsync, that step solve problem with low fps for me. May be that is game compatibility problem.

**Comment by YeTianXingShi** [comment]
> Hello! Try to disable vsync, that step solve problem with low fps for me. May be that is game compatibility problem.

I tried it and the framerate didn't change.

**Comment by Ilya-intel** [comment]
Hey @YeTianXingShi ,
Developers are currently working on this issue.
Bug ID for reference: 22019100884

I'll post updates in this thread.

**Comment by Ilya-intel** [comment]
Hi @YeTianXingShi ,
Our driver team is targeting the most popular games and apps to focus our efforts on providing a high quality, stable experience for the broadest set of users. 
We will continue to improve our software performance and compatibility throughout 2024 and beyond.
While we can’t accommodate your request at this time, please watch [this article](https://www.intel.com/content/www/us/en/support/articles/000097188.html) on our website for any possible changes to this situation.
This thread will be closed.
