### ISSUE TITLE
Naraka Bladepoint Crash while playing

### ISSUE THREAD

**Issue by YUCLing** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#666]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Naraka Bladepoint

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i9-12900KS

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

31.0.101.5084

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13851011/igcit_ssu.txt)

### Description and steps to reproduce [Required]

1. Start the game as you would
2. Play it until it crashes

Tried with both DirectX 12 and 11.

~~FYI: The system has been up for about 5 days, not sure if this affects this tho.~~ Still getting this after a restart.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

3840x2160

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/5d927708-b932-4dbf-94e3-fa80bf51986a)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/c6ea9524-f7bc-4552-b36c-f27986d0a7cf)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/0429ffc2-0a4b-480c-b520-1296f7fe35e6)

### Crash dumps [Required, if applicable]

[WindowsErrorReports.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13851018/WindowsErrorReports.zip)

This dump was captured between switching from screen output to Remote Desktop, I'm not quite sure if it's affected by the switch or not due to the short time window.
[WATCHDOG-20240108-1240.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13856564/WATCHDOG-20240108-1240.zip)

**Comment by YUCLing** [comment]
From half an hour to two hours.

I'm not quite sure what settings are also contributed to the crash.

I also enabled the game's recording functionality, from what I see it made my game a bit more unstable because of the lag after game startup.

I can't stand with this now so I just uninstalled the driver with DDU two days ago and installed a newer version. I haven't played the game much since then due to lack of time.

**Comment by YUCLing** [comment]
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/aaf0eaa1-6e96-4556-8186-0dc5708e546a)
By the way, I got a message saying the hardware doesn't support encoding sometimes I launched the game. The system will also freeze for seconds before this appears.

**Comment by YUCLing** [comment]
Does the dump tell anything about this? Currently I'm using Fedora 39 with GE-Proton 8.27 and the game is not crashing now. If this is OS-specific, how can I find out the root cause?

**Comment by Ilya-intel** [comment]
@YUCLing 
Nothing rather than the driver stopped responding.
This looks like OS related indeed. I've just played for 2 hours without crashes.
Could you try:
1. Play without memory profiles (XMP).
2. Check System File integrity (for example: https://support.microsoft.com/en-us/windows/using-system-file-checker-in-windows-365e0031-36b1-6031-f804-8fd86e0ef4ca)

**Comment by YUCLing** [comment]
I have installed the latest driver (5186, with DDU uninstalled the previous one), and the crash is not happening now.
