### ISSUE TITLE
Trains Sim World 4 (the infamous DeviceLost directx error) 

### ISSUE THREAD

**Issue by paulober** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#672]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Train Sim World 4

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X

### Graphic Card [Required]

Intel Arc A770 LE (16GB)

### GPU Driver Version [Required]

31.0.101.5085

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13929318/igcit_ssu.txt)

### Description and steps to reproduce [Required]

- Start the game
- Go to my trains
- Go to play scenario
- Go to Dresden Nahverkehr
- Select the frist beginner one (or any other)
- Press start
- The game freezes after some seconds but the music keeps playing
- in the background a unreal engine crash dump submit window will popup

I have this issue with many levels when trying to load them.

I also noticed a different issue i have when a level would load (it might be related to this one).
The game mostly has very poor FPS, about 20-30 but sometimes it's hovering between 80-90 fps but with many stutters.
You might think, thats because the GPU has bad performance in this game but no. During either of these fps ranges the GPU activity is about 50% on average. The CPU load is between 5% and 40%. Only 7GB VRAM is used and the system ram is only 50% occupied. Here you can see 23fps (to left hand corner) but a GPU activity of 30%???
![Screenshot 2024-01-13 185714](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44974737/e31a001d-f29d-41f9-a24f-1d33030fcf6e)

These both screenshots show the same issue but with 24fps
![Screenshot 2024-01-13 202700](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44974737/3e09eca8-a858-48a7-9c28-73cc8ac29e58)
![Screenshot 2024-01-13 202713](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44974737/0bf40fb7-00ab-4df6-bc5c-31be2b3191fb)

I guess the game is running DirectX 11 but someone told me that you can run it with -DX12 in steam launch options for DirectX 12 but this mode has some flickering. (not tested)
The game is running UE4 engine.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

3440x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Quality of the foliage: HIGH
Shadow quality: HIGH
Quality of the effects: HIGH
Quality of the sky: HIGH
Fog quality: ULTRA
Quality of the post-process: ULTRA
Render distance quality: ULTRA
Texture quality: ULTRA
Max. FPS: 144
Anti-aliasing: TAA
V-Sync: On/Off (same result with both)
Screen percentage: 100%

### Device / Platform name

MSI B550m pro-vdh wifi

### Crash dumps [Required, if applicable]

LowLevelFatalError [File:Unknown] [Line: 198] Unreal Engine is exiting due to D3D device being lost. (Error: 0x887A0020 - 'INTERNAL_ERROR')

TrainSimWorld
TrainSimWorld
TrainSimWorld
TrainSimWorld
TrainSimWorld
TrainSimWorld
TrainSimWorld
TrainSimWorld
TrainSimWorld
TrainSimWorld
TrainSimWorld
kernel32
ntdll

**Comment by paulober** [comment]
Also i noticed the Task-Manager doesn't show GPU-Activity 3D or something like this for the game process...

**Comment by paulober** [comment]
With the -DX12 switch i was able to load the specified level but still have the same performance issues.

**Comment by Felipe-Intel** [comment]
hello @paulober Can you check if this happens with our [newest driver 101.5186](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)?

**Comment by paulober** [comment]
> hello @paulober Can you check if this happens with our [newest driver 101.5186](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)? 

Unfortunately no. Though not all tracks have the underutilization issue.

**Comment by Felipe-Intel** [comment]
hello @paulober I was able to reproduce the issue. I will be submitting a ticket to our development teams. Stay tuned for news.

**Comment by paulober** [comment]
Yesterday i got artifacts in the top 5% of my screen with the rest getting black. 5sec later both screens went black and even with connecting and disconnecting i couldn't get the screens to work again other than hard rebooting my PC. I guess either the driver or the gpu crashed.

**Comment by Felipe-Intel** [comment]
Hello @paulober I don't see the issue anymore with driver [32.0.101.5762](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html). Could you please check on your side?

**Comment by Felipe-Intel** [comment]
Hello @paulober we haven't hear from you for confirmation about this fix. We will proceed to close this ticket. If you still have problems with the game, please open a new report and refer to this one.

**Comment by paulober** [comment]
> Hello @paulober I don't see the issue anymore with driver [32.0.101.5762](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html). Could you please check on your side?

Sorry for the delay, no i did not but i was rare so maybe i'll reopen in the future if i occurs again.
