### ISSUE TITLE
Standby issue intel driver gfx_win_101.5085_101.5122

### ISSUE THREAD

**Issue by 21747117** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#673]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

gfx_win_101.5085_101.5122

### Processor / Processor Number [Required]

Intel Core i7-14700 K

### Graphic Card [Required]

Intel ARC A770 LE 16GB

### GPU Driver Version [Required]

31.0.101.5085

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

N/A

### Description and steps to reproduce [Required]

Simply let windows enter standby mode by letting it go through the three steps.

It will turn off screen in 3 minutes then back on

It will then try to go to next step ten minutes after the 1st step above, but it won't engage since PC will just shut down.

### Device / Platform

ASUS Z790-H, i7-14700K, Crucial DDR5 Pro 32GB Kit, ARC A770 LE

**Comment by 21747117** [comment]
Updated my Intel ARC GPU drivers to

gfx_win_101.5085_101.5122

For the last two days when the PC tries to engage standby mode it immediately shuts down.

I confirmed it's an issue with the above mentioned drive, when I rolled back to the previous

gfx_win_101.5084_101.5122

The issue has since disappeared/resolved

**Comment by Ilya-intel** [comment]
Hi @21747117 ,
Interesting, could you run the energy report by executing following command in the admin console: `powercfg /energy`?
And send the generated .html report here.

**Comment by 21747117** [comment]
> Updated my Intel ARC GPU drivers to
> 
> gfx_win_101.5085_101.5122
> 
> For the last two days when the PC tries to engage standby mode it immediately shuts down.
> 
> I confirmed it's an issue with the above mentioned drive, when I rolled back to the previous
> 
> gfx_win_101.5084_101.5122
> 
> The issue has since disappeared/resolved

*Update*

I run some more tests and, ...Now the gfx_win_101.5085_101.5122 driver has been working with no issue.

here is what I did.

I clean installed gfx_win_101.5084_101.5122 driver using the in-driver option.

Then installed gfx_win_101.5085_101.5122 driver on top I did not perform clean install.

was working fine then I decided to remove gfx_win_101.5085_101.5122 driver and run a clean install of it.

and all has been well ever since.

**Comment by 21747117** [comment]
> Hi @21747117 , Interesting, could you run the energy report by executing following command in the admin console: `powercfg /energy`? And send the generated .html report here.

<html>
<body>
<h2 style="color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Power Efficiency Diagnostics Report</h2>
Computer Name | -
-- | --
Scan Time | 2024-01-19T03:50:00Z
Scan Duration | 60 seconds
System Manufacturer | ASUS
System Product Name | System Product Name
BIOS Date | 12/08/2023
BIOS Version | 1801
OS Build | 22631
Platform Role | PlatformRoleDesktop
Plugged In | true
Process Count | 195
Thread Count | 2684
Report GUID | {591169c7-c778-4fc4-9425-1af525993ebc}

<span></span></div></div></div><div class="log-entry" style="margin-bottom: 1em; color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: x-small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="

                            info-log-entry

                        " style="background-color: rgb(255, 255, 255); padding: 4pt;"><div class="log-entry-header" style="font-weight: bold;">Device Drivers:Analysis Success</div><div class="log-entry-content" style="margin: 2pt;"><div class="log-entry-description">Analysis was successful. No energy efficiency problems were found. No information was returned.</div></div></div></div>
</body>
</html>

**Comment by Ilya-intel** [comment]
@21747117 
Sooo, am I correct assuming that now everything is fine, and another driver installation helped?

**Comment by Ilya-intel** [comment]
@IGCIT seems to have been abandoned. Could you close this one?
