### ISSUE TITLE
Hard West 2 anisotropic filtering on, configuration option, causing texture issues

### ISSUE THREAD

**Issue by CutePotato** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#676]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Hard West 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Other game platform

Local

### Processor / Processor Number [Required]

AMD Ryzen 5 3600

### Graphic Card [Required]

Arc 770 16GB

### GPU Driver Version [Required]

31.0.101.5085

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13949330/ssulog.txt)

### Description and steps to reproduce [Required]

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/26540424/10b077ad-4e74-4c14-95bd-141bb3243c1b

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Doesn't matter, anisotropic filtering is what causing the texture issue

**Comment by rmorera-intel** [comment]
Thank you for reporting this issue. Our priority is to target the most popular games and apps to focus our efforts on providing a high quality, stable experience for the broadest set of users. We will continue to improve our software performance and compatibility throughout 2024 and beyond. 

While we can’t accommodate your request at this time, please watch [this article](https://www.intel.com/content/www/us/en/support/articles/000099646.html) on our website for any possible changes to this situation.

I'll close this bug report for now.
