### ISSUE TITLE
Intel Graphic Command Center using port 5000

### ISSUE THREAD

**Issue by kiwiufa** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#678]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Graphic Command Center

### Processor / Processor Number [Required]

i7-12700H

### GPU Driver Version [Required]

Other (Please specify)

### Other GPU Driver version

31.0.101.4887

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [X] Other (Please specify)

### Other Windows build number

Version	10.0.22621 Build 22621

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13971049/ssulog.txt)

### Description and steps to reproduce [Required]

Intel Graphic Command Center consistently starts on port 5000 and since it is in the StartUp apps by default if basically start every time you turn your computer on.
Port 5000 is used by almost all developers on Windows for local dev environment. Having Intel Graphic Command Center occupying that port results in a huge headache for a lot of people

**Comment by freak2fast4u** [comment]
Out of curiosity, what dev tool/server uses port 5000 by default ? 
As a Java dev myself our dev servers usually use ports or 8000, 8080 by default. 

It reminds me of a time where Skype would hog port 80 while running as well ... *doh!*

**Comment by rmorera-intel** [comment]
Hi @kiwiufa 
Our IGCC team reviewed this feedback and concluded at this moment it is not feasible to switch port on IGCC. Additional data also showed that there are several other services that use port 5000 as seen here:

![MicrosoftTeams-image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/89094170/ced6f521-2df6-4a1c-a9c7-acc491fb57fa)

Thank you for taking the time to pass on this feedback to us.

Best Regards,

**Comment by JulijaRamoskiene** [comment]
This indeed caused me some headache today. Had to kill IGCC process. Looking into uninstalling it.
