### ISSUE TITLE
Left 4 Dead 2 crash when shader setting is above medium

### ISSUE THREAD

**Issue by zrmdsxa** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#679]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Left 4 Dead 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 7600X

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

31.0.101.5074

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13972443/ssu.txt)

### Description and steps to reproduce [Required]

1. Set shader setting to high or very high.
2. Start any map

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5502880/71d3c6cb-109d-409c-a54a-2dccc6935630)

**Comment by zrmdsxa** [comment]
people have brought it up before outside of github and still hasn't been fixed

2022-09-30 https://community.intel.com/t5/Intel-ARC-Graphics/Left-4-Dead-2-Game-Crashing/m-p/1418703
2023-04-10 https://community.intel.com/t5/Graphics/Poor-performance-of-Left-4-Dead-2/td-p/1474928

**Comment by Arturo-Intel** [comment]
@zrmdsxa thanks for sharing that info..
We are creating the case now.

Will come back with any news.

--r2

**Comment by Vivek-Intel** [comment]
@zrmdsxa Our engineering team had investigated this issue and it was concluded as a game issue. It can not be fixed from driver side so we recommend reporting this issue to the game developer. 
[knowledge article](https://www.intel.com/content/www/us/en/support/articles/000097972/graphics.html)

**Comment by Vivek-Intel** [comment]
@IGCIT please help close this thread.
