### ISSUE TITLE
Dragon Age Inquisition Crash

### ISSUE THREAD

**Issue by Rebusmind** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#68]
#### Checklist [README]

- [X] Device is not undervolted nor overclocked.
- [X] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [X] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Dragon Age Inquisition
---
#### Game Platform [Required]
- [ ] Steam
- [X] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]
i7-1165
---
#### GPU Driver Version [Required]
- [ ] 30.0.100.9667 (*latest*)
- [ ] 27.20.100.9616
- [X] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [X] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1. Start the game
2. Choose New Game
3. During the character creation it crashes randomly

---
#### Device / Platform [Optional][Recommended]

GPD Win 3

---
#### Game Settings [Optional][Recommended]

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---
#### Windows mini dump (*small memory dump*) (*if available*) [Optional][Recommended]

---
#### Game custom logs (*if available*) [Optional][Recommended]

![grafik](https://user-images.githubusercontent.com/9643886/123081565-5ed42180-d41e-11eb-962e-4e950c2914a7.png)

**Comment by IGCIT** [comment]
have you tried the latest beta driver?

**Comment by Rebusmind** [comment]
No, but as the game is nearly 10 years old I thought that it's pretty unrealistic that this does solve the issue.
But I saw that many people across all GPUs had problems like this. I'll try windowed fullscreen and lowered settings next to see if that helps.

**Comment by estebanr863** [comment]
Hi all,

We were able to reproduce this issue using the reported driver 27.20.100.9466. Then, we upgraded the driver to the latest 30.0.100.9955 (I always recommend doing a clean install https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html) and the issue is no longer present. Can you guys try this new driver and let me know?

**Comment by estebanr863** [comment]
@Rebusmind can you please test with driver version 30.0.100.9955?

**Comment by Rebusmind** [comment]
I tested the game (character creation, gameplay, cutscenes) and it ran perfectly fine, so I'll close this issue.
