### ISSUE TITLE
[Regression] D3D11VA to OpenCL interop is completely broken in 5186_5234 driver

### ISSUE THREAD

**Issue by nyanmisaka** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#680]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

FFmpeg / Jellyfin Media Server

### Processor / Processor Number [Required]

AMD Ryzen 7 5700G

### Graphic Card [Required]

Intel Arc A380 Graphics

### GPU Driver Version [Required]

31.0.101.5186

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14052463/igcit_ssu.txt)

### Description and steps to reproduce [Required]

1. Prepare a 1080p or 4k video. It can be any common video format such as H.264, HEVC or AV1.

2. Download and unzip the [jellyfin-ffmpeg6 6.0.1-1](https://github.com/jellyfin/jellyfin-ffmpeg/releases/download/v6.0.1-1/jellyfin-ffmpeg_6.0.1-1-portable_win64.zip), which is the video transcoder of [Jellyfin Media Server](https://jellyfin.org/).

3. Run the following command in CMD or PowerShell:
```
// Input file path is `C:\ANY_H264_HEVC_AV1_VIDEO.mp4`, you can change it
// Output file path is `C:\green_broken.mp4`, you can change it

ffmpeg.exe -init_hw_device d3d11va=dx11:,vendor=0x8086 -init_hw_device qsv=qs@dx11 \
-init_hw_device opencl=ocl@dx11 -filter_hw_device qs -hwaccel d3d11va -hwaccel_output_format d3d11 \
-threads 2 -autorotate 0 -i C:\ANY_H264_HEVC_AV1_VIDEO.mp4 -autoscale 0 \
-c:v hevc_qsv -preset veryfast -b:v 20M -maxrate 20M \
-vf "hwmap=derive_device=opencl,scale_opencl=format=nv12,hwmap=derive_device=qsv:reverse=1,format=qsv" \
-vframes 5000 -y C:\green_broken.mp4
```
4. You can observe the utilization in `GPU->VideoDecode` and `GPU->Compute` in Task Manager. Note that on a multiple Intel GPU system, if the Arc discrete GPU is not being used, please disable UHD integrated graphics and try again.
![taskmgr](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/64d2a387-84cc-42d1-b6fa-2ce882bb5be6)

5. After the `ffmpeg.exe` process is exited, play the output file `C:\green_broken.mp4`. It should be totally green, which means the empty YUV data was encoded.
![green_broken](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/6895a348-847b-4652-92c2-4a8a32172e81)

6. Downgrade the driver to the old version [5085_5122](https://www.intel.com/content/www/us/en/download/785597/813048/intel-arc-iris-xe-graphics-windows.html), re-do the above procedures, you can get back the correct video instead of a green screen.

### Application / Windows logs

During FFmpeg transcoding, you can observe that the real-time bitrate is always close to 0. This means that the YUV data is empty, that is, the D3D11VA to OpenCL interop failed.

The 5186_5234 driver is [advertised as improving performance for many DX11 games](https://game.intel.com/us/stories/intel-arc-game-on-driver-tekken-8-atelier-resleriana-infinite-wealth-palworld-dx11/), so I have reason to suspect that these optimizations also break the ability to share textures between D3D11VA and OpenCL.

1. D3D11VA, [Direct3D 11 Video Decoder](https://learn.microsoft.com/en-us/windows/win32/medfound/direct3d-11-video-apis)
2. Khronos OpenCL extension [cl_khr_d3d11_sharing](https://man.opencl.org/cl_khr_d3d11_sharing.html)
3. Intel OpenCL extension [cl_intel_d3d11_nv12_media_sharing](https://registry.khronos.org/OpenCL/extensions/intel/cl_intel_d3d11_nv12_media_sharing.txt)
4. cl_khr_d3d11_sharing [API docs](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_Ext.html#cl_khr_d3d11_sharing)
5. [Sharing Surfaces between OpenCL™ and DirectX* 11 on Intel® Processor Graphics](https://www.intel.cn/content/www/cn/zh/developer/articles/technical/sharing-surfaces-between-opencl-and-directx-11-on-intel-processor-graphics.html)

In some cases, Jellyfin Media Server needs to use OpenCL to post-process the D3D11VA decoded video.

**Comment by nyanmisaka** [comment]
Can you take a look at this DX11 regression? @Arturo-Intel

**Comment by Arturo-Intel** [comment]
@nyanmisaka on it!
--r2

**Comment by ma3uk** [comment]
The situation is similar with importing Texture2D from DirectX using the new libVPL 2.10 API, instead of a green screen image.

**Comment by nyanmisaka** [comment]
**Still an issue in the [5194_5252](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) driver released on 2/8/2024.**

**Comment by nyanmisaka** [comment]
**Still an issue in the [5330](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) driver released on 2/17/2024.**

**Comment by nyanmisaka** [comment]
**Still an issue in the [5333](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) driver released on 2/26/2024.**

@Arturo-Intel May I get an update on this?

Has the issue been reproduced? Or is it being processed by Intel and I should stay tuned?

If not, you can simply pass the following content to the corresponding DX11 developer. Thanks in advance.

```c
// Sharing of arrays of NV12 D3D11 2D textures to OpenCL is broken.
// This is supported via [cl_intel_d3d11_nv12_media_sharing] extension.

// Prepare D3D11 textures for sharing.
    D3D11_TEXTURE2D_DESC texDesc = {
        .Width      = 1920,
        .Height     = 1080,
        .MipLevels  = 1,
        .Format     = DXGI_FORMAT_NV12,
        .SampleDesc = { .Count = 1 },
        .ArraySize  = 10, // greater than 1, arrayed textures
        .Usage      = D3D11_USAGE_DEFAULT,
        .BindFlags  = D3D11_BIND_DECODER, // bind decoder
        .MiscFlags  = D3D11_RESOURCE_MISC_SHARED, // shared resource
    };
...

// Create OpenCL image from the shared D3D11 textures.
// github.com/FFmpeg/FFmpeg/blob/69dd1ce610fcffec453a0663c613c9b13165fd9e/libavutil/hwcontext_opencl.c#L2623-L2642
    for (i = 0; i < frames_priv->nb_mapped_frames; i++) {
        AVOpenCLFrameDescriptor *desc = &frames_priv->mapped_frames[i];
        desc->nb_planes = nb_planes; // NV12, nb_planes = 2
        for (p = 0; p < nb_planes; p++) {
            UINT subresource = 2 * i + p; // As per [cl_intel_d3d11_nv12_media_sharing]

            desc->planes[p] =
                device_priv->clCreateFromD3D11Texture2DKHR(
                    dst_dev->context, cl_flags, src_hwctx->texture,
                    subresource, &cle);
            if (!desc->planes[p]) {
                av_log(dst_fc, AV_LOG_ERROR, "Failed to create CL "
                       "image from plane %d of D3D texture "
                       "index %d (subresource %u): %d.\n",
                       p, i, (unsigned int)subresource, cle);
                err = AVERROR(EIO);
                goto fail;
            }
        }
    }
...
```

**Comment by Arturo-Intel** [comment]
@nyanmisaka Thank you for sharing this, I will add it to the report.

It's WIP at the moment. I will share any news through this thread. :)

**Comment by Arturo-Intel** [comment]
@nyanmisaka can you share me the whole homebrew code to reproduce this behavior, with this we can push harder into the priority queue :)

**Comment by nyanmisaka** [comment]
@Arturo-Intel FYI I forwarded the issue to oneVPL repo because people there are more familiar with this, and now the issue has been fixed in the latest driver 31.0.101.5592.

**Comment by robo45h** [comment]
I am a complete N00b in this area of graphics, but I've been working with computers since 1978, so there's that. I have an Asus / Intel NUC that has a Core i7-9850H with associated ‎Intel UHD Graphics 630. I'm experiencing **_exactly_** this issue under Windows 11 with Jellyfin when I enable GPU transcoding. If I disable transcoding and leave it to the CPU, no problems. Unfortunately, I have tried the earliest driver available to me 30.0.101.1660, the latest validated by Microsoft for their driver installation 30.0.101.2110, a newer version 30.0.101.2121, and the absolute latest available from the intel website, 30.0.101.2128. None of them resolve this problem. Clearly the fix applied to the drivers for the Intel Arc A380 Graphics need to be applied to the  ‎Intel UHD Graphics 630 drivers for the NUC. But I have no idea how to "cross-post" this bug report to get it addressed. I'm happy to even provide ffmpeg logs and such, but not sure the best place and way to do so.

**Comment by nyanmisaka** [comment]
> I am a complete N00b in this area of graphics, but I've been working with computers since 1978, so there's that. I have an Asus / Intel NUC that has a Core i7-9850H with associated ‎Intel UHD Graphics 630. I'm experiencing **_exactly_** this issue under Windows 11 with Jellyfin when I enable GPU transcoding. If I disable transcoding and leave it to the CPU, no problems. Unfortunately, I have tried the earliest driver available to me 30.0.101.1660, the latest validated by Microsoft for their driver installation 30.0.101.2110, a newer version 30.0.101.2121, and the absolute latest available from the intel website, 30.0.101.2128. None of them resolve this problem. Clearly the fix applied to the drivers for the Intel Arc A380 Graphics need to be applied to the ‎Intel UHD Graphics 630 drivers for the NUC. But I have no idea how to "cross-post" this bug report to get it addressed. I'm happy to even provide ffmpeg logs and such, but not sure the best place and way to do so.

I also have a UHD 630, these older gfx/drivers are not affected as they stopped receiving functional updates over a year ago, only security fixes.

**Comment by robo45h** [comment]
> > I am a complete N00b in this area of graphics, but I've been working with computers since 1978, so there's that. I have an Asus / Intel NUC that has a Core i7-9850H with associated ‎Intel UHD Graphics 630. I'm experiencing **_exactly_** this issue under Windows 11 with Jellyfin when I enable GPU transcoding. If I disable transcoding and leave it to the CPU, no problems. Unfortunately, I have tried the earliest driver available to me 30.0.101.1660, the latest validated by Microsoft for their driver installation 30.0.101.2110, a newer version 30.0.101.2121, and the absolute latest available from the intel website, 30.0.101.2128. None of them resolve this problem. Clearly the fix applied to the drivers for the Intel Arc A380 Graphics need to be applied to the ‎Intel UHD Graphics 630 drivers for the NUC. But I have no idea how to "cross-post" this bug report to get it addressed. I'm happy to even provide ffmpeg logs and such, but not sure the best place and way to do so.
> 
> I also have a UHD 630, these older gfx/drivers are not affected as they stopped receiving functional updates over a year ago, only security fixes.
Thanks for the quick reply! Sigh. I really, _**really**_ don't know what I was thinking when I recently bought this NUC (new in box). In all my years in the IT industry, my experience is that Intel is absolutely horrible at software and long-term support. You'd think I'd learn.

**Comment by nyanmisaka** [comment]
> > > I am a complete N00b in this area of graphics, but I've been working with computers since 1978, so there's that. I have an Asus / Intel NUC that has a Core i7-9850H with associated ‎Intel UHD Graphics 630. I'm experiencing **_exactly_** this issue under Windows 11 with Jellyfin when I enable GPU transcoding. If I disable transcoding and leave it to the CPU, no problems. Unfortunately, I have tried the earliest driver available to me 30.0.101.1660, the latest validated by Microsoft for their driver installation 30.0.101.2110, a newer version 30.0.101.2121, and the absolute latest available from the intel website, 30.0.101.2128. None of them resolve this problem. Clearly the fix applied to the drivers for the Intel Arc A380 Graphics need to be applied to the ‎Intel UHD Graphics 630 drivers for the NUC. But I have no idea how to "cross-post" this bug report to get it addressed. I'm happy to even provide ffmpeg logs and such, but not sure the best place and way to do so.
> > 
> > 
> > I also have a UHD 630, these older gfx/drivers are not affected as they stopped receiving functional updates over a year ago, only security fixes.
> 
> Thanks for the quick reply! Sigh. I really, _**really**_ don't know what I was thinking when I recently bought this NUC (new in box). In all my years in the IT industry, my experience is that Intel is absolutely horrible at software and long-term support. You'd think I'd learn. [edit] Meanwhile, my 2014 Tesla (10 years old!) just received an OTA update. Say what you want about Elon, but he knows software.

Jump on Linux and call it a day ;)

**Comment by robo45h** [comment]
OK, wait -- what? I've used Unix / Linux longer than I've used Windows. I use both these days. The NUC came pre-loaded with Windows 11. But I don't see what that has to do with anything. Are you saying that Intel provides driver support for a longer period of time on Linux than Windows? Or are you saying that people have reverse-engineered the Intel UHD Graphics 630 hardware and written Linux open source drivers without Intel assistance?

**Comment by nyanmisaka** [comment]
> OK, wait -- what? I've used Unix / Linux longer than I've used Windows. I use both these days. The NUC came pre-loaded with Windows 11. But I don't see what that has to do with anything. Are you saying that Intel provides driver support for a longer period of time on Linux than Windows?

That's right. Intel's user-mode ([iHD](https://github.com/intel/media-driver)/[Mesa](https://gitlab.freedesktop.org/mesa/mesa)/[compute-runtime](https://github.com/intel/compute-runtime)) and kernel-mode drivers ([i915](https://github.com/torvalds/linux/commits/master/drivers/gpu/drm/i915)) on Linux are open source, so end users can still benefit from regular updates.

**Comment by robo45h** [comment]
> That's right. Intel's user-mode ([iHD](https://github.com/intel/media-driver)/[Mesa](https://gitlab.freedesktop.org/mesa/mesa)/[compute-runtime](https://github.com/intel/compute-runtime)) and kernel-mode drivers ([i915](https://github.com/torvalds/linux/commits/master/drivers/gpu/drm/i915)) on Linux are open source, so end users can still benefit from regular updates.

Wow -- surprising. Thank you for all the information!

**Comment by bandit8623** [comment]
this still an issue.  pls fix intel.
