### ISSUE TITLE
Starfield black rectangles on lit the edges on some 3D objects

### ISSUE THREAD

**Issue by akarnokd** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#681]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Starfield

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

13700K

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

31.0.101.5186

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14055637/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Starfield 1.8.88

Open the system view and look at planets. Some systems, maybe with particular planet positions, show these artifacts on the lit edges of planets (see below), which also flicker.

Example from the *Volii* system, right gas giant:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/67018342-bd53-4eb0-8414-b52f2e16d526)

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/f13476d9-a283-40a1-855b-e928d19a9769)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/8cf8b278-e5a1-44d5-8399-898ae51eaffa)

### Save game

[Starfield.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14055702/Starfield.zip)

**Comment by Karen-Intel** [comment]
Hey @akarnokd ty for reporting this
I have been able to confirm the black squares on the planet borders with driver v.5186. 
Do you know if it was present in a previous driver version?
I will verify if we already have a report for this, if not, I'll make a new one and share the internal number with you :)

Stay tuned!

Karen

**Comment by akarnokd** [comment]
Yes, it was present in several previous drivers: 4887, 4953, 4972, 5081, 5085

There was one game+driver combo when it was not present: 1.8.86 running 4953 (2023.11.20). But that combo had considerable performance issues otherwise. 4972 brought back the performance and the rectangles.

**Comment by akarnokd** [comment]
Game version 1.9.51.0 - Driver 5186, I no longer see the black rectangles.

I'd still wait for the next driver version, assuming the internal work on Starfield will be included.

**Comment by akarnokd** [comment]
Game version 1.9.51.0 - Driver 5194.

Black rectangles issue seems to be fixed for good. Performance issues have been also fixed.

Thank you for your hard work!
