### ISSUE TITLE
Firefox's YouTube video playback is glitching randomly. 

### ISSUE THREAD

**Issue by peace20021** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#683]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Mozilla Firefox

### Processor / Processor Number [Required]

Ryzen 5 5600X

### Graphic Card [Required]

Sparkle Arc 770 Titan 16GB

### GPU Driver Version [Required]

Other (Please specify)

### Other GPU Driver version

31.0.101.5186

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [x] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14059769/Report.txt)

### Description and steps to reproduce [Required]

Youtube playback on Firefox glitching when watching videos, happens the most when some other application windows on my second screen started playing. 

Here's a preview video: https://youtu.be/qCVwMrsxdMQ

### Device / Platform

Desktop PC

**Comment by mujeeb-intel** [comment]
Hello @peace20021 
What other application were you running on the second monitor to observe this glitch?  

1.  If you havent yet, could you please run the DDU https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html
2. Re-install the latest driver from https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html
3. Please try watching the clip on microsoft edge browser or google chrome and notify whether the issue persists. 

I was unable to reproduce this issue on my system:
Processor: i5-13600K
Win 11 Pro Build 22621
A750 Limited Edition Graphics card
101.5186 Graphics Driver
Monitor 1: 27GL850 LG 1440p 144hz using 4k DP
Monitor 2:  27BL85U 4k 60hz using 4k DP
Browser: Firefox (Latest version), Chrome & Edge.
Tested Video: https://www.youtube.com/watch?v=ZpjDDZM562c&pp=ygUkYnV5IHRoaWcgbGFwdG9wIG9uIHNhbGUgYWNlciBuaXRybyB2  While playing other videos on the second monitor using yahoo ad videos and youtube

**Comment by peace20021** [comment]
> Hello @peace20021 What other application were you running on the second monitor to observe this glitch?
> 
>     1. If you havent yet, could you please run the DDU https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html
> 
>     2. Re-install the latest driver from https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html
> 
>     3. Please try watching the clip on microsoft edge browser or google chrome and notify whether the issue persists.
> 
> 
> I was unable to reproduce this issue on my system: Processor: i5-13600K Win 11 Pro Build 22621 A750 Limited Edition Graphics card 101.5186 Graphics Driver Monitor 1: 27GL850 LG 1440p 144hz using 4k DP Monitor 2: 27BL85U 4k 60hz using 4k DP Browser: Firefox (Latest version), Chrome & Edge. Tested Video: https://www.youtube.com/watch?v=ZpjDDZM562c&pp=ygUkYnV5IHRoaWcgbGFwdG9wIG9uIHNhbGUgYWNlciBuaXRybyB2 While playing other videos on the second monitor using yahoo ad videos and youtube

The glitch happens when one of the monitors play video on it, I have tried Chrome and it seems like nothing happened. Using the same youtube video. However, any other kinds of animations that's rendering on the monitor would make firefox's glitched like the same. For example, if I have Discord windows playing some small animations, my firefox tab would have this specific glitch when I'm also having it playing some animations such as scrolling.

Here's my configurations:
B550 Aorus Pro-P
Ryzen 5 5600X
16GB Corsair vengange RGB CL16
Windows 10 21H2 19044.3930
Sparkle Arc A770 Titan 
101.5186 Driver version
Monitor 1: LG Ultragear 27GN750-B
Monitor 2: Dell E2216H

**Comment by mujeeb-intel** [comment]
Hi @peace20021 did you try the DDU method I mentioned and noticed the same behavior?

Since this is specific to firefox and I was unable to reproduce the issue, I suggest you get in touch with the firefox devs as this could be an issue specific to Mozilla.

**Comment by peace20021** [comment]
> Hi @peace20021 did you try the DDU method I mentioned and noticed the same behavior?
> 
> Since this is specific to firefox and I was unable to reproduce the issue, I suggest you get in touch with the firefox devs as this could be an issue specific to Mozilla.

Yes that is correct. Well I assume I can just write a feedback to them then.

**Comment by mujeeb-intel** [comment]
@IGCIT requesting case closure
