### ISSUE TITLE
Low performance in minecraft

### ISSUE THREAD

**Issue by jdv090905** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#684]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Minecraft

### Game Platform [Required]

- [ ] Steam
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 1500x

### Graphic Card [Required]

intel arc a750

### GPU Driver Version [Required]

Other (Please specify)

### Other GPU Driver version

31.0.101.5085

### Rendering API [Required]

- [ ] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

![Снимок экрана 2024-01-26 184526](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/86566557/41eb08a4-d305-4fe1-9989-3b6802c4aef1)

### Description and steps to reproduce [Required]

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/86566557/47f78dfa-ef4a-46e2-bc9b-574428564c92

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920х1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![Снимок экрана 2024-01-26 185040](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/86566557/cead69ac-871f-4852-abd6-74acbfa21b2e)
![Снимок экрана 2024-01-26 185049](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/86566557/bed094d0-4c0f-4888-a2c0-8b10587d22a6)

**Comment by Arturo-Intel** [comment]
@jdv090905 Just wondering, this behavior occurs at starting the game play session? or I take some time to see the performance down?

**Comment by jdv090905** [comment]
This happens immediately after logging in. Regardless of game settings.

**Comment by Arturo-Intel** [comment]
Thanks for the info, will work on this. 

--r2

**Comment by EliezYT** [comment]
> @Arturo-Intel This happens immediately after entering the game. Regardless of settings . Version 1.20.1. I use one mod Forge. But even without him the situation is the same.

From what I can tell with your tests your gpu is maxing out correct? On this low of settings this should not happen not even my clearly weaker RX 5700 XT does this on these settings.

**Comment by jdv090905** [comment]
@EliezYT Yes, that's right. This problem only exists in Minecraft. I think this is due to the fact that my processor can't handle it Resize bar.

**Comment by EliezYT** [comment]
> @EliezYT Yes, that's right. This problem only exists in Minecraft. I think this is due to the fact that my processor can't handle it Function Resize bar.

From what I've seen it can help with performance in Minecraft but it's not big enough to really matter to much. The fact is the gpu isn't optimized for Minecraft like the other brands AMD and NVIDIA. They both work very well with Minecraft without rebar intel just needs to optimize for Minecraft and that's it.

**Comment by jdv090905** [comment]
The problem was solved by replacing the processor with another one that supports resize bar.
