### ISSUE TITLE
Cant play long sessions with minecraft shaders

### ISSUE THREAD

**Issue by Asphenix20** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#685]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Minecraft Java Edition

### Processor / Processor Number [Required]

12th Gen Intel(R) Core(TM) i5-12400F   2.50 GHz

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

31.0.101.5186

### Rendering API [Required]

- [X] Vulkan
- [X] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[system.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14064855/system.txt)

### Description and steps to reproduce [Required]

When i play the game around 1 hours my fps suddenly drops to 10-15 and stucks there
the problem fixes when i restart whole session and happens again after 1 hours so cant play more than 1 hour
and when i switch to borderless window mode my game runs 5-10 more minutes after 1 hour but then crashes instead
----------------------------------------------------------------------
Minecraft Java Ed. 1.20.1 Fabric Used Mods Iris Shaders,Sodium

### Crash dumps [Required, if applicable]

[hs_err_pid17320.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14064905/hs_err_pid17320.log)

**Comment by Arturo-Intel** [comment]
@Asphenix20 Without the mods, the low performance is still there?

**Comment by Asphenix20** [comment]
> @Asphenix20 Without the mods, the low performance is still there?

The low performance only happens with shaders(aka ray tracing) in vanilla its normal

**Comment by mujeeb-intel** [comment]
@Asphenix20 what is the avg fps that it should be playing? I see 32fps when using A750

**Comment by Asphenix20** [comment]
> @Asphenix20 what is the avg fps that it should be playing? I see 32-40fps when using A750 when playing in Medieval RTX world

I tested other games and similar thing happens at other games like freezing after 1 hour or just crashing the issue seems like not only happen in minecraft and Im not using RTX im using Iris shaders with sodium (both are minecraft mods and pretty populer bcz they provide Shaders and optimized world gen etc.)

**Comment by mujeeb-intel** [comment]
@Asphenix20 okay just to be 100% if you use no mods whatsoever and only use ray tracing natively from the video settings in full screen, do you still observe 10-15fps after an hour of gameplay for Minecraft bedrock? I am going to be testing without mods specifically.

**Comment by Asphenix20** [comment]
> @Asphenix20 okay just to be 100% if you use no mods whatsoever and only use ray tracing natively from the video settings in full screen, do you still observe 10-15fps after an hour of gameplay for Minecraft bedrock? I am going to be testing without mods specifically.

Im Playing at Minecraft Java 1.20.1 With Mods Named Iris , Sodium,Lithium not Bedrock
and i dont own bedrock version of the game

**Comment by mujeeb-intel** [comment]
@Asphenix20 has this ever worked before (comparing it the older graphics drivers)?

**Comment by Asphenix20** [comment]
> @Asphenix20 has this ever worked before (comparing it the older graphics drivers)?

what worked??

**Comment by mujeeb-intel** [comment]
> > @Asphenix20 has this ever worked before (comparing it the older graphics drivers)?
> 
> 
> 
> what worked??

Has Minecraft Java edition with the mods ever worked before with the older intel graphics driver? Has the game ever worked before as expected on any driver before you started noticing this unusual behavior after an hour of gameplay?


Please perform DDU. The instructions can be found here https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html and let me know if you still see the behavior.

**Comment by Asphenix20** [comment]
> > > @Asphenix20 has this ever worked before (comparing it the older graphics drivers)?
> > 
> > 
> > what worked??
> 
> Has Minecraft Java edition with the mods ever worked before with the older intel graphics driver? Has the game ever worked before as expected on any driver before you started noticing this unusual behavior after an hour of gameplay?
> 
> Please perform DDU. The instructions can be found here https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html and let me know if you still see the behavior.

Yeah,It was working at my old computer i did not changed GPU i chaged PC and my friends are playing perfectly fine but my game crashes randomly(even at other games) 
And i already did the DDU thing some guy in Intel forums said to do it like 4 days ago

**Comment by mujeeb-intel** [comment]
Hi @Asphenix20 I was unable to run the game with the mods you mentioned. However, I want to mention since the game works fine natively without any mods, I would advise you to please contact mod developers to figure out what the issue here is. Minecraft Java edition works fine when playing beyond an hour on my machine with no issues in fps. These mods are actively altering performance to provide better fps but like always mods can interfere in performance of the game. 

Since it works on the a different computer environment and not the current computer you are using, you can try  re-installing the fresh windows OS and then give it a shot since DDU did not work for you. 
![incompatible mod](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/112665178/dc161e02-4e56-4b1e-888c-f7997cc01a7d)
![8d4d8286-38c2-4ca3-9564-c2469c381f7e](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/112665178/05453680-9897-479c-8777-cfd48e58b361)

**Comment by Asphenix20** [comment]
> Hi @Asphenix20 I was unable to run the game with the mods you mentioned. However, I want to mention since the game works fine natively without any mods, I would advise you to please contact mod developers to figure out what the issue here is. Minecraft Java edition works fine when playing beyond an hour on my machine with no issues in fps. These mods are actively altering performance to provide better fps but like always mods can interfere in performance of the game.
> 
> Since it works on the a different computer environment and not the current computer you are using, you can try re-installing the fresh windows OS and then give it a shot since DDU did not work for you. ![incompatible mod](https://private-user-images.githubusercontent.com/112665178/301669679-dc161e02-4e56-4b1e-888c-f7997cc01a7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4Mjg0OTksIm5iZiI6MTcwNjgyODE5OSwicGF0aCI6Ii8xMTI2NjUxNzgvMzAxNjY5Njc5LWRjMTYxZTAyLTRlNTYtNGIxZS04ODhjLWY3OTk3Y2MwMWE3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQyMjU2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjA3MDUyNDFhNzFmYTU4NzdmNDJjNTA4NGNmNDIyNWU5YWViMGZmNjA5ODliNzY4NDc2MjQ0MzI4YzI5NWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nt3zYEARIFsubzy1RRnMDJIDSj3ATZQrb-tScsNYyaI) ![8d4d8286-38c2-4ca3-9564-c2469c381f7e](https://private-user-images.githubusercontent.com/112665178/301669710-05453680-9897-479c-8777-cfd48e58b361.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4Mjg0OTksIm5iZiI6MTcwNjgyODE5OSwicGF0aCI6Ii8xMTI2NjUxNzgvMzAxNjY5NzEwLTA1NDUzNjgwLTk4OTctNDc5Yy04Nzc3LWNmZDQ4ZTU4YjM2MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQyMjU2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDA3ZTExMDUzNTJhYzg4YWE1ZGM0MjhhYTc5YTIzODc0MTkxYzg0NTNiZWUzYzE0YjUzYWZjY2ZiZTY1ZmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5IF_y_UHEgJ29J514wIhk1vWMEpjfSF2YKqPStZ6m5k)

Fabric Abi is Basicaly An library that allows you to play with mods i didnt included it cuz it was supposed do wonload automaticly but the problem doesnt happen onlyin modded minecraft but some other games tho

**Comment by mujeeb-intel** [comment]
@Asphenix20 Understood. Please open a new issue for other application you are experiencing performance issues with. For this specific issue, my advise is to contact the mod devs as the game works as expected without mods.

**Comment by Arturo-Intel** [comment]
>Yeah,It was working at my old computer i did not changed GPU i chaged PC and my friends are playing perfectly fine but my game crashes randomly(even at other games)

@Asphenix20 I wonder if the GPU power cables are connected correctly. We had a case where the user was complaining about a game crash after a while of playing it and it was due the power cable was a little loose. Can you check that?

**Comment by Asphenix20** [comment]
> > Yeah,It was working at my old computer i did not changed GPU i chaged PC and my friends are playing perfectly fine but my game crashes randomly(even at other games)
> 
> @Asphenix20 I wonder if the GPU power cables are connected correctly. We had a case where the user was complaining about a game crash after a while of playing it and it was due the power cable was a little loose. Can you check that?

They probably are connected cuz i was not the one plugged them i bought it prebuilt so it was ready but i can check and wdym with check can i just unplug and plug them again?

**Comment by Arturo-Intel** [comment]
> They probably are connected cuz i was not the one plugged them i bought it prebuilt so it was ready but i can check and wdym with check can i just unplug and plug them again?

Ok, so it's a prebuilt system, I do not recommend opening a prebuilt PC because it can avoid the warranty from the place where you buy your rig.

If you still have the warranty, go with them and tell them that the system is crashing after a while. So, they can verify the connections of your rig and fix whatever it needs to be fixed.

The thing here is that the problem is only reproducible in your configuration (your PC), we can't reproduce the behavior in our labs and also seems to be non-related only to minecraft, the system crashes after a while with another games (as you mention before), 
You mention that before changing the PC (I assume you change the CPU) the GPU was working well, 
that's why I am almost sure that is something related with the way your new PC was assembled.

**Comment by mujeeb-intel** [comment]
@IGCIT requesting for closure
