### ISSUE TITLE
Give the opportunity to reduce the delay in online games, some AMD Anti-Lag+ or NVIDIA Reflex

### ISSUE THREAD

**Issue by Pashamolochko** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#686]
### Application [Required]

intel arc control

### Processor / Processor Number [Required]

i5 12400

### Graphic Card [Required]

intel arc a770

### Rendering API [Required]

- [X] Vulkan
- [X] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [X] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

For a long time I have been tormented by high latency in online games, and not only, the mouse movement is sometimes not clear and as if jelly, I apologize for such inaccurate wording, but I think my train of thought is clear, I want to have in the driver the ability to enable a function similar to AMD Anti-Lag + or NVIDIA Reflex

**Comment by Gabriela-Intel** [comment]
Thanks for your feedback We'll pass this along for the team to review :)

@IGCIT
