### ISSUE TITLE
Monitor flickers after display signal comes back

### ISSUE THREAD

**Issue by BlauerToad** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#687]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows itself

### Processor / Processor Number [Required]

AMD Ryzen 5 2600X

### Graphic Card [Required]

Intel Arc A770 16GB

### GPU Driver Version [Required]

31.0.101.5085

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

Windows 10 22H2 (Build 19045.3996)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14072720/igcit_ssu.txt)

### Description and steps to reproduce [Required]

A graphics error occurs, which is characterized by flickering or glitching of the image. The behavior can be seen in the video.

Windows does not crash (black or blue screen), the image returns to normal when the graphics driver is reset ( Win + Cmd + Shift + B )

**Time of Occurrence:**
The error usually occurs when the monitor (model: Alienware AW2724DM) receives a monitor signal again, e.g. when the screen is switched off by the windows energy saving settings and (shortly) afterwards the monitor is woken up again by moving the mouse or similar.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92584570/95bf86eb-219b-4250-8d1e-754d80266888

### Device / Platform

Desktop Computer, AMD Ryzen AM4 Platform, B450 Mainboard

**Comment by BlauerToad** [comment]
Just checked with 31.0.101.5086. The issue persists.

**Comment by jpovixwm** [comment]
The most recent driver is currently 5186.

**Comment by BlauerToad** [comment]
Oh, sorry for the typo. I had 5085 and updated to 5186.

**Comment by mujeeb-intel** [comment]
Hello @BlauerToad

I tried giving this issue a try on my Display: AW2521HF and was unable to reproduce the same behavior as yours.

Could you please try: 
1. If you havent yet, could you please run the DDU https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html
2. Re-install the latest driver from https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html
3. Please switch out the hdmi cable with another hdmi cable and check if the issue persists.


My system:
Changed system settings to Turn off the display: 1 minute
Changed system put the computer to sleep: 1 minute. Then I waited 5 or 10 minutes and hit any keyword on the keyboard for the system t
Processor: i5-13600K
Win 11 Pro Build 22621
A750 Limited Edition Graphics card
101.5186 Graphics Driver
2.1 cable hdmi

**Comment by mujeeb-intel** [comment]
Hi @BlauerToad

 I want to make sure I have this right. The system you are experiencing this issue is on your AMD Ryzen 5 2600X paired with arc a770 as it is mentioned in this github case creation steps?

 In your "When my PC is in standby and I wake up" List me the exact steps that I can use to reproduce this issue.

**Comment by BlauerToad** [comment]
Hi @mujeeb-intel 

yes you are right, I am experiencing the issue on my Desktop AMD Ryzen 5 2600X system paired with Intel Arc A770 16GB Limited Edition, as it is mentioned in this GitHub case 👍

The Display Model is an _Alienware AW2724DM_ with newest Firmware M2B102

The exact steps to reproduce this issue are following:

1. Do not use the computer and wait until Windows turns off the Monitor. The system should stay on and not go into energy-saving mode
2. Right after the Monitor lost the signal, move your mouse, so that Windows will output an display signal again and the monitor automatically turns on
3. 1 out of 3 to 4 times, the displayed image will be "faulty" like it can be seen in the video

To accelerate testing, you can cahnge your system settings to turn off the display after one minute, as you did:

> Changed system settings to Turn off the display: 1 minute

With "When my PC is in standby and I wake it up" I meant that you just need to wait longer until the system goes into Energy Saving Mode. If I wake up my system from Energy Saving Mode and the Monitor automatically turns on, the displayed image is most likely good.

I have another Monitor and will try if the issue persists on that as well.

**Update**
As I mentioned in my previous comment:
> Since then I have not encountered the problem again, but I have not provoked it either.

I have tested my monitor with three different devices at all refresh rate settings and surprisingly **I have not encountered the problem again.**

However, I doubt a little that the problem will go away just like that, especially since I've already removed previous drivers a few times with DDU and then reinstalled the latest driver. Would it therefore be possible not to close the issue directly?

---
**Simply out of interest**
How do I get 10bit color working with Intel Graphics? On my Laptop with integrated Radeon Graphics (Ryzen 7 6800HS - Radeon 680M) 10bit color works out of the box with that monitor.

**Comment by jpovixwm** [comment]
> **Simply out of interest** How do I get 10bit color working with Intel Graphics?

You don't, unless you have an Intel iGPU. See #658 for more info.

**Comment by BlauerToad** [comment]
Ok, I understand. Thank you for your fast reply. No further questions to that topic 😀

**Comment by mujeeb-intel** [comment]
Hi @BlauerToad Thanks alot for step by step instructions. I would say if it happens again, it is better to create a new case and reference back to this.

**Comment by mujeeb-intel** [comment]
@IGCIT requesting case closure

**Comment by BlauerToad** [comment]
> Hi @BlauerToad Thanks alot for step by step instructions. I would say if it happens again, it is better to create a new case and reference back to this.

All right, then let's do it like this.
