### ISSUE TITLE
support for `VK_EXT_swapchain_maintenance1`

### ISSUE THREAD

**Issue by ickk** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#689]
### Application [Required]

vulkan applications

### Graphic Card [Required]

Arc

### Rendering API [Required]

- [X] Vulkan

### Describe the feature [Required]

https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_swapchain_maintenance1.html

Proper swapchain management in Vulkan is cursed without the additional synchronisation objects made available in the `VK_EXT_swapchain_maintenance1` extension.

It seems as though all recent Radeon, GeForce (and even Apple) GPUs [have support for this](<https://vulkan.gpuinfo.org/listdevicescoverage.php?extensionname=VK_EXT_swapchain_maintenance1>) in their drivers nowadays, so it would be amazing if Arc & other Intel GPUs could add support for this as well :pray: 

----

to illustrate the need for this: from [docs.vulkan.org][cursed]
> Before VK_EXT_swapchain_maintenance1, there is no straightforward way to tell when a semaphore associated with a present operation can be recycled, or when a retired swapchain can be destroyed. Both these operations depend on knowing when the presentation engine has acquired a reference to these resources as part of the present job, for which there is no indicator.

and even after the explaining their workaround
> Note that the swapchain may be recreated without a second acquire. This means that the swapchain could be recreated while there are pending old swapchains to be destroyed. The destruction of both old swapchains must now be deferred to when the first QP of the new swapchain has been processed. If an application resizes the window constantly and at a high rate, we would keep accumulating old swapchains and not free them until it stops.

The workaround for the general problem is ugly, but having to handle the specific case above (not being able to free any number of old swapchains and associated semaphores & fences) feels really bad

[cursed]: <https://docs.vulkan.org/samples/latest/samples/api/swapchain_recreation/README.html>

**Comment by Gabriela-Intel** [comment]
Thanks so much for taking the time to provide this detailed feedback :)

I've noted this down in our internal tool so we can review it and pass it along to the team.

@IGCIT Close this, thanks!
