### ISSUE TITLE
Batman Arkham Knight uses Microsoft Basic Display Adapter instead of Arc Gpu

### ISSUE THREAD

**Issue by toriko2** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#690]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Batman Arkham Knight

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7700x

### Graphic Card [Required]

ASRock Intel Arc A750

### GPU Driver Version [Required]

31.0.101.5186

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14079338/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Unfortunately it seems Batman Arkham Knight is hardcoded to ignore any Intel GPU on a system. This means whenever the game is booted it starts with the Microsoft Basic Display Adapter as shown in the game settings screenshot.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/98915401/db76206f-f54c-49a0-a3bb-5b2bcb164e16)

Also the game only boots in windowed mode and runs at ~5 fps. 
This issue was also experienced in issue #222  and is replicated in the following youtube video:
https://youtu.be/g-v2vLNMdZM?si=NKluuAOrS_yCxMD5

Also is referenced in intel article:
https://www.intel.com/content/www/us/en/support/articles/000094465/graphics.html

Does this mean the only solution to run this game is to use DXVK or the following mod (https://community.pcgamingwiki.com/files/file/2546-batman-arkham-knight-intel-gpu-detection-fix/)?

Just curious if any driver updates are planned to fix this game without current workarounds.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1600x900

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/98915401/ee66a304-961e-4071-ad01-fbee1fca37e1)

**Comment by rmorera-intel** [comment]
Hi @toriko2 thanks for this report, I'm looking into this right now.
I'm attempting to reproduce the issue, as soon as I have more information I'll let you know.

**Comment by EstebanIntel** [comment]
Hi @toriko2,

This game is hard coded to ignore al Intel GPUs (including Arc Discrete GPUs). So, they only WA to have this game run correctly on Intel GPU is to:

1. Unzip the attached file
2. <path-to-game>/Binaries/Win64, and overwrite it if needed

[DXGI.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14184511/DXGI.zip)

**Comment by EstebanIntel** [comment]
@IGCIT can this be closed? The issue on the game side and we have provided a workaround.
