### ISSUE TITLE
An Arc Control app for gamer.

### ISSUE THREAD

**Issue by UnderCooled** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#692]
### Application [Required]

Arc Control

### Processor / Processor Number [Required]

i7-12700H

### Graphic Card [Required]

Arc A770M

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

I don't think any gamer really need another game launcher, or another overlay which is not really useful than "xbox game bar" or steam overlay.

You can check out [Special K](https://special-k.info/), you're using an "IntelArcControl" service already, you can inject an [imgui](https://github.com/ocornut/imgui) powered overlay into games like Special K, and let gamer tweak those "Arc Control powered" settings in real time. These kinds of GUI overlay shouldn't require that much of resources like what Arc Control are using right now, which is CEF, it's like electron app, spawns 7 processes on my machine with latest version.

**Comment by Gabriela-Intel** [comment]
Thanks so much for your feedback! We'll pass along this request to the team. :)

@IGCIT please close.
