### ISSUE TITLE
Blender Cycles render engine crashes on latest driver

### ISSUE THREAD

**Issue by NicCrimson** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#694]
### Checklist [README]

- [x] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Blender

### Processor / Processor Number [Required]

Ryzen 5 4500

### Graphic Card [Required]

Arc A380

### GPU Driver Version [Required]

31.0.101.5186

### Other GPU Driver version

31.0.101.5084

### Rendering API [Required]

- [X] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[info.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14150770/info.txt)

The reason it says an older driver version is that I downgraded as the newer stated version is unstable.

### Description and steps to reproduce [Required]

Open Blender. Switch to Cycles render. No image is displayed. Blender Crashes

**Comment by NicCrimson** [comment]
> @NicCrimson which version is where it works well? 101.5085? or older?

It works on 101.5084. This is the only other driver I have tested it on as I have recently got the card and was the one arc control said was available at the time.

**Comment by Vivek-Intel** [comment]
@NicCrimson can you share app version and video of issue reproduction if possible.
Can you check disabling embree on GPU in Edit->preferences->system->oneAPI if issue reproduces

**Comment by NicCrimson** [comment]
I am using Blender Version 4.0.2. I tried disabling Embree and the same problem occurs.


https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/72427419/efb8115b-7973-43c8-95d6-ad38e85a9d02

Here is the new driver: 31.0.101.5186. As you can see when switching to render mode, nothing happens after a full minute.


https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/72427419/e097dccf-2717-4c0d-b321-fb0f5ac36342

Here is the older driver: 31.0.101.5084. As you can see when switching to render mode after a few seconds an image is displayed.

**Comment by Vivek-Intel** [comment]
@NicCrimson allow us some time to try simulate issue in our lab.

**Comment by Vivek-Intel** [comment]
@NicCrimson we tried to simulate the issue in our lab but could not see the problem with latest driver 5186/5194.
Can you share your project file to simulate the issue again, meanwhile just try newer driver 5194.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/114637913/f165c7d8-ac6d-4a1b-aee7-795cdf7136c4

**Comment by NicCrimson** [comment]
Issue seems to be resolved with latest driver: 5194
[](url)
[uzi.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14236383/uzi.zip)
