### ISSUE TITLE
Driver Level Black Frame Insertion

### ISSUE THREAD

**Issue by Powermann293** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#696]
### Application [Required]

Arc Control

### Processor / Processor Number [Required]

Ryzen 3700X

### Graphic Card [Required]

A770 16GB

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [X] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

I'm not even sure this is technically possible but I'll ask anyways. A setting in Arc Control to add Black Frames in between game rendered frames so it allows device side black frame insertion. This makes it so users on monitors with high refresh rates without BFI can still benefit from the feature as long as they have an Intel GPU. Even if it only works with V Sync on or some way to lock the framerate it would still be great.

**Comment by Gabriela-Intel** [comment]
Hi @Powermann293 Thanks so much for sharing your thoughts on how we can improve! We'll take this feedback to the team for them to review and investigate. :)

@IGCIT
