### ISSUE TITLE
Bad performance and stuttering in Ryse Son of rome without RTSS fps lock

### ISSUE THREAD

**Issue by Anoniemer** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#697]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Ryse: Son of Rome

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 5600

### Graphic Card [Required]

Arc A380, Arc A750, A770 16GB

### GPU Driver Version [Required]

31.0.101.5186

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14181415/igcit_ssu.txt)

Video: https://youtu.be/LH9AmyRIQR0

### Description and steps to reproduce [Required]

Happens on every settings, happens with ot without overlcock, driver doesn't seem to realize there is a game running, adding a global fps lock in riva tuner statistic server fixes the issue. 

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

2560x1440P resolution, settings doesn't matter, happens on low all the way to max settings.

**Comment by Vivek-Intel** [comment]
@IGCIT please help close it. user can reopen with updated info if any.
