### ISSUE TITLE
Cyberpunk 2077 XeSS black screen or artifacts

### ISSUE THREAD

**Issue by Anoniemer** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#698]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Cyberpunk 2077

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [X] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 5600

### Graphic Card [Required]

Arc A380, Arc A750 and Arc A770 16GB

### GPU Driver Version [Required]

31.0.101.5186

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14181499/igcit_ssu.txt)

### Description and steps to reproduce [Required]

When enabled XeSS and color precision medium I get a black screen and color precision on high I get artifacts, happens on all my arc cards at any setting with XeSS on, with ot without overlclock. 

Video: https://www.youtube.com/watch?v=LH9AmyRIQR0

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x11440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

All setting with XeSS on, Color precision medium causes black screen and high causes artifacts

**Comment by Karen-Intel** [comment]
Hey @Anoniemer ty for your report! And welcome to our support forum

I'm already doing some testing in both Win11 and Win10, using the Steam Game version. 
I will provide an update as soon as I have results/need more info. Talk to you soon

Karen

**Comment by Anoniemer** [comment]
save file it to big any other way I can share it? its like 180mb

**Comment by Karen-Intel** [comment]
Hey @Anoniemer update on this one

Just completed some testing on my end and I am unable to repro the visual artifacts you're seeing.

**Please have a look at the following videos and let me know if I'm missing anything**
**I included the Graphics Settings part and I will be doing more testing if necessary** 

[1st test:](https://www.youtube.com/watch?v=EittNnm-Gdc) done in Win 10, driver v5186, AMD Ryzen 5 + A380. Using your save game. No changes after enabling XeSS or artifacts
[2nd test:](https://www.youtube.com/watch?v=HuqneETuqYY) done in Win 10, driver v5186, AMD Ryzen 5 + A770. Using your save game. No changes after enabling XeSS or artifacts.

Thank you in advance!

Karen

**Comment by Anoniemer** [comment]
Really weird. I came across a Reddit post a while back with same exact issue and me. I’m trying to find it but have been unsuccessful so far. Exe name is Cyberpunk2077.exe and is located bin\x64 folder. It happens on all of my arc cards, A380, A750 and A770. Ddu’ing the driver doesn’t fix it and with a Nvidia card in the system it works fine. I’ll try a my arc card in different system.

**Comment by Karen-Intel** [comment]
@Anoniemer that would be great! Thanks!
Looking forward to hear from you :)

Karen

**Comment by Anoniemer** [comment]
It doesnt have the issues in other system, I went and compared my game folder and found a file that wasnt in the other one D3D12.dll. I had already reinstalled the game but I think it might have been left behind even after reinstalling. Removed the dll and seems fine now.

**Comment by Karen-Intel** [comment]
Yeeei that's wonderful @Anoniemer!

We would appreciate if you add this information in your video, in case it is helpful to other users who might be experiencing something similar. As I have created a tracking case for this post, I will add the dll details to the resolution.

Would you agree to close this case? 
I'm glad it was just a false alarm and we appreciate that you could verify so quickly in another system :)

Have a great day!

Karen

**Comment by Arturo-Intel** [comment]
> found a file that wasnt in the other one D3D12.dll.

Do you think this was not removed when uninstalling the game? Maybe is a custom lib? or something related?

**Comment by Anoniemer** [comment]
I have cut out that part of video and will add fix for the issue in a Reddit post recently, in case someone ever encounters it they will be able to find that post pretty easily.

**Comment by Karen-Intel** [comment]
@Anoniemer appreciate it, and remember we're here to help! 
@Arturo-Intel do the honors please :)

Karen
