### ISSUE TITLE
Sons of The Forest Fps drops near rocks

### ISSUE THREAD

**Issue by Anoniemer** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#699]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Sons of The Forest

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 5600

### Graphic Card [Required]

Arc A380, A750 and A770

### GPU Driver Version [Required]

31.0.101.5186

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14181539/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Happens on all settings, To repoduce looks for some clifs and walk close to rocks and fps will tank. 

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Lowest setting or highest doesnt matter, TAA AA and 1080P or 1440P, happens on all.

Video: https://www.youtube.com/watch?v=LH9AmyRIQR0

**Comment by Vivek-Intel** [comment]
@Anoniemer Thanks for reporting the issue. we are looking into it and would get back to you with updates or if we need more info.

**Comment by Vivek-Intel** [comment]
internal bug id 14021168880 for this issue.

**Comment by Pashamolochko** [comment]
in Driver 31.0.101.5379, the problem with the stones was solved on my system

**Comment by Vivek-Intel** [comment]
@Pashamolochko thank you for updates.
@Anoniemer 14021168880 is fixed in 101.5379 so can you please test and update this thread

**Comment by Vivek-Intel** [comment]
@IGCIT please help close this issue - [Article](https://www.intel.com/content/www/us/en/support/articles/000098059/graphics.html)
