### ISSUE TITLE
Just Cause 3: Uses all memory (memory leak)

### ISSUE THREAD

**Issue by marph43** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#70]
#### Checklist [README]

- [X ] Device is not undervolted nor overclocked.
- [ X] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [X] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Just Cause 3
---
#### Game Platform [Required]
- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
---
#### GPU Driver Version [Required]
- [X] 30.0.100.9667 (*latest*)
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [X] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

The game uses way too much memory. The total memory of the GPD Win 3 is 16 GB and the game uses more than 10 GB. On my other Win 10 pc with an Nvidia GPU it does not even exceed 4 GB. It very much looks like there's a memory leak of some kind.
1. Start the game with Steam. At first the game uses about 5 GB of memory.
2. In the main menu select "Start". Now the game process quickly takes almost all of the remaining memory.
3. Play for some time. The game is playable, but the frame rate is very unstable and drops often, which produces a lot of stuttering.
4. After playing approx. 5-10 min. the game tends to crash. It happens often if it quickly has to load a lot of stuff. For example while driving.

---
#### Device / Platform [Optional][Recommended]

GPD Win 3 (G1618-03)

---
#### Game Settings [Optional][Recommended]

I've tried every different setting possible: High, mid, low and a great combination of specific settings (settings that users recommended to turn off on several places on the internet). The settings I choose do not have much of an impact on the performance, because the issue is that there is no remaining memory.

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---
#### Windows mini dump (*small memory dump*) (*if available*) [Optional][Recommended]

![jc3 memory graph](https://user-images.githubusercontent.com/56201105/124939332-4dd40480-e009-11eb-9b2a-96f2addaa1bd.PNG)
![jc3 process](https://user-images.githubusercontent.com/56201105/124939409-5debe400-e009-11eb-8b87-fa82551c0063.PNG)

---

**Comment by IGCIT** [comment]
Something wrong is happening for sure here, but please note:

Your Nvidia GPU has its own VRAM.
The Intel GPU uses your RAM as VRAM, so do not expect the same RAM usage of a pc that is using a discrete GPU.

**Comment by marph43** [comment]
Good news: The memory leak has gone with the latest Intel driver (30.0.100.9862)! This makes the game much more playable. It does not crash any more after a short while and the fps drops are not as grave anymore. However the fps still frequently drop below 30. Setting all the graphical settings to the lowest does not fix it, so I recommend maxing them out (more or less) and limit the fps to 30 (with RivaTuner). This makes the frame drops a little less annoying.

**Comment by IGCIT** [comment]
since the issue has been fixed, closing this :)
