### ISSUE TITLE
Poor performance in Granblue Fantasy Relink

### ISSUE THREAD

**Issue by Anoniemer** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#702]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Granblue Fantasy Relink

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 5600

### Graphic Card [Required]

Arc A380, Arc A750 and A770 16GB

### GPU Driver Version [Required]

31.0.101.5186

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14181650/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Lowest in game setting, first town you encounter early in the game. Fps drops below 30. DXVK increase fps by 2X. Happens with and without overclock on all my arc cards.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

standard settings ingame which is lowest. 1080P resolution.

**Comment by Arturo-Intel** [comment]
I was able to reproduce this performance issue on windows 11 + intel 12gen CPU + Arc750.
I will share any news here.

-- r2

**Comment by Anoniemer** [comment]
thanks hope to here back from you

**Comment by EstebanIntel** [comment]
Hi @Anoniemer,

A possible fix for this issue is included with driver version [31.0.101.5379](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html). Can you please install this version and test it out?

**Comment by EstebanIntel** [comment]
@Anoniemer had you had the chance to test this?

**Comment by Anoniemer** [comment]
Fixed
