### ISSUE TITLE
Random VIDEO_TDR_FAILURE BSOD when playing Path of Exile

### ISSUE THREAD

**Issue by Prayer-R** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#703]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Path of Exile

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

https://www.pathofexile.com/

### Processor / Processor Number [Required]

PathOfExile.exe

### Graphic Card [Required]

Intel A770LE 16GB

### GPU Driver Version [Required]

31.0.101.5186

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14184310/ssu.txt)

### Description and steps to reproduce [Required]

* Play game normally, please use the official client(https://www.pathofexile.com/), not steam, not epic.
* Wake up after sleep(not hibernate) or Watch youtube videos while playing game easier BSOD.
* When BSOD, screen like this [flickering](https://community.intel.com/t5/Intel-ARC-Graphics/Intel-ARC-A770-LE-BSOD/m-p/1538981?attachment-id=98750).
* This issue always existed from 4577(bought graphics card) to 5186(latest WHQL).
* Tried use DDU in safe mode to fresh install driver.
* Tried reformat hard disk and reinstall Windows.

I'll keep track the issue, can streaming, can remote desktop, if helps.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

3840x2160

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Path `C:\Users\[User Name]\Documents\My Games\Path of Exile\production_Config.ini`
[production_Config.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14184773/production_Config.txt)

### Crash dumps [Required, if applicable]

latest 2 minidump
[020724-9625-01.dmp](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14184685/020724-9625-01.dmp)
[020224-7906-01.dmp](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14184686/020224-7906-01.dmp)

**Comment by Prayer-R** [comment]
> @Prayer-R does issue occur only with POE, or with other games as well ? does issue occur when playing from Steam ? what is repro rate of the issue (?/5) and how long in the game it takes to trigger the issue ? Can you update to latest BIOS and check the issue again? did you notice temp of GPU , CPU temp just before issue occurrence?

Issue occur only with POE, no issues found with other games yet.
Steam client performs worse than official client(Game developer's issue), most player use the official client, me too, so i don't know does issue occurring on the Steam client.
Random occurrence(1/5), wake up after sleep then playing game(3/5), watch youtube videos while playing game(2/5).
It can be triggered in about 15 minutes at the shortest, maximum a few hours(2-3h).
When there is a lot of content and monsters in the screen, easier to trigger, you may need level up to 80+, maybe hard to test, but i'll wait.
Tried 7D76vA6(AGESA ComboPI 1.0.0.7c)-7D76vAB1(AGESA ComboPI 1.1.0.1), i'll try 7D76vAB4(AGESA ComboPI 1.1.0.2b latest) and check it again.
When playing PoE, temp of GPU maximum 75°, temp of CPU maximum 70°.

**Comment by stalker-svk** [comment]
try to increase TDR delay time
launch this REG file and reboot PC, then check again if the error still occurs.
[GPU TDR Delay.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14221498/GPU.TDR.Delay.zip)

**Comment by Prayer-R** [comment]
> try to increase TDR delay time launch this REG file and reboot PC, then check again if the error still occurs. [GPU TDR Delay.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14221498/GPU.TDR.Delay.zip)

TdrDelay and TdrDdiDelay already set to 60s, not occur BSOD after uptate to AGESA ComboPI 1.1.0.2b, doubt is AGESA bug.
Observe for a few more days.

**Comment by Prayer-R** [comment]
Not occur BSOD after update AGESA ComboPI 1.1.0.2b, close issue.
