### ISSUE TITLE
Device randomly flickering, sometime won't detect 2nd screen at startup. 

### ISSUE THREAD

**Issue by peace20021** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#704]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Just normal windows booting

### Processor / Processor Number [Required]

Ryzen 5 5600X

### Graphic Card [Required]

Sparkle Arc 770 Titan 16GB

### GPU Driver Version [Required]

31.0.101.5186

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [X] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

19044.3930

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14203211/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Usually it happens the most when I boot up windows. It also stops detects my 2nd screen when I turn off too. 

### Device / Platform

Desktop PC

**Comment by peace20021** [comment]
This only happens with the new driver, I can try reinstalling old driver to see if still happens.

**Comment by Arturo-Intel** [comment]
>This only happens with the new driver, I can try reinstalling old driver to see if still happens.

@peace20021 Yes please, that would help us a lot!

**Comment by peace20021** [comment]
> > This only happens with the new driver, I can try reinstalling old driver to see if still happens.
> 
> @peace20021 Yes please, that would help us a lot!

I have tried and it's still happening. I'm assuming some firmware update for the card might make this happens. There's also a chance of heavy flickering when I boot up the machine. I have a video for that will upload it after I'm leaving from work.

**Comment by Vivek-Intel** [comment]
@peace20021 there is a new driver [101.5194](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) so can you try clean the system using [DDU](https://www.guru3d.com/download/display-driver-uninstaller-download/) in safe mode and install driver to check if issue occurs.

I see there are some updates available for Windows 10 LTSC so please try updating windows update as well.

**Comment by Vivek-Intel** [comment]
@peace20021 Gentle reminder

**Comment by Vivek-Intel** [comment]
@IGCIT please help close this

**Comment by peace20021** [comment]
> @peace20021 Gentle reminder

Hi, I have recently returned my GPU due to it having hardware issue. Sorry for the late reply, you can close this.
