### ISSUE TITLE
Spider-Man Remastered performance drops significantly

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#705]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Spider-Man Remastered

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

intel Core i5-13700KF

### Graphic Card [Required]

intel Arc A770

### GPU Driver Version [Required]

31.0.101.5081

### Other GPU Driver version

31.0.101.5186

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU_20240210.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14224707/SSU_20240210.txt)

### Description and steps to reproduce [Required]

I did some benchmarks with this game in early January and it was okay without problems at that time. However, after seeing some people mentioning issues with this game on reddit recently, I retested it and found that some severe problem started to exist. 

Back in January when I benchmarked the game, the GPU utilization was above 90% and the framerate was around 90 FPS. Now the GPU utilization drops to 70-ish% and the framerate drops to around 65 FPS. I tried driver version 5081 and 5186 and both have the same behavior (low GPU utilization and low FPS). (It was on driver 5081 when I did the benchmarks in January.)

Currently I find only one workaround which is disabling both Hyper-Threading and E-cores: with only P-cores and Hyper-Threading off, the GPU utilization can jump back to around 90% and the framerate can be restored to roughly 85 FPS, which is still not as good as the result I got in January but apparently helpful as of now, and a key fact is that I didn't have to use this trick (workaround) for it to run properly. Something has gone wrong between now and then.

Since disabling E-core and Hyper-Threading is obviously effective right now, I guess the issue has something to do with process scheduling or Thread Director. Nevertheless, not much have been changed with my PC since then. The only clues I can think of are some Windows Updates during this period of time, so I'll list them below:

- 2024-01 Cumulative Update for .NET Framework 3.5, 4.8 and 4.8.1 for Windows 10 Versio 22H2 for x64 (KB5034275)
- 2024-01 Cumulative Update for Windows 10 Version 22H2 for x64-based Systems (KB5034122)
- 2024-01 Security Update for Windows 10 Version 22H2 for x64-based Systems (KB5034441)

Another important clue is that I just found with another system with Windows 11 and Arc A750 that this problem seems not to exist on Windows 11. The GPU utilization is well above 90% and the framerate is good when running this game on that system.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

with XeSS "Quality" mode

**Ray-Tracing must be ON.
If RT is off then this problem won't occur.

**Comment by Susie1818** [comment]
Supplementary information: right now this game has random crashes A LOT, often when launching or exiting the game or when toggling ray-tracing on/off. Back in early January when I was doing extensive benchmarks (had at least 8 runs because I have 8 sets of statistics in my notes) on this game, it didn't behave like this.

**Comment by Susie1818** [comment]
I guess it's because something in Windows system mistakenly makes the Arc driver running on E-cores or the secondary threads of P-cores. Right now if I turn off both E-cores and Hyper-Threading, the game works okay, but if I let either E-core or HT (or both) to be enabled, the game just doesn't work correctly. However, it did work normally back in early January. This is a very weird case. I've been using the Arc GPU since December 2022 and so far this is the first and the only case that manifests this kind of problem.

**Comment by Susie1818** [comment]
For your reference:

8P+8E / no HT (16C16T, the preferred configuration I have always been using, and it used to work without an issue a month ago) 
![Screenshot (176)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/124469949/42461ab0-735f-43d6-8635-783c4fb3798c)

8P+0E / HT on (8C16T)
![Screenshot (238)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/124469949/da3de925-5df7-486c-ad85-e85591502ef7)

8P+8E / HT on (16C24T)
![Screenshot (181)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/124469949/8dac9563-8ea8-4da2-8e08-87af9b8066c8)

8P+0E / no HT (8C8T)
![Screenshot (196)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/124469949/b54235e5-c5ff-4e97-bb59-893f28b4435e)

👇 *Ray-Tracing OFF* then no problem
![Screenshot (178)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/124469949/59c56282-6592-40a3-9c73-ee4ab20d85ce)

**Comment by Susie1818** [comment]
For your reference: (on my Windows 11+A750 system, the same Ray-Tracing settings: Very High, object range: 3)

👇This is how it should work correctly.
![Screenshot (10)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/124469949/a8464cba-3729-4a40-a07a-240f6e5a5408)

**Comment by mujeeb-intel** [comment]
Hi @Susie1818 this is very helpful. Thanks.

Quick question: your statement "Another important clue is that I just found with another system with Windows 11 and Arc A750 that this problem seems not to exist on Windows 11. The GPU utilization is well above 90% and the framerate is good when running this game on that system." does this mean on win 11 w/ 13700KF it works without any issues but on win 10 with 13700KF  you are seeing performance issues?

**Comment by Susie1818** [comment]
@mujeeb-intel 

I don't think it has anything specific to do with 13700KF.

1. It used to be without any issue on my Windows 10 system.
2. I don't want to switch to Windows 11 from Windows 10 on this system merely to verify whether it solves the problem or not. Even if it does, it's just a workaround but not a real fix to the problem because the game has been running on Windows 10 without an issue for months until recent Windows Updates. You can take a look at the screenshots I provided above.

**Comment by mujeeb-intel** [comment]
I understand. Just making sure that the issue does not persist on win 11. This way I can focus on win 10 trying to reproduce this issue.  so win 11 doesnt have any issue but with win 10, does.

**Comment by Felipe-Intel** [comment]
Hello @Susie1818 we shared this info with our dev teams under ticket number 14022009955. As soon as we have new info we'll be in touch.

**Comment by mujeeb-intel** [comment]
HI @Susie1818 with the driver version 101.5762 Im not observing poor performance. In the city its showing 80+ as average and sometimes dipping to 75fps but I am also getting over 100fps as well when swinging around the city. With my hour and half gameplay, no crashes were observed as well.

All of this is with RT running at the maximum with xess set to quality with 1440p resolution.

Could you please give it a try with the latest driver and confirm?

**Comment by Susie1818** [comment]
@mujeeb-intel I have to apologize. I couldn't wait so long, so I have installed Windows 11 on my system. As I mentioned earlier, the problem doesn't exist on Win 11, so I can't confirm if driver v5762 has the issue fixed. If you did reproduce the problem on Win 10 with an earlier version of Arc driver, then I think you can confirm it by yourself.

**Comment by mujeeb-intel** [comment]
Awesome! Thanks. 

@IGCIT please go ahead and close the ticket.
