### ISSUE TITLE
Skull & Bones vram usage maxed out A750 first town

### ISSUE THREAD

**Issue by Anoniemer** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#707]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Skull & Bones Open Beta

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [X] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 5600

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

31.0.101.5194

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14234288/igcit_ssu.txt)

### Description and steps to reproduce [Required]

When entering first big town vram usage on my a750 is at 7.8GB and game performance is pretty low and stuttering. In the bay area at start of beta its much lower vram (6.5 to 7GB) usage at higher settings. Video: https://www.youtube.com/watch?v=p4QxSlffX50

I also saw a guy with a 1060 getting around same fps, also low setting just TAA balanced instead of FSR Quality with 4-4.5GB vram usage and no stuttering. Video: https://www.youtube.com/watch?v=T1KvEviwAJg

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Lowest settings, FSR set to quality. 1080P and 1440P

**Comment by mujeeb-intel** [comment]
Hello @Anoniemer Please try with the latest driver by going here: https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html As this supports day 1 for skull and bones.

**Comment by Anoniemer** [comment]
This is already with the latest game ready driver

**Comment by mujeeb-intel** [comment]
Got it. I was confused because the gpu driver mentioned in this github post was "31.0.101.5194" also can you confirm whether you are on the skull and bones beta? I know the premium edition of the game allows 3 days of early access, is that what you're on?

**Comment by Anoniemer** [comment]
Yes driver is 5194 which is latest one. Also the same one you just linked me. Yes I was playing the open beta, do not feel like preordering any game these days.

**Comment by mujeeb-intel** [comment]
Actually, the one I have linked is the 101.5252 and that is the one with supporting skulls and bones, can you try on this, please?. Makes sense, I too, don't pre order until some time has passed by for the patches. The last game I pre-ordered was cyberpunk 2077 and we all know how the launch went.

**Comment by mujeeb-intel** [comment]
So I was playing this today. I don't think I've reached at the same map place as yours. The two missions from black smith has been done and noticed fps in high 40s fps and 60 when in the sea with the vram being used 6GB. 

Is this the island you are on? I think your video said "pirate town" can you help tell me how far I am from this mission to reach pirate town? It's a very slow game.

**Comment by Anoniemer** [comment]
I don’t know if official game follows the same but it started with big ship battle, then your ship gets wrecked and you get picked up a woman in smaller boat. Once in the boat I finished all the quests there. That area had a big ship cut in half basically and you could sail through the middle (see video for area), after doing some of the quests there I was able to leave that area and got in that pirate town (whatever official name is). Was like 30 minutes in or so.

**Comment by Anoniemer** [comment]
Here is a video I found and the area I have problems is 24 minutes in. https://youtu.be/_t--dIfd-yI?si=yIjSuYsGdFaQke7g

**Comment by rmorera-intel** [comment]
Hello @Anoniemer please re-test with our latest WHQL[ driver 32.0.101.6130](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) and let me know if the issue persist.
