### ISSUE TITLE
World of Warplanes - crash when entering match

### ISSUE THREAD

**Issue by zrmdsxa** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#708]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

World of Warplanes

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

Wargaming Game Center

### Processor / Processor Number [Required]

Ryzen 7600X

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

31.0.101.5186

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14234564/report.txt)

### Description and steps to reproduce [Required]

1. Enter a match. You can do this by starting a training room

It seems pretty random but I was able to do it just by starting Road to Rome - Ascension.

Here is the response from Wargaming: "I see you're using Intel Arc - we have no support for those and the issue most probably is in their drivers"

These are the last log messages when the crash happens.

 34.485 ASSET: EffectCompiler::createEffect: Error creating effect for 'shaders/hammer/aircraft_damaged_lod0.fx' (reason = E_OUTOFMEMORY(0x8007000e) : Direct3D could not allocate sufficient memory to complete the call.)
 34.485 ASSET: EffectManager::get - unable to load shaders/hammer/aircraft_damaged_lod0.fx
 34.485 ASSET: EffectCompiler::createEffect: Error creating effect for 'shaders/hammer/aircraft_damaged_lod0_skinned.fx' (reason = E_OUTOFMEMORY(0x8007000e) : Direct3D could not allocate sufficient memory to complete the call.)
 34.485 ASSET: EffectManager::get - unable to load shaders/hammer/aircraft_damaged_lod0_skinned.fx
 34.486 ASSET: EffectCompiler::createEffect: Error creating effect for 'shaders/std_effects/normalmap_specmap_alpha.fx' (reason = E_OUTOFMEMORY(0x8007000e) : Direct3D could not allocate sufficient memory to complete the call.)
 34.486 ASSET: EffectManager::get - unable to load shaders/std_effects/normalmap_specmap_alpha.fx
 34.487 ASSET: EffectCompiler::createEffect: Error creating effect for 'shaders/hammer/aircraft_glass_alpha.fx' (reason = E_OUTOFMEMORY(0x8007000e) : Direct3D could not allocate sufficient memory to complete the call.)
 34.487 ASSET: EffectManager::get - unable to load shaders/hammer/aircraft_glass_alpha.fx
 34.487 ASSET: EffectCompiler::createEffect: Error creating effect for 'shaders/hammer/aircraft_glass_alpha_skinned.fx' (reason = E_OUTOFMEMORY(0x8007000e) : Direct3D could not allocate sufficient memory to complete the call.)
 34.487 ASSET: EffectManager::get - unable to load shaders/hammer/aircraft_glass_alpha_skinned.fx
 34.488 ASSET: EffectCompiler::createEffect: Error creating effect for 'shaders/hammer/aircraft_object.fx' (reason = E_OUTOFMEMORY(0x8007000e) : Direct3D could not allocate sufficient memory to complete the call.)
 34.488 ASSET: EffectManager::get - unable to load shaders/hammer/aircraft_object.fx
 34.489 ASSET: EffectCompiler::createEffect: Error creating effect for 'shaders/hammer/aircraft_internal.fx' (reason = E_OUTOFMEMORY(0x8007000e) : Direct3D could not allocate sufficient memory to complete the call.)
 34.489 ASSET: EffectManager::get - unable to load shaders/hammer/aircraft_internal.fx
 34.489 ASSET: EffectCompiler::createEffect: Error creating effect for 'shaders/hammer/aircraft_mesh_propeller.fx' (reason = E_OUTOFMEMORY(0x8007000e) : Direct3D could not allocate sufficient memory to complete the call.)
 34.489 ASSET: EffectManager::get - unable to load shaders/hammer/aircraft_mesh_propeller.fx
 34.495 NOTICE: [ENVMIN] Can't load ocean resources, ocean disabled
 34.495 NOTICE: Imposters::load_container: Failed to open file (spaces/00_19_hangar_base_2017/imposters.bin)
 34.496 ASSET: EffectCompiler::createEffect: Error creating effect for 'shaders/speedtree/trees.fx' (reason = E_OUTOFMEMORY(0x8007000e) : Direct3D could not allocate sufficient memory to complete the call.)
 34.496 ASSET: EffectManager::get - unable to load shaders/speedtree/trees.fx
 34.497 ASSET: EffectCompiler::createEffect: Error creating effect for 'shaders/speedtree/tree_instancing.fx' (reason = E_OUTOFMEMORY(0x8007000e) : Direct3D could not allocate sufficient memory to complete the call.)
 34.497 ASSET: EffectManager::get - unable to load shaders/speedtree/tree_instancing.fx
 34.498 ASSET: EffectCompiler::createEffect: Error creating effect for 'shaders/speedtree/tree_imposter.fx' (reason = E_OUTOFMEMORY(0x8007000e) : Direct3D could not allocate sufficient memory to complete the call.)
 34.498 ASSET: EffectManager::get - unable to load shaders/speedtree/tree_imposter.fx
 34.499 ASSET: EffectCompiler::createEffect: Error creating effect for 'shaders/std_effects/normalmap_specmap.fx' (reason = E_OUTOFMEMORY(0x8007000e) : Direct3D could not allocate sufficient memory to complete the call.)
 34.499 ASSET: EffectManager::get - unable to load shaders/std_effects/normalmap_specmap.fx
 34.500 INFO: [SCRIPT] (scripts/client/audio/SoundObjects/MusicSound.py, 27): [AUDIO] Hangar 00_19_hangar_base_2017 doesn't found in sound_settings.xml

CRITICAL: Access violation (0xC0000005) at 0x02C60D2B
Reading location 0x0000009C

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5502880/f9f7725a-77a8-4a75-a777-0a217f67296b)

**Comment by zrmdsxa** [comment]
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5502880/181dec2a-317b-4de1-80c9-496d2053bba5

**Comment by Felipe-Intel** [comment]
hello @zrmdsxa 
I just tried the process shown in the video and my game didn't crash. How randomly/consistently are you experiencing your issue. I'm running driver 5194. Try a DDU and install this driver and let me know if your game still crashes.

**Comment by zrmdsxa** [comment]
I feel it happens often when I play random matches at high tier and get the map Cold Peak - Piercing Wind.

After using DDU and running 5194, I was able to get it to crash once by having msiafterburner/rtss running on the map Road to Rome - Ascencion in the training room but it didn't happen again so it is inconsistent.

**Comment by Felipe-Intel** [comment]
After being able to play normally (last week when I wrote to you) I installed the MSI AB today and tried to play and my game crashed consistently when loading Cold Peak - Piercing Wind and other scenarios. I'm going to make a clean install of my OS and give the game a try again. 
The dumps generated by my crash pointed to "bwclient.dll" that is a file of the game, not the driver. 
Can you check if you have any DMP file? Look in "C:\Users\<your_username>\AppData\Local\crashdumps"
Where did you get your logs? I looked into "WorldofWarplanes.log" file but it is empty, even after the crashes. 
Also just as a precaution, make sure you are running in a recent driver (could be 5194 or latest 5330 released during the weekend), update the BIOS and Windows (you are probably there). I'll come back to you as soon as I try the game again.

**Comment by zrmdsxa** [comment]
There is a ToLogs.cmd that takes you to AppData\Roaming\wargaming.net\World of Warplanes\logs. This is also where the .dmp files are generated by the game.

Here is my dmp from crashdumps though https://www.mediafire.com/file/llym46yo3p8kiye/WorldOfWarplanes.exe.12188.dmp/file

**Comment by Felipe-Intel** [comment]
Hello. As I mentioned, I reinstalled windows, installed the game and had no problems. Installed MSI AB and tried the game again and I was able to play the scenarios mentioned. No problems from my side after the reinstall. Maybe try reinstalling the game or verify the files? The dump you provided also points to "bwclient.dll".

**Comment by Felipe-Intel** [comment]
Hi @zrmdsxa 
Since we have not heard any feedback regarding our previous post, we will close this thread now. If you need further assistance, please create a new thread and refer to this one.
