### ISSUE TITLE
Company of Heroes crashes

### ISSUE THREAD

**Issue by LordR7** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#711]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Company of Heroes

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i9-13900K

### Graphic Card [Required]

A770 16GB

### GPU Driver Version [Required]

31.0.101.5194

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [X] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14272610/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Start a random skirmish o any map. Game will crash within 1 minute after loading the map.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

3440 x 1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![Settings](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/94077993/4dedde03-7138-4465-ba52-8b672ea25d7e)

### Crash dumps [Required, if applicable]

[warnings.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14272685/warnings.log)
[CoHNLVT38A3.dmp](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14272693/CoHNLVT38A3.dmp)

**Comment by Ilya-intel** [comment]
Hey @LordR7 ,
I've played the full skirmish battle without any error messages.
So could you first try the latest 31.0.101.5330 driver.
And if won't help try the following workaround:

1. Click your start menu and type "regedit" and click on "Registry Editor"
2. Copy this text and paste it into the "address bar" at the top: 
 > Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers
4. Right click the white space in the right-hand pane and select "New" -> "DWORD (32-bit) Value"
5. You will get a new item called "New Value #1" - Rename this to TdrDdiDelay and hit "enter"
6. Double click the new entry and make sure "Hexadecimal" is selected for "Base" and set the "Value data:" field to 3c
7. Repeat step 3 - 5, but rename this entry to TdrDelay and use the same values. Only the name should be different.
8. Restart your system and try to play.

**Comment by LordR7** [comment]
Only difference with the settings is, that the game freeze now before it crashes after some more time. New Driver does not help either.
[warnings.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14425946/warnings.log)

**Comment by Ilya-intel** [comment]
@LordR7 
I am still not able to replicate the issue on the 3rd system.
Could you try the latest 5379 driver?
https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html

**Comment by Ilya-intel** [comment]
@IGCIT thread seem to be abandoned, kindly close it. Thanks.
