### ISSUE TITLE
[libvpl D3DTexture2D import] video encode crashed with MFX_ERR_LOCK_MEMORY error

### ISSUE THREAD

**Issue by ma3uk** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#713]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

OBS Studio video encode plugin

### Processor / Processor Number [Required]

12700K

### Graphic Card [Required]

Intel Arc A380

### GPU Driver Version [Required]

31.0.101.5194

### Other GPU Driver version

31.0.101.5330

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14318530/igcit_ssu.txt)

### Description and steps to reproduce [Required]

OS: Windows 11 23 H2
Video driver: gfx_win_101.5330, gfx_win_101.5194, gfx_win_101.5186
Video card: Arc A380

I am developing a plugin for OBS Studio using libvpl for real-time coding. With the release of libvpl 2.10, textures for encoding were added and supported, it works, but I ran into a problem, after a few minutes the encoding process was interrupted with the error MFX_ERR_LOCK_MEMORY from the EncodeFrameAsync function. Further attempts to start encoding are immediately interrupted with the MFX_ERR_LOCK_MEMORY error until the application is restarted.

A step-by-step process that I'm doing:

1. A pool of intermediate textures is being created
2. Copying an external texture to pool
3. Importing textures from a pool to libvpl
4. Encode
The error occurs at stage 4. There are no errors in the first 3 stages

The source code of the application can be found at the links below:

- The function of allocating a pool of intermediate textures - https://github.com/ma3uk/obs-qsv-onevpl/blob/edf5864eec4a3965dc660e48b4641bd9404daa7f/obs-qsvonevpl/obs-qsv-onevpl-encoder-internal.cpp#L1266

- The internal function of texture allocation - https://github.com/ma3uk/obs-qsv-onevpl/blob/edf5864eec4a3965dc660e48b4641bd9404daa7f/obs-qsvonevpl/helpers/common_directx11.cpp#L131

- The function of copying an external texture to a texture pool - https://github.com/ma3uk/obs-qsv-onevpl/blob/edf5864eec4a3965dc660e48b4641bd9404daa7f/obs-qsvonevpl/helpers/common_directx11.cpp#L273

- The function of importing textures into libvpl and encoding - https://github.com/ma3uk/obs-qsv-onevpl/blob/edf5864eec4a3965dc660e48b4641bd9404daa7f/obs-qsvonevpl/obs-qsv-onevpl-encoder-internal.cpp#L1607

It is also worth clarifying that in my case the error occurs when encoding the 65537 frame.

**Comment by ma3uk** [comment]
I can provide a compiled plugin file to reproduce the error in OBS Studio

**Comment by ma3uk** [comment]
Addition: when testing on the integrate graphic UHD 770 video card, the video encoding process is interrupted with an error MFX_ERR_DEVICE_FAILED

**Comment by ma3uk** [comment]
> вы видите такое поведение на графических процессорах Nvidia или AMD или только с графическими процессорами Intel Arc / UHD?

Only on Intel A380 and UHD 770

**Comment by Arturo-Intel** [comment]
@ma3uk Let me do some experiments on my side, but please go to https://github.com/intel/libvpl/issues and request support from them as Esteban mention. they are the experts on this matter.

**Comment by ma3uk** [comment]
@Arturo-Intel Thank you for taking up this issue.
I created a support request in the libvpl repository - https://github.com/intel/libvpl/issues/125
I will be very glad for your help in solving the problem.
