### ISSUE TITLE
Problem with Display waking up after it turns off to save power.

### ISSUE THREAD

**Issue by MadArson1999** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#714]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 11 Pro

### Processor / Processor Number [Required]

i5-13600k

### Graphic Card [Required]

Arc A770 Acer Predator Bifrost 16GB OC

### GPU Driver Version [Required]

31.0.101.5330

### Other GPU Driver version

31.0.101.5194 and 31.0.101.5330

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [x] Not applicable

### Windows Build Number [Required]

- [x] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14320335/Intel.SSU.report.txt)

### Description and steps to reproduce [Required]

![IMG_20240217_114600](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143818045/29e82a20-e807-48c7-b2bc-98bb254a4790)
https://youtu.be/FEXwGieVGuU video of issue.
Description: Up until driver 31.0.101.5085 everything was fine and once my screens turned off after set time in windows power settings 15 min in my case (30 min is when pc enters deep sleep that only power button can wake) then i simply move mouse to wake them up. both screens turn on fine main one take a little longer start but its this monitor behaviour, but after updating driver to 31.0.101.5186 and up to 5330. once my screen went sleep power saving mode when i try to wake them up, the secondary one connected to IGPU in my i5-13600k stays black and main one connected to Arc A770 from Acer turns on and then off and on and off till i restart either PC or just gpu driver with CTRL + WINDOWS + SHIFT + B. how to reproduce it. not sure if its my combo of IGPU and GPU and both displays connected to one and another or if its driver issue or both, if you can test that with the same config of 13th gen CPU IGPU and ARC A770 with 2 displays one connected with HDMI to IGPU and another to ARC with DP, then you need to let windows power saving setting to turn off displays/set them to standby mode, and try to wake them up with mouse or keyboard input, note for me when i tried wake them as soon as they turned off it sometimes would start normally but after longer period of sleep the issue would appear. Turning PC on from shutdown/deep sleep/hibernation don't have such issue.

### Device / Platform

Desktop computer assembled by me

**Comment by Vivek-Intel** [comment]
@MadArson1999 I tried to replicate this issue in our lab with different setups but could not see any problem display resume from power saving mode, so can you please try below and provide info :

1: can you uninstall driver using DDU, and then check if you get the same behavior even without driver
2: clean install driver after DDU and then connect same display to only igpu-check the issue
3: connect same display to arc-check the issue 
3: is it possible to try different display type, and try HDMI/DP ? , share the model of display that you are using

**Comment by MadArson1999** [comment]
@Vivek-Intel So i just tested the few things you asked for:
1. After DDU with no driver only secondary screen would work but then windows update loaded old drivers: 31.0.101.4575 for ARC and 31.0.101.4889 for IGPU, didn't changed what screen was plugged where but problem didn't occured. just as i said all was fine until driver 31.0.101.5085 as every one after have this issue for me.
2. with driver 31.0.101.5330 after DDU with both screens connected to IGPU secondary with HDMI as it don't have other option and main with DP, secondary would wake up but main couldn't wake up at all, restarting driver helped.
3. with both screens connected to ARC, main with DP and secondary with HDMI both screens wake up with no problems.
4. i think i could test it with other display but i need more time for that maybe in weekend i don't think i can test my main display over HDMI becasue i don't have enough HDMI ports and couldn't connect both with HDMI to the same GPU/IGPU. Model of my main display is KTC M27T20 and secondary according to system is L01N8A but i call it Jonsbo D31/D41 case screen as it is part of computer case/chassis.

**Comment by Vivek-Intel** [comment]
@MadArson1999 thanks for quick response. I see KTC M27T20 causing issue when connected to igpu only ? (no issue with Arc)? 
can you just use single display (KTC) and see if it is still giving issue on igpu when connected via DP/HDMI. (do not connect other display for sake of isolation of the issue)

Also can you get dispdiag logs when issue occur (Open CMD in any folder path  --type 'dispdiag' --enter--collect dump generated)
unfortunately we do not have exact same display in our lab to check but I have verified with other multiple displays and could not see any such  problem so can you try changing refresh rate and resolution and check if lowering resolution helps.

**Comment by MadArson1999** [comment]
@Vivek-Intel if both of screens are connected to ARC there is no problem (DP+HDMI), if BOTH screens are connected with HDMI one to IGPU and other to ARC there is no problem.
When KTC is only display connected to IGPU via DP it can't wake up at all (the led that signals that it get signal to wake up turns blue and all but its black no video) until i restart driver, tested it also with lowering both refresh and res and even disabled HDR.
When connected to IGPU with HDMI on the other hand it have no problem with waking up even on max res and refresh + HDR.
So far problem with waking occurs when:
1. Secondary screen is connected to IGPU with HDMI while KTC is connected to ARC via DP that resoult in secondary display having backlight waked up but no video where main wake up show picture for few seconds and goes black again doing that in loop until i do driver reset.
2. When main display is connected via DP to IGPU (if secondary is also connected with HDMI to IGPU its the same resoult) it gets wake up signal but no video is displayed until i do driver reset
[DispDiag-20240221-235127-13192-14580.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14366011/DispDiag-20240221-235127-13192-14580.zip)
this Dump is when my main display was connected as only display with DP to IGPU after waking up so i didn't saw screen at all prepared command in CMD to just do dump with single ENTER button press while blind.

**Comment by Vivek-Intel** [comment]
@MadArson1999 thanks for efforts that you are putting in to try troubleshooting steps suggested.
below are few things you can try at this point since this issue is very specific to monitor :
1:power off monitor completely remove all cables and check if you have reset option in monitor OSD menu. connect back the monitor to check the issue.
2: check with other displays, try changing DP cable of KTC monitor (it could be DP cable that you are using). If possible check this monitor with other system ?
3: We would suggest to check with KTC support and check if they have any known issue or resolution.

**Comment by MadArson1999** [comment]
@Vivek-Intel i don't know what happened but tried powering display off, and unplugging it but i don't have access to osd setttings until display gets signal from gpu so i plugged it back, reseted OSD, then enabled everything back like HDR+LD, freesync/VRR and KVM for mouse and keyboard, then pc froze so i hard reseted it by holding power button, also plugged monitors to my standard config secondary to IGPU with HDMI and main to GPU with DP and tested it once more and somehow that BUG dissapeared both screens wake normally. so no it wasn't cable it was probably some weird bug.

**Comment by MadArson1999** [comment]
@Vivek-Intel OK. i will close it now and if issue return at some point i will maybe reopen it.
