### ISSUE TITLE
Assassin's Creed: Odyssey texture and water flickering/artifacting and freezing

### ISSUE THREAD

**Issue by IntelArcTesting** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#715]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Assassin's Creed: Odyssey

### Processor / Processor Number [Required]

Ryzen 5 5600

### Graphic Card [Required]

Arc A750 and Arc A770

### GPU Driver Version [Required]

31.0.101.5330

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14323379/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Water is flickering and some other texture also. Makes it look like its artifacting. Video: https://www.youtube.com/watch?v=c7-JFmSC9bk

### Crash dumps [Required, if applicable]

[Save Files.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14323381/Save.Files.zip)

These are my save files (1 is for origins and 1 odyssey don't which is which so try both)

**Comment by Vivek-Intel** [comment]
@IntelArcTesting does black artifacts occur at the specific part of the game ? I have been trying to reproduce but could not see happening on different setups. Can you try disabling anti aliasing ?

**Comment by kunit1** [comment]
@Vivek-Intel Did you get a chance to use the attached save file in the original post?

**Comment by IntelArcTesting** [comment]
@Vivek-Intel as far as I could tell it happened anywhere and on multiple GPU’s. Was using the ultra settings preset with anti aliasing on, will try this weekend without

**Comment by Vivek-Intel** [comment]
hi @IntelArcTesting we can not commit to any time to get it fixed but here is internal bug id for tracking purpose - 18036250404

**Comment by BiZkViT96** [comment]
@IntelArcTesting This reminds me of the situation with the "Origins" game. When NVIDIA and Ubisoft were blaming each other for the graphics bugs. I personally trust NVIDIA's expertise more than UBISOFT. And if there is a problem with the game, as we all know, UBISOFT won't bother to fix it. And Intel has already said that it will not create special hacks for games, if it's the game's fault and not the driver. So, if this is the case, DXVK will be the only option.

https://wccftech.com/ubisoft-and-nvidia-blame-each-other-for-assassins-creed-origins-bug-present-in-rtx-builds/

**Comment by Vivek-Intel** [comment]
> @Vivek-Intel as far as I could tell it happened anywhere and on multiple GPU’s. Was using the ultra settings preset with anti aliasing on, will try this weekend without

Can you test with driver [101.5379](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) and check if issue is fixed.

**Comment by IntelArcTesting** [comment]
@Vivek-Intel latest driver fixed flickering for me
