### ISSUE TITLE
Lastest Intel Arc driver problem in F1 23 game

### ISSUE THREAD

**Issue by Kuba25x** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#717]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

F1® 23

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-10400F 

### Graphic Card [Required]

Intel Arc A750 8GB

### GPU Driver Version [Required]

31.0.101.5330

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel System Support Utility report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14345026/Intel.System.Support.Utility.report.txt)

### Description and steps to reproduce [Required]

Last time when I was playing F1 23 with driver version 1.0.101.5186 there were no problems and game was smooth. But today I updated Intel Arc driver version to 31.0.101.5330 and game started to have freezes. While playing a race game freezes about 1-3 times per lap for very short time resulting in unsmooth gameplay. Lowering the graphics did not change anything and game still freezes.

I am also attaching a benchamrk file with frame times:

[Benchmark_2024-02-20_at_14-47-12_frametimes.csv](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14345339/Benchmark_2024-02-20_at_14-47-12_frametimes.csv)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Gamma adjustment: 100
Motion blur strength: 20
Steering animation: On
Detail preset: Custom
Ray tracing quality: Medium
Ray-traced shadows: Off
Ray-traced reflections: Off
Ray-traced ambient occlusion: Off
Ray-traced transparent reflections: Off
Ray tracing DDGI: Off
Lighting quality: Ultra high
Post process: High
Shadows: Ultra high
Particles: High
Crowd: Ultra high
Mirrors: Ultra high
Car and helmet reflections: High
Weather effects: Ultra high
Ground cover: Ultra high
Trees: Ultra high
Skidmarks: High
Skidmarks blending: On
Ambient occlusion: HBAO+
Screen space reflections: Ultra high
Asynchronous compute: On
Texture streaming: Ultra high
Variable rate shading: Off
High quality hair: On

**Comment by Vivek-Intel** [comment]
Hi @Kuba25x I checked issue with latest driver but could not see any freeze moments or game stuck as you mentioned in the laps, not even in benchmark.
Can you once uninstall driver using DDU and try latest driver again ?

**Comment by Kuba25x** [comment]
Ok, I'll try that

**Comment by Kuba25x** [comment]
It seems like it solved the issue, the game stopped stuttering. Thank you for your help :)
