### ISSUE TITLE
Earth Defense Force: Iron Rain: random crashes on Iris XE graphics

### ISSUE THREAD

**Issue by IGCIT** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#72]
Submitter: Jesse Bryant
[ X] Device is not undervolted nor overclocked.
[ X] Device is using the latest drivers.
[ X] Game is not cracked, modded and use the latest patch.
Game Platform [Required]
[ X] Steam
[ ] Origin
[ ] Microsoft Store
[ ] GOG Galaxy
[ ] Ubisoft Connect
[ ] Battle.net
[ ] Epic Games
[ ] Bethesda.net
[ ] Other
Processor / Processor Number [Required]
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
GPU Driver Version [Required]
30.0.100.9667
Rendering API [Required]
[ ] Vulkan
[ ] OpenGL
[ x] DirectX12
[ x] DirectX11
[ ] DirectX10
[ ] DirectX9
Windows Build Number [Required]
[ ] Windows 10 21H1 (May 2021 Update)
[ x] Windows 10 20H2 (October 2020 Update)
[ ] Windows 10 20H1 (May 2020 Update)
[ ] Windows 10 19H2 (November 2019 Update)
[ ] Windows 10 19H1 (May 2019 Update)
Description and steps to reproduce [Required]
Go into the single player menu and leave the game running. Crash happens no matter which menu you go into or even if you go into a mission. Crash takes longer to happen when forcing the game to run in DX12 mode using the -d3d12 command in launch options but still happens regardless
Device / Platform [Optional][Recommended]
GPD WIN 3 1165G7
Game Settings [Optional][Recommended]
Any
Screenshot

**Comment by TreeChairRope** [comment]
Update: Same issue on 9805 drivers

**Comment by IGCIT** [comment]
game affected by OpenSSL SHA crash

see: [CPU specific bugs and workarounds - IGCIT Wiki](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/CPU-specific-bugs-and-workarounds)
