### ISSUE TITLE
Getting random DirectX Crashes in Final Fantasy XIV

### ISSUE THREAD

**Issue by Eaglef90** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#721]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Final Fantasy XIV

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

No platform used.

### Processor / Processor Number [Required]

Intel Core i9-13900K

### Graphic Card [Required]

Intel Arc A770 LE

### GPU Driver Version [Required]

31.0.101.5330

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14413810/ssu.txt)

### Description and steps to reproduce [Required]

When playing Final Fantasy XIV the game will randomly freeze up for a few seconds and then crash to the desktop with this error message:

![Screenshot 2024-02-19 183525](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/4780824/e02652b5-2102-4ffb-bf17-7f3d54823f92)

I do not have reproduction steps as it seems to happen randomly and I can go days with no issue but then have the game crash 4 or 5 times in a single hour. It does seem to happen when there is more strain on the GPU like if I streaming in Discord, in a very crowded area of the game, or have weather effects like rain.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![Screenshot 2024-02-26 221924](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/4780824/a74d8599-a58a-43ac-8415-5f55f39493b6)
![Screenshot 2024-02-26 221942](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/4780824/9735c8ec-f691-46e4-ac28-bd502b0fb2ac)
![Screenshot 2024-02-26 221953](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/4780824/ed4be7f8-54fa-4041-b6c3-0ba81c7b10b0)
![Screenshot 2024-02-26 222009](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/4780824/f555af6e-9e60-488b-b3bd-ff7fe30d3d55)
![Screenshot 2024-02-26 222042](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/4780824/b0d2dad0-3118-4d55-ab30-215ae6c53576)

### Device / Platform name

Desktop PC running Windows 11

**Comment by Eaglef90** [comment]
I would like to note that this is a very random crash I have been having since day 1 of owning my Arc card. Sometimes it will go days with no crash other times it could be crashing every few minutes till I give up and play something else. It has gotten much better over time with newer drivers. I don't have this problem in other games I play and I can't get it to do it in stress test programs. If wanted I could force the game to crash by overclocking the arc card for data collection.

**Comment by Arturo-Intel** [comment]
@Eaglef90 It seems to be an issue with the game itself.
https://forum.square-enix.com/ffxiv/search.php?searchid=131772704

In the official forum of ff14 there's a lot of users with different GPUs having this problem. 
Mostly when entering to a populate town (like Limsa) or specific raids.
Also, there is a lot of comments with possible fixes to this issue. From reinstalling everything to change some display configurations.

Note: I play a lot this game on my spare time, using an Arc 750 + 12gen Intel CPU, and I did not get this message at all.
Still going to play more to try to reproduce it :p

--r2

**Comment by Squall-Leonhart** [comment]
> @Eaglef90 It seems to be an issue with the game itself. https://forum.square-enix.com/ffxiv/search.php?searchid=131772704
> 
> In the official forum of ff14 there's a lot of users with different GPUs having this problem. Mostly when entering to a populate town (like Limsa) or specific raids. Also, there is a lot of comments with possible fixes to this issue. From reinstalling everything to change some display configurations.
> 
> Note: I play a lot this game on my spare time, using an Arc 750 + 12gen Intel CPU, and I did not get this message at all. Still going to play more to try to reproduce it :p
> 
> --r2

It is not an issue with the game, You can completely disregard the majority of reports on that forum as they are by people with Hardware or Driver issues, the FF forum is just not a place for providing system related tech support on an individual basis so the reports end up merged or closed with no reproduction.

**Comment by Eaglef90** [comment]
If it is a coming non-GPU issuer or an issue with my CPU why would the craft happen more often as I overclock the GPU? I know right before the game crashes I can hear load coil-whine from the GPU like it is going max power draw.

**Comment by Squall-Leonhart** [comment]
> or an issue with my CPU why would the craft happen more often as I overclock the GPU?

Everything that the GPU processes has been through the CPU and IMC before hand.

**Comment by Eaglef90** [comment]
So I found this https://www.radgametools.com/oodleintel.htm and they are talking about very different error messages and that if you have this problem you would see it in Visual Studio or Benchmarks. My system is 100% stable in benchmarks (even overclocking the GPU) and I have never had a Visual Studio crash on my system (though I do tend to be in VS and XIV at the same time, it is only SIV that crashes). I am redoing the OS on Monday and I will rest BIOS settings and use XTU for overlock and try there suggests in the doc as well but I don't think it will be fixing the problem. It only 14 that gives me problems with this and no other games or benchmarking programs, even when overclocking the GPU

**Comment by Squall-Leonhart** [comment]
the oodle article isn't 100% correct on that aspect of its writeup,  fringe stability bit errors don't always occur in critical code, and sporadic instability tends to be specific to particular cpu cores when pushed too far.  FFXIV only uses 4 cores worth of load, with the appearance of the other cores being loaded being a result of load balancing.

And burn in tests, always have untested outliers that realworld code can provoke simply by having more variable load(and voltage changes) and by less cores used allowing higher clock bins.

**Comment by Eaglef90** [comment]
The article does have steps, apparently from MSI, to deal with it so when I redo everything I will be testing that and we will see how it works out and I will report back later in the week.

**Comment by Arturo-Intel** [comment]
>It is not an issue with the game, You can completely disregard the majority of reports on that forum as they are by people with Hardware or Driver issues.

The FF forum is just not a place for providing system related tech support on an individual basis so the reports end up merged or closed with no reproduction, (And the userbase ranges from actually tech literate to people that call a system "HDD".

The FFXIV video engine is probably one of the saner, more stable multithreaded D3D11 renderers out there, so long as the hardware is - once you get into heavy cpu loading locations such as the City Hubs you can quite readily encounter stability issues if anything is just slightly out of whack.

I suspect the ops Intel Core i9-13900K here, as these are currently in the news for being unstable when using RAD/Oodle, which FFXIV does of late.

Just as a note, this game also throws DirectX errors when the Audio engine crashes, though they've recently moved to a hotplug capable Xaudio implementation it can still throw on audio device loss in the case of very particular headsets that can crash under BT communication saturation (and other conditions).

How do you explain then that this behavior is present on AMD(cpu, gpu) and NVIDIA as well? 

I understand that the ff14 forum is not a technical forum, the point of me mentioning that is that it not only happens on Intel cpu/gpus.

Adding that this behavior is quite random (we don't have step to reproduce it, just play the game until crashes) it is going to be a hard case to prove, and if I just create the internal case with only this data, it is going to be rejected.

**Comment by Arturo-Intel** [comment]
@Eaglef90 BTW, one of the most repeated answers in the forums and channels that I reviewed that "solve" the problem is to disable XMP on your system.

Could you try and let us know how it went?

**Comment by Eaglef90** [comment]
> @Eaglef90 BTW, one of the most repeated answers in the forums and channels that I reviewed that "solve" the problem is to disable XMP on your system.
> 
> Could you try and let us know how it went?

I never had XMP enabled, but I did have a custom RAM overclock. I have just finished rebuilding OS and have disabled both the custom overclock as well as CPU overclock. I work tonight but have the next two nights off and will be running different tests over the weekend and will report back finding.

**Comment by ChuckM-Intel** [comment]
1. Can you run a memory stress test program in Windows (and make sure it can run for hours without failing).  2. When you see the error, can you find the process in task manager and right click and select "create memory dump file" and post it for analysis?  3. Turn on user mode crash dumps (https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps) and see if the game creates one.  If it does, then post for analysis.

**Comment by Eaglef90** [comment]
Hi sorry, I completely forgot about this. I continued to experiance crashing after the rebuild even with no overclocks on RAM or CPU.

@ChuckM-Intel I was able to compleate 3 or 4 passes in MemTest86 with my RAM with no issues. 
I am in the middle of finals at school right now so I will not be able to test for a few weeks but once finals are over (May 4) I will try to get a crash dump for you

**Comment by Eaglef90** [comment]
So I was just taking a break after finishing on of my exams and was playing 14 to do a bit more furnishing of my house and it crashed. I was able to to the "create memory dump file" and it generated a 4.5GB file. Do you want it uploaded here or somewhere else?

Do you also need me to still turn on user mode crash dump and try to get one of them as well or is that the same as the thing I just made?

**Comment by Eaglef90** [comment]
> 1. Can you run a memory stress test program in Windows (and make sure it can run for hours without failing).  2. When you see the error, can you find the process in task manager and right click and select "create memory dump file" and post it for analysis?  3. Turn on user mode crash dumps (https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps) and see if the game creates one.  If it does, then post for analysis.

Can you let me know where to upload the giant crash dump file to?

**Comment by ChuckM-Intel** [comment]
> > 1. Can you run a memory stress test program in Windows (and make sure it can run for hours without failing).  2. When you see the error, can you find the process in task manager and right click and select "create memory dump file" and post it for analysis?  3. Turn on user mode crash dumps (https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps) and see if the game creates one.  If it does, then post for analysis.
> 
> Can you let me know where to upload the giant crash dump file to?

Try to compress it before upload with 7zip.  Can you share a link from Google Drive or OneDrive?

**Comment by Eaglef90** [comment]
@ChuckM-Intel 
I compressed it with max compress and you should be able to get it from

https://gameinfosites-my.sharepoint.com/:u:/g/personal/matthewv_ffinfo_com/ERLUzxaoSvVBlprBcFXhptYB3RLiYjfeOy_KXAqXCgOYDw?e=1s1KOL.

I also just updated to the latest bios for my MB and took the opportunity to remove 2 sticks of ram and run at stock MSI settings including no XMP profile enabled for the ram. So I am at 32GB 5400 DDR5 now. I ran the built in Windows 11 RAM test and it passed with no reported issues but about 20 minutes after that I got this error again.

**Comment by Eaglef90** [comment]
@ChuckM-Intel 

 Please let me know once you have gotten the dump file. I am in the process of shutting off my office (and thus my one drive) account but want to make sure you are able to get the file before I do that.

I have also been running memory tests. The tests take about 3 hours to run (15 passes of the Windows 11 memory tester set to standard) and so far no problems with 2 ram sticks by them selfs without XMP enabled.

**Comment by Arturo-Intel** [comment]
@Eaglef90 hey can you reshare your dump file? 
I was updating some data here and notice I dont have anymore that dump. 
The link looks dead.

thx 
-- r2

**Comment by Toetje585** [comment]
Last few days I see lots of complaints about crashing 13th, 14th Gen Intel CPU's.  Causing directx errors etc. I would ask all people to include there cpu. I have one friend on 13th gen intel cpu that also crashes in FFXIV.

**Comment by Eaglef90** [comment]
> @Eaglef90 hey can you reshare your dump file? I was updating some data here and notice I dont have anymore that dump. The link looks dead.
> 
> thx -- r2

As stated in my post from May 29 I was in the process of shutting off my office subscription and thus no longer have the dump file as I did not feel like having to pay Microsoft another year subscription to keep it around for you guys since there was no response.

I have seen other issues on my Windows machine start to crop up, which I am assuming is due to Intel's process side of the company borking their 13/14 gen CPUs. I run a 13900k so I am waiting for the microcode update and for them to announce dates on when the oxidation issues ran from. I may have to RMA my chip as it is probably already damaged but since I am watercooling and have lapped the CPU I am probably going to get screwed over, which means no more intel products in the feature for me.

**Comment by Eaglef90** [comment]
> Last few days I see lots of complaints about crashing 13th, 14th Gen Intel CPU's. Causing directx errors etc. I would ask all people to include there cpu. I have one friend on 13th gen intel cpu that also crashes in FFXIV.
> 
> Update:
> 
> Intel is coming with a microcode update to keep the voltages in check, please see the Intel Reddit.
> 
> Edit:
> 
> My friend experienced the same error as the original poster. Since it was happening frequently for him, I didn't try to reproduce it myself. Instead, I updated his motherboard BIOS, deployed a fresh Windows 11 image on his system drive using UUP Dump, and prepared a USB stick with the latest drivers. I created the USB stick using Rufus and predefined a user account so I could leave the system disconnected from the Internet during installations. This prevents Windows Update from searching for drivers.
> 
> So far, his system has been stable for the last three days, and the game has not crashed anymore.

I have updated the BIOS, removed all BIOS changes tand ran intel's lowest level settings, reinstalled windows mutiple times, and much much more. None of it has helped. The last time it crashed I did notice a quick spike in CPU temp so it might have to do with the mirocode volt issue they finally admitted to but at this point I am just now playing it on PS5 (which has better graphics then my arc card) and am no longer planning on buying a battlemage card. Depending on how Intel treats me if I have to replace my CPU I will probibily jsut find a cheep 12th gen to throw in the board and give the machine to my brother and then build an all AMD rig to replace it (myu first AMD rig ever, been Intel since the Pentium 2 days) and just leave intel alone for the next 20-30 years.

**Comment by Squall-Leonhart** [comment]
I'll be real with you Matthew, if you're already seeing issues the silicon will not be saved by the microcode update.

**Comment by Eaglef90** [comment]
> I'll be real with you Matthew, if you're already seeing issues the silicon will not be saved by the microcode update.

O I know but when I started to see those issues I decided to do a clean install of windows as there where some experimental things I had which may or may not have been causing issues as well. I finished a reinstall last week and have not see issues in my other software so I am hoping it was just the messing around I did causing the other problems but with FF14 being on PS5 I am not on my desktop as much anymore. The real test will come in September when I rebuild a website's front end code from scratch. If I see issues at that point I know the CPU is fubard and then we will see how much intel carse about it's consumers at that point.

**Comment by Eaglef90** [comment]
With Intel coming out and confirming the volt issue and now a fix coming soon I plan on doing more testing on this. I have seen some good indepth reporting on what to look for in my testing of the CPU and when MSI released a BIOS fix with microcode 0x129 for my z690 board I am going to apply that and play in the game with some detailed logging on my current CPU. If I don't see the volt spikes I know the microcode worked, if I don't see crashes then the CPU is not foobard. I was able to get a good deal on a 14900KS incase my 13900K is bad. After testing on the 13900k and being asured that it is ether bad or good I will be upgrading and testing again. After all this is done I will report back with results and if needed requests for next steps. This testing will probibily take like a month or so.

**Comment by Eaglef90** [comment]
MSI released a beta BIOS for my board to address the CPU problem so I am testing this out now. Basic testing is looking stable so far but I am not pusshing it to hard right now. I have been doing basic stuff in zones that where constant crashes before and am not having issues but when my weekend off from work comes up I plan on pushing it a lot harder to see what happens. Will report back in about a week or so after I can really burn the system in and update.

**Comment by Eaglef90** [comment]
And I spoke to soon. It just crashed on me again. Time to swap in the new CPU and see what happens. >.<

**Comment by Eaglef90** [comment]
Unfortunatly I can no longer work on debuggin this as my Arc card is fried and I don't have the money to spend on a new arc, excpecialy with Battlemage soon to be releaed (we hope). I am closing this out and when I get a new card, if it ends up being battlemage and the problem returns I will come back.
