### ISSUE TITLE
Call of Duty Games Shader Compilation issues

### ISSUE THREAD

**Issue by muzadull** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#723]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Call of Duty: Modern Warfare III 2023

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

8600K

### Graphic Card [Required]

ARC A770 LE 16GB

### GPU Driver Version [Required]

31.0.101.5333

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14435624/SSU.txt)

### Description and steps to reproduce [Required]

There is a shader compilation bug that occurs on COD MW3 Multiplayer when using any driver after 31.0.101.5085

Steps to reproduce the problem:

1: Delete all shader cache in the game directory (cod23 folder).

2: Launch the game and let shaders compile and then close the game.

3: Launch the game again, monitor the cpu usage. You won't be able to join any game (Timed out error). If you wait 5-10 mins the cpu usage goes back to normal and you can play the game normally.

It seems that the game is re validating the already compiled shaders. This happens every time you launch the game.

Similar issues on other Call of Duty Games:
https://community.intel.com/t5/Intel-ARC-Graphics/31-0-101-5234-driver-Warzone-2-chrash/m-p/1570268#M12168

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Quality Preset

**Comment by mujeeb-intel** [comment]
Hello @muzadull 

So, I tried giving this a shot and followed your steps.

1. downloaded from Steam
2. Launched the game
3. Let the shaders compiled to 100%
4. Closed the game
5. Went into steamapps ->common -> modenware folder -> cod32 -> and deleted all the cache.
6. Re-launched the game
7. wait until the shaders compiled all the way to 100% and then closed the game
8.  Re-launched the game and this time, no shaders needed to be compiled and the game ran just fine without any errors. 

Am i missing any step  here?

My system Specs:
13900K w/ A770
32gb ram
win 11
default settings for the game.
gfx driver: 101.4333

Video: https://youtu.be/RgeLAbz8HoA

Could you please take a look at my recording?

**Comment by muzadull** [comment]
Hello @mujeeb-intel 

Thanks for the reply. The video is private. The game runs for me too but with stutters as there is very high cpu usage for about 5-10mins when you launch the game. There is no error or pop up message that shaders are compiling and if you try to join a game when the cpu usage is high you get a timed out error. 
This happens on every driver after 31.0.101.5085.

**Comment by rmorera-intel** [comment]
hi @muzadull I updated the community thread as well but check this out:

This one is turning out to be quite tricky. Our dev team told me they have been unable to reproduce the issue in their systems.
I tested it on 3 different systems (same OS and driver 31.0.101.5333) and so far I only have the issue reproduced in one PC. Steps we are following:

1. Start Warzone.
2. Wait for the game to update the shaders.
3. Play 1 or 2 matches normally.
4. Close the game and reboot PC.
5. Start Warzone and select any kind of game (return, battle royale etc..), then start the match.

This is the moment we should see the game hanging during loading and eventually get the time-out error (until shaders are deleted and start at #2 again). 

I would appreciate if you can point out if there is any other step we can follow to have a more consistent issue repro.

**Comment by muzadull** [comment]
Hello @rmorera-intel  

I don't know any other steps to reproduce the error.
Why only one of the three pc has that bug?
Could it be something different on the pc having the issue?
On my system the game is not on the os drive but on another ssd and i am using steam.
There must be something that is triggering this issue.

**Comment by mujeeb-intel** [comment]
Hi @muzadull 

Please update your graphics driver to the version 101.5522 or newer by going here: https://www.intel.com/content/www/us/en/download/785597/823163/intel-arc-iris-xe-graphics-windows.html 

I was able to confirm that the latest driver fixes this issue.

**Comment by mujeeb-intel** [comment]
@IGCIT I was able to confirm from another user that the driver mentioned above fixes this issue. We can go ahead and close ticket.
