### ISSUE TITLE
Ori and the Blind Forest Definitive Edition intermittent black screen during play and big FPS regression

### ISSUE THREAD

**Issue by 0xDEADFED5** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#724]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Ori and the Blind Forest Definitive Edition

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD 7900X

### Graphic Card [Required]

Arc A770

### GPU Driver Version [Required]

31.0.101.5333

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14446444/igcit_ssu.txt)

### Description and steps to reproduce [Required]

play the game.  screen will occasionally go blank every few minutes while the game keeps running.  performance regression too, unplayable framerate with in game vsync on (@1920x1200)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1200

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

none

### Save game

AppData\Local\Ori and the Blind Forest DE

[saveFile0.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14446507/saveFile0.zip)

**Comment by Karen-Intel** [comment]
Hi @0xDEADFED5 thank you for your report!

I'll be verifying the behavior you just reported. I will be back soon with my findings, talk to you soon

Karen

**Comment by Karen-Intel** [comment]
Hey @0xDEADFED5 could you share a small evidence for me about the blackouts? I'd like to see your game settings too please

Ty

Karen

**Comment by 0xDEADFED5** [comment]
i'll share later today

**Comment by 0xDEADFED5** [comment]
i found the easiest way to repro is by opening map screen.  every time on the first try it should very briefly show map, then screen will blank for a moment and it will come back.

it actually doesn't show in the recording, the recording looks like the blank didn't happen.  it's changing modes or something on my monitor every once in a while, but only in this game and it didn't happen a couple driver versions ago.

i tried running Ori with Visual Studio Graphics Debugger (vs2022), but unfortunately it crashes under the debugger.  I can't use PIX to look at it because the game is x86.

attached is a screenshot of the options, which are incredibly sparse and pretty unhelpful, unfortunately.
![Clipboard 1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/39973293/1591487b-8e91-4bf7-ac4d-e16ec33aad7a)

**Comment by 0xDEADFED5** [comment]
i think i can confirm it's a driver issue.
i've now tested different driver versions to try to narrow it down further.

results:
4953 - pass
5074 - pass
5186 - fail

sometime between driver 5074 and 5186 this regression happened, performance was great before that.  if there's anything i can do to further narrow this down, plz let me know.

**Comment by Karen-Intel** [comment]
@0xDEADFED5 ty for this info. Also, would you kindly show me how it looks for you? You can record with your phone and temporarily upload to drive or any other service. I'm unable to repro those black screen glitches so would be great to see it. I will show you how it looks for me too of course :)

I'm trying the same resolution, VSync ON and an average of 175 FPS on an Intel System (13900k)
I will enable an AMD system for this, just make sure to send me the evidence please

Thanks

Karen

**Comment by 0xDEADFED5** [comment]
here's a video showing the screen blanking:

https://drive.google.com/file/d/1q56X5xAWiXBDonxGe2ljCyDemf0BBrrg/view?usp=sharing

it happens with HDR turned off in Windows 11 also (just obviously without the HDR overlay)

**Comment by Karen-Intel** [comment]
@0xDEADFED5 more questions from my end:
- Could you share what is your card's VBIOS version? 
  You can check it in ARC Control > Settings > System Info > GPU Info > IFWI (V-BIOS) Version
- Can you share your display's specs? Please include if you're using DP or HDMI

[Here are the results](https://www.youtube.com/watch?v=5XRp1mrNFkA) of mi initial testing in my 13900k System and no black flashing at all when I open the map so we'll try to repro with your display's specs instead of the AMD system (if necessary we'll set up a system for this) 
Looks like HDR is forcing to change to ON whenever you open the map but that doesn't happen in my system (which is curious). I'm using an OLED Samsung G8 Display - Adaptive Sync ON

About the FPS performance, we're expecting changes for DX11 based games in future releases so let's pause that a little bit until these changes are implemented. For the time being, let's focus on the flashes you're seeing.

Keep me posted! Thanks

Karen

**Comment by 0xDEADFED5** [comment]
IFWI: 20.0.1063

monitor: https://www.asus.com/us/displays-desktops/monitors/proart/proart-display-pa248cnv/
connected via DP

i'll try troubleshooting a bit more

**Comment by Karen-Intel** [comment]
Hi @0xDEADFED5 have you tried to upgrade your drivers with HDMI plugged on?

Based on your SSU, you have an Intel Branded Card A770 LE (like the one I have). 
If you do, the latest vBios available version is 20.0.1068
If you see the instructions when you upgrade your driver, it has to be done with HDMI plugged on.
Can you attempt to do this? 
Looks like you're not in the latest vBios version and that might be causing some of the issues you have

Keep me posted! TY

Karen

**Comment by 0xDEADFED5** [comment]
oops, not sure how i missed the HDMI notice in the installer, thank you.  i'm on just HDMI now.

however, i can't get the vbios to update from 20.0.1063.  i tried a repair install of 5333 + reboot, then a force downgrade + reboot + 5333 upgrade + reboot, vbios never changed.

**Comment by 0xDEADFED5** [comment]
at this point even IF it's a bug, it's pretty minor one (to me), with an easy workaround, i should've known it was adaptive sync acting up.  thanks for the great support!
