### ISSUE TITLE
Wargame Red Dragon graphical autosetting crash

### ISSUE THREAD

**Issue by movp0acc** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#725]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Wargame Red Dragon

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

R7 5700X

### Graphic Card [Required]

Arc A770 16GB

### GPU Driver Version [Required]

31.0.101.5333

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14468550/igcit_ssu.txt)

### Description and steps to reproduce [Required]

1. start game
2. click options
3. video options
4. set 4k windowed
5. click "AutoSet" for auto graphical setting. The game will crash halfway through its graphical test run.

![wargame_crash](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/22866846/330a3ce2-f5d4-47d6-b7c7-c4adee0bc7ec)

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

3840x2160

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

autoset graphical option crash

**Comment by mujeeb-intel** [comment]
Hey @movp0acc just tested this on the latest graphics driver. I did not see any crash. I did test it on 1440p and 1080 but not the 4k. 

Can you also confirm if you still see an issue with this game?

**Comment by mujeeb-intel** [comment]
Hey, let me know if you can also test the game on your system. So far no crashing is observed when using graphical auto setting.

**Comment by mujeeb-intel** [comment]
I will go ahead and close the ticket as Im unable to reproduce the issue. Feel free to refer back to this ticket.

Thanks!
