### ISSUE TITLE
Settings Reset on Tom Clancy's Rainbow Six Siege whenever booting up the game and every time a new match starts, requiring that it be reset for every single match

### ISSUE THREAD

**Issue by Tealdragon204** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#729]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Tom Clancy's Rainbow Six Siege

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [X] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

R9 5900X

### Graphic Card [Required]

Arc A750 Limited Edition

### GPU Driver Version [Required]

31.0.101.5333

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel System Support Info.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14551631/Intel.System.Support.Info.txt)

### Description and steps to reproduce [Required]

Everytime I boot into the game my settings reset to the default. Likewise whenever queueing into a match they reset to the default (But it does not show they have reset but they have) this is especially noticeable because bloom is enabled even though bloom is off in the settings. Likewise TAA-4X is on instead of no anti-aliasing which is very obvious because the game looks like a smeary mess instead of sharp

Likewise, changing the texture settings does not change anything and the textures are stuck on the lowest setting. 

Very frustrating as every time I boot up the game and every time I start a new match I have to disable and re-enable my settings to get it back to where it was

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Texture Quality: Ultra (not working)
Anisotropic 16x
LOD Quality: Ultra
Shading Quality: High
Shadow Quality: Very high
Reflection Quality: High
VFX Quality: Ultra
Ambient Occlusion: SSBC+ 
Lens Effects: Off
Zoom-In Depth of Field: Off
All Upscaling options: Off
Adaptive Render Scaling: Off
Anti-Aliasing: Off

Monitor: VG27AQL1A
Resolution: 2560x1440
Refresh Rate: 170 Hz
Display Mode: Borderless (also happens in fullscreen)
VSync: Off
FPS Limit: Off
Widescreen Letterbox: Off
Field of View: 90
HUD Display Area: 100
Menu Display Area: 100

**Comment by Tealdragon204** [comment]
Didn't occur at all today and I have no clue why. As I restarted my PC the prior day as well

**Comment by rmorera-intel** [comment]
Hi @Tealdragon204 has this occurred again? I'll try replicating this issue on my test system here and let you know what I can find.
I guess you could also verify game files, try safe mode and worst-case scenario reinstall the game - but first give me a day to get back to you with my results.

**Comment by Tealdragon204** [comment]
> Hi @Tealdragon204 has this occurred again? I'll try replicating this issue on my test system here and let you know what I can find. I guess you could also verify game files, try safe mode and worst-case scenario reinstall the game - but first give me a day to get back to you with my results.

It has occurred again. Already tried verifying the game files but it notably _only_ occurs when I switch steam/ubisoft accounts. I am wondering if it is something related to saving and reading .ini files as it seems if I do a fresh restart and stay on the account it's fine. But if I switch Steam + Ubi accounts to play on a different account on Siege the error occurs. I am not 100% sure on this as I haven't done rigid testing, I've just noticed the error occurred the last two times I switched accounts and hasn't occurred on times I haven't switched. I will have to test more

For clarification: It is two different steam + ubisoft accounts on the same Windows Account. (My personal alt accounts for Siege). To actually be able to switch accounts properly one must first close Siege, then close Ubisoft connect, then switch accounts on Steam, boot up Siege (thus rebooting Ubisoft connecting and booting you into the new account). If you forget the close Ubisoft connect. It will not change accounts on Siege

**Comment by Tealdragon204** [comment]
So I just did a fresh reboot without changing accounts and the

**Comment by Tealdragon204** [comment]
Now I am unable to replicate it. Perhaps it was fixed by a recent patch. I'll leave this open if it occurs again but I'm not seeing anything at the moment

**Comment by Tealdragon204** [comment]
Even after doing all sorts of jank things that I do with my computer, monitor setup etc... it has not occurred again so I will be closing this
