### ISSUE TITLE
[Third party report] Twitch Studio Vulkan Layer is crashing any Vulkan game [Confirmed to be Twitch upstream issue, opened for documentation sake]

### ISSUE THREAD

**Issue by Squall-Leonhart** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#730]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

RDR2, Cemu, Doom Eternal

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [X] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

N/A

### Graphic Card [Required]

Iris Xe, Arc Xe, Arc 750, Arc 770

### GPU Driver Version [Required]

31.0.101.5333

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [X] Windows 11 22H2
- [X] Windows 11 21H2
- [X] Windows 10 22H2
- [X] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

This is an issue made for archival purposes based on the forum contents of https://community.intel.com/t5/Graphics/Vulkan-apps-fail-to-launch-with-Iris-Xe-while-Twitch-Studio-is/m-p/1578520

Twitch are responsible for this issue, however Nvidia has managed some kind of workaround that might be explored,  Twitch has been notified on social media.

Creating this issue so that it can be referred to if anyone else opens a Twitch related issue with Vulkan

### Description and steps to reproduce [Required]

Install Twitch Studio on an admin account (Standard account with Elevation does not install the Twitch Layer)
Run Doom Eternal (chose not to disable the layer)
Run RDR2 (will 0x0C00005 on start)
Start a game(homebrew works) in Cemu (Will Vulkan error -4 in log)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

Resolution not applicable

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Settings aren't relevant, the loader crashes.

### Device / Platform name

PC/Windows

**Comment by Squall-Leonhart** [comment]
Twitch has been notified via social media, perhaps Intel has devrel they can bump internal at Twitch?

**Comment by Felipe-Intel** [comment]
hello @Squall-Leonhart 
Issue has been reproduced internally and we reported it to our dev teams. We will try to reach out to Twitch and see what can we do about it on our side. I'll provide an update as soon as I have one.

**Comment by Felipe-Intel** [comment]
@Squall-Leonhart we were informed that Twitch Studio app support was discontinued last March. Twitch Interactive, Inc is asking their users to switch to another streaming app. You can find more details in this link: 

[Recommended Software for Broadcasting](https://help.twitch.tv/s/article/recommended-software-for-broadcasting?language=en_US )

I wanted to ask you to check if this issue (i.e. crashing vulkan games) still happens with your choice of one of this other apps. If so, please create a new ticket with the details. I made a quick test with OBS and Doom1+Doom2 (Steam) and game launches and play ok. 

Just a note, there is an ongoing investigation about OBS (30.x) failing to capture vulkan apps, so you won't see any video if you try to stream any of the reported game titles in this ticket. Audio should work fine.

I will proceed to close this ticket.
