### ISSUE TITLE
Acer Predator Bifrost ARC A770 fan speed issue

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#733]
### Application [Required]

Windows desktop

### Processor / Processor Number [Required]

intel Core i7-13700KF

### Graphic Card [Required]

intel Arc A770 (Acer Bifrost variant)

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [X] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Using HWiNFO utility, I have gathered the information that when the GPU is idle. the cooler fan on Acer Bifrost A770 runs at 1150 RPM (10-minute average) with "Automatic" selected for the "Fan Speed Control" in the Performance Tuning in Arc Control, and it runs at 1400 RPM (10-minute average) with user customized "Fan Curve" set at 30% PWM (the lowest possible value allowed in the current version of Arc Control).

*Feature request: make it possible for user to customize the fan curve to behave like the "Automatic" profile when GPU is idle. This is very needed because for this particular model the fans running at 1400 RPM is much louder than 1150 RPM. Since its cooler fans can operate at 1150 RPM without any issue, it should be reasonabe and feasible for the customizable fan curve to begin with as low as this speed.

**Comment by Susie1818** [comment]
@abrfilho
@fjamesprice
@Karen-Intel
@vitduck

I hope intel don't evade this issue. Please help.

**Comment by fjamesprice** [comment]
> @abrfilho @fjamesprice @Karen-Intel @vitduck
> 
> I hope intel doesn't evade this issue. Please help.

Thank you for making this thread.  On a good day this card makes it sound like I live by the seaside.  It would be nice to have more control over the fan curve.

**Comment by DealsBeam** [comment]
Perhaps try using these free & open-source tools

https://github.com/lich426/FanCtrl and https://github.com/Rem0o/FanControl.Releases

**Comment by fjamesprice** [comment]
> Perhaps try using these free & open-source tools
> 
> https://github.com/lich426/FanCtrl and https://github.com/Rem0o/FanControl.Releases

These apparently do not detect the fans on the Acer BiFrost card.

**Comment by Gabriela-Intel** [comment]
Hi Susie. The issue you mentioned has already been discussed [here](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/430). I know our response to this issue wasn't ideal for you or other users impacted by it but our stance on this remains the same for the aforementioned reasons explained in the comments of that thread.

As for your feature request, we will definitely take your feedback into consideration and file it for the team to review and discuss. We do really appreciate you taking all this time to give us feedback to improve. 

Thanks for your understanding :)

**Comment by Susie1818** [comment]
@abrfilho
@fjamesprice
@vitduck

Hey guys, I just retested the fan behavior with the latest driver v5333 and Arc Control v1.75.5430.1 and firmware v20.0.1068. It seems to work now. Can you help try and see if it works for you as well?

My fan curve settings:
![Screenshot (18)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/124469949/bb143b64-4fd6-4ece-b973-f127750abea9)

The fan speed can achieve equilibrium at ~1000 RPM while GPU core temp stays at 35°C, and it doesn't fluctuate down to 0 RPM.

**Comment by fjamesprice** [comment]
Susie, I don't know how you're getting 1,000RPM at 35 degrees.  I have the same version driver, arc control, and firmware, but after copying all of your settings, my fans are spinning at a distracting 1320-1440 RPM.  Temperature is 42 C while ambient temperature isn't above 20 C.  
![2024-03-15 10_47_59-ArcControl](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/134095787/10e8ad0f-d367-4aed-a648-12736ae107aa)

**Comment by Susie1818** [comment]
@fjamesprice 

Does your ARC has sufficient fresh air-flow? I use Fractal Design Torrent Compact case with a 180mm fan delivering cool air for my ARC.

**Comment by Susie1818** [comment]
@fjamesprice 

Or maybe you can try shifting right a temperature node - 0% for 40°C and 30% for 55°C, and see what happens.

**Comment by fjamesprice** [comment]
> @fjamesprice
> 
> Does your ARC has sufficient fresh air-flow? I use Fractal Design Torrent Compact case with a 180mm fan delivering cool air for my ARC.

It does.  My case is a Lian Li Lancool III, close in performance to the full size Torrent last time I checked.  Three 140mm fans in the front, one in the back. 



> @fjamesprice
> 
> Or maybe you can try shifting right a temperature node - 0% for 40°C and 30% for 55°C, and see what happens. The most important thing is to see whether the fan speed would ramp up and down to 0 RPM.

This is how I usually have the fan curve set, which causes the fan to jump between 0 and ~1,500 RPM.

With every fan in the system set to 100%, which is very loud, I can achieve 35 C.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/134095787/b5d15cd4-e329-4490-baff-549e528fe60c)

I hope your card continues to behave the way it does now.  I'm starting to think mine has something uniquely wrong with it.

**Comment by Susie1818** [comment]
@fjamesprice 

It is indeed quite strange that your GPU core idle temperature is 42°C when the fan speed is 1400 RPM. I guess there is something wrong with the thermal paste or the heatsink contact pressure on the GPU die.

But what if you use the "Automatic" option? I think the fan would not keep ramping down to 0 RPM with this mode. In my case, if I use the "Automatic" mode, idle fan speed is 1150 RPM and idle temperature is roughly the same.

**Comment by fjamesprice** [comment]
With Automatic enabled, my fan speed fluctuates between 1,140 and 1,300, with an idle temp around 42.  The fan has a constant, noticeable whine with this setting, the most prominent harmonic bouncing between 270Hz and 278Hz.

**Comment by Susie1818** [comment]
@abrfilho
@fjamesprice
@vitduck

Hi guys, I would like to share with you some more findings with the latest driver/Arc_Control/VBIOS.

As I cold booted my PC this morning with my room temperature around 25°C, my ARC's fan was ramping up and down (to 0 RPM) as the core temperature was rising from room temperature. It kept ramping up and down until the core temperature reached 35°C and then it stablized itself, which took about 2-3 minutes. As my fan curve settings are 0% for 25°C and 30% for 40°C, simple arithmetic gives 20% at 35°C. So, I guess the latest firmware has been made to be able to handle 20% (and above) fan speed correctly, but not 19% or below. (20% fan speed translates to ~1000 RPM)

In my opinion, the best solution right now is to make the fan speed threshold line as low as 20% instead of 30% in the Arc Control UI so that we can start the fan curve with a flat line at 20% from 25°C to either 55°C or 70°C.

**Comment by abrfilho** [comment]
> @abrfilho @fjamesprice @vitduck
> 
> Hi guys, I would like to share with you some more findings with the latest driver/Arc_Control/VBIOS.
> 
> As I cold booted my PC this morning with my room temperature around 25°C, my ARC's fan was ramping up and down (to 0 RPM) as the core temperature was rising from room temperature. It kept ramping up and down until the core temperature reached 35°C and then it stablized itself, which took about 2 minutes. As my fan curve settings are 0% for 25°C and 30% for 40°C, simple arithmetic gives 20% at 35°C. So, I guess the latest firmware has been made to be able to handle 20% (and above) fan speed correctly, but not 19% or below. (20% fan speed translates to ~1000 RPM)
> 
> In my opinion, the best solution right now is to make the fan speed threshold line as low as 20% instead of 30% in the Arc Control UI so that we can start the fan curve with a flat line at 20% from 25°C to either 55°C or 70°C.

Today is hot (33C outside) and there's no wind, my case is small and my GPU is idling now at 47C.
I imported the fan curve from Acer Predator Bifrost app, there's one hour that it's running with the fan curve and so far so good, it's below 1300RPM and didn't went to 0 RPM, average RPM here is 1090.

I'll other day with my AC on and see if the fan behaves the same when the GPU is colder.

**Comment by Susie1818** [comment]
@Gabriela-Intel 

> our stance on this remains the same for the aforementioned reasons explained in the comments of that thread.

The "aforementioned reasons explained in the comments of that thread" were just totally non-sense.

I myself have bought an "intel Arc A750 Limited Edition" recently, and with the same fan curve settings I mentioned above - 0% for 25°C and 30% for 40°C - it allows fan to operate to the extent as low as 2% (@26°C) without any problem. You let your own manufactured product to work but destroyed other vendors' AIB models. Is this the righteous manners to treat those AIB vendors who are helping intel to promote your first generation ARC?

I bought my Acer Predator BiFrost A770 in December 2022. Back in the days when I was using an early driver version 4090, I managed to have the GPU fans running at as low as 500 RPM without any problem (the Arc Control at that time didn't restrict the fan speed PWM percentage below 30% and it was allowed set anywhere between 0% and 100%). If you ask my opinion, I would say intel has ruined my user experience (regrarding the GPU fan speed) with stupid firmware as well as Arc Control updates. The very problem here was actually introduced by intel's driver updates, and then intel said they "insist they don't want to fix it." I just really don't get it. What's the problem with you?

Why don't you simply learn from well-established motherboard and GPU fan control logic from other companies such as ASUS, Gigabyte, etc.? From all motherboard BIOS you can see they start fan control at 20% PWM, not 30%.

You should also learn from well-established fan control software logic from popular apps such as MSI Afterburner. When you design the feature of "0 RPM mode", you should not let the fan curve to climb from 0% to 20% (or descend from 20% to 0%) on a slope. Instead, you should let it jump from 0% to 20% (or from 20% to 0%) directly with a vertical cliff.

There have been so many well-established examples out there for you to follow already. I don't understand why intel can't make such simple things right.

**Comment by Susie1818** [comment]
It has been a little bit cold for the past few days, and I couldn't get my BiFrost A770 to warm up to 35°C when it's idle. It's just floating around 33-34°C, so the fan curve couldn't work anymore and I just had to use the "Automatic" mode otherwise it would have haunted me with the ramping-up-and-down syndrome.

Kind of sad. It's good that GPU temperature is cool, but it's just not so cool if it has to act like a dumb psycho.

**Comment by Susie1818** [comment]
@Gabriela-Intel 
@Karen-Intel

Recently some people are reporting the same [fan speed issue with their SPARKLE ARC GPUs](https://www.reddit.com/r/IntelArc/comments/1br6zh1/sparkle_a770_constant_fan_ramping/). Someone mentioned the fan doesn't stablize below 33% PWM, which is exactly the symptom that the [Acer BiFrost had with driver (firmware) v4644](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/430). So the SPARKLE varient has not even received the driver (firmware) v4824 treatment yet. It has been more than 6 months since v4824! You guys at intel should do something, okay?

**Comment by vitduck** [comment]
@Susie1818 

If you still have the Bifrost, could you try setting the fan curve with  [Argus Monitor](https://www.argusmonitor.com/history.php?language=en) ? I no longer have the card. 

I have been using Argus to control the case fans, and they released an update for Intel GPUs: 

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/575950/7e498dd5-4976-4e12-b1a9-b96136f58ed5)

**Comment by abrfilho** [comment]
> @Susie1818
> 
> If you still have the Bifrost, could you try setting the fan curve with [Argus Monitor](https://www.argusmonitor.com/history.php?language=en) ? I no longer have the card.
> 
> I have been using Argus to control the case fans, and they released an update for Intel GPUs:
> 
> ![image](https://private-user-images.githubusercontent.com/575950/320332223-7e498dd5-4976-4e12-b1a9-b96136f58ed5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MTcyMjYsIm5iZiI6MTcxMjYxNjkyNiwicGF0aCI6Ii81NzU5NTAvMzIwMzMyMjIzLTdlNDk4ZGQ1LTQ5NzYtNGUxMi1iMWE5LWI5NjEzNmY1OGVkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQyMjU1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGYxYmY3NjY2ZDM2YWUxOTBiZTM1NmFlYzcwOTMyZGU3YWNjMzFkZjA0ZTU2YjE3Y2JkZWZhMTIzOWNmZjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0HGiWSNz5JeEHYv0H39otf8KhnORGN_J4W3NTJybP2A)

Hello, I tested here and the program works, you can put the fan curve below 30% without a problem, just need to keep an eye to see which value will maintain the fan ABOVE 1000RPM, if the goes below, the fan will go to 0RPM and ramp up, here it's stable above 23%.
The sad part is that Argus Monitor is paid... A plugin for Fan Control is under development.

**Comment by Susie1818** [comment]
@vitduck 
@abrfilho 

Thank you for supporting the follow-up on this issue.

I have tried this Argus Monitor app. On my BiFrost A770 the fan can run stable at 21% and above. The ramping down to 0 RPM symptom begins at 20%.

Agreed with @abrfilho that the problem is that It is a paid software. Hopefully intel will fix this problem with the firmware and Arc Control.

**Comment by Gabriela-Intel** [comment]
@Susie1818 just wanted to remind you that we did forward your request. We'll proceed to close this out.

@IGCIT

**Comment by vitduck** [comment]
@abrfilho @Susie1818 
I am glad that the solution at least works out for you. 
If Argus can override the ham-fisted 30% limit imposed by Intel, I am sure Fan Control can do the same. 
It is unfortunate that MSI Afterburner has ruled out the possibility of Arc support. Otherwise, it will render Arc Control obsolete. 

I understand your reservation against paid software. 
But unlike the greedy practice of OCCT or SignalRGB, Argus offers a _maintenance_ license model. 
Once the license expired, you can keep using the last-updated version.  
And renewing is only required should you want to use functionalities introduced in newer versions.
