### ISSUE TITLE
PAGE_FAULT_IN_NON_PAGED_AREA while playing THE FINALS

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#734]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

THE FINALS

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

31.0.101.5333

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 12.03.2024.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14571249/Intel.SSU.12.03.2024.txt)

### Description and steps to reproduce [Required]

I was playing THE FINALS, and in-game, while I was doing nothing specific, I got this BSOD
I tried looking to the Event Viewer for a crashdump, couldn't find it. Same for the Diagnostic Data Viewer.
The BSOD was very quick, just lasted for like 0.5 seconds
I could take a quick look that the error was PAGE_FAULT_IN_NON_PAGED_AREA, and as always with Intel graphics, the erroring file is igdkmd64.sys

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Max + Max ray tracing, XeSS Quality

### Device / Platform name

ASUS PRIME Z790-P WiFi D4

### Crash dumps [Required, if applicable]

All I could obtain from the Event Viewer : 
https://drive.google.com/drive/folders/1kxY68KZTCvEIFsPVXrq1Qb5H9VFG7ld1?usp=sharing
(GitHub doesn't support .evtx files)
This .evtx file only contains logs from after the crash. I couldn't find logs during the crash in the Event Viewer. Normally, you can select English for the .evtx so that you don't have to translate from French
Tell me if I could look anywhere else to find other logs

**Comment by rmorera-intel** [comment]
Hi @TheWonderfulTartiflette I'll go ahead and try replicating the issue. 
Once I have news I'll let you know here.

**Comment by TheWonderfulTartiflette** [comment]
Hello @rmorera-intel, I'm not sure you'll fully be able to replicate this, as it's not linked to a specific action like opening the menu or pressing a button, it just happened in game, while playing normally

**Comment by rmorera-intel** [comment]
Hi @TheWonderfulTartiflette I can confirmed that so far I haven't got any BSOD when playing The Finals.. I'm on driver 101.5333 on an Intel A770 LE card + Windows 11 23H2.
Have you seen any other BSOD? 
I checked the event log you shared and find interesting that windows couldn't create the dump file - check the steps for "Crashing/freezing issues/BSOD" in [this link ](https://community.intel.com/t5/Intel-ARC-Graphics/Need-help-Reporting-a-bug-or-issue-with-Arc-GPU-PLEASE-READ-THIS/m-p/1494429#M5057)for additional instructions you can follow to enable dumps.

**Comment by TheWonderfulTartiflette** [comment]
No, I haven't seen any other BSOD
The thing is that I had this BSOD only once in like 100 hours of gameplay. Sure, I'll change the registry according to the Intel post, but it's very likely that I won't get anymore BSOD for a long time

**Comment by rmorera-intel** [comment]
That sounds like greats news! Let me close this then and if you ever get another one let me know here.
