### ISSUE TITLE
raytracing in halo infinite looks glitchy

### ISSUE THREAD

**Issue by awadeuwu7u7** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#735]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Halo Infinite

### Game Platform [Required]

- [ ] Steam
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

intel core i5 11400

### Graphic Card [Required]

intel arc a750 limited edition

### GPU Driver Version [Required]

31.0.101.5333

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14572531/report.txt)

### Description and steps to reproduce [Required]

When turning on all ray tracing settings it looks like noise on the walls, turning it off eliminates the issue
[raytracing bug](https://youtu.be/w7d4a43LI3A?si=FRHDsOWkTg7p6TLY)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1980x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![imagen](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/163139715/0827b1e2-a8e8-4ec4-bb8c-5ed099498c94)

**Comment by Vivek-Intel** [comment]
@awadeuwu7u7 are you observing this issue in latest drivers only ? did you see same on old drivers as well ?

**Comment by awadeuwu7u7** [comment]
I had the problem with the previous driver too, which prompted me to update them to see if that fixed it

**Comment by Vivek-Intel** [comment]
Hi @awadeuwu7u7 can you check [101.5379 ](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)and see if issue is fixed.

**Comment by awadeuwu7u7** [comment]
> Hi @awadeuwu7u7 can you check [101.5379 ](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)and see if issue is fixed.

Hi.
IT works allright now! thanks
![infinte fix](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/163139715/7c30e8f0-0b37-4b73-a9f2-7777c4b735a7)
