### ISSUE TITLE
3DMark "API Overhead feature test" - Vulkan part doesn't run

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#736]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

3DMark

### Processor / Processor Number [Required]

intel Core i7-13700KF

### Graphic Card [Required]

intel Arc A770

### GPU Driver Version [Required]

31.0.101.5333

### Other GPU Driver version

31.0.101.5186, 31.0.101.5081

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU_20240313.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14579084/SSU_20240313.txt)

### Description and steps to reproduce [Required]

Something wrong with the Vulkan part of the driver v5333.

Vulkan games (eg. Doom 2016, Red Dead Redemption 2) and benchmarks (eg. 3DMark Solar Bay, Wild Life) are still running fine without problems, but when running 3DMark "API Overhead feature test", the Vulkan part simply ends without even starting and without any error message, either.

I have tried rolling back to driver version 5081 and 5186, and both run okay without this problem.

A small thing worth mentioning is that while DX12 driver efficiency has been greatly improved from driver v5081 (v5081: 14.0M draw calls per second; v5186 & v5333: 16.5M =~18% uplift), the Vulkan driver efficiency seems to be getting noticeably worse (v5081: 10.5M; v5186: 9.7M =~8% decrease). Hopefully when addressing the issue you guys also take care of the driver efficiency.

**Comment by Vivek-Intel** [comment]
Hi @Susie1818 Can you share which version of 3Dmark are you using, I see this feature test is not supported anymore as per [3dmark developer support](https://support.benchmarks.ul.com/support/solutions/articles/44002142683-api-overhead-feature-test-unsupported-).

**Comment by Susie1818** [comment]
@Vivek-Intel

I am simply using the 3DMark purchased on Valve Steam. As I just checked, each single test module has its own version number. The "API Overhead" is of version 2.0.

I think the problem here has nothing to do with whether it is supported by the 3DMark developers or not. First of all, this feature test is particular useful and meaningful for ARC GPU as your first generation product which particularly needs software (driver) polishing. Secondly, it did run with previous versions of ARC driver. It also runs on my Nvidia GPUs without any issue. It's simply something wrong with the latest driver v5333, and I think the ARC driver engineers should be notified of the bug even if they don't want to debug this one.

**Comment by Vivek-Intel** [comment]
@Susie1818 will proceed this case and let you know if there is any news on the issue

**Comment by Vivek-Intel** [comment]
Internal bug id escalated - 16023579419

**Comment by ewahl-osc** [comment]
This problem only showed up in the  5333 release. (still an issue in 5379)   This WAS working previously.  
And with Renderdoc still crashing on ARC, can't debug it.  ;)

**Comment by Dawidusergit** [comment]
Still the same problem on 5382 driver.

**Comment by Vivek-Intel** [comment]
@Dawidusergit @ewahl-osc we are still working on this issue, will let you know once there is update on this one.

**Comment by Vivek-Intel** [comment]
good news is API Overhead feature test crash issue is fixed with internal driver but still might take some time before fix is included in the public driver.

**Comment by Vivek-Intel** [comment]
@Susie1818 please help verify issue with latest driver 101.5590

**Comment by Susie1818** [comment]
@Vivek-Intel I have confirmed the problem is fixed with v5590. Thanks!

Some disappointments, though - compared with driver v5081, driver efficiency has noticeably dropped, except DX12:
DX11MT -9%
DX11ST -12%
DX12 +21%
Vulkan -5%

**Comment by Vivek-Intel** [comment]
Thanks @Susie1818 for verification, please help close this thread.
You can open a new issue with required details if you see there is performance regression in latest drivers.
