### ISSUE TITLE
shader bug in the Warface game:Clutch (for the Europe region) or regular Warface (for the Russian region)

### ISSUE THREAD

**Issue by Pashamolochko** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#738]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Warface:Clutch or Warface

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

Steam

### Processor / Processor Number [Required]

i5 14600k

### Graphic Card [Required]

intel arc a770

### GPU Driver Version [Required]

31.0.101.5333

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

![2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/4f3a0865-6ef3-4c32-af63-158932ead7a2)
![1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/86139144-3cf9-4aaf-bc19-c3808d225bce)

### Description and steps to reproduce [Required]

In these games based on the same engine, there is a rather significant problem that prevents you from playing comfortably, this is a shader bug, and it happens when they are turned off (the quality is low in the game) after 2-5 games, the brightness in the game drops by 20-40%, but when you set the shaders to medium or high, this does not happen,for clarity, I will attach screenshots to compare
![2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/61d5bbb1-f21a-40cb-a075-0c4fd4f1725a)
![1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/ac07151d-e417-4481-b7ae-76b3bc08d33b)

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920-1080,2560-1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![настройки](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/892f150d-73fa-466f-95eb-4d5dff001a93)

**Comment by Pashamolochko** [comment]
I also want to add, when a bug occurs, it helps to turn on and off full-screen mode several times

**Comment by Ilya-intel** [comment]
Hi @Pashamolochko ,
I've replicated this behavior on my system. So I'll collect logs and pass it to the dev team.
I'll post updates here.

**Comment by Pashamolochko** [comment]
> Привет@Pashamolochko, я воспроизвел это поведение в своей системе. Итак, я соберу логи и передам их команде разработчиков. Я буду публиковать обновления здесь.



> Hi @Pashamolochko , I've replicated this behavior on my system. So I'll collect logs and pass it to the dev team. I'll post updates here.

thank you

**Comment by Pashamolochko** [comment]
thank you

**Comment by Pashamolochko** [comment]
Hi, I would like to know how the shader error correction is progressing?enough time has passed, and by the release note of the new driver, this bug is not on the list of known problems, why?

**Comment by Pashamolochko** [comment]
> Привет@Pashamolochko, Я воспроизвел это поведение в своей системе. Поэтому я соберу логи и передам их команде разработчиков. Я буду публиковать обновления здесь.

Hi, I would like to know how the shader error correction is progressing?enough time has passed, and by the release note of the new driver, this bug is not on the list of known problems, why?

**Comment by Ilya-intel** [comment]
Hi @Pashamolochko ,
This fix is still work in progress, no exact time for the release day, but I'll let you know when it is live.

**Comment by Ilya-intel** [comment]
Hey @Pashamolochko ,
We've released a big fix for DX11 games, and this game is also included.
I've tested it a little and it looks like there are no more brightness drops.
Could you install [101.6127](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) driver and check the game?

BR, Ilya.

**Comment by Pashamolochko** [comment]
> Привет@Pashamolochko, Мы выпустили большое исправление для игр DX11, и эта игра также включена. Я немного протестировал его, и похоже, что больше нет падений яркости. Не могли бы вы установить драйвер [101.6127](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) и проверить игру?
> 
> БР, Илья.



> Hey @Pashamolochko , We've released a big fix for DX11 games, and this game is also included. I've tested it a little and it looks like there are no more brightness drops. Could you install [101.6127](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) driver and check the game?
> 
> BR, Ilya.

Wow, I'm surprised by this fix, but unfortunately I sold an intel video card, but I have friends in this game and with this video card, one of these days they will test and I will give you an accurate answer

**Comment by Pashamolochko** [comment]
> Hey @Pashamolochko , We've released a big fix for DX11 games, and this game is also included. I've tested it a little and it looks like there are no more brightness drops. Could you install [101.6127](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) driver and check the game?
> 
> BR, Ilya.

Hi, the game has been checked, there was no bug

**Comment by Ilya-intel** [comment]
@Pashamolochko 
Thanks for confirming, I'll close the thread now.
