### ISSUE TITLE
Graphical artefacts in Eve Online with DX11 & DX12

### ISSUE THREAD

**Issue by rookieattrendax** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#739]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Eve Online

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

CCP Eve Online Launcher

### Processor / Processor Number [Required]

AMD R7 5800X3D

### Graphic Card [Required]

Intel ARC 770

### GPU Driver Version [Required]

31.0.101.5333

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14607059/ssu.txt)

### Description and steps to reproduce [Required]

![eve2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/153989737/d64b7c84-f2ce-47ed-ac1b-8ec476c36daa)

Flickering textures, somtimes blocky body objects, flickering between too bright and completely black. same behavior between dx11 and dx12. particle issues.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![eve1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/153989737/e2686a59-a57e-4438-a2a6-959ff49a00b4)

**Comment by Arturo-Intel** [comment]
@rookieattrendax Can you share us a short video of the behavior? That would help us a lot.

**Comment by rookieattrendax** [comment]
with high reflections:
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/153989737/052b775d-c8c5-4867-b4af-77c283b7b526

**Comment by rookieattrendax** [comment]
medium reflections fixes some, but some artefacts (blocks popping in?) remain:


https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/153989737/7b961a58-67df-4fba-b37f-ae8bf46d8c02

**Comment by rookieattrendax** [comment]
eve better video demo of the problem with medium reflections as well: 

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/153989737/09441929-7e91-493a-a6d2-9cd88373e0db

**Comment by rookieattrendax** [comment]
another sample of a graphical glitch
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/153989737/93372022-5c2c-4e6e-8c54-0fb6b96ed78f

**Comment by mujeeb-intel** [comment]
Hi @rookieattrendax Please install driver 31.0.101.5762 or newer from [Download Center](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html).

This driver fixes this issue. Tested it w/ Arc A770. Please test and let me know so i can close the ticket.

Thanks.

-Muji

**Comment by mujeeb-intel** [comment]
Hi, can I go ahead and close the ticket?

**Comment by mujeeb-intel** [comment]
Hi, I played and confirmed you no longer see the black rectangle artifacts in the game. Ill go ahead and close this ticket but feel free to refer back to this.

Thank you!

-Muji
