### ISSUE TITLE
Ship Graveyard Simulator 2 - Steel Giants DLC - Internal Driver Error - DX11

### ISSUE THREAD

**Issue by akarnokd** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#740]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Ship Graveyard Simulator 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

31.0.101.5333

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14615145/igcit_ssu.txt)

### Reproduction
- You'll need the **Steel Giants** DLC.

From scratch:
- Buy the $6000 huge ship *Big Chung*.
- The game starts to load the ship.
- Unreal Engine Crash citing Internal Driver Error.

Via save:
- Just load the save.

:information_source: Feedback from the Dev's discord indicates this is a driver issue.

:information_source: Played the save on an i7 8700 + GTX 1060 6G in DX11 mode without issues.

### Workaround

Set the `-dx12` launch parameter on the game. Managed to finish the said ship and the even larger ship afterwards.

### Addendum

Also got the following crash details at one point but never since:

```
LowLevelFatalError 
[File:Unknown] [Line: 258] 
Device->CreateBuffer(&Desc, NULL, UniformBufferResource.GetInitReference()) failed 
 at D:/Build/++UE4/Sync/Engine/Source/Runtime/Windows/D3D11RHI/Private/D3D11UniformBuffer.cpp:150 
 with error DXGI_ERROR_DEVICE_REMOVED DXGI_ERROR_DRIVER_INTERNAL_ERROR

Crash in runnable thread RenderThread 1
```

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/aaac0e30-b439-4afb-aeda-8f1d2174292c)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/064dbf2a-6429-4f84-8f81-245ec9df12c7)

### Crash dumps [Required, if applicable]

[UE4CC-Windows-72B37A2E46FDA55C65444CB7799EA36C_0000.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14615203/UE4CC-Windows-72B37A2E46FDA55C65444CB7799EA36C_0000.zip)

### Save game

`%USERPROFILE%\AppData\Local\ShipGraveyard2\Saved\SaveGames\`

[FullSave_AutoSave_001.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14615208/FullSave_AutoSave_001.zip)

**Comment by Felipe-Intel** [comment]
Hello @akarnokd 
Thank you for submitting this issue. We are actively working on a fix for this issue and expect to have it available in the upcoming months. As soon as I have new information I will come back to you.

**Comment by Felipe-Intel** [comment]
@akarnokd I know it's been a while but we finally have released a driver with dozens of fixes for DX11 game, including this title. You can find the driver [here](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html). Its version is 32.0.101.6127.
I tested it and didn't see the crash in the savegame you provided. I also noticed the game allows to be launched with DX11 or DX12, no crash on either option. 
Could you also confirm the game works for you with the new driver?

**Comment by akarnokd** [comment]
Thank you. Unfortunately, I won't be able to verify this until late next Monday. 

Anyway, I'll close this report and open a new one in case I have further issues with this game.

**Comment by akarnokd** [comment]
Confirmed no more issues with 6129 in either DX11 or DX12 mode. Thank you!
