### ISSUE TITLE
Starfield performance regression with 1.10.31.0+

### ISSUE THREAD

**Issue by akarnokd** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#743]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Starfield

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

31.0.101.5333

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14654365/igcit_ssu.txt)

### Description and steps to reproduce [Required]

First of all, thank you for the labor of love work you are doing for Starfield :heart:

New game version dropped, **1.10.31.0**. I see performance regression in the Lodge again. Haven't checked the usual suspects, such as temples.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/739296ba-175f-47c3-8fdb-69a1d190f760)

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/b00ed10a-6e2d-46d9-8df3-0ff2ed86eb12)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/3d67c3be-56a9-4451-bab2-3cd9a144e36e)

### Save game

If you need a save in the Lodge (77MB):

https://drive.google.com/file/d/16c8uwtsfClyE9y6lMbIlcPdhcgD7AmN8/view?usp=sharing

**Comment by akarnokd** [comment]
I also noticed some new flickering when rotating the system view, not sure if it is related:

https://youtu.be/JkUaDVFSbdg

**Comment by akarnokd** [comment]
FYI, Driver 5379 via DDU, same 40 fps and same flickering.

**Comment by rmorera-intel** [comment]
@akarnokd thanks for the update, I'll go ahead and replicate this in my test bench. I'll provide an update shortly.

**Comment by akarnokd** [comment]
Just for the record, DDU + Driver 5382, Game 1.10.32.0 - same 40fps in the lodge.

**Comment by rmorera-intel** [comment]
Thanks for the update! I was able to complete my tests and can confirm the FPS drop in the lodge area. I'll pass this on to the driver debug team now.
Once there is an update I'll let you know.

**Comment by akarnokd** [comment]
For the record, DDU + Driver 5444, Game 1.10.32.0 - same 40fps in the lodge. 
35fps when talking to the lady at the Centaur Arms while practically looking at a wall behind her.

**Comment by akarnokd** [comment]
Thank you for working on this.

I have one more issue that may or may not related to the game or current drivers.

While playing the game, I sometimes after a few hours of playing Starfield, get a black screen for a couple of seconds, after which the picture comes back as if nothing happened. Game not affected. No event viewer entry. The load on the card at that point was about 160W, 74C core, 80C memory, 21C ambient.

This black screen looks like as if the card presents a complete black screen - not even the Arc Control overlay is visible during this time. (Of course, when the game loads, the game itself can show a black screen but the Arc Control overlay is still there.)

Running a 1080p 60Hz Samsung SD300 monitor (2015) over HDMI. 8Bit SDR mode in Windows. Monitor doesn't have any DP port. Also the monitor doesn't support HDCP.

**Comment by rmorera-intel** [comment]
Please file a new GitHub thread for this separate issue so it is easier to track and follow by others.

**Comment by akarnokd** [comment]
Driver 5518 and Game version 1.11.36 seem to have fixed the performance issue *on average*.

Frametime graph is wibbly-wobbly with 1% lows at 40 and 50, but I'm not noticing any stutter. I'd consider this particular issue resolved.

![Starfield_1_11_36_d](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/78e8ae04-e5c1-4e99-8f7f-45471e15fac1)

![Starfield_1_11_36_c](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/dcce5b98-a113-44de-8bcf-d7f1b3343ac2)

**Comment by rmorera-intel** [comment]
Thank you for reporting back, there is still plenty of work pending to further improve performance so keep those drivers up to date! 
Best Regards,
