### ISSUE TITLE
New DirectX 11 driver efficiency problem

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#745]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Assassin's Creed Origins

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [X] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

intel Core i7-13700KF

### Graphic Card [Required]

intel Arc A770

### GPU Driver Version [Required]

31.0.101.5379

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU_20240321.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14695343/SSU_20240321.txt)

### Description and steps to reproduce [Required]

One of the highlight features of driver v5379 is performance uplift for AC:Origins.

I just tested it, with "Ultra High" graphics preset, the new DX11 driver can achieve 80 FPS while using DXVK can get 83 FPS, so the new DX11 does bring very good (though not perfect yet) result compared to previous DX11 drivers. The driver dev team deserves great praise.

However, carefully examining the statistics, you'll see the CPU frametime values are 3/4/8(min/avg/max) milliseconds with DXVK but 6/8/18 with DX11. That means even with the new DX11 driver, it still takes double the time, compared to DXVK wrapper, for the CPU to issue draw calls for a single frame.

I think this information might be helpful for the driver dev team to further improve the driver efficiency.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

simply the "Ultra High" preset

**Comment by Susie1818** [comment]
Why driver efficiency is important? The benchmark mentioned above was done under 1440p resolution and Ultra High graphics settings. With lower resolutions such as 1080p in addition to lower graphics settings, which both lessen GPU burdens, the CPU frametimes mentioned above would very soon become not fast enough to keep up with shortened GPU frametimes. 

In the example above, the current driver v5379 is capable of delivering about 125 FPS with DX11 (which is far better than the ~60 FPS with previous drivers BTW) and about 250 FPS with DXVK using an i7-13700K CPU in this game. Apparently an A770 is very likely capable of rendering more than 125 FPS under lower resolutions and lower graphics settings. Moreover, considering the fact that most ARC GPU users would be using middle-range or entry level CPUs, such as a Ryzen 5600 which definitely cannot achieve an average frametime of 8ms, the driver efficiency is even more important.

At the end of the day, we just don't want to see our GPU underperforming due to driver inefficiency.

**Comment by Susie1818** [comment]
[For your reference](https://youtu.be/Iw88keFi0Lk?si=YZXhHcEmbtObH7Pi&t=194)

The new driver is still not efficient enough. The performance is still quite sub-par on an Ryzen 5600 CPU, and the GPU utilization is still quite low. This kind of phenomenon (when paired with mid-range or low-end CPUs) doesn't happen with Nvidia/AMD GPUs (drivers). If the performance target is to surpass RTX3060 with A750, you have to make sure it's achievable on at least mid-range CPUs (if you guys don't have AMD platforms in your labs, at least use an i5-10400 for your testing), otherwise it's quite meaningless (if you guys always use 12900K/13900K/14900K for testing).

**Comment by Felipe-Intel** [comment]
Thanks again for reporting this issue and being so passionate about our graphics products. As you may have seen in the past months, other DX11 titles have received performance uplifts thanks to driver improvements. For the title used to submit this report (AC Origins) no further performance tuning will be made. You can be certain that we will continue to improve our software performance and compatibility but for this particular case we can’t accommodate your request. Remember to keep your drivers up-to-date to take advantage of any fix or tweak that may improve the general performance of this and other DX11 titles. 
I will close this ticket. Feel free to answer back here if needed.
