### ISSUE TITLE
Very low performance in a number of games and programs, no matter the settings

### ISSUE THREAD

**Issue by MasterKamen** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#746]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

American Truck Simulator, Bus Simulator 2018, rFactor 2, Minecraft, Need for Speed Heat, Uboat

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 3 2200G

### Graphic Card [Required]

Intel Arc A750 Limited Edition

### GPU Driver Version [Required]

31.0.101.5379

### Rendering API [Required]

- [X] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14733836/ssu.txt)
Note that the BIOS version/date is incorrect, I am running Gigabyte BIOS F51 (the latest version). It reports as AMI because I used one of their utilities to toggle some settings. The BIOS is entirely stock other than modified "optimal" default values for some settings.
The graphics driver version is the older one because I downgraded to fix the issues I'm reporting.

### Description and steps to reproduce [Required]

I am encountering terrible performance (4 fps) in the listed games and in graphically accelerated software. The performance issue seems to be specific to the .5379 driver version. 5333 has no such issues but has graphical bugs in a number of other games.
DaVinci Resolve hardware acceleration does not work like it should, it chokes the GPU and it performs worse than pure software rendering on the CPU. Render time for a 15 minute 4k video is about an hour, compared to 18 minutes on the previous driver version. 
The performance does not improve after lowering any settings, it always hovers between 4 to 7 fps. I have noticed that Euro Truck Simulator 2 (a game that is very similar to American Truck Simulator under the hood) performs as it's supposed to, around 80 fps at 1440p. 

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

There is no difference in performance, no matter the resolution

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

I have tried all possible graphics settings and it does not change the performance.

**Comment by Gabriela-Intel** [comment]
Hi @MasterKamen Did you use [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) before installing 5739? I tried to replicate with 2 of the games you mentioned (American Truck Simulator & Bus Simulator 2018) but they both ran just fine.

By the way, I also see you have a Ryzen 3 2200G system. Technically this isn't a supported hw configuration for Arc (see [here](https://www.intel.com/content/www/us/en/support/articles/000091128/graphics.html)) so you may encounter unreliable performance (or other types of issues) here and there...

**Comment by MasterKamen** [comment]
> Hi @MasterKamen Did you use [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) before installing 5739? I tried to replicate with 2 of the games you mentioned (American Truck Simulator & Bus Simulator 2018) but they both ran just fine.
> 
> By the way, I also see you have a Ryzen 3 2200G system. Technically this isn't a supported hw configuration for Arc (see [here](https://www.intel.com/content/www/us/en/support/articles/000091128/graphics.html)) so you may encounter unreliable performance (or other types of issues) here and there...

I DDU'd the driver now and reinstalling has fixed the problem. However, I do not trust that it won't happen again. The last time I "fixed" it in a similar way, it started occuring again while the system was being used about a day later.

Having read a lot about this particular combination (Ryzen 2000 and B350 chipset) I'm attributing the issues to the very dodgy ReBAR support on the old CPU and motherboard. I'm upgrading the CPU tomorrow so I guess only time will tell if the problem is gone for good. 

Thank you for the effort.
