### ISSUE TITLE
Broken bloom in Star Trek Online

### ISSUE THREAD

**Issue by MasterKamen** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#752]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Star Trek Online

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 5600X

### Graphic Card [Required]

Intel Arc A750 Limited Edition

### GPU Driver Version [Required]

31.0.101.5379

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14795395/ssu.txt)

### Description and steps to reproduce [Required]

https://www.mediafire.com/file/sm1iepclzf6tq6s/2024-03-28+21-46-33.mp4/file

As you can see from the video, bloom (which is on by default), is very broken. It is way too strong and is in the wrong colors. There is also a "mesh" present underneath. The bug seems to only appear on planets, and it happens on all maps. Turning it off removes this effect but leaves the mesh behind.
It happens on all graphical settings and resolutions. Enabling fullscreen alters the effect slightly, but it is still there.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![Screenshot 2024-03-28 220301](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/164693812/532722f5-acfe-4bc6-9c12-48130405dd37)
![Screenshot 2024-03-28 220311](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/164693812/fbe34842-95b1-4708-8bf6-b5e027d4dd0c)
![Screenshot 2024-03-28 220319](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/164693812/75352904-bed9-448e-bc2e-840c70d29abd)

### Device / Platform name

Gigabyte AB350 Gaming revision 1 (B350 chipset)

**Comment by Ilya-intel** [comment]
Hey @MasterKamen ,
I've successfully replicated the issue and reported it to developers under bug id 18037866396.
In the mean time you can use the following workaround:

- Open Options
- Select Graphics tab
- Under Effects
- Disable Texture anisotropic filtering

**Comment by Ilya-intel** [comment]
Hi @MasterKamen ,
The fix is included in the latest [31.0.101.5590](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) driver.
Could you try it and confirm the fix?

**Comment by Ilya-intel** [comment]
Hey @MasterKamen ,
Did you manage to try the fix for Star Trek?

**Comment by MasterKamen** [comment]
> Hey @MasterKamen , Did you manage to try the fix for Star Trek?

Good evening, I apologize for not replying, I had somehow gotten signed out and failed to receive the replies. I have reenabled the affected settings and it does in fact appear to be fully fixed. Thank you.
