### ISSUE TITLE
Arc Control does not report GPU Voltage correctly

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#754]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Arc Control

### Processor / Processor Number [Required]

intel Core i7-13700KF

### Graphic Card [Required]

intel Arc A770

### GPU Driver Version [Required]

31.0.101.5382

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU_20240329.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14812622/SSU_20240329.txt)

### Description and steps to reproduce [Required]

The "GPU Voltage" value shown on the Arc Control's Performance Telemetry overlay is capped at 1000 mV and does not reflect the real voltage when it's beyond 1000 mV. If you use HWiNFO to monitor the GPU stats, the correct value of GPU voltage is actually reported by the hardware and HWiNFO is able to retrieve it.

I don't know why Arc Control tries to conceal the actual value of GPU voltage now. I remember very clearly that some older version of Arc Control didn't do this. When I started to use my A770 in December 2022, I did spend quite some time tweaking the performance settings and thus I did see GPU voltage higher than 1000 mV shown on the Arc Control's Telemetry overlay very often back then. Since when (which version) has the Arc Control started to do this? And why?

**Comment by Gabriela-Intel** [comment]
Hi Susie! Thanks for taking the time to report this. I'll start investigating what you've mentioned here. I'll get back to you on this soon.

**Comment by Gabriela-Intel** [comment]
Hi again. I was able to successfully replicate so I filed a bug for the team to investigate further (bug id 22019802426). I'll circle back here once I see some movement on the issue. Thanks!

**Comment by Gabriela-Intel** [comment]
Thanks again Susie1818 for reporting this issue! 

 We've been concentrating on making sure the most popular games and apps run smoothly, aiming for top-notch quality. We're going to keep enhancing performance and compatibility with our software through 2024 and beyond.
Unfortunately, we can't tackle your request right now, but keep an eye on the support site [article](https://www.intel.com/content/www/us/en/support/articles/000098610/graphics.html) for updates on this issue. 

Thanks for your understanding!

**Comment by Gabriela-Intel** [comment]
@IGCIT Please close
