### ISSUE TITLE
[X4 Foundations] - Invisible Asteroids

### ISSUE THREAD

**Issue by Spookat** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#758]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

X4 Foundations

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [X] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel i5 12400F

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

31.0.101.5382

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[output.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14898148/output.txt)

### Description and steps to reproduce [Required]

All asteroids in the game do not render. The models are there, but invisible. Happens on 6.20 (release) and 7.00 (beta).

Tested on both GOG and Steam releases, all currently released expansions.

This game is a bit of a nightmare to learn so I will try to be as detailed as possible - the screenshots are from the beta patch 7.00 there was nothing major changed in terms of reproduction.

There is no mentions of this in the X4 foundations forums and I was able to see them fine with my previous graphics card (GeForce 1060).

You can shoot the asteroid, it has a hitbox so you'll collide with it. This affects all asteroids in the game - wrecks function similar but they load fine.

**Reproduction:**
- Start a new game, use the Young Gun start.
- Board your ship (you spawn in front of it), press F on the chair in the cockpit to enter it
- Press undock
- You can use X to accelerate, Z to decelerate, or use the mouse wheel - hold down left click to change direction
- Shift+1 to enter "travel mode" - you are much faster in this mode
- Press M to open the map, zoom out, right click somewhere in Second Contact II Flashpoint, and click "Set Guidance"
This will show you where to go, or you can use autopilot (CTRL+A) to automatically fly there:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/99222453/583fd370-87c4-48b2-ab88-05d38b1e3101)
- Second Contact is meant to be a system full of asteroids. They are invisible so they are a bit harder to find. Fly around in travel mode until you see this:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/99222453/1cc7be08-03b7-4622-a592-2a35dcd343fb)
You can select the asteroid and get closer - it is invisible:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/99222453/86e48c65-48e4-4175-9c02-9a9c93d8244f)

Bizarrely enough everything else seems to load fine, this is exclusive to asteroids. The game functions well, it's just immensely frustrating to fly around and constantly get knocked out of the way by invisible asteroids.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [x] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/99222453/f8cadb43-eb1f-4a13-bd22-57f721ef2d5d)

**Comment by Ilya-intel** [comment]
@Spookat 
I'm a huge fan of X4 and whole Series :)
I'll work on this issue, stay tuned.

**Comment by Ilya-intel** [comment]
@Spookat 
Have you tried clean driver uninstalling using DDU Tool?
I've just checked and asteroids seems to render correctly.
![X4](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/fe8a50ae-c396-43f2-9313-9e636eb4b18f)
