### ISSUE TITLE
Earth Defense Force 5: Crashing on startup on new drivers

### ISSUE THREAD

**Issue by TreeChairRope** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#76]
#### Checklist [README]

- [x ] Device is not undervolted nor overclocked.
- [x ] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [x ] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Earth Defense Force 5
---
#### Game Platform [Required]
- [x ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]

---I7 1165G7
#### GPU Driver Version [Required]
- [ x] 30.0.100.9805 (*latest*)
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ x] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [ ] Windows 11 (*Insider Preview*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ x] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (*Please specify your build number*)

---
#### Description and steps to reproduce [Required]

1. try to launch game on newest drivers
2. 
3. 

---
#### Device / Platform [Optional][Recommended]

---
#### Game Settings [Optional][Recommended]
<!--maximum settings

**Comment by IGCIT** [comment]
user confirmed this has been fixed by reinstalling the game
