### ISSUE TITLE
Forza Motorsport closes due to lack of support for Enhanced Barriers on Iris Xe graphics

### ISSUE THREAD

**Issue by goldenx86** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#761]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Forza Motorsport

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5 1240P

### Graphic Card [Required]

Iris Xe

### GPU Driver Version [Required]

31.0.101.5382

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[summary.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14920217/summary.txt)

### Description and steps to reproduce [Required]

Start the game. Can't confirm due to not having enough free space, but Forza Horizon 5 should suffer from the same issue.
![Intel1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/42481638/7ea1f43b-e059-414e-acbf-2ac8649da048)
![Intel2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/42481638/ac8b4360-82d0-4229-913e-49b22e165118)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Any, the game can't create a D3D12 instance.

**Comment by goldenx86** [comment]
Issue persists with driver 5522. Complete lack of enhanced barrier support.

**Comment by mujeeb-intel** [comment]
hey @goldenx86 which version of forza motorsport is this?

**Comment by mujeeb-intel** [comment]
I got it. I dont think this game will even run as the minimum config doesnt mention being capable of running on xe.

Check this out:
![image](https://github.com/user-attachments/assets/b655331a-8915-461b-b671-7fe23bb6a68c)
 

Ill go ahead and close this, let me know if you want to re-open it.

Thanks.

**Comment by goldenx86** [comment]
Being under the hardware features of a 7 years old Pascal GPU is quite "nice".
Thanks, I learnt my lesson, it's better to avoid Intel hardware due to the lack of software support.
