### ISSUE TITLE
CK3 crashes on start-up when launched via Vulkan and/or runs really choppy and stuttery until it crashes (ONLY IF STARTED VIA VULKAN)

### ISSUE THREAD

**Issue by Azmorian** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#765]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Crusader Kings 3

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 5600

### Graphic Card [Required]

Intel Arc A750 LE

### GPU Driver Version [Required]

31.0.101.5382

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14983689/igcit_ssu.txt)

### Description and steps to reproduce [Required]

If you select the launch via Vulkan setting in the settings  on the launcher and then start the game, the game will either crash on boot up or crash while playing. There is no specific moment this happens, it just does. If it doesn't crash right on start up the game will run really choppy and just not nearly as good as with DX11; and it already isn't running as well as it should be on DX11 (no surprise ofc). Needless to say that running games on Vulkan mostly worked wonders for Arc, so this feels very weird and would be great if there is a fix for that!

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [x] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Tried several settings, it seems like this isn't bound to a specific set of settings. Went from highest to lowest.

**Comment by Vivek-Intel** [comment]
@Azmorian thanks for reporting the issue.  are using MSAA x16 when in Vulkan mode ? can you set it to x4 and check if it still crashes. Meanwhile we will try to simulate it in our lab.

**Comment by Azmorian** [comment]
@Vivek-Intel okay during my last session to my surprise my game didn't crash at all that time. That's a first; I will play again today and see how it goes. My graphics settings were on mostly medium quality, I also used MSAA x4 that time.

**Comment by Azmorian** [comment]
Just played again and had another crash. I think this time it was due to lots of troops on the map since there was a crusade going on. I never crashed in this scenario on DX11, so this seems to be clearly an issue when playing via vulkan

**Comment by Vivek-Intel** [comment]
@Azmorian this game has performance issues with Vulkan and it turned out to be an issue from game side.
Please refer to [article](https://www.intel.com/content/www/us/en/support/articles/000098825/graphics.html) and we suggest to play this game in DX11 to avoid issues when playing in Vulkan mode.

**Comment by Vivek-Intel** [comment]
@IGCIT please help close this thread.
