### ISSUE TITLE
Running Fallout 76 & The Planet Crafter at the same time resulted in a card crash

### ISSUE THREAD

**Issue by akarnokd** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#766]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Fallout 76 & The Planet Crafter

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

31.0.101.5382

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15000273/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Launched Fallout 76, entered a world, moved to a safe interior location, then opened the map so the game's load is minimal.

Launched the game [The Planet Crafter](https://store.steampowered.com/app/1284190/The_Planet_Crafter/), loaded a world, walked around a bit, then opened my inventory via TAB and stayed on that screen for about 30 seconds.

Within that 30 seconds, the screen became corrupted with random rectangles showing random pixels, then my card turned off and lost HDMI output.

As far as I could hear, the game and rest of the computer kept on going as I could hear both games' music.

After pressing Ctrl+Win+Shift+B, about 30 seconds later I saw a BSOD for a split second and my computer tried to reboot.

Reboot failed, didn't get to post. Poweroff, poweron. BIOS forced me to reload optimized BIOS settings.

Computer is working now, played only Fallout 76 afterwards without issue.

The crash might not be due to these particular games run at once. Usually don't run two games at once. Theoretically, both games barely tax the card when they run individually and should not overload it either when run at once.

I understand this is not a priority.

Anecdotally, I've experienced similar card crashes when I played a game (Fallout 76, Horizon Forbidden West), Alt+Tabbed out to watch some youtube or facebook video to meet the same card crash. Google Chrome with HW acceleration on. No further details, such as crash dump as I hit reset before even trying the reset-driver key combo - which never worked before.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/43682f45-2eba-46b2-960c-953b0312e03c)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/c9f6a5e8-f205-4e0b-a569-0983225bd6e6)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/09bdcd23-51d3-48f4-ade9-0884b57e117c)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/926cbf6d-6a3c-4679-b423-099504ba74bc)

### Crash dumps [Required, if applicable]

[041624-5578-01.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15000403/041624-5578-01.zip)

### Save game

Fallout 76 saves online.

The Planet Crafter: [Chill-4.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15000435/Chill-4.zip)

Goes into `%USERPROFILE%\AppData\LocalLow\MijuGames\Planet Crafter\`.

**Comment by akarnokd** [comment]
Addendum: Event viewer entry: 116 - TDR failure to recover. I have *TdrDelay 5* and *TdrDdiDelay 10* set months ago via IGCIT Helper. Hence the several 10s of seconds.

**Comment by mujeeb-intel** [comment]
@akarnokd Thank you for bringing this to our attention. Rest assured, I will be working on replicating the issue. Will come back with the results.

I really appreciate your patience.

**Comment by mujeeb-intel** [comment]
Hey @akarnokd excuse the screen recording quality. But check this out. Running Horizon FW and switch to youtube on edge. I noticed no crash. https://youtu.be/9jb17fgSrRc 

I know its not ideal to run 2 games simultaneously but that should not crash the card itself. Im able to run multi applications without the card crashing. Im assuming you have already tried running the ddu and resintalling the driver? If not, can you try that on the latest graphics driver please and let me know?

**Comment by akarnokd** [comment]
I have since installed several newer drivers up to 5768, each after DDU. I have not encountered further card crashes for two months now.

Closing as completed/resolved.
