### ISSUE TITLE
It Takes Two - LowLevelFatalError

### ISSUE THREAD

**Issue by Valkirie** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#77]
#### Checklist [README]

- [X] Device is not undervolted nor overclocked.
- [X] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [X] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
It Takes Two

---
#### Game Platform [Required]
- [ ] Steam
- [X] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]
Intel® Core™ i7-1165G7

---
#### GPU Driver Version [Required]
- [X] 30.0.100.9805 (*latest*)
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [X] Windows 11 (*Insider Preview*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (*Please specify your build number*)

---
#### Description and steps to reproduce [Required]

1. Start the game.
2. Play until the game freezes and display LowLevelFatalError.

---
#### Device / Platform [Optional][Recommended]

Dell XPS 13 9310

**Comment by craiggx** [comment]
Hi there, 

We're looking at your issue and we could use some more details about the system you found this on.

If you could attach a dxdiag, that would be most useful.

To do this:
type "dxdiag" on the bottom search bar on your desktop or press the windows key and type "dxdiag". 
When you run it, it will generate a report. 
Click Save all information to save into a txt file and attach it to this issue. Then we can use it to further debug. Thanks!

**Comment by craiggx** [comment]
Hi Valkyrie,

We're still looking at the crash issue on It Takes Two. Were you able to grab the dxdiag information?

**Comment by estebanr863** [comment]
Hi @Valkirie, can you please test this with the [latest driver version](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html)?

**Comment by estebanr863** [comment]
Hi @Valkirie, had the chance to try this with the latest drivers?

**Comment by estebanr863** [comment]
Hi @IGCIT and @mva94,

We are not seen this issue in our lab with the lastest drivers. Can any of you help test it?

**Comment by IGCIT** [comment]
Hi, unfortunately i don't own the game

**Comment by estebanr863** [comment]
Since @Valkirie is not responding and we are not seen the issue on the latest drivers, can this be closed?
