### ISSUE TITLE
White square blinking, when looking at the water 

### ISSUE THREAD

**Issue by Crazik1982** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#771]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

The Chronicles of Riddick: Assault on Dark Athena

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [X] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 5600G

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

31.0.101.5382

### Rendering API [Required]

- [ ] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

Just start game

### Description and steps to reproduce [Required]

Just start the game,blink can see in cutscene

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Maximum 

### Device / Platform name

PC

**Comment by Vivek-Intel** [comment]
Hi @Crazik1982 can you share your game settings and also try turning off Screen Space Ambient Occlusion ?

**Comment by Vivek-Intel** [comment]
@Crazik1982  I do not see this game in GOG store anymore. where did you buy it from ?

**Comment by Crazik1982** [comment]
Trying to turned off  Ambient Occlusion no results
I buying in gog long time ago, and stored in my clouds torы the cloud

пт, 3 мая 2024 г. в 17:49, Vivek-Intel ***@***.***>:

**Comment by Vivek-Intel** [comment]
@Crazik1982 this game is not available anywhere so we will not be able to work on this issue.
<img width="620" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/114637913/5a292e84-8f96-4676-a5cf-3c8cdffdff56">

**Comment by Crazik1982** [comment]
No buying game, no proublem, good solution!!!
maybe trying, torrent edition?
