### ISSUE TITLE
NFS Unbound: Wraps on the right side of cars turn black 

### ISSUE THREAD

**Issue by weebawop** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#772]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Need for Speed Unbound

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-12500h

### Graphic Card [Required]

A370M

### GPU Driver Version [Required]

31.0.101.5444

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15132668/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Go into lakeshore online and equip a wrap with lots of stickers on your car, when you go out to drive the car, or change the car, the stickers on the right side of the car will turn black. I have 70 cars, I'm not sure whether the problem occurs if you only have one car, but it doesn't take 70 cars for the issue to show up.

If the car has the issue, going into the style or performance menus will fix it temporarily, but leaving the garage or changing cars will make the issue reappear.

![broken wraps](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46519780/35d568e1-eda6-4f36-af27-b6e709f37c28)
![wrap bug](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46519780/d3fd7063-dbfd-4f4b-9e6b-276dccef5b76)

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1200

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

1080p low, XeSS performance

**Comment by Zack-Intel** [comment]
Hi @weebawop 

Appreciate the report and checklist. I'll get testing on my end and have an update by the end of the week on my findings.

**Comment by Zack-Intel** [comment]
Hi @weebawop 

I apologize, but I ran into an issue with my system trying to set up this replication. I will work to resolve it and have a concrete update in a few days.

In the meantime, can you share if this is a regression issue and if it's seen on other graphics settings?

**Comment by Zack-Intel** [comment]
Hi @weebawop 

I was able to reproduce this issue. I will work to collect logs and get this ticket escalated to see if debug team will work on it.

In the meantime, can you clarify the previous questions on if this has been a regression and if other graphics configurations still show the issue?

**Comment by Zack-Intel** [comment]
Hi @weebawop 

We were able to also reproduce this issue on a Nvidia graphics card, so there's suspicion that it might be an issue with the developer's end. Were you able to contact them as well for additional information?

**Comment by Zack-Intel** [comment]
Hi @weebawop 

Do you have any updates regarding the previous communication?

**Comment by Zack-Intel** [comment]
Hi @weebawop 

If there are no additional comments, I will go ahead and close the case. If you have any updates from the developer or additional issues you are seeing, feel free to open a new case.
