### ISSUE TITLE
Arc A380 no longer boosts GPU clock speed and limits it to 1000 MHz while Vsync is actived in Guild Wars 2

### ISSUE THREAD

**Issue by aflamingcookie** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#773]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Guild Wars 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 5 5500

### Graphic Card [Required]

Arc A380

### GPU Driver Version [Required]

31.0.101.5445

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15167483/igcit_ssu.txt)

### Description and steps to reproduce [Required]

The Arc A380 lowers its GPU clock speed to 1000MHz and keeps it limited to that frequency whenever Vsync is activated in Guild Wars 2. Disabling the Vsync option in-game allows the card to boost back to 2450 MHz, which appears to be its maximum factory set clock speed. The graphics card is [https://www.asrock.com/Graphics-Card/Intel/Intel%20Arc%20A380%20Challenger%20ITX%206GB%20OC/index.asp](url)

Restarting the game, resetting its settings to default, reinstalling it completely, reinstalling the intel Arc drivers, reinstalling Windows 11 (full SSD wipe and fresh install) does not resolve the issue.

I have also tested this in other games, such as Metro Exodus, and Guild Wars 2 was the only one i found to be affected by this issue.
The issue does not seem impacted by any other graphics settings, Enabling the Vsync option immediately causing the issue to occur regardless of what other graphics settings are used.

While the issue occurs the game rendering will stutter, which is easy to observe while the player moves around the world.

Additionally note that this issue occurs both with Resize BAR and Above 4G decoding settings activated or deactivated.

Repro steps:
1. Launch Steam and start Guild Wars 2 on a PC using the Arc A380 GPU
2. Log into the game and activate the Intel Performance Telemetry Overlay
3. Enter the game world in any instance, city or open world location
4. Access the Guild Wars 2 Graphics Options menu
5. Activate the Vsync option
6. Observe that the GPU clock drops to 1000MHz and remains locked to that frequency
7. Deactivate the game's Vsync option
8. Observe that the GPU clock returns to normal boost behaviour

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![gw001](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/168570043/04ac0579-1ef0-46dd-a52c-c4536e0e15ff)
![gw002](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/168570043/168ed77e-231a-4d80-a539-4d8c403c2a86)

**Comment by mujeeb-intel** [comment]
Hi, so the issue is seen across different GPU manufacturers, including Intel Arc Graphics. Please report this issue to developer of this title, as the root cause of the issue is on the game itself.
