### ISSUE TITLE
HP Spectrex360 screen freezes when updated to  31.0.101.5445

### ISSUE THREAD

**Issue by fedbwas** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#776]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows

### Processor / Processor Number [Required]

13th Gen Intel(R) Core(TM) i7-1360P 2.20 GHz

### Graphic Card [Required]

Intel ARC A370M driver version 31.0.101.5186

### GPU Driver Version [Required]

31.0.101.5445

### Other GPU Driver version

currently using 31.0.101.5186

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU report 1st May 24.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15177361/SSU.report.1st.May.24.txt)

### Description and steps to reproduce [Required]

update to  31.0.101.5445

### Device / Platform

hp specture x360

**Comment by Ilya-intel** [comment]
Hey @fedbwas ,
I'm currently working on it, as of now, simply disabling Panel Self Refresh in Intel Graphics Command Center (IGCC) is fixing this issue. 

1. Open IGCC.
2. Go to System tab.
3. Power - disable Panel Self Refresh for both On Battery and Plugged In.

I'll let you know when the fix will be published.

**Comment by fedbwas** [comment]
sorry ilya but that didn't work! 

i initialluy couldn't even see the system tab in my version of IGCC, so i uninstalled that and got a new one from the windows store
there i disabled panel self refresh 
then i updated drivers - arc370 had no issues but Xe graphics, same thing happened
i would be well and truly stuck if this wasn't an x360 with a touch screen! I end up having to touch the screen then reset the driver with win+ctrl+shift+b step by step to rollback the driver in device manager.
and now, when i go back to IGCC, there's no disable panel self refresh option at all!
![Screenshot 2024-05-02 123743](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116633446/bb0f331f-0118-4073-bc17-fe30096df406)

**Comment by Ilya-intel** [comment]
@fedbwas 
It works with external display, so it might help to install the driver.
Could try following steps then:

1. Download 101.5445 driver from here: https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html
2. Install/reboot it and wait until IGCC got installed.
3. Disable Wifi and run IGCC to check for PSR setting.
4. If it's there - disable for both power modes.
5. Restart and check for freeze.

**Comment by fedbwas** [comment]
Hi sorry i haven't done this yet because it was freezing right after install and i've had to travel. when i'm back i'll try again

**Comment by fedbwas** [comment]
so, currently i'm running 31.0.101.5445 totally fine. but i see that 31.0.101.5522  is available. however, i see that this issue hasn't been resolved yet on a forum https://community.intel.com/t5/Graphics/Upgrading-Xe-drivers-causes-laptop-screen-to-freeze-HP-Spectre/td-p/1594494 

i also had that issue with the webcam not working yesterday as well. 

when i check the hp website, their driver version is  31.0.101.4146 Rev.A https://support.hp.com/gb-en/drivers/hp-spectre-x360-16-inch-2-in-1-laptop-pc-16-f2000/2101525780

that leads me to believe that HP aren't keeping up with the intel cadence of arc updates. 

so now i'm reluctant to update to .5522. I would dearly like to get my webcam function back though. Any news on when this might be resolved?

**Comment by Ilya-intel** [comment]
@fedbwas 
The fix for this issue is not included in 5522 and 5534, but workaround of disabling PSR is still applicable.

For the web camera issue - I just tried, and it works for me, gfx driver doesn't do anything to other devices, so please try reinstalling webcam driver from hp website.

**Comment by fedbwas** [comment]
![IMG_20240531_100656997](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116633446/aba66ed2-ef70-4271-8221-cb8732da64d1)


Lol it's frozen mid install again. I only got to this screen by ctrl shift windows b refresh and touching the screen. I know it's just the graphics because my music is playing fine. If this computer wasn't a touchscreen, I would be in trouble as I don't have an external device!

I can wait while it works and just graphics refresh and touchscreen to restart but this is v unnerving

**Comment by fedbwas** [comment]
ok i got it! had to get IGCC from the windows store and then step by step get to the menu. i had PSR enabled for plugged in. works fine now. thanks!

**Comment by Ilya-intel** [comment]
@fedbwas 
Good news! The Fix is now included into the latest driver - [31.0.101.5590 ](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)
Could you install it, then enable back PSR in the IGCC and confirm the fix?

**Comment by fedbwas** [comment]
it works!! thank you very much!!
