### ISSUE TITLE
[BeamNG.Drive][Vulkan][VR][A770-16GB][PICO4] VR not showing on VR Headset

### ISSUE THREAD

**Issue by PeterMC96** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#777]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

BeamNG.Drive

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 7 5800x

### Graphic Card [Required]

Bifrost Arc A770 OC 16gb

### GPU Driver Version [Required]

31.0.101.5445

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15189669/igcit_ssu.txt)

### Description and steps to reproduce [Required]

- Open BeamNG.Drive in Vulkan Mode
- Enter any level
- Open Pico Connect and connect PICO 4 VR Headset to the PC
- Open SteamVR
- Switch to VR mode in-game
- The game receives inputs regarding the head tracking and renders the game accordingly as seen on the PC display:
![Screenshot 2024-05-02 171240](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/45486005/b2e9386b-6aad-42f2-a120-49f4a5501e13)
- But no visual input:
![Screenshot_com picovr picostreamassistant_2024 05 02-17 11 48 474_346](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/45486005/27908572-f1d5-4a4d-96de-f0e93f4579c8)

I looked into the SteamVR debug console, and there it seems to be continuously messaging this error: 
![Screenshot 2024-05-02 171313](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/45486005/b240c794-0493-4596-b8b2-9331891ed996)

I have tested with other similar performance GPUs and had no issue, so I think it's something related to the implementation of this function: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceImageFormatProperties2.html

Let me know if you need additional test case scenarios / data. 

Thank you!

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/45486005/c19de694-350d-4504-80e8-3de235a06236)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/45486005/25266712-f765-4ef9-a055-186aa717b92f)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/45486005/28175c1c-69a9-46d1-9f9a-4ab0c19a60f8)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/45486005/3c4ad5a3-1e58-4095-a251-7ecc260b61a3)

### Device / Platform name

Pico 4 / Pico Connect

### Crash dumps [Required, if applicable]

[SteamVR-2024-05-02-PM_05_14_53.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15189793/SteamVR-2024-05-02-PM_05_14_53.txt)

### Save game

Not applicable.

**Comment by EstebanIntel** [comment]
Hi @PeterMC96,

Unfortunately, Arc A-Series currently doesn't support VR. We are continuously working to add more features to our drivers, so this might change in the future. However, due to the current workload and priorities our driver development team, there is no specific timeframe for this.

**Comment by EstebanIntel** [comment]
@PeterMC96 can this issue be closed?

**Comment by PeterMC96** [comment]
If you promise to add support for this specific use-case, then yes :).
FYI: Even if it doesn't officially support VR , in Asseto Corsa and Blade and Sorcery the GPU works like a charm.
