### ISSUE TITLE
Starfield: occasional temporary black screen in some demanding scenes

### ISSUE THREAD

**Issue by akarnokd** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#778]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Starfield

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7 13700K

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

31.0.101.5445

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15209492/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Game version: 1.10.32

*The issue is more of an annoyance so I understand if this becomes low priority.*

Can happen on lush planets, just by walking around or demading caves. In the attached save, entering the cave results in the temporary, 2-3 second black screen on occasion. Doesn't happen all the time, nor can I reproduce the issue by repeatedly entering.

It appears the card renders a black image as both the Steam FPS overlay and the Arc Control performance telemetry is also missing. Doesn't look like any HDMI cutout or resolution change that typically cause temporary no display as those result in my monitor showing its menu/source overlay afterwards.

Generally, the frequency is about once or twice every day I start to play the game. I.e., I played a week ago, got the temp black screen but then no issues in the remaining 6 hours. Played it today, got the temp black screen issue but not again in the past 1 hour.

There are no entries in the event log, the game or the rest of the system is not disrupted in any measurable way.

I've been monitoring the GPU via the Arc Control overlay, temps were 70-78 C and power in the <150W outside, but entering the cave, the power jumped up to 170W.

The card is plugged into the motherboard directly, runs at PCIe 4.0x16. My PSU is a Corsair RM750x. The system was built brand new at the end of February, 2023. Card power limit is still 190W. TDR timeuts are set to 5 and 10 seconds. Drivers installed after DDU every time a new driver comes out.

I have not encountered such temporary black image with other, demanding games I've played recently, such as Horizon Forbidden West (which strangely never went above 170W with 100% utilization either). So for me, it is only Starfield that does this.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

All settings low or off, except VSync(on) and Anisotropic filter (4x). No upscaling.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/d8cf4f0f-8054-4661-8b30-453d2f4ea4bc)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/8f006c31-7c65-45f8-9ac7-f89c09eabae9)

### Save game

[Save6_DAED947E_4A6F65_050233_20240504111512_289_11_4.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15209500/Save6_DAED947E_4A6F65_050233_20240504111512_289_11_4.zip)

**Comment by Felipe-Intel** [comment]
Hi @akarnokd I noticed you submitted various bug reports for Starfield. Was this solved with the recently released driver 5518. 
Just saw your report of a returning corruption in bug #787 and was wondering if this one (778) was fixed.

**Comment by akarnokd** [comment]
Yes. No more power spikes with this save. No temporary black screen either.
