### ISSUE TITLE
Passmark PerformanceTest 11.0 fails DX10 on x6414RE

### ISSUE THREAD

**Issue by ulfhei** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#780]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Passmark PerformanceTest 11.0

### Processor / Processor Number [Required]

x6414RE (also x6413E)

### GPU Driver Version [Required]

31.0.101.2127

### Other GPU Driver version

Tested on 31.0.101.2127 and 2125

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [X] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[TCA7.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15234964/TCA7.txt)

### Description and steps to reproduce [Required]

1.Start Passmark Performance Test
2.Click 3D MARK
3.Click Run DirectX 10 test
4. Benchmark will start, and screen go black when first meteor comes really near.
5. Looks lile the GPU resets itself, and application "fails" after 2-3 of these resets.
7. Fails in 95 % of tests with “Manually aborted”, so please test multiple times if it does not fail the first time.

### Device / Platform

CPU card congatec TCA7/x6414RE, but also fails on other CPU-card with same CPU

**Comment by ulfhei** [comment]
I can also add that we have only seen this behaviour on x6414RE and x6413E, not on J6412, which is stable, so to replicate this, you most likely will need one of those two models of CPU.

**Comment by EstebanIntel** [comment]
Hi @ulfhei,

As stated in the [Intel® Arc™ A-Series Graphics – Desktop Quick Start Guide](https://www.intel.com/content/www/us/en/support/articles/000091128/graphics.html), the supported hardware configurations for Arc A-Series GPUs include 10th gen or newer Intel Core CPUs and AMD Ryzen 3000 or newer CPUs. Atom CPUs are not a supported hardware configuration.

**Comment by ulfhei** [comment]
We are not using an Arc GPU, just the built in GPU in the x6414RE SOC, so there must be some misunderstaning.

**Comment by EstebanIntel** [comment]
Hi @ulfhei,

Sorry for my misunderstanding.

Me and the rest of the Intel team providing support on this site are focused on consumer Intel graphics products, while the Intel Atom x6414RE is intended for the embedded market. For support on embedded products, please contact your device manufacturer directly. Or, if you are working with a device manufacturer, please submit your issue to [https://premiersupport.intel.com/](https://premiersupport.intel.com/).
