### ISSUE TITLE
Low poly flashy waves in Valheim (again)

### ISSUE THREAD

**Issue by PhildeSade** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#781]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Valheim

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzon 5 2600

### Graphic Card [Required]

Intel ARC A770

### GPU Driver Version [Required]

31.0.101.5445

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15237493/SSU.txt)

### Description and steps to reproduce [Required]

Intel ARC A770, AMD Ryzon 5 2600 (y, will upgrade this soon), 32GB RAM 3200mhz, Windows 11

Valheim / Intel ARC A770 had a problem with low polygonal waves for a long time. Driver 5382 fixed the issue (at least i noticed it then, had not played Valheim for a while). Sunday i installed the latest driver 5445 (uninstalled all older drivers with DDU)  and the low polygonal flashy lighning waves are back. Reverted back to the 5382 and they are fine again (not perfect, they look like lower graphic setttings, but not that hard shapes and not that flashy). 
Here is a clip from stream (from back in the days): https://clips.twitch.tv/CourageousThankfulElephantTakeNRG-lFiQyrDG3BHV7Hdk 
Here an recent clip: https://clips.twitch.tv/GlutenFreeEvilWitchFUNgineer-yvl2ejsMMJhCtdkr 

Have no clip for "normal" waves cause... why clip something normal. But if needed i can sure deliver this aswell.

Also reproduced it by reinstalling 5445, clearing the DirectX shaders, it reappers. Going back to 5382 solves the problem again. So it is a reproducable driver problem on my side.

Also tried with and without mods and on stable also as on latest test branch. All the same.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Appears on all settings.

**Comment by PhildeSade** [comment]
Forgot to mention: Also the same starting Valheim with Vulcan or without.

**Comment by Arturo-Intel** [comment]
Hey @PhildeSade, thanks for sharing this case. 
I just want to make sure you used DDU (in safe mode) to install the new driver.

I am in the middle of reproducing this behavior in the lab.
Will share any news/questions here.

**Comment by Arturo-Intel** [comment]
https://youtu.be/ApzMJ4ZdGBY
I am not able to reproduce it with 101.5444
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/8c3bfdd7-00f0-4966-8ce0-3fdd5f78b1df)
Settings:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/d40d6dca-1a7d-43b3-be26-7815dff25020)
In the video shared, you were near the Plains biome right?
Could it be the weather? 

-r2

**Comment by PhildeSade** [comment]
Hi. 
I used DDU before installing, yes. Also cleared directX shaders after installing driver.

And yes, it appears when waves move fast/get higher. If you use the console u can go:
devcommands
debugmode
env thunderstorm
to make bad weather.

And no, it appers regardless wich biome i am close to.

And btw: i tested kinda every graphics setting. Does not change whatsoever.

Ty for ur help. :)

**Comment by PhildeSade** [comment]
Btw: i am not the only one, same issue reported here:
https://valheimbugs.featureupvote.com/suggestions/445932/low-poly-waves-with-intel-arc-a750a770

**Comment by Arturo-Intel** [comment]
Hello again,
Tried with Thunderstorm enabled, still no luck to reproduce the issue...

https://youtu.be/PezXLPM5KU0

Can you share your seed map number?

-- r2

**Comment by PhildeSade** [comment]
Hi again @Arturo-Intel 

it happens on every seed i have tried. Strange that you can't reproduce it cause i managed to replicate it several times now.

Seeds confirmed with the issue: 4sch3, MX7L9GYcf3, vQAVD4LD7P

Any Ideas from here on?

**Comment by PhildeSade** [comment]
I spent some time again to replicate: 

Save mode --> DDU uninstalled the driver with restart --> Cleared DirectX shaders --> installed 5445 --> restart --> Bug is there again. 
Just clean installing 5382 --> restart --> fixes the issue again.

I am far from beeing expert, but it seems to be a clear driver issue on at least my system, as this is the only thing i can do to turn on/off the bug.

**Comment by Arturo-Intel** [comment]
Let me try with those seeds numbers, I am still unable to reproduce this behavior, even in different machines.

**Comment by PhildeSade** [comment]
Tested with 5448 today. Bug is there. Reverted to 5382, bug is gone again.

**Comment by Arturo-Intel** [comment]
@PhildeSade could you please verify the integrity of the game files?
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92489452/614e7d02-2234-402a-867c-33e421487ef9)

I am still not able to reproduce this behavior on my side.

**Comment by PhildeSade** [comment]
@Arturo-Intel Just tested, Nothing wrong with the files. 

Tomorrow i get my new CPU (upgrading from 2700 to 5700 to close the bottleneck as good as possible with my board). 

Will then test again if u got no more ideas. Also i can for sure offer a call or something to get through step by step if helpfull.

Also got a graphical bug in another game (Star Trek Online) with flickering lights. There it can be fixed by turning off "Texture anisotropic filtering". Just mentioned it cause it may be correlated and helpfull for you. Ignore it if not. :P

**Comment by Arturo-Intel** [comment]
https://youtu.be/6LzFI16ajds

Using driver: 101.5448
Seed: vQAVD4LD7P

No luck reproducing the behavior... :/

@PhildeSade We can get in contact by discord (mrr2d2) if you like!

-- r2

**Comment by PhildeSade** [comment]
Hi there,

only thing i saw was ur higher resolution. I am on 1080p. Rest of the settings are same (but it happens on literary all settings on my side) May it be a compability issue with board/cpu? Sent u a request on Discord, maybe we can find a faster communication there. As mentioned, My new CPU is arriving soon, will test it with the new one.

**Comment by PhildeSade** [comment]
@Arturo-Intel Just wanted to say thank you for ur patience, ur kindness and ur good work. Finally reproduced it. If there is any place i can share my great feedback about that experience, just let me know. :)

**Comment by Arturo-Intel** [comment]
@PhildeSade hey can you test with [32.101.0.5972](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)?

**Comment by PhildeSade** [comment]
@Arturo-Intel on the first look all looks fine. 5972 seems to fix the issue. No long testing time, but can't reproduce it anymore, wich was kinda instant on the older versions.

Ty for the help again.


New Problem: Enshrouded crashes now at loading screen into world (new and old character, had problems on and off with that game) :P

crash_dump:
[enshrouded.log](https://github.com/user-attachments/files/16821533/enshrouded.log)

If u see a quick reason, tell me, if not i will try a clean reinsall and all the stuff.

**Comment by Arturo-Intel** [comment]
@PhildeSade Thanks for the confirmation
For the Enshrouded issue, please open a new case for it.
