### ISSUE TITLE
Flashing Lights in Escape from Tarkov: Arena

### ISSUE THREAD

**Issue by Kawamaha** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#782]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [ ] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Escape from Tarkov: Arena

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

BSG Launcher

### Processor / Processor Number [Required]

Intel i5-13600K

### Graphic Card [Required]

Intel Arc A750

### GPU Driver Version [Required]

31.0.101.5333

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

-

### Description and steps to reproduce [Required]

Bright white light flashing, frequently, also happens in the main game "Escape from Tarkov", but not as often.
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/60267630/4a49ea8f-a635-4b1f-b464-ff96d21705d7

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1200

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

FOV: 65
![arena_settings](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/60267630/19b0d014-6bf0-470d-8b6f-e1c1222ce9af)

**Comment by Zack-Intel** [comment]
Hello, @Kawamaha 

Thank you for the checklist! I'll begin testing on my end and should have an update in a few days.

In the meantime, can you share if this case happened on older graphics drivers, and if any changes to graphics settings affect if the flashing lights appear?

**Comment by Zack-Intel** [comment]
Hi @Kawamaha 

I've run some tests with the game, and I might have seen the issue once or twice, but it could've also been gameplay shots. I'm also testing with the most recent driver, 101.5518. I'm also testing in "unranked mode" if that matters, but using the same maps described.

Could you specify the exact frequency this happens, and maybe if there are any characters or weapons that increase the frequency of this happening?

**Comment by Zack-Intel** [comment]
Hi @Kawamaha 

I've been trying some more and I still don't see the issue, except maybe once, which is unfortunately much less frequently than described. I'll keep trying with some other configurations and provide an update soon.

In the meantime, I did notice there was a game update. Can you make sure the game and the drivers are the latest versions/updates and let me know if the issue still persists?

**Comment by Zack-Intel** [comment]
Hi @Kawamaha 

I'm going to go ahead and close this case since I haven't heard back and I haven't been able to reproduce the issue. If you're able to still see the issue with the latest game updates and drivers, feel free to open a new case linking this one and we can continue where we left off.

**Comment by VladimirS37** [comment]
У меня так же была проблема с  мигающими огнями. В игре в настройках анизотропной фильтрации переключите на "Только текстуры".
