### ISSUE TITLE
Destiny 2 : Minor bug with visual lights links

### ISSUE THREAD

**Issue by Nealx3** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#783]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Destiny 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel i5-13600K

### Graphic Card [Required]

Intel ARC A770

### GPU Driver Version [Required]

31.0.101.5445

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15269228/ssulog.txt)

### Description and steps to reproduce [Required]

Hello, I was told to post here to share this bug with you (I'm from reddit).

So it's not a major problem.

The game does not show the "links", for example with the Wish-Keeper when you shoot the arrows loaded on the ground, it must form a pentagram. I do not see it. (Example in pic 1, my game in pic 2).

In the Garden of Salvation raid, the red link does not appear (which is annoying for the Divinity quest lol). I don't have this problem when I'm on console.

I think it's come from the drivers of the gpu, not the game.
Does anyone have an idea where this could come fro.m? Is anyone in the same situation as me?

(Sorry for my bad English, I use a translator lol)

Sorry if this isn't the right place to ask this question.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/169413503/8b043873-81a0-442f-884b-0a5d4f30b1b8)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/169413503/708bcf6e-a077-4d6c-894f-93527458d2a0)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Elevée = high
Moyen = medium

Settings (french name) : 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/169413503/7a0f5a0a-7374-4397-b987-637fa3cb4096)

**Comment by Zack-Intel** [comment]
Hi @Nealx3 

Thank you for reporting this to us. No worries about the English translation. I'm going to see what can be done for replication, but for transparency sake I'm not sure we have a game file far enough to unlock this weapon, so if I'm to pursue this, it might take some time.

Can you let me know if this happens on older drivers, or the newest driver posted on Monday? Also, does reducing the graphics quality bring the links back?

**Comment by Zack-Intel** [comment]
Hi @Nealx3 

We're still working to analyze this case, but we could use some clarification if you happen to know.

Do you happen to know if this only seems to happen on Intel Arc cards, or is it also seen on Nvidia/AMD graphics?

**Comment by Zack-Intel** [comment]
Hi @Nealx3 

I followed up with the debug team, and they're also curious about if the issue happens on other graphics cards. I looked online but had trouble finding anything concrete, so I'm wondering if you saw anything else online about this.

**Comment by Zack-Intel** [comment]
Hi @Nealx3 

I'm going to go ahead and close this issue for now since we are unable to compare this with other graphics cards to know if it's an Arc specific issue. If you're able to help us find more information for us, please feel free to reopen the case, or open a new case linking this one and we can continue where we left off.
