### ISSUE TITLE
Sound through mini displayport may accasualy stop working

### ISSUE THREAD

**Issue by rosti-il** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#784]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

WSL

### Processor / Processor Number [Required]

i7-4790

### GPU Driver Version [Required]

Other (Please specify)

### Other GPU Driver version

20.19.15.5171

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

10.0.19045.4291

### Intel System Support Utility report

[ssu-report.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15276156/ssu-report.txt)

### Description and steps to reproduce [Required]

Please read my bug report and comments at https://github.com/microsoft/WSL/issues/11546

I have the latest drivers of my Intel HD 4600 video card (20.19.15.5171) and of Intel Display Audio (6.16.0.3208).
I use Windows 10 Professional 22H2 build 19045.4291 with all latest updates installed.
Hyper-V is disabled, only Virtual Machine Platform and WSL are enabled.
Tried with WSL versions: 2.2.4, 2.2.3, 2.2.2, 2.1.5
Before I started to use the "Virtual Machine Platform" component of Windows 10 Pro and WSL2 this issue never happened for many years. And after I uninstalled they both the issue gone. But I need them!

There are no special steps. Some time sound works properly but suddenly just stop working through the mini display port and when this happens videos from youtube on my Firefox web browser are played slow too, like in slow motion. Sound through any other audio device still works properly and if I switch into one of other audio devices the youtube issue is also gone. Switching back to the intel audio through mini displayport brings the issue back. Rebooting can help to make intel audio to start working properly again but just until the next time this issue will happen again.

I need the "Virtual Machine Platform" component of Windows 10 Pro and WSL2 for my R&D work and this issue just makes my computer not usable for that just because of this nasty bug. Please investigate and release a new fixed driver.

**Comment by EstebanIntel** [comment]
Hi @rosti-il,

Unfortunately, as described in [this article](https://www.intel.com/content/www/us/en/support/articles/000005733/graphics.html), the Intel HD 4600 was moved to EOS (End of Support) on June 1, 2021.
