### ISSUE TITLE
Halo Infinite - Raytraced Sun Shadows Missing Lighting

### ISSUE THREAD

**Issue by LieutBennett** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#785]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Halo Infinite

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

Xbox App for Windows PC

### Processor / Processor Number [Required]

12th Gen Intel(R) Core(TM) i5-12400F 2.50 GHz

### Graphic Card [Required]

Intel Arc A770 Graphics

### GPU Driver Version [Required]

Other (Please specify)

### Other GPU Driver version

31.0.101.5448

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15283624/ssulog.txt)

### Description and steps to reproduce [Required]

While playing Halo Infinite with the "Raytraced Sun Shadows" setting turned on at any level, there is a complete lack of lighting in game. When it is turned off, the game's baked-in lighting is visible. See the attached screenshots for an example.

Raytraced Sun Shadows off: ![rt_off](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/169548811/76a4f0f9-2135-4933-ba88-f64f0393bcab)

Raytraced Sun Shadows on (High): ![rt_on](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/169548811/ac4b1010-7f91-4d1d-86c2-d38a8b26c852)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Graphics settings are set to "High", VSync is on, all other settings are default.

**Comment by LieutBennett** [comment]
Hello, I submitted this several months ago and still have not heard back about it. I just wanted to check in.

**Comment by mujeeb-intel** [comment]
Hey @LieutBennett I meant to get back to you. I apologies for the late reply but we were able to reproduce the issue internally and it is being worked on. I will let you know as soon as I learn anything new from the devs.

Thanks.

-Muji

**Comment by mujeeb-intel** [comment]
Our engineers have looked into this issue and determined this issue needs to be addressed by the devs of this game. I also suggest you reporting it to the game devs. 

I will go ahead and close this ticket for now
