### ISSUE TITLE
0x119_5_DRIVER_FAULTED_SYSTEM_COMMAND_igdkmdnd64!unknown_function when updating drivers

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#786]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

N/A

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

31.0.101.5448

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 12.05.2024.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15286340/Intel.SSU.12.05.2024.txt)

### Description and steps to reproduce [Required]

Update drivers to 5448
I was casually updating my drivers from DSA, and it just happened. My PC rebooted, the drivers were not updated, and this error popped in the Diagnostic Data Viewer, not even a bluescreen

### Device / Platform

ASUS Prime Z790-P WiFi D4

**Comment by EstebanIntel** [comment]
Hi @TheWonderfulTartiflette,

Can you attach this file: C:\ProgramData\Intel\GFXInstaller\IntelGFX.log?

**Comment by TheWonderfulTartiflette** [comment]
> Hi @TheWonderfulTartiflette,
> 
> Can you attach this file: C:\ProgramData\Intel\GFXInstaller\IntelGFX.log?

Oh sorry I forgot. Sure, here it is
[IntelGFX.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15437107/IntelGFX.log)
I've just tried to install the driver, and got the exact same error and reboot

**Comment by EstebanIntel** [comment]
Hi @TheWonderfulTartiflette,

The [latest driver](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) version 32.0.101.5971 has a possible fix for the installer issue. Can you please test it?
