### ISSUE TITLE
Dragon Age Origins - Dialogue/Choices Text does not render

### ISSUE THREAD

**Issue by bizude** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#79]
#### Checklist [README]

- [X ] Device is not undervolted nor overclocked.
- [X ] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [ X] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Dragon Age : Origins]

---
#### Game Platform [Required]
- [ ] Steam
- [X] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]

i9-11900K and i9-11900KB

---
#### GPU Driver Version [Required]
- [ ] 30.0.100.9805 (*latest*)
- [X] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

---
#### Windows Build Number [Required]
- [ ] Windows 11 (*Insider Preview*)
- [X] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (*Please specify your build number*)

---
#### Description and steps to reproduce [Required]

1. Run Dragon Age : Origins with any Xe-LP based iGPU
2. Begin a dialogue scene
3. You will have black bars on the bottom, but no dialogue text

---
#### Device / Platform [Optional][Recommended]

Device #1 : Rocketlake i9-11900k, ASRock b560 Steel Legend motherboard
Device #2: Tigerlake-H i9-11900KB, "Beast Canyon" NUC

---
#### Game Settings [Optional][Recommended]

This issue occurs at any resolution or settings, but was tested at 1920x1080 low. 
A video of this issue occuring has been uploaded to YouTube:

https://www.youtube.com/watch?v=W-ZgmFs3cJg

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

The scene above can be recreated simply by starting Dragon Age Origins : Awakening DLC and playing the first 5 minutes of the game. 

---
#### Windows mini dump (*small memory dump*) (*if available*) [Optional][Recommended]

---

**Comment by estebanr863** [comment]
Hi @bizude 

Can you please perform this test:

1.	Find and open the “DaOriginsConfig.exe” in your game install folder
2.	Disable aspect ratio correction
3.	Test is no you can see the dialogue choices in-game

**Comment by bizude** [comment]
@estebanr863 Thanks for looking at this issue. After receiving this response, I loaded Dragon Age : Origins using the UHD 770 iGPU and it's working great now. I didn't impliment the step you advised above, so I would assume a driver update in the last 8 months has fixed the issue.
