### ISSUE TITLE
Second Monitor on Portrait (Flipped) but mouse cursor controls stuck in landscape mode

### ISSUE THREAD

**Issue by Joeyboy21** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#790]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows

### Processor / Processor Number [Required]

12th Gen Intel(R) Core(TM) i5-12600K

### Graphic Card [Required]

Intel(R) Arc(TM) A380

### GPU Driver Version [Required]

31.0.101.5522

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/15520689/igcit_ssu.txt)

### Description and steps to reproduce [Required]

1. Set up 2 monitors connected to the Intel Arc A380 GPU.
2. As per below image, arrange the monitors as such. 
3. Display orientation for monitor 2 is Landscape, but Display orientation for monitor 1 is Portrait (flipped).

The display on display 2 shows up correctly to be in Portrait (flipped).
However, when you try to move the mouse cursor like the below image, moving to the right end of monitor 2, the mouse cursor instead comes from the bottom of monitor 1 as per the below image. 
The expected behavior is that the mouse cursor will show up from the left end of monitor 1 instead. 
![20240601_SecondMonitorIssue](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/41661843/bf4f440c-c088-4bea-b273-1c854624bfed)

### Device / Platform

Self-built

**Comment by Joeyboy21** [comment]
Managed to resolve this issue by turning on "Display pointer trails" under "Additional mouse settings" for Mouse settings. 
The wrong cursor still shows up when I disable "Display pointer trails".

**Comment by Vivek-Intel** [comment]
@Joeyboy21 thanks for reporting the issue. Can you please share video of pass and fail case ?

**Comment by Vivek-Intel** [comment]
Hi @Joeyboy21 
I have checked this issue and it does not look like graphics bug but could be a Windows bug or expected behavior
We have simulated this issue on Arc GPU as well as competition GPU and we see the same behavior as in [attached video](https://drive.google.com/drive/folders/1ulIuyugptrdKCy8ZyL3p5_beeE15Mlsl?usp=drive_link) for your reference.
I suggest you to check with Microsoft to confirm if it is expected behavior regarding cursor movement.

**Comment by Joeyboy21** [comment]
@Vivek-Intel I just changed from a GeForce GTX 970 and it did not have this issue. This issue only happened when I started using the Intel Arc A380.

**Comment by Vivek-Intel** [comment]
@Joeyboy21 can you please share videos in both pass and fail case at your end ?

**Comment by Joeyboy21** [comment]
@Vivek-Intel The issue is resolved by turning on pointer trails so please close the ticket. thanks

**Comment by hydratim** [comment]
I'm sorry, but this shouldn't be closed. It's still an issue; turning on pointer trails is a workaround, not a fix.
I don't want pointer trails on, as I find them distracting.

**Comment by Vivek-Intel** [comment]
Hi @hydratim Please help create a new issue if you think this could be a driver related and not the OS related with all required information.

**Comment by jasonycw** [comment]
Somehow I am having the same issue but I am not using an Intel GPU but an AMD GPU.

**Comment by lucidfrontier45** [comment]
Today I switched from NVIDIA RTX 3060 to Intel Arc B580 and found the same problem. It happends not only in multiple display environment but also in single display case.

The mouse trail workaround worked though.

**Comment by AndreaSegoni** [comment]
Same issue on B580, portrait mode only work with cursor trails

**Comment by Motionmist** [comment]
This is still an issue. Cursor trails is still the only workaround. I did try both DisplayPort and HDMI but the problem is still there. This really needs to be reopened to figure out if it is a Arc issue or Windows.

Windows 11 Pro v24H2
Arc B580
AMD Ryzen 7 5800XT
32GB 3600 MHz

**Comment by Felipe-Intel** [comment]
Since this was closed so long ago, please create a new ticket and make reference to this one.
