### ISSUE TITLE
Add HDMI VRR/Freesync support to Arc GPUs

### ISSUE THREAD

**Issue by toriko2** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#791]
### Application [Required]

Any gaming application/ Feature in Arc Control

### Processor / Processor Number [Required]

AMD 7700x

### Graphic Card [Required]

ASRock Intel Arc A750

### Rendering API [Required]

- [X] Vulkan
- [X] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Currently Intel Arc doesn't support VRR over HDMI based on issue thread #590 . Given this, I'm creating this request with the hope that it can be added. Unfortunately it seems the HDMI 2.1 port on Arc cards is incompatible with VRR due to its PCON conversion chip. However to my knowledge the other HDMI port, which is version 2.0, is native and may potentially be able to support VRR. This seems possible given the fact that the original Xbox One, which uses the older 1.4 version of HDMI, has VRR support enabled. Though its of course a different manufacturer, being AMD, so I understand if Intel Arc cards are unable to support this. 

### Additional notes

At the end of thread #590 I was instructed to make this a feature request. Apologies for the delay in doing so.

**Comment by Gabriela-Intel** [comment]
Sorry for taking so long to get back to you! I filed this and passed it along to the team. We really appreciate the feedback!

@IGCIT Please close

**Comment by toriko2** [comment]
Hi, I very much so appreciate passing my issue along to the team. Though after recent research I'm very confused as to why the following pieces of information are distributed

These articles mention that HDMI 2.1 VRR support is available on the card
"The Intel® Arc™ A770 Limited Edition and A750 Limited Edition Graphics offer an HDMI 2.1 output with support for variable refresh rate" quoted from this article https://www.intel.com/content/www/us/en/support/articles/000091128/graphics.html
These articles also imply the same thing:
https://www.intel.com/content/www/us/en/support/articles/000098241/graphics.html
https://www.intel.com/content/www/us/en/support/articles/000096980/graphics.html

My confusion is a such; do intel arc cards actually support VRR over HDMI 2.1 or no? Because in thread #590 it is implied that it doesn't work. I would just appreciate some clarification as someone who bought the card hoping this would work.

**Comment by Gabriela-Intel** [comment]
As Karen mentioned in your other thread, VRR _should_ be supported via HDMI 2.1 but it was determined after investigation that it's not working and was identified as a 3rd party issue so we're asking to contact the PCON manufacturer for support.

And yes I completely agree it IS confusing. I'll work with the team to get these articles updated so it accurately reflects the information that's been shared in this thread and thread #590.

Hope that helps clarify!!

**Comment by toriko2** [comment]
That clears up most of my confusion! So I appreciate the answer. I have contacted the PCON manufacturer(Synaptics) and ASRock so hopefully it gets resolved.

One last question though, is my issue exclusive to the ASRock line of cards or do the limited edition cards sold by you folk have the same issue? Because that was left ambiguous in the last thread.

**Comment by Gabriela-Intel** [comment]
My understanding is that the issue can be seen on LE cards as well, but it's more sporadic.

By the way, thanks so much for your understanding and patience! This one wasn't exactly a clear cut issue. :)

**Comment by toriko2** [comment]
Just to put a final nail in the coffin on this issue. I was able to contact ASRock support and they provided me with the necessary tool to update my GPU's HDMI firmware and now VRR works like a charm!

If any intel employee see's this post, perhaps it would be possible to reach out to ASRock and add this firmware update to intel's standard Arc updater so that everyone else with this card can get the fix.
