### ISSUE TITLE
Stuttering in Company of Heroes 3

### ISSUE THREAD

**Issue by crilles2204** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#792]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Company of Heroes 3

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

 Intel Core i5-13600K

### Graphic Card [Required]

 Intel Arc A770 (16GB)

### GPU Driver Version [Required]

31.0.101.5534

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel System Support Utility report.txt](https://github.com/user-attachments/files/15747396/Intel.System.Support.Utility.report.txt)

### Description and steps to reproduce [Required]

The game is stuttering especially when playing in team game modes. It's most noticeable when panning over the center of the maps and when a lot of things is happening. I've tried to tingle with the settings, DDU re-installed drivers (5534, 5522 and 5448). The driver 5448 don't seems to has as much stuttering as 5534 and 5522. I've played the game for over a year and the stuttering has only been present in the past week and onwards.

Havn't installed new software on the PC. No new Windows Updates appears to have been installed.

Tried to verify the file integrity of the game and did a re-install of the game. Didn't help.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560 x 1440 (2K)

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![Company of Heroes 3 - Performance   Quality](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/172073912/79cedf0c-a7b1-4705-9110-0340efceb38e)
![Company of Heroes 3 - Display Settings](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/172073912/01fd5178-6aeb-4dc9-9e3d-ef4deeff2588)

### Device / Platform name

Self-built

**Comment by crilles2204** [comment]
Tried to update my BIOS to the lastest from Gigabyte (F11b). No change.
Tried to lower the settings from maximum to high. No change. With maximum settings in the past I had good FPS and no stuttering.

**Comment by crilles2204** [comment]
Loaded up a single player skirmish match to see my average FPS in the beginning of a match where not much is happening. Dropping very quickly to around 50 ish FPS.

I also noticed the GPU is almost always running at 100% when in game - is this expected behavior?

I have no FPS issues when playing Red Dead Redemption 2 on max settings. GPU is still on 100% though.

![Company of Heroes 3 - AVG FPS](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/172073912/06b04916-1ee8-4784-8629-65d6ae5f58f1)

**Comment by crilles2204** [comment]
Setting texture detail to low seems to be improving the performance but the stuttering/low fps is still noticeable.

**Comment by Adrian-Intel** [comment]
Thank you for sending this @crilles2204. Please give me some time to try and replicate this on my end. I will send updates here for any results I get.

**Comment by crilles2204** [comment]
Thank you, @Adrian-Intel. Let me know if you need more info or testing from my end.

**Comment by Adrian-Intel** [comment]
@crilles2204 when you do the panning, do you use the arrow keys or the mouse? Does it happen on either?

Please also try new Arc driver 101.5590 and let me know of your results. Thank you!

**Comment by crilles2204** [comment]
@Adrian-Intel - I use the mouse. I happened either way. I upgrade to the latest WHQL driver last night and it's running perfectly again. I don't know what has changed in the driver versions, but something for sure fixed it. I'll try and upload some benchmark data.

**Comment by crilles2204** [comment]
Seems like the stuttering / performance is largely related to the texture detail setting. When set to low on the new driver, performance is good. When set to ultra, the stuttering seems to appear - although not as bad as in the previous drivers.

**Comment by crilles2204** [comment]
Benchmark on highest settings.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/172073912/fe924364-18e3-48fe-b625-9dcd4258d03f)

**Comment by crilles2204** [comment]
Stuttering didn't appear in automated benchmark test. Only seems to appear in-game.

**Comment by crilles2204** [comment]
Benchmark with highest settings except texture detail set to medium.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/172073912/7866a09c-a7be-46fb-96f8-e31f46637058)

**Comment by Adrian-Intel** [comment]
@crilles2204 

I tested with latest Arc Driver v5593 as of this writing and performance is smooth. I used combination of arrow keys and mouse to navigate the map randomly. The stuttering is very small, and I did not notice it during my actual test.

Can you try on your end using Arc driver v5593 and let me know of your results?

Thank you very much!

**Comment by Adrian-Intel** [comment]
I measured smoothness using CapFrameX

1st run
![01](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/158005437/1cfa24fb-b61b-460d-a11c-bc17d8acb0fa)

2nd run
![02](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/158005437/6bec663d-ed7d-4be5-83b4-893c71690b71)

3rd run
![03](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/158005437/95956a98-c211-431d-a4b7-12faf514b6c2)

**Comment by crilles2204** [comment]
Hey @Adrian-Intel 

Just downloaded the latest driver 5594. Played a 4v4 game and captured the first 10 minutes. Didn't notice any stutter. Unsure why it happened on a older driver... Here's my result.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/172073912/b616891f-804d-4535-870e-dd3044e876a5)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/172073912/ae29c7b0-36f8-4999-b2da-f20d61951948)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/172073912/ff273f91-ffa9-434d-84b6-74958fb35a90)

Let me know if you want anymore data. If not, it's fine with me that we close the case. I can always re-open a new one and refer to this one if the same issue occurs in the future.

**Comment by Adrian-Intel** [comment]
@crilles2204 Thank you for sharing your latest test results and it's good to hear that it performs better now. Nothing else is needed on your end.

I got curious and did a retest using Arc Driver 101.5522 which you reported that exhibits the stuttering and it worked out fine with this run. Please see below:

![2024-07-04 - 5522](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/158005437/5491a6fb-1ed6-482a-9034-268d993f9030)

I checked the Steam page of the game, and it shows that there was a hotfix posted last June 26 (Hot Fix 1.6.11). So maybe that helped fix it.

Once again, thank you for reporting this and this definitely helps us improve on our products. In the future, please don't hesitate to send us issues encountered with Arc graphics cards.

We will have this case closed now.

Thank you very much!


Adrian

**Comment by Adrian-Intel** [comment]
@IGCIT please help close this. Thank you!
