### ISSUE TITLE
BodyCam game crashes with the error DXGI_ERROR_DEVICE_REMOVED

### ISSUE THREAD

**Issue by Pashamolochko** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#793]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Bodycam

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Other game platform

Steam

### Processor / Processor Number [Required]

i5 14600k

### Graphic Card [Required]

intel arc a770

### GPU Driver Version [Required]

31.0.101.5534

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

![GpbnK717fEU](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/519e0f56-7446-47a0-bb1d-8397d4737c7d)

### Description and steps to reproduce [Required]

The game runs one or two battles, and crashes with a driver error
![GpbnK717fEU](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/76698599-bcd8-422e-8131-cdce20878735)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920-1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![ыаввыа](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/133571007/ff902555-9f6f-4dd6-aff1-aa18b10e4d1e)

**Comment by Vivek-Intel** [comment]
Hi @Pashamolochko thanks for reporting the issue. how consistent is this issue and can you check on any competition GPU to confirm that issue is specific to Arc only ?

**Comment by Pashamolochko** [comment]
> Привет@Pashamolochkoспасибо, что сообщили о проблеме. Насколько постоянна эта проблема, и можете ли вы проверить любой конкурирующий графический процессор, чтобы убедиться, что проблема характерна только для Arc?

hi, the problem is very floating, and the problem is exclusively on intel arc, there is still an RTX 4070 Super in my operation, there are no similar problems on it

**Comment by Pashamolochko** [comment]
and in general, the closest RTX 3060 in terms of performance shows the best FPS result in this game, if possible, I would like to see some improvements and optimizations in the driver, although everything depends on the developer's side, perhaps I don't know, I'm not an expert in this)

**Comment by Pashamolochko** [comment]
and sorry for my English, I'm communicating with you and your test team through an online translator)

**Comment by Pashamolochko** [comment]
the problem with the crash was solved by installing a more up-to-date version of the game, now it remains to somehow tighten the driver optimization for higher FPS

**Comment by Vivek-Intel** [comment]
HI @Pashamolochko glad to know that crash issue has been resolved after updating the game, can you please help close this issue.
For performance issue, I would appreciate if you can open a new thread with FPS/perf number comparing with other competition GPU so that our engineers can check and work on perf issue separately. Many thanks.
