### ISSUE TITLE
Unable to use more than 2 monitors

### ISSUE THREAD

**Issue by Yomi0** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#795]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 10

### Processor / Processor Number [Required]

AMD Ryzen 9 5900X

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

31.0.101.5534

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu_12_june_2924.txt](https://github.com/user-attachments/files/15808194/ssu_12_june_2924.txt)

### Description and steps to reproduce [Required]

I have two monitors connected via DisplayPort.
If I try to connect a third monitor (either via DisplayPort or HDMI), the third monitor does not come up.
The monitor is listed in, "Advanced Display Settings" but Windows says it isn't active.

If I disconnect one of the other two monitors, then the 3rd does come up.
Oddly, this same monitor setup does happen work on Arch Linux without an issue.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3170531/056b8d18-bb37-4818-8417-95daa3e2ab2f)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3170531/8ec25adc-8bc5-440a-94b3-8a7904b60a35)

**Comment by Gabriela-Intel** [comment]
Hey there! A couple of questions.

Is this the first time setting up the third monitor or was it working fine before and just suddenly stop working?
Have you already tried reinstalling the latest Arc graphics driver using [DDU](https://www.guru3d.com/download/display-driver-uninstaller-download/)?
Can you share the models of the displays? I do see the Dell 2415H in your screenshot.

Thanks!

**Comment by Gabriela-Intel** [comment]
I'm assuming you're running both SDMU27M90*30s at 3840x2160@144hz and the S2415H at 1920x1080@60Hz. Let me know if otherwise.

If you lower the resolution and/or refresh rate on the SDMU27M90*30s, does anything happen?

I can also give this a shot on my end using similar displays and a similar set up.

**Comment by Yomi0** [comment]
> I'm assuming you're running both SDMU27M90*30s at 3840x2160@144hz and the S2415H at 1920x1080@60Hz. Let me know if otherwise.
> 
> If you lower the resolution and/or refresh rate on the SDMU27M90*30s, does anything happen?
> 
> I can also give this a shot on my end using similar displays and a similar set up.

Yes, that's correct. I'm using the SDMU27M90*30s at 3480x2160@144Hz and the Dell 1920x1080@60Hz.

I changed the changed the refresh rate for both to 120Hz, no change.
Lowered the resolution to 2560x1440 for both, no change then, either.

**Comment by Gabriela-Intel** [comment]
Thanks for confirming! Let me get back to you on this so I can give it a shot.

**Comment by Gabriela-Intel** [comment]
Sorry for the delay. 

I was reviewing the specs for the SDMU27M90*30s. On the [Sony site](https://electronics.sony.com/tv-video/gaming-monitors/all-inzone-monitors/p/sdmu27m90) it lists that there is 1 x DP 1.4 port and 2 x HDMI 2.1 ports. 

But you previously mentioned you had two displays connected via DP. Can you confirm how the displays are connected?

**Comment by Yomi0** [comment]
> Sorry for the delay.
> 
> I was reviewing the specs for the SDMU27M90*30s. On the [Sony site](https://electronics.sony.com/tv-video/gaming-monitors/all-inzone-monitors/p/sdmu27m90) it lists that there is 1 x DP 1.4 port and 2 x HDMI 2.1 ports.
> 
> But you previously mentioned you had two displays connected via DP. Can you confirm how the displays are connected?

Sure,

1x sdmu27m90 connected via DP.
1x sdmu27m90 connected via DP.
1x Dell 2415H connected via HDMI or DP (with a DP to HDMI adapter).

**Comment by Gabriela-Intel** [comment]
Hey Yomi. Finally got a hold of some displays to test this out on. I used the following display configuration on a similar system, and I didn't observe any issues getting any of the displays working.

- MSI MAG274UPF via DP 1.4 (3840 x 2160 @ 144 Hz)
- ASUS TUF Gaming VG28UQL1A via DP 1.4 (3840 x 2160 @ 144 Hz, disabled DSC)
- HP HP2333 via HDMI (1920 x 1080 @ 60 Hz)

I thought this could've been potentially a bandwidth issue with Arc, but your previous testing of setting the two Dell 4K displays down to 120Hz should've done the trick if that was the case..

I did find this that could help, it may be worth trying: [https://www.youtube.com/watch?v=H8yy0brdCuQ](https://www.youtube.com/watch?v=H8yy0brdCuQ)

Also, I'm guessing you already tried some basic troubleshooting but if you haven't already, try swapping out the cables with some that are known to be working.

**Comment by Gabriela-Intel** [comment]
Any update on this?

**Comment by Yomi0** [comment]
I tried it, but I'm still running into the same issue. The Dell monitor has been swapped out for a different screen, but the issue remains the same. This is what I see when I try to extend the display to the monitor. 

![image](https://github.com/user-attachments/assets/df47de3c-e006-434f-b6af-e690d862bc58)

**Comment by Gabriela-Intel** [comment]
By chance do you have another dgpu laying around to test this out on?

**Comment by Yomi0** [comment]
Yes, I've got another GPU laying around, a RTX 2060 Super.

So far, I've tested the following (on baremetal, completely different machine, fresh installs, latest available updates):

_RTX 2060 Super_
Manjaro Linux: (nvidia version 550, I think). It drives all 3 displays at 144 Hz, 120 Hz and 144 Hz. (2x DisplayPort, 1x USB-C)
Windows: (nvidia version 560.70): Same config as above. Same issue as the Intel Arc A770. It can drive two displays, but not the third.

_Arc A770_
Windows: (32.0.101.5762): Same issue as on the VM. Only able to drive two displays.
Linux: All 3 displays work on Arch.

Seems the issue is with Windows.

**Comment by Gabriela-Intel** [comment]
Hmm it might be worth doing a fresh OS install then to see if that changes anything.

**Comment by Yomi0** [comment]
> Hmm it might be worth doing a fresh OS install then to see if that changes anything.

I did, on the other machine I had lying around.
I could spin up new VM, though and see if anything changes there.

**Comment by Yomi0** [comment]
Changing the DisplayPort Version on the Sony monitors from 1.4 to 1.2 allows all 3 monitors to come up.
It limits the maximum refresh rate to 60Hz across all 3 monitors, though.

**Comment by Gabriela-Intel** [comment]
Interesting, thanks for following up here to confirm!

**Comment by Yomi0** [comment]
I was wondering if this could somehow be passed along to Microsoft, because it seems like this should work just fine on Windows.

On Page 7 (PDF, linked below), it mentions the following (I assume it applies to the A770 as well): 

The rich potential display connectivity available from the Intel® Arc™ A380 is uncommon for
a graphics card of its class. Display setups supported include:
- Up to 2x 8k60 HDR
- Up to 4x 4k120 HDR
- Up to 1080p360 and 1440p360 HDR

The same thing is also mentioned on pcworld, under the heading: Xe HPG display engine, however due to the image format, I cannot upload it here.

https://www.pcworld.com/article/627427/intel-arc-xe-hpg-gpu-alchemist-deep-dive.html
https://www.igorslab.de/wp-content/uploads/2022/07/Specs-and-Architecture.pdf

**Comment by Gabriela-Intel** [comment]
In the case that it's occurring across various dgpus, I'd recommend contacting [Microsoft](https://support.microsoft.com/en-us/contactus) directly so they can root cause and debug the issue.

And yes, please note Arc is intended to be used for 1080p/1440p gaming. Arc might be capable of running some games at 4K, it will do it at lower framerates; and it's unlikely that Arc will be able to achieve high FPS @ 4K.
