### ISSUE TITLE
No More Heroes & No More Heroes 2: Desperate Struggle - Really bad performance (5fps)

### ISSUE THREAD

**Issue by prudis** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#80]
#### Checklist [README]

- [X] Device is not undervolted nor overclocked.
- [X] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [X] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
1) No More Heroes
2) No More Heroes 2: Desperate Struggle
---
#### Game Platform [Required]
- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]
i5-1135G7
---
#### GPU Driver Version [Required]
- [X] 30.0.100.9862 (*latest*)
- [ ] 30.0.100.9805
- [X] 30.0.100.9684
- [X] 30.0.100.9667
- [X] 27.20.100.9616
- [X] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [ ] Windows 11 (*Insider Preview*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [X] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (*Please specify your build number*)

---
#### Description and steps to reproduce [Required]

Both games have extremely  low performance (+-4 fps) no matter the setting , no matter the driver, 
both games ran well on older iGPUs Intel HD Graphics 630 (tested on laptop).

1. Start NMH1 or NMH2
2. Choice any settings in launcher
3.  Play 

---
#### Device / Platform [Optional][Recommended]

GPD WIN3

**Comment by IGCIT** [comment]
a user tested these on latest driver, performance fixed on 1191.
