### ISSUE TITLE
All current available drivers for Arc A770 set RGB range incorrectly / incorrect black levels

### ISSUE THREAD

**Issue by alexander-laiman** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#801]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows

### Processor / Processor Number [Required]

4790k

### Graphic Card [Required]

ASRock A770 16GB

### GPU Driver Version [Required]

31.0.101.5590

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[respot.txt](https://github.com/user-attachments/files/15934724/respot.txt)

### Description and steps to reproduce [Required]

Using any of the recent drivers on this card, with the card connected via hdmi to a display, produces incorrect black levels.
User with similar issue here: https://www.reddit.com/r/IntelArc/comments/1cwoqv6/colors_washed_out_on_secondary_monitor/
I tried all the intel graphics center type apps but I have no options to change the RGB range of the output, forcing me to instead set my display to limited thus reducing the effective image quality.

Please note this is not due to the HDMI connection, as when the driver is uninstalled and forced to fallback on windows, the black levels and colours are all displayed correctly. Also, older drivers did not have this issue as detailed in the above reddit post. Please fix! 

In my particular case I have an AVR between the pc and the display, so im not sure if the card is trying to set level based on what it thinks the display might support, but the AVR can support up to 4k HDR so either way the driver is having issues.

### Device / Platform

ASRock A770 16GB GPU

**Comment by Felipe-Intel** [comment]
Hello @alexander-laiman we recently posted driver [31.0.101.5592](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)
Could you please try this driver? Also, I wanted to ask you to try with your monitor connected directly to the Arc Card, and also please share the details of the monitor and the AVR.

**Comment by Felipe-Intel** [comment]
Hello @alexander-laiman we haven't hear from you so we are closing this ticket. If you still need help with this issue, please create a new ticket and mention this one.
