### ISSUE TITLE
Dungeons 4 missing highlights

### ISSUE THREAD

**Issue by UmbraAtrox** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#802]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Dungeons 4

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

12th Gen Intel(R) Core(TM) i5-12600K

### Graphic Card [Required]

Intel(R) Arc(TM) A750 Graphics

### GPU Driver Version [Required]

31.0.101.5590

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/15945773/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Recording https://www.youtube.com/watch?v=sW7y_Sy0Ef4

Start any map, hover mouse over digable area, observe tiles below mouse not highlighting. Click digable area, observe tile not highlighted.

Timestamp is how it should look like https://youtu.be/tQAw2ZI22Wc?t=522 

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

i tried every available setting on every option. 

It was working previously but seems to have broken with some driver in January. 
https://discord.com/channels/554824368740630529/1202298428462211162/1202298428462211162

**Comment by mujeeb-intel** [comment]
Hey @UmbraAtrox Do you still have issues with the latest graphics driver?

**Comment by mujeeb-intel** [comment]
The team has internally been working on this since we were able to reproduce the issue. Will let you know anything new I learn from the devs.

**Comment by UmbraAtrox** [comment]
> Hey @UmbraAtrox Do you still have issues with the latest graphics driver?

Yes, still the same behaviour with 32.0.101.5768.

**Comment by UmbraAtrox** [comment]
Still looks broken from here. https://youtu.be/Vs9ayrQxQ-Q

**Comment by mujeeb-intel** [comment]
Interesting. It seems to have been fixed for me. But re running it is now showing me the same issue. No worries. Im working with the engineers on this.

**Comment by UmbraAtrox** [comment]
32.0.101.6079 seems to have fixed this for me.
