### ISSUE TITLE
Scarlet Nexus | Red flashing during text based cutscenes

### ISSUE THREAD

**Issue by Xanonblade** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#803]
### Checklist [README]

- [x] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Scarlet Nexus

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5 13600K

### Graphic Card [Required]

Asrock PG Intel Arc A770 16GB

### GPU Driver Version [Required]

31.0.101.5590

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/15960826/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Steps: Just trigger any static cutscene like the one I show in the video. It can be early or late in the game, seems to happen regardless.
Video is being recorded using OBS but the issue still persists even if I don't have OBS active or open.
File is being attached in google drive because it's too large if I start from opening the game in windows to the fastest point for me to reach the issue.
https://drive.google.com/file/d/1AWD8-Qs6GPwH8CsrdO9Q7Ujba8RNdu5a/view?usp=sharing
Timestamp 2:15 starts a text based cutscene, the bright red flashing is the issue here. The background should normally just be black with the smaller red lines.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Graphics settings:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116854916/e420b0b2-4239-4677-8204-0439b3b9bf8e)
Controller vs Keyboard doesn't matter since the issue happens with both
Brightness:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116854916/fb547c63-3343-48f6-9ad0-805a5162a94b)
General settings (probably don't matter much):
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116854916/aac003e7-27ae-40b2-940c-a0c021615a3d)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/116854916/844c1666-07ec-4a1a-bcd1-0e6b80d1d19b)

### Device / Platform name

Asrock Z690 PG Velocita

### Crash dumps [Required, if applicable]

Not applicable, game doesn't crash.

**Comment by Adrian-Intel** [comment]
@Xanonblade thank you for sending this. I will check on my end and will report my results here.

Adrian

**Comment by Xanonblade** [comment]
Thanks for the fast work!

**Comment by Xanonblade** [comment]
I tested with Arc driver 101.5971 and had none of the red flashing issues. Thanks to you for the support and the whole driver team for fixing the issue! :)
