### ISSUE TITLE
Team Fortress 2 Gives a Black Screen when ran on the current driver.

### ISSUE THREAD

**Issue by yurienjoyerdeluxe** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#804]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Team Fortress 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

12th Gen Intel(R) Core(TM) i7-1255U 1.70 GHz

### Graphic Card [Required]

Intel Iris Xe

### GPU Driver Version [Required]

31.0.101.5590

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/15962009/igcit_ssu.txt)

### Description and steps to reproduce [Required]

When launching the game, it gives a black screen whenever it is ran in dxlevel 90 or vulkan.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/172859241/f14522bf-4d39-40e2-b700-7a30c559eaa1
Vulkan Footage. It shows the FPS counter, but thats it.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/172859241/742848f9-e6e4-435a-b876-06a1f19d1bab
DirectX 9 Footage. Doesnt even show the FPS counter, just a simple blank screen and thats it.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/172859241/0f348a11-f844-4877-b6b2-4c1c27569355

DirectX 8.1 Footage. It "loads", but nothing happens. So I decide to hold down my laptop's power button, and it causes it to finally reach the menu, but with awful screen tearing akin to when a monitor is running on a refresh rate it cant run with. Not an issue with the monitor at all. It doesnt show here because the OBS recording switches to the primary laptop monitor.

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1024x576

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

cfgver "1"
unbindall
bind "0" "slot10"
bind "1" "slot1"
bind "2" "slot2"
bind "3" "slot3"
bind "4" "slot4"
bind "5" "slot5"
bind "6" "slot6"
bind "7" "slot7"
bind "8" "slot8"
bind "9" "slot9"
bind "a" "+moveleft"
bind "b" "lastdisguise"
bind "c" "+duck"
bind "d" "+moveright"
bind "e" "+helpme"
bind "f" "+inspect"
bind "g" "+taunt"
bind "h" "+use_action_slot_item"
bind "i" "+lookup"
bind "j" "cl_trigger_first_notification"
bind "k" "+lookdown"
bind "l" "dropitem"
bind "m" "open_charinfo_direct"
bind "n" "open_charinfo_backpack"
bind "o" "say_party"
bind "q" "lastinv"
bind "r" "+reload"
bind "s" "+back"
bind "t" "impulse 201"
bind "u" "say_team"
bind "v" "+voicerecord"
bind "w" "+forward"
bind "x" "voice_menu_2"
bind "y" "say"
bind "z" "voice_menu_1"
bind "[" "cl_decline_first_notification"
bind "'" "+moveup"
bind "`" "toggleconsole"
bind "," "changeclass"
bind "." "changeteam"
bind "/" "+movedown"
bind "-" "disguiseteam"
bind "ENTER" "+quickswitch"
bind "SPACE" "+jump"
bind "BACKSPACE" "kill"
bind "TAB" "+showscores"
bind "ESCAPE" "cancelselect"
bind "INS" "+klook"
bind "END" "centerview"
bind "PAUSE" "pause"
bind "ALT" "+strafe"
bind "F1" "+showroundinfo"
bind "F2" "show_quest_log"
bind "F3" "show_matchmaking"
bind "F5" "screenshot"
bind "F6" "save_replay"
bind "F7" "abuse_report_queue"
bind "F9" "vr_toggle"
bind "F10" "quit prompt"
bind "F11" "vr_reset_home_pos"
bind "F12" "replay_togglereplaytips"
bind "MOUSE1" "+attack"
bind "MOUSE2" "+attack2"
bind "MOUSE3" "+attack3"
bind "MWHEELUP" "invprev"
bind "MWHEELDOWN" "invnext"
cl_interp_ratio "1"
r_drawtracers_firstperson "0"
hud_achievement_description "0"
hud_achievement_count "0"
cl_chatfilter_version "1"
joy_pitchsensitivity "1.640000"
joy_yawsensitivity "-1.550000"
m_pitch "0.022000"
sensitivity "5.710000"
m_customaccel "3"
m_customaccel_exponent "1.050000"
m_rawinput_onetime_reset "1"
viewmodel_fov "70.000000"
mat_viewportscale "1"
mat_software_aa_strength "0"
mat_software_aa_strength_vgui "0"
pyro_vignette "0"
pyro_dof "0"
hud_fastswitch "1"
tf_explanations_backpackpanel "1"
tf_backpack_page_button_delay ".25"
cl_notifications_move_time ".1"
tf_time_loading_item_panels ".0005"
tf_store_stamp_donation_add_timestamp "1658887761"
hud_classautokill "0"
cl_spec_mode "5"
cl_disablehtmlmotd "1"
sixense_sensitivity_level "2"
sixense_aim_freeaim_heading_multiplier "1.750000"
sixense_aim_freeaim_pitch_multiplier "1.750000"
sixense_aim_freeaim_dead_zone_radius "0.000000"
sixense_aim_freeaim_accel_band_size "15"
sixense_aim_freeaim_max_speed "12.000000"
sixense_aim_1to1_pitch_multiplier "3.000000"
sixense_feet_angles_offset_stick_spin_horiz_multiplier "7.500000"
sixense_feet_angles_offset_stick_spin_vert_multiplier "4.500000"
cl_spraydisable "0"
muzzleflash_light "0"
cl_autorezoom "0"
sb_dontshow_maxplayer_warning "1"
tf_inspect_hint_count "11"
fov_desired "90"
cl_hud_minmode "1"
ds_min_streak "4.000000"
ds_kill_delay "15.000000"
ds_notify "2"
tf_particles_disable_weather "1"
hud_combattext_batching "1"
hud_combattext_red "255.000000"
hud_combattext_green "1.000000"
hud_combattext_blue "1.000000"
tf_dingalingaling "1"
tf_dingaling_volume "0.730000"
tf_dingaling_pitchmindmg "101.650002"
tf_dingaling_pitchmaxdmg "137.240005"
tf_dingalingaling_lasthit "1"
tf_dingaling_lasthit_volume "0.960000"
tf_dingaling_lasthit_pitchmindmg "128.389999"
tf_dingaling_lasthit_pitchmaxdmg "118.949997"
tf_dingalingaling_repeat_delay ".001"
tf_dingalingaling_effect "4"
tf_dingalingaling_last_effect "1"
hud_achievement_count_engineer "0"
cl_crosshair_red "133.869995"
cl_crosshair_green "0.000000"
cl_crosshair_blue "206.119995"
cl_crosshair_file "crosshair5"
cl_crosshair_scale "34.480000"
cl_hud_killstreak_display_time "2"
cl_hud_killstreak_display_alpha "255"
tf_find_a_match_hint_viewed "1"
tf_training_has_prompted_for_training "2"
tf_training_has_prompted_for_offline_practice "1"
tf_training_has_prompted_for_forums "1"
tf_training_has_prompted_for_options "1"
tf_training_has_prompted_for_loadout "1"
cl_mainmenu_operation_motd_start "2018-10-14 23:40:05"
cl_promotional_codes_button_show "0"
tf_last_store_pricesheet_version "1259"
cl_mvm_wave_status_visible_during_wave "1"
tf_simple_disguise_menu "0"
tf_hud_notification_show_count_kart_controls "1"
tf_hud_notification_show_count_ghost_controls "1"
tf_hud_notification_show_count_ghost_controls_no_respawn "2"
tf_hud_show_servertimelimit "1"
cl_hud_playerclass_playermodel_showed_confirm_dialog "1"
tf_spec_xray_disable "1"
tf_enable_glows_after_respawn "0"
tf_hud_target_id_alpha "255.000000"
tf_hud_target_id_show_avatars "0"
tf_item_inspect_model_auto_spin "0"
tf_colorblindassist "1"
tf_use_min_viewmodels "1"
tf_mm_custom_ping_enabled "1"
tf_mm_custom_ping "59.930000"
tf_party_join_request_mode "1"
tf_mvm_tabs_discovered "3"
tf_explanations_charinfopanel "1"
tf_show_preset_explanation_in_class_loadout "0"
tf_show_taunt_explanation_in_class_loadout "0"
tf_show_maps_details_explanation_count "0"
tf_mvm_classupgradehelpcount "3"
tf_scoreboard_mouse_mode "1"
tf_scoreboard_ping_as_text "1"
tf_casual_welcome_hide "1"
tf_comp_welcome_hide "1"
tf_dashboard_slide_time "0"
tf_matchmaking_ticket_help "1"
tf_quest_map_intro_viewed "1"
tf_medigun_autoheal "1"
hud_medicautocallersthreshold "75.000000"
hud_medichealtargetmarker "1"
tf_sniper_fullcharge_bell "1"
tf_explanations_discardpanel "1"
tf_explanations_store "1"
sv_skyname "sky_upward"
snd_surround_speakers "2"
volume "0.770000"
snd_musicvolume "0.000000"
snd_mixahead ".05"
voice_scale "1.000000"
name "Yuri Enjoyer Deluxe #YuriTF2"
sv_unlockedchapters "99"
cl_timeout "60"
cl_logofile "materials/vgui/logos/spray.vtf"
mat_colorcorrection "1"
con_enable "1"
r_eyemove "0"
r_ambientboost "0"
mp_decals "9.000000"
bugreporter_uploadasync "1"
rate "786432"
cl_cmdrate "66"
cl_updaterate "66"
closecaption "1"
net_maxroutable "576.000000"
engine_no_focus_sleep "1"
r_rootlod "1"
mat_picmip "2"
mat_monitorgamma "1.600000"
mat_antialias "1"
r_shadowrendertotexture "1"
r_waterforceexpensive "1"
mat_managedtextures "0"
mat_hdr_level "0"

### Device / Platform name

Inspiron 14 7420 2-in-1

**Comment by yurienjoyerdeluxe** [comment]
Update: New Driver, 31.0.101.5592 has released today. It now works on Vulkan, but the issues that occur when running in DirectX 9 and DirectX 8.1 in TF2 still occur despite this update.

**Comment by Vivek-Intel** [comment]
@yurienjoyerdeluxe thanks for reporting the issue. is it happening on previous drivers as well?
can you share exact launch code for DX9 that you are trying to play with and check if it happens in both full screen and windowed mode.

**Comment by yurienjoyerdeluxe** [comment]
> @yurienjoyerdeluxe thanks for reporting the issue. is it happening on previous drivers as well? can you share exact launch code for DX9 that you are trying to play with and check if it happens in both full screen and windowed mode.

This only happened on 31.0.101.5590 and 31.0.101.5592. The driver before those worked just fine. 31.0.101.5592 somewhat works with Vulkan, but in of itself freezes after enough time, but thats been an issue since the 64 bit implementation of TF2 earlier this year, so unlikely thats related.   

I will attempt to run it in windowed mode and see what happens, as all the issues I mentioned do occur in fullscreen mode.

**Comment by yurienjoyerdeluxe** [comment]
@Vivek-Intel Update: 


https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/172859241/056a7b3b-980f-43a4-8f09-3a0ab4611ce3


Ran the game on DX9, mostly same settings, but in windowed instead of fullscreen  (as seen in the Steam Properties tab in the video) and this is what I got. It works. 

This makes me wonder if something else is at play then if windowed works just fine?

**Comment by yurienjoyerdeluxe** [comment]
Edit: I think I found what caused the black screen.



https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/172859241/b9842846-2c91-49f2-a723-2b45aa56818d


Above is DX9 running in fullscreen, but I simply removed the check for "Disable Fullscreen Optimizations". Nothing else has changed otherwise. It works perfectly fine now. So the issue at hand seems to be whenever I disable fullscreen optimizations.

**Comment by yurienjoyerdeluxe** [comment]
Also while this issue is still open (not sure im allowed to mention this, but it is related to TF2): Ive been having constant random freezes with TF2 regardless of what renderer I run it on. No explanable phenomenon, it just randomly freezes when im playing with 0 explainable reason, and im forced to close it.

I hope they look into that as well for the next driver @Vivek-Intel

**Comment by Vivek-Intel** [comment]
@yurienjoyerdeluxe thank you for sharing details. please allow us some time to simulate this issue internally. we will get back to you

**Comment by Vivek-Intel** [comment]
Hi @yurienjoyerdeluxe 
we have submitted the issue to our engineering team, you can continue to use either Vulkan API or disable Fullscreen optimization checkbox to bypass the issue and also please know that we can not commit any estimated time to get the issue fixed but we will update you if there is any news on this issue.

**Comment by Vivek-Intel** [comment]
internal bug id for your reference only - 15016408207

**Comment by yurienjoyerdeluxe** [comment]
@Vivek-Intel Using the current driver, 
32.0.101.5762 (Latest), and the blackscreen issue still persists when playing TF2 in fullscreen while using "Disable FullScreen Optimizations", but since about 
31.0.101.5594 or so, the game runs perfectly fine with no crashes of any kind, still has the issue of not being able to run with "Disable Fullscreen Optimizations" checked in Properties however.

Just letting you know.

**Comment by Vivek-Intel** [comment]
Hi @yurienjoyerdeluxe can you verify this issue with latest driver [101.5768](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)

**Comment by yurienjoyerdeluxe** [comment]
> Hi @yurienjoyerdeluxe can you verify this issue with latest driver [101.5768](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)

@Vivek-Intel Can verify it still persists with this driver. Ran the game fullscreen, with fullscreen optimizations disabled (which was the root cause for the black screen) and it still gives me the black screen when I run the game under those parameters. No sound or anything either, so not sure if it even loads anything when fullscreen optimizations are turned off.

So have to say the issue is still not resolved as of yet. May test the other dx modes and see what happens, but as it stands, its still an issue.

**Comment by Vivek-Intel** [comment]
Issue is fixed with latest driver [101.6130](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) . Please verify it.

**Comment by yurienjoyerdeluxe** [comment]
> Issue is fixed with latest driver [101.6130](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) . Please verify it.

@Vivek-Intel Can confirm, the issue has now been resolved, regardless of dxlevel or vulkan being placed in properties, it now shows properly, as it should.

**Comment by Vivek-Intel** [comment]
Closing.
