### ISSUE TITLE
provide a public changelog for driver releases

### ISSUE THREAD

**Issue by Vipitis** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#805]
### Application [Required]

Intel Graphics Drivers

### Processor / Processor Number [Required]

n/a

### Graphic Card [Required]

Intel Arc

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [X] Windows 11 22H2
- [X] Windows 11 21H1
- [X] Windows 10 22H2
- [X] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Hey,

Every driver release comes with a release notes .pdf - but this only contains some release highlights and a very limited number of fixed/known issues. The driver package also includes other packages which rarely get release highlights mentioned in the notes. 
This is not a changelog. While I understand that not all changes can be stated (for example due to confidentiality agreements for unreleased games etc) - it would be helpful to have a list of all changes available.

Currently I have to run tests to see if my issues persist, find disclosed changes in issues in this repository, the Discord channels or the forum posts. Can you instead aggregate a (limited) changelog that is publicly facing. 
One example where this is already in place: the Linux graphics drivers https://dgpu-docs.intel.com/releases/index.html

**Comment by Gabriela-Intel** [comment]
Hey there @Vipitis ! I totally get where you're coming from. I can see why not having a fully comprehensive list of changes/fixes/known issues might be a pain. :/

I can't make any promises but I can make sure we pass along your requests to the right people.

**Comment by Gabriela-Intel** [comment]
@Vipitis Let's proceed with closing since this is considered a feature request where we cannot promise some sort of ETA. Thanks!
