### ISSUE TITLE
Hogwarts Legacy crash DXGI_ERROR_DRIVER_INTERNAL_ERROR

### ISSUE THREAD

**Issue by przkreft** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#806]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Hogwarts Legacy

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

R5 5600

### Graphic Card [Required]

Arc A750

### GPU Driver Version [Required]

31.0.101.5592

### Other GPU Driver version

Last good known: 31.0.101.5084

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[sysinfo.txt](https://github.com/user-attachments/files/16012230/sysinfo.txt)

### Description and steps to reproduce [Required]

Just open game on steam

Attaching crashlog from:
C:\Users\Przemo\AppData\Local\Hogwarts Legacy\Saved\Crashes\11566776413630403C3C43958B07F57D

	"ErrorMessage": "LowLevelFatalError [File:Unknown] [Line: 715] \nhr failed \n at W:/Engine/Source/Runtime/D3D12RHI/Private/Windows/WindowsD3D12PipelineState.cpp:1043 \n with error DXGI_ERROR_DEVICE_REMOVED with Reason: DXGI_ERROR_DRIVER_INTERNAL_ERROR\n\n\n\n",

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

doesn't apply

### Crash dumps [Required, if applicable]
[CrashUserData.json](https://github.com/user-attachments/files/16012257/CrashUserData.json)
_No response_

**Comment by przkreft** [comment]
cleanup of C:\ProgramData\Hogwarts Legacy helped

**Comment by IGCIT** [comment]
is the crash solved?

**Comment by Felipe-Intel** [comment]
I installed the game on a 12th gen + A770 system and had no problem. @przkreft please confirm if you are still seeing the crash. Thanks!

**Comment by przkreft** [comment]
Cleanup of shaders from  C:\ProgramData\Hogwarts Legacy helps to solve issue.
Still consumer can see issue when will try to run game without shader clean up after driver update.
My files before removal were as old as 2023

Potential steps to reproduce ->
First prepare clean environment (Uninstall Hogwarts Legacy + Clean up shaders C:\ProgramData\Hogwarts Legacy)

1. Install older intel arc driver 5084
2. Install game
3. Run game (compile shaders)
4. Update driver to latest one 5592
5. Run game (expected crash)

Workaround:
1. Remove files from C:\ProgramData\Hogwarts Legacy
2. Run again game (expected to run as expected and compile shaders correctly)

I'm not sure if we can say here about driver issue as cleanup of shaders was done from game ProgramData folder...

**Comment by Felipe-Intel** [comment]
hello @przkreft thanks for this great feedback. We will proceed to close this ticket and create a knowledge article with the shader clean suggestion.

**Comment by przkreft** [comment]
Thanks @Felipe-Intel, I'm glad that I could help.
