### ISSUE TITLE
Dead Island 2 keep crashing when entering the savegame

### ISSUE THREAD

**Issue by paulober** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#809]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Dead Island 2 

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X

### Graphic Card [Required]

Intel Arc A770 LE (16GB)

### GPU Driver Version [Required]

31.0.101.5592

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu-report-1.txt](https://github.com/user-attachments/files/16039469/ssu-report-1.txt)

### Description and steps to reproduce [Required]

After all intro cut-scenes and after selecting the character to play with the game crashed. Now if i want to enter the game it crashes after the press ... to enter dialog.
The game doesn't realy crash but the window goes in the background and i can't Alt-Tab into it or though any other method it stays hidden forever. But sometimes it also just crashes.

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

3440x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

- FOV: 80
- Motion Blur: 100
- Anti-aliasing: temp anti high
- VIew distance: high
- all high except textures: ultra
- AMD Fidelity FX super resolution 2: quality

### Device / Platform name

MSI B550M Pro-VDH WIFI

### Crash dumps [Required, if applicable]

No windows event log entry.
[DeadIsland.log](https://github.com/user-attachments/files/16039488/DeadIsland.log)

[UE4CC-Windows-0674FF55404CDC481F73F28F8EB7910C_0000.zip](https://github.com/user-attachments/files/16039502/UE4CC-Windows-0674FF55404CDC481F73F28F8EB7910C_0000.zip)

### Save game

[DeadIsland2SaveGame.bak.zip](https://github.com/user-attachments/files/16039471/DeadIsland2SaveGame.bak.zip)

**Comment by paulober** [comment]
I found the issue. It's FX super resolution 2 enabled. I got it working by using keyboard instead of controller and disabling fx super res then playing like 20 seconds > back to main menu > enabling super fx > back into game. But then it crashed again like before with running in the background an no option to enter after some seconds.
[UE4CC-Windows-623E8BCE407598C4CE9C75995909BC8E_0000.zip](https://github.com/user-attachments/files/16039518/UE4CC-Windows-623E8BCE407598C4CE9C75995909BC8E_0000.zip)

**Comment by Ilya-intel** [comment]
Hi @paulober ,
So, I've tried this game on 3 different machines (including similar to yours), and no issues were observed.
In the log file I noticed a vast number of issues related to GameInput service, this can be the reason of the game being minimized.
I'd advise you to fix those issues first to continue with further troubleshooting. There is a thread on Reddit, which can be helpful: https://www.reddit.com/r/WindowsHelp/comments/18bb6e0/gameinput_service_stops_working_after_windows_11/

**Comment by Ilya-intel** [comment]
Hey @paulober ,
Did you get a chance to check my previous message?

**Comment by paulober** [comment]
sorry for the delay. Ok, so yes if the game crashes it minimizes it self with no option to maximize again. At the moment i just play without FSR 2 which fixed the issue. Maybe the FSR 2 Intel ARC crash only happens in the first intro of the game.
As now if i activate it mid game i get some minor stutters but nothing big and no crash.
