### ISSUE TITLE
Escape From Tarkov crashes when pressing Play on any newer drivers than .5534

### ISSUE THREAD

**Issue by GottaSlay** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#811]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Escape From Tarkov

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

Battlestate Games

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3D

### Graphic Card [Required]

Acer Intel Arc A770 Predator BiFrost OC

### GPU Driver Version [Required]

31.0.101.5594

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

-

### Description and steps to reproduce [Required]

The game crashes upon pressing Play in the launcher. I cannot post the game settings as I cannot get into the game. 

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Cannot access the game settings as it keeps crashing upon pressing Play. 

### Crash dumps [Required, if applicable]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/deaf7b82-74fb-4a54-a9ba-05083d1ee90e)

**Comment by Zack-Intel** [comment]
Hi @GottaSlay 

Thank you for making this report. Interesting that it doesn't seem to happen when another game is going on.

Do you have any pop-ups from battleye when launching the game?

**Comment by GottaSlay** [comment]
No pop-ups from battleye. For some reason the game is just very inconsistent with launching since driver .5534.

**Comment by Zack-Intel** [comment]
Thanks @GottaSlay 

Can you clarify what you mean by the game being inconsistent? I know the work around was mentioned, but for clarity and testing, it'll be helpful to know how often the crashing happens when launching

**Comment by GottaSlay** [comment]
The crashing happens more often than not. It rarely launches correctly by itself.

**Comment by GottaSlay** [comment]
According to Event Viewer the Exception code for Tarkov's crashing is: 0xc0000409

**Comment by Zack-Intel** [comment]
Hi @GottaSlay 

After some tests, I still don't seem to see the issue, but the event viewer exception code does seem related to the software itself. I would double check that the files of the game aren't corrupted and potentially reinstall the game/launcher, check for windows updates, double check firewall exceptions, and check the GPU load when you try to open the game.

Additionally, I know you mentioned that overclocking isn't being done, but RAM might be another component to double check for overclocking/overuse.

**Comment by Zack-Intel** [comment]
Hi @GottaSlay 

I wanted to follow up to see if you had a chance to try any of the suggestions provided or had more details regarding the issue.

**Comment by GottaSlay** [comment]
I haven't managed to find a solution to the issue regardless of trying out your recommended fixes. I suppose the issue can be closed since the game seems to work fine for other Arc users.

**Comment by Zack-Intel** [comment]
Thank you for the update, @GottaSlay. I'm sorry the game still isn't working for you.

If you're able to get more detailed information or find other people with the same issue, feel free to open a new case and link to this one and we will continue where we left off.
