### ISSUE TITLE
Windows 11 update always rolls back Intel iGPU drivers after manual driver update through Intel driver setup

### ISSUE THREAD

**Issue by makedir** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#812]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows

### Processor / Processor Number [Required]

N100

### Graphic Card [Required]

N100

### GPU Driver Version [Required]

31.0.101.5594

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/user-attachments/files/16089744/ssu.txt)

### Description and steps to reproduce [Required]

Update iGPU drivers. Next reboot Windows 11 update will download older drivers and rollback.

Tried the following workarounds, none are working:

https://www.elevenforum.com/t/enable-or-disable-include-drivers-with-windows-updates-in-windows-11.2232/

Solution as Option 2, does not work for Home edition.

https://www.intel.com/content/www/us/en/support/articles/000087834/graphics.html

Solution to make non clean intall in this post does not help.

Problem exists only in Windows 11 Home edition, if you have Windows 11 Pro, you can use gpedit to disable driver updates through Windows update.

Suggestions:

Please communicate with Microsoft to find a solution to this issue. Either make all driver updates optional, and user can decide which are installed. Or give an optional toggle button to disable drivers in Windows 11 settings, or/better, give more in detail options, for example to exclude GPU driver updates through Windows update, or give option, that newer installed drivers are never rolledback, also optional.

Only working workaround, is that you need to go into device manager after Windows 11 update rolled back, then go to Intel iGPU, and select, use last worked driver. Windows will now keep the driver and wont rollback, until you update again manually the driver. I had this issue now several times after I installed 5594, 5593. Maybe because these are not WHQL certified.

**Comment by IGCIT** [comment]
hi @makedir,

this is a widespread issue with how Windows handle updates when OEM drivers are available in their repos, removing user installed drivers with no prompt, and, in many cases, breaking stuff while doing so.

you should probably open a ticket to MS for this, not intel drivers related per se.

the solutions you have tried, are all wrong for this kind of issue, online many still don't know how to properly stop this behaviour so you usually find ineffective solutions.


the correct steps:

download this tool [wushowhide.zip](https://github.com/user-attachments/files/16090476/wushowhide.zip) (an old windows tool to enable/disable updates in windows update, still working as of today)

1 - run windows update and let windows downgrade your drivers (if you installed the new one and update is already pending)
2 - disconnect from internet
3 - install the new drivers (you may also want use DDU to clear any old drivers)
4 - reboot
6 - reconnect
7 - run the wushowhide tool and select "hide updates" and wait for it to grab the updates available for your device
8 - you should see the OEM drivers, select and hide the update

once done, windows will ignore OEM drivers, from personal experience, even if the OEM pushes a new driver

**Comment by makedir** [comment]
@IGCIT Yes, I know this is an issue since years in Windows. Me making a ticket at MS wont do or change anything. I am not intel. Obviously Intel could easily get someone at MS on the phone or other communication ways and easily solve this is in minutes. When Intel tells MS this is an issue, obviously MS is more open to change this. As a "nobody" it is kinda impossible to report issues to MS.

**Comment by EstebanIntel** [comment]
Hi @makedir,

We have communicated this issue to Microsoft, so they are aware of it. This is a change that needs to be done on the OS side, not on the driver side. So please raise the ticket to Microsoft.

**Comment by ValeZAA** [comment]
>removing user installed drivers with no prompt

Nope, drivers remain in the system, you can check that with Device manager --> your GPU, update driver, find drivers on this computer, select from already installed drivers, and a newer driver will be there. If you press the button to install it Windows will not revert it, and will not ask to install the old driver. Instead you will have revert button in device manager.

What is a funny bug is that, why are there two driver with the same version:

![image](https://github.com/user-attachments/assets/ac779dcf-1bba-4dfd-9830-b81d3fe6d273)

**Comment by jdrch** [comment]
Has anyone tried @IGCIT's [method](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/812#issuecomment-2207208973) on Windows 11 24H2?

**Comment by jdrch** [comment]
> > Has anyone tried [@IGCIT](https://github.com/IGCIT)'s [method](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/812#issuecomment-2207208973) on Windows 11 24H2? I have this exact same problem on my HP Envy 17.
> 
> Yes, it works fine. Can you also hide old CPU iGPU drivers.

I tried it and couldn't get it to work. Ultimately I decided to stick with the Windows Update driver, as a future Windows Update might just KO the workaround anyway (as frequently happens), and the Windows Update driver isn't giving me any trouble.
