### ISSUE TITLE
Intel i7-14650HX+Intel® UHD Graphics for 14th Gen Intel® Processors STUTTER

### ISSUE THREAD

**Issue by benjaminmorozov** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#813]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

All of Windows

### Processor / Processor Number [Required]

Intel i7-14650HX

### Graphic Card [Required]

Intel® UHD Graphics for 14th Gen Intel® Processors

### GPU Driver Version [Required]

31.0.101.5594

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/user-attachments/files/16101515/ssu.txt)

### Description and steps to reproduce [Required]

I am currently experiencing stutter issues when running Windows on the iGPU. Stutters appear whenever I open the start menu, control center, chrome, discord, scroll reddit or just move windows around. These stutter disappear when I switch to the dGPU or when I uninstall the iGPU driver and switch to the Microsoft Basic Display Adapter.

Replication - The stutters can be reproduced by:
1. minimizing, maximizing or moving windows around
2. opening Windows UI (start menu, control center, notification center)
3. opening chromium apps (chrome, spotify, discord, scrolling youtube)
<img width="946" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/33388822/5c793ba1-945b-4098-b87f-7b9a14fe65cf">

LatencyMon identifies the dxgkrnl.sys driver as the source of these stutters/latency issues, which typically last ~1200μs (as shown in the attached picture).

### Device / Platform

Lenovo Legion 5i 16IRX9

**Comment by Gabriela-Intel** [comment]
@benjaminmorozov We're working on getting a hold of a similar system so we can take a look at the issue. We'll get back to you once we have the system.

**Comment by Gabriela-Intel** [comment]
Hey @benjaminmorozov just wanted to check in to ask how exactly you are setting Windows to run on the igpu instead of the dgpu?

**Comment by benjaminmorozov** [comment]
Hi, the official Lenovo Vantage tool (made for the laptop) allows me to switch between three modes - Hybrid (igpu+dgpu), igpu only and dgpu only. The BIOS allows for the exact same graphics device switching too. The stutters disappear only when in dgpu only mode or when running games on the dgpu.

**Comment by Gabriela-Intel** [comment]
I'm not seeing any significant stutters on my end. Any chance you can capture a video of the stutters?

**Comment by benjaminmorozov** [comment]
Hi, I'm sorry but I don't think I'll be able to catch any of these stutters on video myself seeing as they're not very predictable. They're the exact same as these from a different user despite him running a different gpu, however:
[video1](https://www.youtube.com/watch?v=fSN5a5k-2k8)
[video2](https://www.youtube.com/watch?v=BGvH53GvaGo)
The system basically hangs for a small time until it unfreezes again. This happens in the exact same scenarios as captured by the users - moving windows and opening the control center, and additionally when minimizing and maximizing windows, opening the start menu, scrolling the youtube home page feed (most reproducible there - basically the exact same kind of stutter everytime the next part of feed starts loading). Graphically intensive websites also cause stutters, such as this website (excuse the different language please) - [Telekom Slovakia Parallax + 3D](https://eshop.telekom.sk/category/all-devices/list/product_listing/product/iPhone-15-Pro) - when scrolling up and down a few times.
Hope this helps - if not, I'll be sure to try and capture the stutters as soon as possible.

**Comment by Gabriela-Intel** [comment]
How often do you see the stutters?

I do see a higher value for highest reported DPC execution time when using hybrid mode than when using dgpu only, but I'm still not observing visible stutters when scrolling through reddit, maximizing/minimizing windows, or when scrolling through youtube. I also tried the link you provided but still no visible stutters.

Did you already try using [DDU ](https://www.guru3d.com/download/display-driver-uninstaller-download/)on for both the igpu and dgpu?

**Comment by benjaminmorozov** [comment]
Hi, I've had some new development for my issue:
I've practically fixed the high DPC latency issue by installing the latest drivers from the respective manufacturers (instead of the ones from the OEM). The highest reported DPC execution time is now 500 microseconds at most and caused by a completely different driver, so that's amazing.

![image](https://github.com/user-attachments/assets/1f3de338-2974-47bd-bc82-784c832127ce)

After switching to Windows 11 **Insider**, the issue with windows apps (settings, store), moving/minimizing/maximizing windows, opening the control center/start/notification area seems to be practically fixed or rather diminished to a state where stutters occur very rarely.
They now occur only in chromium-based apps and browsers. Firefox gives me an incredibly smooth experience on all websites whereas Chrome seems to have hickups whenever new content (on youtube/reddit/facebook/insert any dynamic website) is being fetched at least once every minute or so.
I feel like that is not the issue of the Intel iGPU drivers anymore but rather chromium being... ineffective and unoptimized.
I would thus like to thank you for your amazing help and I'm sorry that I wasted your time given that the issue is probably not caused by iGPU drivers.

**Comment by Gabriela-Intel** [comment]
Glad to hear that! No worries - thank you so much for taking the time to investigate to figure out what's happening. Appreciate you for following up here to let me know. :)

I'll go ahead and marked this as closed then.
