### ISSUE TITLE
final fantasy xv flickering sometimes freezing

### ISSUE THREAD

**Issue by papandbuddyg** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#814]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Final Fantasy XV

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

ryzen 5 3600

### Graphic Card [Required]

Intel Arc A580

### GPU Driver Version [Required]

31.0.101.5594

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[system 2.txt](https://github.com/user-attachments/files/16104856/system.2.txt)

### Description and steps to reproduce [Required]

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/107985226/6f367ab6-edb9-44e5-944d-fa22c3dbce74

heres a video of the issue im having and sometimes the game will do that then freeze up completely but not crash

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920 x 1440p

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

1440p highest settings

### Device / Platform name

Deskop-K8UIJRPO

### Save game

sadly no way of getting save file for this game

**Comment by papandbuddyg** [comment]
this happens during combat normally but i cant seem to find someone who has the same issue so ima report it incase

**Comment by papandbuddyg** [comment]
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/107985226/fa8dbc52-7907-45af-bb02-1f30f878690d)
 heres a picture when it freezes

**Comment by papandbuddyg** [comment]
this happens during combat typically and i tried using both vulkan and dx11 as well as  vsync off and on

**Comment by IGCIT** [comment]
freezes are known issue, see #638

**Comment by papandbuddyg** [comment]
well then glad its reported xd
