### ISSUE TITLE
Zenless Zone Zero Crashed on Intel iGPU

### ISSUE THREAD

**Issue by ShadowyLycan990** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#816]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Zenless Zone Zero

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

HoYoPlay

### Processor / Processor Number [Required]

i3-8130U

### GPU Driver Version [Required]

31.0.101.2128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/16115582/igcit_ssu.txt)

### Description and steps to reproduce [Required]

**Description**
Immediately crashed after the splash screen.

**How to reproduce this issue?**
1. Launch HoYoPlay (assuming you already downloaded the game)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92839483/c3740e62-3f6c-4160-a25e-4dd133e2ad4d)
2. Press Start Game
3. The game launched
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92839483/a9b4c921-3488-4d81-8f27-6efbc1f07d07)
4. The game crashed after the splash screen.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92839483/83a747e1-fadb-4771-9e69-cae1961cc25e)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080, 1280x720

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

I cannot access it because the game crashed after splash screen.

### Device / Platform name

Acer TravelMate TX40-G3-M (non-Nvidia version)/Win32

### Crash dumps [Required, if applicable]

[Crash_2024-07-06_095643596.zip](https://github.com/user-attachments/files/16115608/Crash_2024-07-06_095643596.zip)

**Comment by BiZkViT96** [comment]
Your CPU is too old. If there is no newer driver available, you are out of luck.

Driver 101.3222 (July 28th, 2022)

Intel will be moving 6th - 10th Gen Intel Processor Graphics and related Intel Atom, Pentium, and Celeron processor graphics to a legacy software support model.

**Comment by ShadowyLycan990** [comment]
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/92839483/fa9d9bf7-a9f7-4267-9d1a-78bcd44ce078)
I used this version.
The latest one.

**Comment by ShadowyLycan990** [comment]
If there's no way that means I should replace my device? Damn, laptops and PCs here are expensive in my country. Both AMD and Intel laptops are expensive, thanks to AI farms + inflation.

**Comment by BiZkViT96** [comment]
Wait for official response from support. But don't be surprised if they repeat what I said previously.

**Comment by ShadowyLycan990** [comment]
Okay...
I hope they will do it.

**Comment by ShadowyLycan990** [comment]
All Intel GPU series are facing the similar issues including the Intel Arc and Iris Xe series too, affecting all Intel GPUs. Not only integrated GPU.

**Comment by ShadowyLycan990** [comment]
Any progresses about the investigations? Intel driver team?

**Comment by EstebanIntel** [comment]
Hi @ShadowyLycan990,

As mentioned by @BiZkViT96, your iGPU has been moved to a legacy support model, as described in the article: [Graphics Driver Support Update for 10th Generation and Older Intel Processor Graphics](https://www.intel.com/content/www/us/en/support/articles/000091662/graphics.html).

On the crashing issue on Zenless Zone Zero, we are aware of the crash and fix was added to the drivers for 11th gen or newer GPUs. Unfortunately, due to the drivers for 10th gen and older iGPUs been moved to a legacy support model, this fix won't be available for these older iGPUs.
