### ISSUE TITLE
Grand Theft Auto 5 FiveM performance issues

### ISSUE THREAD

**Issue by GottaSlay** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#818]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Grand Theft Auto 5 FiveM 

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

FiveM

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3D

### Graphic Card [Required]

Acer Intel Arc A770 Predator BiFrost OC

### GPU Driver Version [Required]

Other (Please specify)

### Other GPU Driver version

32.0.101.5762 Non-WHQ

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

-

### Description and steps to reproduce [Required]

Launch any server via the FiveM launcher and load into the game: 
Game settings:
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/c7db37da-27bd-4196-828d-1b2820d38e68)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/8177b742-85a1-49d2-9551-45245b86ca84)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/6be0099c-e921-44b1-99fc-efc9e132a860)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/43540181/37989a3e-b88a-4f1c-bf15-1db04196d76f)

The FPS is far less than expected and the GPU usage hovers at around 50%.

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

I've shared the settings above.

**Comment by Felipe-Intel** [comment]
Hello @GottaSlay 
I understand this is a mod for GTA V. Please create a CapframeX capture during your gameplay (5 to 10 minutes) to compare it with a run in my lab system with an unmodded instance of the game. More so, if it is possible for you to test the game without mods in your system it would be great, so we can rule out this mods are affecting the performance of the game. Please also share the configuration file along with the captures so we can use the same values. This file should be located in _C:\Users\<your_user_name>\Documents\Rockstar Games\GTA V\Settings.xml_ (C: or the driver where your game is installed). Also attach the SSU report of your system.

**Comment by GottaSlay** [comment]
Hey! It is indeed a mod but also a multiplayer mod with a large userbase. I'll get back to you with the SSU report and a CapframeX capture.

**Comment by Felipe-Intel** [comment]
@GottaSlay any luck with the capture? In the non-moded GTA-V (story mode, father/son mission) I see around between around 96 FPS average during the mission. 

Use the following graphics config (not sure if the settings file is in the same location for your game version)

Open C:\users\<user>\Documents\Rockstar Games\settings.xml 
Replace the according sections with the following configuration and save the file. 


_<graphics>

    <Tessellation value="3" />

    <LodScale value="1.000000" />

    <PedLodBias value="0.000000" />

    <VehicleLodBias value="0.000000" />

    <ShadowQuality value="3" />

    <ReflectionQuality value="3" />

    <ReflectionMSAA value="8" />

    <SSAO value="2" />

    <AnisotropicFiltering value="16" />

    <MSAA value="0" />

    <MSAAFragments value="0" />

    <MSAAQuality value="0" />

    <SamplingMode value="0" />

    <TextureQuality value="2" />

    <ParticleQuality value="2" />

    <WaterQuality value="2" />

    <GrassQuality value="1" />

    <ShaderQuality value="2" />

    <Shadow_SoftShadows value="4" />

    <UltraShadows_Enabled value="true" />

    <Shadow_ParticleShadows value="false" />

    <Shadow_Distance value="1.000000" />

    <Shadow_LongShadows value="true" />

    <Shadow_SplitZStart value="0.930000" />

    <Shadow_SplitZEnd value="0.890000" />

    <Shadow_aircraftExpWeight value="0.990000" />

    <Shadow_DisableScreenSizeCheck value="false" />

    <Reflection_MipBlur value="true" />

    <FXAA_Enabled value="true" />

    <TXAA_Enabled value="false" />

    <Lighting_FogVolumes value="true" />

    <Shader_SSA value="true" />

    <DX_Version value="2" />

    <CityDensity value="1.000000" />

    <PedVarietyMultiplier value="1.000000" />

    <VehicleVarietyMultiplier value="1.000000" />

    <PostFX value="1" />

    <DoF value="false" />

    <HdStreamingInFlight value="true" />

    <MaxLodScale value="1.000000" />

    <MotionBlurStrength value="0.000000" />

  </graphics>

  <system>

    <numBytesPerReplayBlock value="9000000" />

    <numReplayBlocks value="30" />

    <maxSizeOfStreamingReplay value="1024" />

    <maxFileStoreSize value="65536" />

  </system>

  <audio>

    <Audio3d value="false" />

  </audio>

  <video>

    <AdapterIndex value="0" />

    <OutputIndex value="0" />

    <ScreenWidth value="1920" />

    <ScreenHeight value="1080" />

    <RefreshRate value="119" />

    <Windowed value="2" />

    <VSync value="0" />

    <Stereo value="0" />

    <Convergence value="0.100000" />

    <Separation value="1.000000" />

    <PauseOnFocusLoss value="0" />

    <AspectRatio value="5" />

  </video>_

**Comment by GottaSlay** [comment]
Hey. Unfortunately I've been busy and haven't had the time to get the capture quite yet.

**Comment by Felipe-Intel** [comment]
Noted. Please submit your result when you have the chance.

**Comment by Felipe-Intel** [comment]
@GottaSlay following up with the request. If for any reason you are unable to provide the information, we can close this ticket and you may open a new one later.

**Comment by GottaSlay** [comment]
Hello, the ticket can be closed yes.
