### ISSUE TITLE
Wuthering Waves not loading environment textures properly in the new regions

### ISSUE THREAD

**Issue by ArifJawad243** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#819]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Wuthering Waves

### Processor / Processor Number [Required]

Ryzen 7 5700x

### Graphic Card [Required]

Arc A770 LE

### GPU Driver Version [Required]

31.0.101.5592

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build [Required]

Windows 11 22H2

### Intel System Support Utility report

[log.txt](https://github.com/user-attachments/files/16183010/log.txt)

### Description and steps to reproduce [Required]

The textures in the new region added in the latest update won't load. 
Video- https://drive.google.com/file/d/1qup10LH3ajVm24NlLNRyND0E2N0GvZjV/view?usp=sharing

**Comment by Ilya-intel** [comment]
Hi @ArifJawad243 ,
Any ways to get to these locations when starting the game from 0?

**Comment by ArifJawad243** [comment]
> Hi @ArifJawad243 , Any ways to get to these locations when starting the game from 0?

No, you have to be at a fairly high level to unlock it.

**Comment by Ilya-intel** [comment]
@ArifJawad243 
Quick update: I'm still playing this game trying to get to this end-game content.
