### ISSUE TITLE
Intel ARC Control resets the system level color profile

### ISSUE THREAD

**Issue by goldenx86** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#820]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel ARC Control

### Processor / Processor Number [Required]

i5 1240P

### Graphic Card [Required]

Iris Xe

### GPU Driver Version [Required]

32.0.101.5762

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build [Required]

Windows 11 23H2

### Other Windows build

At least 23H2 and 24H2

### Intel System Support Utility report

[intel.txt](https://github.com/user-attachments/files/16200458/intel.txt)

### Description and steps to reproduce [Required]

If a system-wide color profile is configured, opening Intel ARC Control resets it back to sRGB, making some monitors display wrong colors. The only way to revert this on 23H2 is to disable ARC Control from startup and log off. 24H2 solves it by opening the color profile settings.

Tested system is an ASUS Vivobook X1502ZA, i5 1240P, Iris Xe. Both Windows 11 23H2 and 24H2 are affected.
I'm attaching the profile my display needs as an example.
[X1502ZA_8086_E5090903.zip](https://github.com/user-attachments/files/16200456/X1502ZA_8086_E5090903.zip)

### Device / Platform

Asus Vivobook X1502ZA

**Comment by goldenx86** [comment]
Before opening ARC Control:
![20240712_224025](https://github.com/user-attachments/assets/30d1d1c4-c1af-4e60-81f7-8a08435df2d5)

After opening ARC Control:
![20240712_224033](https://github.com/user-attachments/assets/b0d7ad62-604b-431b-8dfa-b1828300f57e)

**Comment by mujeeb-intel** [comment]
Hi @goldenx86 thanks for this.

when you mention " 24H2 solves it by opening the color profile settings." are you saying the latest update of windows, fixes your issue?

**Comment by goldenx86** [comment]
Hi. Yes and no, it's not guaranteed to work after some several attempts.
When it works, just going to Windows Configure > Display > Color profile solves it. Other times, it still needs a system reboot/log-off to solve it.

**Comment by mujeeb-intel** [comment]
@goldenx86 

So, checkout my testing video: https://youtu.be/3HPAXTKymJY

Am i doing everything right here? I used your profile and did not notice much of anything. Tried leaving for an hour and then coming back and re-did all the steps. Still did not see the reverting back after launching arc control.

What monitors are you using? It could very well be thr monitor specific issue. 

Could you tell me the following:
- How many monitors are connected?
- Are you using an adapater to connect multi monitors or simply using hdmi and dp ports? If so is it 1 hdmi, 2 dp ports are you using?
- Try https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html and then reinstalling the graphics driver. Does it make any difference?

-Muji

**Comment by goldenx86** [comment]
For 23H2, you have to set the profile as system wide for the change to take effect, which is what my laptop's driver does. This is in Color Management, Advanced tab, at the bottom left, Change system defaults, and then set the profile for the display there.
On 24H2 this is just done from Configure > Devices > Screen Color profiles.

Make sure to test this locally and not over remote, as it won't show up on recordings, the profiles only affect the output of the display, not the actual frames.

The specific display shouldn't matter, but just in case, this Asus laptop comes with a BOE 0903, it's just the integrated display. From the Intel Discord server, at least 3 people are affected from what I could find, all with different configurations.
I'll try if DDU helps with the latest driver.

**Comment by mujeeb-intel** [comment]
Oh nice, I now tested it on the integrated graphics (not a remote device). and followed your instructions.

can you tell me if I did everything right here? https://youtu.be/H2tmGKVM2FE I couldnt see any difference in the behavior of resetting it to srgb when opening arc control.

**Comment by goldenx86** [comment]
Yeah, LGTM. I wonder if it is the fact that it's installed for the specific device instead of loading the profile manually.
I didn't have any luck with DDU, the issue is still reproducible on my end.

**Comment by mujeeb-intel** [comment]
yeah, this is interesting to me. Do you have the link to the post on discord? I wonder if they all use the same exact model of the laptop/display.

**Comment by mujeeb-intel** [comment]
Actually, I found the post on discord. I have a similar laptop as the other user. I'm going to test it on that one and come back with the results. 

I'm going to follow the exact same procedure to test it on another system. 

When you say "it's installed for the device vs manually loading" what do you mean by that? You mean the default the device came with was the profile you shared vs how I am manually loading it to apply as default?



-Muji

**Comment by goldenx86** [comment]
Yeah by default (the stock Windows install), or if you manually install the "driver" responsible for adding the system level profile, you don't need to go yourself through what you did on the videos. But since those drivers look for the vendor and panel IDs, it's basically useless unless you have my same laptop.
I can pass the installer, I just extracted the profile from there so I can also use it on Linux too: https://dlcdnets.asus.com/pub/ASUS/nb/Image/Software/SoftwareandUtility/15070/MyASUSSplendid_ASUS_Z_V6.0.0.487_15070.exe?model=X1502ZA

**Comment by mujeeb-intel** [comment]
Yeah could be specific to that brand of device since I couldn't reproduce it on other desktops. However, I still have to test on the system one discord person tasted since I have the similar if not the exact one. Will keep you in the loop. 

Btw, if you can get in touch with the manufacturer regarding this and letting them know it doesn't happen anywhere else, could be helpful as well since it could very well be something from the manufacturer driver setup that's causing this weird conflict.

**Comment by goldenx86** [comment]
I can try at least. Asus is not the greatest, but it's worth mentioning it to them.

**Comment by mujeeb-intel** [comment]
Hey @goldenx86 so we had the i7-14700HX lenovo legion pro 5i model ordered and I tested on that with both IGPU and only Nvidia dgpu. Did not notice any resetting of the color management profile.

-Muji

**Comment by goldenx86** [comment]
Pretty slippery one.

**Comment by mujeeb-intel** [comment]
So yeah, I suspect this issue is related to your system and the best course of action would to be get in touch with the manufacturer. I mean you could try our latest graphics driver released two days ago. But if that doesn't do the trick, then the manufacturer route would be the ideal choice in this scenario.

**Comment by mujeeb-intel** [comment]
Okay, so this the game plan:

1. Run the ddu again like I mentioned above.
2. Then head over to the asus website so you can download your manufacturer graphics driver build. I looked it up on this and you can find it here. https://www.asus.com/supportonly/x1502za/helpdesk_download/
3. Then confirm if the issue is happening on that graphics driver build. The drivers that comes with manufacturer is custom-tailored to that specific device. 
4. Then if Youd like you can go ahead and download the latest generic graphics driver by heading over to intels website.
5. Lastly, contact your manufacturer regarding this issue. It does not happen to any other systems ive tried so far. Confirmed it with my team as well.

Does this sound good to you?

**Comment by goldenx86** [comment]
Will do and confirm with you here.
Guess it's the last to do before the incoming EoL.
Thanks.

**Comment by mujeeb-intel** [comment]
Ill go ahead and close the ticket, if you have questions you can refer back to this ticket, sounds good?

**Comment by goldenx86** [comment]
Sounds good to me, thank you for your time.

**Comment by mujeeb-intel** [comment]
Appreciate it. Thank you for reaching out.

**Comment by goldenx86** [comment]
Found the cause, ARC Control has a brightness default of 30 instead of the proper value of 50. Resetting that solves the problem.
