### ISSUE TITLE
Minecraft OFFICIAL modpack texture bug

### ISSUE THREAD

**Issue by NoxNostraEst** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#822]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Minecraft GregTech: New Horizons (Technic Launcher)

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

Minecraft Official Technic Launcher

### Processor / Processor Number [Required]

11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz

### Graphic Card [Required]

Intel Iris Xe

### GPU Driver Version [Required]

32.0.101.5762

### Rendering API [Required]

- [ ] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 10 21H2

### Intel System Support Utility report

Issue generating it.

### Description and steps to reproduce [Required]

1. Download the Minecraft Technic Launcher
2. Install the Gregtech: New Horizons modpack
3. Try creating a new world, entering it, exiting to the main menu, and then accessing the world list again. The texture bug will be visible. 
4. ALTERNATIVE: Press J in-game, create a waypoint and then access the waypoint list again.

*This issue affects multiple UIs from multiple different mods hence it is not a mod-related issue. Other people that do not use Intel Iris Xe do not experience these problems!*

![1](https://github.com/user-attachments/assets/e2a82673-087b-4a06-9c33-7edcede847cf)
![2](https://github.com/user-attachments/assets/d1dec629-594e-4561-926b-bb63ccc33d69)
![3](https://github.com/user-attachments/assets/8bcf9473-2519-437d-8b5d-d80a95cf4883)

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Issue was present when playing on the standard settings that came with the launcher. Issue persisted regardless of the settings I have put in.

### Save game

**NOTE: I understand this is a modpack, so a modded version, BUT it is an official modpack with a proper development team and this issue is persistent on this GPU only and not others!

Secondly, I have attempted using these mods on an updated version of the game. The issue still persists in terms of UI.**

**Comment by Zack-Intel** [comment]
Hi @NoxNostraEst 

Thank you for making this post. I had a couple clarification questions so I can assist you better:

1. Just as a sanity check to 100% confirm, is this the Java version or the Windows version of Minecraft? The mods seem to indicate it's for the Java version but I wanted to double check
2. You mentioned it happens for multiple different mods. Are the different mods all from the same modlist under GT New Horizens, or different mod packs?
3. Do the modpack creators have official connections or work with the Minecraft developers directly, or is it an offshoot fan mod creation?

**Comment by NoxNostraEst** [comment]
Hello! Sorry for the delay!

1. It is indeed Java!
2. Indeed, it happens to UIs of different mods, not only one specific mod. All mods are under this pack.
3. The modpack itself should be a fan creation, however, it has been accepted on official launchers of parties which are official partners of Minecraft, according to your website.

**Comment by Zack-Intel** [comment]
No worries, @NoxNostraEst Thank you for clarifying.

Even as an officially supported launcher, the mod itself was still developed outside of Microsoft/the Minecraft creators. The Intel driver team and the mod creator need to collaborate for a fix in this instance, so the best course of action would be to request the mod creator on their forums to work on the Developing Games on the Intel Graphics Forum for assistance, and the team there can collaborate with the creators for next steps. I'm sorry this isn't the route you were hoping for, but having them work with us directly increases the chances for a fix.

If you have any questions on next steps, please let me know and I'm happy to further clarify or answer any questions.

**Comment by Zack-Intel** [comment]
Hi @NoxNostraEst 

Do you have any additional questions or updates for us at this time?

**Comment by Zack-Intel** [comment]
Hi @NoxNostraEst 

I will go ahead and close the case. If there are additional questions that can be addressed not relating to a mod pack, please feel free to open a new case.
