### ISSUE TITLE
Quantum Break crashing on launch with drivers newer then 5534

### ISSUE THREAD

**Issue by IntelArcTesting** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#823]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Quantum Break 

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

Game Pass (Xbox App)

### Processor / Processor Number [Required]

Ryzen 7 5700X3D

### Graphic Card [Required]

Arc A580, Arc A750 and A770

### GPU Driver Version [Required]

32.0.101.5762

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 10 22H2

### Intel System Support Utility report

[igcit_ssu (5762).txt](https://github.com/user-attachments/files/16274968/igcit_ssu.5762.txt)
[igcit_ssu (5534).txt](https://github.com/user-attachments/files/16274969/igcit_ssu.5534.txt)

### Description and steps to reproduce [Required]

When launching the game I picture with faces of 2 main characters of the game and after that a white screen followed by as crash. When I downgrade to driver version 5534 it doesnt crash and boots and runs perfectly fine. Same issue on my A750 and A770

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Won't even start so settings should not be the issue

### Device / Platform name

DIY build.

**Comment by Felipe-Intel** [comment]
hello @IntelArcTesting thanks for this report. We will submit this to our driver development team. As soon as I have news I will be sharing them here.

**Comment by Felipe-Intel** [comment]
@IntelArcTesting I was able to launch the game and play with driver 32.0.101.5972. Could you please check on your side if now the game is working as expected?

**Comment by kunit1** [comment]
Not the original poster but I just tested with driver 32.0.101.5972 and it launched successfully.

**Comment by Felipe-Intel** [comment]
Thanks for testing! I'll proceed to close this ticket.
