### ISSUE TITLE
Sims 2 D3DDER Invalid code issue

### ISSUE THREAD

**Issue by Mika2125** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#825]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Sims 2 

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

Sims2RPC

### Processor / Processor Number [Required]

i5 13600k

### Graphic Card [Required]

A770 LE

### GPU Driver Version [Required]

32.0.101.5762

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [x] DirectX9

### Windows Build [Required]

Windows 11 24H2

### Intel System Support Utility report

![350996575-b85cd4b3-33d5-42f7-a91d-5af06e9e6a50](https://github.com/user-attachments/assets/20840d01-ae99-4b86-883f-4b720f688993)

### Description and steps to reproduce [Required]

I am experiencing a recurring bug while playing a game. This issue persists even with the latest drivers installed. I had previously reported this problem in an older ticket, and at that time, I mentioned the specific driver version that worked correctly. I am unsure what to do atm, but I hope you can look into it again?  **My older ticket was #568**

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![277785029-77562607-5cad-400b-b781-676a9fb2f0e7](https://github.com/user-attachments/assets/bfe6b6d0-fdb6-4fcc-b45f-1642b6965c96)
![277785056-068dd2a5-9b10-41fa-aa9b-29d5619fa338](https://github.com/user-attachments/assets/7bcdc976-ea24-4e6c-998c-1fbd452b6642)

**Comment by Gabriela-Intel** [comment]
@Mika2125 Can you disable your modder and check if the error still occurs?

I tried it out on a Sims 2 copy ordered from Ebay and it seems that it only crashes when Shadows are set to High. But please confirm and let me know.

Thanks!

**Comment by Mika2125** [comment]
@Gabriela-Intel I've disabled it and ran it with and without mods! It's a blessing that you checked up on this old game—I love. Honestly, I didn't expect it at all! Setting the shadows to high causes a crash at the moment, but overall, it's pretty stable on the current driver. So far, I haven't encountered any immediate issues on driver 5768.
Previous one, I had issues with.

AGAIN tysm!

**Comment by Gabriela-Intel** [comment]
Thanks for checking! I did submit a bug sighting (id #14023168870) since I'm still observing some crashing issues with Shadows set to High. That being said I cannot promise if or when there is going to be a fix, especially given the age of the game. :/

For now I'll keep this open until I hear official word on how we are proceeding on the bug.

**Comment by Mika2125** [comment]
Here's your message with corrections:

---

@Gabriela-Intel thank you so much again! I'm just happy that it's being looked into since a significant community still plays these games, including The Sims 3. It makes me hopeful because I really don't want to get a whole new GPU for nothing, especially since I'm so happy with the ARC team. So, I thank you again for looking into it! I honestly didn't think it would happen.

Once again, thank you so much! Even if it's not a complete promise, I still find it quite hopeful, especially since I've had that issue open for some time.

Thank you again for looking into it. I'm still hopeful! 🙏🏽✨💅
