### ISSUE TITLE
dead rising 2 freezes

### ISSUE THREAD

**Issue by papandbuddyg** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#826]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

dead rising 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Intel Arc A580

### GPU Driver Version [Required]

32.0.101.5762

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build [Required]

Windows 11 24H2

### Intel System Support Utility report

[system 2.txt](https://github.com/user-attachments/files/16405295/system.2.txt)

### Description and steps to reproduce [Required]

![image](https://github.com/user-attachments/assets/3c70a5ad-5f38-4696-b5fa-5460dcc9b382)
i was in the open world messing around walking and at fortune park i was freezing from time to time and i would also freeze on the loading from time to time

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

2560 x 1440p

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

high settings on everything 2560 x 1440p (120hz)

### Device / Platform name

Deskop-K8UIJRPO

### Save game

honestly not even 5 minutes into the game tbh

**Comment by mujeeb-intel** [comment]
Hey @papandbuddyg thanks for bringing this to our attention,

As I prepare my system to replicate this issue. Do you know if the issue happens if you use directx12, 11 or 10?  or does it not have that feature?

thanks.

-Muji

**Comment by papandbuddyg** [comment]
this game doesnt support 12 11 or 10 @mujeeb-intel

**Comment by mujeeb-intel** [comment]
Hi @papandbuddyg Tried to replicate the crash but could not.

Tried it on 3 different systems with 1080p,1440p and 4k.

All at 120hz with the highest settings and turned off vsync like you mentioned. 

Could you try to run the [ddu](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) and reinstalling the latest driver if you havent tried that yet, please?

**Comment by papandbuddyg** [comment]
ya i have no crashes now @mujeeb-intel
