### ISSUE TITLE
performance horrible

### ISSUE THREAD

**Issue by papandbuddyg** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#827]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

battlefield 2042

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 3600

### Graphic Card [Required]

Intel Arc A580

### GPU Driver Version [Required]

32.0.101.5762

### Other GPU Driver version

32.0.101.5768

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 11 24H2

### Intel System Support Utility report

[system 2.txt](https://github.com/user-attachments/files/16421427/system.2.txt)

### Description and steps to reproduce [Required]

![image](https://github.com/user-attachments/assets/7e7c9999-15b6-4e5e-977f-40f387fcda02)
![image](https://github.com/user-attachments/assets/f73c5f40-675c-4b3a-81cc-e412cd0a4bb0)

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

2560 x 1440p

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/user-attachments/assets/d966dd04-9a53-4703-bcc1-632746eaad0d)
![image](https://github.com/user-attachments/assets/b697607e-f08a-4c60-aa4b-1d6efcb75523)
![image](https://github.com/user-attachments/assets/0af6d03a-c1f0-421a-b48b-d76a5b04fafb)

### Device / Platform name

Deskop-K8UIJRPO

**Comment by papandbuddyg** [comment]
![image](https://github.com/user-attachments/assets/135c1327-bb87-4dc1-8379-d1599f80f629)
i also got this error so its def driver related

**Comment by Ilya-intel** [comment]
Hey @papandbuddyg ,
I've played a bit with the same config as yours and haven't seen any performance issues (see pictures below).
Have you tried clean reinstallation of GFX driver using DDU tool?
What about temperatures, is there any overheating of CPU/GPU leading to throttling?
![Screenshot 2024-07-30 155149](https://github.com/user-attachments/assets/15e09382-f6cc-437b-a92a-09a85e0dac07)
![Screenshot 2024-07-30 155318](https://github.com/user-attachments/assets/66d6420c-e20f-4175-831a-cbb4da5b0a84)
![Screenshot 2024-07-30 155339](https://github.com/user-attachments/assets/9115339a-f1a4-4c15-8b61-659d9e4763f1)
![Screenshot 2024-07-30 155637](https://github.com/user-attachments/assets/77033c4b-663e-46ac-b563-a22040783a00)

**Comment by Ilya-intel** [comment]
@papandbuddyg 
Also, is Resizable BAR (Smart Access Memory) enabled on your motherboard?
You can check it in GPU-Z tool.

**Comment by papandbuddyg** [comment]
![image](https://github.com/user-attachments/assets/c94c1ed3-b58e-432b-9a93-9d3d21000760)
yes rebar is on i could try reinstalling using ddu in a bit @Ilya-intel

**Comment by papandbuddyg** [comment]
ya i tried ddu and my fps is still rough @Ilya-intel 
![image](https://github.com/user-attachments/assets/ea092cb7-4619-483d-b43e-28f0e3954a59)
![image](https://github.com/user-attachments/assets/14e826bd-1d97-49aa-a8bc-1b3507a14a7a)
![image](https://github.com/user-attachments/ass
![image](https://github.com/user-attachments/assets/ba218e26-2546-4ded-8a34-009888e21561)
ets/eca5e669-9061-43ac-a3a4-257a6ea61c05)

**Comment by Ilya-intel** [comment]
@papandbuddyg 
Okay I see.

On your screenshots I see that CPU is being highly utilized, while GPU is not, which is not OK.
So, I have a few clarifying questions:
1. Do you see this behavior from the very beginning?
2. What PSU do you use and are both power connectors attached to the GPU?
3. Have you tried resetting BIOS settings?
4. Can you try using other RAM modules (or try with one module at least)?

This might be caused by some unsupported features by this particular motherboard model since AMD 400 Series boards are not supported.

**Comment by papandbuddyg** [comment]
1. i havent i actually been playing a few demanding games with my arc such as ff7 remake and ive been playing ffxiv everyday on it and it runs perfectly fine the only real issue i notice is lag spikes on games but it seemed to tone down a bit
2. i use a Apevia ATX-PR600W Prestige 600W 80+ Gold  and both power connectors are connected to the gpu
3. i actually try to update my bios regularly
4. this sadly wont cant happen as if i take out a ram stick its going to run even worse with 8gb of ram lol
i do want to add that i have a motherboard that supports 5000 series cpu and if i was to take out my arc and put in my rx580 my fps would be fine @Ilya-intel

**Comment by papandbuddyg** [comment]
![image](https://github.com/user-attachments/assets/e582d0a8-48dc-4adb-a2c1-5c630e165bea)
heres a picture of rdr2 with max settings because i wanted to see how far the gpu can go xd

**Comment by Ilya-intel** [comment]
@papandbuddyg 
Interestingly, GPU is not fully utilized again.
Could you check which power mode is set in the Windows settings? It is worth trying switching from Balanced to Best Performance and vice versa.

**Comment by papandbuddyg** [comment]
![image](https://github.com/user-attachments/assets/679159e9-4aa0-4070-92b5-44bb47ab5c32) this is current and i just changed it to balanced i get this performance booting up rdr2  and battlefield 2042 negated its a loading screen but still  is very uh rough on utlization 
![image](https://github.com/user-attachments/assets/ccc97cba-8805-411e-b3e6-045207d8845c)
![image](https://github.com/user-attachments/assets/9c9b508e-9599-4498-8198-ba1a82d83479)

@Ilya-intel

**Comment by Ilya-intel** [comment]
@papandbuddyg 
I still can't reproduce such behavior on several systems, which makes me think this is an OS issue.
Could you check Windows system files integrity and maybe even try reinstalling OS?

**Comment by papandbuddyg** [comment]
@Felipe-Intel im not reinstalling the os for a single game tbh
![image](https://github.com/user-attachments/assets/807bb965-035d-46de-a7de-95de436ae3a3)
it also did not find anything wrong i dual boot but i cant try on linux because this game doesnt support linux xd its odd tbh

**Comment by Ilya-intel** [comment]
Hey @papandbuddyg ,
There is a newer driver available, please try to clean install it: https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html
If it won't help, please upload DxDiag report (you can simply type dxdiag in start menu and then press the "Save All Information" button).

**Comment by papandbuddyg** [comment]
ima go ahead and reopen this issue because it sparked back up recently @Ilya-intel i did try ddu recently and ya its still not utlizing 100 percent of my gpu its with select games like ya rdr2 and battlefield its odd heres my dxdiag
[DxDiag.txt](https://github.com/user-attachments/files/18000430/DxDiag.txt)
