### ISSUE TITLE
Dark Souls III Missing Particles

### ISSUE THREAD

**Issue by hcwy** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#829]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Dark Souls III

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5 5600

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

32.0.101.5768

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 11 22H2

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/16483016/igcit_ssu.txt)

### Description and steps to reproduce [Required]

1.) Create / load game
2.) Find bonfire / item on floor / fire
3.) Observe particle is missing but light cast still visible (e.g. no dragon fire on floor after attack, but fire from attack itself visible)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![settings](https://github.com/user-attachments/assets/d8927194-eb75-4728-ba58-8f5fbc715613)

### Device / Platform name

B450M-DS3H

### Crash dumps [Required, if applicable]

N/A

### Save game

[DS30000.zip](https://github.com/user-attachments/files/16483061/DS30000.zip)

Save file is right next to a dragon, wait for its fire attack, walk towards where the attack landed, character will take damage but fire is invisible

**Comment by Zack-Intel** [comment]
Hi @hcwy 

Thank you for your post. I'll begin working on this case and let you know once I have any updates.
 
It does look like there's some difficulty in the most recent versions of DS3 in getting save files from different accounts at least though official means. If you have a way to navigate this, please let me know. Otherwise, I'll try to play though the game until I run into a dragon.

In the meantime, if you're able to help me with a few questions that can help make the process easier:

1. Is this seen as a regression with the drivers, or has it always appeared since you started playing?
2. Do differences in the graphics settings/configurations change the outcome of this issue?
3. About how far into the game is needed to get to a fire-breathing dragon to more easily see the issue? Alternatively, you mentioned it could be seen with bonfire or items on the floor. Do you have any screenshots of what that looks like?

**Comment by hcwy** [comment]
Hello Zack,


Thank you for taking the time to work on this.


1. I only started playing the game after installing the latest drivers

2. No, as far as I can tell changing graphics settings doesn't appear to help fix this issue

3.

Bottom of bonfire glowing, but no fire visible

Same with this tree, the glow from the fire is visible, but not the fire itself


If you need further help, please contact me again. Also I initially replied via email, could you confirm whether the email was received or not?
 
Thanks.

**Comment by hcwy** [comment]
Apologies, screenshots didn't attach, here they are:

![gCVmroVci7glLF29](https://github.com/user-attachments/assets/cf94c8fe-c2aa-4525-a74a-d1a8b0483b57)
Bottom of bonfire glowing, but no fire visible

![3dpXh27oo6Kj1Ckh](https://github.com/user-attachments/assets/f3ab055e-2bbd-45e9-b2e0-18e3000cbbd9)
Same with this tree, the glow from the fire is visible, but not the fire itself

**Comment by Zack-Intel** [comment]
Hi @hcwy 

Thank you for the screenshots and updates. I'll continue through the game and reach a bonfire to attempt replication.

Regarding the email, I did not get the manual email sent, but I do get alerts on new github posts with the content of the new post, so posting on this forum will be sufficient for me to get quick updates.

**Comment by Zack-Intel** [comment]
Hi @hcwy 

I believe I've been able to reproduce the issue on my end. I'm going to run further tests and collect logs to get to the next steps. I'll update you when I have new information to share.

**Comment by hcwy** [comment]
Hello @Zack-Intel 

That's great to hear.

**Comment by hcwy** [comment]
Hello @Zack-Intel 

A quick update: this issue appears to have been fixed in the latest driver version 32.0.101.5971, noted here in case of regression.

Here is a screenshot of the tree with the latest drivers:
![particles_fixed_ds3](https://github.com/user-attachments/assets/7be49bb2-42ad-4787-9fa4-c03adac9a3f5)

Thank you for all your help in resolving this issue, I will now close the issue.
