### ISSUE TITLE
Battlefield 4 random blackscreen in fullscreen mode

### ISSUE THREAD

**Issue by IGCIT** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#83]
#### Checklist [README]

- [x] Device is not undervolted nor overclocked.
- [x] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [x] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Battlefield 4

---
#### Game Platform [Required]
- [ ] Steam
- [x] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]
i7-1165g7

---
#### GPU Driver Version [Required]
- [x] 30.0.100.9862 (*latest*)
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [x] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [ ] Windows 11 (*Insider Preview*)
- [x] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (*Please specify your build number*)

---
#### Description and steps to reproduce [Required]

Random black screen in fullscreen mode, the game is still running, no crash or freeze.

1. Launch the game
2. set fullscreen mode and apply settings (if not fullscreen)
3. play the game (i only tested multiplayer, but it also happens in main menu)
4. or change resolution or play with other settings till the screen goes black 

Partial workaround:

unfocus the game and focus it again, ie go back to desktop (do not exit the game, just press Windows button) then resume the game.
This fixes the blackscreen for a few minutes, then it goes black again.

Workaround:

set windowed mode, no blackscreen. (but the game does not support borderless windowed mode, so it is old windowed mode)

---
#### Device / Platform [Optional][Recommended]

GPD Win3

---
#### Game Settings [Optional][Recommended]

High/Ultra settings, no AA

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---
#### Windows mini dump (*small memory dump*) (*if available*) [Optional][Recommended]

---

**Comment by craiggx** [comment]
Hi there. I have some questions about the above issue. Can you tell me the windows version you were running at the time you discovered this? You can see the current Windows version by opening command line and looking at the windows version at the top of the window.

Also, what was your device's resolution set to?

Finally, could you run dxdiag and attach the results to this issue? You can get to dxdiag hitting the Windows key and typing in "dxdiag"

**Comment by IGCIT** [comment]
windows version is reported in the issue, i don't remeber the exact version string, windows 10 21h1 + windows updates at the time of writing (mandadory, optional and quality)

the problem occurs on both internal and external display

720x1280 (rotated screen) (internal)
1920x1080 (external) (TV)

i did a new test just now, current env:

windows 10.0.19043.1320
driver 9955
[DxDiag.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/7456104/DxDiag.txt)


Internal:

internal display is mostly fixed now, i've played 2 matches and no black screen, but if i change the game resolution the screen goes black and i must apply the workaround described in the issue (go back to desktop with Windows button and refocus the game)
i'll play some more in next days.


External:

i now get more issues on external display tho
if i connect the hdmi cable while the game is running, the screen goes black immediately (before was random every 3-5 minutes)
in addition, the audio of the game gets lost until you exit and relaunch the game from origin

to connect an external display i go back to desktop, connect hdmi cable, refocus the game.
if i change the resolution, the screen goes black (same as internal display)

**Comment by craiggx** [comment]
Thanks a lot for the info! 

One more question: Have you only encountered this in multiplayer matches? Have you ever seen it in campaign or the training area?

**Comment by IGCIT** [comment]
i've never played campaign or training :P
i'll test them

**Comment by craiggx** [comment]
Also, when you're using an external display are both displays active or just one? Are you in extended display mode or duplicate?

**Comment by IGCIT** [comment]
only external screen is active, windows saved my settings so when i connect the hdmi cable, it will automatically disable my internal screen

it happens with any resolution,if you switch, you get a black screen (internal and external)
the new resolution is being applied, but you cannot confirm the new setting because the screen is black.
if you are fast enough to go back to desk and focus the game, you can apply the new resolution, otherwise the old setting is restored and screen will go back to normal.

**Comment by craiggx** [comment]
I've got another question: Were you using the docking station to connect to your external display?

**Comment by craiggx** [comment]
Also, if you could provide a video of the issue happening, that would really help us to reproduce it and work on a fix.

**Comment by IGCIT** [comment]
> I've got another question: Were you using the docking station that comes with the gpd win3 to connect to your external display?

no, https://us.lemorele.com/products/5-in-1-usb-c-hub-tc24upgraded-of-tc15



> Also, if you could provide a video of the issue happening, that would really help us to reproduce it and work on a fix.

well, the bug breaks recording apps too and i don't have a camera, when i switch resolution the screen goes black, but when i press windows button it comes back (but not obs, which still shows a black screen)

this is on internal screen

https://user-images.githubusercontent.com/76787191/140327325-a8bd5197-feb1-4343-a7cf-96da790dee6d.mp4


on external screen

as i said, there is no audio, moreover, when i boot the game from origin, it shows a black screen (again apply the workaround)
if i switch resolution, it shows a black screen as shown in the video

**Comment by estebanr863** [comment]
Hi @IGCIT,

We were not able to reproduce this issue without the specific docking station you are using. I should mention that we cannot guarantee that every docking station on the market will work correctly, since every manufacturer designs their products differently.

This specific issue can’t be reproduced when using a display connected directly to an Intel system and so, this issue falls out of the scope of the support we can provide. I apologize for the inconvenience.

**Comment by IGCIT** [comment]
ok, thanks
probably specific to gpd win 3 internal screen :\
