### ISSUE TITLE
Battlefield 1 and 4  extremely high CPU load [ igd10um64xe.dll high CPU usage]

### ISSUE THREAD

**Issue by qefyr** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#830]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Battlefield 1

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i3-1215u

### Graphic Card [Required]

UHD with 24Gb DDR4-3200

### GPU Driver Version [Required]

32.0.101.5768

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 11 23H2

### Other Windows build

same problem in Win10 22h2

### Intel System Support Utility report

On a laptop with an i3-1215u, the game Battlefield 1 (minimum settings, multiplayer) loads the CPU at 100%, shows low FPS with stutters, even at 720p, while the integrated UHD video card is often not loaded at 99-100%. This CPU load in this game is abnormal. The game runs perfectly on a 2009 processor (Xeon X3440) with an Nvidia GTX770 video card, but on a modern processor there is supposedly a bottleneck.
I checked in the process explorer, in the threads tab, a lot of igd10um64xe.dll processes. I believe that this file is a driver component from Intel.
![bf1](https://github.com/user-attachments/assets/e9831213-2e52-4ae5-b763-55871486f5fe)
https://www.youtube.com/watch?v=NCyK7yeZCQs

### Description and steps to reproduce [Required]

https://www.youtube.com/watch?v=NCyK7yeZCQs

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280x720 and 1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

ALL SETTINGS at MINIMUM 100% render

**Comment by BiZkViT96** [comment]
Please attach SSU report. https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/How-to-generate-Intel-System-Support-Utility-report

Battlefield multiplayer is usually very CPU intensive load and your i3-1215u how I can tell is 2 P-cores/4 E-cores CPU. So don't expect to much from it.

Wait for official answer.

**Comment by qefyr** [comment]
[igcit_ssu.txt](https://github.com/user-attachments/files/16487585/igcit_ssu.txt)

**Comment by Vivek-Intel** [comment]
@qefyr thank you for reporting the issue.
Did you see this issue after driver or game updates ?

Can you try below things and check if you see any improvements :

1: close process explorer
2: turn of TAA in game setting, use FXAA
3: set ambient occlusion to SSAO
4: please restart the game and check

**Comment by Vivek-Intel** [comment]
hi, We do not have exact laptop model so we did try BF4 on another laptop (NEC) with similar configuration i3-1215u with 101.5768 driver but could not see CPU maxing out to 90-100% at any point or any lagging. Please find the video [here ](https://drive.google.com/file/d/1QXggANUNX9cuWS_Lz-WyWDg1INuO2Cmq/view?usp=drive_link). Can you share issue video with BF4.

**Comment by Vivek-Intel** [comment]
closing this issue as of now, user can reopen if needed once above asked steps are tried and requested info provided on latest driver.
