### ISSUE TITLE
Battlemage discrete GPU to provide USB-C DP Alt output port

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#832]
### Application [Required]

All

### Processor / Processor Number [Required]

Core i7-13700K

### Graphic Card [Required]

Arc Battlemage B???

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build [Required]

Windows 11 23H2

### Describe the feature [Required]

I hope the upcoming Battlemage dGPU can be equipped with one USB-C DP Alt output port just like the RX 7900 XT(X) MBA reference edition. Nowadays many new gaming monitors have USB-C DP Alt input because the monitor can easily provide built-in KVM with such configuration.

**Comment by EstebanIntel** [comment]
Hi @Susie1818,

We will share this to our engineering team, thanks for your feedback!
