### ISSUE TITLE
Game won't render to headset with intel arc

### ISSUE THREAD

**Issue by characharm** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#834]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Half Life 2 VR Mod

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

7959x amd

### Graphic Card [Required]

a770

### GPU Driver Version [Required]

32.0.101.5768

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 11 24H2

### Intel System Support Utility report

n/a

### Description and steps to reproduce [Required]

When running the game with my quest 2, alvr, and an a750, the game will start, and pick up my movements, but it won't render to the headset, or the steamvr preview.
This seems to be an intel driver level thing, but they say the want to get in contact with you to fix the issue.
----
I would like to bring this issue to your attention. Kindly follow the link https://feedback.halflife2vr.com/boards/bug-reports/posts/game-won-t-render-to-headset-with-intel-arc for more information.

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

2064×2208p

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

not related

**Comment by EstebanIntel** [comment]
Hi @characharm,

Unfortunately, VR is not currently supported by Arc A-Series GPUs. We will provide feedback to our engineering team that this is a requested feature. Thanks for your feedback!

**Comment by Felipe-Intel** [comment]
test (disregard this message)
