### ISSUE TITLE
Lots of graphics issues in Rainbow Six Siege Vulkan with latest driver

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#837]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Rainbow Six: Siege

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

32.0.101.5971

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 11 24H2

### Intel System Support Utility report

[Intel SSU 24.08.2024.txt](https://github.com/user-attachments/files/16738049/Intel.SSU.24.08.2024.txt)

### Description and steps to reproduce [Required]

![PXL_20240824_214215024](https://github.com/user-attachments/assets/cb8ba164-31b2-4be8-9039-f04262a6590b)

https://github.com/user-attachments/assets/bbe2cf5b-cc79-4ec0-b15e-afd16c817106

You can see here two different instances of the issues. They're pretty varied, it's not a single graphical issue there's a lot of different ones. They happen only when Alt Tabbing
When alt tabbing, there's like a 1/3 chance that one of the visual issues will appear. Same thing when Alt Tabbing when there's already an issue, there's then a 2/3 chance that it'll go away
Sometimes the issue is absolutely makes it absolutely unplayable, sometimes it's minor
Tbh on such a huge game like that, it's really important issue, especially for those who take a lot of time Alt Tabbing because of black screen
### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1080, ratio of 4:3

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

All set to medium, anistropic x16, TAA 4x, 0.25x render, 100% TAA sharpness

### Device / Platform name

ASUS PRIME Z790-P WiFi D4

**Comment by kunit1** [comment]
There is already a more up to date driver. Did you try it? [driver 32.0.101.5972](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) did you

**Comment by TheWonderfulTartiflette** [comment]
@kunit1 the form didn't let me choose a higher version, but that's actually my driver version

**Comment by Zack-Intel** [comment]
Hi @TheWonderfulTartiflette 

Thank you for filing a ticket regarding this issue. My initial tests aren't able to reproduce the issue, but I'll keep testing different configurations and drivers to see if I can get it to show up here.

In the meantime, can you clarify a few points for me to rule out some issues:

1. Just to confirm, has this issue been seen in previous drivers? The title implies that it is a regression, but I wanted to double check if it was seen with older drivers.
2. What programs are being alt-tabbed into when leaving the game? Are they graphically intense or more basic programs?
3. Are you able to test with other monitors or ports by any chance to rule out a screen flicker issue?

**Comment by TheWonderfulTartiflette** [comment]
@Zack-Intel Yes, this is a regression, this hasn't happened once before the new driver
Basically any program, but I mainly did it with Chrome and Discord
No, I don't have any other monitor, R6 was the only game where I have such issues, and this is very probably not a screen flicker issue, as you can see in the video, one of the glitch patterns was to create some noise around the two characters in the menu (only the game/driver/OS has access to such 3D info, it would be a huge coincidence if it was a screen issue)

**Comment by TheWonderfulTartiflette** [comment]
There's a ton of other glitch patterns, but one that I just remembered was like one of those VHS issue with a line going from top to down, in like a second, repeating

**Comment by TheWonderfulTartiflette** [comment]
@hcwy no I haven't but I will try this evening

**Comment by hcwy** [comment]
Hey @TheWonderfulTartiflette 

Also curious as to whether this occurs in the DX11 version of the game or only Vulkan?

**Comment by TheWonderfulTartiflette** [comment]
@hcwy haven't tried dx11 recently, can't tell. But if DDU doesn't fix the issue, I'll try dx11

**Comment by hcwy** [comment]
@TheWonderfulTartiflette I'm only asking because Ubisoft has decided to replace the Vulkan version of the game entirely with DX12 in the upcoming season (Y9S3)

**Comment by Zack-Intel** [comment]
Hi @TheWonderfulTartiflette 

I'm still unable to reproduce the issue on my end. Can you let me know if the DDU tool or using DX12 improved performance or reduced the issue? If not, I will see what additional options we have to pursue this.

**Comment by TheWonderfulTartiflette** [comment]
@Zack-Intel as I said, the DDU did not solve anything, but I have yet to try with DX11
As for performance, that was not my issue with the game? The only issue I was talking about was the graphical glitches

**Comment by Zack-Intel** [comment]
> @Zack-Intel as I said, the DDU did not solve anything, but I have yet to try with DX11 As for performance, that was not my issue with the game? The only issue I was talking about was the graphical glitches

Apologies for the confusing wording. I did mean the graphical glitch issue. I'll continue to investigate as we see what DirectX 11 performance shows on your end.

**Comment by Zack-Intel** [comment]
Hello @TheWonderfulTartiflette,

I'm still not able to see the issue after more extensive testing and investigating, regardless of configurations, so I'm suspecting this is an isolated issue. 

My next guess would be to double check if the save file is corrupted by trying a new file and also check if there's any changes or spikes in Memory within Task Manager when it shows the issue, as well as letting me know if using DirectX has different behavior.

**Comment by Squall-Leonhart** [comment]
This issue occurs when VRAM has been exhausted and atleast 2-3GB's of System shared is in use, it also manifests on nvidia drivers under the same condition.

**Comment by Zack-Intel** [comment]
Hi @Squall-Leonhart 

Given this information regarding the Vulkan renders and also happening on Nvidia drivers, I would double check with the game vendor for more specified help with the issue as they may be able to root cause for this.
