### ISSUE TITLE
Halo: combat evolved. Bug when zoom scope is activated

### ISSUE THREAD

**Issue by alucard1792** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#842]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Halo: combat evolved with 1.10 patch

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

none

### Processor / Processor Number [Required]

Ryzen 5800x

### Graphic Card [Required]

PREDATOR BIFROST Arc A770

### GPU Driver Version [Required]

32.0.101.5989

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build [Required]

Windows 10 22H2

### Intel System Support Utility report

![image](https://github.com/user-attachments/assets/35d402b4-0022-458e-b182-63778186dd13)

### Description and steps to reproduce [Required]

Start any game mode (campaign or multiplayer)
select any weapon that does has zoom (pistol, sniper, rocket) 
press zoom button and the background turns into a white transparent

![image](https://github.com/user-attachments/assets/fe662d3e-129c-4794-a657-901692517008)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1280*1024

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/user-attachments/assets/e6b29bbf-f36d-44ec-9c7f-12f6908bb386)

**Comment by Felipe-Intel** [comment]
@alucard1792 I am affraid this is not the version included in Halo: Master Chief Collection, is it? Please detail what version you have and if it has any special instructions for installing/running. At least in Halo: MCC the zoom looks the same in Arc and other non-Intel GPUs. Please check the screenshots attached (this is at the beginning of the campaing). 
Also please attach the txt file generated by SSU. 

Arc
![Arc](https://github.com/user-attachments/assets/c926da22-928f-49fd-9890-c3b2e5e8b5d6)


Nvidia
![NV](https://github.com/user-attachments/assets/7969713b-a286-4db7-b05e-85ba5f00e056)

**Comment by alucard1792** [comment]
Hi Felipe, thanks for your support. 
The version of Halo: Combat Evolved that has the bug is not included in the Halo: Master Chief Collection but is from the original launch of Halo: Combat Evolved and Halo: Custom Edition in 2003.
If you need more information, please let me know.

**Comment by Felipe-Intel** [comment]
@alucard1792 Our priority is to target the most popular games and apps to focus our efforts on providing a high quality, stable experience for the broadest set of users. Unfortunately we can’t accommodate your request at this time for this specific title. Our recommendation is to use the latest version of the game (included with the Halo Masterchief Collection), which has been remastered and works well with modern graphics solutions and doesn't show the issue described. I'm going to close this ticket (you can still comment on this thread).

**Comment by alucard1792** [comment]
Hi Felipe, sorry to ask you this in this thread, but can I post about graphics glitches from emulators like Ryujinx, RPCS3, Xenia, etc.?

**Comment by Felipe-Intel** [comment]
@alucard1792 no worries. For your reference, you can post general questions you may have about our products in one of [our communities](https://community.intel.com/t5/Gaming-Forums/ct-p/gaming-community) (choose the appropriate one), or by opening a ticket with [customer service](https://www.intel.com/content/www/us/en/support.html). 
Now to your question: you should communicate with mod or emulator developer and ask them to submit the case directly in:
[Developing Games on Intel Graphics](https://community.intel.com/t5/Developing-Games-on-Intel/bd-p/developing-games-graphics) or
[IGCIT GitHub Support](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues)
Please note emulator developer should share raw code to isolate issue which will be debugged and analyzed. This is code that could be run without the emulator and focuses its functionality on the issue reproduction.

**Comment by Pawlicker** [comment]
2026, the same bug is still happening but if anyone is having this bug still, dxvk will fix it.
