### ISSUE TITLE
Escape from Tarkov: Arena - Flashing Lights

### ISSUE THREAD

**Issue by Kawamaha** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#845]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Escape from Tarkov: Arena

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

BSG Launcher

### Processor / Processor Number [Required]

Intel i5-13600K

### Graphic Card [Required]

Intel Arc A750

### GPU Driver Version [Required]

32.0.101.6077

### Other GPU Driver version

32.0.101.6078

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 11 24H2

### Intel System Support Utility report

--

### Description and steps to reproduce [Required]

Old issue: https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/782

Active "tactical devices" such as a "TBL blue laser" and the setting "anisotropic filtering" set to "on" induces light flickering as seen in the videos.

https://github.com/user-attachments/assets/9ab02046-8d1b-4265-86a3-204880daf303

https://github.com/user-attachments/assets/6625b6af-bf16-466e-bd3e-75077eb1b5c4

To reproduce the issue "anisotropic filtering" has to be set to "on" in the graphics settings, then activate a "TBL blue laser" or an "AN/PEQ-15" on a gun and turn the device on.

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1920x1200

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![efta_settings](https://github.com/user-attachments/assets/3f73086f-87b4-4494-9fd7-c12a049105e4)

**Comment by benaskiburtas** [comment]
The lights flickering, especially on scopes and/or attachments seems similar to an issue I posted recently https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/836

**Comment by Zack-Intel** [comment]
Hi @Kawamaha and @benaskiburtas 

Thank you for submitting the ticket. I worked on reproducing the issue, and I believe I've been able to see the issue, though it doesn't seem as frequent so I wanted to ask a couple clarifying questions

1. Are you seeing the issue with any other lasers/light combinations?
2. How frequently do you see the issue? How much does it affect gameplay?
3. You mentioned "anisotropic filtering" had to be turned on. To clarify, does turning it off make the issue go away?

**Comment by Zack-Intel** [comment]
Hi @Kawamaha 

I haven't been seeing the issue since updating the game and graphics driver. Can you let me know if you still see the issue? If you do, I'll go back and run some further tests

**Comment by Zack-Intel** [comment]
Hi @Kawamaha 

I am glad to hear there is no more flickering for the light! If you would like me to see if the light is becoming more "white" on my end, I can begin testing, but we will have to open a separate case for that to see what next steps would be.
