### ISSUE TITLE
Call of duty Vanguard not rendering

### ISSUE THREAD

**Issue by IGCIT** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#85]
#### Checklist [README]

- [x] Device is not undervolted nor overclocked.
- [x] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs).
- [x] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Call of duty Vanguard

---
#### Game Platform [Required]
- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [x] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]
i7-1165g7

---
#### GPU Driver Version [Required]
- [x] 30.0.100.9894 (*latest*)
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [x] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [ ] Windows 11 (*Insider Preview*)
- [ ] Windows 10 21H2 (*Insider Preview*)
- [x] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (*Please specify your build number*)

---
#### Description and steps to reproduce [Required]

The game is not rendering almost everything but UI elements.
Menu and in-game have no graphics (white screen) or a bunch of lines and circles and some colors.

Main menu
![Capture](https://user-images.githubusercontent.com/76787191/133925881-36d0bb13-2b51-43fd-88d7-3f15c7ad3fd8.jpg)

in-game
![Capture2](https://user-images.githubusercontent.com/76787191/133925889-efcadff5-1b98-47ce-9bf2-65994468d392.PNG)

---
#### Device / Platform [Optional][Recommended]

GPD Win3

---
#### Game Settings [Optional][Recommended]

everything low/disabled

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---
#### Windows mini dump (*small memory dump*) (*if available*) [Optional][Recommended]

---

**Comment by mva94** [comment]
@IGCIT I'm going to send it right away to our intel discord group so they can acknowledge it right away .
Do you mind posting a few pics to speed up the process ?

**Comment by estebanr863** [comment]
Hi all,

This issue was reported internally and is already been worked on by our development team. I’ll keep you posted on when this is included in a driver release.
