### ISSUE TITLE
Laggy Scrolling (Especially when viewing 60fps YouTube videos) on Firefox while Hardware Acceleration ON

### ISSUE THREAD

**Issue by yippeeeyay** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#850]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Firefox

### Processor / Processor Number [Required]

Intel Core Ultra 7 155H

### Graphic Card [Required]

Intel Arc Integrated Graphics

### GPU Driver Version [Required]

32.0.101.6078_101.5736

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build [Required]

Windows 11 24H2

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/17176853/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Go to any YouTube video with 1080p 60fps as an option (for my test I used https://www.youtube.com/watch?v=bwA16cxe_SE) and scroll. Scrolling is also a bit jittery on normal webpages. Fixed if hardware acceleration is turned off.

https://github.com/user-attachments/assets/5a905b6e-3a9f-43f0-a42b-2f0a569bd0e1

### Device / Platform

ASUS Zenbook 14 UX3405MA_Q425MA

**Comment by Vivek-Intel** [comment]
@yippeeeyay thanks for reporting the issue. do you observe same issue in Chrome browser also and can you try launching Firefox in administrator mode and check if you still see the issue ?

**Comment by yippeeeyay** [comment]
@Vivek-Intel Hope you are doing well. I do not see the same issue in Chrome, the scrolling is smooth. I tried launching Firefox in administrator mode and the issue is unfortunately still present.

**Comment by Vivek-Intel** [comment]
Hi @yippeeeyay We do not have the exact laptop model that you have but we tried to replicate this issue with other i7 155H systems but could not reproduce or see any distinction in scrolling hardware acc on and off case.

Can you try enabling smooth scrolling and update firefox to latest if not already and also I see there had been similar issues reported by other graphics users ([link1](https://www.reddit.com/r/firefox/comments/pzu5od/why_is_firefox_slow_with_hardware_acceleration/) , [link2](https://support.mozilla.org/en-US/questions/1281801) as well so it could be the application issue so suggest you to report it to Mozila support as well.

**Comment by yippeeeyay** [comment]
@Vivek-Intel https://bugzilla.mozilla.org/show_bug.cgi?id=1909123 Here is a bugzilla thread with people who experience the same issue. I have enabled smooth scrolling and updated firefox but the issue persists. It is especially laggy when scrolling when 60 fps video is playing. Did you test using a 60fps video? For me it lags when scrolling and then becomes smooth after a minute or so. I think this is definitely a driver issue

**Comment by Squall-Leonhart** [comment]
lag when scrolling while video is playing is an OS or Browser issue, not a driver issue.
