### ISSUE TITLE
Forza Motorsport 2023 - one frame every 15 seconds rendering

### ISSUE THREAD

**Issue by goldenx86** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#853]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Forza Motorsport (2023)

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5 1240P

### Graphic Card [Required]

Iris Xe

### GPU Driver Version [Required]

32.0.101.6079_101.5736

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 11 24H2

### Intel System Support Utility report

[intel.txt](https://github.com/user-attachments/files/17248876/intel.txt)

### Description and steps to reproduce [Required]

Boot the game, the menu alone will render a frame every 10-30 seconds.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280x720, 1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Seems to be irrelevant, hard to test due to the time it takes to navigate the UI at that performance.

![{64DB1F31-0BD1-4852-BB2D-437475D328BC}](https://github.com/user-attachments/assets/bf681e65-8dac-442b-8d95-f5ee803e03af)

### Device / Platform name

Asus Vivobook X1502ZA

**Comment by goldenx86** [comment]
I hope you're able to provide a real reply for driver issues this time.

**Comment by EstebanIntel** [comment]
Hi @goldenx86,

The [Steam page for this game](https://store.steampowered.com/app/2440510/Forza_Motorsport/) lists as minimum graphics requirement: NVidia GTX 1060 or AMD RX 5500 XT. And the iGPU included with the 1240P is way less performant than any of the listed minimum required GPUs. So, unfortunately, this game is not expected to run well using only the iGPU included with the 1240P.

**Comment by goldenx86** [comment]
I'm aware of that, I'm not asking to get the GPU from 15 to 60 FPS magically.
The driver constantly resets the rendering each time it manages to render a frame, there's clearly a heavy bottleneck somewhere, a frame capture should easily reflect this.

Gen 12.1 is a much newer architecture than GCN4 or Pascal, it's on you people to make the driver perform well enough to work as expected on D3D12 loads, especially when the same ISA on ARC cards does the job well.

**Comment by goldenx86** [comment]
Got it, perfectly understandable points. I'll close the issue.

The between lines point here is that Gen 12.1 products are basically EoL, only 12.7 and higher gets any active development now. Gotta avoid companies that end support so shortly from now on.

**Comment by EstebanIntel** [comment]
@goldenx86 

That is not the case at all. We still support issues on Tiger Lake (TGL), Alder Lake (ADL), etc. However, a lot of these issues require work both from our side and from the game developer. And given our limited resources, we need to prioritize which issues we work on; same as the game developers. And issues where the game's requirements (which were set by the game developer for a reason) are not met, is highly unlikely to get any priority from both our team and the game developer. But issues on iGPUs from TGL, ADL, etc. on games and apps where these iGPUs do meet the minimum requirements, we will support.
