### ISSUE TITLE
Applications crashing randomly using Vulkan

### ISSUE THREAD

**Issue by LuffyMugiwara-remote** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#855]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Chiaki-ng and PxPlay

### Processor / Processor Number [Required]

11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz, 1498 Mhz, 4 Core(s), 8 Logical Processor(s)

### Graphic Card [Required]

Intel(R) Iris(R) Xe Graphics

### GPU Driver Version [Required]

32.0.101.6083_101.5736

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build [Required]

Other (Please specify)

### Other Windows build

22631

### Intel System Support Utility report

[intel.txt](https://github.com/user-attachments/files/17442486/intel.txt)

### Description and steps to reproduce [Required]

Running the applications listed below using Vulkan causes the application to crash to desktop randomly. The crash will occur 95% of the time within the hour. Very rarely it will not crash within a hour of play. I provided the links to the applications below. Also I have included an issue that I opened with the dev about the crashing. They think that is a driver bug. In that link also contains log files. 

I can provide any information that is needed.

Application: https://streetpea.github.io/chiaki-ng/    Issue: https://github.com/streetpea/chiaki-ng/issues/415
Application: https://github.com/streamingdv/PSPlay-Application-Hosting/releases

### Device / Platform

System Model	HP ENVY x360 Convertible 15m-es1xxx

**Comment by Felipe-Intel** [comment]
Hello @LuffyMugiwara-remote. Correct me if I'm wrong. These are not emulators but clients that connects to an actual Playstation console, right? 
Do you know or can you check if the crash happens with the app just open but not connected a PS and actually playing (just left it there "idling")? I ask because at the moment we don't have access to a PS console to where we can connect and test the operation of the app. 
Also, please check out this [guide on how to enable memory dumps](https://community.intel.com/t5/Intel-ARC-Graphics/Need-help-Reporting-a-bug-or-issue-with-Arc-GPU-PLEASE-READ-THIS/td-p/1494429?profile.language=en#:~:text=Crashing/freezing%20issues/BSOD%3A) so maybe you can attach here the dump created by the app during crash (if any). This can greatly help us.

**Comment by LuffyMugiwara-remote** [comment]
The chiaki-ng has crashed using the Vulkan decoder during a play session of about a half hour. These were the only dump files I was able to locate using the guide above. I had to put in Google Drive as the file size was too big.  I will now attempt to crash using the drd11va decoder on chiaki-ng.

https://drive.google.com/file/d/1jaAxJuRyrE_hKWbAWm7Xm3eOzUn5WR1T/view?usp=sharing, https://drive.google.com/file/d/1rJguW0hpAjHiBgDnzAKjdcHpUfbOzzuf/view?usp=sharing

**Comment by LuffyMugiwara-remote** [comment]
@Felipe-Intel The chiaki-ng has crashed using the drd11va decoder during a play session of about 5 minutes These were the only dump files I was able to locate using the guide above. I had to put in Google Drive as the file size was too big. 

Let me know if you need any other information or if there any else that you need me to preform.

Thanks for the help

https://drive.google.com/file/d/1T8SpiPXljA6yM8hrJrKNNP1IVeOHWssN/view?usp=drive_link

**Comment by LuffyMugiwara-remote** [comment]
@Felipe-Intel PxPlay has crashed using the Vulkan for both setting during a play session of about a 10 minutes. These were the only dump files I was able to locate using the guide above. I had to put in Google Drive as the file size was too big. 

https://drive.google.com/file/d/1Rdu7R4DKjdNqqjHMuNBSKxtEvro4q2xj/view?usp=drive_link

**Comment by LuffyMugiwara-remote** [comment]
@Felipe-Intel No problem. Yeah my laptop only has Iris Xe Graphics so that is the only graphics card that I have and I don't think i could add another one too it.

Also I did contact the the devs directly for both apps. They both said it sounds a graphic card issue. I have an issue opened with chiaki-ng (Issue: https://github.com/streetpea/chiaki-ng/issues/415) . They did also send me a debug build with symbols enabled. The code is also public as it open source. So debugging should be easier that way.

Let me know if you need anything from me or I can help in anyway

Thanks

**Comment by rmorera-intel** [comment]
Thanks for your cooperation. One last-thing: please test by doing a clean driver installation using DDU in safe mode and then install our latest WHQL driver [32.0.101.6129](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html). If the issue persist with this driver just let me know.

**Comment by LuffyMugiwara-remote** [comment]
@rmorera-intel Since the Iris Xe graphics card is integrated and there is no other graphics card on the system or a connected display. Would it be safe to run DDU?

**Comment by rmorera-intel** [comment]
Yes, the system will default to Microsoft Basic Display Adapter drivers so you'll still have video and the laptop will work.

**Comment by LuffyMugiwara-remote** [comment]
@rmorera-intel I ran DDU and installed the graphic driver and it didn't work. I'm still getting crashes.

Anything else you want me to try?

**Comment by rmorera-intel** [comment]
No, that would be all thanks for all your inputs.
I have asked our debug team to analyze the dump files, if I get any update I'll let you know.

**Comment by rmorera-intel** [comment]
@LuffyMugiwara-remote I received an update from our debug team. The dump showed the call stack that triggers the crash but a reproducible environment is needed to drive this investigation further. Since getting this setup (PS5 locally for each debug/dev team) is tricky on a multi-location work team so I was told this won't be prioritized. I know this isn't the news you wanted to hear.

If this gets picked up in the near future I'll re-open the report and update you here.
