### ISSUE TITLE
Implement VK_EXT_swapchain_maintenance1

### ISSUE THREAD

**Issue by Blisto91** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#856]
### Application [Required]

dxvk

### Processor / Processor Number [Required]

7950x

### Graphic Card [Required]

7900xtx & RTX 4080 (Intel GPU maybe in the future)

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build [Required]

Windows 11 24H2

### Describe the feature [Required]

While the main dxvk repository does not consider Windows a officially targeted platform it is still somewhat popular among various Windows users to use it with some games. Because of that some thoughts are still given to the platform and its main drivers, hence my request.

With time it would be a nice bonus for dxvk to be able to rely on VK_EXT_swapchain_maintenance1 being generally supported, but there are still some big drivers that haven't implemented it. Intel Windows being one if them i can see.
The Linux Intel Vulkan driver (ANV) have support for this extension so i hope you will consider adding it too in the Windows driver.

Best regards.

**Comment by Felipe-Intel** [comment]
Hello @Blisto91 Thanks for your recommendation. We will share this information with our driver development team so they can evaluate the feasibility of it. With that, I will close this ticket.
