### ISSUE TITLE
Did Intel just break overclocking on Arc in 101.6127? GPU clock will not go above 2400Mhz (stock) by any means.

### ISSUE THREAD

**Issue by removsarah** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#857]
### Checklist [README]

- [x] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Inapplicable

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

Inapplicable

### Processor / Processor Number [Required]

Intel Core i5-12600KF

### Graphic Card [Required]

SPARKLE Intel Arc A770 TITAN OC Edition 16G

### GPU Driver Version [Required]

32.0.101.6127_101.6044

### Rendering API [Required]

- [X] Vulkan
- [X] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9

### Windows Build [Required]

Windows 11 23H2

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/17500681/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Try to overclock the GPU, either through the Arc Control application or through 3rd party utilities such as Shamino's Arc OC Tool. While using the OC Lock feature (exposed from IGCL - https://intel.github.io/drivers.gpu.control-library/Control/api.html#ctloverclockgpulockset), the GPU clock gets capped at 2400Mhz (default frequency) even if setting it higher, voltage can be locked normally. Lowering the clock below 2400Mhz is also working. Regular offset mode (e.g. in Arc Control) doesn't seem to boost above 2400Mhz either, but I'm mostly familiar with OC Lock so I'm not 100% certain. Overclocking worked fine in 101.6083 driver version.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Inapplicable

### Device / Platform name

Asus Prime Z690M-PLUS D4

**Comment by Ilya-intel** [comment]
Hi @removsarah ,
Which tool do you use to track frequency?
I've just tested and got higher GPU Frequency after overclocking through Arc Control (see below).
Also, could you try remove the driver using DDU and then install it back again.
![Screenshot 2024-10-24 174603](https://github.com/user-attachments/assets/7a68e1eb-c258-4e14-bbb7-57258a7b70bd)

https://github.com/user-attachments/assets/b3187aa4-82b8-443a-b74d-c4083a0d32bd

**Comment by removsarah** [comment]
@Ilya-intel Hello, both Arc Control and GPU-Z don't show the clock increase beyond 2400Mhz with OC Lock, and the in-game performance does not change. I've tried DDUing in safe mode (again), that did not solve the issue.

While I can confirm that Offset Mode with your provided settings (30 Performance Boost, +15mV Voltage Offset) does boost a bit above 2400Mhz, that is not an acceptable solution, the whole reason why I bought an Arc GPU is to lock the clocks so I don't have to deal with the dynamic powersaving of modern AMD or Nvidia GPUs.

If that helps (and you don't want to use a 3rd party tool to try OC Lock to replicate the issue), I believe it's possible to make a small C++ application based on the code examples from IGCL API to consistently reproduce this.

(the OC tool is located here by the way https://skatterbencher.com/arc-oc-tool/)

**Comment by removsarah** [comment]
Issue persists after updating (with DDU in safe mode) to driver 32.0.101.6129

**Comment by Ilya-intel** [comment]
@removsarah 
Thanks for clarifying! I'll be working on replicating it and collecting logs.
I'll keep you updated in this thread.

**Comment by Ilya-intel** [comment]
Hey @removsarah ,
IGCL library was updated recently from 1.1 to 2.1 which means there were changes in some functions.
This topic is out of scope of this community, but I have 2 advises how to proceed further:
1. Contact developer of this Arc Tool app regarding updated IGCL.
and/or
2. Contact IGCL community directly and ask there: https://github.com/intel/drivers.gpu.control-library/issues?q=is%3Aissue+is%3Aopen

I apologize for our limited support here, but, again, this topic is outside the scope of this community.
BR, Ilya.

**Comment by removsarah** [comment]
@Ilya-intel Hello again, while I do understand that you don't provide support for the API here, this in fact seems to be a driver issue, unrelated to the IGCL API itself.

https://gist.github.com/removsarah/b0fe5b3385596fa4a70ef22c53eee3a7 here's a code gist (edited overclock sample app from your linked repository), on driver 32.0.101.6083 or older this actually sets the clock and voltage, and allows it to go beyond 2400Mhz (the sample sets it 50Mhz beyond default, in my case 2450Mhz). On newer drivers such as 32.0.101.6127 or 32.0.101.6129 this is capped at 2400Mhz. The functions still exist in the newer IGCL library, they're just broken.

**Comment by Ilya-intel** [comment]
Hi @removsarah,
The thing is that IGCL library comes within the graphics driver package so that's the reason why some updated functions from IGCL 2.1 might not work, with older drivers you are using IGCL 1.1.

**Comment by Ilya-intel** [comment]
I'm closing this thread since the issue described is not supported through this channel.
