### ISSUE TITLE
DirectX 11 driver weird behavior (performance)

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#860]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

3DMark: API Overhead feature test

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

intel Core i7-13700KF

### Graphic Card [Required]

intel Arc A770

### GPU Driver Version [Required]

32.0.101.6130_101.6048

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 11 23H2

### Intel System Support Utility report

[SSU_20241102.txt](https://github.com/user-attachments/files/17609409/SSU_20241102.txt)

### Description and steps to reproduce [Required]

I just retested the driver efficiency with the latest beta driver 6130 using 3DMark "API Overhead" feature test: 
![API overhead 6130](https://github.com/user-attachments/assets/90d3ac38-ac8b-4695-a3ff-c018075135e0)

I haven't done this test again since driver 5590 released in June, so I didn't really keep track of the progress of driver efficiency improvement. Here is the result with driver 5590: 
![API overhead 5590](https://github.com/user-attachments/assets/d42995f2-ec27-4195-9249-1008d0d219a3)

As you can see, the performance of DirectX 11 has improved a lot (27% uplift on single-thread). Great job dev team!👍

However, it is quite weird now that DX11 single-thread is faster than multi-thread, even though by merely a very small margin. Since the single-thread performance has gained such a big leap, I believe it is hopeful that the DX11 multi-thread performance can also get promising uplift if the dev team can dig deeper into it.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Irrelevant for this. Just click on the "RUN" button with default settings.

**Comment by Felipe-Intel** [comment]
Hello @Susie1818 thanks for bringing this up and for your continous feedback. We will share this information with our driver development team so they can evaluate it and determine the best course of action. With that, I will close this ticket. Feel free to reopen the issue and/or answer here in case you have further comments.
