### ISSUE TITLE
Dragon Age II DX11 Insta-crash

### ISSUE THREAD

**Issue by auroradarks** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#861]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Dragon Age II

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 7600

### Graphic Card [Required]

Arc 770

### GPU Driver Version [Required]

32.0.101.6130_101.6048

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 11 24H2

### Intel System Support Utility report

[ssulog.txt](https://github.com/user-attachments/files/17610536/ssulog.txt)

### Description and steps to reproduce [Required]

Game will make it to start menu, but crashes upon starting a new game.  Note that this will only occur when using DX11 as the renderer.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

3440x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

N/A

**Comment by Zack-Intel** [comment]
Hello @auroradarks 

I've been running some tests on different systems and configurations, and I'm still having some trouble being able to reproduce the issue. Can you clarify a few points for me to assist further:

1. Does the game crash immediately at new game startup, or do you have to play for a bit before the crash occurs?
2. Can you provide additional graphics settings within the game?
3. Are there any crash logs/error codes when the game crashes?

**Comment by auroradarks** [comment]
1. Basically as soon as you press the play button
2. None that were relevant, I cycled through dozens of them but the only
thing that fixed it was swapping to DX9 (medium settings).  Everything else
I could change freely.
3. Nothing, instant crash with no log.

**Comment by Zack-Intel** [comment]
Hi @auroradarks 

Thank you for the info. I'm still having trouble reproducing the issue on multiple systems I've tested on. There are a couple more questions I have that could assist me further:

1. Is this a regression issue? Was it seen when using older graphics drivers, both AMD and Intel?
2. Do you have details on if/how you utilize the AMD graphics vs the Intel Arc graphics, and if both graphics drivers for AMD and Intel are used?
3. Does loading the game through the EA app vs Steam change the effects of the issue?

**Comment by Zack-Intel** [comment]
Hi @auroradarks 

Can you let me know if you have any updates regarding the inquiries?

**Comment by Zack-Intel** [comment]
Hi @auroradarks 

I'm going to go ahead and close this case. If you are still running into issues and are able to follow up with the inquiries, feel free to reopen/open a new case and we can continue where we left off.
