### ISSUE TITLE
Is there a gpu driver for windows 11 24h2

### ISSUE THREAD

**Issue by Danjhop4** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#863]
### Application [Required]

N/a

### Processor / Processor Number [Required]

N/a

### Graphic Card [Required]

N/a

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build [Required]

Windows 11 24H2

### Other Windows build

N/a

### Describe the feature [Required]

Is there a new driver for the new driver model?

### Additional notes

N/a

**Comment by Felipe-Intel** [comment]
![image](https://github.com/user-attachments/assets/3b68e8d0-26f7-41c5-a463-9b5c6c02b564)

**Comment by Danjhop4** [comment]
> ![image](https://private-user-images.githubusercontent.com/101756820/383678225-3b68e8d0-26f7-41c5-a463-9b5c6c02b564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NjcyODksIm5iZiI6MTczMTc2Njk4OSwicGF0aCI6Ii8xMDE3NTY4MjAvMzgzNjc4MjI1LTNiNjhlOGQwLTI2ZjctNDFjNS1hNDYzLTliNWM2YzAyYjU2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxNDIzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjRjMGMxOTcyMWVjYWJiZmY4ZjU3MDQ1MWQ0ZTE2NmNkNTA1NTk3YTJhYzdjMGI5ZDdmYmI3OWJkMjA1M2U0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Akvd02tEkI9xubhbnFlU2846OeUxsBcBkMIj5En5EH0)

I mean via windows update not admin

**Comment by Danjhop4** [comment]
@Felipe-Intel not admin so custom driver installs are not a thing only windows update even if the newest driver has it it’s no good unless it’s on windows update too

**Comment by Felipe-Intel** [comment]
May I know which is the latest version you are seeing via Windows Update?

**Comment by Danjhop4** [comment]
Not had one for over a year not sure just outdated

**Comment by Danjhop4** [comment]
Not sure what version that's on my laptop on iPad right now

**Comment by Danjhop4** [comment]
@Felipe-Intel look above I replied

**Comment by Danjhop4** [comment]
11th gen i7 cpu not sure of model exactly @Felipe-Intel

**Comment by Felipe-Intel** [comment]
All Intel graphics drivers starting from version 32.0.101.5768 support for Windows 11 24H2. We make our graphics drivers available for download from our website.
 
Intel doesn't control which drivers Microsoft offers through Windows Update. Please Contact Microsoft for support on their products.

**Comment by Danjhop4** [comment]
You can't do that @Felipe-Intel only Intel can

**Comment by Danjhop4** [comment]
Also found the drivers from Reddit so I don't trust them @Felipe-Intel

**Comment by Danjhop4** [comment]
Could be malware @Felipe-Intel

**Comment by EstebanIntel** [comment]
@Danjhop4,

As Felipe mentioned, if you don't have access to install drivers on your own computer, you need to contact Microsoft for support.

Regarding our graphics drivers, all the ones marked as [WHQL Certified](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/whql-release-signature) are submitted to Microsoft as part of the certification process. And as you can see [here](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html), there are multiple WHQL certified drivers newer than version 32.0.1.5768; all of which support Windows 11 24H2.

**Comment by Danjhop4** [comment]
@EstebanIntel you need to tell Microsoft to do it I can't

**Comment by Danjhop4** [comment]
@EstebanIntel unless they are bundled in system updates for Intel not any info as to what they are I can't find a support document for what you want sure it does not exist

**Comment by EstebanIntel** [comment]
@Danjhop4,

Intel officially provides graphics driver in our website: [https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html). If you don't have access to install drivers on your own computer, you need to contact Microsoft for support, since that is a Windows issue, not an Intel issue.

Also, we don't control which drivers Microsoft offers through Windows Update, or when they offer them. We only provide them the drivers but is out of our control when they decide to push them.

**Comment by Danjhop4** [comment]
@EstebanIntel thats not the issue your a 3rd party as far as I can tell so I would not trust the downloads anyway just because you say it's official does not mean it is and Intel is responsible for publishing via official mean

**Comment by EstebanIntel** [comment]
@Danjhop4 What is more official than a driver directly from Intel from the Intel website?

**Comment by EstebanIntel** [comment]
@Danjhop4 

What is more official than a driver directly from Intel from the Intel website?

If you don't trust Intel enough to download an Intel driver from the Intel website, why even come to Intel for support?

**Comment by Danjhop4** [comment]
@EstebanIntel I only have your word it official the entire thing could be a scam being it's ground from Reddit and I am not admin only windows update can do it

**Comment by Danjhop4** [comment]
@EstebanIntel if it was official you would not try and force me to take such risk

**Comment by Danjhop4** [comment]
@EstebanIntel @Felipe-Intel why can't you do official stuff why force such a risk
