### ISSUE TITLE
Thread renamed when calling D3D11CreateDevice

### ISSUE THREAD

**Issue by forderud** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#875]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Reproducer attached

### Processor / Processor Number [Required]

12th Gen Intel(R) Core(TM) i7-1265U   1.80 GHz

### Graphic Card [Required]

Intel(R) Iris(R) Xe Graphics

### GPU Driver Version [Required]

32.0.101.6078

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build [Required]

Windows 10 22H2

### Intel System Support Utility report

[SSU_report.txt](https://github.com/user-attachments/files/18024011/SSU_report.txt)

### Description and steps to reproduce [Required]

Minimal C++ reproducer:
```
#include <d3d11.h>
#pragma comment(lib, "D3D11.lib")

int WINAPI wmain(int argc, wchar_t * argv[]) {
  const D3D_FEATURE_LEVEL desired_levels[] = { D3D_FEATURE_LEVEL_11_0 };
  D3D_FEATURE_LEVEL actual_level = D3D_FEATURE_LEVEL_9_1; // overwritten on device creation
  ID3D11Device* device = nullptr;
  ID3D11DeviceContext* context = nullptr;
  // will trigger renaming of the thread
  HRESULT hr = D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, D3D11_CREATE_DEVICE_BGRA_SUPPORT, desired_levels, ARRAYSIZE(desired_levels), D3D11_SDK_VERSION, &device, &actual_level, &context);
  if (FAILED(hr))
    abort();
}
```
Thread name _before_ calling `D3D11CreateDevice`:
![main-baseline](https://github.com/user-attachments/assets/da0bca67-8544-4ed2-a245-d3fdbd9b7e15)

Thread name _after_ calling `D3D11CreateDevice`:
![main-renamed](https://github.com/user-attachments/assets/c04c4639-6cf3-4a59-99f7-e06dc6a64194)

### Application / Windows logs

[DxDiag.txt](https://github.com/user-attachments/files/18023976/DxDiag.txt)

**Comment by Arturo-Intel** [comment]
Hello again @forderud 
I was not able to reproduce this issue on the latest driver
![image](https://github.com/user-attachments/assets/bb8fcda7-df5d-4904-ae10-e079eb388600)

Please update your driver and try again.
-- r2

**Comment by forderud** [comment]
Thank you for your quick response @Arturo-Intel.

I've now upgraded my driver to version 101.6314 as suggested and hereby confirm that the problem appear to have been fixed. Please therefore feel free to close the issue as fixed.
