### ISSUE TITLE
Grounded graphical glitch

### ISSUE THREAD

**Issue by pacoa-kdbg** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#88]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Grounded

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [X] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7 1165G7

### GPU Driver Version [Required]

- [X] 30.0.100.9894 (*latest*)
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [x] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 (*Insider Preview*)
- [ ] Windows 10 21H2 (*Insider Preview*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Description and steps to reproduce [Required]

Start the game
![image](https://user-images.githubusercontent.com/29181120/136645935-7bf939dd-9bb5-4809-b73f-d140f1e8d3b9.png)

The higher the quality settings the easier to reproduce

### Device / Platform

GPD WIN  3

**Comment by estebanr863** [comment]
Hi @pacoa-kdbg,

Can you please install the [latest driver](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) version and try again? We are not seen the issue on the latest drivers.

**Comment by estebanr863** [comment]
Hi @pacoa-kdbg,

Got the chance to test with the latest drivers?

**Comment by estebanr863** [comment]
Hi @mva94 @IGCIT @Valkirie, we are not seen this issue on the latest drivers and got no answer from @pacoa-kdbg. Can this be closed?

**Comment by pacoa-kdbg** [comment]
@estebanr863 
I can confirm that this issue is not present on latest driver
