### ISSUE TITLE
Lighting glithes in Forza Horizon 4

### ISSUE THREAD

**Issue by dFeoktistov** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#887]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Forza Horizon 4

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Core Ultra 7 258V

### Graphic Card [Required]

Arc 140V

### GPU Driver Version [Required]

32.0.101.6325_101.6252

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 11 24H2

### Intel System Support Utility report

[ssulog.txt](https://github.com/user-attachments/files/18137908/ssulog.txt)

### Description and steps to reproduce [Required]

Light glitches in a strange way on high graphics settings in Forza Horizon 4 at night. I've also tried low preset and bug became less noticeable, but didn't disappear completely.
https://github.com/user-attachments/assets/ca55bac7-4b52-47b0-a1fe-8df6331691de

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1680x1050

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

High preset with dynamic optimization
![1293830_6](https://github.com/user-attachments/assets/ae704ccc-cd1e-4bcf-a365-79b276969c14)
![1293830_7](https://github.com/user-attachments/assets/f4b43eeb-0381-41d0-85df-2188689fc694)

### Device / Platform name

Asus Zenbook S 14

**Comment by mujeeb-intel** [comment]
Hi @dFeoktistov going to try to reproduce this issue.

Can you please help me with the following:

1. Can the issue be reproduced at any time during the night time?
2. what type of graphic glitches. Like artifacts on the grass, sky or anywhere? did you happen to take any pic of it?
3. Do you also get the message upon starting the game that "your system does not meet the minimum requirement" and the game suggests to put every game settings to low.

**Comment by mujeeb-intel** [comment]
Hi @dFeoktistov thank you for providing the step by step instruction with the screenshots. I was able to test it on my own personal system and was able to replicate this issue. However, being that Forza horizon 4 already delisted from steam and Microsoft store, we can't pursue this case. I know this isn't the outcome we expected, but it's impossible to work on a game that is no longer available.

**Comment by dFeoktistov** [comment]
OK, thanks anyway.

**Comment by Squall-Leonhart** [comment]
The outcome is BS, if you have access to the game, use that access to the game to work out the issue and fix it, don't use copout excuses to not even try.
