### ISSUE TITLE
Please add Arc control's ‘Studio’ feature to Intel Graphics Software.

### ISSUE THREAD

**Issue by fuchaohan** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#889]
### Application [Required]

Intel Graphics Software

### Processor / Processor Number [Required]

intel i7 14700K

### Graphic Card [Required]

intel Arc A770

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build [Required]

Windows 11 23H2

### Describe the feature [Required]

![image](https://github.com/user-attachments/assets/5fda013b-95f1-41f8-b729-4229d04cdfa8)
Arc control's Capture and Virtual Devices has less impact on frame rate, better recording results.
Please move  to Intel Graphics Software.

**Comment by EstebanIntel** [comment]
Hi @fuchaohan,

Intel has made the tough decision to retire the Studio page and it’s feature for now in our graphics software. The reason behind this decision is the features within the Studio page had very low user usage, and many features within the Studio page are supported by great third party software today like OBS, Steam, Windows GameBar etc. We may consider bringing back these features in the future if demand is high.

**Comment by FabriceDelahaij** [comment]
They should bring it back to life.
