### ISSUE TITLE
Driver overhead is still a huge problem with Battlemage.

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#896]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

3DMark: API Overhead feature test

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

intel Core i7-13700KF

### Graphic Card [Required]

intel Arc B580

### GPU Driver Version [Required]

32.0.101.6325_101.6252

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 11 23H2

### Intel System Support Utility report

[SSU_20241218.txt](https://github.com/user-attachments/files/18170140/SSU_20241218.txt)

### Description and steps to reproduce [Required]

I just tested the driver efficiency on the new B580:

![Screenshot (37)](https://github.com/user-attachments/assets/cde98b1e-ed46-4e04-8539-87c3a8b13202)

DX12 and Vulkan efficiency are both roughly only 50% compared to the Alchemist:

![Screenshot (33)](https://github.com/user-attachments/assets/216db636-a11d-4737-b79e-dc33d8334013)

I guess this is due to the PCIe x8 interface resulting in half bandwidth between the GPU and the CPU. However, even if the interface bandwidth had not been cut down by half, we can multiply the B580's scores by 2, and then the driver software doesn't seem to have improvement over Alchemist at all. This is quite disappoiting. You know, Nvidia's GPU get 400% scores compared to the Arc GPU in this test, and AMD's GPU get even higher score.

Briefly speaking, the B580, despite being faster and more power efficient than an A770,  is even more unfriendly to older CPUs and platforms. It is even less suitable than an A770 to be taken as an upgrade option for older systems.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Irrelevant for this. Just click on the "RUN" button with default settings.

**Comment by Arturo-Intel** [comment]
@Susie1818 Thanks for sharing this data. 
Please use a newer benchmark tool. In the following link you'll see the reasons why its information is not reliable anymore https://store.steampowered.com/app/407080/3DMark_API_Overhead_feature_test/)].
 
Looking forward to seeing your results with a newer tool, :)
-- r2

**Comment by Susie1818** [comment]
@Arturo-Intel 

Apparently you have misunderstood the message you quoted. It doesn't by any means say "its information is not reliable anymore." What the message means is:

The purpose of this test (back then when developed) was to exihibit the big advantage of the next-gen API (DX12 and Vulkan) over the older API (DX11) - being way more efficient and thus can issue almost ten times more draw calls per second. After so many years since DX12 and Vulkan were released, modern GPUs and CPUs have evolved so much to an extent that the inefficiency of DX11 is not really a concern anymore.
======

Back to reality, DX11 performance is indeed not a concern anymore in most cases on today's AMD and Nvidia GPUs paired with today's CPUs. Therefore, generally speaking, you don't need this particular "API overhead test" to exhibit or to prove that you should deprecate DX11 and embrace DX12/Vulkan. Nowadays, game developers can freely choose DX11 for their works (eg. Baldur's Gate 3) because DX11 performance, even though still much slower than DX12/Vulkan, is no longer a deal breaker with modern hardware.

HOWEVER, the purpose we use this test here is not to persuade developers to use DX12/Vulkan. We use this test here is to show that Arc GPU has a very noticeable driver inefficiency (compared to Nvidia and AMD products) that has dwelled into a territory where it is likely to do harm to game performance because the number of draw calls per second is terribly low. And, for the past two years, we early adopters of the Arc GPU have been through and have shown you many concrete examples. We sacrificed our time to endure the bugs and report the issues to support the first-gen Arc and voluntarily helped you develop your GPU product. Don't fool me around like I don't know what I am talking about.

The test results ARE reliable. If you want your product to be successful, learn humbly from it and try hard to improve.

**Comment by Arturo-Intel** [comment]
Hey @Susie1818, 

I got your point, but unfortunately this case with this tool and all the info you shared, has been shared to our dev team already for Arc A-Series and the process couldn't continue because the tool is discontinued/not supported. 

# This test is no longer supported.

If you manage to get a tool for overhead that is supported by an active developer that would help us a lot to continue the process.

The collaboration and feedback we have had from this community is invaluable and we appreciate it a lot. 
Thanks again for the explanation. You and me, both, want the best for this product. 
Lastly, remember **we are a professional and humble community. Let's keep it that way**

-- r2

**Comment by Susie1818** [comment]
@Arturo-Intel 

I don't think it's a bug that the Arc driver does something wrong and thus resulting in unexpected behavior only in this particular test. 

Your emphasis on the fact that this test is no longer supported seems to view this benchmark result as a bug and thus needs mutual collaborations with 3DMark devs to fix it. So, you believe overall there is nothing wrong with the Arc driver, and this benchmark result is just misleading.

I don't think our goal here is to get a beautiful high score in this particular test and through collaboration with the devs of 3DMark you guys can figure out what's wrong with this program's algorithm/methodology running on an Arc GPU and then you can patch out the bug, either on the driver side or on the app side or on both sides. I don't think this is the case. My purpose is not to get a good score in this test, and I don't think any driver should be optimized for any single benchmark tool in the first place.

That being said, the results were mere indications that Arc GPU development is playing safe and put too many things done by the software. AMD Polaris architecture had similar issues, but they eventually overhauled the whole architecture.

**Comment by Arturo-Intel** [comment]
@Susie1818 
I totally agree that this is something that needs to be reviewed. But as I mentioned before, this case is already in our scope (since ACM) and now BMG is having similar symptoms. 

We are doing all in our power to push this further, but it seems that the only way to push it is if a 3DMark dev (or any other dev) comes to us and make pressure. 

Thats why I was asking you for a) newer supported overhead bench and/or b) a way to contact the devs to work with them.
This is not the first time we (as support team) encounter this type of cases and for our experience having a developer behind the case will make things easier.

That being said, I will confirm when the case changes to pending to under research, and if I have any news 'll let you know.
BTW, we are not diminishing your knowledge and comments; we appreciate them a lot. Any feedback is good feedback.

In the meantime, I'll proceed to close this case. Thanks again
--r2

**Comment by Susie1818** [comment]
@Arturo-Intel 

I get your point now, but unfortunately, as I mentioned above, the original purpose of this test was not to reveal a GPU's problem but to exhibit the drastic difference between DX11 and DX12/Vulkan. Because of this, 3DMark devs have no further interests in this feature test because the purpose is no longer valid nor needed. 

I have already communicated with 3DMark devs via Steam forum and thus the answer was it.
