### ISSUE TITLE
Burnout Paradise Remastered black screen

### ISSUE THREAD

**Issue by IGCIT** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#9]
#### Game _[Required]_
Burnout Paradise Remastered (Origin store)

---
#### CPU _[Required]_
i5-1035g7

---
#### GPU Driver Version _[Required]_
9126

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_: DirectX

**API Version** _(example DirectX 12)_: 11

---
#### Windows Build Number _[Required]_
19042 (20H2)

---
#### Description _[Required]_
After a few minutes of gameplay, the screen goes black.
Game is still running in background

---
#### Steps To Reproduce _[Required]_
* Add -skipvideos boot argument (yeah, this is broken too)
* Boot the game
* Select a car
* Play for a few minutes (usually 2-5 or less)

---
#### Screenshots _[Optional]_

---
#### Notes _[Optional]_
probably known issue, but still there.

**Comment by Valkirie** [comment]
Issue can be reproduced on Intel side.

**Comment by IGCIT** [comment]
update

driver 9313 - now black screen and crash

**Comment by mva94** [comment]
@IGCIT is that still a thing on driver 9955?

**Comment by IGCIT** [comment]
yes

**Comment by estebanr863** [comment]
Hi @IGCIT,

During our debugging process, we found the root cause of this issue to be the Denuvo DRM causing the game to crash. The fix for this needs to come from the game developer. But been this an older game, it’s very unlikely the developer will invest time on this.

**Comment by IGCIT** [comment]
thanks for the update.

i'll leave this here, as a note, for those like me, who bought the game and cannot get a refound:

this game can be played on Intel GPUs in Linux with Lutris (tested on lutris wine 5.7)
