### ISSUE TITLE
Marvel’s Guardians of The Galaxy Crash

### ISSUE THREAD

**Issue by DjXtom** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#90]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Marvel’s Guardians of The Galaxy

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other (please specify)

### Processor / Processor Number [Required]

I7 1165

### GPU Driver Version [Required]

- [X] 30.0.100.9955 (*latest*)
- [X] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11
- [ ] Windows 10 21H2 (*Insider Preview*)
- [X] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Description and steps to reproduce [Required]

Crash at launch with the message: “ dx12 adapter not found”

### Device / Platform

GPD win 3

**Comment by ruineka** [comment]
This game does not work on my OneXPlayer using the Iris Xe Graphics as well, it says dx12 adapter not found. Tested using Windows 10 and using Proton on Pop 21.04 Linux.

**Comment by KaeAlSa** [comment]
Same issue in my onexplayer. Latest version of windows 10 and the new 1191 driver tested.

**Comment by pacoa-kdbg** [comment]
Still a valid issue?

**Comment by estebanr863** [comment]
Hi @DjXtom, @KaeAlSa and @pacoa-kdbg 

We were able to reproduce this issue and found that its root cause to be on the game side. We have already escalated this issue to the game developer, but now is up to them to fix the issue.

**Comment by jfavelar** [comment]
Seem to be fixed, but there are different graphical issues now 

https://www.youtube.com/watch?v=FkTPeHTY9rE&t=615s

(not my video )

**Comment by pacoa-kdbg** [comment]
Looks like crash is not present anymore, but there are some graphical issues

https://www.youtube.com/watch?v=FkTPeHTY9rE&t=615s

**Comment by estebanr863** [comment]
Hi @DjXtom and @pacoa-kdbg,

Issues on this game have been root caused to game bugs. We escalated the issues to the game's developer, but the informed us that they will not be working on this game any longer, so issues will not be resolved.
