### ISSUE TITLE
Tom Clancy's Ghost Recon Breakpoint: Vulkan crash and Dx11 glitches

### ISSUE THREAD

**Issue by IGCIT** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#91]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Tom Clancy's Ghost Recon Breakpoint

### Game Platform [Required]

- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [X] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-1035g7

### GPU Driver Version [Required]

- [X] 30.0.100.9955 (*latest*)
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*Insider Preview*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Description and steps to reproduce [Required]

i don't own the game, but it is free for this weekend.

Vulkan crashes on boot, no error or message is shown.

Dx11 has lots of glitches, almost everything is missing.

![Screenshot (5)](https://user-images.githubusercontent.com/76787191/140368341-2c4d17ce-1151-48fd-b46d-f5f9367bcaf3.png)

### Device / Platform

GPD Win Max 2020

### Game Settings

![Screenshot (6)](https://user-images.githubusercontent.com/76787191/140368375-23b6bb7a-5bd2-4a84-847b-84aabfdbe683.png)
![Screenshot (7)](https://user-images.githubusercontent.com/76787191/140368387-8dcc8814-73e3-4ee0-9023-161d4fa8a02b.png)
![Screenshot (8)](https://user-images.githubusercontent.com/76787191/140368398-bfce2452-317a-4476-a46c-de4a4f8c9662.png)

**Comment by estebanr863** [comment]
Hi @IGCIT 

We were able to reproduce this issue and it has now been escalated to our driver development team. I just want to set the right expectation with you, as with the current workload, it may take from 3 to 6 months for a possible fix to be integrated into a release driver.

**Comment by estebanr863** [comment]
Hi @IGCIT,

We are not seen the issue anymore on the [latest driver](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) 30.0.101.1960. Can you please test it?

**Comment by IGCIT** [comment]
hi @estebanr863 

dx11 is fixed, vulkan version is still crashing on boot because anti-aliasing is enabled by default ( i saw other apps having crashes with AA on intel hw, so not sure this is game specific or something in intel hw)

**Comment by estebanr863** [comment]
Hi @IGCIT,

The app crash on Vulkan was found to have a root cause on a bug on the game side. The issue was escalated to the game developer, but they seem to have moved on to other games and will not be fixing this issue.
