### ISSUE TITLE
Steel Division 2 runs at single digit FPS with any graphical preset other than very low.

### ISSUE THREAD

**Issue by Azonnali** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#914]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Steel Division 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 5600x

### Graphic Card [Required]

Intel Arc A 770 16GB

### GPU Driver Version [Required]

32.0.101.6325_101.6252

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 11 24H2

### Intel System Support Utility report

[Report 20241222.txt](https://github.com/user-attachments/files/18221409/Report.20241222.txt)

### Description and steps to reproduce [Required]

Start the game. Select any graphical preset other than very low. Go into a game (even tutorial works). 

The game is not even giving me 10 FPS in most cases and the GPU hangs out at 50 Watts of power draw. On the ultra setting the terrain becomes corrupted as an added bonus. 

Interestingly enough after I tried different settings, I gave DXVK a go. Still the same result. Same FPS with everything other than very low while very low gave me 400 FPS consistently. 

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1440p

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Set the preset to very low for performance. 

Change literally any setting to get single digit FPS.

**Comment by Felipe-Intel** [comment]
Hello @Azonnali this is a known issue on Intel A-Series Graphics Cards
