### ISSUE TITLE
Watch Dogs Crashes on 1069

### ISSUE THREAD

**Issue by beenees** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#96]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Wactch Dogs

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i7 1165 g7

### GPU Driver Version [Required]

- [X] 30.0.101.1069 (*latest*)
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11
- [ ] Windows 10 21H2 (*Insider Preview*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Description and steps to reproduce [Required]

Game loads to menu but crashes immediately after the game is loaded up from save, reverting back to 9955 solves the issue.

### Device / Platform

GPD Win 3

### Game Settings

Medium setting

**Comment by estebanr863** [comment]
Hi @beenees 

Can you please try with the [lastest drivers](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html). We are no seen the issue on driver version 30.0.101.1340.

**Comment by estebanr863** [comment]
Hi @IGCIT @Valkirie @mva94 

Any of you own this game and can help test it with the latest drivers?

**Comment by mva94** [comment]
@estebanr863 hey 
Yes I confirmed a while back it was fixed , 
Sorry I forgot to close the issue
